/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhBanners extends org.jooq.impl.TableImpl<com.everhomes.server.schema.tables.records.EhBannersRecord> {

	private static final long serialVersionUID = -1213715715;

	/**
	 * The singleton instance of <code>ehcore.eh_banners</code>
	 */
	public static final com.everhomes.server.schema.tables.EhBanners EH_BANNERS = new com.everhomes.server.schema.tables.EhBanners();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.everhomes.server.schema.tables.records.EhBannersRecord> getRecordType() {
		return com.everhomes.server.schema.tables.records.EhBannersRecord.class;
	}

	/**
	 * The column <code>ehcore.eh_banners.id</code>. id of the record
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhBannersRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "id of the record");

	/**
	 * The column <code>ehcore.eh_banners.namespace_id</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhBannersRecord, java.lang.Integer> NAMESPACE_ID = createField("namespace_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>ehcore.eh_banners.appId</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhBannersRecord, java.lang.Long> APPID = createField("appId", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>ehcore.eh_banners.banner_location</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhBannersRecord, java.lang.String> BANNER_LOCATION = createField("banner_location", org.jooq.impl.SQLDataType.VARCHAR.length(2048), this, "");

	/**
	 * The column <code>ehcore.eh_banners.banner_group</code>. the type to filter item when querying: GA, BIZ, PM, GARC, GANC, GAPS
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhBannersRecord, java.lang.String> BANNER_GROUP = createField("banner_group", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false).defaulted(true), this, "the type to filter item when querying: GA, BIZ, PM, GARC, GANC, GAPS");

	/**
	 * The column <code>ehcore.eh_banners.scope_code</code>. 0: all, 1: community, 2: city, 3: user
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhBannersRecord, java.lang.Byte> SCOPE_CODE = createField("scope_code", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this, "0: all, 1: community, 2: city, 3: user");

	/**
	 * The column <code>ehcore.eh_banners.scope_id</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhBannersRecord, java.lang.Long> SCOPE_ID = createField("scope_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>ehcore.eh_banners.name</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhBannersRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>ehcore.eh_banners.vendor_tag</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhBannersRecord, java.lang.String> VENDOR_TAG = createField("vendor_tag", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>ehcore.eh_banners.poster_path</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhBannersRecord, java.lang.String> POSTER_PATH = createField("poster_path", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>ehcore.eh_banners.action_type</code>. according to document
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhBannersRecord, java.lang.Byte> ACTION_TYPE = createField("action_type", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this, "according to document");

	/**
	 * The column <code>ehcore.eh_banners.action_data</code>. the parameters depend on item_type, json format
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhBannersRecord, java.lang.String> ACTION_DATA = createField("action_data", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "the parameters depend on item_type, json format");

	/**
	 * The column <code>ehcore.eh_banners.start_time</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhBannersRecord, java.sql.Timestamp> START_TIME = createField("start_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ehcore.eh_banners.end_time</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhBannersRecord, java.sql.Timestamp> END_TIME = createField("end_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ehcore.eh_banners.status</code>. 0: closed, 1: waiting for confirmation, 2: active
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhBannersRecord, java.lang.Byte> STATUS = createField("status", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this, "0: closed, 1: waiting for confirmation, 2: active");

	/**
	 * The column <code>ehcore.eh_banners.order</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhBannersRecord, java.lang.Integer> ORDER = createField("order", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>ehcore.eh_banners.creator_uid</code>. record creator user id
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhBannersRecord, java.lang.Long> CREATOR_UID = createField("creator_uid", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "record creator user id");

	/**
	 * The column <code>ehcore.eh_banners.create_time</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhBannersRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ehcore.eh_banners.delete_time</code>. mark-deletion policy, historic data may be valuable
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhBannersRecord, java.sql.Timestamp> DELETE_TIME = createField("delete_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "mark-deletion policy, historic data may be valuable");

	/**
	 * The column <code>ehcore.eh_banners.scene_type</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhBannersRecord, java.lang.String> SCENE_TYPE = createField("scene_type", org.jooq.impl.SQLDataType.VARCHAR.length(64).defaulted(true), this, "");

	/**
	 * The column <code>ehcore.eh_banners.apply_policy</code>. 0: default, 1: override, 2: revert 3:customized
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhBannersRecord, java.lang.Byte> APPLY_POLICY = createField("apply_policy", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this, "0: default, 1: override, 2: revert 3:customized");

	/**
	 * The column <code>ehcore.eh_banners.update_time</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhBannersRecord, java.sql.Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * Create a <code>ehcore.eh_banners</code> table reference
	 */
	public EhBanners() {
		this("eh_banners", null);
	}

	/**
	 * Create an aliased <code>ehcore.eh_banners</code> table reference
	 */
	public EhBanners(java.lang.String alias) {
		this(alias, com.everhomes.server.schema.tables.EhBanners.EH_BANNERS);
	}

	private EhBanners(java.lang.String alias, org.jooq.Table<com.everhomes.server.schema.tables.records.EhBannersRecord> aliased) {
		this(alias, aliased, null);
	}

	private EhBanners(java.lang.String alias, org.jooq.Table<com.everhomes.server.schema.tables.records.EhBannersRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.everhomes.server.schema.Ehcore.EHCORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.everhomes.server.schema.tables.records.EhBannersRecord, java.lang.Long> getIdentity() {
		return com.everhomes.server.schema.Keys.IDENTITY_EH_BANNERS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.everhomes.server.schema.tables.records.EhBannersRecord> getPrimaryKey() {
		return com.everhomes.server.schema.Keys.KEY_EH_BANNERS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.everhomes.server.schema.tables.records.EhBannersRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.everhomes.server.schema.tables.records.EhBannersRecord>>asList(com.everhomes.server.schema.Keys.KEY_EH_BANNERS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.everhomes.server.schema.tables.EhBanners as(java.lang.String alias) {
		return new com.everhomes.server.schema.tables.EhBanners(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.everhomes.server.schema.tables.EhBanners rename(java.lang.String name) {
		return new com.everhomes.server.schema.tables.EhBanners(name, null);
	}
}
