/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhBinaryResources extends org.jooq.impl.TableImpl<com.everhomes.server.schema.tables.records.EhBinaryResourcesRecord> {

	private static final long serialVersionUID = 1451014329;

	/**
	 * The singleton instance of <code>ehcore.eh_binary_resources</code>
	 */
	public static final com.everhomes.server.schema.tables.EhBinaryResources EH_BINARY_RESOURCES = new com.everhomes.server.schema.tables.EhBinaryResources();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.everhomes.server.schema.tables.records.EhBinaryResourcesRecord> getRecordType() {
		return com.everhomes.server.schema.tables.records.EhBinaryResourcesRecord.class;
	}

	/**
	 * The column <code>ehcore.eh_binary_resources.id</code>. id of the record
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhBinaryResourcesRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "id of the record");

	/**
	 * The column <code>ehcore.eh_binary_resources.namespace_id</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhBinaryResourcesRecord, java.lang.Integer> NAMESPACE_ID = createField("namespace_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>ehcore.eh_binary_resources.checksum</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhBinaryResourcesRecord, java.lang.String> CHECKSUM = createField("checksum", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>ehcore.eh_binary_resources.store_type</code>. content store type
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhBinaryResourcesRecord, java.lang.String> STORE_TYPE = createField("store_type", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "content store type");

	/**
	 * The column <code>ehcore.eh_binary_resources.store_uri</code>. identify the store instance
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhBinaryResourcesRecord, java.lang.String> STORE_URI = createField("store_uri", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "identify the store instance");

	/**
	 * The column <code>ehcore.eh_binary_resources.content_type</code>. object content type
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhBinaryResourcesRecord, java.lang.String> CONTENT_TYPE = createField("content_type", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "object content type");

	/**
	 * The column <code>ehcore.eh_binary_resources.content_length</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhBinaryResourcesRecord, java.lang.Long> CONTENT_LENGTH = createField("content_length", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>ehcore.eh_binary_resources.content_uri</code>. object link info on storage
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhBinaryResourcesRecord, java.lang.String> CONTENT_URI = createField("content_uri", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "object link info on storage");

	/**
	 * The column <code>ehcore.eh_binary_resources.reference_count</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhBinaryResourcesRecord, java.lang.Long> REFERENCE_COUNT = createField("reference_count", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>ehcore.eh_binary_resources.create_time</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhBinaryResourcesRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ehcore.eh_binary_resources.access_time</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhBinaryResourcesRecord, java.sql.Timestamp> ACCESS_TIME = createField("access_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * Create a <code>ehcore.eh_binary_resources</code> table reference
	 */
	public EhBinaryResources() {
		this("eh_binary_resources", null);
	}

	/**
	 * Create an aliased <code>ehcore.eh_binary_resources</code> table reference
	 */
	public EhBinaryResources(java.lang.String alias) {
		this(alias, com.everhomes.server.schema.tables.EhBinaryResources.EH_BINARY_RESOURCES);
	}

	private EhBinaryResources(java.lang.String alias, org.jooq.Table<com.everhomes.server.schema.tables.records.EhBinaryResourcesRecord> aliased) {
		this(alias, aliased, null);
	}

	private EhBinaryResources(java.lang.String alias, org.jooq.Table<com.everhomes.server.schema.tables.records.EhBinaryResourcesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.everhomes.server.schema.Ehcore.EHCORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.everhomes.server.schema.tables.records.EhBinaryResourcesRecord> getPrimaryKey() {
		return com.everhomes.server.schema.Keys.KEY_EH_BINARY_RESOURCES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.everhomes.server.schema.tables.records.EhBinaryResourcesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.everhomes.server.schema.tables.records.EhBinaryResourcesRecord>>asList(com.everhomes.server.schema.Keys.KEY_EH_BINARY_RESOURCES_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.everhomes.server.schema.tables.EhBinaryResources as(java.lang.String alias) {
		return new com.everhomes.server.schema.tables.EhBinaryResources(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.everhomes.server.schema.tables.EhBinaryResources rename(java.lang.String name) {
		return new com.everhomes.server.schema.tables.EhBinaryResources(name, null);
	}
}
