/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhConfAccountHistories extends org.jooq.impl.TableImpl<com.everhomes.server.schema.tables.records.EhConfAccountHistoriesRecord> {

	private static final long serialVersionUID = -1613597790;

	/**
	 * The singleton instance of <code>ehcore.eh_conf_account_histories</code>
	 */
	public static final com.everhomes.server.schema.tables.EhConfAccountHistories EH_CONF_ACCOUNT_HISTORIES = new com.everhomes.server.schema.tables.EhConfAccountHistories();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.everhomes.server.schema.tables.records.EhConfAccountHistoriesRecord> getRecordType() {
		return com.everhomes.server.schema.tables.records.EhConfAccountHistoriesRecord.class;
	}

	/**
	 * The column <code>ehcore.eh_conf_account_histories.id</code>. id
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhConfAccountHistoriesRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "id");

	/**
	 * The column <code>ehcore.eh_conf_account_histories.enterprise_id</code>. enterprise_id
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhConfAccountHistoriesRecord, java.lang.Long> ENTERPRISE_ID = createField("enterprise_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "enterprise_id");

	/**
	 * The column <code>ehcore.eh_conf_account_histories.expired_date</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhConfAccountHistoriesRecord, java.sql.Timestamp> EXPIRED_DATE = createField("expired_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ehcore.eh_conf_account_histories.status</code>. 0: inactive, 1: active, 2: locked
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhConfAccountHistoriesRecord, java.lang.Byte> STATUS = createField("status", org.jooq.impl.SQLDataType.TINYINT, this, "0: inactive, 1: active, 2: locked");

	/**
	 * The column <code>ehcore.eh_conf_account_histories.account_category_id</code>. refernece to the id of eh_conf_account_categories
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhConfAccountHistoriesRecord, java.lang.Long> ACCOUNT_CATEGORY_ID = createField("account_category_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "refernece to the id of eh_conf_account_categories");

	/**
	 * The column <code>ehcore.eh_conf_account_histories.account_type</code>. 0: none, 1: trial, 2: normal
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhConfAccountHistoriesRecord, java.lang.Byte> ACCOUNT_TYPE = createField("account_type", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this, "0: none, 1: trial, 2: normal");

	/**
	 * The column <code>ehcore.eh_conf_account_histories.owner_id</code>. the user id who use the account, reference to the id of eh_users
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhConfAccountHistoriesRecord, java.lang.Long> OWNER_ID = createField("owner_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "the user id who use the account, reference to the id of eh_users");

	/**
	 * The column <code>ehcore.eh_conf_account_histories.own_time</code>. the time when the user own the account
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhConfAccountHistoriesRecord, java.sql.Timestamp> OWN_TIME = createField("own_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "the time when the user own the account");

	/**
	 * The column <code>ehcore.eh_conf_account_histories.deleter_uid</code>. deleter id
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhConfAccountHistoriesRecord, java.lang.Long> DELETER_UID = createField("deleter_uid", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "deleter id");

	/**
	 * The column <code>ehcore.eh_conf_account_histories.delete_time</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhConfAccountHistoriesRecord, java.sql.Timestamp> DELETE_TIME = createField("delete_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ehcore.eh_conf_account_histories.creator_uid</code>. the user id who create the account
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhConfAccountHistoriesRecord, java.lang.Long> CREATOR_UID = createField("creator_uid", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "the user id who create the account");

	/**
	 * The column <code>ehcore.eh_conf_account_histories.create_time</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhConfAccountHistoriesRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ehcore.eh_conf_account_histories.operator_uid</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhConfAccountHistoriesRecord, java.lang.Long> OPERATOR_UID = createField("operator_uid", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>ehcore.eh_conf_account_histories.operation_type</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhConfAccountHistoriesRecord, java.lang.String> OPERATION_TYPE = createField("operation_type", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ehcore.eh_conf_account_histories.process_details</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhConfAccountHistoriesRecord, java.lang.String> PROCESS_DETAILS = createField("process_details", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>ehcore.eh_conf_account_histories.operate_time</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhConfAccountHistoriesRecord, java.sql.Timestamp> OPERATE_TIME = createField("operate_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ehcore.eh_conf_account_histories.namespace_id</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhConfAccountHistoriesRecord, java.lang.Integer> NAMESPACE_ID = createField("namespace_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>ehcore.eh_conf_account_histories</code> table reference
	 */
	public EhConfAccountHistories() {
		this("eh_conf_account_histories", null);
	}

	/**
	 * Create an aliased <code>ehcore.eh_conf_account_histories</code> table reference
	 */
	public EhConfAccountHistories(java.lang.String alias) {
		this(alias, com.everhomes.server.schema.tables.EhConfAccountHistories.EH_CONF_ACCOUNT_HISTORIES);
	}

	private EhConfAccountHistories(java.lang.String alias, org.jooq.Table<com.everhomes.server.schema.tables.records.EhConfAccountHistoriesRecord> aliased) {
		this(alias, aliased, null);
	}

	private EhConfAccountHistories(java.lang.String alias, org.jooq.Table<com.everhomes.server.schema.tables.records.EhConfAccountHistoriesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.everhomes.server.schema.Ehcore.EHCORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.everhomes.server.schema.tables.records.EhConfAccountHistoriesRecord> getPrimaryKey() {
		return com.everhomes.server.schema.Keys.KEY_EH_CONF_ACCOUNT_HISTORIES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.everhomes.server.schema.tables.records.EhConfAccountHistoriesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.everhomes.server.schema.tables.records.EhConfAccountHistoriesRecord>>asList(com.everhomes.server.schema.Keys.KEY_EH_CONF_ACCOUNT_HISTORIES_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.everhomes.server.schema.tables.EhConfAccountHistories as(java.lang.String alias) {
		return new com.everhomes.server.schema.tables.EhConfAccountHistories(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.everhomes.server.schema.tables.EhConfAccountHistories rename(java.lang.String name) {
		return new com.everhomes.server.schema.tables.EhConfAccountHistories(name, null);
	}
}
