/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhConfAccountCategories extends org.jooq.impl.TableImpl<com.everhomes.server.schema.tables.records.EhConfAccountCategoriesRecord> {

	private static final long serialVersionUID = -1160297111;

	/**
	 * The singleton instance of <code>ehcore.eh_conf_account_categories</code>
	 */
	public static final com.everhomes.server.schema.tables.EhConfAccountCategories EH_CONF_ACCOUNT_CATEGORIES = new com.everhomes.server.schema.tables.EhConfAccountCategories();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.everhomes.server.schema.tables.records.EhConfAccountCategoriesRecord> getRecordType() {
		return com.everhomes.server.schema.tables.records.EhConfAccountCategoriesRecord.class;
	}

	/**
	 * The column <code>ehcore.eh_conf_account_categories.id</code>. id
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhConfAccountCategoriesRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "id");

	/**
	 * The column <code>ehcore.eh_conf_account_categories.channel_type</code>. 0: single, 1: multiple
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhConfAccountCategoriesRecord, java.lang.Byte> CHANNEL_TYPE = createField("channel_type", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this, "0: single, 1: multiple");

	/**
	 * The column <code>ehcore.eh_conf_account_categories.conf_type</code>. 0: none, 1: 25方仅视频, 2: 25方支持电话, 3: 100方仅视频, 4: 100方支持电话
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhConfAccountCategoriesRecord, java.lang.Byte> CONF_TYPE = createField("conf_type", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this, "0: none, 1: 25方仅视频, 2: 25方支持电话, 3: 100方仅视频, 4: 100方支持电话");

	/**
	 * The column <code>ehcore.eh_conf_account_categories.min_period</code>. the minimum count of months
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhConfAccountCategoriesRecord, java.lang.Integer> MIN_PERIOD = createField("min_period", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "the minimum count of months");

	/**
	 * The column <code>ehcore.eh_conf_account_categories.amount</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhConfAccountCategoriesRecord, java.math.BigDecimal> AMOUNT = createField("amount", org.jooq.impl.SQLDataType.DECIMAL.precision(10, 2), this, "");

	/**
	 * The column <code>ehcore.eh_conf_account_categories.namespace_id</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhConfAccountCategoriesRecord, java.lang.Integer> NAMESPACE_ID = createField("namespace_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>ehcore.eh_conf_account_categories</code> table reference
	 */
	public EhConfAccountCategories() {
		this("eh_conf_account_categories", null);
	}

	/**
	 * Create an aliased <code>ehcore.eh_conf_account_categories</code> table reference
	 */
	public EhConfAccountCategories(java.lang.String alias) {
		this(alias, com.everhomes.server.schema.tables.EhConfAccountCategories.EH_CONF_ACCOUNT_CATEGORIES);
	}

	private EhConfAccountCategories(java.lang.String alias, org.jooq.Table<com.everhomes.server.schema.tables.records.EhConfAccountCategoriesRecord> aliased) {
		this(alias, aliased, null);
	}

	private EhConfAccountCategories(java.lang.String alias, org.jooq.Table<com.everhomes.server.schema.tables.records.EhConfAccountCategoriesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.everhomes.server.schema.Ehcore.EHCORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.everhomes.server.schema.tables.records.EhConfAccountCategoriesRecord> getPrimaryKey() {
		return com.everhomes.server.schema.Keys.KEY_EH_CONF_ACCOUNT_CATEGORIES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.everhomes.server.schema.tables.records.EhConfAccountCategoriesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.everhomes.server.schema.tables.records.EhConfAccountCategoriesRecord>>asList(com.everhomes.server.schema.Keys.KEY_EH_CONF_ACCOUNT_CATEGORIES_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.everhomes.server.schema.tables.EhConfAccountCategories as(java.lang.String alias) {
		return new com.everhomes.server.schema.tables.EhConfAccountCategories(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.everhomes.server.schema.tables.EhConfAccountCategories rename(java.lang.String name) {
		return new com.everhomes.server.schema.tables.EhConfAccountCategories(name, null);
	}
}
