/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhDevices extends org.jooq.impl.TableImpl<com.everhomes.server.schema.tables.records.EhDevicesRecord> {

	private static final long serialVersionUID = -1777416782;

	/**
	 * The singleton instance of <code>ehcore.eh_devices</code>
	 */
	public static final com.everhomes.server.schema.tables.EhDevices EH_DEVICES = new com.everhomes.server.schema.tables.EhDevices();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.everhomes.server.schema.tables.records.EhDevicesRecord> getRecordType() {
		return com.everhomes.server.schema.tables.records.EhDevicesRecord.class;
	}

	/**
	 * The column <code>ehcore.eh_devices.id</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhDevicesRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>ehcore.eh_devices.device_id</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhDevicesRecord, java.lang.String> DEVICE_ID = createField("device_id", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

	/**
	 * The column <code>ehcore.eh_devices.platform</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhDevicesRecord, java.lang.String> PLATFORM = createField("platform", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>ehcore.eh_devices.product</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhDevicesRecord, java.lang.String> PRODUCT = createField("product", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ehcore.eh_devices.brand</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhDevicesRecord, java.lang.String> BRAND = createField("brand", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ehcore.eh_devices.device_model</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhDevicesRecord, java.lang.String> DEVICE_MODEL = createField("device_model", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ehcore.eh_devices.system_version</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhDevicesRecord, java.lang.String> SYSTEM_VERSION = createField("system_version", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ehcore.eh_devices.meta</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhDevicesRecord, java.lang.String> META = createField("meta", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>ehcore.eh_devices.create_time</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhDevicesRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * Create a <code>ehcore.eh_devices</code> table reference
	 */
	public EhDevices() {
		this("eh_devices", null);
	}

	/**
	 * Create an aliased <code>ehcore.eh_devices</code> table reference
	 */
	public EhDevices(java.lang.String alias) {
		this(alias, com.everhomes.server.schema.tables.EhDevices.EH_DEVICES);
	}

	private EhDevices(java.lang.String alias, org.jooq.Table<com.everhomes.server.schema.tables.records.EhDevicesRecord> aliased) {
		this(alias, aliased, null);
	}

	private EhDevices(java.lang.String alias, org.jooq.Table<com.everhomes.server.schema.tables.records.EhDevicesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.everhomes.server.schema.Ehcore.EHCORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.everhomes.server.schema.tables.records.EhDevicesRecord, java.lang.Long> getIdentity() {
		return com.everhomes.server.schema.Keys.IDENTITY_EH_DEVICES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.everhomes.server.schema.tables.records.EhDevicesRecord> getPrimaryKey() {
		return com.everhomes.server.schema.Keys.KEY_EH_DEVICES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.everhomes.server.schema.tables.records.EhDevicesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.everhomes.server.schema.tables.records.EhDevicesRecord>>asList(com.everhomes.server.schema.Keys.KEY_EH_DEVICES_PRIMARY, com.everhomes.server.schema.Keys.KEY_EH_DEVICES_U_EH_DEV_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.everhomes.server.schema.tables.EhDevices as(java.lang.String alias) {
		return new com.everhomes.server.schema.tables.EhDevices(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.everhomes.server.schema.tables.EhDevices rename(java.lang.String name) {
		return new com.everhomes.server.schema.tables.EhDevices(name, null);
	}
}
