/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhEnergyMeters extends org.jooq.impl.TableImpl<com.everhomes.server.schema.tables.records.EhEnergyMetersRecord> {

	private static final long serialVersionUID = 375046796;

	/**
	 * The singleton instance of <code>ehcore.eh_energy_meters</code>
	 */
	public static final com.everhomes.server.schema.tables.EhEnergyMeters EH_ENERGY_METERS = new com.everhomes.server.schema.tables.EhEnergyMeters();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.everhomes.server.schema.tables.records.EhEnergyMetersRecord> getRecordType() {
		return com.everhomes.server.schema.tables.records.EhEnergyMetersRecord.class;
	}

	/**
	 * The column <code>ehcore.eh_energy_meters.id</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhEnergyMetersRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>ehcore.eh_energy_meters.namespace_id</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhEnergyMetersRecord, java.lang.Integer> NAMESPACE_ID = createField("namespace_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>ehcore.eh_energy_meters.community_id</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhEnergyMetersRecord, java.lang.Long> COMMUNITY_ID = createField("community_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>ehcore.eh_energy_meters.name</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhEnergyMetersRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>ehcore.eh_energy_meters.meter_number</code>. meter number
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhEnergyMetersRecord, java.lang.String> METER_NUMBER = createField("meter_number", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "meter number");

	/**
	 * The column <code>ehcore.eh_energy_meters.meter_type</code>. 1:WATER, 2: ELECTRIC
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhEnergyMetersRecord, java.lang.Byte> METER_TYPE = createField("meter_type", org.jooq.impl.SQLDataType.TINYINT, this, "1:WATER, 2: ELECTRIC");

	/**
	 * The column <code>ehcore.eh_energy_meters.bill_category_id</code>. eh_energy_meter_categories id
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhEnergyMetersRecord, java.lang.Long> BILL_CATEGORY_ID = createField("bill_category_id", org.jooq.impl.SQLDataType.BIGINT, this, "eh_energy_meter_categories id");

	/**
	 * The column <code>ehcore.eh_energy_meters.service_category_id</code>. eh_energy_meter_categories id
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhEnergyMetersRecord, java.lang.Long> SERVICE_CATEGORY_ID = createField("service_category_id", org.jooq.impl.SQLDataType.BIGINT, this, "eh_energy_meter_categories id");

	/**
	 * The column <code>ehcore.eh_energy_meters.max_reading</code>. The maximum range of the meter
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhEnergyMetersRecord, java.math.BigDecimal> MAX_READING = createField("max_reading", org.jooq.impl.SQLDataType.DECIMAL.precision(10, 1), this, "The maximum range of the meter");

	/**
	 * The column <code>ehcore.eh_energy_meters.start_reading</code>. The initial reading of the meter
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhEnergyMetersRecord, java.math.BigDecimal> START_READING = createField("start_reading", org.jooq.impl.SQLDataType.DECIMAL.precision(10, 1), this, "The initial reading of the meter");

	/**
	 * The column <code>ehcore.eh_energy_meters.rate</code>. Calculate magnification
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhEnergyMetersRecord, java.math.BigDecimal> RATE = createField("rate", org.jooq.impl.SQLDataType.DECIMAL.precision(10, 2), this, "Calculate magnification");

	/**
	 * The column <code>ehcore.eh_energy_meters.price</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhEnergyMetersRecord, java.math.BigDecimal> PRICE = createField("price", org.jooq.impl.SQLDataType.DECIMAL.precision(10, 2), this, "");

	/**
	 * The column <code>ehcore.eh_energy_meters.cost_formula_id</code>. Cost calculation formula
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhEnergyMetersRecord, java.lang.Long> COST_FORMULA_ID = createField("cost_formula_id", org.jooq.impl.SQLDataType.BIGINT, this, "Cost calculation formula");

	/**
	 * The column <code>ehcore.eh_energy_meters.amount_formula_id</code>. Amount calculation formula
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhEnergyMetersRecord, java.lang.Long> AMOUNT_FORMULA_ID = createField("amount_formula_id", org.jooq.impl.SQLDataType.BIGINT, this, "Amount calculation formula");

	/**
	 * The column <code>ehcore.eh_energy_meters.last_read_time</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhEnergyMetersRecord, java.sql.Timestamp> LAST_READ_TIME = createField("last_read_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ehcore.eh_energy_meters.last_reading</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhEnergyMetersRecord, java.math.BigDecimal> LAST_READING = createField("last_reading", org.jooq.impl.SQLDataType.DECIMAL.precision(10, 1), this, "");

	/**
	 * The column <code>ehcore.eh_energy_meters.status</code>. 0: inactive, 1: waitingForApproval, 2: active
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhEnergyMetersRecord, java.lang.Byte> STATUS = createField("status", org.jooq.impl.SQLDataType.TINYINT, this, "0: inactive, 1: waitingForApproval, 2: active");

	/**
	 * The column <code>ehcore.eh_energy_meters.creator_uid</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhEnergyMetersRecord, java.lang.Long> CREATOR_UID = createField("creator_uid", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>ehcore.eh_energy_meters.create_time</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhEnergyMetersRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ehcore.eh_energy_meters.update_uid</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhEnergyMetersRecord, java.lang.Long> UPDATE_UID = createField("update_uid", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>ehcore.eh_energy_meters.update_time</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhEnergyMetersRecord, java.sql.Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ehcore.eh_energy_meters.owner_type</code>. the type of who own the price energy meter, enterprise, etc
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhEnergyMetersRecord, java.lang.String> OWNER_TYPE = createField("owner_type", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false).defaulted(true), this, "the type of who own the price energy meter, enterprise, etc");

	/**
	 * The column <code>ehcore.eh_energy_meters.owner_id</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhEnergyMetersRecord, java.lang.Long> OWNER_ID = createField("owner_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>ehcore.eh_energy_meters.calculation_type</code>. 0: standing charge tariff 固定费用, 1: block tariff 阶梯收费
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhEnergyMetersRecord, java.lang.Byte> CALCULATION_TYPE = createField("calculation_type", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this, "0: standing charge tariff 固定费用, 1: block tariff 阶梯收费");

	/**
	 * The column <code>ehcore.eh_energy_meters.config_id</code>. if setting_type is price and  have this value
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhEnergyMetersRecord, java.lang.Long> CONFIG_ID = createField("config_id", org.jooq.impl.SQLDataType.BIGINT, this, "if setting_type is price and  have this value");

	/**
	 * Create a <code>ehcore.eh_energy_meters</code> table reference
	 */
	public EhEnergyMeters() {
		this("eh_energy_meters", null);
	}

	/**
	 * Create an aliased <code>ehcore.eh_energy_meters</code> table reference
	 */
	public EhEnergyMeters(java.lang.String alias) {
		this(alias, com.everhomes.server.schema.tables.EhEnergyMeters.EH_ENERGY_METERS);
	}

	private EhEnergyMeters(java.lang.String alias, org.jooq.Table<com.everhomes.server.schema.tables.records.EhEnergyMetersRecord> aliased) {
		this(alias, aliased, null);
	}

	private EhEnergyMeters(java.lang.String alias, org.jooq.Table<com.everhomes.server.schema.tables.records.EhEnergyMetersRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.everhomes.server.schema.Ehcore.EHCORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.everhomes.server.schema.tables.records.EhEnergyMetersRecord> getPrimaryKey() {
		return com.everhomes.server.schema.Keys.KEY_EH_ENERGY_METERS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.everhomes.server.schema.tables.records.EhEnergyMetersRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.everhomes.server.schema.tables.records.EhEnergyMetersRecord>>asList(com.everhomes.server.schema.Keys.KEY_EH_ENERGY_METERS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.everhomes.server.schema.tables.EhEnergyMeters as(java.lang.String alias) {
		return new com.everhomes.server.schema.tables.EhEnergyMeters(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.everhomes.server.schema.tables.EhEnergyMeters rename(java.lang.String name) {
		return new com.everhomes.server.schema.tables.EhEnergyMeters(name, null);
	}
}
