/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhGroupVisibleScopes extends org.jooq.impl.TableImpl<com.everhomes.server.schema.tables.records.EhGroupVisibleScopesRecord> {

	private static final long serialVersionUID = 977636063;

	/**
	 * The singleton instance of <code>ehcore.eh_group_visible_scopes</code>
	 */
	public static final com.everhomes.server.schema.tables.EhGroupVisibleScopes EH_GROUP_VISIBLE_SCOPES = new com.everhomes.server.schema.tables.EhGroupVisibleScopes();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.everhomes.server.schema.tables.records.EhGroupVisibleScopesRecord> getRecordType() {
		return com.everhomes.server.schema.tables.records.EhGroupVisibleScopesRecord.class;
	}

	/**
	 * The column <code>ehcore.eh_group_visible_scopes.id</code>. id of the record
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhGroupVisibleScopesRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "id of the record");

	/**
	 * The column <code>ehcore.eh_group_visible_scopes.owner_id</code>. owner group id
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhGroupVisibleScopesRecord, java.lang.Long> OWNER_ID = createField("owner_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "owner group id");

	/**
	 * The column <code>ehcore.eh_group_visible_scopes.scope_code</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhGroupVisibleScopesRecord, java.lang.Byte> SCOPE_CODE = createField("scope_code", org.jooq.impl.SQLDataType.TINYINT, this, "");

	/**
	 * The column <code>ehcore.eh_group_visible_scopes.scope_id</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhGroupVisibleScopesRecord, java.lang.Long> SCOPE_ID = createField("scope_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>ehcore.eh_group_visible_scopes</code> table reference
	 */
	public EhGroupVisibleScopes() {
		this("eh_group_visible_scopes", null);
	}

	/**
	 * Create an aliased <code>ehcore.eh_group_visible_scopes</code> table reference
	 */
	public EhGroupVisibleScopes(java.lang.String alias) {
		this(alias, com.everhomes.server.schema.tables.EhGroupVisibleScopes.EH_GROUP_VISIBLE_SCOPES);
	}

	private EhGroupVisibleScopes(java.lang.String alias, org.jooq.Table<com.everhomes.server.schema.tables.records.EhGroupVisibleScopesRecord> aliased) {
		this(alias, aliased, null);
	}

	private EhGroupVisibleScopes(java.lang.String alias, org.jooq.Table<com.everhomes.server.schema.tables.records.EhGroupVisibleScopesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.everhomes.server.schema.Ehcore.EHCORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.everhomes.server.schema.tables.records.EhGroupVisibleScopesRecord> getPrimaryKey() {
		return com.everhomes.server.schema.Keys.KEY_EH_GROUP_VISIBLE_SCOPES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.everhomes.server.schema.tables.records.EhGroupVisibleScopesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.everhomes.server.schema.tables.records.EhGroupVisibleScopesRecord>>asList(com.everhomes.server.schema.Keys.KEY_EH_GROUP_VISIBLE_SCOPES_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.everhomes.server.schema.tables.records.EhGroupVisibleScopesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.everhomes.server.schema.tables.records.EhGroupVisibleScopesRecord, ?>>asList(com.everhomes.server.schema.Keys.EH_GROUP_VISIBLE_SCOPES_IBFK_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.everhomes.server.schema.tables.EhGroupVisibleScopes as(java.lang.String alias) {
		return new com.everhomes.server.schema.tables.EhGroupVisibleScopes(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.everhomes.server.schema.tables.EhGroupVisibleScopes rename(java.lang.String name) {
		return new com.everhomes.server.schema.tables.EhGroupVisibleScopes(name, null);
	}
}
