/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhLaunchPadLayouts extends org.jooq.impl.TableImpl<com.everhomes.server.schema.tables.records.EhLaunchPadLayoutsRecord> {

	private static final long serialVersionUID = 1711116266;

	/**
	 * The singleton instance of <code>ehcore.eh_launch_pad_layouts</code>
	 */
	public static final com.everhomes.server.schema.tables.EhLaunchPadLayouts EH_LAUNCH_PAD_LAYOUTS = new com.everhomes.server.schema.tables.EhLaunchPadLayouts();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.everhomes.server.schema.tables.records.EhLaunchPadLayoutsRecord> getRecordType() {
		return com.everhomes.server.schema.tables.records.EhLaunchPadLayoutsRecord.class;
	}

	/**
	 * The column <code>ehcore.eh_launch_pad_layouts.id</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhLaunchPadLayoutsRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>ehcore.eh_launch_pad_layouts.namespace_id</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhLaunchPadLayoutsRecord, java.lang.Integer> NAMESPACE_ID = createField("namespace_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>ehcore.eh_launch_pad_layouts.name</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhLaunchPadLayoutsRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>ehcore.eh_launch_pad_layouts.layout_json</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhLaunchPadLayoutsRecord, java.lang.String> LAYOUT_JSON = createField("layout_json", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * The column <code>ehcore.eh_launch_pad_layouts.version_code</code>. the current version code
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhLaunchPadLayoutsRecord, java.lang.Long> VERSION_CODE = createField("version_code", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "the current version code");

	/**
	 * The column <code>ehcore.eh_launch_pad_layouts.min_version_code</code>. the minmum version code which is compatible
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhLaunchPadLayoutsRecord, java.lang.Long> MIN_VERSION_CODE = createField("min_version_code", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "the minmum version code which is compatible");

	/**
	 * The column <code>ehcore.eh_launch_pad_layouts.status</code>. 0: inactive, 1: waitingForConfirmation, 2: active
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhLaunchPadLayoutsRecord, java.lang.Byte> STATUS = createField("status", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this, "0: inactive, 1: waitingForConfirmation, 2: active");

	/**
	 * The column <code>ehcore.eh_launch_pad_layouts.create_time</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhLaunchPadLayoutsRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ehcore.eh_launch_pad_layouts.scene_type</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhLaunchPadLayoutsRecord, java.lang.String> SCENE_TYPE = createField("scene_type", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>ehcore.eh_launch_pad_layouts.scope_code</code>. 0: all, 1: community, 2: city, 3: user
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhLaunchPadLayoutsRecord, java.lang.Byte> SCOPE_CODE = createField("scope_code", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this, "0: all, 1: community, 2: city, 3: user");

	/**
	 * The column <code>ehcore.eh_launch_pad_layouts.scope_id</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhLaunchPadLayoutsRecord, java.lang.Long> SCOPE_ID = createField("scope_id", org.jooq.impl.SQLDataType.BIGINT.defaulted(true), this, "");

	/**
	 * The column <code>ehcore.eh_launch_pad_layouts.apply_policy</code>. 0: default, 1: override, 2: revert 3:customized
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhLaunchPadLayoutsRecord, java.lang.Byte> APPLY_POLICY = createField("apply_policy", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this, "0: default, 1: override, 2: revert 3:customized");

	/**
	 * Create a <code>ehcore.eh_launch_pad_layouts</code> table reference
	 */
	public EhLaunchPadLayouts() {
		this("eh_launch_pad_layouts", null);
	}

	/**
	 * Create an aliased <code>ehcore.eh_launch_pad_layouts</code> table reference
	 */
	public EhLaunchPadLayouts(java.lang.String alias) {
		this(alias, com.everhomes.server.schema.tables.EhLaunchPadLayouts.EH_LAUNCH_PAD_LAYOUTS);
	}

	private EhLaunchPadLayouts(java.lang.String alias, org.jooq.Table<com.everhomes.server.schema.tables.records.EhLaunchPadLayoutsRecord> aliased) {
		this(alias, aliased, null);
	}

	private EhLaunchPadLayouts(java.lang.String alias, org.jooq.Table<com.everhomes.server.schema.tables.records.EhLaunchPadLayoutsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.everhomes.server.schema.Ehcore.EHCORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.everhomes.server.schema.tables.records.EhLaunchPadLayoutsRecord, java.lang.Long> getIdentity() {
		return com.everhomes.server.schema.Keys.IDENTITY_EH_LAUNCH_PAD_LAYOUTS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.everhomes.server.schema.tables.records.EhLaunchPadLayoutsRecord> getPrimaryKey() {
		return com.everhomes.server.schema.Keys.KEY_EH_LAUNCH_PAD_LAYOUTS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.everhomes.server.schema.tables.records.EhLaunchPadLayoutsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.everhomes.server.schema.tables.records.EhLaunchPadLayoutsRecord>>asList(com.everhomes.server.schema.Keys.KEY_EH_LAUNCH_PAD_LAYOUTS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.everhomes.server.schema.tables.EhLaunchPadLayouts as(java.lang.String alias) {
		return new com.everhomes.server.schema.tables.EhLaunchPadLayouts(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.everhomes.server.schema.tables.EhLaunchPadLayouts rename(java.lang.String name) {
		return new com.everhomes.server.schema.tables.EhLaunchPadLayouts(name, null);
	}
}
