/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhParkingStatistics extends org.jooq.impl.TableImpl<com.everhomes.server.schema.tables.records.EhParkingStatisticsRecord> {

	private static final long serialVersionUID = -282961343;

	/**
	 * The singleton instance of <code>ehcore.eh_parking_statistics</code>
	 */
	public static final com.everhomes.server.schema.tables.EhParkingStatistics EH_PARKING_STATISTICS = new com.everhomes.server.schema.tables.EhParkingStatistics();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.everhomes.server.schema.tables.records.EhParkingStatisticsRecord> getRecordType() {
		return com.everhomes.server.schema.tables.records.EhParkingStatisticsRecord.class;
	}

	/**
	 * The column <code>ehcore.eh_parking_statistics.id</code>. id of the record
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhParkingStatisticsRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "id of the record");

	/**
	 * The column <code>ehcore.eh_parking_statistics.namespace_id</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhParkingStatisticsRecord, java.lang.Integer> NAMESPACE_ID = createField("namespace_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>ehcore.eh_parking_statistics.owner_type</code>. the type of who own the standard, community, etc
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhParkingStatisticsRecord, java.lang.String> OWNER_TYPE = createField("owner_type", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false).defaulted(true), this, "the type of who own the standard, community, etc");

	/**
	 * The column <code>ehcore.eh_parking_statistics.owner_id</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhParkingStatisticsRecord, java.lang.Long> OWNER_ID = createField("owner_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>ehcore.eh_parking_statistics.parking_lot_id</code>. reference to id of eh_parking_lots
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhParkingStatisticsRecord, java.lang.Long> PARKING_LOT_ID = createField("parking_lot_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "reference to id of eh_parking_lots");

	/**
	 * The column <code>ehcore.eh_parking_statistics.amount</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhParkingStatisticsRecord, java.math.BigDecimal> AMOUNT = createField("amount", org.jooq.impl.SQLDataType.DECIMAL.precision(10, 2), this, "");

	/**
	 * The column <code>ehcore.eh_parking_statistics.date_str</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhParkingStatisticsRecord, java.sql.Timestamp> DATE_STR = createField("date_str", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ehcore.eh_parking_statistics.create_time</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhParkingStatisticsRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * Create a <code>ehcore.eh_parking_statistics</code> table reference
	 */
	public EhParkingStatistics() {
		this("eh_parking_statistics", null);
	}

	/**
	 * Create an aliased <code>ehcore.eh_parking_statistics</code> table reference
	 */
	public EhParkingStatistics(java.lang.String alias) {
		this(alias, com.everhomes.server.schema.tables.EhParkingStatistics.EH_PARKING_STATISTICS);
	}

	private EhParkingStatistics(java.lang.String alias, org.jooq.Table<com.everhomes.server.schema.tables.records.EhParkingStatisticsRecord> aliased) {
		this(alias, aliased, null);
	}

	private EhParkingStatistics(java.lang.String alias, org.jooq.Table<com.everhomes.server.schema.tables.records.EhParkingStatisticsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.everhomes.server.schema.Ehcore.EHCORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.everhomes.server.schema.tables.records.EhParkingStatisticsRecord> getPrimaryKey() {
		return com.everhomes.server.schema.Keys.KEY_EH_PARKING_STATISTICS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.everhomes.server.schema.tables.records.EhParkingStatisticsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.everhomes.server.schema.tables.records.EhParkingStatisticsRecord>>asList(com.everhomes.server.schema.Keys.KEY_EH_PARKING_STATISTICS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.everhomes.server.schema.tables.EhParkingStatistics as(java.lang.String alias) {
		return new com.everhomes.server.schema.tables.EhParkingStatistics(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.everhomes.server.schema.tables.EhParkingStatistics rename(java.lang.String name) {
		return new com.everhomes.server.schema.tables.EhParkingStatistics(name, null);
	}
}
