/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhStatActiveUsers extends org.jooq.impl.TableImpl<com.everhomes.server.schema.tables.records.EhStatActiveUsersRecord> {

	private static final long serialVersionUID = 176756390;

	/**
	 * The singleton instance of <code>ehcore.eh_stat_active_users</code>
	 */
	public static final com.everhomes.server.schema.tables.EhStatActiveUsers EH_STAT_ACTIVE_USERS = new com.everhomes.server.schema.tables.EhStatActiveUsers();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.everhomes.server.schema.tables.records.EhStatActiveUsersRecord> getRecordType() {
		return com.everhomes.server.schema.tables.records.EhStatActiveUsersRecord.class;
	}

	/**
	 * The column <code>ehcore.eh_stat_active_users.id</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhStatActiveUsersRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>ehcore.eh_stat_active_users.stat_date</code>. 统计日期
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhStatActiveUsersRecord, java.sql.Date> STAT_DATE = createField("stat_date", org.jooq.impl.SQLDataType.DATE, this, "统计日期");

	/**
	 * The column <code>ehcore.eh_stat_active_users.namespace_id</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhStatActiveUsersRecord, java.lang.Integer> NAMESPACE_ID = createField("namespace_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>ehcore.eh_stat_active_users.active_count</code>. 活动人数
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhStatActiveUsersRecord, java.lang.Integer> ACTIVE_COUNT = createField("active_count", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "活动人数");

	/**
	 * The column <code>ehcore.eh_stat_active_users.total_count</code>. 总人数-当天的
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhStatActiveUsersRecord, java.lang.Integer> TOTAL_COUNT = createField("total_count", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "总人数-当天的");

	/**
	 * The column <code>ehcore.eh_stat_active_users.create_time</code>.
	 */
	public final org.jooq.TableField<com.everhomes.server.schema.tables.records.EhStatActiveUsersRecord, java.sql.Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * Create a <code>ehcore.eh_stat_active_users</code> table reference
	 */
	public EhStatActiveUsers() {
		this("eh_stat_active_users", null);
	}

	/**
	 * Create an aliased <code>ehcore.eh_stat_active_users</code> table reference
	 */
	public EhStatActiveUsers(java.lang.String alias) {
		this(alias, com.everhomes.server.schema.tables.EhStatActiveUsers.EH_STAT_ACTIVE_USERS);
	}

	private EhStatActiveUsers(java.lang.String alias, org.jooq.Table<com.everhomes.server.schema.tables.records.EhStatActiveUsersRecord> aliased) {
		this(alias, aliased, null);
	}

	private EhStatActiveUsers(java.lang.String alias, org.jooq.Table<com.everhomes.server.schema.tables.records.EhStatActiveUsersRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.everhomes.server.schema.Ehcore.EHCORE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.everhomes.server.schema.tables.records.EhStatActiveUsersRecord> getPrimaryKey() {
		return com.everhomes.server.schema.Keys.KEY_EH_STAT_ACTIVE_USERS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.everhomes.server.schema.tables.records.EhStatActiveUsersRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.everhomes.server.schema.tables.records.EhStatActiveUsersRecord>>asList(com.everhomes.server.schema.Keys.KEY_EH_STAT_ACTIVE_USERS_PRIMARY, com.everhomes.server.schema.Keys.KEY_EH_STAT_ACTIVE_USERS_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.everhomes.server.schema.tables.EhStatActiveUsers as(java.lang.String alias) {
		return new com.everhomes.server.schema.tables.EhStatActiveUsers(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.everhomes.server.schema.tables.EhStatActiveUsers rename(java.lang.String name) {
		return new com.everhomes.server.schema.tables.EhStatActiveUsers(name, null);
	}
}
