// @formatter:off
package com.everhomes.socialSecurity;

import com.everhomes.rest.socialSecurity.*;

import java.math.BigDecimal;

interface SocialSecurityService {

 
	void addSocialSecurity(AddSocialSecurityCommand cmd);


	void newSocialSecurityEmployee(Long detailId);

	ListSocialSecurityCitiesResponse listSocialSecurityCities(ListSocialSecurityCitiesCommand cmd);


	ListAccumulationFundCitiesResponse listAccumulationFundCities(ListAccumulationFundCitiesCommand cmd);


	ListFilterItemsResponse listFilterItems(ListFilterItemsCommand cmd);


	ListSocialSecurityPaymentsResponse listSocialSecurityPayments(ListSocialSecurityPaymentsCommand cmd);


	ListSocialSecurityEmployeeStatusResponse listSocialSecurityEmployeeStatus(ListSocialSecurityEmployeeStatusCommand cmd);


	SocialSecurityPaymentDetailDTO getSocialSecurityRule(GetSocialSecurityRuleCommand cmd);

	GetSocialSecurityPaymentDetailsResponse getSocialSecurityPaymentDetails(GetSocialSecurityPaymentDetailsCommand cmd);


	void updateSocialSecurityPayment(UpdateSocialSecurityPaymentCommand cmd);


	void importSocialSecurityPayments(ImportSocialSecurityPaymentsCommand cmd);


	CalculateSocialSecurityReportsResponse calculateSocialSecurityReports(CalculateSocialSecurityReportsCommand cmd);


	BigDecimal calculateAmount(BigDecimal radix, Integer ratio);

	ListSocialSecurityReportsResponse listSocialSecurityReports(ListSocialSecurityReportsCommand cmd);


	void exportSocialSecurityReports(ExportSocialSecurityReportsCommand cmd);


	ListSocialSecurityDepartmentSummarysResponse listSocialSecurityDepartmentSummarys(ListSocialSecurityDepartmentSummarysCommand cmd);


	void exportSocialSecurityDepartmentSummarys(ExportSocialSecurityDepartmentSummarysCommand cmd);


	ListSocialSecurityInoutReportsResponse listSocialSecurityInoutReports(ListSocialSecurityInoutReportsCommand cmd);


	void exportSocialSecurityInoutReports(ExportSocialSecurityInoutReportsCommand cmd);


	void fileSocialSecurity(FileSocialSecurityCommand cmd);


	ListSocialSecurityHistoryFilesResponse listSocialSecurityHistoryFiles(ListSocialSecurityHistoryFilesCommand cmd);


	ListUserInoutHistoryResponse listUserInoutHistory(ListUserInoutHistoryCommand cmd);


	ListSocialSecurityHouseholdTypesResponse listSocialSecurityHouseholdTypes(ListSocialSecurityHouseholdTypesCommand cmd);


	ListAccumulationFundHouseholdTypesResponse listAccumulationFundHouseholdTypes(ListAccumulationFundHouseholdTypesCommand cmd);


	GetSocialSecurityReportStatusResponse getSocialSecurityReportStatus(GetSocialSecurityReportStatusCommand cmd);

	GetSocialSecurityReportsHeadResponse getSocialSecurityReportsHead(GetSocialSecurityReportsHeadCommand cmd);

	SocialSecurityEmployeesCountResponse getSocialSecurityEmployeesCount(Long organizationId, Long month);
}