/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhUsers implements java.io.Serializable {

	private static final long serialVersionUID = -1052999489;

	private java.lang.Long     id;
	private java.lang.String   accountName;
	private java.lang.String   nickName;
	private java.lang.Byte     status;
	private java.sql.Timestamp createTime;
	private java.lang.String   passwordHash;

	public EhUsers() {}

	public EhUsers(
		java.lang.Long     id,
		java.lang.String   accountName,
		java.lang.String   nickName,
		java.lang.Byte     status,
		java.sql.Timestamp createTime,
		java.lang.String   passwordHash
	) {
		this.id = id;
		this.accountName = accountName;
		this.nickName = nickName;
		this.status = status;
		this.createTime = createTime;
		this.passwordHash = passwordHash;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getAccountName() {
		return this.accountName;
	}

	public void setAccountName(java.lang.String accountName) {
		this.accountName = accountName;
	}

	public java.lang.String getNickName() {
		return this.nickName;
	}

	public void setNickName(java.lang.String nickName) {
		this.nickName = nickName;
	}

	public java.lang.Byte getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.Byte status) {
		this.status = status;
	}

	public java.sql.Timestamp getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(java.sql.Timestamp createTime) {
		this.createTime = createTime;
	}

	public java.lang.String getPasswordHash() {
		return this.passwordHash;
	}

	public void setPasswordHash(java.lang.String passwordHash) {
		this.passwordHash = passwordHash;
	}
}
