/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhUserProfiles implements java.io.Serializable {

	private static final long serialVersionUID = -1267959054;

	private java.lang.Long   id;
	private java.lang.Long   ownerId;
	private java.lang.String itemName;
	private java.lang.String itemGroup;
	private java.lang.Byte   itemKind;
	private java.lang.String targetType;
	private java.lang.Long   targetId;
	private java.lang.String targetValue;

	public EhUserProfiles() {}

	public EhUserProfiles(
		java.lang.Long   id,
		java.lang.Long   ownerId,
		java.lang.String itemName,
		java.lang.String itemGroup,
		java.lang.Byte   itemKind,
		java.lang.String targetType,
		java.lang.Long   targetId,
		java.lang.String targetValue
	) {
		this.id = id;
		this.ownerId = ownerId;
		this.itemName = itemName;
		this.itemGroup = itemGroup;
		this.itemKind = itemKind;
		this.targetType = targetType;
		this.targetId = targetId;
		this.targetValue = targetValue;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Long getOwnerId() {
		return this.ownerId;
	}

	public void setOwnerId(java.lang.Long ownerId) {
		this.ownerId = ownerId;
	}

	public java.lang.String getItemName() {
		return this.itemName;
	}

	public void setItemName(java.lang.String itemName) {
		this.itemName = itemName;
	}

	public java.lang.String getItemGroup() {
		return this.itemGroup;
	}

	public void setItemGroup(java.lang.String itemGroup) {
		this.itemGroup = itemGroup;
	}

	public java.lang.Byte getItemKind() {
		return this.itemKind;
	}

	public void setItemKind(java.lang.Byte itemKind) {
		this.itemKind = itemKind;
	}

	public java.lang.String getTargetType() {
		return this.targetType;
	}

	public void setTargetType(java.lang.String targetType) {
		this.targetType = targetType;
	}

	public java.lang.Long getTargetId() {
		return this.targetId;
	}

	public void setTargetId(java.lang.Long targetId) {
		this.targetId = targetId;
	}

	public java.lang.String getTargetValue() {
		return this.targetValue;
	}

	public void setTargetValue(java.lang.String targetValue) {
		this.targetValue = targetValue;
	}
}
