
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OfficeApp_CMService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://10.50.12.39/cm/WebService/OfficeApp-CM/OfficeApp_CMService.asmx?wsdl")
public class OfficeAppCMService
    extends Service
{

    private final static URL OFFICEAPPCMSERVICE_WSDL_LOCATION;
    private final static WebServiceException OFFICEAPPCMSERVICE_EXCEPTION;
    private final static QName OFFICEAPPCMSERVICE_QNAME = new QName("http://tempuri.org/", "OfficeApp_CMService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.50.12.39/cm/WebService/OfficeApp-CM/OfficeApp_CMService.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OFFICEAPPCMSERVICE_WSDL_LOCATION = url;
        OFFICEAPPCMSERVICE_EXCEPTION = e;
    }

    public OfficeAppCMService() {
        super(__getWsdlLocation(), OFFICEAPPCMSERVICE_QNAME);
    }

    public OfficeAppCMService(WebServiceFeature... features) {
        super(__getWsdlLocation(), OFFICEAPPCMSERVICE_QNAME, features);
    }

    public OfficeAppCMService(URL wsdlLocation) {
        super(wsdlLocation, OFFICEAPPCMSERVICE_QNAME);
    }

    public OfficeAppCMService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OFFICEAPPCMSERVICE_QNAME, features);
    }

    public OfficeAppCMService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OfficeAppCMService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OfficeAppCMServiceSoap
     */
    @WebEndpoint(name = "OfficeApp_CMServiceSoap")
    public OfficeAppCMServiceSoap getOfficeAppCMServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "OfficeApp_CMServiceSoap"), OfficeAppCMServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OfficeAppCMServiceSoap
     */
    @WebEndpoint(name = "OfficeApp_CMServiceSoap")
    public OfficeAppCMServiceSoap getOfficeAppCMServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "OfficeApp_CMServiceSoap"), OfficeAppCMServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OFFICEAPPCMSERVICE_EXCEPTION!= null) {
            throw OFFICEAPPCMSERVICE_EXCEPTION;
        }
        return OFFICEAPPCMSERVICE_WSDL_LOCATION;
    }

}
