/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhApprovalRangeStatistics implements java.io.Serializable {

	private static final long serialVersionUID = 2011349810;

	private java.lang.Long     id;
	private java.lang.String   punchMonth;
	private java.lang.String   ownerType;
	private java.lang.Long     ownerId;
	private java.lang.Long     userId;
	private java.lang.Byte     approvalType;
	private java.lang.Long     categoryId;
	private java.lang.String   actualResult;
	private java.lang.Long     creatorUid;
	private java.sql.Timestamp createTime;

	public EhApprovalRangeStatistics() {}

	public EhApprovalRangeStatistics(
		java.lang.Long     id,
		java.lang.String   punchMonth,
		java.lang.String   ownerType,
		java.lang.Long     ownerId,
		java.lang.Long     userId,
		java.lang.Byte     approvalType,
		java.lang.Long     categoryId,
		java.lang.String   actualResult,
		java.lang.Long     creatorUid,
		java.sql.Timestamp createTime
	) {
		this.id = id;
		this.punchMonth = punchMonth;
		this.ownerType = ownerType;
		this.ownerId = ownerId;
		this.userId = userId;
		this.approvalType = approvalType;
		this.categoryId = categoryId;
		this.actualResult = actualResult;
		this.creatorUid = creatorUid;
		this.createTime = createTime;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getPunchMonth() {
		return this.punchMonth;
	}

	public void setPunchMonth(java.lang.String punchMonth) {
		this.punchMonth = punchMonth;
	}

	public java.lang.String getOwnerType() {
		return this.ownerType;
	}

	public void setOwnerType(java.lang.String ownerType) {
		this.ownerType = ownerType;
	}

	public java.lang.Long getOwnerId() {
		return this.ownerId;
	}

	public void setOwnerId(java.lang.Long ownerId) {
		this.ownerId = ownerId;
	}

	public java.lang.Long getUserId() {
		return this.userId;
	}

	public void setUserId(java.lang.Long userId) {
		this.userId = userId;
	}

	public java.lang.Byte getApprovalType() {
		return this.approvalType;
	}

	public void setApprovalType(java.lang.Byte approvalType) {
		this.approvalType = approvalType;
	}

	public java.lang.Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(java.lang.Long categoryId) {
		this.categoryId = categoryId;
	}

	public java.lang.String getActualResult() {
		return this.actualResult;
	}

	public void setActualResult(java.lang.String actualResult) {
		this.actualResult = actualResult;
	}

	public java.lang.Long getCreatorUid() {
		return this.creatorUid;
	}

	public void setCreatorUid(java.lang.Long creatorUid) {
		this.creatorUid = creatorUid;
	}

	public java.sql.Timestamp getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(java.sql.Timestamp createTime) {
		this.createTime = createTime;
	}
}
