/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhBanners implements java.io.Serializable {

	private static final long serialVersionUID = 776470504;

	private java.lang.Long     id;
	private java.lang.Integer  namespaceId;
	private java.lang.Long     appid;
	private java.lang.String   name;
	private java.lang.String   posterPath;
	private java.lang.String   vendorTag;
	private java.sql.Timestamp listingStartTime;
	private java.sql.Timestamp listingEndTime;
	private java.lang.String   resourceType;
	private java.lang.Long     resourceId;
	private java.lang.String   resourceUrl;
	private java.lang.Byte     status;
	private java.lang.Integer  order;
	private java.lang.Long     creatorUid;
	private java.sql.Timestamp createTime;
	private java.sql.Timestamp deleteTime;

	public EhBanners() {}

	public EhBanners(
		java.lang.Long     id,
		java.lang.Integer  namespaceId,
		java.lang.Long     appid,
		java.lang.String   name,
		java.lang.String   posterPath,
		java.lang.String   vendorTag,
		java.sql.Timestamp listingStartTime,
		java.sql.Timestamp listingEndTime,
		java.lang.String   resourceType,
		java.lang.Long     resourceId,
		java.lang.String   resourceUrl,
		java.lang.Byte     status,
		java.lang.Integer  order,
		java.lang.Long     creatorUid,
		java.sql.Timestamp createTime,
		java.sql.Timestamp deleteTime
	) {
		this.id = id;
		this.namespaceId = namespaceId;
		this.appid = appid;
		this.name = name;
		this.posterPath = posterPath;
		this.vendorTag = vendorTag;
		this.listingStartTime = listingStartTime;
		this.listingEndTime = listingEndTime;
		this.resourceType = resourceType;
		this.resourceId = resourceId;
		this.resourceUrl = resourceUrl;
		this.status = status;
		this.order = order;
		this.creatorUid = creatorUid;
		this.createTime = createTime;
		this.deleteTime = deleteTime;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Integer getNamespaceId() {
		return this.namespaceId;
	}

	public void setNamespaceId(java.lang.Integer namespaceId) {
		this.namespaceId = namespaceId;
	}

	public java.lang.Long getAppid() {
		return this.appid;
	}

	public void setAppid(java.lang.Long appid) {
		this.appid = appid;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getPosterPath() {
		return this.posterPath;
	}

	public void setPosterPath(java.lang.String posterPath) {
		this.posterPath = posterPath;
	}

	public java.lang.String getVendorTag() {
		return this.vendorTag;
	}

	public void setVendorTag(java.lang.String vendorTag) {
		this.vendorTag = vendorTag;
	}

	public java.sql.Timestamp getListingStartTime() {
		return this.listingStartTime;
	}

	public void setListingStartTime(java.sql.Timestamp listingStartTime) {
		this.listingStartTime = listingStartTime;
	}

	public java.sql.Timestamp getListingEndTime() {
		return this.listingEndTime;
	}

	public void setListingEndTime(java.sql.Timestamp listingEndTime) {
		this.listingEndTime = listingEndTime;
	}

	public java.lang.String getResourceType() {
		return this.resourceType;
	}

	public void setResourceType(java.lang.String resourceType) {
		this.resourceType = resourceType;
	}

	public java.lang.Long getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(java.lang.Long resourceId) {
		this.resourceId = resourceId;
	}

	public java.lang.String getResourceUrl() {
		return this.resourceUrl;
	}

	public void setResourceUrl(java.lang.String resourceUrl) {
		this.resourceUrl = resourceUrl;
	}

	public java.lang.Byte getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.Byte status) {
		this.status = status;
	}

	public java.lang.Integer getOrder() {
		return this.order;
	}

	public void setOrder(java.lang.Integer order) {
		this.order = order;
	}

	public java.lang.Long getCreatorUid() {
		return this.creatorUid;
	}

	public void setCreatorUid(java.lang.Long creatorUid) {
		this.creatorUid = creatorUid;
	}

	public java.sql.Timestamp getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(java.sql.Timestamp createTime) {
		this.createTime = createTime;
	}

	public java.sql.Timestamp getDeleteTime() {
		return this.deleteTime;
	}

	public void setDeleteTime(java.sql.Timestamp deleteTime) {
		this.deleteTime = deleteTime;
	}
}
