/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhGeneralApprovalVals implements java.io.Serializable {

	private static final long serialVersionUID = 1627725306;

	private java.lang.Long     id;
	private java.lang.Integer  namespaceId;
	private java.lang.Long     flowCaseId;
	private java.lang.Long     requestId;
	private java.lang.Long     approvalId;
	private java.lang.Long     formOriginId;
	private java.lang.Long     formVersion;
	private java.lang.String   fieldName;
	private java.lang.String   fieldType;
	private java.lang.String   dataSourceType;
	private java.lang.Byte     valType;
	private java.lang.String   fieldStr1;
	private java.lang.String   fieldStr2;
	private java.lang.String   fieldStr3;
	private java.lang.Long     fieldInt1;
	private java.lang.Long     fieldInt2;
	private java.lang.Long     fieldInt3;
	private java.sql.Timestamp createTime;

	public EhGeneralApprovalVals() {}

	public EhGeneralApprovalVals(
		java.lang.Long     id,
		java.lang.Integer  namespaceId,
		java.lang.Long     flowCaseId,
		java.lang.Long     requestId,
		java.lang.Long     approvalId,
		java.lang.Long     formOriginId,
		java.lang.Long     formVersion,
		java.lang.String   fieldName,
		java.lang.String   fieldType,
		java.lang.String   dataSourceType,
		java.lang.Byte     valType,
		java.lang.String   fieldStr1,
		java.lang.String   fieldStr2,
		java.lang.String   fieldStr3,
		java.lang.Long     fieldInt1,
		java.lang.Long     fieldInt2,
		java.lang.Long     fieldInt3,
		java.sql.Timestamp createTime
	) {
		this.id = id;
		this.namespaceId = namespaceId;
		this.flowCaseId = flowCaseId;
		this.requestId = requestId;
		this.approvalId = approvalId;
		this.formOriginId = formOriginId;
		this.formVersion = formVersion;
		this.fieldName = fieldName;
		this.fieldType = fieldType;
		this.dataSourceType = dataSourceType;
		this.valType = valType;
		this.fieldStr1 = fieldStr1;
		this.fieldStr2 = fieldStr2;
		this.fieldStr3 = fieldStr3;
		this.fieldInt1 = fieldInt1;
		this.fieldInt2 = fieldInt2;
		this.fieldInt3 = fieldInt3;
		this.createTime = createTime;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Integer getNamespaceId() {
		return this.namespaceId;
	}

	public void setNamespaceId(java.lang.Integer namespaceId) {
		this.namespaceId = namespaceId;
	}

	public java.lang.Long getFlowCaseId() {
		return this.flowCaseId;
	}

	public void setFlowCaseId(java.lang.Long flowCaseId) {
		this.flowCaseId = flowCaseId;
	}

	public java.lang.Long getRequestId() {
		return this.requestId;
	}

	public void setRequestId(java.lang.Long requestId) {
		this.requestId = requestId;
	}

	public java.lang.Long getApprovalId() {
		return this.approvalId;
	}

	public void setApprovalId(java.lang.Long approvalId) {
		this.approvalId = approvalId;
	}

	public java.lang.Long getFormOriginId() {
		return this.formOriginId;
	}

	public void setFormOriginId(java.lang.Long formOriginId) {
		this.formOriginId = formOriginId;
	}

	public java.lang.Long getFormVersion() {
		return this.formVersion;
	}

	public void setFormVersion(java.lang.Long formVersion) {
		this.formVersion = formVersion;
	}

	public java.lang.String getFieldName() {
		return this.fieldName;
	}

	public void setFieldName(java.lang.String fieldName) {
		this.fieldName = fieldName;
	}

	public java.lang.String getFieldType() {
		return this.fieldType;
	}

	public void setFieldType(java.lang.String fieldType) {
		this.fieldType = fieldType;
	}

	public java.lang.String getDataSourceType() {
		return this.dataSourceType;
	}

	public void setDataSourceType(java.lang.String dataSourceType) {
		this.dataSourceType = dataSourceType;
	}

	public java.lang.Byte getValType() {
		return this.valType;
	}

	public void setValType(java.lang.Byte valType) {
		this.valType = valType;
	}

	public java.lang.String getFieldStr1() {
		return this.fieldStr1;
	}

	public void setFieldStr1(java.lang.String fieldStr1) {
		this.fieldStr1 = fieldStr1;
	}

	public java.lang.String getFieldStr2() {
		return this.fieldStr2;
	}

	public void setFieldStr2(java.lang.String fieldStr2) {
		this.fieldStr2 = fieldStr2;
	}

	public java.lang.String getFieldStr3() {
		return this.fieldStr3;
	}

	public void setFieldStr3(java.lang.String fieldStr3) {
		this.fieldStr3 = fieldStr3;
	}

	public java.lang.Long getFieldInt1() {
		return this.fieldInt1;
	}

	public void setFieldInt1(java.lang.Long fieldInt1) {
		this.fieldInt1 = fieldInt1;
	}

	public java.lang.Long getFieldInt2() {
		return this.fieldInt2;
	}

	public void setFieldInt2(java.lang.Long fieldInt2) {
		this.fieldInt2 = fieldInt2;
	}

	public java.lang.Long getFieldInt3() {
		return this.fieldInt3;
	}

	public void setFieldInt3(java.lang.Long fieldInt3) {
		this.fieldInt3 = fieldInt3;
	}

	public java.sql.Timestamp getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(java.sql.Timestamp createTime) {
		this.createTime = createTime;
	}
}
