/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhParkCharge implements java.io.Serializable {

	private static final long serialVersionUID = 1052518975;

	private java.lang.Long   id;
	private java.lang.Byte   months;
	private java.lang.Double amount;
	private java.lang.Long   communityId;
	private java.lang.String cardType;

	public EhParkCharge() {}

	public EhParkCharge(
		java.lang.Long   id,
		java.lang.Byte   months,
		java.lang.Double amount,
		java.lang.Long   communityId,
		java.lang.String cardType
	) {
		this.id = id;
		this.months = months;
		this.amount = amount;
		this.communityId = communityId;
		this.cardType = cardType;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Byte getMonths() {
		return this.months;
	}

	public void setMonths(java.lang.Byte months) {
		this.months = months;
	}

	public java.lang.Double getAmount() {
		return this.amount;
	}

	public void setAmount(java.lang.Double amount) {
		this.amount = amount;
	}

	public java.lang.Long getCommunityId() {
		return this.communityId;
	}

	public void setCommunityId(java.lang.Long communityId) {
		this.communityId = communityId;
	}

	public java.lang.String getCardType() {
		return this.cardType;
	}

	public void setCardType(java.lang.String cardType) {
		this.cardType = cardType;
	}
}
