/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhParkApplyCard implements java.io.Serializable {

	private static final long serialVersionUID = -2010890629;

	private java.lang.Long     id;
	private java.lang.Long     applierId;
	private java.lang.String   applierName;
	private java.lang.String   applierPhone;
	private java.lang.String   plateNumber;
	private java.sql.Timestamp applyTime;
	private java.lang.Byte     applyStatus;
	private java.lang.Byte     fetchStatus;
	private java.sql.Timestamp deadline;
	private java.lang.Long     communityId;
	private java.lang.String   companyName;

	public EhParkApplyCard() {}

	public EhParkApplyCard(
		java.lang.Long     id,
		java.lang.Long     applierId,
		java.lang.String   applierName,
		java.lang.String   applierPhone,
		java.lang.String   plateNumber,
		java.sql.Timestamp applyTime,
		java.lang.Byte     applyStatus,
		java.lang.Byte     fetchStatus,
		java.sql.Timestamp deadline,
		java.lang.Long     communityId,
		java.lang.String   companyName
	) {
		this.id = id;
		this.applierId = applierId;
		this.applierName = applierName;
		this.applierPhone = applierPhone;
		this.plateNumber = plateNumber;
		this.applyTime = applyTime;
		this.applyStatus = applyStatus;
		this.fetchStatus = fetchStatus;
		this.deadline = deadline;
		this.communityId = communityId;
		this.companyName = companyName;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Long getApplierId() {
		return this.applierId;
	}

	public void setApplierId(java.lang.Long applierId) {
		this.applierId = applierId;
	}

	public java.lang.String getApplierName() {
		return this.applierName;
	}

	public void setApplierName(java.lang.String applierName) {
		this.applierName = applierName;
	}

	public java.lang.String getApplierPhone() {
		return this.applierPhone;
	}

	public void setApplierPhone(java.lang.String applierPhone) {
		this.applierPhone = applierPhone;
	}

	public java.lang.String getPlateNumber() {
		return this.plateNumber;
	}

	public void setPlateNumber(java.lang.String plateNumber) {
		this.plateNumber = plateNumber;
	}

	public java.sql.Timestamp getApplyTime() {
		return this.applyTime;
	}

	public void setApplyTime(java.sql.Timestamp applyTime) {
		this.applyTime = applyTime;
	}

	public java.lang.Byte getApplyStatus() {
		return this.applyStatus;
	}

	public void setApplyStatus(java.lang.Byte applyStatus) {
		this.applyStatus = applyStatus;
	}

	public java.lang.Byte getFetchStatus() {
		return this.fetchStatus;
	}

	public void setFetchStatus(java.lang.Byte fetchStatus) {
		this.fetchStatus = fetchStatus;
	}

	public java.sql.Timestamp getDeadline() {
		return this.deadline;
	}

	public void setDeadline(java.sql.Timestamp deadline) {
		this.deadline = deadline;
	}

	public java.lang.Long getCommunityId() {
		return this.communityId;
	}

	public void setCommunityId(java.lang.Long communityId) {
		this.communityId = communityId;
	}

	public java.lang.String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(java.lang.String companyName) {
		this.companyName = companyName;
	}
}
