/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhPmsyOrders implements java.io.Serializable {

	private static final long serialVersionUID = 1616930721;

	private java.lang.Long       id;
	private java.lang.Integer    namespaceId;
	private java.lang.String     ownerType;
	private java.lang.Long       ownerId;
	private java.lang.String     userName;
	private java.lang.String     userContact;
	private java.math.BigDecimal orderAmount;
	private java.sql.Timestamp   paidTime;
	private java.lang.Byte       status;
	private java.lang.Long       creatorUid;
	private java.sql.Timestamp   createTime;
	private java.lang.String     paidType;
	private java.lang.String     projectId;
	private java.lang.String     customerId;

	public EhPmsyOrders() {}

	public EhPmsyOrders(
		java.lang.Long       id,
		java.lang.Integer    namespaceId,
		java.lang.String     ownerType,
		java.lang.Long       ownerId,
		java.lang.String     userName,
		java.lang.String     userContact,
		java.math.BigDecimal orderAmount,
		java.sql.Timestamp   paidTime,
		java.lang.Byte       status,
		java.lang.Long       creatorUid,
		java.sql.Timestamp   createTime,
		java.lang.String     paidType,
		java.lang.String     projectId,
		java.lang.String     customerId
	) {
		this.id = id;
		this.namespaceId = namespaceId;
		this.ownerType = ownerType;
		this.ownerId = ownerId;
		this.userName = userName;
		this.userContact = userContact;
		this.orderAmount = orderAmount;
		this.paidTime = paidTime;
		this.status = status;
		this.creatorUid = creatorUid;
		this.createTime = createTime;
		this.paidType = paidType;
		this.projectId = projectId;
		this.customerId = customerId;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Integer getNamespaceId() {
		return this.namespaceId;
	}

	public void setNamespaceId(java.lang.Integer namespaceId) {
		this.namespaceId = namespaceId;
	}

	public java.lang.String getOwnerType() {
		return this.ownerType;
	}

	public void setOwnerType(java.lang.String ownerType) {
		this.ownerType = ownerType;
	}

	public java.lang.Long getOwnerId() {
		return this.ownerId;
	}

	public void setOwnerId(java.lang.Long ownerId) {
		this.ownerId = ownerId;
	}

	public java.lang.String getUserName() {
		return this.userName;
	}

	public void setUserName(java.lang.String userName) {
		this.userName = userName;
	}

	public java.lang.String getUserContact() {
		return this.userContact;
	}

	public void setUserContact(java.lang.String userContact) {
		this.userContact = userContact;
	}

	public java.math.BigDecimal getOrderAmount() {
		return this.orderAmount;
	}

	public void setOrderAmount(java.math.BigDecimal orderAmount) {
		this.orderAmount = orderAmount;
	}

	public java.sql.Timestamp getPaidTime() {
		return this.paidTime;
	}

	public void setPaidTime(java.sql.Timestamp paidTime) {
		this.paidTime = paidTime;
	}

	public java.lang.Byte getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.Byte status) {
		this.status = status;
	}

	public java.lang.Long getCreatorUid() {
		return this.creatorUid;
	}

	public void setCreatorUid(java.lang.Long creatorUid) {
		this.creatorUid = creatorUid;
	}

	public java.sql.Timestamp getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(java.sql.Timestamp createTime) {
		this.createTime = createTime;
	}

	public java.lang.String getPaidType() {
		return this.paidType;
	}

	public void setPaidType(java.lang.String paidType) {
		this.paidType = paidType;
	}

	public java.lang.String getProjectId() {
		return this.projectId;
	}

	public void setProjectId(java.lang.String projectId) {
		this.projectId = projectId;
	}

	public java.lang.String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(java.lang.String customerId) {
		this.customerId = customerId;
	}
}
