/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhRechargeInfo implements java.io.Serializable {

	private static final long serialVersionUID = 827117302;

	private java.lang.Long     id;
	private java.lang.Long     billId;
	private java.lang.String   plateNumber;
	private java.lang.Byte     numberType;
	private java.lang.String   ownerName;
	private java.lang.String   ownerPhone;
	private java.lang.String   rechargeUsername;
	private java.lang.String   rechargePhone;
	private java.sql.Timestamp rechargeTime;
	private java.lang.Byte     rechargeMonth;
	private java.lang.Integer  rechargeAmount;
	private java.lang.Byte     paymentStatus;
	private java.lang.Byte     rechargeStatus;
	private java.lang.Long     enterpriseCommunityId;

	public EhRechargeInfo() {}

	public EhRechargeInfo(
		java.lang.Long     id,
		java.lang.Long     billId,
		java.lang.String   plateNumber,
		java.lang.Byte     numberType,
		java.lang.String   ownerName,
		java.lang.String   ownerPhone,
		java.lang.String   rechargeUsername,
		java.lang.String   rechargePhone,
		java.sql.Timestamp rechargeTime,
		java.lang.Byte     rechargeMonth,
		java.lang.Integer  rechargeAmount,
		java.lang.Byte     paymentStatus,
		java.lang.Byte     rechargeStatus,
		java.lang.Long     enterpriseCommunityId
	) {
		this.id = id;
		this.billId = billId;
		this.plateNumber = plateNumber;
		this.numberType = numberType;
		this.ownerName = ownerName;
		this.ownerPhone = ownerPhone;
		this.rechargeUsername = rechargeUsername;
		this.rechargePhone = rechargePhone;
		this.rechargeTime = rechargeTime;
		this.rechargeMonth = rechargeMonth;
		this.rechargeAmount = rechargeAmount;
		this.paymentStatus = paymentStatus;
		this.rechargeStatus = rechargeStatus;
		this.enterpriseCommunityId = enterpriseCommunityId;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Long getBillId() {
		return this.billId;
	}

	public void setBillId(java.lang.Long billId) {
		this.billId = billId;
	}

	public java.lang.String getPlateNumber() {
		return this.plateNumber;
	}

	public void setPlateNumber(java.lang.String plateNumber) {
		this.plateNumber = plateNumber;
	}

	public java.lang.Byte getNumberType() {
		return this.numberType;
	}

	public void setNumberType(java.lang.Byte numberType) {
		this.numberType = numberType;
	}

	public java.lang.String getOwnerName() {
		return this.ownerName;
	}

	public void setOwnerName(java.lang.String ownerName) {
		this.ownerName = ownerName;
	}

	public java.lang.String getOwnerPhone() {
		return this.ownerPhone;
	}

	public void setOwnerPhone(java.lang.String ownerPhone) {
		this.ownerPhone = ownerPhone;
	}

	public java.lang.String getRechargeUsername() {
		return this.rechargeUsername;
	}

	public void setRechargeUsername(java.lang.String rechargeUsername) {
		this.rechargeUsername = rechargeUsername;
	}

	public java.lang.String getRechargePhone() {
		return this.rechargePhone;
	}

	public void setRechargePhone(java.lang.String rechargePhone) {
		this.rechargePhone = rechargePhone;
	}

	public java.sql.Timestamp getRechargeTime() {
		return this.rechargeTime;
	}

	public void setRechargeTime(java.sql.Timestamp rechargeTime) {
		this.rechargeTime = rechargeTime;
	}

	public java.lang.Byte getRechargeMonth() {
		return this.rechargeMonth;
	}

	public void setRechargeMonth(java.lang.Byte rechargeMonth) {
		this.rechargeMonth = rechargeMonth;
	}

	public java.lang.Integer getRechargeAmount() {
		return this.rechargeAmount;
	}

	public void setRechargeAmount(java.lang.Integer rechargeAmount) {
		this.rechargeAmount = rechargeAmount;
	}

	public java.lang.Byte getPaymentStatus() {
		return this.paymentStatus;
	}

	public void setPaymentStatus(java.lang.Byte paymentStatus) {
		this.paymentStatus = paymentStatus;
	}

	public java.lang.Byte getRechargeStatus() {
		return this.rechargeStatus;
	}

	public void setRechargeStatus(java.lang.Byte rechargeStatus) {
		this.rechargeStatus = rechargeStatus;
	}

	public java.lang.Long getEnterpriseCommunityId() {
		return this.enterpriseCommunityId;
	}

	public void setEnterpriseCommunityId(java.lang.Long enterpriseCommunityId) {
		this.enterpriseCommunityId = enterpriseCommunityId;
	}
}
