/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhRentalv2PriceRules implements java.io.Serializable {

	private static final long serialVersionUID = 2101032083;

	private java.lang.Long       id;
	private java.lang.String     ownerType;
	private java.lang.Long       ownerId;
	private java.lang.Byte       rentalType;
	private java.math.BigDecimal workdayPrice;
	private java.math.BigDecimal weekendPrice;
	private java.math.BigDecimal orgMemberWorkdayPrice;
	private java.math.BigDecimal orgMemberWeekendPrice;
	private java.math.BigDecimal approvingUserWorkdayPrice;
	private java.math.BigDecimal approvingUserWeekendPrice;
	private java.lang.Byte       discountType;
	private java.math.BigDecimal fullPrice;
	private java.math.BigDecimal cutPrice;
	private java.lang.Double     discountRatio;
	private java.lang.Long       cellBeginId;
	private java.lang.Long       cellEndId;
	private java.lang.Long       creatorUid;
	private java.sql.Timestamp   createTime;

	public EhRentalv2PriceRules() {}

	public EhRentalv2PriceRules(
		java.lang.Long       id,
		java.lang.String     ownerType,
		java.lang.Long       ownerId,
		java.lang.Byte       rentalType,
		java.math.BigDecimal workdayPrice,
		java.math.BigDecimal weekendPrice,
		java.math.BigDecimal orgMemberWorkdayPrice,
		java.math.BigDecimal orgMemberWeekendPrice,
		java.math.BigDecimal approvingUserWorkdayPrice,
		java.math.BigDecimal approvingUserWeekendPrice,
		java.lang.Byte       discountType,
		java.math.BigDecimal fullPrice,
		java.math.BigDecimal cutPrice,
		java.lang.Double     discountRatio,
		java.lang.Long       cellBeginId,
		java.lang.Long       cellEndId,
		java.lang.Long       creatorUid,
		java.sql.Timestamp   createTime
	) {
		this.id = id;
		this.ownerType = ownerType;
		this.ownerId = ownerId;
		this.rentalType = rentalType;
		this.workdayPrice = workdayPrice;
		this.weekendPrice = weekendPrice;
		this.orgMemberWorkdayPrice = orgMemberWorkdayPrice;
		this.orgMemberWeekendPrice = orgMemberWeekendPrice;
		this.approvingUserWorkdayPrice = approvingUserWorkdayPrice;
		this.approvingUserWeekendPrice = approvingUserWeekendPrice;
		this.discountType = discountType;
		this.fullPrice = fullPrice;
		this.cutPrice = cutPrice;
		this.discountRatio = discountRatio;
		this.cellBeginId = cellBeginId;
		this.cellEndId = cellEndId;
		this.creatorUid = creatorUid;
		this.createTime = createTime;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getOwnerType() {
		return this.ownerType;
	}

	public void setOwnerType(java.lang.String ownerType) {
		this.ownerType = ownerType;
	}

	public java.lang.Long getOwnerId() {
		return this.ownerId;
	}

	public void setOwnerId(java.lang.Long ownerId) {
		this.ownerId = ownerId;
	}

	public java.lang.Byte getRentalType() {
		return this.rentalType;
	}

	public void setRentalType(java.lang.Byte rentalType) {
		this.rentalType = rentalType;
	}

	public java.math.BigDecimal getWorkdayPrice() {
		return this.workdayPrice;
	}

	public void setWorkdayPrice(java.math.BigDecimal workdayPrice) {
		this.workdayPrice = workdayPrice;
	}

	public java.math.BigDecimal getWeekendPrice() {
		return this.weekendPrice;
	}

	public void setWeekendPrice(java.math.BigDecimal weekendPrice) {
		this.weekendPrice = weekendPrice;
	}

	public java.math.BigDecimal getOrgMemberWorkdayPrice() {
		return this.orgMemberWorkdayPrice;
	}

	public void setOrgMemberWorkdayPrice(java.math.BigDecimal orgMemberWorkdayPrice) {
		this.orgMemberWorkdayPrice = orgMemberWorkdayPrice;
	}

	public java.math.BigDecimal getOrgMemberWeekendPrice() {
		return this.orgMemberWeekendPrice;
	}

	public void setOrgMemberWeekendPrice(java.math.BigDecimal orgMemberWeekendPrice) {
		this.orgMemberWeekendPrice = orgMemberWeekendPrice;
	}

	public java.math.BigDecimal getApprovingUserWorkdayPrice() {
		return this.approvingUserWorkdayPrice;
	}

	public void setApprovingUserWorkdayPrice(java.math.BigDecimal approvingUserWorkdayPrice) {
		this.approvingUserWorkdayPrice = approvingUserWorkdayPrice;
	}

	public java.math.BigDecimal getApprovingUserWeekendPrice() {
		return this.approvingUserWeekendPrice;
	}

	public void setApprovingUserWeekendPrice(java.math.BigDecimal approvingUserWeekendPrice) {
		this.approvingUserWeekendPrice = approvingUserWeekendPrice;
	}

	public java.lang.Byte getDiscountType() {
		return this.discountType;
	}

	public void setDiscountType(java.lang.Byte discountType) {
		this.discountType = discountType;
	}

	public java.math.BigDecimal getFullPrice() {
		return this.fullPrice;
	}

	public void setFullPrice(java.math.BigDecimal fullPrice) {
		this.fullPrice = fullPrice;
	}

	public java.math.BigDecimal getCutPrice() {
		return this.cutPrice;
	}

	public void setCutPrice(java.math.BigDecimal cutPrice) {
		this.cutPrice = cutPrice;
	}

	public java.lang.Double getDiscountRatio() {
		return this.discountRatio;
	}

	public void setDiscountRatio(java.lang.Double discountRatio) {
		this.discountRatio = discountRatio;
	}

	public java.lang.Long getCellBeginId() {
		return this.cellBeginId;
	}

	public void setCellBeginId(java.lang.Long cellBeginId) {
		this.cellBeginId = cellBeginId;
	}

	public java.lang.Long getCellEndId() {
		return this.cellEndId;
	}

	public void setCellEndId(java.lang.Long cellEndId) {
		this.cellEndId = cellEndId;
	}

	public java.lang.Long getCreatorUid() {
		return this.creatorUid;
	}

	public void setCreatorUid(java.lang.Long creatorUid) {
		this.creatorUid = creatorUid;
	}

	public java.sql.Timestamp getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(java.sql.Timestamp createTime) {
		this.createTime = createTime;
	}
}
