#!/bin/bash
# chkconfig: 345 80 20

#set -x

EVH_HOME=.
WAR=oauth2-client-0.0.1-SNAPSHOT.war

getpid() {
    local i
    for i in $(ps -ef | grep "oauth2-client-0.0.1-SNAPSHOT" | grep -v grep | awk '{print $2}')
    do
        echo $i
    done	
}

start() {
    local pid=$(getpid)
    if [ "$pid" != "" ]; then
        echo "oauth2-client server is already running with pid=$pid"
        return 0
    fi
    
    if [ ! -e $EVH_HOME/$WAR ]; then
        echo "oauth2-client server is not properly installed"
        return 1
    fi
    
    echo -n "Starting oauth2-client server"
    
    rm -rf $EVH_HOME/atomikos
    nohup java -jar $EVH_HOME/$WAR --spring.config.name=oauth2-client > /dev/null &
    sleep 2
    pid=$(getpid)
    if [ "$pid" != "" ]; then
        echo " succeeded"
    else
        echo " failed"
    fi       
}

stop() {
    local pid=$(getpid)
    if [ "$pid" != "" ]; then
        echo -n "Stopping oauth2-client server"

        kill $pid >/dev/null 2>&1
        sleep 1
        
        pid=$(getpid)
        if [ "$pid" == "" ]; then
            echo " succeeded"
        else
            echo " failed"
        fi       
    else
        echo "oauth2-client server is already stopped"
    fi
}

status() {
    local pid=$(getpid)
    if [ "$pid" != "" ]; then
        echo "oauth2-client server is currently running with pid: $pid"
    else
        echo "oauth2-client server is not running"
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart}"
        exit 1
        ;;
esac

exit $?

