//
// EvhCategoryConstants.h
//

#define EvhCategoryConstants_CATEGORY_ID_TOPIC 1
#define EvhCategoryConstants_CATEGORY_ID_INTEREST 2
#define EvhCategoryConstants_CATEGORY_ID_SERVICE 3
#define EvhCategoryConstants_CATEGORY_ID_ACTIVITY 4
#define EvhCategoryConstants_CATEGORY_ID_TECH_ACTIVITY 5
#define EvhCategoryConstants_CATEGORY_ID_QUALITY_INSPECTION 6
#define EvhCategoryConstants_CATEGORY_ID_TOPIC_COMMON 1001
#define EvhCategoryConstants_CATEGORY_ID_URGENT_NOTICE 1002
#define EvhCategoryConstants_CATEGORY_ID_NOTICE 1003
#define EvhCategoryConstants_CATEGORY_ID_REPAIRS 1004
#define EvhCategoryConstants_CATEGORY_ID_CONSULT_APPEAL 1005
#define EvhCategoryConstants_CATEGORY_ID_COMPLAINT_ADVICE 1006
#define EvhCategoryConstants_CATEGORY_ID_USED_AND_RENTAL 1007
#define EvhCategoryConstants_CATEGORY_ID_FREE_STUFF 1008
#define EvhCategoryConstants_CATEGORY_ID_LOST_AND_FOUND 1009
#define EvhCategoryConstants_CATEGORY_ID_TOPIC_ACTIVITY 1010
#define EvhCategoryConstants_CATEGORY_ID_TOPIC_POLLING 1011
#define EvhCategoryConstants_CATEGORY_ID_EMERGENCY_HELP 1012
#define EvhCategoryConstants_CATEGORY_ID_CONF 200001
#define EvhCategoryConstants_CATEGORY_ID_CONF_CAPACITY 200101
#define EvhCategoryConstants_CATEGORY_ID_CONF_TYPE 200201
#define EvhCategoryConstants_CATEGORY_ID_ACCOUNT_TYPE 200301
#define EvhCategoryConstants_CATEGORY_ID_CLEANING 102021
#define EvhCategoryConstants_CATEGORY_ID_HOUSE_KEEPING 102022
#define EvhCategoryConstants_CATEGORY_ID_MAINTENANCE 102023
#define EvhCategoryConstants_GA_RELATED_CATEGORIES [1003, 1004, 1005, 1006, 102021, 102022, 102023, 1012]
#define EvhCategoryConstants_GA_PRIVACY_CATEGORIES [1004, 1005, 1006, 102021, 102022, 102023]
