//
// EvhCommunityServiceErrorCode.h
//

#define EvhCommunityServiceErrorCode_SCOPE @"community"
#define EvhCommunityServiceErrorCode_ERROR_COMMUNITY_NOT_EXIST 10001
#define EvhCommunityServiceErrorCode_ERROR_COMMUNITY_GEOPOIN_NOT_EXIST 10002
#define EvhCommunityServiceErrorCode_ERROR_COMMUNITY_CITY_NOT_EXIST 10003
#define EvhCommunityServiceErrorCode_ERROR_BUILDING_NOT_EXIST 10004
#define EvhCommunityServiceErrorCode_ERROR_BUILDING_COMMUNITY_NOT_EXIST 10005
