//
// EvhContentServerErrorCode.h
//

#define EvhContentServerErrorCode_SCOPE @"contentserver"
#define EvhContentServerErrorCode_ERROR_INVALID_PRIVILLAGE 10000
#define EvhContentServerErrorCode_ERROR_INVALID_SESSION 10001
#define EvhContentServerErrorCode_ERROR_INVALID_SERVER 10002
#define EvhContentServerErrorCode_ERROR_INVALID_USER 10003
#define EvhContentServerErrorCode_ERROR_INVALID_ACTION 10004
#define EvhContentServerErrorCode_ERROR_INVALID_PARAMS 10005
