//
// EvhCommunityNotificationTemplateCode.h
//

#define EvhCommunityNotificationTemplateCode_SCOPE @"community.notification"
#define EvhCommunityNotificationTemplateCode_COMMUNITY_ADD_FOR_APPLICANT 1
#define EvhCommunityNotificationTemplateCode_COMMUNITY_ADD_APPROVE_FOR_APPLICANT 2
#define EvhCommunityNotificationTemplateCode_COMMUNITY_ADD_REJECT_FOR_APPLICANT 3
