//
// EvhEnterpriseServiceErrorCode.h
// generated at 2016-04-08 20:09:22 
//

#define EvhEnterpriseServiceErrorCode_SCOPE @"enterprise"
#define EvhEnterpriseServiceErrorCode_ERROR_ENTERPRISE_NOT_FOUND 10001
#define EvhEnterpriseServiceErrorCode_ERROR_ENTERPRISE_USER_NOT_FOUND 10002
#define EvhEnterpriseServiceErrorCode_ERROR_ENTERPRISE_CONTACT_NOT_FOUND 10101
#define EvhEnterpriseServiceErrorCode_ERROR_ENTERPRISE_CONTACT_PHONENUM_USED 10111
#define EvhEnterpriseServiceErrorCode_ERROR_ENTERPRISE_CONTACT_GROUP_HAS_CHILD 11101
