//
// EvhForumServiceErrorCode.h
//

#define EvhForumServiceErrorCode_SCOPE @"forum"
#define EvhForumServiceErrorCode_ERROR_FORUM_NOT_FOUND 10001
#define EvhForumServiceErrorCode_ERROR_FORUM_VISIBLE_REGION_NOT_FOUND 10002
#define EvhForumServiceErrorCode_ERROR_FORUM_COMMUNITY_NOT_FOUND 10003
#define EvhForumServiceErrorCode_ERROR_FORUM_TOPIC_NOT_FOUND 10004
#define EvhForumServiceErrorCode_ERROR_FORUM_ORGANIZATION_NOT_FOUND 10004
#define EvhForumServiceErrorCode_ERROR_FORUM_ORGANIZATION_COMMUNITY_NOT_FOUND 10005
#define EvhForumServiceErrorCode_ERROR_FORUM_TOPIC_DELETED 10006
#define EvhForumServiceErrorCode_ERROR_FORUM_TOPIC_NOT_ASSIGNED 10011
#define EvhForumServiceErrorCode_ERROR_FORUM_TOPIC_ALREADY_ASSIGNED 10012
