//
// EvhForumLocalStringCode.h
//

#define EvhForumLocalStringCode_SCOPE @"forum"
#define EvhForumLocalStringCode_FORUM_TOPIC_DELETED 1
#define EvhForumLocalStringCode_FORUM_COMMENT_DELETED 2
#define EvhForumLocalStringCode_POST_MEMU_COMMUNITY_GROUP 101
#define EvhForumLocalStringCode_POST_MEMU_COMMUNITY_NEARBY 102
#define EvhForumLocalStringCode_POST_MEMU_COMMUNITY_ONLY 103
#define EvhForumLocalStringCode_POST_MEMU_INTEREST_GROUP 104
#define EvhForumLocalStringCode_POST_MEMU_ORGANIZATION_GROUP 105
#define EvhForumLocalStringCode_POST_MEMU_ALL 106
#define EvhForumLocalStringCode_POST_MEMU_PARK_ONLY 107
