//
// EvhFamilyNotificationTemplateCode.h
//

#define EvhFamilyNotificationTemplateCode_SCOPE @"family.notification"
#define EvhFamilyNotificationTemplateCode_FAMILY_JOIN_REQ_FOR_APPLICANT 1
#define EvhFamilyNotificationTemplateCode_FAMILY_JOIN_REQ_FOR_OPERATOR 2
#define EvhFamilyNotificationTemplateCode_FAMILY_JOIN_ADMIN_APPROVE_FOR_APPLICANT 3
#define EvhFamilyNotificationTemplateCode_FAMILY_JOIN_ADMIN_APPROVE_FOR_OTHER 4
#define EvhFamilyNotificationTemplateCode_FAMILY_JOIN_ADMIN_CORRECT_FOR_APPLICANT 5
#define EvhFamilyNotificationTemplateCode_FAMILY_JOIN_ADMIN_CORRECT_FOR_OTHER 6
#define EvhFamilyNotificationTemplateCode_FAMILY_JOIN_MEMBER_APPROVE_FOR_APPLICANT 7
#define EvhFamilyNotificationTemplateCode_FAMILY_JOIN_MEMBER_APPROVE_FOR_OPERATOR 8
#define EvhFamilyNotificationTemplateCode_FAMILY_JOIN_MEMBER_APPROVE_FOR_OTHER 9
#define EvhFamilyNotificationTemplateCode_FAMILY_JOIN_ADMIN_REJECT_FOR_APPLICANT 10
#define EvhFamilyNotificationTemplateCode_FAMILY_JOIN_ADMIN_REJECT_FOR_OTHER 11
#define EvhFamilyNotificationTemplateCode_FAMILY_JOIN_MEMBER_REJECT_FOR_APPLICANT 12
#define EvhFamilyNotificationTemplateCode_FAMILY_JOIN_MEMBER_REJECT_FOR_OPERATOR 13
#define EvhFamilyNotificationTemplateCode_FAMILY_JOIN_MEMBER_REJECT_FOR_OTHER 14
#define EvhFamilyNotificationTemplateCode_FAMILY_MEMBER_LEAVE_FOR_APPLICANT 15
#define EvhFamilyNotificationTemplateCode_FAMILY_MEMBER_LEAVE_FOR_OTHER 16
#define EvhFamilyNotificationTemplateCode_FAMILY_MEMBER_REVOKE_FOR_APPLICANT 17
#define EvhFamilyNotificationTemplateCode_FAMILY_MEMBER_REVOKE_FOR_OPERATOR 18
#define EvhFamilyNotificationTemplateCode_FAMILY_MEMBER_REVOKE_FOR_OTHER 19
#define EvhFamilyNotificationTemplateCode_FAMILY_MEMBER_QUICK_APPLICANT 20
