//
// EvhGroupAdminNotificationTemplateCode.h
//

#define EvhGroupAdminNotificationTemplateCode_SCOPE @"group.admin.notification"
#define EvhGroupAdminNotificationTemplateCode_GROUP_ADMINROLE_REQ_FOR_APPLICANT 1
#define EvhGroupAdminNotificationTemplateCode_GROUP_ADMINROLE_REQ_FOR_OPERATOR 2
#define EvhGroupAdminNotificationTemplateCode_GROUP_ADMINROLE_APPROVE_FOR_APPLICANT 3
#define EvhGroupAdminNotificationTemplateCode_GROUP_ADMINROLE_APPROVE_FOR_OPERATOR 4
#define EvhGroupAdminNotificationTemplateCode_GROUP_ADMINROLE_APPROVE_FOR_OTHER 5
#define EvhGroupAdminNotificationTemplateCode_GROUP_ADMINROLE_REJECT_FOR_APPLICANT 6
#define EvhGroupAdminNotificationTemplateCode_GROUP_ADMINROLE_REJECT_FOR_OPERATOR 7
#define EvhGroupAdminNotificationTemplateCode_GROUP_ADMINROLE_REJECT_FOR_OTHER 8
#define EvhGroupAdminNotificationTemplateCode_GROUP_ADMINROLE_INVITATION_REQ_FOR_APPLICANT 9
#define EvhGroupAdminNotificationTemplateCode_GROUP_ADMINROLE_INVITATION_REQ_FOR_OPERATOR 10
#define EvhGroupAdminNotificationTemplateCode_GROUP_ADMINROLE_INVITATION_ACCEPT_FOR_APPLICANT 11
#define EvhGroupAdminNotificationTemplateCode_GROUP_ADMINROLE_INVITATION_ACCEPT_FOR_OPERATOR 12
#define EvhGroupAdminNotificationTemplateCode_GROUP_ADMINROLE_INVITATION_ACCEPT_FOR_OTHER 13
#define EvhGroupAdminNotificationTemplateCode_GROUP_ADMINROLE_INVITATION_REJECT_FOR_APPLICANT 14
#define EvhGroupAdminNotificationTemplateCode_GROUP_ADMINROLE_INVITATION_REJECT_FOR_OPERATOR 15
#define EvhGroupAdminNotificationTemplateCode_GROUP_ADMINROLE_INVITATION_REJECT_FOR_OTHER 16
#define EvhGroupAdminNotificationTemplateCode_GROUP_ADMINROLE_LEAVE_FOR_OPERATOR 17
#define EvhGroupAdminNotificationTemplateCode_GROUP_ADMINROLE_LEAVE_FOR_OTHER 18
#define EvhGroupAdminNotificationTemplateCode_GROUP_ADMINROLE_INVOKE_FOR_APPLICANT 20
#define EvhGroupAdminNotificationTemplateCode_GROUP_ADMINROLE_INVOKE_FOR_OPERATOR 19
#define EvhGroupAdminNotificationTemplateCode_GROUP_ADMINROLE_INVOKE_FOR_OTHER 21
#define EvhGroupAdminNotificationTemplateCode_GROUP_ADMINROLE_FREE_INVITATION_FOR_APPLICANT 22
#define EvhGroupAdminNotificationTemplateCode_GROUP_ADMINROLE_FREE_INVITATION_FOR_OPERATOR 23
#define EvhGroupAdminNotificationTemplateCode_GROUP_ADMINROLE_FREE_INVITATION_FOR_OTHER 24
