//
// EvhGroupNotificationTemplateCode.h
//

#define EvhGroupNotificationTemplateCode_SCOPE @"group.notification"
#define EvhGroupNotificationTemplateCode_GROUP_FREE_JOIN_REQ_FOR_APPLICANT 1
#define EvhGroupNotificationTemplateCode_GROUP_FREE_JOIN_REQ_FOR_OTHER 2
#define EvhGroupNotificationTemplateCode_GROUP_AUTH_JOIN_REQ_FOR_APPLICANT 3
#define EvhGroupNotificationTemplateCode_GROUP_AUTH_JOIN_REQ_FOR_OPERATOR 4
#define EvhGroupNotificationTemplateCode_GROUP_AUTH_JOIN_APPROVE_FOR_APPLICANT 5
#define EvhGroupNotificationTemplateCode_GROUP_AUTH_JOIN_APPROVE_FOR_OPERATOR 6
#define EvhGroupNotificationTemplateCode_GROUP_AUTH_JOIN_APPROVE_FOR_OTHER 7
#define EvhGroupNotificationTemplateCode_GROUP_AUTH_JOIN_REJECT_FOR_APPLICANT 8
#define EvhGroupNotificationTemplateCode_GROUP_AUTH_JOIN_REJECT_FOR_OPERATOR 9
#define EvhGroupNotificationTemplateCode_GROUP_AUTH_JOIN_REJECT_FOR_OTHER 10
#define EvhGroupNotificationTemplateCode_GROUP_FREE_JOIN_INVITATION_REQ_FOR_APPLICANT 11
#define EvhGroupNotificationTemplateCode_GROUP_FREE_JOIN_INVITATION_REQ_FOR_OPERATOR 12
#define EvhGroupNotificationTemplateCode_GROUP_FREE_JOIN_INVITATION_REQ_FOR_OTHER 13
#define EvhGroupNotificationTemplateCode_GROUP_AUTH_JOIN_INVITATION_REQ_FOR_APPLICANT 14
#define EvhGroupNotificationTemplateCode_GROUP_AUTH_JOIN_INVITATION_REQ_FOR_OPERATOR 15
#define EvhGroupNotificationTemplateCode_GROUP_AUTH_JOIN_INVITATION_REQ_FOR_OTHER 16
#define EvhGroupNotificationTemplateCode_GROUP_JOIN_INVITATION_ACCEPT_FOR_APPLICANT 17
#define EvhGroupNotificationTemplateCode_GROUP_JOIN_INVITATION_ACCEPT_FOR_OPERATOR 18
#define EvhGroupNotificationTemplateCode_GROUP_JOIN_INVITATION_ACCEPT_FOR_OTHER 19
#define EvhGroupNotificationTemplateCode_GROUP_JOIN_INVITATION_REJECT_FOR_APPLICANT 20
#define EvhGroupNotificationTemplateCode_GROUP_JOIN_INVITATION_REJECT_FOR_OPERATOR 21
#define EvhGroupNotificationTemplateCode_GROUP_JOIN_INVITATION_REJECT_FOR_OTHER 22
#define EvhGroupNotificationTemplateCode_GROUP_MEMBER_LEAVE_FOR_OPERATOR 23
#define EvhGroupNotificationTemplateCode_GROUP_MEMBER_LEAVE_FOR_OTHER 24
#define EvhGroupNotificationTemplateCode_GROUP_MEMBER_INVOKE_FOR_APPLICANT 25
#define EvhGroupNotificationTemplateCode_GROUP_MEMBER_INVOKE_FOR_OPERATOR 26
#define EvhGroupNotificationTemplateCode_GROUP_MEMBER_INVOKE_FOR_OTHER 27
#define EvhGroupNotificationTemplateCode_GROUP_MEMBER_PUBLIC_APPLICANT 28
#define EvhGroupNotificationTemplateCode_GROUP_MEMBER_PUBLIC_MEMBER_CHANGE 29
#define EvhGroupNotificationTemplateCode_GROUP_MEMBER_DELETED_ADMIN 30
#define EvhGroupNotificationTemplateCode_GROUP_MEMBER_DELETED_OPERATOR 31
#define EvhGroupNotificationTemplateCode_GROUP_MEMBER_DELETE_MEMBER 32
#define EvhGroupNotificationTemplateCode_GROUP_RECOMMEND 33
#define EvhGroupNotificationTemplateCode_GROUP_MEMBER_DELETED_CLUB_ADMIN 34
#define EvhGroupNotificationTemplateCode_GROUP_MEMBER_DELETED_CLUB_OPERATOR 35
