//
// EvhNewsServiceErrorCode.h
//

#define EvhNewsServiceErrorCode_SCOPE @"news"
#define EvhNewsServiceErrorCode_ERROR_NEWS_OWNER_TYPE_INVALID 10001
#define EvhNewsServiceErrorCode_ERROR_NEWS_OWNER_ID_INVALID 10002
#define EvhNewsServiceErrorCode_ERROR_NEWS_NEWSTOKEN_INVALID 10003
#define EvhNewsServiceErrorCode_ERROR_NEWS_COMMENT_CONTENT_TYPE_INVALID 10004
#define EvhNewsServiceErrorCode_ERROR_NEWS_NEWSID_COMMENTID_NOT_MATCH 10005
#define EvhNewsServiceErrorCode_ERROR_NEWS_SCENETOKEN_INVALID 10006
#define EvhNewsServiceErrorCode_ERROR_NEWS_PROCESS_EXCEL_ERROR 10007
#define EvhNewsServiceErrorCode_ERROR_NEWS_CONTENT_URL_INVALID 10008
