//
// EvhOrganizationServiceErrorCode.h
//

#define EvhOrganizationServiceErrorCode_SCOPE @"organization"
#define EvhOrganizationServiceErrorCode_ERROR_NO_PRIVILEGED 100001
#define EvhOrganizationServiceErrorCode_ERROR_PHONE_ALREADY_EXIST 100010
#define EvhOrganizationServiceErrorCode_ERROR_INVALID_PARAMETER 100011
#define EvhOrganizationServiceErrorCode_ERROR_PHONE_ALREADY_APPLY 100012
#define EvhOrganizationServiceErrorCode_ERROR_FILE_IS_EMPTY 100100
#define EvhOrganizationServiceErrorCode_ERROR_ORG_TASK_NOT_EXIST 100201
#define EvhOrganizationServiceErrorCode_ERROR_ORG_TASK_ALREADY_PROCESSED 100201
#define EvhOrganizationServiceErrorCode_ERROR_ORG_TASK_NOT_ASSIGNED_PERSONNEL 100202
#define EvhOrganizationServiceErrorCode_ERROR_ORG_TASK_CANNOT_OPERATE 100203
#define EvhOrganizationServiceErrorCode_ERROR_FILE_CONTEXT_ISNULL 200001
#define EvhOrganizationServiceErrorCode_ERROR_COMMUNITY_EXISTS 300001
#define EvhOrganizationServiceErrorCode_ERROR_ENTERPRISE_CONTACT_NOT_FOUND 10101
#define EvhOrganizationServiceErrorCode_ERROR_PARAMETER_NOT_EXIST 400001
#define EvhOrganizationServiceErrorCode_ERROR_OBJECT_NOT_EXIST 400002
