//
// EvhOrganizationNotificationTemplateCode.h
//

#define EvhOrganizationNotificationTemplateCode_SCOPE @"organization.notification"
#define EvhOrganizationNotificationTemplateCode_ORGANIZATION_MEMBER_APPROVE_FOR_APPLICANT 1
#define EvhOrganizationNotificationTemplateCode_ORGANIZATION_MEMBER_APPROVE_FOR_MANAGER 2
#define EvhOrganizationNotificationTemplateCode_ORGANIZATION_MEMBER_REJECT_FOR_APPLICANT 3
#define EvhOrganizationNotificationTemplateCode_ORGANIZATION_MEMBER_REJECT_FOR_MANAGER 4
#define EvhOrganizationNotificationTemplateCode_ORGANIZATION_ASSIGN_TOPIC_FOR_COMMENT 5
#define EvhOrganizationNotificationTemplateCode_ORGANIZATION_ASSIGN_TOPIC_FOR_MEMBER 6
#define EvhOrganizationNotificationTemplateCode_ORGANIZATION_ASSIGN_TOPIC_BY_MANAGER_FOR_MEMBER 7
#define EvhOrganizationNotificationTemplateCode_ORGANIZATION_MEMBER_DELETE_FOR_MANAGER 8
#define EvhOrganizationNotificationTemplateCode_ORGANIZATION_TASK_ACCEPT_COMMENT 10
#define EvhOrganizationNotificationTemplateCode_ORGANIZATION_TASK_NEW 11
#define EvhOrganizationNotificationTemplateCode_ORGANIZATION_TASK_PROCESSING 12
#define EvhOrganizationNotificationTemplateCode_ORGANIZATION_TASK_PROCESSING_COMMENT 13
#define EvhOrganizationNotificationTemplateCode_ORGANIZATION_TASK_REFUSE 14
#define EvhOrganizationNotificationTemplateCode_ORGANIZATION_TASK_FINISH 15
#define EvhOrganizationNotificationTemplateCode_ORGANIZATION_TASK_FINISH_COMMENT 16
#define EvhOrganizationNotificationTemplateCode_ORGANIZATION_APPLY_FOR_CONTACT 17
