//
// EvhOAuth2ServiceErrorCode.h
//

#define EvhOAuth2ServiceErrorCode_SCOPE @"oauth2"
#define EvhOAuth2ServiceErrorCode_ERROR_INVALID_REQUEST 1
#define EvhOAuth2ServiceErrorCode_ERROR_UNAUTHORIZED_CLIENT 2
#define EvhOAuth2ServiceErrorCode_ERROR_ACCESS_DENIED 3
#define EvhOAuth2ServiceErrorCode_ERROR_UNSUPPORTED_RESPONSE_TYPE 4
#define EvhOAuth2ServiceErrorCode_ERROR_INVALID_SCOPE 5
#define EvhOAuth2ServiceErrorCode_ERROR_SERVER_ERROR 6
#define EvhOAuth2ServiceErrorCode_ERROR_SERVER_BUSY 7
#define EvhOAuth2ServiceErrorCode_ERROR_INVALID_CLIENT 8
#define EvhOAuth2ServiceErrorCode_ERROR_INVALID_GRANT 9
#define EvhOAuth2ServiceErrorCode_ERROR_UNSUPPORTED_GRANT_TYPE 10
