//
// EvhPropertyServiceErrorCode.h
//

#define EvhPropertyServiceErrorCode_SCOPE @"pm"
#define EvhPropertyServiceErrorCode_ERROR_INVALID_FAMILY 10001
#define EvhPropertyServiceErrorCode_ERROR_INVALID_ADDRESS 10002
#define EvhPropertyServiceErrorCode_ERROR_INVALID_BILL 10003
#define EvhPropertyServiceErrorCode_ERROR_INVALID_TOPIC 11001
#define EvhPropertyServiceErrorCode_ERROR_INVALID_COMMENT 12002
#define EvhPropertyServiceErrorCode_ERROR_INVALID_TASK 12003
#define EvhPropertyServiceErrorCode_ERROR_INVALID_TASK_STATUS 12004
