//
// EvhPunchServiceErrorCode.h
//

#define EvhPunchServiceErrorCode_SCOPE @"punch"
#define EvhPunchServiceErrorCode_ERROR_USER_NOT_IN_PUNCHAREA 10001
#define EvhPunchServiceErrorCode_ERROR_QUERY_YEAR_ERROR 10002
#define EvhPunchServiceErrorCode_ERROR_PUNCH_RULE 10003
#define EvhPunchServiceErrorCode_ERROR_PUNCH_ADD_DAYLOG 10004
#define EvhPunchServiceErrorCode_ERROR_PUNCH_REFRESH_DAYLOG 10005
#define EvhPunchServiceErrorCode_ERROR_ENTERPRISE_DIDNOT_SETTING 10010
