//
// EvhQualityServiceErrorCode.h
//

#define EvhQualityServiceErrorCode_SCOPE @"quality"
#define EvhQualityServiceErrorCode_ERROR_HECHA_MEMBER_EMPTY 10001
#define EvhQualityServiceErrorCode_ERROR_TASK_NOT_EXIST 10002
#define EvhQualityServiceErrorCode_ERROR_STANDARD_NOT_EXIST 10003
#define EvhQualityServiceErrorCode_ERROR_CATEGORY_NOT_EXIST 10004
#define EvhQualityServiceErrorCode_ERROR_FACTOR_NOT_EXIST 10005
#define EvhQualityServiceErrorCode_ATTACHMENT_TEXT 10006
#define EvhQualityServiceErrorCode_ERROR_CATEGORY_HAS_STANDARD 10007
#define EvhQualityServiceErrorCode_ERROR_TASK_IS_CLOSED 10008
#define EvhQualityServiceErrorCode_ERROR_CREATE_EXCEL 10009
#define EvhQualityServiceErrorCode_ERROR_DOWNLOAD_EXCEL 10010
#define EvhQualityServiceErrorCode_ERROR_ASSIGN_TO_ONESELF 10011
