//
// EvhQualityNotificationTemplateCode.h
//

#define EvhQualityNotificationTemplateCode_SCOPE @"quality.notification"
#define EvhQualityNotificationTemplateCode_GENERATE_QUALITY_TASK_NOTIFY_EXECUTOR 1
#define EvhQualityNotificationTemplateCode_ASSIGN_TASK_NOTIFY_OPERATOR 2
#define EvhQualityNotificationTemplateCode_ASSIGN_TASK_MSG 3
#define EvhQualityNotificationTemplateCode_UNQUALIFIED_TASK_NOTIFY_EXECUTOR 4
