//
// EvhRentalServiceErrorCode.h
//

#define EvhRentalServiceErrorCode_SCOPE @"rental"
#define EvhRentalServiceErrorCode_ERROR_RESERVE_TOO_EARLY 10001
#define EvhRentalServiceErrorCode_ERROR_RESERVE_TOO_LATE 10002
#define EvhRentalServiceErrorCode_ERROR_HAVE_BILL 10003
#define EvhRentalServiceErrorCode_ERROR_NO_ENOUGH_SITES 10004
#define EvhRentalServiceErrorCode_ERROR_BILL_OVERTIME 10005
#define EvhRentalServiceErrorCode_ERROR_CANCEL_OVERTIME 10006
#define EvhRentalServiceErrorCode_ERROR_DID_NOT_PAY 10007
#define EvhRentalServiceErrorCode_ERROR_NOT_SUCCESS 10008
#define EvhRentalServiceErrorCode_ERROR_NOT_COMPLETE 10009
#define EvhRentalServiceErrorCode_ERROR_ORDER_DUPLICATE 10010
#define EvhRentalServiceErrorCode_ERROR_CREATE_EXCEL 10011
#define EvhRentalServiceErrorCode_ERROR_DOWNLOAD_EXCEL 10012
#define EvhRentalServiceErrorCode_ERROR_NO_ENOUGH_ITEMS 10020
#define EvhRentalServiceErrorCode_ERROR_REPEAT_SITE_ASSGIN 11000
#define EvhRentalServiceErrorCode_ERROR_SITE_ASSGIN_NULL 11001
#define EvhRentalServiceErrorCode_ERROR_LOOP_TOOMUCH 12000
