//
// EvhRentalRentalServiceErrorCode.h
//

#define EvhRentalRentalServiceErrorCode_SCOPE @"rental"
#define EvhRentalRentalServiceErrorCode_ERROR_RESERVE_TOO_EARLY 10001
#define EvhRentalRentalServiceErrorCode_ERROR_RESERVE_TOO_LATE 10002
#define EvhRentalRentalServiceErrorCode_ERROR_HAVE_BILL 10003
#define EvhRentalRentalServiceErrorCode_ERROR_NO_ENOUGH_SITES 10004
#define EvhRentalRentalServiceErrorCode_ERROR_BILL_OVERTIME 10005
#define EvhRentalRentalServiceErrorCode_ERROR_CANCEL_OVERTIME 10006
#define EvhRentalRentalServiceErrorCode_ERROR_DID_NOT_PAY 10007
#define EvhRentalRentalServiceErrorCode_ERROR_NOT_SUCCESS 10008
#define EvhRentalRentalServiceErrorCode_ERROR_NOT_COMPLETE 10009
#define EvhRentalRentalServiceErrorCode_ERROR_ORDER_DUPLICATE 10010
#define EvhRentalRentalServiceErrorCode_ERROR_CREATE_EXCEL 10011
#define EvhRentalRentalServiceErrorCode_ERROR_DOWNLOAD_EXCEL 10012
#define EvhRentalRentalServiceErrorCode_ERROR_RENTAL_RULE_NOT_FOUND 10013
