//
// EvhUserServiceErrorCode.h
//

#define EvhUserServiceErrorCode_SCOPE @"user"
#define EvhUserServiceErrorCode_ERROR_INVALID_SIGNUP_TOKEN 10000
#define EvhUserServiceErrorCode_ERROR_INVALID_LOGIN_TOKEN 10001
#define EvhUserServiceErrorCode_ERROR_OLD_PASSWORD_NOT_MATCH 10002
#define EvhUserServiceErrorCode_ERROR_INVALD_TOKEN_STATUS 10003
#define EvhUserServiceErrorCode_ERROR_INVALID_VERIFICATION_CODE 10004
#define EvhUserServiceErrorCode_ERROR_UNABLE_TO_LOCATE_USER 10005
#define EvhUserServiceErrorCode_ERROR_USER_NOT_EXIST 10006
#define EvhUserServiceErrorCode_ERROR_INVALID_PASSWORD 10007
#define EvhUserServiceErrorCode_ERROR_INVALID_MESSAGE_JSON_DATA 10008
#define EvhUserServiceErrorCode_ERROR_MISSING_MESSAGE_CHANNEL 10009
#define EvhUserServiceErrorCode_ERROR_ACCOUNT_NOT_ACTIVATED 10010
#define EvhUserServiceErrorCode_ERROR_IDENTIFIER_ALREADY_CLAIMED 10011
#define EvhUserServiceErrorCode_ERROR_ACCOUNT_NAME_ALREADY_EXISTS 10012
#define EvhUserServiceErrorCode_ERROR_ACCOUNT_PASSWORD_NOT_SET 10013
#define EvhUserServiceErrorCode_ERROR_INVALID_INVITATION_CODE 10014
#define EvhUserServiceErrorCode_ERROR_INVITATION_CODE 100015
#define EvhUserServiceErrorCode_ERROR_INVALID_PARAMS 100016
#define EvhUserServiceErrorCode_ERROR_INVALID_PERMISSION 100017
#define EvhUserServiceErrorCode_ERROR_UNAUTHENTITICATION 401
#define EvhUserServiceErrorCode_ERROR_FORBIDDEN 403
#define EvhUserServiceErrorCode_ERROR_FILE_CONTEXT_ISNULL 200001
#define EvhUserServiceErrorCode_ERROR_INVALID_SCENE_TOKEN 100101
