//
// EvhVideoconfNotificationTemplateCode.h
//

#define EvhVideoconfNotificationTemplateCode_SCOPE @"videoconf.notification"
#define EvhVideoconfNotificationTemplateCode_VIDEOCONF_MSG_SUBJECT 1
#define EvhVideoconfNotificationTemplateCode_VIDEOCONF_CONFTIME 2
#define EvhVideoconfNotificationTemplateCode_VIDEOCONF_CONFDESCRIBTION 3
