package com.everhomes.rest.news;

public interface NewsServiceErrorCode {
	String SCOPE = "news";
	
	int ERROR_NEWS_OWNER_TYPE_INVALID = 10001;
	int ERROR_NEWS_OWNER_ID_INVALID = 10002;
	int ERROR_NEWS_NEWSTOKEN_INVALID = 10003;
	int ERROR_NEWS_COMMENT_CONTENT_TYPE_INVALID = 10004;
	int ERROR_NEWS_NEWSID_COMMENTID_NOT_MATCH = 10005;
	int ERROR_NEWS_SCENETOKEN_INVALID = 10006;
	int ERROR_NEWS_PROCESS_EXCEL_ERROR = 10007;
	int ERROR_NEWS_CONTENT_URL_INVALID = 10008;

	int ERROR_NEWS_VISIBLE_INVALID = 10009;

}
