package com.everhomes.rest.news;

public interface NewsServiceErrorCode {
	String SCOPE = "news";
	
	int ERROR_NEWS_OWNER_TYPE_INVALID = 10001;
	int ERROR_NEWS_OWNER_ID_INVALID = 10002;
	int ERROR_NEWS_NEWSTOKEN_INVALID = 10003;
	int ERROR_NEWS_COMMENT_CONTENT_TYPE_INVALID = 10004;
	int ERROR_NEWS_NEWSID_COMMENTID_NOT_MATCH = 10005;
	int ERROR_NEWS_SCENETOKEN_INVALID = 10006;
	int ERROR_NEWS_PROCESS_EXCEL_ERROR = 10007;
	int ERROR_NEWS_CONTENT_URL_INVALID = 10008;

	int ERROR_NEWS_VISIBLE_INVALID = 10009;
	int ERROR_PM_ID_INVALID = 10010;
	int ERROR_PROJECT_ID_INVALID = 10011;
	int ERROR_USER_PROJECT_NOT_LEGAL = 10012;
	int ERROR_PORTAL_VERSION_NOT_FOUND = 10013;
	int ERROR_NEWS_MODULE_NOT_FOUND = 10014;
	int ERROR_ENCODE_STRING_EXCEPTION = 10015;
	int ERROR_PORTAL_ITEM_GROUP_NOT_FOUND = 10016;
	int ERROR_COMMENT_NOT_EXIST_OR_DELETED = 10017; //评论不存在或已被删除
	int ERROR_INPUT_PARAM_INVALID = 10018; //接口参数异常

	// openapi 错误码
	int ERROR_NEWS_NOT_FOUND = 11000; //文章不存在
	int ERROR_PARAMS_NOT_VALID = 11001; //参数不合法
	int ERROR_NEWS_OWNER_NOT_FOUND = 11002; //项目不存在

	int ERROR_NOT_LEGAL_REQUEST = 90000; //非法访问
	int ERROR_APPKEY_NAMESPACE_MAP_NOT_FOUND = 90001; //未找到appkey对应namespaceId

}
