package com.everhomes.business;

import java.util.List;

import com.everhomes.rest.address.ApartmentDTO;
import com.everhomes.rest.address.ApartmentFloorDTO;
import com.everhomes.rest.address.BuildingDTO;
import com.everhomes.rest.address.CommunityDTO;
import com.everhomes.rest.address.ListApartmentFloorCommand;
import com.everhomes.rest.address.ListPropApartmentsByKeywordCommand;
import com.everhomes.rest.address.admin.ListBuildingByCommunityIdsCommand;
import com.everhomes.rest.business.BusinessAsignedNamespaceCommand;
import com.everhomes.rest.business.BusinessDTO;
import com.everhomes.rest.business.CancelFavoriteBusinessCommand;
import com.everhomes.rest.business.DeleteBusinessCommand;
import com.everhomes.rest.business.FavoriteBusinessCommand;
import com.everhomes.rest.business.FavoriteBusinessesCommand;
import com.everhomes.rest.business.FindBusinessByIdCommand;
import com.everhomes.rest.business.GetBusinessesByCategoryCommand;
import com.everhomes.rest.business.GetBusinessesByCategoryCommandResponse;
import com.everhomes.rest.business.GetBusinessesByScopeCommand;
import com.everhomes.rest.business.GetReceivedCouponCountCommand;
import com.everhomes.rest.business.ListBusinessByCommonityIdCommand;
import com.everhomes.rest.business.ListBusinessByKeywordCommand;
import com.everhomes.rest.business.ListBusinessByKeywordCommandResponse;
import com.everhomes.rest.business.ListUserByIdentifierCommand;
import com.everhomes.rest.business.ListUserByKeywordCommand;
import com.everhomes.rest.business.ReSyncBusinessCommand;
import com.everhomes.rest.business.SyncBusinessCommand;
import com.everhomes.rest.business.SyncDeleteBusinessCommand;
import com.everhomes.rest.business.UpdateBusinessCommand;
import com.everhomes.rest.business.UpdateBusinessDistanceCommand;
import com.everhomes.rest.business.UpdateReceivedCouponCountCommand;
import com.everhomes.rest.business.UserFavoriteCommand;
import com.everhomes.rest.business.admin.CreateBusinessAdminCommand;
import com.everhomes.rest.business.admin.DeletePromoteBusinessAdminCommand;
import com.everhomes.rest.business.admin.ListBusinessesByKeywordAdminCommand;
import com.everhomes.rest.business.admin.ListBusinessesByKeywordAdminCommandResponse;
import com.everhomes.rest.business.admin.PromoteBusinessAdminCommand;
import com.everhomes.rest.business.admin.RecommendBusinessesAdminCommand;
import com.everhomes.rest.community.GetCommunitiesByNameAndCityIdCommand;
import com.everhomes.rest.community.GetCommunityByIdCommand;
import com.everhomes.rest.openapi.CreateBusinessGroupCommand;
import com.everhomes.rest.openapi.CreateBusinessGroupResponse;
import com.everhomes.rest.openapi.JoinBusinessGroupCommand;
import com.everhomes.rest.openapi.UpdateUserCouponCountCommand;
import com.everhomes.rest.openapi.UpdateUserOrderCountCommand;
import com.everhomes.rest.openapi.UserCouponsCommand;
import com.everhomes.rest.openapi.UserServiceAddressDTO;
import com.everhomes.rest.openapi.ValidateUserPassCommand;
import com.everhomes.rest.region.ListRegionByKeywordCommand;
import com.everhomes.rest.region.ListRegionCommand;
import com.everhomes.rest.region.RegionDTO;
import com.everhomes.rest.ui.launchpad.FavoriteBusinessesBySceneCommand;
import com.everhomes.rest.ui.user.UserProfileDTO;
import com.everhomes.rest.user.GetUserDefaultAddressCommand;
import com.everhomes.rest.user.ListUserCommand;
import com.everhomes.rest.user.UserDtoForBiz;
import com.everhomes.rest.user.UserInfo;
import com.everhomes.util.Tuple;

public interface BusinessService {
    void syncBusiness(SyncBusinessCommand cmd);
    void updateBusiness(UpdateBusinessCommand cmd);
    void deleteBusiness(DeleteBusinessCommand cmd);
    BusinessDTO findBusinessById(Long id);
    List<BusinessDTO> getBusinessesByScope(GetBusinessesByScopeCommand cmd);
    GetBusinessesByCategoryCommandResponse getBusinessesByCategory(GetBusinessesByCategoryCommand cmd);
    ListBusinessesByKeywordAdminCommandResponse listBusinessesByKeyword(ListBusinessesByKeywordAdminCommand cmd);
    void recommendBusiness(RecommendBusinessesAdminCommand cmd);
    void syncDeleteBusiness(SyncDeleteBusinessCommand cmd);
    void createBusiness(CreateBusinessAdminCommand cmd);
    void syncUserFavorite(UserFavoriteCommand cmd);
    void syncUserCancelFavorite(UserFavoriteCommand cmd);
    Byte findBusinessFavoriteStatus(UserFavoriteCommand cmd);
    void favoriteBusiness(FavoriteBusinessCommand cmd);
    void cancelFavoriteBusiness(CancelFavoriteBusinessCommand cmd);
    void promoteBusiness(PromoteBusinessAdminCommand cmd);
    void deletePromoteBusiness(DeletePromoteBusinessAdminCommand cmd);
	UserServiceAddressDTO getUserDefaultAddress(GetUserDefaultAddressCommand cmd);
	List<UserDtoForBiz> listUser(ListUserCommand cmd);
	void favoriteBusinesses(FavoriteBusinessesCommand cmd);
	void updateBusinessDistance(UpdateBusinessDistanceCommand cmd);
	BusinessDTO findBusinessById(FindBusinessByIdCommand cmd);
	ListBusinessByKeywordCommandResponse listBusinessByKeyword(ListBusinessByKeywordCommand cmd);
	List<UserInfo> listUserByKeyword(ListUserByKeywordCommand cmd);
	List<String> listBusinessByCommonityId(ListBusinessByCommonityIdCommand cmd);
	List<UserInfo> listUserByIdentifier(ListUserByIdentifierCommand cmd);
	void openBusinessAssignedNamespace(BusinessAsignedNamespaceCommand cmd);
	void closeBusinessAssignedNamespace(BusinessAsignedNamespaceCommand cmd);
	void updateReceivedCouponCount(UpdateReceivedCouponCountCommand cmd);
	UserProfileDTO getReceivedCouponCount(GetReceivedCouponCountCommand cmd);
	void reSyncBusiness(ReSyncBusinessCommand cmd);
	List<BuildingDTO> listBuildingsByKeyword(ListBuildingByCommunityIdsCommand cmd);
	Tuple<Integer, List<ApartmentDTO>> listApartmentsByKeyword(ListPropApartmentsByKeywordCommand cmd);
	List<CommunityDTO> getCommunitiesByNameAndCityId(GetCommunitiesByNameAndCityIdCommand cmd);
	CommunityDTO getCommunityById(GetCommunityByIdCommand cmd);
	List<RegionDTO> listRegionByKeyword(ListRegionByKeywordCommand cmd);
	
	void favoriteBusinessesByScene(FavoriteBusinessesBySceneCommand cmd, String baseScene);
	
	List<BusinessDTO> getBusinesses(List<Long> categoryIds,Long communityId);
	Integer findUserCouponCount(UserCouponsCommand cmd);
	void updateUserCouponCount(UpdateUserCouponCountCommand cmd);
	void addUserOrderCount(Long userId);
	void reduceUserOrderCount(Long userId);
	Integer findUserOrderCount(UserCouponsCommand cmd);
	void updateUserOrderCount(UpdateUserOrderCountCommand cmd);
	List<RegionDTO> listRegion(ListRegionCommand cmd);
	UserInfo validateUserPass(ValidateUserPassCommand cmd);
	CreateBusinessGroupResponse createBusinessGroup(CreateBusinessGroupCommand cmd);
	void joinBusinessGroup(JoinBusinessGroupCommand cmd);
	Tuple<Integer, List<ApartmentFloorDTO>> listApartmentFloor(ListApartmentFloorCommand cmd);
}
