delete from eh_launch_pad_items where id = 802;
delete from eh_launch_pad_items where id = 10303;
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('802', '1000000', '0', '0', '0', '/home', 'GovAgencies', 'SERVICE_HOT_LINE', '园区热线', 'cs://1/image/aW1hZ2UvTVRwaE56VTFNR0k1TlRJd016aGlOekJtT0RoaE9HVTNPVGRoTnpsbVpXRXpOUQ', '1', '1', '45', '', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'park_tourist');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES (10303, '1000000', '0', '0', '0', '/home', 'GovAgencies', 'SERVICE_HOT_LINE', '园区热线', 'cs://1/image/aW1hZ2UvTVRwaE56VTFNR0k1TlRJd016aGlOekJtT0RoaE9HVTNPVGRoTnpsbVpXRXpOUQ', '1', '1', '45', '', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'pm_admin');

INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('10170', '1000000', '0', '0', '0', '/home', 'Bizs', 'CONTACTS', '通讯录', 'cs://1/image/aW1hZ2UvTVRvMFpEUTNNbVF5WW1abU5XVXhNak16WTJOa1pHVTVZekl4TmpGalpERmlOdw', '1', '1', '46', '', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'park_tourist');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('10171', '1000000', '0', '0', '0', '/home', 'Bizs', 'CONTACTS', '通讯录', 'cs://1/image/aW1hZ2UvTVRvMFpEUTNNbVF5WW1abU5XVXhNak16WTJOa1pHVTVZekl4TmpGalpERmlOdw', '1', '1', '46', '', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'pm_admin');




-- 左邻广场
delete from eh_launch_pad_items where namespace_id = 0;
delete from eh_launch_pad_layouts where namespace_id = 0;


INSERT INTO `eh_launch_pad_layouts` (`id`, `namespace_id`, `name`, `layout_json`, `version_code`, `min_version_code`, `status`, `create_time`, `scene_type`) 
VALUES ('1', '0', 'ServiceMarketLayout', '{\"versionCode\":\"2016031201\",\"versionName\":\"3.4.0\",\"layoutName\":\"ServiceMarketLayout\",\"displayName\":\"服务市场\",\"groups\":[{\"groupName\":\"\",\"widget\":\"Banners\",\"instanceConfig\":{\"itemGroup\":\"Default\"},\"style\":\"Default\",\"defaultOrder\":1,\"separatorFlag\":0,\"separatorHeight\":0},{\"groupName\":\"\",\"widget\":\"Coupons\",\"instanceConfig\":{\"itemGroup\":\"Coupons\"},\"style\":\"Default\",\"defaultOrder\":3,\"separatorFlag\":1,\"separatorHeight\":21},{\"groupName\":\"商家服务\",\"widget\":\"Navigator\",\"instanceConfig\":{\"itemGroup\":\"Bizs\"},\"style\":\"Default\",\"defaultOrder\":5,\"separatorFlag\":0,\"separatorHeight\":0}]}', '2016031201', '0', '2', UTC_TIMESTAMP(), 'default');
INSERT INTO `eh_launch_pad_layouts` (`id`, `namespace_id`, `name`, `layout_json`, `version_code`, `min_version_code`, `status`, `create_time`, `scene_type`) 
VALUES ('2', '0', 'ServiceMarketLayout', '{\"versionCode\":\"2016031201\",\"versionName\":\"3.4.0\",\"layoutName\":\"ServiceMarketLayout\",\"displayName\":\"服务市场\",\"groups\":[{\"groupName\":\"\",\"widget\":\"Banners\",\"instanceConfig\":{\"itemGroup\":\"Default\"},\"style\":\"Default\",\"defaultOrder\":1,\"separatorFlag\":0,\"separatorHeight\":0},{\"groupName\":\"\",\"widget\":\"Coupons\",\"instanceConfig\":{\"itemGroup\":\"Coupons\"},\"style\":\"Default\",\"defaultOrder\":3,\"separatorFlag\":1,\"separatorHeight\":21},{\"groupName\":\"商家服务\",\"widget\":\"Navigator\",\"instanceConfig\":{\"itemGroup\":\"Bizs\"},\"style\":\"Default\",\"defaultOrder\":5,\"separatorFlag\":0,\"separatorHeight\":0}]}', '2016031201', '0', '2', UTC_TIMESTAMP(), 'park_tourist');
-- INSERT INTO `eh_launch_pad_layouts` (`id`, `namespace_id`, `name`, `layout_json`, `version_code`, `min_version_code`, `status`, `create_time`, `scene_type`) 
-- VALUES ('3', '0', 'ServiceMarketLayout', '{\"versionCode\":\"2016031201\",\"versionName\":\"3.4.0\",\"layoutName\":\"ServiceMarketLayout\",\"displayName\":\"服务市场\",\"groups\":[{\"groupName\":\"\",\"widget\":\"Banners\",\"instanceConfig\":{\"itemGroup\":\"Default\"},\"style\":\"Default\",\"defaultOrder\":1,\"separatorFlag\":0,\"separatorHeight\":0},{\"groupName\":\"\",\"widget\":\"Coupons\",\"instanceConfig\":{\"itemGroup\":\"Coupons\"},\"style\":\"Default\",\"defaultOrder\":3,\"separatorFlag\":1,\"separatorHeight\":21},{\"groupName\":\"商家服务\",\"widget\":\"Navigator\",\"instanceConfig\":{\"itemGroup\":\"Bizs\"},\"style\":\"Default\",\"defaultOrder\":5,\"separatorFlag\":0,\"separatorHeight\":0}]}', '2016031201', '0', '2', UTC_TIMESTAMP(), 'pm_admin');
INSERT INTO `eh_launch_pad_layouts` (`id`, `namespace_id`, `name`, `layout_json`, `version_code`, `min_version_code`, `status`, `create_time`, `scene_type`) 
VALUES ('4', '0', 'PmLayout', '{\"versionCode\":\"2015072815\",\"versionName\":\"3.4.0\",\"displayName\":\"物业首页\",\"layoutName\":\"PmLayout\",\"groups\":[{\"groupName\":\"\",\"widget\":\"Navigator\",\"instanceConfig\":{\"itemGroup\":\"GaActions\"},\"style\":\"Default\",\"defaultOrder\":2,\"separatorFlag\":1,\"separatorHeight\":21,\"columnCount\":4},{\"groupName\":\"\",\"widget\":\"Posts\",\"instanceConfig\":{\"itemGroup\":\"GaPosts\"},\"style\":\"Default\",\"defaultOrder\":3,\"separatorFlag\":0,\"separatorHeight\":0},{\"groupName\":\"CallPhone\",\"widget\":\"CallPhones\",\"instanceConfig\":{\"itemGroup\":\"CallPhones\",\"position\":\"bottom\"},\"style\":\"Default\",\"defaultOrder\":3,\"separatorFlag\":0,\"separatorHeight\":0}]}', '2015082914', '2015061701', '2', UTC_TIMESTAMP(), 'default');
INSERT INTO `eh_launch_pad_layouts` (`id`, `namespace_id`, `name`, `layout_json`, `version_code`, `min_version_code`, `status`, `create_time`, `scene_type`) 
VALUES ('5', '0', 'PmLayout', '{\"versionCode\":\"2015072815\",\"versionName\":\"3.4.0\",\"displayName\":\"物业首页\",\"layoutName\":\"PmLayout\",\"groups\":[{\"groupName\":\"\",\"widget\":\"Navigator\",\"instanceConfig\":{\"itemGroup\":\"GaActions\"},\"style\":\"Default\",\"defaultOrder\":2,\"separatorFlag\":1,\"separatorHeight\":21,\"columnCount\":4},{\"groupName\":\"\",\"widget\":\"Posts\",\"instanceConfig\":{\"itemGroup\":\"GaPosts\"},\"style\":\"Default\",\"defaultOrder\":3,\"separatorFlag\":0,\"separatorHeight\":0},{\"groupName\":\"CallPhone\",\"widget\":\"CallPhones\",\"instanceConfig\":{\"itemGroup\":\"CallPhones\",\"position\":\"bottom\"},\"style\":\"Default\",\"defaultOrder\":3,\"separatorFlag\":0,\"separatorHeight\":0}]}', '2015082914', '2015061701', '2', UTC_TIMESTAMP(), 'park_tourist');
-- INSERT INTO `eh_launch_pad_layouts` (`id`, `namespace_id`, `name`, `layout_json`, `version_code`, `min_version_code`, `status`, `create_time`, `scene_type`) 
-- VALUES ('6', '0', 'PmLayout', '{\"versionCode\":\"2015072815\",\"versionName\":\"3.4.0\",\"displayName\":\"物业首页\",\"layoutName\":\"PmLayout\",\"groups\":[{\"groupName\":\"\",\"widget\":\"Navigator\",\"instanceConfig\":{\"itemGroup\":\"GaActions\"},\"style\":\"Default\",\"defaultOrder\":2,\"separatorFlag\":1,\"separatorHeight\":21,\"columnCount\":4},{\"groupName\":\"\",\"widget\":\"Posts\",\"instanceConfig\":{\"itemGroup\":\"GaPosts\"},\"style\":\"Default\",\"defaultOrder\":3,\"separatorFlag\":0,\"separatorHeight\":0},{\"groupName\":\"CallPhone\",\"widget\":\"CallPhones\",\"instanceConfig\":{\"itemGroup\":\"CallPhones\",\"position\":\"bottom\"},\"style\":\"Default\",\"defaultOrder\":3,\"separatorFlag\":0,\"separatorHeight\":0}]}', '2015082914', '2015061701', '2', UTC_TIMESTAMP(), 'pm_admin');

INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('1', '0', '0', '0', '0', '/home', 'Coupons', '优倍商城', '优倍商城', 'cs://1/image/aW1hZ2UvTVRvMk16aGhObVJqT1dFd1lqRTBOR0kwTnprMk56SmpNVEE1WVdJM01qQmtOQQ', '5', '1', '14', '{\"url\":\"https://zuolin.com/evh/user/appServiceAccess?appKey=bf925ea0-a5e0-11e4-a68c-00163e024632&type=simple&uri=http%3a%2f%2fm.ubive.com%2findex.php%3futm_source%3d297321423546#zlservice_redirect\"}', '2', '0', '1', '1', NULL, '0', NULL, NULL, NULL, '0', 'default');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('2', '0', '0', '0', '0', '/home', 'Coupons', '优惠券', '优惠券', 'cs://1/image/aW1hZ2UvTVRwbU5UQTRNbUU1TlRObU5qRmlZVGhtTnpSak1qQTBOekkzWm1JNU9UQm1PQQ', '3', '1', '14', '{\"url\":\"https://biz.zuolin.com/zl-ec/rest/service/front/logon?hideNavigationBar=1&sourceUrl=https://biz.zuolin.com%2Fweb%2Fapp%2Fuser%2Findex.html%23%2Fpromotion%2Fall%3F_k%3Dzlbiz#sign_suffix\"}', '1', '0', '1', '1', NULL, '0', NULL, NULL, NULL, '0', 'default');

INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('3', '0', '0', '0', '0', '/home', 'Coupons', '左邻小站', '左邻小站', 'cs://1/image/aW1hZ2UvTVRveU9ERXlPV014TWpFNE1ESTNaalU1TVdWbU5UQmxNMlV6WmpkbVlqa3paZw', '5', '1', '14', '{\"url\":\"http://121.199.69.107:8080/zl-ec/rest/service/front/logon?hideNavigationBar=1&sourceUrl=http://121.199.69.107:8080%2Fweb%2Fapp%2Fuser%2Findex.html%23%2Fstore%2Fdetails%2F14477417463124576784%3F_k%3Dzlbiz#sign_suffix"}', '2', '0', '1', '1', NULL, '0', NULL, NULL, NULL, '0', 'park_tourist');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('4', '0', '0', '0', '0', '/home', 'Coupons', '优惠券', '优惠券', 'cs://1/image/aW1hZ2UvTVRwbU5UQTRNbUU1TlRObU5qRmlZVGhtTnpSak1qQTBOekkzWm1JNU9UQm1PQQ', '3', '1', '14', '{\"url\":\"https://biz.zuolin.com/zl-ec/rest/service/front/logon?hideNavigationBar=1&sourceUrl=https://biz.zuolin.com%2Fweb%2Fapp%2Fuser%2Findex.html%23%2Fpromotion%2Fall%3F_k%3Dzlbiz#sign_suffix\"}', '1', '0', '1', '1', NULL, '0', NULL, NULL, NULL, '0', 'park_tourist');

INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('5', '0', '0', '0', '0', '/home', 'Coupons', '左邻小站', '左邻小站', 'cs://1/image/aW1hZ2UvTVRveU9ERXlPV014TWpFNE1ESTNaalU1TVdWbU5UQmxNMlV6WmpkbVlqa3paZw', '5', '1', '14', '{\"url\":\"http://121.199.69.107:8080/zl-ec/rest/service/front/logon?hideNavigationBar=1&sourceUrl=http://121.199.69.107:8080%2Fweb%2Fapp%2Fuser%2Findex.html%23%2Fstore%2Fdetails%2F14477417463124576784%3F_k%3Dzlbiz#sign_suffix"}', '2', '0', '1', '1', NULL, '0', NULL, NULL, NULL, '0', 'pm_admin');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('6', '0', '0', '0', '0', '/home', 'Coupons', '优惠券', '优惠券', 'cs://1/image/aW1hZ2UvTVRwbU5UQTRNbUU1TlRObU5qRmlZVGhtTnpSak1qQTBOekkzWm1JNU9UQm1PQQ', '3', '1', '14', '{\"url\":\"https://biz.zuolin.com/zl-ec/rest/service/front/logon?hideNavigationBar=1&sourceUrl=https://biz.zuolin.com%2Fweb%2Fapp%2Fuser%2Findex.html%23%2Fpromotion%2Fall%3F_k%3Dzlbiz#sign_suffix\"}', '1', '0', '1', '1', NULL, '0', NULL, NULL, NULL, '0', 'pm_admin');


INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('7', '0', '0', '0', '0', '/home', 'Bizs', 'PM', '物业服务', 'cs://1/image/aW1hZ2UvTVRvMVlqVTBNMll5WlRoak9EUTRaRGN4TlRBMk9HSTJabUZtWVRaaU1EWTFOUQ', '1', '1', '2', '{\"itemLocation\":\"/home/Pm\",\"layoutName\":\"PmLayout\",\"title\":\"物业服务\",\"entityTag\":\"PM\"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'default');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('8', '0', '0', '0', '0', '/home', 'Bizs', 'PM', '物业服务', 'cs://1/image/aW1hZ2UvTVRvMVlqVTBNMll5WlRoak9EUTRaRGN4TlRBMk9HSTJabUZtWVRaaU1EWTFOUQ', '1', '1', '2', '{\"itemLocation\":\"/home/Pm\",\"layoutName\":\"PmLayout\",\"title\":\"物业服务\",\"entityTag\":\"PM\"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'park_tourist');
-- INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
-- VALUES ('9', '0', '0', '0', '0', '/home', 'Bizs', 'PM', '物业服务', 'cs://1/image/aW1hZ2UvTVRwbFl6a3lNelptTnpZMlpERm1aRFZrT1RaaFpXRmhOamc0TnpnM01tVmpNZw', '1', '1', '2', '{\"itemLocation\":\"/home/Pm\",\"layoutName\":\"PmLayout\",\"title\":\"物业服务\",\"entityTag\":\"PM\"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'pm_admin');

INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('10', '0', '0', '0', '0', '/home', 'Bizs', 'SERVICE_HOT_LINE', '服务热线', 'cs://1/image/aW1hZ2UvTVRvM09ETTRZakUwTXpFNVpUVTNaR0kzWW1JMlpqSTJNMlF4WmpRMVpXWXhNdw', '1', '1', '45', '', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'default');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('11', '0', '0', '0', '0', '/home', 'Bizs', 'SERVICE_HOT_LINE', '服务热线', 'cs://1/image/aW1hZ2UvTVRvM09ETTRZakUwTXpFNVpUVTNaR0kzWW1JMlpqSTJNMlF4WmpRMVpXWXhNdw', '1', '1', '45', '', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'park_tourist');
-- INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
-- VALUES ('12', '0', '0', '0', '0', '/home', 'Bizs', 'SERVICE_HOT_LINE', '服务热线', 'cs://1/image/aW1hZ2UvTVRvellUZzNNREV6Wm1WaE5tWTJaVGc1Tm1Sak5UTXdZak01TVRNeU56RTFNQQ', '1', '1', '45', '', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'pm_admin');

-- INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
-- VALUES ('13', '0', '0', '0', '0', '/home', 'Bizs', '门禁', '门禁', 'cs://1/image/aW1hZ2UvTVRvNE9XUmhZekU1WWpKaE56Z3pOakJqTnpWak16QTRNekl5WkdNeVpqbGlPUQ', '1', '1', '40', '', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'default');	
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('14', '0', '0', '0', '0', '/home', 'Bizs', '门禁', '门禁', 'cs://1/image/aW1hZ2UvTVRvd1lUazNOR1JrTmpVek1UVTNOR1F5TUdNNFptSmpaVGxqWVRnek1UQTFaUQ', '1', '1', '40', '', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'park_tourist');	
-- INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
-- VALUES ('15', '0', '0', '0', '0', '/home', 'Bizs', '门禁', '门禁', 'cs://1/image/aW1hZ2UvTVRvNE9XUmhZekU1WWpKaE56Z3pOakJqTnpWak16QTRNekl5WkdNeVpqbGlPUQ', '1', '1', '40', '', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'pm_admin');	

-- INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
-- VALUES ('16', '0', '0', '0', '0', '/home', 'Bizs', 'PARKING_RECHARGE', '停车充值', 'cs://1/image/aW1hZ2UvTVRwbE1EWXlZbUU0T1dWbU5XTXhNamxoTWpKaU1qQmlObVZsT0dFMk1tRmpNQQ', '1', '1', '30', '', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'default');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('17', '0', '0', '0', '0', '/home', 'Bizs', 'PARKING_RECHARGE', '停车充值', 'cs://1/image/aW1hZ2UvTVRwa056UmpOakZqWWpjeE1qZzJaRGN5TTJNeE1UVmlNRGcyTVRaak1UYzJaQQ', '1', '1', '30', '', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'park_tourist');
-- INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
-- VALUES ('18', '0', '0', '0', '0', '/home', 'Bizs', 'PARKING_RECHARGE', '停车充值', 'cs://1/image/aW1hZ2UvTVRwbE1EWXlZbUU0T1dWbU5XTXhNamxoTWpKaU1qQmlObVZsT0dFMk1tRmpNQQ', '1', '1', '30', '', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'pm_admin');

INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('19', '0', '0', '0', '0', '/home', 'Bizs', '管道疏通', '管道疏通', 'cs://1/image/aW1hZ2UvTVRwa1lUZGtPV1ppTldVMlpqTmxZelF6WXpsa1pUTTJOakUxWVRaak5UQm1aUQ', '1', '1', '14', '', '0', '0', '1', '1', NULL, '0', NULL, 'biz', '20', '1', 'default');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES (20, '0', '0', '0', '0', '/home', 'Bizs', '视频会议', '视频会议', 'cs://1/image/aW1hZ2UvTVRvMU5qVmhOakUzTm1ZM01HSm1aakpqTURVeVltTXhZemhsT1dRek5HWTRPUQ', '1', '1', '27', '', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'park_tourist');
-- INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
-- VALUES (21, '0', '0', '0', '0', '/home', 'Bizs', '视频会议', '视频会议', 'cs://1/image/aW1hZ2UvTVRwa05HRXhaVGRqTjJZek9EbGhaR00yT1RBME9ERmxOREU1T1RObE1UaGxaQQ', '1', '1', '27', '', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'pm_admin');

INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('22', '0', '0', '0', '0', '/home', 'Bizs', '家政服务', '家政服务', 'cs://1/image/aW1hZ2UvTVRveE56RmlORFZqWVRWaFl6YzJORGRqWkRCa09HWmpNak5sWkRRM05HWTRNdw', '1', '1', '19', '{\"contentCategory\":102022,\"actionCategory\":0,\"forumId\":179511,\"targetEntityTag\":\"PM\",\"embedAppId\":27} ', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'default');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES (23, '0', '0', '0', '0', '/home', 'Bizs', 'PUNCH', '打卡考勤', 'cs://1/image/aW1hZ2UvTVRwak9EUTVaRFF4TmpkbE5UTmxNalF4WTJRM05UUXdOMlJtTWpaaU5XUm1Odw', '1', '1', '23', '', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'park_tourist');
-- INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
-- VALUES (24, '0', '0', '0', '0', '/home', 'Bizs', 'PUNCH', '打卡考勤', 'cs://1/image/aW1hZ2UvTVRwbE16Y3dObUkwTTJaaE56VXhOVE5qTVRNMlpUYzNZemRsWlRReFpqbGxOdw', '1', '1', '23', '', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'pm_admin');

INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES (25, '0', '0', '0', '0', '/home', 'Bizs', 'CAR', '快递查询', 'cs://1/image/aW1hZ2UvTVRveE9UazFOMk00TkdZd04yTmtPVGc1TnpNMU9EZ3pOREEzWTJJd05tRXhaQQ', '1', '1', '14', '{\"url\":\"http://m.kuaidi100.com\"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'default');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('27', '0', '0', '0', '0', '/home', 'Bizs', 'CONTACTS', '企业通讯录', 'cs://1/image/aW1hZ2UvTVRwak16azJOelEwWW1RNU5HRTFZalF4T1dGaE1qWTBOelE1TVRjNU4yTmhNQQ', '1', '1', '46', '', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'park_tourist');
-- INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
-- VALUES ('28', '0', '0', '0', '0', '/home', 'Bizs', 'CONTACTS', '企业通讯录', 'cs://1/image/aW1hZ2UvTVRveFl6STJOV0U1WldRellUUXhOelU1TmpnNFl6SXhOR1JqWlRVNE1tVmhaUQ', '1', '1', '46', '', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'pm_admin');

INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES (29, '0', '0', '0', '0', '/home', 'Bizs', '更多', '更多', 'cs://1/image/aW1hZ2UvTVRvNU0yVTJaall3WWpZNE1EVTRaV0k1WkdNMk1tWXdORGMzTXpRelpUVmxZdw', '1', '1', '1', '{\"itemLocation\":\"/home\",\"itemGroup\":\"Bizs\"}', '30', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'default');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES (30, '0', '0', '0', '0', '/home', 'Bizs', '更多', '更多', 'cs://1/image/aW1hZ2UvTVRvNU0yVTJaall3WWpZNE1EVTRaV0k1WkdNMk1tWXdORGMzTXpRelpUVmxZdw', '1', '1', '1', '{\"itemLocation\":\"/home\",\"itemGroup\":\"Bizs\"}', '30', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'park_tourist');
-- INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
-- VALUES (31, '0', '0', '0', '0', '/home', 'Bizs', '更多', '更多', 'cs://1/image/aW1hZ2UvTVRvek1qVXdOVFl3TVRkak16STFORFZqTm1Ka05qY3daVEk1TXpZeVlUbGlPQQ', '1', '1', '1', '{\"itemLocation\":\"/home\",\"itemGroup\":\"Bizs\"}', '30', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'pm_admin');

INSERT INTO `eh_launch_pad_layouts`(`id`, `namespace_id`, `scene_type`, `name`, `layout_json`, `version_code`, `min_version_code`, `status`, `create_time`) 
	VALUES (3, 0, 'pm_admin', 'ServiceMarketLayout', '{"versionCode":"2016031201","versionName":"3.3.0","layoutName":"ServiceMarketLayout","displayName":"服务市场","groups":[{"groupName":"","widget":"Banners","instanceConfig":{"itemGroup":"Default"},"style":"Default","defaultOrder":1,"separatorFlag":0,"separatorHeight":0},{"groupName":"","widget":"Navigator","instanceConfig":{"itemGroup":"GovAgencies"},"style":"Default","defaultOrder":2,"separatorFlag":1,"separatorHeight":21,"columnCount":4},{"groupName":"","widget":"Coupons","instanceConfig":{"itemGroup":"Coupons"},"style":"Default","defaultOrder":3,"separatorFlag":1,"separatorHeight":21},{"groupName":"商家服务","widget":"Navigator","instanceConfig":{"itemGroup":"Bizs"},"style":"Default","defaultOrder":5,"separatorFlag":0,"separatorHeight":0}]}', '2016031201', '0', 2, '2016-03-12 19:16:25');
	
INSERT INTO `eh_launch_pad_items`(`id`, `scene_type`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) 
	VALUES (9, 'pm_admin', 0, 0, 0, 0, '/home', 'GovAgencies', 'OrgTaskManagement', '任务管理', 'cs://1/image/aW1hZ2UvTVRwbE16QXlNekJrTVRZMU16Rm1OakpoTnpVNE9URmtaalU1WXpJMFpUaG1Ndw', 1, 1, '39', '{"module":"ORG_TASK_MANAGEMENT"}', 0, 0, 1, 1, '','0', NULL, NULL, NULL);
INSERT INTO `eh_launch_pad_items`(`id`, `scene_type`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) 
	VALUES (12, 'pm_admin', 0, 0, 0, 0, '/home','GovAgencies','NoticeManager','公告管理','cs://1/image/aW1hZ2UvTVRvMU1tUmhZbVE0T0RZek5URm1NVEl5WVRWa05HSTJaVEJpWWpVeU1UUm1OZw',1,1,43, '', 0, 0, 1, 1, '', '0', NULL, NULL, NULL);
INSERT INTO `eh_launch_pad_items`(`id`, `scene_type`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) 
	VALUES (15, 'pm_admin', 999992, 0, 0, 0, '/home', 'Bizs', 'PUNCH', '打卡', 'cs://1/image/aW1hZ2UvTVRvMU9HRmxaR0V5TnpBNE1tWTVNakEwTnpFek5UTXhObVZoWTJaalptSmtNZw', '1', '1', '23', '', 0, 0, 1, 1, '', '0', NULL, NULL, NULL);
INSERT INTO `eh_launch_pad_items`(`id`, `scene_type`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) 
	VALUES (18, 'pm_admin', 0, 0, 0, 0, '/home', 'Bizs', 'QualityInspection', '品质核查', 'cs://1/image/aW1hZ2UvTVRwaU5tRTRZalZqTlRJNE5XUTVNelZoT1ROak9UWXlabUk1TURRMVpEZzROUQ', '1', '1', '44', '{"realm":"quality","entryUrl":"https://core.zuolin.com/nar/quality/index.html?hideNavigationBar=1#/task_list#sign_suffix"}', 0, 0, 1, 1, '', 0, NULL, NULL, NULL);
INSERT INTO `eh_launch_pad_items`(`id`, `scene_type`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) 
	VALUES (21, 'pm_admin', 0, 0, 0, 0, '/home', 'Bizs', 'DoorManagement', '门禁', 'cs://1/image/aW1hZ2UvTVRvNFptVTROV0k0T1dZeVpEazJaVGRoTmpka1pUQmxPRE01Tm1FMVptWmhNdw', 1, 1, 40, '', 0, 0, 1, 1, '', 0, NULL, NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`,  `scene_type`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`) 
	VALUES (24, 'pm_admin', 0, 0, 0, 0, '/home', 'Bizs', 'PUNCH', '停车充值', 'cs://1/image/aW1hZ2UvTVRwaE5UVTBOR0U1WWpRellUUTBPVE5tTUdFNE9EWmtPV0UyWW1RNU5EVmhOQQ', '1', '1', '14', '{\"url\":\"http://zuolin.com/mobile/static/coming_soon/index.html\"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1');
INSERT INTO `eh_launch_pad_items` (`id`,  `scene_type`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`) 
	VALUES (28, 'pm_admin', 0, 0, 0, 0, '/home', 'Bizs', '视频会议', '视频会议', 'cs://1/image/aW1hZ2UvTVRveU5tUmxZVEE0WVdFd1lXWmhZakpqTVRGak9XUXhZelZtWVdWa09HTXdaQQ', '1', '1', '27', '', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1');
INSERT INTO `eh_launch_pad_items`(`id`, `scene_type`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`)
    VALUES (31, 'pm_admin', 0, 0, 0, 0, '/home/NoticeManager', 'GaActions', 'PUBLIC_NOTICE', '发布公告', 'cs://1/image/aW1hZ2UvTVRvMk1USXdPREJpTkRSa05XVXhNV1EzTW1ZeVpEWTNaRE5tTnpCaU0ySmhNQQ', 1, 1, 19, '{"contentCategory":1003,"actionCategory":0,"targetEntityTag":"PM","visibleRegionType":0}', 0, 0, 1, 1, '', '0', NULL, NULL, NULL);


INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('32', '0', '0', '0', '0', '/home/Pm', 'GaActions', 'ADVISE', '投诉建议', 'cs://1/image/aW1hZ2UvTVRvMVl6aGlOekkxT0dGbVlXSTBZbVZtTURjMU5EQmtOMkU0WmpCbU1tSXpOdw', '1', '1', '19', '{\"contentCategory\":1006, \"actionCategory\":0, \"forumId\":1, \"targetEntityTag\":\"PM\", \"embedAppId\":27, \"visibleRegionType\":0}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'default');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('33', '0', '0', '0', '0', '/home/Pm', 'GaPosts', 'ADVISE', '投诉建议', NULL, '1', '1', '15', '{\"contentCategory\":1006, \"actionCategory\":0, \"forumId\":1, \"embedAppId\":27, \"entityTag\":\"PM\"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'default');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('34', '0', '0', '0', '0', '/home/Pm', 'GaActions', 'HELP', '紧急求助', 'cs://1/image/aW1hZ2UvTVRvNE9XSTFaakU1WWprNE4yVTFPV0pqT1dNMk9XWXlPRGN5WVdFMU1qUXpaZw', '1', '1', '19', '{\"contentCategory\":1012,\"actionCategory\":0,\"forumId\":1,\"targetEntityTag\":\"PM\",\"embedAppId\":27}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'default');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('35', '0', '0', '0', '0', '/home/Pm', 'GaActions', 'HELP', '咨询求助', 'cs://1/image/aW1hZ2UvTVRvMFlqazJOalppWkRjME4yTXpOVEE1TlRnNFlqRTFNemMwWXpjeVlqTTNZUQ', '1', '1', '19', '{\"contentCategory\":1005,\"actionCategory\":0,\"forumId\":1,\"targetEntityTag\":\"PM\",\"embedAppId\":27}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'default');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('38', '0', '0', '0', '0', '/home/Pm', 'GaPosts', 'HELP', '紧急求助', NULL, '1', '1', '15', '{\"contentCategory\":1012,\"actionCategory\":0,\"forumId\":1,\"embedAppId\":27,\"entityTag\":\"PM\"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'default');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('39', '0', '0', '0', '0', '/home/Pm', 'GaPosts', 'HELP', '咨询求助', NULL, '1', '1', '15', '{\"contentCategory\":1005,\"actionCategory\":0,\"forumId\":1,\"embedAppId\":27,\"entityTag\":\"PM\"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'default');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('40', '0', '0', '0', '0', '/home/Pm', 'GaPosts', 'NOTICE', '公告', NULL, '1', '1', '15', '{\"contentCategory\":1003, \"actionCategory\":0, \"forumId\":1, \"embedAppId\":0, \"entityTag\":\"PM\"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'default');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('41', '0', '0', '0', '0', '/home/Pm', 'GaActions', 'REPAIR', '报修', 'cs://1/image/aW1hZ2UvTVRwaFpqUmxNRGd6WkRJME1URmtNMlJtWm1Sak1USmtNamN6WTJJelltSTJZUQ', '1', '1', '19', '{\"contentCategory\":1004, \"actionCategory\":0, \"forumId\":1, \"targetEntityTag\":\"PM\", \"embedAppId\":27, \"visibleRegionType\":0}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'default');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('43', '0', '0', '0', '0', '/home/Pm', 'GaPosts', 'REPAIR', '报修', NULL, '1', '1', '15', '{\"contentCategory\":1004, \"actionCategory\":0, \"forumId\":1, \"embedAppId\":27, \"entityTag\":\"PM\"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'default');

INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('44', '0', '0', '0', '0', '/home/Pm', 'GaActions', 'ADVISE', '投诉建议', 'cs://1/image/aW1hZ2UvTVRvMVl6aGlOekkxT0dGbVlXSTBZbVZtTURjMU5EQmtOMkU0WmpCbU1tSXpOdw', '1', '1', '19', '{\"contentCategory\":1006, \"actionCategory\":0, \"forumId\":1, \"targetEntityTag\":\"PM\", \"embedAppId\":27, \"visibleRegionType\":0}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'park_tourist');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('45', '0', '0', '0', '0', '/home/Pm', 'GaPosts', 'ADVISE', '投诉建议', NULL, '1', '1', '15', '{\"contentCategory\":1006, \"actionCategory\":0, \"forumId\":1, \"embedAppId\":27, \"entityTag\":\"PM\"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'park_tourist');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('46', '0', '0', '0', '0', '/home/Pm', 'GaActions', 'HELP', '紧急求助', 'cs://1/image/aW1hZ2UvTVRvNE9XSTFaakU1WWprNE4yVTFPV0pqT1dNMk9XWXlPRGN5WVdFMU1qUXpaZw', '1', '1', '19', '{\"contentCategory\":1012,\"actionCategory\":0,\"forumId\":1,\"targetEntityTag\":\"PM\",\"embedAppId\":27}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'park_tourist');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('47', '0', '0', '0', '0', '/home/Pm', 'GaActions', 'HELP', '咨询求助', 'cs://1/image/aW1hZ2UvTVRvMFlqazJOalppWkRjME4yTXpOVEE1TlRnNFlqRTFNemMwWXpjeVlqTTNZUQ', '1', '1', '19', '{\"contentCategory\":1005,\"actionCategory\":0,\"forumId\":1,\"targetEntityTag\":\"PM\",\"embedAppId\":27}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'park_tourist');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('48', '0', '0', '0', '0', '/home/Pm', 'GaPosts', 'HELP', '紧急求助', NULL, '1', '1', '15', '{\"contentCategory\":1012,\"actionCategory\":0,\"forumId\":1,\"embedAppId\":27,\"entityTag\":\"PM\"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'park_tourist');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('50', '0', '0', '0', '0', '/home/Pm', 'GaPosts', 'HELP', '咨询求助', NULL, '1', '1', '15', '{\"contentCategory\":1005,\"actionCategory\":0,\"forumId\":1,\"embedAppId\":27,\"entityTag\":\"PM\"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'park_tourist');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('51', '0', '0', '0', '0', '/home/Pm', 'GaPosts', 'NOTICE', '公告', NULL, '1', '1', '15', '{\"contentCategory\":1003, \"actionCategory\":0, \"forumId\":1, \"embedAppId\":0, \"entityTag\":\"PM\"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'park_tourist');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('52', '0', '0', '0', '0', '/home/Pm', 'GaActions', 'REPAIR', '报修', 'cs://1/image/aW1hZ2UvTVRwaFpqUmxNRGd6WkRJME1URmtNMlJtWm1Sak1USmtNamN6WTJJelltSTJZUQ', '1', '1', '19', '{\"contentCategory\":1004, \"actionCategory\":0, \"forumId\":1, \"targetEntityTag\":\"PM\", \"embedAppId\":27, \"visibleRegionType\":0}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'park_tourist');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('53', '0', '0', '0', '0', '/home/Pm', 'GaPosts', 'REPAIR', '报修', NULL, '1', '1', '15', '{\"contentCategory\":1004, \"actionCategory\":0, \"forumId\":1, \"embedAppId\":27, \"entityTag\":\"PM\"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'park_tourist');

INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('54', '0', '0', '0', '0', '/home/Pm', 'GaActions', 'ADVISE', '投诉建议', 'cs://1/image/aW1hZ2UvTVRvMVl6aGlOekkxT0dGbVlXSTBZbVZtTURjMU5EQmtOMkU0WmpCbU1tSXpOdw', '1', '1', '19', '{\"contentCategory\":1006, \"actionCategory\":0, \"forumId\":1, \"targetEntityTag\":\"PM\", \"embedAppId\":27, \"visibleRegionType\":0}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'pm_admin');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('59', '0', '0', '0', '0', '/home/Pm', 'GaPosts', 'ADVISE', '投诉建议', NULL, '1', '1', '15', '{\"contentCategory\":1006, \"actionCategory\":0, \"forumId\":1, \"embedAppId\":27, \"entityTag\":\"PM\"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'pm_admin');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('60', '0', '0', '0', '0', '/home/Pm', 'GaActions', 'HELP', '紧急求助', 'cs://1/image/aW1hZ2UvTVRvNE9XSTFaakU1WWprNE4yVTFPV0pqT1dNMk9XWXlPRGN5WVdFMU1qUXpaZw', '1', '1', '19', '{\"contentCategory\":1012,\"actionCategory\":0,\"forumId\":1,\"targetEntityTag\":\"PM\",\"embedAppId\":27}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'pm_admin');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('61', '0', '0', '0', '0', '/home/Pm', 'GaActions', 'HELP', '咨询求助', 'cs://1/image/aW1hZ2UvTVRvMFlqazJOalppWkRjME4yTXpOVEE1TlRnNFlqRTFNemMwWXpjeVlqTTNZUQ', '1', '1', '19', '{\"contentCategory\":1005,\"actionCategory\":0,\"forumId\":1,\"targetEntityTag\":\"PM\",\"embedAppId\":27}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'pm_admin');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('69', '0', '0', '0', '0', '/home/Pm', 'GaPosts', 'HELP', '紧急求助', NULL, '1', '1', '15', '{\"contentCategory\":1012,\"actionCategory\":0,\"forumId\":1,\"embedAppId\":27,\"entityTag\":\"PM\"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'pm_admin');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('70', '0', '0', '0', '0', '/home/Pm', 'GaPosts', 'HELP', '咨询求助', NULL, '1', '1', '15', '{\"contentCategory\":1005,\"actionCategory\":0,\"forumId\":1,\"embedAppId\":27,\"entityTag\":\"PM\"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'pm_admin');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('71', '0', '0', '0', '0', '/home/Pm', 'GaPosts', 'NOTICE', '公告', NULL, '1', '1', '15', '{\"contentCategory\":1003, \"actionCategory\":0, \"forumId\":1, \"embedAppId\":0, \"entityTag\":\"PM\"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'pm_admin');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('72', '0', '0', '0', '0', '/home/Pm', 'GaActions', 'REPAIR', '报修', 'cs://1/image/aW1hZ2UvTVRwaFpqUmxNRGd6WkRJME1URmtNMlJtWm1Sak1USmtNamN6WTJJelltSTJZUQ', '1', '1', '19', '{\"contentCategory\":1004, \"actionCategory\":0, \"forumId\":1, \"targetEntityTag\":\"PM\", \"embedAppId\":27, \"visibleRegionType\":0}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'pm_admin');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('94', '0', '0', '0', '0', '/home/Pm', 'GaPosts', 'REPAIR', '报修', NULL, '1', '1', '15', '{\"contentCategory\":1004, \"actionCategory\":0, \"forumId\":1, \"embedAppId\":27, \"entityTag\":\"PM\"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'pm_admin');


















