-- merge from mergeAsset by xiongying20170417
INSERT INTO `eh_asset_vendor` (`id`, `owner_type`, `owner_id`, `name`, `vendor_name`, `status`, `namespace_id`) VALUES ('1', 'community', '240111044331055940', '科兴物业缴费', 'EBEI', '2', '999983');
INSERT INTO `eh_asset_vendor` (`id`, `owner_type`, `owner_id`, `name`, `vendor_name`, `status`, `namespace_id`) VALUES ('2', 'community', '240111044331055035', '华润物业缴费', 'ZUOLIN', '2', '999985');
INSERT INTO `eh_asset_vendor` (`id`, `owner_type`, `owner_id`, `name`, `vendor_name`, `status`, `namespace_id`) VALUES ('3', 'community', '240111044331055036', '华润物业缴费', 'ZUOLIN', '2', '999985');
SET @item_id = (SELECT MAX(id) FROM `eh_launch_pad_items`); 
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`) VALUES ((@item_id := @item_id + 1), '999985', '0', '0', '0', '/home', 'Bizs', '费用查询', '缴费管理', 'cs://1/image/aW1hZ2UvTVRvM016QTVaR0U1WWpCa05EYzJNR0psWkRVME5XSmhaakUyTkdVM09UY3lZUQ', '1', '1', '14', '{\"url\":\"http://xiongying.lab.everhomes.com/property-bill/index.html?hideNavigationBar=1&name=缴费管理#/verify_account#sign_suffix\"}', '1', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'pm_admin', '0', NULL, NULL, '0');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`) VALUES ((@item_id := @item_id + 1), '999985', '0', '0', '0', '/home', 'Bizs', '费用查询', '缴费管理', 'cs://1/image/aW1hZ2UvTVRvM016QTVaR0U1WWpCa05EYzJNR0psWkRVME5XSmhaakUyTkdVM09UY3lZUQ', '1', '1', '14', '{\"url\":\"http://xiongying.lab.everhomes.com/property-bill/index.html?hideNavigationBar=1&name=缴费管理#/verify_account#sign_suffix\"}', '1', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'park_tourist', '0', NULL, NULL, '0');


-- 社群的二级页面item配置 add sfyan 20170425
SET @launch_pad_item_id = (SELECT max(id) FROM `eh_launch_pad_items`); 

insert into `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`) values((@launch_pad_item_id := @launch_pad_item_id + 1),'999985','0','0','0','/home','Bizs','Association','社群','','1','1','60','{\"url\":\"zl://association/main?layoutName=AssociationLayout&itemLocation=/association&versionCode=2017042501\"}','10','0','1','1','','0',NULL,NULL,NULL,'1','pm_admin','1',NULL,NULL,'0');

insert into `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`) values((@launch_pad_item_id := @launch_pad_item_id + 1),'999985','0','0','0','/association','TabGroup','RENTAL','会议室预定','cs://1/image/aW1hZ2UvTVRwaVlqZzJOV1F3Wm1KbU1EVXpZMlF6TldKalpUWm1PV00zWXpSbU5qVTRaZw','1','1','49','{\"resourceTypeId\":10096,\"pageType\":0}','40','0','1','1','','1',NULL,NULL,NULL,'1','pm_admin','0',NULL,NULL,'0');

insert into `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`) values((@launch_pad_item_id := @launch_pad_item_id + 1),'999985','0','0','0','/association','TabGroup','OFFICECUBICLE','工位预订','','1','1','14','{"url":"http://alpha.lab.everhomes.com/station-booking/index.html?hideNavigationBar=1#/station_booking#sign_suffix"}','10','0','1','1','','0',NULL,NULL,NULL,'1','pm_admin','1',NULL,NULL,'0');