-- 提示信息 add by sfyan 20170427
insert into `eh_locale_strings` (`scope`, `code`, `locale`, `text`) values('organization','100010','zh_CN','手机号码已存在');
insert into `eh_locale_strings` (`scope`, `code`, `locale`, `text`) values('organization','700000','zh_CN','姓名不能为空');
insert into `eh_locale_strings` (`scope`, `code`, `locale`, `text`) values('organization','700001','zh_CN','电话号码不能为空');

-- 把eh_organization_members的两个字段更新对应到eh_organization两个字段的值 add by sfyan 20170427
update `eh_organization_members` om set `group_path` = (select path from eh_organizations where id = om.organization_id), `group_type` = (select `group_type` from eh_organizations where id = om.organization_id), `update_time` = now() where `group_path` <> (select path from eh_organizations where id = om.organization_id) OR `group_type` <> (select `group_type` from eh_organizations where id = om.organization_id);

-- 增加应用类型和商家类型 add by yanjun 20170427 search-2.0
SELECT MAX(id) INTO @id FROM eh_search_types;
INSERT INTO `eh_search_types` (`id`, `namespace_id`, `owner_type`, `owner_id`, `name`, `content_type`, `status`, `create_time`, `delete_time`) VALUES(@id:=@id+1,'0','','0','应用','launchpaditem','1',NULL,NULL);
INSERT INTO `eh_search_types` (`id`, `namespace_id`, `owner_type`, `owner_id`, `name`, `content_type`, `status`, `create_time`, `delete_time`) VALUES(@id:=@id+1,'1000000','','0','应用','launchpaditem','1',NULL,NULL);
INSERT INTO `eh_search_types` (`id`, `namespace_id`, `owner_type`, `owner_id`, `name`, `content_type`, `status`, `create_time`, `delete_time`) VALUES(@id:=@id+1,'999992','','0','应用','launchpaditem','1',NULL,NULL);
INSERT INTO `eh_search_types` (`id`, `namespace_id`, `owner_type`, `owner_id`, `name`, `content_type`, `status`, `create_time`, `delete_time`) VALUES(@id:=@id+1,'999991','','0','应用','launchpaditem','1',NULL,NULL);
INSERT INTO `eh_search_types` (`id`, `namespace_id`, `owner_type`, `owner_id`, `name`, `content_type`, `status`, `create_time`, `delete_time`) VALUES(@id:=@id+1,'999989','','0','应用','launchpaditem','1',NULL,NULL);
INSERT INTO `eh_search_types` (`id`, `namespace_id`, `owner_type`, `owner_id`, `name`, `content_type`, `status`, `create_time`, `delete_time`) VALUES(@id:=@id+1,'999990','','0','应用','launchpaditem','1',NULL,NULL);
INSERT INTO `eh_search_types` (`id`, `namespace_id`, `owner_type`, `owner_id`, `name`, `content_type`, `status`, `create_time`, `delete_time`) VALUES(@id:=@id+1,'999993','','0','应用','launchpaditem','1',NULL,NULL);
INSERT INTO `eh_search_types` (`id`, `namespace_id`, `owner_type`, `owner_id`, `name`, `content_type`, `status`, `create_time`, `delete_time`) VALUES(@id:=@id+1,'999999','','0','应用','launchpaditem','1',NULL,NULL);
INSERT INTO `eh_search_types` (`id`, `namespace_id`, `owner_type`, `owner_id`, `name`, `content_type`, `status`, `create_time`, `delete_time`) VALUES(@id:=@id+1,'999988','','0','应用','launchpaditem','1',NULL,NULL);
INSERT INTO `eh_search_types` (`id`, `namespace_id`, `owner_type`, `owner_id`, `name`, `content_type`, `status`, `create_time`, `delete_time`) VALUES(@id:=@id+1,'999987','','0','应用','launchpaditem','1',NULL,NULL);
INSERT INTO `eh_search_types` (`id`, `namespace_id`, `owner_type`, `owner_id`, `name`, `content_type`, `status`, `create_time`, `delete_time`) VALUES(@id:=@id+1,'999986','','0','应用','launchpaditem','1',NULL,NULL);
INSERT INTO `eh_search_types` (`id`, `namespace_id`, `owner_type`, `owner_id`, `name`, `content_type`, `status`, `create_time`, `delete_time`) VALUES(@id:=@id+1,'999985','','0','应用','launchpaditem','1',NULL,NULL);
INSERT INTO `eh_search_types` (`id`, `namespace_id`, `owner_type`, `owner_id`, `name`, `content_type`, `status`, `create_time`, `delete_time`) VALUES(@id:=@id+1,'999983','','0','应用','launchpaditem','1',NULL,NULL);
INSERT INTO `eh_search_types` (`id`, `namespace_id`, `owner_type`, `owner_id`, `name`, `content_type`, `status`, `create_time`, `delete_time`) VALUES(@id:=@id+1,'0','','0','商家','shop','1',NULL,NULL);
INSERT INTO `eh_search_types` (`id`, `namespace_id`, `owner_type`, `owner_id`, `name`, `content_type`, `status`, `create_time`, `delete_time`) VALUES(@id:=@id+1,'1000000','','0','商家','shop','1',NULL,NULL);
INSERT INTO `eh_search_types` (`id`, `namespace_id`, `owner_type`, `owner_id`, `name`, `content_type`, `status`, `create_time`, `delete_time`) VALUES(@id:=@id+1,'999992','','0','商家','shop','1',NULL,NULL);
INSERT INTO `eh_search_types` (`id`, `namespace_id`, `owner_type`, `owner_id`, `name`, `content_type`, `status`, `create_time`, `delete_time`) VALUES(@id:=@id+1,'999991','','0','商家','shop','1',NULL,NULL);
INSERT INTO `eh_search_types` (`id`, `namespace_id`, `owner_type`, `owner_id`, `name`, `content_type`, `status`, `create_time`, `delete_time`) VALUES(@id:=@id+1,'999989','','0','商家','shop','1',NULL,NULL);
INSERT INTO `eh_search_types` (`id`, `namespace_id`, `owner_type`, `owner_id`, `name`, `content_type`, `status`, `create_time`, `delete_time`) VALUES(@id:=@id+1,'999990','','0','商家','shop','1',NULL,NULL);
INSERT INTO `eh_search_types` (`id`, `namespace_id`, `owner_type`, `owner_id`, `name`, `content_type`, `status`, `create_time`, `delete_time`) VALUES(@id:=@id+1,'999993','','0','商家','shop','1',NULL,NULL);
INSERT INTO `eh_search_types` (`id`, `namespace_id`, `owner_type`, `owner_id`, `name`, `content_type`, `status`, `create_time`, `delete_time`) VALUES(@id:=@id+1,'999999','','0','商家','shop','1',NULL,NULL);
INSERT INTO `eh_search_types` (`id`, `namespace_id`, `owner_type`, `owner_id`, `name`, `content_type`, `status`, `create_time`, `delete_time`) VALUES(@id:=@id+1,'999988','','0','商家','shop','1',NULL,NULL);
INSERT INTO `eh_search_types` (`id`, `namespace_id`, `owner_type`, `owner_id`, `name`, `content_type`, `status`, `create_time`, `delete_time`) VALUES(@id:=@id+1,'999987','','0','商家','shop','1',NULL,NULL);
INSERT INTO `eh_search_types` (`id`, `namespace_id`, `owner_type`, `owner_id`, `name`, `content_type`, `status`, `create_time`, `delete_time`) VALUES(@id:=@id+1,'999986','','0','商家','shop','1',NULL,NULL);
INSERT INTO `eh_search_types` (`id`, `namespace_id`, `owner_type`, `owner_id`, `name`, `content_type`, `status`, `create_time`, `delete_time`) VALUES(@id:=@id+1,'999985','','0','商家','shop','1',NULL,NULL);
INSERT INTO `eh_search_types` (`id`, `namespace_id`, `owner_type`, `owner_id`, `name`, `content_type`, `status`, `create_time`, `delete_time`) VALUES(@id:=@id+1,'999983','','0','商家','shop','1',NULL,NULL);

-- 搜索电商商家API add by yanjun 20170427 search-2.0
SELECT MAX(id) INTO @id FROM eh_configurations;
INSERT INTO `eh_configurations` (`id`, `name`, `value`, `description`, `namespace_id`, `display_name`) VALUES(@id:=@id+1,'biz.search.shops.api','/zl-ec/rest/openapi/shop/listByKeyword','搜索电商商家API','0',NULL);

-- 当item对应的layout是方形时给它一个默认的icon，现在用于搜索时的icon展现。以下的图片路径需要根据上线时实际的图片路径作修改。add by yanjun 20170427 search-2.0
SELECT 'cs://1/image/aW1hZ2UvTVRwak5tTmtNREpqT0dJM01XSmhabVJoT1dJNFpEYzFOelUyTURJNE1EY3hZZw' INTO @alias_icon_uri FROM DUAL;
UPDATE eh_launch_pad_items a SET a.alias_icon_uri = @alias_icon_uri WHERE a.namespace_id = 0 AND item_group IN ('Bizs') ; 
UPDATE eh_launch_pad_items a SET a.alias_icon_uri = @alias_icon_uri WHERE a.namespace_id = 999980 AND item_group IN ('Gallery', 'Coupons') ; 
UPDATE eh_launch_pad_items a SET a.alias_icon_uri = @alias_icon_uri WHERE a.namespace_id = 999982 AND item_group IN ('Gallery') ; 
UPDATE eh_launch_pad_items a SET a.alias_icon_uri = @alias_icon_uri WHERE a.namespace_id = 999983 AND item_group IN ('Gallery1', 'Gallery', 'BizList') ; 
UPDATE eh_launch_pad_items a SET a.alias_icon_uri = @alias_icon_uri WHERE a.namespace_id = 999985 AND item_group IN ('libraryBanner', 'BizList') ; 
UPDATE eh_launch_pad_items a SET a.alias_icon_uri = @alias_icon_uri WHERE a.namespace_id = 999986 AND item_group IN ('aclinkAndpunchBanner', 'aclinkAndpunchBiz', 'serviceAllianceBanner', 'serviceAllianceBiz', 'communityBanner', 'communityBiz') ; 
UPDATE eh_launch_pad_items a SET a.alias_icon_uri = @alias_icon_uri WHERE a.namespace_id = 999990 AND item_group IN ('GovAgencies') ; 
UPDATE eh_launch_pad_items a SET a.alias_icon_uri = @alias_icon_uri WHERE a.namespace_id = 999991 AND item_group IN ('BizList') ; 
UPDATE eh_launch_pad_items a SET a.alias_icon_uri = @alias_icon_uri WHERE a.namespace_id = 999992 AND item_group IN ('Coupons') ; 
UPDATE eh_launch_pad_items a SET a.alias_icon_uri = @alias_icon_uri WHERE a.namespace_id = 999993 AND item_group IN ('Coupons') ; 
UPDATE eh_launch_pad_items a SET a.alias_icon_uri = @alias_icon_uri WHERE a.namespace_id = 999999 AND item_group IN ('MakerBanners', 'MakerSpaces') ; 


-- 增加一个排序字段，用于客户端显示顺序，顺序为活动、话题、投票、快讯、应用和商店 add by yanjun 20170427 search-2.0
UPDATE eh_search_types s SET s.order = 1 WHERE s.content_type = 'activity';
UPDATE eh_search_types s SET s.order = 2 WHERE s.content_type = 'topic';
UPDATE eh_search_types s SET s.order = 3 WHERE s.content_type = 'poll';
UPDATE eh_search_types s SET s.order = 4 WHERE s.content_type = 'news';
UPDATE eh_search_types s SET s.order = 5 WHERE s.content_type = 'launchpaditem';
UPDATE eh_search_types s SET s.order = 6 WHERE s.content_type = 'shop';

-- 增加索引以便门牌那里查询更快，add by tt, 20170428
ALTER TABLE `eh_organization_address_mappings` ADD INDEX `address_id` (`address_id`);

-- 停车充值 add by sw 20170502
INSERT INTO `eh_locale_strings` ( `scope`, `code`, `locale`, `text`) VALUES ('parking', '10004', 'zh_CN', '服务器通讯异常，请稍后再试！');
INSERT INTO `eh_locale_strings` ( `scope`, `code`, `locale`, `text`) VALUES ('parking', '10020', 'zh_CN', '该车牌不支持APP缴费！');

-- 左邻域下面永佳天成机构数据修改 add by sfyan 20170503
update `eh_organizations` set `directly_enterprise_id` = 1023080 where path like '/1023080/%' and `group_type` <> 'ENTERPRISE';

-- 社群增加参数配置 add by 20170503
update `eh_launch_pad_items` set `action_data` = '{\"url\":\"zl://association/main?layoutName=AssociationLayout&itemLocation=/association&versionCode=2017042501&displayName=社群\"}' where `item_name` = 'Association' and `item_label` = '社群' and namespace_id = 999985;

-- 批量把通讯录关联用户 add by sfyan 20170503 需要一点时间
update `eh_organization_members` om set `target_type` = IF(((select count(*) from `eh_user_identifiers` where namespace_id = 999992 and `identifier_token` = om.`contact_token`) = 0) , 'UNTRACK', 'USER'), `target_id` = IFNULL((select `owner_uid` from `eh_user_identifiers` where namespace_id = 999992 and `identifier_token` = om.`contact_token`) , 0) where `group_path` like '/1000750%' and status = 3 and target_type = 'UNTRACK';


-- 配置能量加油站, add by tt, 20170509（已执行）
select max(id) into @id from `eh_launch_pad_items`;
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`) VALUES (@id:=@id+1, 1000000, 0, 4, 178170, '/home', 'Bizs', '能量加油站', '能量加油站', 'cs://1/image/aW1hZ2UvTVRwbU4yRXhNek0xTldVek1EaGhPV1ZrT0RVM1pEUmtPR1kzWXpKbU5qUXlOZw', 1, 1, 14, '{"url":"https://biz.zuolin.com/zl-ec/rest/service/front/logon?hideNavigationBar=1&sourceUrl=https://biz.zuolin.com%2Fnar%2Fbiz%2Fweb%2Fapp%2Fuser%2Findex.html%23%2Fstore%2Fdetails%2F14937905385175861793%3F_k%3Dzlbiz#sign_suffix"}', 0, 0, 1, 1, '', 0, NULL, NULL, NULL, 1, 'pm_admin', 0, NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`) VALUES (@id:=@id+1, 1000000, 0, 4, 178170, '/home', 'Bizs', '能量加油站', '能量加油站', 'cs://1/image/aW1hZ2UvTVRwbU4yRXhNek0xTldVek1EaGhPV1ZrT0RVM1pEUmtPR1kzWXpKbU5qUXlOZw', 1, 1, 14, '{"url":"https://biz.zuolin.com/zl-ec/rest/service/front/logon?hideNavigationBar=1&sourceUrl=https://biz.zuolin.com%2Fnar%2Fbiz%2Fweb%2Fapp%2Fuser%2Findex.html%23%2Fstore%2Fdetails%2F14937905385175861793%3F_k%3Dzlbiz#sign_suffix"}', 0, 0, 1, 1, '', 0, NULL, NULL, NULL, 1, 'park_tourist', 0, NULL, NULL);

INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`) VALUES (@id:=@id+1, 1000000, 0, 4, 178307, '/home', 'Bizs', '能量加油站', '能量加油站', 'cs://1/image/aW1hZ2UvTVRwbU4yRXhNek0xTldVek1EaGhPV1ZrT0RVM1pEUmtPR1kzWXpKbU5qUXlOZw', 1, 1, 14, '{"url":"https://biz.zuolin.com/zl-ec/rest/service/front/logon?hideNavigationBar=1&sourceUrl=https://biz.zuolin.com%2Fnar%2Fbiz%2Fweb%2Fapp%2Fuser%2Findex.html%23%2Fstore%2Fdetails%2F14938834358936096746%3F_k%3Dzlbiz#sign_suffix"}', 0, 0, 1, 1, '', 0, NULL, NULL, NULL, 1, 'pm_admin', 0, NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`) VALUES (@id:=@id+1, 1000000, 0, 4, 178307, '/home', 'Bizs', '能量加油站', '能量加油站', 'cs://1/image/aW1hZ2UvTVRwbU4yRXhNek0xTldVek1EaGhPV1ZrT0RVM1pEUmtPR1kzWXpKbU5qUXlOZw', 1, 1, 14, '{"url":"https://biz.zuolin.com/zl-ec/rest/service/front/logon?hideNavigationBar=1&sourceUrl=https://biz.zuolin.com%2Fnar%2Fbiz%2Fweb%2Fapp%2Fuser%2Findex.html%23%2Fstore%2Fdetails%2F14938834358936096746%3F_k%3Dzlbiz#sign_suffix"}', 0, 0, 1, 1, '', 0, NULL, NULL, NULL, 1, 'park_tourist', 0, NULL, NULL);

INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`) VALUES (@id:=@id+1, 999990, 0, 4, 1006090, '/home', 'Bizs', '能量加油站', '能量加油站', 'cs://1/image/aW1hZ2UvTVRwbU4yRXhNek0xTldVek1EaGhPV1ZrT0RVM1pEUmtPR1kzWXpKbU5qUXlOZw', 1, 1, 14, '{"url":"https://biz.zuolin.com/zl-ec/rest/service/front/logon?hideNavigationBar=1&sourceUrl=https://biz.zuolin.com%2Fnar%2Fbiz%2Fweb%2Fapp%2Fuser%2Findex.html%23%2Fstore%2Fdetails%2F14937781453413755100%3F_k%3Dzlbiz#sign_suffix"}', 0, 0, 1, 1, '', 0, NULL, NULL, NULL, 1, 'pm_admin', 0, NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`) VALUES (@id:=@id+1, 999990, 0, 4, 1006090, '/home', 'Bizs', '能量加油站', '能量加油站', 'cs://1/image/aW1hZ2UvTVRwbU4yRXhNek0xTldVek1EaGhPV1ZrT0RVM1pEUmtPR1kzWXpKbU5qUXlOZw', 1, 1, 14, '{"url":"https://biz.zuolin.com/zl-ec/rest/service/front/logon?hideNavigationBar=1&sourceUrl=https://biz.zuolin.com%2Fnar%2Fbiz%2Fweb%2Fapp%2Fuser%2Findex.html%23%2Fstore%2Fdetails%2F14937781453413755100%3F_k%3Dzlbiz#sign_suffix"}', 0, 0, 1, 1, '', 0, NULL, NULL, NULL, 1, 'park_tourist', 0, NULL, NULL);

INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`) VALUES (@id:=@id+1, 999990, 0, 4, 1001115, '/home', 'Bizs', '能量加油站', '能量加油站', 'cs://1/image/aW1hZ2UvTVRwbU4yRXhNek0xTldVek1EaGhPV1ZrT0RVM1pEUmtPR1kzWXpKbU5qUXlOZw', 1, 1, 14, '{"url":"https://biz.zuolin.com/zl-ec/rest/service/front/logon?hideNavigationBar=1&sourceUrl=https://biz.zuolin.com%2Fnar%2Fbiz%2Fweb%2Fapp%2Fuser%2Findex.html%23%2Fstore%2Fdetails%2F14937902738181683764%3F_k%3Dzlbiz#sign_suffix"}', 0, 0, 1, 1, '', 0, NULL, NULL, NULL, 1, 'pm_admin', 0, NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`) VALUES (@id:=@id+1, 999990, 0, 4, 1001115, '/home', 'Bizs', '能量加油站', '能量加油站', 'cs://1/image/aW1hZ2UvTVRwbU4yRXhNek0xTldVek1EaGhPV1ZrT0RVM1pEUmtPR1kzWXpKbU5qUXlOZw', 1, 1, 14, '{"url":"https://biz.zuolin.com/zl-ec/rest/service/front/logon?hideNavigationBar=1&sourceUrl=https://biz.zuolin.com%2Fnar%2Fbiz%2Fweb%2Fapp%2Fuser%2Findex.html%23%2Fstore%2Fdetails%2F14937902738181683764%3F_k%3Dzlbiz#sign_suffix"}', 0, 0, 1, 1, '', 0, NULL, NULL, NULL, 1, 'park_tourist', 0, NULL, NULL);

INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`) VALUES (@id:=@id+1, 1000000, 0, 4, 1011046, '/home', 'Bizs', '能量加油站', '能量加油站', 'cs://1/image/aW1hZ2UvTVRwbU4yRXhNek0xTldVek1EaGhPV1ZrT0RVM1pEUmtPR1kzWXpKbU5qUXlOZw', 1, 1, 14, '{"url":"https://biz.zuolin.com/zl-ec/rest/service/front/logon?hideNavigationBar=1&sourceUrl=https://biz.zuolin.com%2Fnar%2Fbiz%2Fweb%2Fapp%2Fuser%2Findex.html%23%2Fstore%2Fdetails%2F14937905385175861793%3F_k%3Dzlbiz#sign_suffix"}', 0, 0, 1, 1, '', 0, NULL, NULL, NULL, 1, 'pm_admin', 0, NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`) VALUES (@id:=@id+1, 1000000, 0, 4, 1011046, '/home', 'Bizs', '能量加油站', '能量加油站', 'cs://1/image/aW1hZ2UvTVRwbU4yRXhNek0xTldVek1EaGhPV1ZrT0RVM1pEUmtPR1kzWXpKbU5qUXlOZw', 1, 1, 14, '{"url":"https://biz.zuolin.com/zl-ec/rest/service/front/logon?hideNavigationBar=1&sourceUrl=https://biz.zuolin.com%2Fnar%2Fbiz%2Fweb%2Fapp%2Fuser%2Findex.html%23%2Fstore%2Fdetails%2F14937905385175861793%3F_k%3Dzlbiz#sign_suffix"}', 0, 0, 1, 1, '', 0, NULL, NULL, NULL, 1, 'park_tourist', 0, NULL, NULL);

INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`) VALUES (@id:=@id+1, 1000000, 0, 4, 1011073, '/home', 'Bizs', '能量加油站', '能量加油站', 'cs://1/image/aW1hZ2UvTVRwbU4yRXhNek0xTldVek1EaGhPV1ZrT0RVM1pEUmtPR1kzWXpKbU5qUXlOZw', 1, 1, 14, '{"url":"https://biz.zuolin.com/zl-ec/rest/service/front/logon?hideNavigationBar=1&sourceUrl=https://biz.zuolin.com%2Fnar%2Fbiz%2Fweb%2Fapp%2Fuser%2Findex.html%23%2Fstore%2Fdetails%2F14938834358936096746%3F_k%3Dzlbiz#sign_suffix"}', 0, 0, 1, 1, '', 0, NULL, NULL, NULL, 1, 'pm_admin', 0, NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`) VALUES (@id:=@id+1, 1000000, 0, 4, 1011073, '/home', 'Bizs', '能量加油站', '能量加油站', 'cs://1/image/aW1hZ2UvTVRwbU4yRXhNek0xTldVek1EaGhPV1ZrT0RVM1pEUmtPR1kzWXpKbU5qUXlOZw', 1, 1, 14, '{"url":"https://biz.zuolin.com/zl-ec/rest/service/front/logon?hideNavigationBar=1&sourceUrl=https://biz.zuolin.com%2Fnar%2Fbiz%2Fweb%2Fapp%2Fuser%2Findex.html%23%2Fstore%2Fdetails%2F14938834358936096746%3F_k%3Dzlbiz#sign_suffix"}', 0, 0, 1, 1, '', 0, NULL, NULL, NULL, 1, 'park_tourist', 0, NULL, NULL);

-- 修改嗒嗒巴士链接 , add by tt, 20170510（已执行）
update eh_launch_pad_items set action_data = '{"url":"http://jump.buskeji.com/custom/jump?ddb_jump_key=baoche"}' where namespace_id = 999990 and item_name = '班车';