INSERT INTO `eh_locale_strings` (`scope`, `code`, `locale`, `text`) VALUES ('customer', '10016', 'zh_CN', '客户编号已存在');

delete from eh_var_fields;
delete from eh_var_field_groups;

INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ('1', 'enterprise_customer', '0', '/1', '基本信息', '', '0', NULL, '2', '1', '2017-08-18 02:24:19');
INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ('2', 'enterprise_customer', '0', '/2', '税务信息', '', '0', NULL, '2', '1', '2017-08-18 02:24:19');
INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ('3', 'enterprise_customer', '0', '/3', '银行账号', '', '0', NULL, '2', '1', '2017-08-18 02:24:19');
INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ('4', 'enterprise_customer', '0', '/4', '人才团队信息', 'com.everhomes.customer.CustomerTalent', '0', NULL, '2', '1', '2017-08-18 02:24:19');
INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ('5', 'enterprise_customer', '17', '/17/5', '商标信息', 'com.everhomes.customer.CustomerTrademark', '0', NULL, '2', '1', '2017-08-18 02:24:19');
INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ('6', 'enterprise_customer', '0', '/6', '申报项目', 'com.everhomes.customer.CustomerApplyProject', '0', NULL, '2', '1', '2017-08-18 02:24:20');
INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ('7', 'enterprise_customer', '0', '/7', '工商信息', 'com.everhomes.customer.CustomerCommercial', '0', NULL, '2', '1', '2017-08-18 02:24:20');
INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ('8', 'enterprise_customer', '0', '/8', '投融情况', 'com.everhomes.customer.CustomerInvestment', '0', NULL, '2', '1', '2017-08-18 02:24:20');
INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ('9', 'enterprise_customer', '0', '/9', '经济指标', 'com.everhomes.customer.CustomerEconomicIndicator', '0', NULL, '2', '1', '2017-08-18 02:24:20');
INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ('10', 'enterprise_customer', '1', '/1/10', '基本信息', 'com.everhomes.customer.EnterpriseCustomer', '0', NULL, '2', '1', '2017-08-18 02:24:20');
INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ('11', 'enterprise_customer', '1', '/1/11', '企业情况', 'com.everhomes.customer.EnterpriseCustomer', '0', NULL, '2', '1', '2017-08-18 02:24:20');
INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ('12', 'enterprise_customer', '1', '/1/12', '员工情况', 'com.everhomes.customer.EnterpriseCustomer', '0', NULL, '2', '1', '2017-08-18 02:24:21');
INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ('13', 'contract', '0', '/13', '合同信息', '', '0', NULL, '2', '1', '2017-08-18 02:24:21');
INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ('14', 'contract', '13', '/13/14', '基本信息', '', '0', NULL, '2', '1', '2017-08-18 02:24:21');
INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ('15', 'contract', '13', '/13/15', '合同概览', '', '0', NULL, '2', '1', '2017-08-18 02:24:21');
INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ('16', 'enterprise_customer', '17', '/17/16', '专利信息', 'com.everhomes.customer.CustomerPatent', '0', NULL, '2', '1', '2017-08-23 10:54:35');
INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ('17', 'enterprise_customer', '0', '/17', '知识产权', '', '0', NULL, '1', '1', '2017-08-30 10:47:42');
INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ('18', 'enterprise_customer', '17', '/17/18', '证书', 'com.everhomes.customer.CustomerCertificate', '0', NULL, '2', '1', '2017-08-23 10:54:35');
INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ('19', 'contract', '13', '/13/19', '计价条款', 'chargeItems', '0', NULL, '2', '1', '2017-08-18 02:24:21');
INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ('20', 'contract', '13', '/13/20', '调租计划', 'rentAdjustment', '0', NULL, '2', '1', '2017-08-18 02:24:21');
INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ('21', 'contract', '13', '/13/21', '免租计划', 'rentFree', '0', NULL, '2', '1', '2017-08-18 02:24:21');
INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ('22', 'contract', '13', '/13/22', '费用清单', 'chargeList', '0', NULL, '2', '1', '2017-08-18 02:24:21');
INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ('23', 'apartment', '0', '/23', '资产门牌', 'apartment', '0', NULL, '2', '1', '2017-09-27 11:44:31');


INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('1', 'enterprise_customer', 'customerNumber', '客户编号', 'String', '10', '/1/10', '0', NULL, '2', '1', '2017-08-18 02:24:23', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('2', 'enterprise_customer', 'name', '客户名称', 'String', '10', '/1/10', '0', NULL, '2', '1', '2017-08-18 02:24:24', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('3', 'enterprise_customer', 'nickName', '简称', 'String', '10', '/1/10', '0', NULL, '2', '1', '2017-08-18 02:24:24', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('4', 'enterprise_customer', 'categoryItemId', '客户类型', 'Long', '10', '/1/10', '0', NULL, '2', '1', '2017-08-18 02:24:24', '{\"fieldParamType\": \"select\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('5', 'enterprise_customer', 'levelItemId', '客户级别', 'Long', '10', '/1/10', '0', NULL, '2', '1', '2017-08-18 02:24:25', '{\"fieldParamType\": \"select\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('6', 'enterprise_customer', 'sourceItemId', '认知途径', 'Long', '10', '/1/10', '0', NULL, '2', '1', '2017-08-18 02:24:25', '{\"fieldParamType\": \"select\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('7', 'enterprise_customer', 'contactName', '联系人', 'String', '10', '/1/10', '0', NULL, '2', '1', '2017-08-18 02:24:25', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('8', 'enterprise_customer', 'contactGenderItemId', '联系人性别', 'Long', '10', '/1/10', '0', NULL, '2', '1', '2017-08-18 02:24:25', '{\"fieldParamType\": \"select\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('9', 'enterprise_customer', 'contactMobile', '手机号码', 'String', '10', '/1/10', '0', NULL, '2', '1', '2017-08-18 02:24:25', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('10', 'enterprise_customer', 'contactPhone', '座机号码', 'String', '10', '/1/10', '0', NULL, '2', '1', '2017-08-18 02:24:26', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('11', 'enterprise_customer', 'contactOffficePhone', '办公电话', 'String', '10', '/1/10', '0', NULL, '2', '1', '2017-08-18 02:24:26', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('12', 'enterprise_customer', 'contactFamilyPhone', '家庭电话', 'String', '10', '/1/10', '0', NULL, '2', '1', '2017-08-18 02:24:26', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('13', 'enterprise_customer', 'contactEmail', '电子邮件', 'String', '10', '/1/10', '0', NULL, '2', '1', '2017-08-18 02:24:26', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('14', 'enterprise_customer', 'contactFax', '传真', 'String', '11', '/1/11', '0', NULL, '2', '1', '2017-08-18 02:24:26', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('15', 'enterprise_customer', 'contactAddress', '地址', 'String', '11', '/1/11', '0', NULL, '2', '1', '2017-08-18 02:24:26', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('16', 'enterprise_customer', 'corpEmail', '企业邮箱', 'String', '11', '/1/11', '0', NULL, '2', '1', '2017-08-18 02:24:26', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('17', 'enterprise_customer', 'corpWebsite', '企业网址', 'String', '11', '/1/11', '0', NULL, '2', '1', '2017-08-18 02:24:27', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('18', 'enterprise_customer', 'corpRegAddress', '注册地址', 'String', '11', '/1/11', '0', NULL, '2', '1', '2017-08-18 02:24:27', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('19', 'enterprise_customer', 'corpOpAddress', '经营地址', 'String', '11', '/1/11', '0', NULL, '2', '1', '2017-08-18 02:24:27', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('20', 'enterprise_customer', 'corpLegalPerson', '法人代表', 'String', '11', '/1/11', '0', NULL, '2', '1', '2017-08-18 02:24:27', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('21', 'enterprise_customer', 'corpRegCapital', '注册资金(万元）', 'BigDecimal', '11', '/1/11', '0', NULL, '2', '1', '2017-08-18 02:24:27', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('22', 'enterprise_customer', 'corpNatureItemId', '企业性质', 'Long', '11', '/1/11', '0', NULL, '2', '1', '2017-08-18 02:24:28', '{\"fieldParamType\": \"select\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('23', 'enterprise_customer', 'corpScale', '企业规模', 'BigDecimal', '11', '/1/11', '0', NULL, '2', '1', '2017-08-18 02:24:28', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('24', 'enterprise_customer', 'corpIndustryItemId', '行业类型', 'Long', '11', '/1/11', '0', NULL, '2', '1', '2017-08-18 02:24:28', '{\"fieldParamType\": \"select\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('25', 'enterprise_customer', 'corpPurposeItemId', '企业定位', 'Long', '11', '/1/11', '0', NULL, '2', '1', '2017-08-18 02:24:28', '{\"fieldParamType\": \"select\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('26', 'enterprise_customer', 'corpAnnualTurnover', '年营业额(万元)', 'BigDecimal', '11', '/1/11', '0', NULL, '2', '1', '2017-08-18 02:24:28', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('27', 'enterprise_customer', 'corpBusinessScope', '营业范围', 'String', '11', '/1/11', '0', NULL, '2', '1', '2017-08-18 02:24:28', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('28', 'enterprise_customer', 'corpBusinessLicense', '营业执照号', 'String', '11', '/1/11', '0', NULL, '2', '1', '2017-08-18 02:24:28', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('30', 'enterprise_customer', 'contactAddressId', '门牌号', 'Long', '11', '/1/11', '0', NULL, '2', '1', '2017-08-18 02:24:28', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('31', 'enterprise_customer', 'corpSiteArea', '场地面积', 'BigDecimal', '11', '/1/11', '0', NULL, '2', '1', '2017-08-18 02:24:28', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('32', 'enterprise_customer', 'corpEntryDate', '入住园区日期', 'Date', '11', '/1/11', '0', NULL, '2', '1', '2017-08-18 02:24:29', '{\"fieldParamType\": \"datetime\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('33', 'enterprise_customer', 'corpProductCategoryItemId', '产品类型', 'Long', '11', '/1/11', '0', NULL, '2', '1', '2017-08-18 02:24:29', '{\"fieldParamType\": \"select\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('34', 'enterprise_customer', 'corpProductDesc', '主要技术及产品', 'String', '11', '/1/11', '0', NULL, '2', '1', '2017-08-18 02:24:29', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('35', 'enterprise_customer', 'corpQualificationItemId', '企业资质认证', 'Long', '11', '/1/11', '0', NULL, '2', '1', '2017-08-18 02:24:29', '{\"fieldParamType\": \"select\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('36', 'enterprise_customer', 'corpLogoUri', '企业LOGO', 'String', '11', '/1/11', '0', NULL, '2', '1', '2017-08-18 02:24:29', '{\"fieldParamType\": \"image\", \"length\": 1}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('37', 'enterprise_customer', 'corpDescription', '企业简介', 'String', '11', '/1/11', '0', NULL, '2', '1', '2017-08-18 02:24:29', '{\"fieldParamType\": \"text\", \"length\": 320}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('38', 'enterprise_customer', 'corpEmployeeAmount', '员工总数', 'Integer', '12', '/1/12', '0', NULL, '2', '1', '2017-08-18 02:24:29', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('39', 'enterprise_customer', 'corpEmployeeAverageAge', '员工平均年龄', 'Double', '12', '/1/12', '0', NULL, '2', '1', '2017-08-18 02:24:29', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('40', 'enterprise_customer', 'corpManagerAverageAge', '高管平均年龄', 'Double', '12', '/1/12', '0', NULL, '2', '1', '2017-08-18 02:24:30', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('41', 'enterprise_customer', 'corpEmployeeAmountFemale', '女性员工总数', 'Integer', '12', '/1/12', '0', NULL, '2', '1', '2017-08-18 02:24:30', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('42', 'enterprise_customer', 'corpEmployeeAmountMale', '男性员工总数', 'Integer', '12', '/1/12', '0', NULL, '2', '1', '2017-08-18 02:24:30', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('43', 'enterprise_customer', 'corpEmployeeAmountRd', '研发员工总数', 'Integer', '12', '/1/12', '0', NULL, '2', '1', '2017-08-18 02:24:30', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('44', 'enterprise_customer', 'corpEmployeeReturneeRate', '海归人数占比', 'Double', '12', '/1/12', '0', NULL, '2', '1', '2017-08-18 02:24:30', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('45', 'enterprise_customer', 'managerName', '总经理', 'String', '12', '/1/12', '0', NULL, '2', '1', '2017-08-18 02:24:30', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('46', 'enterprise_customer', 'managerPhone', '总经理电话', 'String', '12', '/1/12', '0', NULL, '2', '1', '2017-08-18 02:24:31', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('47', 'enterprise_customer', 'managerEmail', '总经理邮箱', 'String', '12', '/1/12', '0', NULL, '2', '1', '2017-08-18 02:24:31', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('48', 'enterprise_customer', 'remark', '备注', 'String', '12', '/1/12', '0', NULL, '2', '1', '2017-08-18 02:24:31', '{\"fieldParamType\": \"multiText\", \"length\": 2048}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('100', 'contract', 'contractNumber', '合同编号', 'String', '14', '/13/14', '1', NULL, '2', '1', '2017-08-18 02:24:45', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('101', 'contract', 'name', '合同名称', 'String', '14', '/13/14', '1', NULL, '2', '1', '2017-08-18 02:24:45', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('102', 'contract', 'customerId', '客户名称', 'Long', '14', '/13/14', '1', NULL, '2', '1', '2017-08-18 02:24:45', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('103', 'contract', 'partyAId', '出租方', 'Long', '14', '/13/14', '1', NULL, '2', '1', '2017-08-18 02:24:45', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('104', 'contract', 'contractType', '合同属性', 'Byte', '14', '/13/14', '1', NULL, '2', '1', '2017-08-18 02:24:45', '{\"fieldParamType\": \"select\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('105', 'contract', 'categoryItemId', '合同类型', 'Long', '14', '/13/14', '1', NULL, '2', '1', '2017-08-18 02:24:45', '{\"fieldParamType\": \"select\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('106', 'contract', 'parentId', '原合同', 'Long', '14', '/13/14', '1', NULL, '2', '1', '2017-08-18 02:24:45', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('107', 'contract', 'rootParentId', '初始合同', 'Long', '14', '/13/14', '1', NULL, '2', '1', '2017-08-18 02:24:45', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('108', 'contract', 'filingPlace', '归档地', 'String', '14', '/13/14', '0', NULL, '2', '1', '2017-08-18 02:24:46', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('109', 'contract', 'recordNumber', '备案号', 'String', '14', '/13/14', '0', NULL, '2', '1', '2017-08-18 02:24:46', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('110', 'contract', 'contractStartDate', '开始日期', 'Long', '14', '/13/14', '1', NULL, '2', '1', '2017-08-18 02:24:46', '{\"fieldParamType\": \"datetime\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('111', 'contract', 'contractEndDate', '结束日期', 'Long', '14', '/13/14', '1', NULL, '2', '1', '2017-08-18 02:24:46', '{\"fieldParamType\": \"datetime\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('112', 'contract', 'signedTime', '签约日期', 'Long', '14', '/13/14', '1', NULL, '2', '1', '2017-08-18 02:24:46', '{\"fieldParamType\": \"datetime\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('113', 'contract', 'signedPurpose', '签约原因', '签约原因', '14', '/13/14', '0', NULL, '2', '1', '2017-08-18 02:24:46', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('114', 'contract', 'contractSituation', '合同情况', 'String', '14', '/13/14', '0', NULL, '2', '1', '2017-08-18 02:24:46', '{\"fieldParamType\": \"multiText\", \"length\": 2048}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('115', 'contract', 'apartments', '合同资产', 'List<BuildingApartmentDTO>', '14', '/13/14', '1', NULL, '2', '1', '2017-08-18 02:24:46', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('117', 'contract', 'rent', '租赁总额', 'BigDecimal', '15', '/13/15', '1', NULL, '2', '1', '2017-08-18 02:24:46', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('118', 'contract', 'rentSize', '租赁总面积', 'Double', '15', '/13/15', '1', NULL, '2', '1', '2017-08-18 02:24:46', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('119', 'contract', 'deposit', '定金', 'BigDecimal', '15', '/13/15', '0', NULL, '2', '1', '2017-08-18 02:24:47', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('120', 'contract', 'depositTime', '定金最迟收取日期', 'Long', '15', '/13/15', '0', NULL, '2', '1', '2017-08-18 02:24:47', '{\"fieldParamType\": \"datetime\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('121', 'contract', 'contractualPenalty', '违约金', 'BigDecimal', '15', '/13/15', '0', NULL, '2', '1', '2017-08-18 02:24:47', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('122', 'contract', 'penaltyRemark', '违约说明', 'String', '15', '/13/15', '0', NULL, '2', '1', '2017-08-18 02:24:48', '{\"fieldParamType\": \"text\", \"length\": 64}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('123', 'contract', 'freeDays', '免租期', 'Integer', '15', '/13/15', '0', NULL, '2', '1', '2017-08-18 02:24:48', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('124', 'contract', 'freeParkingSpace', '赠送车位数量', 'Integer', '15', '/13/15', '0', NULL, '2', '1', '2017-08-18 02:24:48', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('125', 'contract', 'decorateBeginDate', '装修开始日期', 'Integer', '15', '/13/15', '0', NULL, '2', '1', '2017-08-18 02:24:49', '{\"fieldParamType\": \"datetime\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('126', 'contract', 'decorateEndDate', '装修结束日期', 'Integer', '15', '/13/15', '0', NULL, '2', '1', '2017-08-18 02:24:49', '{\"fieldParamType\": \"datetime\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('127', 'contract', 'downpayment', '首付总额', 'BigDecimal', '15', '/13/15', '0', NULL, '2', '1', '2017-08-18 02:24:49', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('128', 'contract', 'downpaymentTime', '首付截止日期', 'Long', '15', '/13/15', '0', NULL, '2', '1', '2017-08-18 02:24:49', '{\"fieldParamType\": \"datetime\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('129', 'contract', 'commission', '佣金', 'BigDecimal', '15', '/13/15', '0', NULL, '2', '1', '2017-08-18 02:24:50', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('130', 'contract', 'paidType', '付款方式', 'String', '15', '/13/15', '0', NULL, '2', '1', '2017-08-18 02:24:50', '{\"fieldParamType\": \"select\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('131', 'contract', 'status', '合同状态', 'Byte', '15', '/13/15', '1', NULL, '2', '1', '2017-08-18 02:24:50', '{\"fieldParamType\": \"select\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('132', 'contract', 'createUid', '签约经办人', 'Long', '15', '/13/15', '1', NULL, '2', '1', '2017-08-18 02:24:50', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('133', 'contract', 'invalidReason', '作废原因', 'String', '15', '/13/15', '0', NULL, '2', '1', '2017-08-18 02:24:50', '{\"fieldParamType\": \"text\", \"length\": 64}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('134', 'contract', 'denunciationReason', '退约原因', 'String', '15', '/13/15', '0', NULL, '2', '1', '2017-08-18 02:24:50', '{\"fieldParamType\": \"text\", \"length\": 64}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('135', 'contract', 'remark', '备注', 'String', '15', '/13/15', '0', NULL, '2', '1', '2017-08-18 02:24:50', '{\"fieldParamType\": \"multiText\", \"length\": 2048}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('136', 'contract', 'attachments', '附件', 'List<ContractAttachmentDTO>', '15', '/13/15', '0', NULL, '2', '1', '2017-08-18 02:24:50', '{\"fieldParamType\": \"file\", \"length\": 9}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('140', 'enterprise_customer', 'name', '名称', 'String', '4', '/4', '0', NULL, '2', '1', '2017-08-19 09:14:27', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('141', 'enterprise_customer', 'gender', '性别', 'Long', '4', '/4', '0', NULL, '2', '1', '2017-08-19 09:14:27', '{\"fieldParamType\": \"select\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('142', 'enterprise_customer', 'phone', '联系电话', 'String', '4', '/4', '0', NULL, '2', '1', '2017-08-19 09:14:27', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('143', 'enterprise_customer', 'nationalityItemId', '国籍', 'Long', '4', '/4', '0', NULL, '2', '1', '2017-08-19 09:14:27', '{\"fieldParamType\": \"select\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('144', 'enterprise_customer', 'degreeItemId', '最高学历', 'Long', '4', '/4', '0', NULL, '2', '1', '2017-08-19 09:14:27', '{\"fieldParamType\": \"select\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('145', 'enterprise_customer', 'graduateSchool', '毕业学校', 'String', '4', '/4', '0', NULL, '2', '1', '2017-08-19 09:14:27', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('146', 'enterprise_customer', 'major', '所属专业', 'String', '4', '/4', '0', NULL, '2', '1', '2017-08-19 09:14:27', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('147', 'enterprise_customer', 'experience', '工作经验', 'Integer', '4', '/4', '0', NULL, '2', '1', '2017-08-19 09:14:27', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('148', 'enterprise_customer', 'returneeFlag', '是否海归', 'Long', '4', '/4', '0', NULL, '2', '1', '2017-08-19 09:14:27', '{\"fieldParamType\": \"select\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('149', 'enterprise_customer', 'abroadItemId', '留学国家', 'Long', '4', '/4', '0', NULL, '2', '1', '2017-08-19 09:14:27', '{\"fieldParamType\": \"select\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('150', 'enterprise_customer', 'jobPosition', '聘任职务', 'String', '4', '/4', '0', NULL, '2', '1', '2017-08-19 09:14:28', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('151', 'enterprise_customer', 'technicalTitleItemId', '技术职称', 'Long', '4', '/4', '0', NULL, '2', '1', '2017-08-19 09:14:28', '{\"fieldParamType\": \"select\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('152', 'enterprise_customer', 'individualEvaluationItemId', '个人评定', 'Long', '4', '/4', '0', NULL, '2', '1', '2017-08-19 09:14:28', '{\"fieldParamType\": \"select\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('153', 'enterprise_customer', 'personalCertificate', '个人证书', 'String', '4', '/4', '0', NULL, '2', '1', '2017-08-19 09:14:28', '{\"fieldParamType\": \"text\", \"length\": 64}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('154', 'enterprise_customer', 'careerExperience', '主要职业经历', 'String', '4', '/4', '0', NULL, '2', '1', '2017-08-19 09:14:28', '{\"fieldParamType\": \"text\", \"length\": 2048}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('155', 'enterprise_customer', 'remark', '人才备注', 'String', '4', '/4', '0', NULL, '2', '1', '2017-08-19 09:14:28', '{\"fieldParamType\": \"multiText\", \"length\": 2048}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('156', 'enterprise_customer', 'projectName', '项目名称', 'String', '6', '/6', '0', NULL, '2', '1', '2017-08-19 09:48:57', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('157', 'enterprise_customer', 'projectSource', '项目来源', 'String', '6', '/6', '0', NULL, '2', '1', '2017-08-19 09:48:57', '{\"fieldParamType\": \"select\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('158', 'enterprise_customer', 'projectEstablishDate', '项目立项日期', 'Long', '6', '/6', '0', NULL, '2', '1', '2017-08-19 09:48:57', '{\"fieldParamType\": \"datetime\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('159', 'enterprise_customer', 'projectCompleteDate', '项目完成日期', 'Long', '6', '/6', '0', NULL, '2', '1', '2017-08-19 09:48:57', '{\"fieldParamType\": \"datetime\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('160', 'enterprise_customer', 'projectAmount', '获批项目金额', 'BigDecimal', '6', '/6', '0', NULL, '2', '1', '2017-08-19 09:48:57', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('161', 'enterprise_customer', 'name', '商标名称', 'String', '5', '/17/5', '0', NULL, '2', '1', '2017-08-23 10:56:15', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('162', 'enterprise_customer', 'registeDate', '注册日期', 'Long', '5', '/17/5', '0', NULL, '2', '1', '2017-08-23 10:56:15', '{\"fieldParamType\": \"datetime\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('163', 'enterprise_customer', 'trademarkTypeItemId', '商标类型', 'Long', '5', '/17/5', '0', NULL, '2', '1', '2017-08-23 10:56:15', '{\"fieldParamType\": \"select\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('164', 'enterprise_customer', 'trademarkAmount', '商标数量', 'Integer', '5', '/17/5', '0', NULL, '2', '1', '2017-08-23 10:56:16', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('165', 'enterprise_customer', 'name', '证书名称', 'String', '16', '/17/16', '0', NULL, '2', '1', '2017-08-24 01:20:50', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('166', 'enterprise_customer', 'patentName', '专利名称', 'String', '16', '/17/16', '0', NULL, '2', '1', '2017-08-24 01:20:50', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('167', 'enterprise_customer', 'applicationNumber', '授权号', 'String', '16', '/17/16', '0', NULL, '2', '1', '2017-08-24 01:20:50', '{\"fieldParamType\": \"datetime\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('168', 'enterprise_customer', 'registeDate', '注册日期', 'Long', '16', '/17/16', '0', NULL, '2', '1', '2017-08-24 01:20:50', '{\"fieldParamType\": \"select\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('169', 'enterprise_customer', 'patentTypeItemId', '专利类型', 'Long', '16', '/17/16', '0', NULL, '2', '1', '2017-08-24 01:20:50', '{\"fieldParamType\": \"select\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('170', 'enterprise_customer', 'patentStatusItemId', '专利状态', 'Long', '16', '/17/16', '0', NULL, '2', '1', '2017-08-24 01:20:52', '{\"fieldParamType\": \"select\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('171', 'enterprise_customer', 'enterpriseTypeItemId', '企业类型', 'Long', '7', '/7', '0', NULL, '2', '1', '2017-08-24 04:26:20', '{\"fieldParamType\": \"select\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('172', 'enterprise_customer', 'shareTypeItemId', '控股情况', 'Long', '7', '/7', '0', NULL, '2', '1', '2017-08-24 04:26:22', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('173', 'enterprise_customer', 'contact', '联系人', 'String', '7', '/7', '0', NULL, '2', '1', '2017-08-24 04:26:23', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('174', 'enterprise_customer', 'contactNumber', '联系人电话', 'String', '7', '/7', '0', NULL, '2', '1', '2017-08-24 04:26:23', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('175', 'enterprise_customer', 'unifiedSocialCreditCode', '统一社会信用代码', 'String', '7', '/7', '0', NULL, '2', '1', '2017-08-24 04:26:23', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('176', 'enterprise_customer', 'businessScope', '主营业务', 'String', '7', '/7', '0', NULL, '2', '1', '2017-08-24 04:26:23', '{\"fieldParamType\": \"datetime\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('177', 'enterprise_customer', 'foundationDate', '成立日期', 'Long', '7', '/7', '0', NULL, '2', '1', '2017-08-24 04:26:24', '{\"fieldParamType\": \"datetime\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('178', 'enterprise_customer', 'taxRegistrationDate', '税务登记日期', 'Long', '7', '/7', '0', NULL, '2', '1', '2017-08-24 04:26:24', '{\"fieldParamType\": \"datetime\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('179', 'enterprise_customer', 'validityBeginDate', '有效开始日期', 'Long', '7', '/7', '0', NULL, '2', '1', '2017-08-24 04:26:24', '{\"fieldParamType\": \"datetime\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('180', 'enterprise_customer', 'validityEndDate', '有效截止日期', 'Long', '7', '/7', '0', NULL, '2', '1', '2017-08-24 04:26:24', '{\"fieldParamType\": \"datetime\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('181', 'enterprise_customer', 'changeDate', '变更日期', 'Long', '7', '/7', '0', NULL, '2', '1', '2017-08-24 04:26:24', '{\"fieldParamType\": \"datetime\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('182', 'enterprise_customer', 'businessLicenceDate', '出营业执照日期', 'Long', '7', '/7', '0', NULL, '2', '1', '2017-08-24 04:26:24', '{\"fieldParamType\": \"datetime\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('183', 'enterprise_customer', 'liquidationCommitteeRecoredDate', '清算组备案日期', 'Long', '7', '/7', '0', NULL, '2', '1', '2017-08-24 04:26:24', '{\"fieldParamType\": \"datetime\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('184', 'enterprise_customer', 'cancelDate', '注销日期', 'Long', '7', '/7', '0', NULL, '2', '1', '2017-08-24 04:26:24', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('185', 'enterprise_customer', 'registeredAddr', '注册地址', 'String', '7', '/7', '0', NULL, '2', '1', '2017-08-24 04:26:24', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('186', 'enterprise_customer', 'registeredCapital', '注册资金', 'BigDecimal', '7', '/7', '0', NULL, '2', '1', '2017-08-24 04:26:25', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('187', 'enterprise_customer', 'paidupApital', '实到资金', 'BigDecimal', '7', '/7', '0', NULL, '2', '1', '2017-08-24 04:26:25', '{\"fieldParamType\": \"select\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('188', 'enterprise_customer', 'propertyType', '房产性质', 'Long', '7', '/7', '0', NULL, '2', '1', '2017-08-24 04:26:25', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('189', 'enterprise_customer', 'governmentProject', '获得政府扶持项目', 'String', '8', '/8', '0', NULL, '2', '1', '2017-08-24 12:40:45', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('190', 'enterprise_customer', 'bankLoans', '银行贷款', 'BigDecimal', '8', '/8', '0', NULL, '2', '1', '2017-08-24 12:40:46', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('191', 'enterprise_customer', 'equityFinancing', '股权融资', 'BigDecimal', '8', '/8', '0', NULL, '2', '1', '2017-08-24 12:40:46', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('192', 'enterprise_customer', 'totalAssets', '资产总计', 'BigDecimal', '9', '/9', '0', NULL, '2', '1', '2017-08-25 02:27:27', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('193', 'enterprise_customer', 'totalProfit', '利润总额', 'BigDecimal', '9', '/9', '0', NULL, '2', '1', '2017-08-25 02:27:27', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('194', 'enterprise_customer', 'sales', '销售额', 'BigDecimal', '9', '/9', '0', NULL, '2', '1', '2017-08-25 02:27:28', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('195', 'enterprise_customer', 'turnover', '营业额', 'BigDecimal', '9', '/9', '0', NULL, '2', '1', '2017-08-25 02:27:28', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('196', 'enterprise_customer', 'taxIndex', '税收指标', 'BigDecimal', '9', '/9', '0', NULL, '2', '1', '2017-08-25 02:27:28', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('197', 'enterprise_customer', 'taxPayment', '纳税额', 'BigDecimal', '9', '/9', '0', NULL, '2', '1', '2017-08-25 02:27:29', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('198', 'enterprise_customer', 'valueAddedTax', '增值税', 'BigDecimal', '9', '/9', '0', NULL, '2', '1', '2017-08-25 02:27:29', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('199', 'enterprise_customer', 'businessTax', '营业税', 'BigDecimal', '9', '/9', '0', NULL, '2', '1', '2017-08-25 02:27:29', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('200', 'enterprise_customer', 'businessIncomeTax', '企业所得税', 'BigDecimal', '9', '/9', '0', NULL, '2', '1', '2017-08-25 02:27:29', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('201', 'enterprise_customer', 'foreignCompanyIncomeTax', '外企所得税', 'BigDecimal', '9', '/9', '0', NULL, '2', '1', '2017-08-25 02:27:29', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('202', 'enterprise_customer', 'individualIncomeTax', '个人所得税', 'BigDecimal', '9', '/9', '0', NULL, '2', '1', '2017-08-25 02:27:29', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('203', 'enterprise_customer', 'totalTaxAmount', '税费合计', 'BigDecimal', '9', '/9', '0', NULL, '2', '1', '2017-08-25 02:27:30', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('204', 'enterprise_customer', 'name', '证书名称', 'String', '18', '/17/18', '0', NULL, '2', '1', '2017-08-30 14:11:01', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('205', 'enterprise_customer', 'certificateNumber', '证书编号', 'String', '18', '/17/18', '0', NULL, '2', '1', '2017-08-30 14:11:01', '{\"fieldParamType\": \"datetime\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('206', 'enterprise_customer', 'registeDate', '获得日期', 'Long', '18', '/17/18', '0', NULL, '2', '1', '2017-08-30 14:11:01', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('207', 'contract', 'rentCycle', '租赁周期', 'Integer', '14', '/13/14', '1', NULL, '2', '1', '2017-08-18 02:24:46', '{\"fieldParamType\": \"select\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('208', 'enterprise_customer', 'status', '项目状态', 'Byte', '6', '/6', '0', NULL, '2', '1', '2017-08-19 09:48:57', '{\"fieldParamType\": \"text\", \"length\": 32}');



INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('209', 'apartment', 'apartmentNumber', '门牌编号', 'String', '23', '/23', '0', NULL, '2', '1', '2017-09-27 19:48:57', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('210', 'apartment', 'apartmentName', '门牌名称', 'String', '23', '/23', '0', NULL, '2', '1', '2017-09-27 19:48:57', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('211', 'apartment', 'addressUnit', '单元', 'String', '23', '/23', '0', NULL, '2', '1', '2017-09-27 19:48:57', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('212', 'apartment', 'layout', '户型', 'String', '23', '/23', '0', NULL, '2', '1', '2017-09-27 19:48:57', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('213', 'apartment', 'apartmentFloor', '楼层名称', 'String', '23', '/23', '0', NULL, '2', '1', '2017-09-27 19:48:57', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('214', 'apartment', 'categoryItemId', '门牌类型', 'String', '23', '/23', '0', NULL, '2', '1', '2017-09-27 19:48:57', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('215', 'apartment', 'sourceItemId', '门牌来源', 'String', '23', '/23', '0', NULL, '2', '1', '2017-09-27 19:48:57', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('217', 'apartment', 'addressStatus', '门牌状态', 'String', '23', '/23', '0', NULL, '2', '1', '2017-09-27 19:48:57', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('218', 'apartment', 'decorateStatus', '装修状态', 'String', '23', '/23', '0', NULL, '2', '1', '2017-09-27 19:48:57', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('219', 'apartment', 'buildArea', '建筑面积', 'String', '23', '/23', '0', NULL, '2', '1', '2017-09-27 19:48:57', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('220', 'apartment', 'innerArea', '使用面积', 'String', '23', '/23', '0', NULL, '2', '1', '2017-09-27 19:48:57', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('221', 'apartment', 'chargeArea', '收费面积', 'String', '23', '/23', '0', NULL, '2', '1', '2017-09-27 19:48:57', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('222', 'apartment', 'sharedArea', '分摊面积', 'String', '23', '/23', '0', NULL, '2', '1', '2017-09-27 19:48:57', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('223', 'apartment', 'rentArea', '出租面积', 'String', '23', '/23', '0', NULL, '2', '1', '2017-09-27 19:48:57', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('224', 'apartment', 'orientation', '朝向', 'String', '23', '/23', '0', NULL, '2', '1', '2017-09-27 19:48:57', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('225', 'apartment', 'address', '地址', 'String', '23', '/23', '0', NULL, '2', '1', '2017-09-27 19:48:57', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('226', 'apartment', 'addressOwnershipId', '产权归属', 'Long', '23', '/23', '0', NULL, '2', '1', '2017-09-27 19:48:57', '{\"fieldParamType\": \"select\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('227', 'apartment', 'attachments', '门牌附件', 'List<AddressAttachmentDTO>', '23', '/23', '0', NULL, '2', '1', '2017-09-27 19:48:57', '{\"fieldParamType\": \"file\", \"length\": 9}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('228', 'apartment', 'livingStatus', '入住状况', 'Byte', '23', '/23', '0', NULL, '2', '1', '2017-09-27 19:48:57', '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ('229', 'apartment', 'remark', '备注', 'String', '23', '/23', '0', NULL, '2', '1', '2017-09-27 19:48:57', '{\"fieldParamType\": \"multiText\", \"length\": 2048}');

                                                                                                                                                                                                                      





delete from eh_var_field_items where field_id = 25;
SET @item_id = (SELECT MAX(id) FROM `eh_var_field_items`); 
INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '25', '总部', '1', '2', '1', UTC_TIMESTAMP());
INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '25', '区域总部', '1', '2', '1', UTC_TIMESTAMP());
INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '25', '研发中心', '1', '2', '1', UTC_TIMESTAMP());
INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '25', '运营中心', '1', '2', '1', UTC_TIMESTAMP());
INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '25', '生产', '1', '2', '1', UTC_TIMESTAMP());
INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '25', '商业', '1', '2', '1', UTC_TIMESTAMP());
INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '25', '其他', '1', '2', '1', UTC_TIMESTAMP());

delete from eh_var_field_items where field_id = 172;
INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '172', '国有控股', '1', '2', '1', UTC_TIMESTAMP());
INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '172', '集体控股', '1', '2', '1', UTC_TIMESTAMP());
INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '172', '私人控股', '1', '2', '1', UTC_TIMESTAMP());
INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '172', '港澳台商控股', '1', '2', '1', UTC_TIMESTAMP());
INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '172', '外商投资', '1', '2', '1', UTC_TIMESTAMP());
INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '172', '其他', '1', '2', '1', UTC_TIMESTAMP());

delete from eh_var_field_items where field_id = 35;
INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '35', '高新技术企业', '1', '2', '1', UTC_TIMESTAMP());
INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '35', '软件企业', '1', '2', '1', UTC_TIMESTAMP());
INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '35', '文信企业', '1', '2', '1', UTC_TIMESTAMP());
INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '35', '小巨人企业', '1', '2', '1', UTC_TIMESTAMP());
INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '35', '留学生创业企业', '1', '2', '1', UTC_TIMESTAMP());
INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '35', '大学生创业企业', '1', '2', '1', UTC_TIMESTAMP());

INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '210', '单间', '1', '2', '1', UTC_TIMESTAMP());
INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '210', '一室一厅', '1', '2', '1', UTC_TIMESTAMP());
INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '210', '两室一厅', '1', '2', '1', UTC_TIMESTAMP());
INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '210', '两室两厅', '1', '2', '1', UTC_TIMESTAMP());
INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '210', '三室一厅', '1', '2', '1', UTC_TIMESTAMP());
INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '210', '三室两厅', '1', '2', '1', UTC_TIMESTAMP());
INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '210', '三室三厅', '1', '2', '1', UTC_TIMESTAMP());
INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '210', '四室两厅', '1', '2', '1', UTC_TIMESTAMP());
INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '210', '其他', '1', '2', '1', UTC_TIMESTAMP());

INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '188', '商品房', '1', '2', '1', UTC_TIMESTAMP());
INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '188', '存量房', '1', '2', '1', UTC_TIMESTAMP());
INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '188', '集资房', '1', '2', '1', UTC_TIMESTAMP());
INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '188', '平价房', '1', '2', '1', UTC_TIMESTAMP());
INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '188', '廉租住房', '1', '2', '1', UTC_TIMESTAMP());
INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '188', '经济适用住房', '1', '2', '1', UTC_TIMESTAMP());
INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '188', '公寓式住宅', '1', '2', '1', UTC_TIMESTAMP());
INSERT INTO `eh_var_field_items` (`id`, `module_name`, `field_id`, `display_name`, `default_order`, `status`, `creator_uid`, `create_time`) VALUES ((@item_id := @item_id + 1), 'enterprise_customer', '188', '其他', '1', '2', '1', UTC_TIMESTAMP());









