
-- 合同动态表单修改  by jiarui
UPDATE  eh_var_field_groups set title = '收款合同' WHERE  module_name ='contract' and title ='合同信息' AND  parent_id =0;
UPDATE `eh_var_fields`  SET `field_param`='{\"fieldParamType\": \"text\", \"length\": 32}' WHERE `module_name`='contract' AND `name`='contractType';
UPDATE `eh_var_field_scopes`  SET `field_param`='{\"fieldParamType\": \"text\", \"length\": 32}' WHERE  field_id IN (SELECT id FROM eh_var_fields   WHERE `module_name`='contract' AND `name`='contractType');
UPDATE `eh_var_fields`  SET `field_param`='{\"fieldParamType\": \"text\", \"length\": 32}' WHERE `module_name`='contract' AND `name`='status';
UPDATE `eh_var_field_scopes`  SET `field_param`='{\"fieldParamType\": \"text\", \"length\": 32}' WHERE  field_id IN (SELECT id FROM eh_var_fields   WHERE `module_name`='contract' AND `name`='status');
-- 表单select 自定义
UPDATE  eh_var_fields  SET field_param = REPLACE(field_param,'select','customizationSelect') WHERE module_name = 'enterprise_customer' AND `name` <> 'levelItemId';
UPDATE  eh_var_fields  SET field_param = REPLACE(field_param,'select','customizationSelect') WHERE module_name = 'contract' AND `name` NOT  IN ('contractType','status');

UPDATE  eh_var_field_scopes SET field_param = (SELECT field_param FROM eh_var_fields WHERE id = field_id);
-- 表单default  by jiarui

SET  @id = (SELECT MAX(id) FROM  eh_var_field_group_scopes);
INSERT INTO `eh_var_field_group_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `group_display_name`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_parent_id`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '1', '客户信息', '1', '2', '1', NOW(), NULL, NULL, NULL, NULL);
INSERT INTO `eh_var_field_group_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `group_display_name`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_parent_id`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '10', '基本信息', '1', '2', '1', NOW(), NULL, NULL, NULL, NULL);
INSERT INTO `eh_var_field_group_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `group_display_name`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_parent_id`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '11', '企业情况', '3', '2', '1',NOW(), NULL, NULL, NULL, NULL);
INSERT INTO `eh_var_field_group_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `group_display_name`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_parent_id`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '12', '员工情况', '4', '2', '1', NOW(), NULL, NULL, NULL, NULL);

SET  @id = (SELECT MAX(id) FROM  eh_var_field_scopes);
INSERT INTO `eh_var_field_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `field_id`, `field_param`, `field_display_name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_path`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '10', '2', '{\"fieldParamType\": \"text\", \"length\": 32}', '客户名称', '1', '1', '2', '1', now(), '1', NULL , NULL, '/1/10/');
INSERT INTO `eh_var_field_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `field_id`, `field_param`, `field_display_name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_path`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '10', '3', '{\"fieldParamType\": \"text\", \"length\": 32}', '简称', '0', '3', '2', '1', now(), NULL, NULL, NULL, '/1/10/');
INSERT INTO `eh_var_field_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `field_id`, `field_param`, `field_display_name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_path`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '10', '4', '{\"fieldParamType\": \"select\", \"length\": 32}', '客户类型', '0', '3', '2', '1', now(), NULL, NULL, NULL, '/1/10/');
INSERT INTO `eh_var_field_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `field_id`, `field_param`, `field_display_name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_path`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '10', '5', '{\"fieldParamType\": \"select\", \"length\": 32}', '客户级别', '1', '4', '2', '1', now(), '1', NULL , NULL, '/1/10/');
INSERT INTO `eh_var_field_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `field_id`, `field_param`, `field_display_name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_path`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '10', '7', '{\"fieldParamType\": \"text\", \"length\": 32}', '联系人', '1', '5', '2', '1', now(), '1', NULL , NULL, '/1/10/');
INSERT INTO `eh_var_field_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `field_id`, `field_param`, `field_display_name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_path`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '10', '10', '{\"fieldParamType\": \"text\", \"length\": 32}', '联系电话', '1', '6', '2', '1',now(), '1', NULL , NULL , '/1/10/');
INSERT INTO `eh_var_field_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `field_id`, `field_param`, `field_display_name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_path`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '10', '211', '{\"fieldParamType\": \"text\", \"length\": 32}', '跟进人', '0', '8', '2', '1', now(), '1', NULL , NULL, '/1/10/');

INSERT INTO `eh_var_field_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `field_id`, `field_param`, `field_display_name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_path`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '11', '15', '{\"fieldParamType\": \"text\", \"length\": 32}', '地址', '1', '8', '2', '1', now(), NULL, NULL, NULL, '/1/11/');
INSERT INTO `eh_var_field_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `field_id`, `field_param`, `field_display_name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_path`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '11', '17', '{\"fieldParamType\": \"text\", \"length\": 32}', '企业网址', '0', '11', '2', '1', now(), NULL, NULL, NULL, '/1/11/');
INSERT INTO `eh_var_field_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `field_id`, `field_param`, `field_display_name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_path`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '11', '24', '{\"fieldParamType\": \"select\", \"length\": 32}', '行业类型', '0', '13', '2', '1',now(), NULL, NULL, NULL, '/1/11/');
INSERT INTO `eh_var_field_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `field_id`, `field_param`, `field_display_name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_path`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '11', '36', '{\"fieldParamType\": \"image\", \"length\": 1}', '企业LOGO', '0', '46', '2', '1', now(), '1', NULL , NULL , '/1/11//');
INSERT INTO `eh_var_field_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `field_id`, `field_param`, `field_display_name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_path`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '11', '37', '{\"fieldParamType\": \"multiText\", \"length\": 2048}', '企业简介', '0', '26', '2', '1', now(), '1', NULL , NULL , '/1/11/');

SET  @id = (SELECT MAX(id) FROM  eh_var_field_item_scopes);
INSERT INTO `eh_var_field_item_scopes` (`id`, `namespace_id`, `module_name`, `field_id`, `item_id`, `item_display_name`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `business_value`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '5', '3', '普通客户', '3', '2', '1', now(), NULL, NULL, NULL, NULL);
INSERT INTO `eh_var_field_item_scopes` (`id`, `namespace_id`, `module_name`, `field_id`, `item_id`, `item_display_name`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `business_value`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '5', '4', '重要客户', '4', '2', '1', now(), NULL, NULL, NULL, NULL);
INSERT INTO `eh_var_field_item_scopes` (`id`, `namespace_id`, `module_name`, `field_id`, `item_id`, `item_display_name`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `business_value`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '5', '5', '意向客户', '5', '2', '1', now(), NULL, NULL, NULL, NULL);
INSERT INTO `eh_var_field_item_scopes` (`id`, `namespace_id`, `module_name`, `field_id`, `item_id`, `item_display_name`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `business_value`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '5', '6', '已成交客户', '6', '2', '1',now(), NULL, NULL, NULL, NULL);

INSERT INTO `eh_var_field_item_scopes` (`id`, `namespace_id`, `module_name`, `field_id`, `item_id`, `item_display_name`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `business_value`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '24', '202', '集成电路', '1', '2', '1', now(), NULL, NULL, NULL, NULL);
INSERT INTO `eh_var_field_item_scopes` (`id`, `namespace_id`, `module_name`, `field_id`, `item_id`, `item_display_name`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `business_value`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '24', '203', '软件', '1', '2', '1', now(), NULL, NULL, NULL, NULL);
INSERT INTO `eh_var_field_item_scopes` (`id`, `namespace_id`, `module_name`, `field_id`, `item_id`, `item_display_name`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `business_value`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '24', '204', '通信技术', '1', '2', '1', now(), NULL, NULL, NULL, NULL);
INSERT INTO `eh_var_field_item_scopes` (`id`, `namespace_id`, `module_name`, `field_id`, `item_id`, `item_display_name`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `business_value`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '24', '205', '生物医药', '1', '2', '1', now(), NULL, NULL, NULL, NULL);
INSERT INTO `eh_var_field_item_scopes` (`id`, `namespace_id`, `module_name`, `field_id`, `item_id`, `item_display_name`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `business_value`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '24', '206', '医疗器械', '1', '2', '1', now(), NULL, NULL, NULL, NULL);
INSERT INTO `eh_var_field_item_scopes` (`id`, `namespace_id`, `module_name`, `field_id`, `item_id`, `item_display_name`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `business_value`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '24', '207', '光机电', '1', '2', '1', now(), NULL, NULL, NULL, NULL);
INSERT INTO `eh_var_field_item_scopes` (`id`, `namespace_id`, `module_name`, `field_id`, `item_id`, `item_display_name`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `business_value`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '24', '208', '金融服务', '1', '2', '1', now(), NULL, NULL, NULL, NULL);
INSERT INTO `eh_var_field_item_scopes` (`id`, `namespace_id`, `module_name`, `field_id`, `item_id`, `item_display_name`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `business_value`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '24', '209', '新能源与环保', '1', '2', '1', now(), NULL, NULL, NULL, NULL);
INSERT INTO `eh_var_field_item_scopes` (`id`, `namespace_id`, `module_name`, `field_id`, `item_id`, `item_display_name`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `business_value`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '24', '210', '文化创意', '1', '2', '1', now(), NULL, NULL, NULL, NULL);
INSERT INTO `eh_var_field_item_scopes` (`id`, `namespace_id`, `module_name`, `field_id`, `item_id`, `item_display_name`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `business_value`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '24', '211', '商业-餐饮', '1', '2', '1', now(), NULL, NULL, NULL, NULL);
INSERT INTO `eh_var_field_item_scopes` (`id`, `namespace_id`, `module_name`, `field_id`, `item_id`, `item_display_name`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `business_value`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '24', '212', '商业-超市', '1', '2', '1', now(), NULL, NULL, NULL, NULL);
INSERT INTO `eh_var_field_item_scopes` (`id`, `namespace_id`, `module_name`, `field_id`, `item_id`, `item_display_name`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `business_value`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '24', '213', '商业-食堂', '1', '2', '1', now(), NULL, NULL, NULL, NULL);
INSERT INTO `eh_var_field_item_scopes` (`id`, `namespace_id`, `module_name`, `field_id`, `item_id`, `item_display_name`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `business_value`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '24', '214', '商业-其他', '1', '2', '1', now(), NULL, NULL, NULL, NULL);
INSERT INTO `eh_var_field_item_scopes` (`id`, `namespace_id`, `module_name`, `field_id`, `item_id`, `item_display_name`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `business_value`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '24', '215', '其他', '1', '2', '1', now(), NULL, NULL, NULL, NULL);


INSERT INTO `eh_var_field_item_scopes` (`id`, `namespace_id`, `module_name`, `field_id`, `item_id`, `item_display_name`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `business_value`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '4', '197', '业主', '1', '2', '1', now(), NULL, NULL, NULL, NULL);
INSERT INTO `eh_var_field_item_scopes` (`id`, `namespace_id`, `module_name`, `field_id`, `item_id`, `item_display_name`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `business_value`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '4', '198', '办公', '2', '2', '1', now(), NULL, NULL, NULL, NULL);
INSERT INTO `eh_var_field_item_scopes` (`id`, `namespace_id`, `module_name`, `field_id`, `item_id`, `item_display_name`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `business_value`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '4', '199', '商业', '3', '2', '1', now(), NULL, NULL, NULL, NULL);
INSERT INTO `eh_var_field_item_scopes` (`id`, `namespace_id`, `module_name`, `field_id`, `item_id`, `item_display_name`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `business_value`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '4', '200', '孵化器', '4', '2', '1', now(), NULL, NULL, NULL, NULL);
INSERT INTO `eh_var_field_item_scopes` (`id`, `namespace_id`, `module_name`, `field_id`, `item_id`, `item_display_name`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `business_value`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '4', '201', '物业公司', '5', '2', '1', now(), NULL, NULL, NULL, NULL);

