--  客户事件加入动态表单
--  by jiarui 20180626
SET  @groupId = (SELECT  max(id) FROM  eh_var_field_groups);
INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`) VALUES (( @groupId:= @groupId+1), 'enterprise_customer', '0', concat('/',@groupId), '客户事件', '', '0', NULL, '2', '1', NOW(), NULL, NULL);

SET  @fieldId = (SELECT  max(id) FROM  eh_var_fields);
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `field_param`) VALUES ((@fieldId:=@fieldId+1), 'enterprise_customer', 'creatorName', '操作人', 'String', @groupId, concat('/',@groupId,'/'), '1', NULL, '2', '1', now(), NULL, NULL, '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `field_param`) VALUES ((@fieldId:=@fieldId+1), 'enterprise_customer', 'operateTime', '操作时间', 'String', @groupId, concat('/',@groupId,'/'), '1', NULL, '2', '1', now(), NULL, NULL, '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `field_param`) VALUES ((@fieldId:=@fieldId+1), 'enterprise_customer', 'sourceType', '事件来源', 'String', @groupId, concat('/',@groupId,'/'), '1', NULL, '2', '1', now(), NULL, NULL, '{\"fieldParamType\": \"text\", \"length\": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `field_param`) VALUES ((@fieldId:=@fieldId+1), 'enterprise_customer', 'content', '描述', 'String', @groupId, concat('/',@groupId,'/'), '1', NULL, '2', '1', now(), NULL, NULL, '{\"fieldParamType\": \"text\", \"length\": 32}');


SET  @id = (SELECT MAX(id) FROM  eh_var_field_group_scopes);
INSERT INTO `eh_var_field_group_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `group_display_name`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_parent_id`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '1', '客户事件', '1', '2', '1', NOW(), NULL, NULL, NULL, NULL);

SET  @scope_id = (SELECT MAX(id) FROM  eh_var_field_scopes);
INSERT INTO `eh_var_field_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `field_id`, `field_param`, `field_display_name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_path`, `category_id`) VALUES ((@scope_id:=@scope_id+1), '0', 'enterprise_customer', @groupId, (@fieldId-3), '{\"fieldParamType\": \"text\", \"length\": 32}', '操作人', '1', '0', '2', '1', now(), NULL, NULL, NULL , concat('/',@groupId,'/'), NULL);
INSERT INTO `eh_var_field_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `field_id`, `field_param`, `field_display_name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_path`, `category_id`) VALUES ((@scope_id:=@scope_id+1), '0', 'enterprise_customer', @groupId, (@fieldId-2), '{\"fieldParamType\": \"text\", \"length\": 32}', '操作时间', '1', '1', '2', '1', now(), NULL, NULL, NULL , concat('/',@groupId,'/'), NULL);
INSERT INTO `eh_var_field_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `field_id`, `field_param`, `field_display_name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_path`, `category_id`) VALUES ((@scope_id:=@scope_id+1), '0', 'enterprise_customer', @groupId, (@fieldId-1), '{\"fieldParamType\": \"text\", \"length\": 32}', '事件来源', '1', '2', '2', '1', now(), NULL, NULL,NULL , concat('/',@groupId,'/'), NULL);
INSERT INTO `eh_var_field_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `field_id`, `field_param`, `field_display_name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_path`, `category_id`) VALUES ((@scope_id:=@scope_id+1), '0', 'enterprise_customer', @groupId, (@fieldId), '{\"fieldParamType\": \"text\", \"length\": 32}', '描述', '1', '3', '2', '1', now(), NULL, NULL, NULL , concat('/',@groupId,'/'), NULL);

-- end