CREATE TABLE `eh_new_preview` (
  `id` bigint(20) NOT NULL,
  `namespace_id` int(11) NOT NULL DEFAULT '0' COMMENT 'namespace id',
  `owner_type` varchar(32) DEFAULT NULL COMMENT 'ORGANIZATION',
  `owner_id` bigint(20) DEFAULT '0' COMMENT 'organization_id',
  `title` varchar(1024) DEFAULT NULL COMMENT 'title',
  `author` varchar(128) DEFAULT NULL COMMENT 'author',
  `cover_uri` varchar(1024) DEFAULT NULL COMMENT 'cover image uri',
  `content_type` varchar(32) DEFAULT NULL COMMENT 'object content type: link url、rich text',
  `content` longtext COMMENT 'content data, depends on value of content_type',
  `content_abstract` text COMMENT 'abstract of content data',
  `source_desc` varchar(128) DEFAULT NULL COMMENT 'where the news comes from',
  `source_url` varchar(256) DEFAULT NULL COMMENT 'the url of source',
  `phone` varchar(32) DEFAULT '0',
  `child_count` bigint(20) NOT NULL DEFAULT '0' COMMENT 'comment count',
  `forward_count` bigint(20) NOT NULL DEFAULT '0' COMMENT 'forward count',
  `like_count` bigint(20) NOT NULL DEFAULT '0' COMMENT 'like count',
  `view_count` bigint(20) NOT NULL DEFAULT '0' COMMENT 'view count',
  `publish_time` datetime DEFAULT NULL COMMENT 'the time when the news was created, now equals to create_time',
  `top_index` bigint(20) NOT NULL DEFAULT '0' COMMENT 'if has this value, go to first, order from big to small',
  `top_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'whether it is top',
  `status` tinyint(4) NOT NULL DEFAULT '2' COMMENT '0: inactive, 1: waitingForConfirmation, 2: active',
  `creator_uid` bigint(20) NOT NULL DEFAULT '0' COMMENT 'news creator uid',
  `create_time` datetime DEFAULT NULL COMMENT 'create time',
  `deleter_uid` bigint(20) NOT NULL DEFAULT '0' COMMENT 'deleter uid',
  `delete_time` datetime DEFAULT NULL COMMENT 'mark-deletion policy. historic data may be useful',
  `category_id` bigint(20) NOT NULL DEFAULT '0' COMMENT 'category id',
  `visible_type` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;