UPDATE eh_launch_pad_items  SET icon_uri = 'cs://1/image/aW1hZ2UvTVRvMFpqSTRObU0wTkRaaE1XRTVZemhoWVRKaU5UbG1ObVUwWldNek56TmxaZw' ,item_label ='五丰水果' WHERE item_label ='说粉' AND namespace_id = 999983;
UPDATE eh_launch_pad_items  SET icon_uri = 'cs://1/image/aW1hZ2UvTVRvM09UQXlOelZrWWpsbE1HSm1PVGN3WWpRMFl6SXpNamszTUdJellqSmpNQQ' ,item_label ='好色派沙拉'  WHERE item_label ='够咖啡' AND namespace_id = 999983;
UPDATE eh_launch_pad_items  SET icon_uri = 'cs://1/image/aW1hZ2UvTVRwaE9EUTFOR0prWlRjeFpEazFZVFl6WkdNMk5qQTJPV00zTURBNVl6YzVNQQ' ,item_label ='太平洋咖啡'  WHERE item_label ='Urban Table' AND namespace_id = 999983; 

SET @eh_launch_pad_items =(SELECT MAX(id) FROM eh_launch_pad_items );
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`) 
VALUES((@eh_launch_pad_items := @eh_launch_pad_items + 1),'999983','0','0','0','/home/Biz','BizList','Volgo Caffe','Volgo Caffe','cs://1/image/aW1hZ2UvTVRvd1pEZG1PRGhpTnpsaU1qZGlZekl6WkRkaVpXRmlNRFl5WVRObFpXSXpaQQ','1','1','14','{\"url\":\"https://biz.zuolin.com/zl-ec/rest/service/front/logon?hideNavigationBar=1&sourceUrl=https://biz.zuolin.com%2Fnar%2Fbiz%2Fweb%2Fapp%2Fuser%2Findex.html%23%2Fstore%2Fdetails%2F14882634540217997579%3F_k%3Dzlbiz#sign_suffix\"}','0','0','1','1','','0',NULL,NULL,NULL,'0','pm_admin','0',NULL,NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`) 
VALUES((@eh_launch_pad_items := @eh_launch_pad_items + 1),'999983','0','0','0','/home/Biz','BizList','Volgo Caffe','Volgo Caffe','cs://1/image/aW1hZ2UvTVRvd1pEZG1PRGhpTnpsaU1qZGlZekl6WkRkaVpXRmlNRFl5WVRObFpXSXpaQQ','1','1','14','{\"url\":\"https://biz.zuolin.com/zl-ec/rest/service/front/logon?hideNavigationBar=1&sourceUrl=https://biz.zuolin.com%2Fnar%2Fbiz%2Fweb%2Fapp%2Fuser%2Findex.html%23%2Fstore%2Fdetails%2F14882634540217997579%3F_k%3Dzlbiz#sign_suffix\"}','0','0','1','1','','0',NULL,NULL,NULL,'0','park_tourist','0',NULL,NULL);

-- fix 8047 add by xiongying20170328
update eh_launch_pad_items set icon_uri = 'cs://1/image/aW1hZ2UvTVRwa1l6bGxZV1k1TVdaak5qUTBNemN5Tm1VM1ptRXdOekUyTWpVMU1tSmtOZw' where id in (112848, 112878 ) and namespace_id = 999983;
update eh_launch_pad_items set action_data = '{"itemLocation":"/home/Coupons","layoutName":"CouponsLayout","title":"资源租赁"}' where id in (112848, 112878 ) and namespace_id = 999983;