-- bydeng,中天停车参数，未填写 todo
-- INSERT INTO `eh_parking_lots` (`id`, `owner_type`, `owner_id`, `name`, `vendor_name`, `vendor_lot_token`, `status`, `creator_uid`, `create_time`, `namespace_id`, `recharge_json`, `config_json`, `order_tag`, `order_code`) VALUES ('?', 'community', '?', '中天停车场', 'BEE_ZHONGTIAN', '', '2', '1', now(), 'ns?', NULL, '{\"tempfeeFlag\": 1, \"rateFlag\": 1, \"lockCarFlag\": 0, \"searchCarFlag\": 0, \"currentInfoType\": 0,\"identityCardFlag\":0}', '?', '0');
-- INSERT INTO `eh_configurations` (`name`, `value`, `description`, `namespace_id`, `display_name`) VALUES ('parking.beezhongtian.ploid', '', '中天停车停车场id', 0, NULL);
-- INSERT INTO `eh_configurations` (`name`, `value`, `description`, `namespace_id`, `display_name`) VALUES ('parking.beezhongtian.privatekey', '', '中天停车私钥', 0, NULL);
-- INSERT INTO `eh_configurations` (`name`, `value`, `description`, `namespace_id`, `display_name`) VALUES ('parking.beezhongtian.url', '', '中天停车系统地址', 0, NULL);
-- INSERT INTO `eh_configurations` (`name`, `value`, `description`, `namespace_id`, `display_name`) VALUES ('parking.beezhongtian.gcode', '', '中天停车系统gcode', 0, NULL);
-- INSERT INTO `eh_configurations` (`name`, `value`, `description`, `namespace_id`, `display_name`) VALUES ('parking.beezhongtian.comid', '', '中天停车物业id', 0, NULL);

-- bydeng,康利停车参数，未填写 todo
-- INSERT INTO `eh_parking_lots` (`id`, `owner_type`, `owner_id`, `name`, `vendor_name`, `vendor_lot_token`, `status`, `creator_uid`, `create_time`, `namespace_id`, `recharge_json`, `config_json`, `order_tag`, `order_code`) VALUES ('?', 'community', '?', '康利停车场', 'BEE_KANGLI', '', '2', '1', now(), 'ns?', NULL, '{\"tempfeeFlag\": 1, \"rateFlag\": 1, \"lockCarFlag\": 0, \"searchCarFlag\": 0, \"currentInfoType\": 0,\"identityCardFlag\":0}', '?', '0');
-- INSERT INTO `eh_configurations` (`name`, `value`, `description`, `namespace_id`, `display_name`) VALUES ('parking.beekangli.ploid', '', '康利停车停车场id', 0, NULL);
-- INSERT INTO `eh_configurations` (`name`, `value`, `description`, `namespace_id`, `display_name`) VALUES ('parking.beekangli.privatekey', '', '康利停车私钥', 0, NULL);
-- INSERT INTO `eh_configurations` (`name`, `value`, `description`, `namespace_id`, `display_name`) VALUES ('parking.beekangli.url', '', '康利停车系统地址', 0, NULL);
-- INSERT INTO `eh_configurations` (`name`, `value`, `description`, `namespace_id`, `display_name`) VALUES ('parking.beekangli.gcode', '', '康利停车系统gcode', 0, NULL);
-- INSERT INTO `eh_configurations` (`name`, `value`, `description`, `namespace_id`, `display_name`) VALUES ('parking.beekangli.comid', '', '康利停车物业id', 0, NULL);