SET FOREIGN_KEY_CHECKS = 0;
SET @namespace_id=999975;
SET @community_id = (SELECT MAX(id) FROM `eh_communities`) + 5; -- 需要取现网eh_communities的ID的最大值再加一定余量 
SET @organization_id = (SELECT MAX(id) FROM `eh_organizations`) + 5; 	-- 需要取eh_organizations的ID最大值并加一定余量，如果修改此值则其path也要改
SET @community_geopoint_id = (SELECT MAX(id) FROM `eh_community_geopoints`) + 5;  
SET @community_forum_id = (SELECT MAX(id) FROM `eh_forums`) + 5;   -- 取eh_forums的ID最大值再加一定余量
SET @org_group_id = (SELECT MAX(id) FROM `eh_groups`) + 5;  -- 需要取eh_groups的ID的最大值再加一定余量
SET @org_forum_id = @community_forum_id+2;   -- @community_forum_id+2
SET @feedback_forum_id = @community_forum_id+1;   -- @community_forum_id+1
SET @building_id = (SELECT MAX(id) FROM `eh_buildings`) + 5;   -- 取eh_buildings的ID最大值再加一定余量
SET @sheng_id = 18160;  -- 广东
SET @shi_id = 18161;  -- 深圳
SET @qu_id = 18162;    -- 福田


INSERT INTO `eh_communities` (`id`, `uuid`, `city_id`, `city_name`, `area_id`, `area_name`, `name`, `alias_name`, `address`, `zipcode`, `description`, `detail_description`, `apt_segment1`, `apt_segment2`, `apt_segment3`, `apt_seg1_sample`, `apt_seg2_sample`, `apt_seg3_sample`, `apt_count`, `creator_uid`, `operator_uid`, `status`, `create_time`, `delete_time`, `integral_tag1`, `integral_tag2`, `integral_tag3`, `integral_tag4`, `integral_tag5`, `string_tag1`, `string_tag2`, `string_tag3`, `string_tag4`, `string_tag5`, `community_type`, `default_forum_id`, `feedback_forum_id`, `update_time`, `namespace_id`)
	VALUES(@community_id, UUID(), @shi_id, '深圳市',  @qu_id, '福田区', '荣超大厦', '荣超大厦', '深圳市福田区金田路4036', NULL, '',NULL, NULL, NULL, NULL, NULL, NULL,NULL, 492, 1,NULL,'2',UTC_TIMESTAMP(), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,NULL,1, @community_forum_id, @feedback_forum_id, UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_community_geopoints`(`id`, `community_id`, `description`, `longitude`, `latitude`, `geohash`) 
	VALUES((@community_geopoint_id := @community_geopoint_id + 1), @community_id, '', 114.06359, 22.54839, 'ws1078f9fk91');
INSERT INTO `eh_organization_communities`(organization_id, community_id) 
	VALUES(@organization_id, @community_id);
INSERT INTO `eh_namespace_resources`(`id`, `namespace_id`, `resource_type`, `resource_id`, `create_time`) 
	VALUES((@namespace_resource_id := @namespace_resource_id + 1), @namespace_id, 'COMMUNITY', @community_id, UTC_TIMESTAMP());	

INSERT INTO `eh_buildings` (`id`, `community_id`, `name`, `alias_name`, `manager_uid`, `contact`, `address`, `area_size`, `longitude`, `latitude`, `geohash`, `description`, `poster_uri`, `status`, `operator_uid`, `operate_time`, `creator_uid`, `create_time`, `delete_time`, `integral_tag1`, `integral_tag2`, `integral_tag3`, `integral_tag4`, `integral_tag5`, `string_tag1`, `string_tag2`, `string_tag3`, `string_tag4`, `string_tag5`, `namespace_id`) 
	VALUES ((@building_id := @building_id + 1), @community_id, '荣超大厦', '荣超大厦', 0, NULL, '深圳市福田区金田路4036', NULL, 114.06359, 22.54839, 'ws1078f9fk91', '', '', '2', '1', UTC_TIMESTAMP(), 1, UTC_TIMESTAMP(), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @namespace_id);
	
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-M101','荣超大厦','M101','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-M102','荣超大厦','M102','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-M103','荣超大厦','M103','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-M105','荣超大厦','M105','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-M106','荣超大厦','M106','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-M108','荣超大厦','M108','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-M109','荣超大厦','M109','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-M110','荣超大厦','M110','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-M111','荣超大厦','M111','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-M201','荣超大厦','M201','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-M202','荣超大厦','M202','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-M203','荣超大厦','M203','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-M205','荣超大厦','M205','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-M206','荣超大厦','M206','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-M208','荣超大厦','M208','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-M209','荣超大厦','M209','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-101','荣超大厦','101','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-201','荣超大厦','201','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-202','荣超大厦','202','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-203','荣超大厦','203','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-205','荣超大厦','205','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-102','荣超大厦','102','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-206','荣超大厦','206','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-208','荣超大厦','208','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-209','荣超大厦','209','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-210','荣超大厦','210','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-301','荣超大厦','301','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-302','荣超大厦','302','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-303','荣超大厦','303','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-305','荣超大厦','305','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-306','荣超大厦','306','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-308','荣超大厦','308','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-309','荣超大厦','309','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-310','荣超大厦','310','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-311','荣超大厦','311','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-312','荣超大厦','312','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-313','荣超大厦','313','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-401','荣超大厦','401','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-402','荣超大厦','402','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-403','荣超大厦','403','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-405','荣超大厦','405','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-406','荣超大厦','406','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-408','荣超大厦','408','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-409','荣超大厦','409','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-412','荣超大厦','412','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-413','荣超大厦','413','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-410','荣超大厦','410','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-411','荣超大厦','411','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-501','荣超大厦','501','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-502','荣超大厦','502','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-503','荣超大厦','503','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-505','荣超大厦','505','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-506','荣超大厦','506','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-508','荣超大厦','508','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-509','荣超大厦','509','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-510','荣超大厦','510','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-511','荣超大厦','511','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-512','荣超大厦','512','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-513','荣超大厦','513','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-601','荣超大厦','601','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-602','荣超大厦','602','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-603','荣超大厦','603','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-605','荣超大厦','605','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-606','荣超大厦','606','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-608','荣超大厦','608','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-609','荣超大厦','609','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-610','荣超大厦','610','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-612','荣超大厦','612','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-701','荣超大厦','701','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-702','荣超大厦','702','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-703','荣超大厦','703','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-705','荣超大厦','705','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-706','荣超大厦','706','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-708','荣超大厦','708','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-709','荣超大厦','709','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-710','荣超大厦','710','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-711','荣超大厦','711','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-712','荣超大厦','712','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-713','荣超大厦','713','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-801','荣超大厦','801','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-803','荣超大厦','803','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-802','荣超大厦','802','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-805','荣超大厦','805','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-901','荣超大厦','901','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-902','荣超大厦','902','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-903','荣超大厦','903','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-905','荣超大厦','905','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1001','荣超大厦','1001','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1003','荣超大厦','1003','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1002A','荣超大厦','1002A','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1005A','荣超大厦','1005A','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1005B','荣超大厦','1005B','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1101','荣超大厦','1101','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1103','荣超大厦','1103','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1102','荣超大厦','1102','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1105','荣超大厦','1105','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1201','荣超大厦','1201','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1202','荣超大厦','1202','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1203','荣超大厦','1203','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1205','荣超大厦','1205','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1205','荣超大厦','1205','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1301','荣超大厦','1301','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1302','荣超大厦','1302','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1303','荣超大厦','1303','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1305','荣超大厦','1305','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1401','荣超大厦','1401','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1501','荣超大厦','1501','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1503','荣超大厦','1503','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1502','荣超大厦','1502','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1505','荣超大厦','1505','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1402','荣超大厦','1402','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1403','荣超大厦','1403','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1405','荣超大厦','1405','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1601','荣超大厦','1601','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1602','荣超大厦','1602','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1603','荣超大厦','1603','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1605','荣超大厦','1605','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1701','荣超大厦','1701','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1702','荣超大厦','1702','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1703','荣超大厦','1703','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1705','荣超大厦','1705','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1801','荣超大厦','1801','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1802','荣超大厦','1802','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1803','荣超大厦','1803','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1805','荣超大厦','1805','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1901','荣超大厦','1901','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1902','荣超大厦','1902','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1903','荣超大厦','1903','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-1905','荣超大厦','1905','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-2001','荣超大厦','2001','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-2002','荣超大厦','2002','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-2003','荣超大厦','2003','2','0',UTC_TIMESTAMP(), @namespace_id);
INSERT INTO `eh_addresses` (`id`, `uuid`, `community_id`, `city_id`, `city_name`, `area_id`, `area_name`, `address`, `building_name`, `apartment_name`, `status`, `operator_uid`, `create_time`, `namespace_id`)VALUES(239825274387255375,UUID(),@community_id, @shi_id, '深圳市',  @qu_id, '福田区' ,'荣超大厦-2005','荣超大厦','2005','2','0',UTC_TIMESTAMP(), @namespace_id);
