update eh_settle_requests set template_type = 'Settle';
update eh_service_alliance_requests set template_type = 'ServiceAlliance';
update eh_service_alliance_apartment_requests set template_type = 'Apartment';

SET @eh_request_templates = (SELECT MAX(id) FROM `eh_request_templates`);
INSERT INTO `eh_request_templates` (`id`, `template_type`, `name`, `button_title`, `email_flag`, `msg_flag`, `fields_json`, `status`, `creator_uid`, `create_time`, `delete_uid`, `delete_time`) 
    VALUES ((@eh_request_templates := @eh_request_templates + 1), 'Invest', '我要投资', '我有意向', '1', '1', '{"fields":[{"fieldName":"name","fieldDisplayName":"姓名","fieldType":"string","fieldContentType":"text","fieldDesc":"请输入您的姓名","requiredFlag":"1","dynamicFlag":"1"},{"fieldName":"mobile","fieldDisplayName":"手机号","fieldType":"number","fieldContentType":"text","fieldDesc":"请输入您的手机号","requiredFlag":"1","dynamicFlag":"1"},{"fieldName":"organizationName","fieldDisplayName":"公司","fieldType":"string","fieldContentType":"text","fieldDesc":"请输入您的公司","requiredFlag":"1","dynamicFlag":"1"},{"fieldName":"financingAmount","fieldDisplayName":"意向投资金额（万元）","fieldType":"decimal","fieldContentType":"text","fieldDesc":"","requiredFlag":"1"},{"fieldName":"industry","fieldDisplayName":"投资行业","fieldType":"string","fieldContentType":"text","fieldDesc":"","requiredFlag":"1"},{"fieldName":"investPeriod","fieldDisplayName":"投资年限","fieldType":"number","fieldContentType":"text","fieldDesc":"","requiredFlag":"1"},{"fieldName":"annualYield","fieldDisplayName":"预期年化收益（%）","fieldType":"decimal","fieldContentType":"text","fieldDesc":"","requiredFlag":"1"},{"fieldName":"remarks","fieldDisplayName":"备注","fieldType":"string","fieldContentType":"text","fieldDesc":"（选填）其他说明","requiredFlag":"0"}]}', '1', '1', UTC_TIMESTAMP(), '0', NULL);

INSERT INTO `eh_request_templates` (`id`, `template_type`, `name`, `button_title`, `email_flag`, `msg_flag`, `fields_json`, `status`, `creator_uid`, `create_time`, `delete_uid`, `delete_time`) 
    VALUES ((@eh_request_templates := @eh_request_templates + 1), 'ServiceAllianceFinancing', '我要融资', '我有意向', '1', '1', '{"fields":[{"fieldName":"name","fieldDisplayName":"姓名","fieldType":"string","fieldContentType":"text","fieldDesc":"请输入您的姓名","requiredFlag":"1","dynamicFlag":"1"},{"fieldName":"mobile","fieldDisplayName":"手机号","fieldType":"number","fieldContentType":"text","fieldDesc":"请输入您的手机号","requiredFlag":"1","dynamicFlag":"1"},{"fieldName":"organizationName","fieldDisplayName":"公司","fieldType":"string","fieldContentType":"text","fieldDesc":"请输入您的公司","requiredFlag":"1","dynamicFlag":"1"},{"fieldName":"financingAmount","fieldDisplayName":"意向融资金额（万元）","fieldType":"decimal","fieldContentType":"text","fieldDesc":"","requiredFlag":"1"},{"fieldName":"projectDesc","fieldDisplayName":"担保物","fieldType":"string","fieldContentType":"text","fieldDesc":"选填","requiredFlag":"0"},{"fieldName":"remarks","fieldDisplayName":"备注","fieldType":"string","fieldContentType":"text","fieldDesc":"（选填）其他说明","requiredFlag":"0"}]}', '1', '1', UTC_TIMESTAMP(), '0', NULL);
INSERT INTO `eh_request_templates` (`id`, `template_type`, `name`, `button_title`, `email_flag`, `msg_flag`, `fields_json`, `status`, `creator_uid`, `create_time`, `delete_uid`, `delete_time`) 
    VALUES ((@eh_request_templates := @eh_request_templates + 1), 'ServiceAllianceProjcet', '我有项目', '我有意向', '1', '1', '{"fields":[{"fieldName":"name","fieldDisplayName":"姓名","fieldType":"string","fieldContentType":"text","fieldDesc":"请输入您的姓名","requiredFlag":"1","dynamicFlag":"1"},{"fieldName":"mobile","fieldDisplayName":"手机号","fieldType":"number","fieldContentType":"text","fieldDesc":"请输入您的手机号","requiredFlag":"1","dynamicFlag":"1"},{"fieldName":"organizationName","fieldDisplayName":"公司","fieldType":"string","fieldContentType":"text","fieldDesc":"请输入您的公司","requiredFlag":"1","dynamicFlag":"1"},{"fieldName":"projectDesc","fieldDisplayName":"项目名称","fieldType":"string","fieldContentType":"text","fieldDesc":"","requiredFlag":"1"},{"fieldName":"transferShares","fieldDisplayName":"意向出让股份比例（%）","fieldType":"number","fieldContentType":"text","fieldDesc":"","requiredFlag":"1"},{"fieldName":"financingAmount","fieldDisplayName":"融资金额（万元）","fieldType":"decimal","fieldContentType":"text","fieldDesc":"","requiredFlag":"1"},{"fieldName":"remarks","fieldDisplayName":"备注","fieldType":"string","fieldContentType":"text","fieldDesc":"（选填）其他说明","requiredFlag":"0"}]}', '1', '1', UTC_TIMESTAMP(), '0', NULL);
INSERT INTO `eh_request_templates` (`id`, `template_type`, `name`, `button_title`, `email_flag`, `msg_flag`, `fields_json`, `status`, `creator_uid`, `create_time`, `delete_uid`, `delete_time`) 
    VALUES ((@eh_request_templates := @eh_request_templates + 1), 'ServiceAllianceTech', '科技成果', '我有意向', '1', '1', '{"fields":[{"fieldName":"name","fieldDisplayName":"姓名","fieldType":"string","fieldContentType":"text","fieldDesc":"请输入您的姓名","requiredFlag":"1","dynamicFlag":"1"},{"fieldName":"mobile","fieldDisplayName":"手机号","fieldType":"number","fieldContentType":"text","fieldDesc":"请输入您的手机号","requiredFlag":"1","dynamicFlag":"1"},{"fieldName":"organizationName","fieldDisplayName":"公司","fieldType":"string","fieldContentType":"text","fieldDesc":"请输入您的公司","requiredFlag":"1","dynamicFlag":"1"},{"fieldName":"financingAmount","fieldDisplayName":"拟投资金额（百万元）","fieldType":"decimal","fieldContentType":"text","fieldDesc":"","requiredFlag":"1"},{"fieldName":"remarks","fieldDisplayName":"备注","fieldType":"string","fieldContentType":"text","fieldDesc":"（选填）其他说明","requiredFlag":"0"}]}', '1', '1', UTC_TIMESTAMP(), '0', NULL);
    
INSERT INTO `eh_request_templates` (`id`, `template_type`, `name`, `button_title`, `email_flag`, `msg_flag`, `fields_json`, `status`, `creator_uid`, `create_time`, `delete_uid`, `delete_time`) 
    VALUES ((@eh_request_templates := @eh_request_templates + 1), 'SettleIncubator', '星空孵化器', '我有意向', '1', '1', '{"fields":[{"fieldName":"name","fieldDisplayName":"姓名","fieldType":"string","fieldContentType":"text","fieldDesc":"请输入您的姓名","requiredFlag":"1","dynamicFlag":"1"},{"fieldName":"mobile","fieldDisplayName":"手机号","fieldType":"number","fieldContentType":"text","fieldDesc":"请输入您的手机号","requiredFlag":"1","dynamicFlag":"1"},{"fieldName":"stringTag1","fieldDisplayName":"项目名称","fieldType":"string","fieldContentType":"text","fieldDesc":"","requiredFlag":"1"},{"fieldName":"integralTag1","fieldDisplayName":"意向工位数","fieldType":"number","fieldContentType":"text","fieldDesc":"","requiredFlag":"1"},{"fieldName":"remarks","fieldDisplayName":"备注","fieldType":"string","fieldContentType":"text","fieldDesc":"（选填）其他说明","requiredFlag":"0"}]}', '1', '1', UTC_TIMESTAMP(), '0', NULL);
INSERT INTO `eh_request_templates` (`id`, `template_type`, `name`, `button_title`, `email_flag`, `msg_flag`, `fields_json`, `status`, `creator_uid`, `create_time`, `delete_uid`, `delete_time`) 
    VALUES ((@eh_request_templates := @eh_request_templates + 1), 'SettleResearchPlat', '研发平台', '我有意向', '1', '1', '{"fields":[{"fieldName":"name","fieldDisplayName":"姓名","fieldType":"string","fieldContentType":"text","fieldDesc":"请输入您的姓名","requiredFlag":"1","dynamicFlag":"1"},{"fieldName":"mobile","fieldDisplayName":"手机号","fieldType":"number","fieldContentType":"text","fieldDesc":"请输入您的手机号","requiredFlag":"1","dynamicFlag":"1"},{"fieldName":"organizationName","fieldDisplayName":"公司","fieldType":"string","fieldContentType":"text","fieldDesc":"请输入您的公司","requiredFlag":"1","dynamicFlag":"1"},{"fieldName":"stringTag1","fieldDisplayName":"项目名称","fieldType":"string","fieldContentType":"text","fieldDesc":"","requiredFlag":"1"},{"fieldName":"remarks","fieldDisplayName":"备注","fieldType":"string","fieldContentType":"text","fieldDesc":"（选填）其他说明","requiredFlag":"0"}]}', '1', '1', UTC_TIMESTAMP(), '0', NULL);
INSERT INTO `eh_request_templates` (`id`, `template_type`, `name`, `button_title`, `email_flag`, `msg_flag`, `fields_json`, `status`, `creator_uid`, `create_time`, `delete_uid`, `delete_time`) 
    VALUES ((@eh_request_templates := @eh_request_templates + 1), 'SettleProfessionalService', '专业服务', '我有意向', '1', '1', '{"fields":[{"fieldName":"name","fieldDisplayName":"姓名","fieldType":"string","fieldContentType":"text","fieldDesc":"请输入您的姓名","requiredFlag":"1","dynamicFlag":"1"},{"fieldName":"mobile","fieldDisplayName":"手机号","fieldType":"number","fieldContentType":"text","fieldDesc":"请输入您的手机号","requiredFlag":"1","dynamicFlag":"1"},{"fieldName":"organizationName","fieldDisplayName":"公司","fieldType":"string","fieldContentType":"text","fieldDesc":"请输入您的公司","requiredFlag":"1","dynamicFlag":"1"},{"fieldName":"stringTag1","fieldDisplayName":"企业需求","fieldType":"string","fieldContentType":"text","fieldDesc":"（必填）请输入您的需求","requiredFlag":"1"},{"fieldName":"remarks","fieldDisplayName":"备注","fieldType":"string","fieldContentType":"text","fieldDesc":"（选填）其他说明","requiredFlag":"0"}]}', '1', '1', UTC_TIMESTAMP(), '0', NULL);
INSERT INTO `eh_request_templates` (`id`, `template_type`, `name`, `button_title`, `email_flag`, `msg_flag`, `fields_json`, `status`, `creator_uid`, `create_time`, `delete_uid`, `delete_time`) 
    VALUES ((@eh_request_templates := @eh_request_templates + 1), 'SettleConsultationCooperation', '载物微咨询和国际合作', '我有意向', '1', '1', '{"fields":[{"fieldName":"name","fieldDisplayName":"姓名","fieldType":"string","fieldContentType":"text","fieldDesc":"请输入您的姓名","requiredFlag":"1","dynamicFlag":"1"},{"fieldName":"mobile","fieldDisplayName":"手机号","fieldType":"number","fieldContentType":"text","fieldDesc":"请输入您的手机号","requiredFlag":"1","dynamicFlag":"1"},{"fieldName":"organizationName","fieldDisplayName":"公司","fieldType":"string","fieldContentType":"text","fieldDesc":"请输入您的公司","requiredFlag":"1","dynamicFlag":"1"},{"fieldName":"remarks","fieldDisplayName":"备注","fieldType":"string","fieldContentType":"text","fieldDesc":"（选填）其他说明","requiredFlag":"0"}]}', '1', '1', UTC_TIMESTAMP(), '0', NULL);
INSERT INTO `eh_request_templates` (`id`, `template_type`, `name`, `button_title`, `email_flag`, `msg_flag`, `fields_json`, `status`, `creator_uid`, `create_time`, `delete_uid`, `delete_time`) 
    VALUES ((@eh_request_templates := @eh_request_templates + 1), 'SettleFundSupport', '资金扶持', '我有意向', '1', '1', '{"fields":[{"fieldName":"name","fieldDisplayName":"姓名","fieldType":"string","fieldContentType":"text","fieldDesc":"请输入您的姓名","requiredFlag":"1","dynamicFlag":"1"},{"fieldName":"mobile","fieldDisplayName":"手机号","fieldType":"number","fieldContentType":"text","fieldDesc":"请输入您的手机号","requiredFlag":"1","dynamicFlag":"1"},{"fieldName":"organizationName","fieldDisplayName":"公司","fieldType":"string","fieldContentType":"text","fieldDesc":"请输入您的公司","requiredFlag":"1","dynamicFlag":"1"},{"fieldName":"remarks","fieldDisplayName":"备注","fieldType":"string","fieldContentType":"text","fieldDesc":"（选填）其他说明","requiredFlag":"0"}]}', '1', '1', UTC_TIMESTAMP(), '0', NULL);

    
update eh_service_alliances set integral_tag1 = '1' where string_tag2 in(select template_type from eh_request_templates);