/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhAppPromotionsDao extends org.jooq.impl.DAOImpl<com.everhomes.server.schema.tables.records.EhAppPromotionsRecord, com.everhomes.server.schema.tables.pojos.EhAppPromotions, java.lang.Integer> {

	/**
	 * Create a new EhAppPromotionsDao without any configuration
	 */
	public EhAppPromotionsDao() {
		super(com.everhomes.server.schema.tables.EhAppPromotions.EH_APP_PROMOTIONS, com.everhomes.server.schema.tables.pojos.EhAppPromotions.class);
	}

	/**
	 * Create a new EhAppPromotionsDao with an attached configuration
	 */
	public EhAppPromotionsDao(org.jooq.Configuration configuration) {
		super(com.everhomes.server.schema.tables.EhAppPromotions.EH_APP_PROMOTIONS, com.everhomes.server.schema.tables.pojos.EhAppPromotions.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(com.everhomes.server.schema.tables.pojos.EhAppPromotions object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhAppPromotions> fetchById(java.lang.Integer... values) {
		return fetch(com.everhomes.server.schema.tables.EhAppPromotions.EH_APP_PROMOTIONS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.everhomes.server.schema.tables.pojos.EhAppPromotions fetchOneById(java.lang.Integer value) {
		return fetchOne(com.everhomes.server.schema.tables.EhAppPromotions.EH_APP_PROMOTIONS.ID, value);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhAppPromotions> fetchByName(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhAppPromotions.EH_APP_PROMOTIONS.NAME, values);
	}

	/**
	 * Fetch records that have <code>channel IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhAppPromotions> fetchByChannel(java.lang.Integer... values) {
		return fetch(com.everhomes.server.schema.tables.EhAppPromotions.EH_APP_PROMOTIONS.CHANNEL, values);
	}

	/**
	 * Fetch records that have <code>version IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhAppPromotions> fetchByVersion(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhAppPromotions.EH_APP_PROMOTIONS.VERSION, values);
	}

	/**
	 * Fetch records that have <code>path IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhAppPromotions> fetchByPath(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhAppPromotions.EH_APP_PROMOTIONS.PATH, values);
	}

	/**
	 * Fetch records that have <code>file_name IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhAppPromotions> fetchByFileName(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhAppPromotions.EH_APP_PROMOTIONS.FILE_NAME, values);
	}

	/**
	 * Fetch records that have <code>link IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhAppPromotions> fetchByLink(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhAppPromotions.EH_APP_PROMOTIONS.LINK, values);
	}

	/**
	 * Fetch records that have <code>download_count IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhAppPromotions> fetchByDownloadCount(java.lang.Integer... values) {
		return fetch(com.everhomes.server.schema.tables.EhAppPromotions.EH_APP_PROMOTIONS.DOWNLOAD_COUNT, values);
	}

	/**
	 * Fetch records that have <code>register_count IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhAppPromotions> fetchByRegisterCount(java.lang.Integer... values) {
		return fetch(com.everhomes.server.schema.tables.EhAppPromotions.EH_APP_PROMOTIONS.REGISTER_COUNT, values);
	}

	/**
	 * Fetch records that have <code>create_time IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhAppPromotions> fetchByCreateTime(java.sql.Timestamp... values) {
		return fetch(com.everhomes.server.schema.tables.EhAppPromotions.EH_APP_PROMOTIONS.CREATE_TIME, values);
	}
}
