/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhScopedConfigurationsDao extends org.jooq.impl.DAOImpl<com.everhomes.server.schema.tables.records.EhScopedConfigurationsRecord, com.everhomes.server.schema.tables.pojos.EhScopedConfigurations, java.lang.Integer> {

	/**
	 * Create a new EhScopedConfigurationsDao without any configuration
	 */
	public EhScopedConfigurationsDao() {
		super(com.everhomes.server.schema.tables.EhScopedConfigurations.EH_SCOPED_CONFIGURATIONS, com.everhomes.server.schema.tables.pojos.EhScopedConfigurations.class);
	}

	/**
	 * Create a new EhScopedConfigurationsDao with an attached configuration
	 */
	public EhScopedConfigurationsDao(org.jooq.Configuration configuration) {
		super(com.everhomes.server.schema.tables.EhScopedConfigurations.EH_SCOPED_CONFIGURATIONS, com.everhomes.server.schema.tables.pojos.EhScopedConfigurations.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(com.everhomes.server.schema.tables.pojos.EhScopedConfigurations object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhScopedConfigurations> fetchById(java.lang.Integer... values) {
		return fetch(com.everhomes.server.schema.tables.EhScopedConfigurations.EH_SCOPED_CONFIGURATIONS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.everhomes.server.schema.tables.pojos.EhScopedConfigurations fetchOneById(java.lang.Integer value) {
		return fetchOne(com.everhomes.server.schema.tables.EhScopedConfigurations.EH_SCOPED_CONFIGURATIONS.ID, value);
	}

	/**
	 * Fetch records that have <code>namespace_id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhScopedConfigurations> fetchByNamespaceId(java.lang.Integer... values) {
		return fetch(com.everhomes.server.schema.tables.EhScopedConfigurations.EH_SCOPED_CONFIGURATIONS.NAMESPACE_ID, values);
	}

	/**
	 * Fetch records that have <code>app_id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhScopedConfigurations> fetchByAppId(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhScopedConfigurations.EH_SCOPED_CONFIGURATIONS.APP_ID, values);
	}

	/**
	 * Fetch records that have <code>scope_type IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhScopedConfigurations> fetchByScopeType(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhScopedConfigurations.EH_SCOPED_CONFIGURATIONS.SCOPE_TYPE, values);
	}

	/**
	 * Fetch records that have <code>scope_id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhScopedConfigurations> fetchByScopeId(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhScopedConfigurations.EH_SCOPED_CONFIGURATIONS.SCOPE_ID, values);
	}

	/**
	 * Fetch records that have <code>item_name IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhScopedConfigurations> fetchByItemName(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhScopedConfigurations.EH_SCOPED_CONFIGURATIONS.ITEM_NAME, values);
	}

	/**
	 * Fetch records that have <code>item_kind IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhScopedConfigurations> fetchByItemKind(java.lang.Byte... values) {
		return fetch(com.everhomes.server.schema.tables.EhScopedConfigurations.EH_SCOPED_CONFIGURATIONS.ITEM_KIND, values);
	}

	/**
	 * Fetch records that have <code>item_value IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhScopedConfigurations> fetchByItemValue(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhScopedConfigurations.EH_SCOPED_CONFIGURATIONS.ITEM_VALUE, values);
	}

	/**
	 * Fetch records that have <code>target_type IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhScopedConfigurations> fetchByTargetType(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhScopedConfigurations.EH_SCOPED_CONFIGURATIONS.TARGET_TYPE, values);
	}

	/**
	 * Fetch records that have <code>target_id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhScopedConfigurations> fetchByTargetId(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhScopedConfigurations.EH_SCOPED_CONFIGURATIONS.TARGET_ID, values);
	}

	/**
	 * Fetch records that have <code>apply_policy IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhScopedConfigurations> fetchByApplyPolicy(java.lang.Byte... values) {
		return fetch(com.everhomes.server.schema.tables.EhScopedConfigurations.EH_SCOPED_CONFIGURATIONS.APPLY_POLICY, values);
	}

	/**
	 * Fetch records that have <code>integral_tag1 IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhScopedConfigurations> fetchByIntegralTag1(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhScopedConfigurations.EH_SCOPED_CONFIGURATIONS.INTEGRAL_TAG1, values);
	}

	/**
	 * Fetch records that have <code>integral_tag2 IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhScopedConfigurations> fetchByIntegralTag2(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhScopedConfigurations.EH_SCOPED_CONFIGURATIONS.INTEGRAL_TAG2, values);
	}

	/**
	 * Fetch records that have <code>integral_tag3 IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhScopedConfigurations> fetchByIntegralTag3(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhScopedConfigurations.EH_SCOPED_CONFIGURATIONS.INTEGRAL_TAG3, values);
	}

	/**
	 * Fetch records that have <code>integral_tag4 IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhScopedConfigurations> fetchByIntegralTag4(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhScopedConfigurations.EH_SCOPED_CONFIGURATIONS.INTEGRAL_TAG4, values);
	}

	/**
	 * Fetch records that have <code>integral_tag5 IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhScopedConfigurations> fetchByIntegralTag5(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhScopedConfigurations.EH_SCOPED_CONFIGURATIONS.INTEGRAL_TAG5, values);
	}

	/**
	 * Fetch records that have <code>string_tag1 IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhScopedConfigurations> fetchByStringTag1(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhScopedConfigurations.EH_SCOPED_CONFIGURATIONS.STRING_TAG1, values);
	}

	/**
	 * Fetch records that have <code>string_tag2 IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhScopedConfigurations> fetchByStringTag2(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhScopedConfigurations.EH_SCOPED_CONFIGURATIONS.STRING_TAG2, values);
	}

	/**
	 * Fetch records that have <code>string_tag3 IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhScopedConfigurations> fetchByStringTag3(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhScopedConfigurations.EH_SCOPED_CONFIGURATIONS.STRING_TAG3, values);
	}

	/**
	 * Fetch records that have <code>string_tag4 IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhScopedConfigurations> fetchByStringTag4(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhScopedConfigurations.EH_SCOPED_CONFIGURATIONS.STRING_TAG4, values);
	}

	/**
	 * Fetch records that have <code>string_tag5 IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhScopedConfigurations> fetchByStringTag5(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhScopedConfigurations.EH_SCOPED_CONFIGURATIONS.STRING_TAG5, values);
	}
}
