/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhUserInvitationsRecord extends org.jooq.impl.UpdatableRecordImpl<com.everhomes.server.schema.tables.records.EhUserInvitationsRecord> implements org.jooq.Record11<java.lang.Long, java.lang.Long, java.lang.String, java.lang.Byte, java.sql.Timestamp, java.lang.String, java.lang.Long, java.lang.Integer, java.lang.Integer, java.lang.Byte, java.sql.Timestamp> {

	private static final long serialVersionUID = 1204568867;

	/**
	 * Setter for <code>ehcore.eh_user_invitations.id</code>. id of the record
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_invitations.id</code>. id of the record
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>ehcore.eh_user_invitations.owner_uid</code>. owner user id
	 */
	public void setOwnerUid(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_invitations.owner_uid</code>. owner user id
	 */
	public java.lang.Long getOwnerUid() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>ehcore.eh_user_invitations.invite_code</code>.
	 */
	public void setInviteCode(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_invitations.invite_code</code>.
	 */
	public java.lang.String getInviteCode() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>ehcore.eh_user_invitations.invite_type</code>. 1: SMS, 2: wechat, 3, wechat friend circle, 4: weibo, 5: phone contact
	 */
	public void setInviteType(java.lang.Byte value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_invitations.invite_type</code>. 1: SMS, 2: wechat, 3, wechat friend circle, 4: weibo, 5: phone contact
	 */
	public java.lang.Byte getInviteType() {
		return (java.lang.Byte) getValue(3);
	}

	/**
	 * Setter for <code>ehcore.eh_user_invitations.expiration</code>. expiration time of the invitation
	 */
	public void setExpiration(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_invitations.expiration</code>. expiration time of the invitation
	 */
	public java.sql.Timestamp getExpiration() {
		return (java.sql.Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>ehcore.eh_user_invitations.target_entity_type</code>.
	 */
	public void setTargetEntityType(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_invitations.target_entity_type</code>.
	 */
	public java.lang.String getTargetEntityType() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>ehcore.eh_user_invitations.target_entity_id</code>.
	 */
	public void setTargetEntityId(java.lang.Long value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_invitations.target_entity_id</code>.
	 */
	public java.lang.Long getTargetEntityId() {
		return (java.lang.Long) getValue(6);
	}

	/**
	 * Setter for <code>ehcore.eh_user_invitations.max_invite_count</code>.
	 */
	public void setMaxInviteCount(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_invitations.max_invite_count</code>.
	 */
	public java.lang.Integer getMaxInviteCount() {
		return (java.lang.Integer) getValue(7);
	}

	/**
	 * Setter for <code>ehcore.eh_user_invitations.current_invite_count</code>.
	 */
	public void setCurrentInviteCount(java.lang.Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_invitations.current_invite_count</code>.
	 */
	public java.lang.Integer getCurrentInviteCount() {
		return (java.lang.Integer) getValue(8);
	}

	/**
	 * Setter for <code>ehcore.eh_user_invitations.status</code>. 0: inactive, 1: active
	 */
	public void setStatus(java.lang.Byte value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_invitations.status</code>. 0: inactive, 1: active
	 */
	public java.lang.Byte getStatus() {
		return (java.lang.Byte) getValue(9);
	}

	/**
	 * Setter for <code>ehcore.eh_user_invitations.create_time</code>. remove-deletion policy, user directly managed data
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_invitations.create_time</code>. remove-deletion policy, user directly managed data
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.lang.Long, java.lang.Long, java.lang.String, java.lang.Byte, java.sql.Timestamp, java.lang.String, java.lang.Long, java.lang.Integer, java.lang.Integer, java.lang.Byte, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.lang.Long, java.lang.Long, java.lang.String, java.lang.Byte, java.sql.Timestamp, java.lang.String, java.lang.Long, java.lang.Integer, java.lang.Integer, java.lang.Byte, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.everhomes.server.schema.tables.EhUserInvitations.EH_USER_INVITATIONS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.everhomes.server.schema.tables.EhUserInvitations.EH_USER_INVITATIONS.OWNER_UID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.everhomes.server.schema.tables.EhUserInvitations.EH_USER_INVITATIONS.INVITE_CODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field4() {
		return com.everhomes.server.schema.tables.EhUserInvitations.EH_USER_INVITATIONS.INVITE_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return com.everhomes.server.schema.tables.EhUserInvitations.EH_USER_INVITATIONS.EXPIRATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.everhomes.server.schema.tables.EhUserInvitations.EH_USER_INVITATIONS.TARGET_ENTITY_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field7() {
		return com.everhomes.server.schema.tables.EhUserInvitations.EH_USER_INVITATIONS.TARGET_ENTITY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field8() {
		return com.everhomes.server.schema.tables.EhUserInvitations.EH_USER_INVITATIONS.MAX_INVITE_COUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field9() {
		return com.everhomes.server.schema.tables.EhUserInvitations.EH_USER_INVITATIONS.CURRENT_INVITE_COUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field10() {
		return com.everhomes.server.schema.tables.EhUserInvitations.EH_USER_INVITATIONS.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field11() {
		return com.everhomes.server.schema.tables.EhUserInvitations.EH_USER_INVITATIONS.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getOwnerUid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getInviteCode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value4() {
		return getInviteType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getExpiration();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getTargetEntityType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value7() {
		return getTargetEntityId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value8() {
		return getMaxInviteCount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value9() {
		return getCurrentInviteCount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value10() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value11() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserInvitationsRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserInvitationsRecord value2(java.lang.Long value) {
		setOwnerUid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserInvitationsRecord value3(java.lang.String value) {
		setInviteCode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserInvitationsRecord value4(java.lang.Byte value) {
		setInviteType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserInvitationsRecord value5(java.sql.Timestamp value) {
		setExpiration(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserInvitationsRecord value6(java.lang.String value) {
		setTargetEntityType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserInvitationsRecord value7(java.lang.Long value) {
		setTargetEntityId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserInvitationsRecord value8(java.lang.Integer value) {
		setMaxInviteCount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserInvitationsRecord value9(java.lang.Integer value) {
		setCurrentInviteCount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserInvitationsRecord value10(java.lang.Byte value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserInvitationsRecord value11(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserInvitationsRecord values(java.lang.Long value1, java.lang.Long value2, java.lang.String value3, java.lang.Byte value4, java.sql.Timestamp value5, java.lang.String value6, java.lang.Long value7, java.lang.Integer value8, java.lang.Integer value9, java.lang.Byte value10, java.sql.Timestamp value11) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EhUserInvitationsRecord
	 */
	public EhUserInvitationsRecord() {
		super(com.everhomes.server.schema.tables.EhUserInvitations.EH_USER_INVITATIONS);
	}

	/**
	 * Create a detached, initialised EhUserInvitationsRecord
	 */
	public EhUserInvitationsRecord(java.lang.Long id, java.lang.Long ownerUid, java.lang.String inviteCode, java.lang.Byte inviteType, java.sql.Timestamp expiration, java.lang.String targetEntityType, java.lang.Long targetEntityId, java.lang.Integer maxInviteCount, java.lang.Integer currentInviteCount, java.lang.Byte status, java.sql.Timestamp createTime) {
		super(com.everhomes.server.schema.tables.EhUserInvitations.EH_USER_INVITATIONS);

		setValue(0, id);
		setValue(1, ownerUid);
		setValue(2, inviteCode);
		setValue(3, inviteType);
		setValue(4, expiration);
		setValue(5, targetEntityType);
		setValue(6, targetEntityId);
		setValue(7, maxInviteCount);
		setValue(8, currentInviteCount);
		setValue(9, status);
		setValue(10, createTime);
	}
}
