/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhAuthorizationsRecord extends org.jooq.impl.UpdatableRecordImpl<com.everhomes.server.schema.tables.records.EhAuthorizationsRecord> implements org.jooq.Record16<java.lang.Long, java.lang.Integer, java.lang.String, java.lang.Long, java.lang.String, java.lang.String, java.lang.Long, java.lang.String, java.lang.Long, java.lang.String, java.lang.Byte, java.lang.String, java.lang.Long, java.sql.Timestamp, java.sql.Timestamp, java.lang.Long> {

	private static final long serialVersionUID = 1672297321;

	/**
	 * Setter for <code>ehcore.eh_authorizations.id</code>. id of the record
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehcore.eh_authorizations.id</code>. id of the record
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>ehcore.eh_authorizations.namespace_id</code>.
	 */
	public void setNamespaceId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehcore.eh_authorizations.namespace_id</code>.
	 */
	public java.lang.Integer getNamespaceId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>ehcore.eh_authorizations.target_type</code>. EhOrganizations, EhUsers
	 */
	public void setTargetType(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ehcore.eh_authorizations.target_type</code>. EhOrganizations, EhUsers
	 */
	public java.lang.String getTargetType() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>ehcore.eh_authorizations.target_id</code>.
	 */
	public void setTargetId(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ehcore.eh_authorizations.target_id</code>.
	 */
	public java.lang.Long getTargetId() {
		return (java.lang.Long) getValue(3);
	}

	/**
	 * Setter for <code>ehcore.eh_authorizations.target_name</code>.
	 */
	public void setTargetName(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ehcore.eh_authorizations.target_name</code>.
	 */
	public java.lang.String getTargetName() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>ehcore.eh_authorizations.owner_type</code>. EhOrganizations, EhCommunities
	 */
	public void setOwnerType(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ehcore.eh_authorizations.owner_type</code>. EhOrganizations, EhCommunities
	 */
	public java.lang.String getOwnerType() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>ehcore.eh_authorizations.owner_id</code>.
	 */
	public void setOwnerId(java.lang.Long value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ehcore.eh_authorizations.owner_id</code>.
	 */
	public java.lang.Long getOwnerId() {
		return (java.lang.Long) getValue(6);
	}

	/**
	 * Setter for <code>ehcore.eh_authorizations.auth_type</code>. EhServiceModules, EhRoles
	 */
	public void setAuthType(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ehcore.eh_authorizations.auth_type</code>. EhServiceModules, EhRoles
	 */
	public java.lang.String getAuthType() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>ehcore.eh_authorizations.auth_id</code>.
	 */
	public void setAuthId(java.lang.Long value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ehcore.eh_authorizations.auth_id</code>.
	 */
	public java.lang.Long getAuthId() {
		return (java.lang.Long) getValue(8);
	}

	/**
	 * Setter for <code>ehcore.eh_authorizations.identity_type</code>. manage, ordinary
	 */
	public void setIdentityType(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>ehcore.eh_authorizations.identity_type</code>. manage, ordinary
	 */
	public java.lang.String getIdentityType() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>ehcore.eh_authorizations.all_flag</code>. 0 not all, 1 all
	 */
	public void setAllFlag(java.lang.Byte value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>ehcore.eh_authorizations.all_flag</code>. 0 not all, 1 all
	 */
	public java.lang.Byte getAllFlag() {
		return (java.lang.Byte) getValue(10);
	}

	/**
	 * Setter for <code>ehcore.eh_authorizations.scope</code>.
	 */
	public void setScope(java.lang.String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>ehcore.eh_authorizations.scope</code>.
	 */
	public java.lang.String getScope() {
		return (java.lang.String) getValue(11);
	}

	/**
	 * Setter for <code>ehcore.eh_authorizations.creator_uid</code>.
	 */
	public void setCreatorUid(java.lang.Long value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>ehcore.eh_authorizations.creator_uid</code>.
	 */
	public java.lang.Long getCreatorUid() {
		return (java.lang.Long) getValue(12);
	}

	/**
	 * Setter for <code>ehcore.eh_authorizations.create_time</code>.
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>ehcore.eh_authorizations.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(13);
	}

	/**
	 * Setter for <code>ehcore.eh_authorizations.update_time</code>.
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>ehcore.eh_authorizations.update_time</code>.
	 */
	public java.sql.Timestamp getUpdateTime() {
		return (java.sql.Timestamp) getValue(14);
	}

	/**
	 * Setter for <code>ehcore.eh_authorizations.operator_uid</code>.
	 */
	public void setOperatorUid(java.lang.Long value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>ehcore.eh_authorizations.operator_uid</code>.
	 */
	public java.lang.Long getOperatorUid() {
		return (java.lang.Long) getValue(15);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record16 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row16<java.lang.Long, java.lang.Integer, java.lang.String, java.lang.Long, java.lang.String, java.lang.String, java.lang.Long, java.lang.String, java.lang.Long, java.lang.String, java.lang.Byte, java.lang.String, java.lang.Long, java.sql.Timestamp, java.sql.Timestamp, java.lang.Long> fieldsRow() {
		return (org.jooq.Row16) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row16<java.lang.Long, java.lang.Integer, java.lang.String, java.lang.Long, java.lang.String, java.lang.String, java.lang.Long, java.lang.String, java.lang.Long, java.lang.String, java.lang.Byte, java.lang.String, java.lang.Long, java.sql.Timestamp, java.sql.Timestamp, java.lang.Long> valuesRow() {
		return (org.jooq.Row16) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.everhomes.server.schema.tables.EhAuthorizations.EH_AUTHORIZATIONS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.everhomes.server.schema.tables.EhAuthorizations.EH_AUTHORIZATIONS.NAMESPACE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.everhomes.server.schema.tables.EhAuthorizations.EH_AUTHORIZATIONS.TARGET_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return com.everhomes.server.schema.tables.EhAuthorizations.EH_AUTHORIZATIONS.TARGET_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.everhomes.server.schema.tables.EhAuthorizations.EH_AUTHORIZATIONS.TARGET_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.everhomes.server.schema.tables.EhAuthorizations.EH_AUTHORIZATIONS.OWNER_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field7() {
		return com.everhomes.server.schema.tables.EhAuthorizations.EH_AUTHORIZATIONS.OWNER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.everhomes.server.schema.tables.EhAuthorizations.EH_AUTHORIZATIONS.AUTH_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field9() {
		return com.everhomes.server.schema.tables.EhAuthorizations.EH_AUTHORIZATIONS.AUTH_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return com.everhomes.server.schema.tables.EhAuthorizations.EH_AUTHORIZATIONS.IDENTITY_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field11() {
		return com.everhomes.server.schema.tables.EhAuthorizations.EH_AUTHORIZATIONS.ALL_FLAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field12() {
		return com.everhomes.server.schema.tables.EhAuthorizations.EH_AUTHORIZATIONS.SCOPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field13() {
		return com.everhomes.server.schema.tables.EhAuthorizations.EH_AUTHORIZATIONS.CREATOR_UID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field14() {
		return com.everhomes.server.schema.tables.EhAuthorizations.EH_AUTHORIZATIONS.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field15() {
		return com.everhomes.server.schema.tables.EhAuthorizations.EH_AUTHORIZATIONS.UPDATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field16() {
		return com.everhomes.server.schema.tables.EhAuthorizations.EH_AUTHORIZATIONS.OPERATOR_UID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getNamespaceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getTargetType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getTargetId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getTargetName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getOwnerType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value7() {
		return getOwnerId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getAuthType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value9() {
		return getAuthId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getIdentityType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value11() {
		return getAllFlag();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value12() {
		return getScope();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value13() {
		return getCreatorUid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value14() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value15() {
		return getUpdateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value16() {
		return getOperatorUid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhAuthorizationsRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhAuthorizationsRecord value2(java.lang.Integer value) {
		setNamespaceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhAuthorizationsRecord value3(java.lang.String value) {
		setTargetType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhAuthorizationsRecord value4(java.lang.Long value) {
		setTargetId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhAuthorizationsRecord value5(java.lang.String value) {
		setTargetName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhAuthorizationsRecord value6(java.lang.String value) {
		setOwnerType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhAuthorizationsRecord value7(java.lang.Long value) {
		setOwnerId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhAuthorizationsRecord value8(java.lang.String value) {
		setAuthType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhAuthorizationsRecord value9(java.lang.Long value) {
		setAuthId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhAuthorizationsRecord value10(java.lang.String value) {
		setIdentityType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhAuthorizationsRecord value11(java.lang.Byte value) {
		setAllFlag(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhAuthorizationsRecord value12(java.lang.String value) {
		setScope(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhAuthorizationsRecord value13(java.lang.Long value) {
		setCreatorUid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhAuthorizationsRecord value14(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhAuthorizationsRecord value15(java.sql.Timestamp value) {
		setUpdateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhAuthorizationsRecord value16(java.lang.Long value) {
		setOperatorUid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhAuthorizationsRecord values(java.lang.Long value1, java.lang.Integer value2, java.lang.String value3, java.lang.Long value4, java.lang.String value5, java.lang.String value6, java.lang.Long value7, java.lang.String value8, java.lang.Long value9, java.lang.String value10, java.lang.Byte value11, java.lang.String value12, java.lang.Long value13, java.sql.Timestamp value14, java.sql.Timestamp value15, java.lang.Long value16) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EhAuthorizationsRecord
	 */
	public EhAuthorizationsRecord() {
		super(com.everhomes.server.schema.tables.EhAuthorizations.EH_AUTHORIZATIONS);
	}

	/**
	 * Create a detached, initialised EhAuthorizationsRecord
	 */
	public EhAuthorizationsRecord(java.lang.Long id, java.lang.Integer namespaceId, java.lang.String targetType, java.lang.Long targetId, java.lang.String targetName, java.lang.String ownerType, java.lang.Long ownerId, java.lang.String authType, java.lang.Long authId, java.lang.String identityType, java.lang.Byte allFlag, java.lang.String scope, java.lang.Long creatorUid, java.sql.Timestamp createTime, java.sql.Timestamp updateTime, java.lang.Long operatorUid) {
		super(com.everhomes.server.schema.tables.EhAuthorizations.EH_AUTHORIZATIONS);

		setValue(0, id);
		setValue(1, namespaceId);
		setValue(2, targetType);
		setValue(3, targetId);
		setValue(4, targetName);
		setValue(5, ownerType);
		setValue(6, ownerId);
		setValue(7, authType);
		setValue(8, authId);
		setValue(9, identityType);
		setValue(10, allFlag);
		setValue(11, scope);
		setValue(12, creatorUid);
		setValue(13, createTime);
		setValue(14, updateTime);
		setValue(15, operatorUid);
	}
}
