/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhAuthorizationRelationsRecord extends org.jooq.impl.UpdatableRecordImpl<com.everhomes.server.schema.tables.records.EhAuthorizationRelationsRecord> implements org.jooq.Record14<java.lang.Long, java.lang.Integer, java.lang.String, java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.Byte, java.lang.Byte, java.lang.Long, java.sql.Timestamp, java.sql.Timestamp, java.lang.Long> {

	private static final long serialVersionUID = -906331440;

	/**
	 * Setter for <code>ehcore.eh_authorization_relations.id</code>. id of the record
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehcore.eh_authorization_relations.id</code>. id of the record
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>ehcore.eh_authorization_relations.namespace_id</code>.
	 */
	public void setNamespaceId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehcore.eh_authorization_relations.namespace_id</code>.
	 */
	public java.lang.Integer getNamespaceId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>ehcore.eh_authorization_relations.owner_type</code>. EhOrganizations, EhCommunities
	 */
	public void setOwnerType(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ehcore.eh_authorization_relations.owner_type</code>. EhOrganizations, EhCommunities
	 */
	public java.lang.String getOwnerType() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>ehcore.eh_authorization_relations.owner_id</code>.
	 */
	public void setOwnerId(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ehcore.eh_authorization_relations.owner_id</code>.
	 */
	public java.lang.Long getOwnerId() {
		return (java.lang.Long) getValue(3);
	}

	/**
	 * Setter for <code>ehcore.eh_authorization_relations.module_id</code>.
	 */
	public void setModuleId(java.lang.Long value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ehcore.eh_authorization_relations.module_id</code>.
	 */
	public java.lang.Long getModuleId() {
		return (java.lang.Long) getValue(4);
	}

	/**
	 * Setter for <code>ehcore.eh_authorization_relations.target_json</code>.
	 */
	public void setTargetJson(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ehcore.eh_authorization_relations.target_json</code>.
	 */
	public java.lang.String getTargetJson() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>ehcore.eh_authorization_relations.project_json</code>.
	 */
	public void setProjectJson(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ehcore.eh_authorization_relations.project_json</code>.
	 */
	public java.lang.String getProjectJson() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>ehcore.eh_authorization_relations.privilege_json</code>.
	 */
	public void setPrivilegeJson(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ehcore.eh_authorization_relations.privilege_json</code>.
	 */
	public java.lang.String getPrivilegeJson() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>ehcore.eh_authorization_relations.all_flag</code>. 0 not all, 1 all
	 */
	public void setAllFlag(java.lang.Byte value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ehcore.eh_authorization_relations.all_flag</code>. 0 not all, 1 all
	 */
	public java.lang.Byte getAllFlag() {
		return (java.lang.Byte) getValue(8);
	}

	/**
	 * Setter for <code>ehcore.eh_authorization_relations.all_project_flag</code>. 0 not all, 1 all
	 */
	public void setAllProjectFlag(java.lang.Byte value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>ehcore.eh_authorization_relations.all_project_flag</code>. 0 not all, 1 all
	 */
	public java.lang.Byte getAllProjectFlag() {
		return (java.lang.Byte) getValue(9);
	}

	/**
	 * Setter for <code>ehcore.eh_authorization_relations.creator_uid</code>.
	 */
	public void setCreatorUid(java.lang.Long value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>ehcore.eh_authorization_relations.creator_uid</code>.
	 */
	public java.lang.Long getCreatorUid() {
		return (java.lang.Long) getValue(10);
	}

	/**
	 * Setter for <code>ehcore.eh_authorization_relations.create_time</code>.
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>ehcore.eh_authorization_relations.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(11);
	}

	/**
	 * Setter for <code>ehcore.eh_authorization_relations.update_time</code>.
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>ehcore.eh_authorization_relations.update_time</code>.
	 */
	public java.sql.Timestamp getUpdateTime() {
		return (java.sql.Timestamp) getValue(12);
	}

	/**
	 * Setter for <code>ehcore.eh_authorization_relations.operator_uid</code>.
	 */
	public void setOperatorUid(java.lang.Long value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>ehcore.eh_authorization_relations.operator_uid</code>.
	 */
	public java.lang.Long getOperatorUid() {
		return (java.lang.Long) getValue(13);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record14 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row14<java.lang.Long, java.lang.Integer, java.lang.String, java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.Byte, java.lang.Byte, java.lang.Long, java.sql.Timestamp, java.sql.Timestamp, java.lang.Long> fieldsRow() {
		return (org.jooq.Row14) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row14<java.lang.Long, java.lang.Integer, java.lang.String, java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.Byte, java.lang.Byte, java.lang.Long, java.sql.Timestamp, java.sql.Timestamp, java.lang.Long> valuesRow() {
		return (org.jooq.Row14) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.everhomes.server.schema.tables.EhAuthorizationRelations.EH_AUTHORIZATION_RELATIONS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.everhomes.server.schema.tables.EhAuthorizationRelations.EH_AUTHORIZATION_RELATIONS.NAMESPACE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.everhomes.server.schema.tables.EhAuthorizationRelations.EH_AUTHORIZATION_RELATIONS.OWNER_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return com.everhomes.server.schema.tables.EhAuthorizationRelations.EH_AUTHORIZATION_RELATIONS.OWNER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field5() {
		return com.everhomes.server.schema.tables.EhAuthorizationRelations.EH_AUTHORIZATION_RELATIONS.MODULE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.everhomes.server.schema.tables.EhAuthorizationRelations.EH_AUTHORIZATION_RELATIONS.TARGET_JSON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.everhomes.server.schema.tables.EhAuthorizationRelations.EH_AUTHORIZATION_RELATIONS.PROJECT_JSON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.everhomes.server.schema.tables.EhAuthorizationRelations.EH_AUTHORIZATION_RELATIONS.PRIVILEGE_JSON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field9() {
		return com.everhomes.server.schema.tables.EhAuthorizationRelations.EH_AUTHORIZATION_RELATIONS.ALL_FLAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field10() {
		return com.everhomes.server.schema.tables.EhAuthorizationRelations.EH_AUTHORIZATION_RELATIONS.ALL_PROJECT_FLAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field11() {
		return com.everhomes.server.schema.tables.EhAuthorizationRelations.EH_AUTHORIZATION_RELATIONS.CREATOR_UID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field12() {
		return com.everhomes.server.schema.tables.EhAuthorizationRelations.EH_AUTHORIZATION_RELATIONS.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field13() {
		return com.everhomes.server.schema.tables.EhAuthorizationRelations.EH_AUTHORIZATION_RELATIONS.UPDATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field14() {
		return com.everhomes.server.schema.tables.EhAuthorizationRelations.EH_AUTHORIZATION_RELATIONS.OPERATOR_UID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getNamespaceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getOwnerType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getOwnerId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value5() {
		return getModuleId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getTargetJson();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getProjectJson();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getPrivilegeJson();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value9() {
		return getAllFlag();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value10() {
		return getAllProjectFlag();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value11() {
		return getCreatorUid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value12() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value13() {
		return getUpdateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value14() {
		return getOperatorUid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhAuthorizationRelationsRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhAuthorizationRelationsRecord value2(java.lang.Integer value) {
		setNamespaceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhAuthorizationRelationsRecord value3(java.lang.String value) {
		setOwnerType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhAuthorizationRelationsRecord value4(java.lang.Long value) {
		setOwnerId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhAuthorizationRelationsRecord value5(java.lang.Long value) {
		setModuleId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhAuthorizationRelationsRecord value6(java.lang.String value) {
		setTargetJson(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhAuthorizationRelationsRecord value7(java.lang.String value) {
		setProjectJson(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhAuthorizationRelationsRecord value8(java.lang.String value) {
		setPrivilegeJson(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhAuthorizationRelationsRecord value9(java.lang.Byte value) {
		setAllFlag(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhAuthorizationRelationsRecord value10(java.lang.Byte value) {
		setAllProjectFlag(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhAuthorizationRelationsRecord value11(java.lang.Long value) {
		setCreatorUid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhAuthorizationRelationsRecord value12(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhAuthorizationRelationsRecord value13(java.sql.Timestamp value) {
		setUpdateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhAuthorizationRelationsRecord value14(java.lang.Long value) {
		setOperatorUid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhAuthorizationRelationsRecord values(java.lang.Long value1, java.lang.Integer value2, java.lang.String value3, java.lang.Long value4, java.lang.Long value5, java.lang.String value6, java.lang.String value7, java.lang.String value8, java.lang.Byte value9, java.lang.Byte value10, java.lang.Long value11, java.sql.Timestamp value12, java.sql.Timestamp value13, java.lang.Long value14) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EhAuthorizationRelationsRecord
	 */
	public EhAuthorizationRelationsRecord() {
		super(com.everhomes.server.schema.tables.EhAuthorizationRelations.EH_AUTHORIZATION_RELATIONS);
	}

	/**
	 * Create a detached, initialised EhAuthorizationRelationsRecord
	 */
	public EhAuthorizationRelationsRecord(java.lang.Long id, java.lang.Integer namespaceId, java.lang.String ownerType, java.lang.Long ownerId, java.lang.Long moduleId, java.lang.String targetJson, java.lang.String projectJson, java.lang.String privilegeJson, java.lang.Byte allFlag, java.lang.Byte allProjectFlag, java.lang.Long creatorUid, java.sql.Timestamp createTime, java.sql.Timestamp updateTime, java.lang.Long operatorUid) {
		super(com.everhomes.server.schema.tables.EhAuthorizationRelations.EH_AUTHORIZATION_RELATIONS);

		setValue(0, id);
		setValue(1, namespaceId);
		setValue(2, ownerType);
		setValue(3, ownerId);
		setValue(4, moduleId);
		setValue(5, targetJson);
		setValue(6, projectJson);
		setValue(7, privilegeJson);
		setValue(8, allFlag);
		setValue(9, allProjectFlag);
		setValue(10, creatorUid);
		setValue(11, createTime);
		setValue(12, updateTime);
		setValue(13, operatorUid);
	}
}
