/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhConfOrderAccountMapRecord extends org.jooq.impl.UpdatableRecordImpl<com.everhomes.server.schema.tables.records.EhConfOrderAccountMapRecord> implements org.jooq.Record7<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Byte, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = 1038685081;

	/**
	 * Setter for <code>ehcore.eh_conf_order_account_map.id</code>. id
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehcore.eh_conf_order_account_map.id</code>. id
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>ehcore.eh_conf_order_account_map.order_id</code>.
	 */
	public void setOrderId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehcore.eh_conf_order_account_map.order_id</code>.
	 */
	public java.lang.Long getOrderId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>ehcore.eh_conf_order_account_map.enterprise_id</code>.
	 */
	public void setEnterpriseId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ehcore.eh_conf_order_account_map.enterprise_id</code>.
	 */
	public java.lang.Long getEnterpriseId() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>ehcore.eh_conf_order_account_map.conf_account_id</code>.
	 */
	public void setConfAccountId(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ehcore.eh_conf_order_account_map.conf_account_id</code>.
	 */
	public java.lang.Long getConfAccountId() {
		return (java.lang.Long) getValue(3);
	}

	/**
	 * Setter for <code>ehcore.eh_conf_order_account_map.assiged_flag</code>. whether the account has assiged to user, 0: none, 1: assigned
	 */
	public void setAssigedFlag(java.lang.Byte value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ehcore.eh_conf_order_account_map.assiged_flag</code>. whether the account has assiged to user, 0: none, 1: assigned
	 */
	public java.lang.Byte getAssigedFlag() {
		return (java.lang.Byte) getValue(4);
	}

	/**
	 * Setter for <code>ehcore.eh_conf_order_account_map.namespace_id</code>.
	 */
	public void setNamespaceId(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ehcore.eh_conf_order_account_map.namespace_id</code>.
	 */
	public java.lang.Integer getNamespaceId() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>ehcore.eh_conf_order_account_map.conf_account_namespace_id</code>.
	 */
	public void setConfAccountNamespaceId(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ehcore.eh_conf_order_account_map.conf_account_namespace_id</code>.
	 */
	public java.lang.Integer getConfAccountNamespaceId() {
		return (java.lang.Integer) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Byte, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Byte, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.everhomes.server.schema.tables.EhConfOrderAccountMap.EH_CONF_ORDER_ACCOUNT_MAP.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.everhomes.server.schema.tables.EhConfOrderAccountMap.EH_CONF_ORDER_ACCOUNT_MAP.ORDER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return com.everhomes.server.schema.tables.EhConfOrderAccountMap.EH_CONF_ORDER_ACCOUNT_MAP.ENTERPRISE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return com.everhomes.server.schema.tables.EhConfOrderAccountMap.EH_CONF_ORDER_ACCOUNT_MAP.CONF_ACCOUNT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field5() {
		return com.everhomes.server.schema.tables.EhConfOrderAccountMap.EH_CONF_ORDER_ACCOUNT_MAP.ASSIGED_FLAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return com.everhomes.server.schema.tables.EhConfOrderAccountMap.EH_CONF_ORDER_ACCOUNT_MAP.NAMESPACE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return com.everhomes.server.schema.tables.EhConfOrderAccountMap.EH_CONF_ORDER_ACCOUNT_MAP.CONF_ACCOUNT_NAMESPACE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getOrderId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getEnterpriseId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getConfAccountId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value5() {
		return getAssigedFlag();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getNamespaceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getConfAccountNamespaceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhConfOrderAccountMapRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhConfOrderAccountMapRecord value2(java.lang.Long value) {
		setOrderId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhConfOrderAccountMapRecord value3(java.lang.Long value) {
		setEnterpriseId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhConfOrderAccountMapRecord value4(java.lang.Long value) {
		setConfAccountId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhConfOrderAccountMapRecord value5(java.lang.Byte value) {
		setAssigedFlag(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhConfOrderAccountMapRecord value6(java.lang.Integer value) {
		setNamespaceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhConfOrderAccountMapRecord value7(java.lang.Integer value) {
		setConfAccountNamespaceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhConfOrderAccountMapRecord values(java.lang.Long value1, java.lang.Long value2, java.lang.Long value3, java.lang.Long value4, java.lang.Byte value5, java.lang.Integer value6, java.lang.Integer value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EhConfOrderAccountMapRecord
	 */
	public EhConfOrderAccountMapRecord() {
		super(com.everhomes.server.schema.tables.EhConfOrderAccountMap.EH_CONF_ORDER_ACCOUNT_MAP);
	}

	/**
	 * Create a detached, initialised EhConfOrderAccountMapRecord
	 */
	public EhConfOrderAccountMapRecord(java.lang.Long id, java.lang.Long orderId, java.lang.Long enterpriseId, java.lang.Long confAccountId, java.lang.Byte assigedFlag, java.lang.Integer namespaceId, java.lang.Integer confAccountNamespaceId) {
		super(com.everhomes.server.schema.tables.EhConfOrderAccountMap.EH_CONF_ORDER_ACCOUNT_MAP);

		setValue(0, id);
		setValue(1, orderId);
		setValue(2, enterpriseId);
		setValue(3, confAccountId);
		setValue(4, assigedFlag);
		setValue(5, namespaceId);
		setValue(6, confAccountNamespaceId);
	}
}
