/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhGeneralApprovalValsRecord extends org.jooq.impl.UpdatableRecordImpl<com.everhomes.server.schema.tables.records.EhGeneralApprovalValsRecord> implements org.jooq.Record18<java.lang.Long, java.lang.Integer, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.Byte, java.lang.String, java.lang.String, java.lang.String, java.lang.Long, java.lang.Long, java.lang.Long, java.sql.Timestamp> {

	private static final long serialVersionUID = 329524064;

	/**
	 * Setter for <code>ehcore.eh_general_approval_vals.id</code>. id of the record
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehcore.eh_general_approval_vals.id</code>. id of the record
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>ehcore.eh_general_approval_vals.namespace_id</code>.
	 */
	public void setNamespaceId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehcore.eh_general_approval_vals.namespace_id</code>.
	 */
	public java.lang.Integer getNamespaceId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>ehcore.eh_general_approval_vals.flow_case_id</code>.
	 */
	public void setFlowCaseId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ehcore.eh_general_approval_vals.flow_case_id</code>.
	 */
	public java.lang.Long getFlowCaseId() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>ehcore.eh_general_approval_vals.request_id</code>.
	 */
	public void setRequestId(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ehcore.eh_general_approval_vals.request_id</code>.
	 */
	public java.lang.Long getRequestId() {
		return (java.lang.Long) getValue(3);
	}

	/**
	 * Setter for <code>ehcore.eh_general_approval_vals.approval_id</code>.
	 */
	public void setApprovalId(java.lang.Long value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ehcore.eh_general_approval_vals.approval_id</code>.
	 */
	public java.lang.Long getApprovalId() {
		return (java.lang.Long) getValue(4);
	}

	/**
	 * Setter for <code>ehcore.eh_general_approval_vals.form_origin_id</code>.
	 */
	public void setFormOriginId(java.lang.Long value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ehcore.eh_general_approval_vals.form_origin_id</code>.
	 */
	public java.lang.Long getFormOriginId() {
		return (java.lang.Long) getValue(5);
	}

	/**
	 * Setter for <code>ehcore.eh_general_approval_vals.form_version</code>.
	 */
	public void setFormVersion(java.lang.Long value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ehcore.eh_general_approval_vals.form_version</code>.
	 */
	public java.lang.Long getFormVersion() {
		return (java.lang.Long) getValue(6);
	}

	/**
	 * Setter for <code>ehcore.eh_general_approval_vals.field_name</code>.
	 */
	public void setFieldName(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ehcore.eh_general_approval_vals.field_name</code>.
	 */
	public java.lang.String getFieldName() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>ehcore.eh_general_approval_vals.field_type</code>.
	 */
	public void setFieldType(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ehcore.eh_general_approval_vals.field_type</code>.
	 */
	public java.lang.String getFieldType() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>ehcore.eh_general_approval_vals.data_source_type</code>.
	 */
	public void setDataSourceType(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>ehcore.eh_general_approval_vals.data_source_type</code>.
	 */
	public java.lang.String getDataSourceType() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>ehcore.eh_general_approval_vals.val_type</code>. 0: invalid, 1: request_root, 2: request_item
	 */
	public void setValType(java.lang.Byte value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>ehcore.eh_general_approval_vals.val_type</code>. 0: invalid, 1: request_root, 2: request_item
	 */
	public java.lang.Byte getValType() {
		return (java.lang.Byte) getValue(10);
	}

	/**
	 * Setter for <code>ehcore.eh_general_approval_vals.field_str1</code>.
	 */
	public void setFieldStr1(java.lang.String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>ehcore.eh_general_approval_vals.field_str1</code>.
	 */
	public java.lang.String getFieldStr1() {
		return (java.lang.String) getValue(11);
	}

	/**
	 * Setter for <code>ehcore.eh_general_approval_vals.field_str2</code>.
	 */
	public void setFieldStr2(java.lang.String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>ehcore.eh_general_approval_vals.field_str2</code>.
	 */
	public java.lang.String getFieldStr2() {
		return (java.lang.String) getValue(12);
	}

	/**
	 * Setter for <code>ehcore.eh_general_approval_vals.field_str3</code>.
	 */
	public void setFieldStr3(java.lang.String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>ehcore.eh_general_approval_vals.field_str3</code>.
	 */
	public java.lang.String getFieldStr3() {
		return (java.lang.String) getValue(13);
	}

	/**
	 * Setter for <code>ehcore.eh_general_approval_vals.field_int1</code>.
	 */
	public void setFieldInt1(java.lang.Long value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>ehcore.eh_general_approval_vals.field_int1</code>.
	 */
	public java.lang.Long getFieldInt1() {
		return (java.lang.Long) getValue(14);
	}

	/**
	 * Setter for <code>ehcore.eh_general_approval_vals.field_int2</code>.
	 */
	public void setFieldInt2(java.lang.Long value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>ehcore.eh_general_approval_vals.field_int2</code>.
	 */
	public java.lang.Long getFieldInt2() {
		return (java.lang.Long) getValue(15);
	}

	/**
	 * Setter for <code>ehcore.eh_general_approval_vals.field_int3</code>.
	 */
	public void setFieldInt3(java.lang.Long value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>ehcore.eh_general_approval_vals.field_int3</code>.
	 */
	public java.lang.Long getFieldInt3() {
		return (java.lang.Long) getValue(16);
	}

	/**
	 * Setter for <code>ehcore.eh_general_approval_vals.create_time</code>. record create time
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>ehcore.eh_general_approval_vals.create_time</code>. record create time
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(17);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record18 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row18<java.lang.Long, java.lang.Integer, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.Byte, java.lang.String, java.lang.String, java.lang.String, java.lang.Long, java.lang.Long, java.lang.Long, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row18) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row18<java.lang.Long, java.lang.Integer, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.Byte, java.lang.String, java.lang.String, java.lang.String, java.lang.Long, java.lang.Long, java.lang.Long, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row18) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.everhomes.server.schema.tables.EhGeneralApprovalVals.EH_GENERAL_APPROVAL_VALS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.everhomes.server.schema.tables.EhGeneralApprovalVals.EH_GENERAL_APPROVAL_VALS.NAMESPACE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return com.everhomes.server.schema.tables.EhGeneralApprovalVals.EH_GENERAL_APPROVAL_VALS.FLOW_CASE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return com.everhomes.server.schema.tables.EhGeneralApprovalVals.EH_GENERAL_APPROVAL_VALS.REQUEST_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field5() {
		return com.everhomes.server.schema.tables.EhGeneralApprovalVals.EH_GENERAL_APPROVAL_VALS.APPROVAL_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field6() {
		return com.everhomes.server.schema.tables.EhGeneralApprovalVals.EH_GENERAL_APPROVAL_VALS.FORM_ORIGIN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field7() {
		return com.everhomes.server.schema.tables.EhGeneralApprovalVals.EH_GENERAL_APPROVAL_VALS.FORM_VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.everhomes.server.schema.tables.EhGeneralApprovalVals.EH_GENERAL_APPROVAL_VALS.FIELD_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return com.everhomes.server.schema.tables.EhGeneralApprovalVals.EH_GENERAL_APPROVAL_VALS.FIELD_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return com.everhomes.server.schema.tables.EhGeneralApprovalVals.EH_GENERAL_APPROVAL_VALS.DATA_SOURCE_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field11() {
		return com.everhomes.server.schema.tables.EhGeneralApprovalVals.EH_GENERAL_APPROVAL_VALS.VAL_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field12() {
		return com.everhomes.server.schema.tables.EhGeneralApprovalVals.EH_GENERAL_APPROVAL_VALS.FIELD_STR1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field13() {
		return com.everhomes.server.schema.tables.EhGeneralApprovalVals.EH_GENERAL_APPROVAL_VALS.FIELD_STR2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field14() {
		return com.everhomes.server.schema.tables.EhGeneralApprovalVals.EH_GENERAL_APPROVAL_VALS.FIELD_STR3;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field15() {
		return com.everhomes.server.schema.tables.EhGeneralApprovalVals.EH_GENERAL_APPROVAL_VALS.FIELD_INT1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field16() {
		return com.everhomes.server.schema.tables.EhGeneralApprovalVals.EH_GENERAL_APPROVAL_VALS.FIELD_INT2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field17() {
		return com.everhomes.server.schema.tables.EhGeneralApprovalVals.EH_GENERAL_APPROVAL_VALS.FIELD_INT3;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field18() {
		return com.everhomes.server.schema.tables.EhGeneralApprovalVals.EH_GENERAL_APPROVAL_VALS.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getNamespaceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getFlowCaseId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getRequestId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value5() {
		return getApprovalId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value6() {
		return getFormOriginId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value7() {
		return getFormVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getFieldName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getFieldType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getDataSourceType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value11() {
		return getValType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value12() {
		return getFieldStr1();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value13() {
		return getFieldStr2();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value14() {
		return getFieldStr3();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value15() {
		return getFieldInt1();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value16() {
		return getFieldInt2();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value17() {
		return getFieldInt3();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value18() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhGeneralApprovalValsRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhGeneralApprovalValsRecord value2(java.lang.Integer value) {
		setNamespaceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhGeneralApprovalValsRecord value3(java.lang.Long value) {
		setFlowCaseId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhGeneralApprovalValsRecord value4(java.lang.Long value) {
		setRequestId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhGeneralApprovalValsRecord value5(java.lang.Long value) {
		setApprovalId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhGeneralApprovalValsRecord value6(java.lang.Long value) {
		setFormOriginId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhGeneralApprovalValsRecord value7(java.lang.Long value) {
		setFormVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhGeneralApprovalValsRecord value8(java.lang.String value) {
		setFieldName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhGeneralApprovalValsRecord value9(java.lang.String value) {
		setFieldType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhGeneralApprovalValsRecord value10(java.lang.String value) {
		setDataSourceType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhGeneralApprovalValsRecord value11(java.lang.Byte value) {
		setValType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhGeneralApprovalValsRecord value12(java.lang.String value) {
		setFieldStr1(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhGeneralApprovalValsRecord value13(java.lang.String value) {
		setFieldStr2(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhGeneralApprovalValsRecord value14(java.lang.String value) {
		setFieldStr3(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhGeneralApprovalValsRecord value15(java.lang.Long value) {
		setFieldInt1(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhGeneralApprovalValsRecord value16(java.lang.Long value) {
		setFieldInt2(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhGeneralApprovalValsRecord value17(java.lang.Long value) {
		setFieldInt3(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhGeneralApprovalValsRecord value18(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhGeneralApprovalValsRecord values(java.lang.Long value1, java.lang.Integer value2, java.lang.Long value3, java.lang.Long value4, java.lang.Long value5, java.lang.Long value6, java.lang.Long value7, java.lang.String value8, java.lang.String value9, java.lang.String value10, java.lang.Byte value11, java.lang.String value12, java.lang.String value13, java.lang.String value14, java.lang.Long value15, java.lang.Long value16, java.lang.Long value17, java.sql.Timestamp value18) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EhGeneralApprovalValsRecord
	 */
	public EhGeneralApprovalValsRecord() {
		super(com.everhomes.server.schema.tables.EhGeneralApprovalVals.EH_GENERAL_APPROVAL_VALS);
	}

	/**
	 * Create a detached, initialised EhGeneralApprovalValsRecord
	 */
	public EhGeneralApprovalValsRecord(java.lang.Long id, java.lang.Integer namespaceId, java.lang.Long flowCaseId, java.lang.Long requestId, java.lang.Long approvalId, java.lang.Long formOriginId, java.lang.Long formVersion, java.lang.String fieldName, java.lang.String fieldType, java.lang.String dataSourceType, java.lang.Byte valType, java.lang.String fieldStr1, java.lang.String fieldStr2, java.lang.String fieldStr3, java.lang.Long fieldInt1, java.lang.Long fieldInt2, java.lang.Long fieldInt3, java.sql.Timestamp createTime) {
		super(com.everhomes.server.schema.tables.EhGeneralApprovalVals.EH_GENERAL_APPROVAL_VALS);

		setValue(0, id);
		setValue(1, namespaceId);
		setValue(2, flowCaseId);
		setValue(3, requestId);
		setValue(4, approvalId);
		setValue(5, formOriginId);
		setValue(6, formVersion);
		setValue(7, fieldName);
		setValue(8, fieldType);
		setValue(9, dataSourceType);
		setValue(10, valType);
		setValue(11, fieldStr1);
		setValue(12, fieldStr2);
		setValue(13, fieldStr3);
		setValue(14, fieldInt1);
		setValue(15, fieldInt2);
		setValue(16, fieldInt3);
		setValue(17, createTime);
	}
}
