/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhOfficeCubicleOrdersRecord extends org.jooq.impl.UpdatableRecordImpl<com.everhomes.server.schema.tables.records.EhOfficeCubicleOrdersRecord> {

	private static final long serialVersionUID = 885075771;

	/**
	 * Setter for <code>ehcore.eh_office_cubicle_orders.id</code>. id
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehcore.eh_office_cubicle_orders.id</code>. id
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>ehcore.eh_office_cubicle_orders.namespace_id</code>.
	 */
	public void setNamespaceId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehcore.eh_office_cubicle_orders.namespace_id</code>.
	 */
	public java.lang.Integer getNamespaceId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>ehcore.eh_office_cubicle_orders.space_id</code>. 工位空间id
	 */
	public void setSpaceId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ehcore.eh_office_cubicle_orders.space_id</code>. 工位空间id
	 */
	public java.lang.Long getSpaceId() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>ehcore.eh_office_cubicle_orders.space_name</code>. 工位空间名称
	 */
	public void setSpaceName(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ehcore.eh_office_cubicle_orders.space_name</code>. 工位空间名称
	 */
	public java.lang.String getSpaceName() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>ehcore.eh_office_cubicle_orders.province_id</code>. 省份id
	 */
	public void setProvinceId(java.lang.Long value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ehcore.eh_office_cubicle_orders.province_id</code>. 省份id
	 */
	public java.lang.Long getProvinceId() {
		return (java.lang.Long) getValue(4);
	}

	/**
	 * Setter for <code>ehcore.eh_office_cubicle_orders.province_name</code>. 省份名称
	 */
	public void setProvinceName(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ehcore.eh_office_cubicle_orders.province_name</code>. 省份名称
	 */
	public java.lang.String getProvinceName() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>ehcore.eh_office_cubicle_orders.city_id</code>. 城市id
	 */
	public void setCityId(java.lang.Long value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ehcore.eh_office_cubicle_orders.city_id</code>. 城市id
	 */
	public java.lang.Long getCityId() {
		return (java.lang.Long) getValue(6);
	}

	/**
	 * Setter for <code>ehcore.eh_office_cubicle_orders.city_name</code>. 城市名称
	 */
	public void setCityName(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ehcore.eh_office_cubicle_orders.city_name</code>. 城市名称
	 */
	public java.lang.String getCityName() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>ehcore.eh_office_cubicle_orders.cover_uri</code>. 封面图片
	 */
	public void setCoverUri(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ehcore.eh_office_cubicle_orders.cover_uri</code>. 封面图片
	 */
	public java.lang.String getCoverUri() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>ehcore.eh_office_cubicle_orders.address</code>. 地址
	 */
	public void setAddress(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>ehcore.eh_office_cubicle_orders.address</code>. 地址
	 */
	public java.lang.String getAddress() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>ehcore.eh_office_cubicle_orders.longitude</code>. 经度
	 */
	public void setLongitude(java.lang.Double value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>ehcore.eh_office_cubicle_orders.longitude</code>. 经度
	 */
	public java.lang.Double getLongitude() {
		return (java.lang.Double) getValue(10);
	}

	/**
	 * Setter for <code>ehcore.eh_office_cubicle_orders.latitude</code>. 纬度
	 */
	public void setLatitude(java.lang.Double value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>ehcore.eh_office_cubicle_orders.latitude</code>. 纬度
	 */
	public java.lang.Double getLatitude() {
		return (java.lang.Double) getValue(11);
	}

	/**
	 * Setter for <code>ehcore.eh_office_cubicle_orders.geohash</code>.
	 */
	public void setGeohash(java.lang.String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>ehcore.eh_office_cubicle_orders.geohash</code>.
	 */
	public java.lang.String getGeohash() {
		return (java.lang.String) getValue(12);
	}

	/**
	 * Setter for <code>ehcore.eh_office_cubicle_orders.contact_phone</code>. 咨询电话
	 */
	public void setContactPhone(java.lang.String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>ehcore.eh_office_cubicle_orders.contact_phone</code>. 咨询电话
	 */
	public java.lang.String getContactPhone() {
		return (java.lang.String) getValue(13);
	}

	/**
	 * Setter for <code>ehcore.eh_office_cubicle_orders.manager_uid</code>. 负责人uid
	 */
	public void setManagerUid(java.lang.Long value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>ehcore.eh_office_cubicle_orders.manager_uid</code>. 负责人uid
	 */
	public java.lang.Long getManagerUid() {
		return (java.lang.Long) getValue(14);
	}

	/**
	 * Setter for <code>ehcore.eh_office_cubicle_orders.description</code>. 详情-html片
	 */
	public void setDescription(java.lang.String value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>ehcore.eh_office_cubicle_orders.description</code>. 详情-html片
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(15);
	}

	/**
	 * Setter for <code>ehcore.eh_office_cubicle_orders.rent_type</code>. 租赁类别:1-开放式（默认space_type 1）,2-办公室
	 */
	public void setRentType(java.lang.Byte value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>ehcore.eh_office_cubicle_orders.rent_type</code>. 租赁类别:1-开放式（默认space_type 1）,2-办公室
	 */
	public java.lang.Byte getRentType() {
		return (java.lang.Byte) getValue(16);
	}

	/**
	 * Setter for <code>ehcore.eh_office_cubicle_orders.space_type</code>. 空间类别:1-工位,2-面积
	 */
	public void setSpaceType(java.lang.Byte value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>ehcore.eh_office_cubicle_orders.space_type</code>. 空间类别:1-工位,2-面积
	 */
	public java.lang.Byte getSpaceType() {
		return (java.lang.Byte) getValue(17);
	}

	/**
	 * Setter for <code>ehcore.eh_office_cubicle_orders.space_size</code>. 工位数或面积数
	 */
	public void setSpaceSize(java.lang.String value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>ehcore.eh_office_cubicle_orders.space_size</code>. 工位数或面积数
	 */
	public java.lang.String getSpaceSize() {
		return (java.lang.String) getValue(18);
	}

	/**
	 * Setter for <code>ehcore.eh_office_cubicle_orders.status</code>. 状态:2-用户可见,0-用户不可见
	 */
	public void setStatus(java.lang.Byte value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>ehcore.eh_office_cubicle_orders.status</code>. 状态:2-用户可见,0-用户不可见
	 */
	public java.lang.Byte getStatus() {
		return (java.lang.Byte) getValue(19);
	}

	/**
	 * Setter for <code>ehcore.eh_office_cubicle_orders.order_type</code>. 预定类别：1-参观 2-预定
	 */
	public void setOrderType(java.lang.Byte value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>ehcore.eh_office_cubicle_orders.order_type</code>. 预定类别：1-参观 2-预定
	 */
	public java.lang.Byte getOrderType() {
		return (java.lang.Byte) getValue(20);
	}

	/**
	 * Setter for <code>ehcore.eh_office_cubicle_orders.reserver_uid</code>. 预订人uid
	 */
	public void setReserverUid(java.lang.Long value) {
		setValue(21, value);
	}

	/**
	 * Getter for <code>ehcore.eh_office_cubicle_orders.reserver_uid</code>. 预订人uid
	 */
	public java.lang.Long getReserverUid() {
		return (java.lang.Long) getValue(21);
	}

	/**
	 * Setter for <code>ehcore.eh_office_cubicle_orders.reserve_time</code>. 预定时间
	 */
	public void setReserveTime(java.sql.Timestamp value) {
		setValue(22, value);
	}

	/**
	 * Getter for <code>ehcore.eh_office_cubicle_orders.reserve_time</code>. 预定时间
	 */
	public java.sql.Timestamp getReserveTime() {
		return (java.sql.Timestamp) getValue(22);
	}

	/**
	 * Setter for <code>ehcore.eh_office_cubicle_orders.reserver_name</code>. 预订人姓名
	 */
	public void setReserverName(java.lang.String value) {
		setValue(23, value);
	}

	/**
	 * Getter for <code>ehcore.eh_office_cubicle_orders.reserver_name</code>. 预订人姓名
	 */
	public java.lang.String getReserverName() {
		return (java.lang.String) getValue(23);
	}

	/**
	 * Setter for <code>ehcore.eh_office_cubicle_orders.reserve_contact_token</code>. 预定联系方式
	 */
	public void setReserveContactToken(java.lang.String value) {
		setValue(24, value);
	}

	/**
	 * Getter for <code>ehcore.eh_office_cubicle_orders.reserve_contact_token</code>. 预定联系方式
	 */
	public java.lang.String getReserveContactToken() {
		return (java.lang.String) getValue(24);
	}

	/**
	 * Setter for <code>ehcore.eh_office_cubicle_orders.reserve_enterprise</code>. 预订人公司
	 */
	public void setReserveEnterprise(java.lang.String value) {
		setValue(25, value);
	}

	/**
	 * Getter for <code>ehcore.eh_office_cubicle_orders.reserve_enterprise</code>. 预订人公司
	 */
	public java.lang.String getReserveEnterprise() {
		return (java.lang.String) getValue(25);
	}

	/**
	 * Setter for <code>ehcore.eh_office_cubicle_orders.create_time</code>.
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(26, value);
	}

	/**
	 * Getter for <code>ehcore.eh_office_cubicle_orders.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(26);
	}

	/**
	 * Setter for <code>ehcore.eh_office_cubicle_orders.update_time</code>.
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(27, value);
	}

	/**
	 * Getter for <code>ehcore.eh_office_cubicle_orders.update_time</code>.
	 */
	public java.sql.Timestamp getUpdateTime() {
		return (java.sql.Timestamp) getValue(27);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EhOfficeCubicleOrdersRecord
	 */
	public EhOfficeCubicleOrdersRecord() {
		super(com.everhomes.server.schema.tables.EhOfficeCubicleOrders.EH_OFFICE_CUBICLE_ORDERS);
	}

	/**
	 * Create a detached, initialised EhOfficeCubicleOrdersRecord
	 */
	public EhOfficeCubicleOrdersRecord(java.lang.Long id, java.lang.Integer namespaceId, java.lang.Long spaceId, java.lang.String spaceName, java.lang.Long provinceId, java.lang.String provinceName, java.lang.Long cityId, java.lang.String cityName, java.lang.String coverUri, java.lang.String address, java.lang.Double longitude, java.lang.Double latitude, java.lang.String geohash, java.lang.String contactPhone, java.lang.Long managerUid, java.lang.String description, java.lang.Byte rentType, java.lang.Byte spaceType, java.lang.String spaceSize, java.lang.Byte status, java.lang.Byte orderType, java.lang.Long reserverUid, java.sql.Timestamp reserveTime, java.lang.String reserverName, java.lang.String reserveContactToken, java.lang.String reserveEnterprise, java.sql.Timestamp createTime, java.sql.Timestamp updateTime) {
		super(com.everhomes.server.schema.tables.EhOfficeCubicleOrders.EH_OFFICE_CUBICLE_ORDERS);

		setValue(0, id);
		setValue(1, namespaceId);
		setValue(2, spaceId);
		setValue(3, spaceName);
		setValue(4, provinceId);
		setValue(5, provinceName);
		setValue(6, cityId);
		setValue(7, cityName);
		setValue(8, coverUri);
		setValue(9, address);
		setValue(10, longitude);
		setValue(11, latitude);
		setValue(12, geohash);
		setValue(13, contactPhone);
		setValue(14, managerUid);
		setValue(15, description);
		setValue(16, rentType);
		setValue(17, spaceType);
		setValue(18, spaceSize);
		setValue(19, status);
		setValue(20, orderType);
		setValue(21, reserverUid);
		setValue(22, reserveTime);
		setValue(23, reserverName);
		setValue(24, reserveContactToken);
		setValue(25, reserveEnterprise);
		setValue(26, createTime);
		setValue(27, updateTime);
	}
}
