/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhOrganizationMemberInsurancesRecord extends org.jooq.impl.UpdatableRecordImpl<com.everhomes.server.schema.tables.records.EhOrganizationMemberInsurancesRecord> implements org.jooq.Record11<java.lang.Long, java.lang.Long, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Date, java.sql.Date, java.lang.Long, java.sql.Timestamp, java.lang.Byte> {

	private static final long serialVersionUID = 1912875810;

	/**
	 * Setter for <code>ehcore.eh_organization_member_insurances.id</code>. id for records
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_member_insurances.id</code>. id for records
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_member_insurances.detail_id</code>. id for members, reference for eh_organization_member_details id
	 */
	public void setDetailId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_member_insurances.detail_id</code>. id for members, reference for eh_organization_member_details id
	 */
	public java.lang.Long getDetailId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_member_insurances.namespace_id</code>.
	 */
	public void setNamespaceId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_member_insurances.namespace_id</code>.
	 */
	public java.lang.Integer getNamespaceId() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_member_insurances.name</code>. the name of the insurance
	 */
	public void setName(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_member_insurances.name</code>. the name of the insurance
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_member_insurances.enterprise</code>. the company name of the insurance
	 */
	public void setEnterprise(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_member_insurances.enterprise</code>. the company name of the insurance
	 */
	public java.lang.String getEnterprise() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_member_insurances.number</code>. the number of the insurance
	 */
	public void setNumber(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_member_insurances.number</code>. the number of the insurance
	 */
	public java.lang.String getNumber() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_member_insurances.start_time</code>. 生效时间
	 */
	public void setStartTime(java.sql.Date value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_member_insurances.start_time</code>. 生效时间
	 */
	public java.sql.Date getStartTime() {
		return (java.sql.Date) getValue(6);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_member_insurances.end_time</code>. 到期时间
	 */
	public void setEndTime(java.sql.Date value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_member_insurances.end_time</code>. 到期时间
	 */
	public java.sql.Date getEndTime() {
		return (java.sql.Date) getValue(7);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_member_insurances.creator_uid</code>.
	 */
	public void setCreatorUid(java.lang.Long value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_member_insurances.creator_uid</code>.
	 */
	public java.lang.Long getCreatorUid() {
		return (java.lang.Long) getValue(8);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_member_insurances.create_time</code>.
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_member_insurances.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(9);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_member_insurances.status</code>. 0: inactive, 3: active
	 */
	public void setStatus(java.lang.Byte value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_member_insurances.status</code>. 0: inactive, 3: active
	 */
	public java.lang.Byte getStatus() {
		return (java.lang.Byte) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.lang.Long, java.lang.Long, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Date, java.sql.Date, java.lang.Long, java.sql.Timestamp, java.lang.Byte> fieldsRow() {
		return (org.jooq.Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.lang.Long, java.lang.Long, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Date, java.sql.Date, java.lang.Long, java.sql.Timestamp, java.lang.Byte> valuesRow() {
		return (org.jooq.Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.everhomes.server.schema.tables.EhOrganizationMemberInsurances.EH_ORGANIZATION_MEMBER_INSURANCES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.everhomes.server.schema.tables.EhOrganizationMemberInsurances.EH_ORGANIZATION_MEMBER_INSURANCES.DETAIL_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return com.everhomes.server.schema.tables.EhOrganizationMemberInsurances.EH_ORGANIZATION_MEMBER_INSURANCES.NAMESPACE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.everhomes.server.schema.tables.EhOrganizationMemberInsurances.EH_ORGANIZATION_MEMBER_INSURANCES.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.everhomes.server.schema.tables.EhOrganizationMemberInsurances.EH_ORGANIZATION_MEMBER_INSURANCES.ENTERPRISE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.everhomes.server.schema.tables.EhOrganizationMemberInsurances.EH_ORGANIZATION_MEMBER_INSURANCES.NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field7() {
		return com.everhomes.server.schema.tables.EhOrganizationMemberInsurances.EH_ORGANIZATION_MEMBER_INSURANCES.START_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field8() {
		return com.everhomes.server.schema.tables.EhOrganizationMemberInsurances.EH_ORGANIZATION_MEMBER_INSURANCES.END_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field9() {
		return com.everhomes.server.schema.tables.EhOrganizationMemberInsurances.EH_ORGANIZATION_MEMBER_INSURANCES.CREATOR_UID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field10() {
		return com.everhomes.server.schema.tables.EhOrganizationMemberInsurances.EH_ORGANIZATION_MEMBER_INSURANCES.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field11() {
		return com.everhomes.server.schema.tables.EhOrganizationMemberInsurances.EH_ORGANIZATION_MEMBER_INSURANCES.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getDetailId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getNamespaceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getEnterprise();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value7() {
		return getStartTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value8() {
		return getEndTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value9() {
		return getCreatorUid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value10() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value11() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhOrganizationMemberInsurancesRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhOrganizationMemberInsurancesRecord value2(java.lang.Long value) {
		setDetailId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhOrganizationMemberInsurancesRecord value3(java.lang.Integer value) {
		setNamespaceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhOrganizationMemberInsurancesRecord value4(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhOrganizationMemberInsurancesRecord value5(java.lang.String value) {
		setEnterprise(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhOrganizationMemberInsurancesRecord value6(java.lang.String value) {
		setNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhOrganizationMemberInsurancesRecord value7(java.sql.Date value) {
		setStartTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhOrganizationMemberInsurancesRecord value8(java.sql.Date value) {
		setEndTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhOrganizationMemberInsurancesRecord value9(java.lang.Long value) {
		setCreatorUid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhOrganizationMemberInsurancesRecord value10(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhOrganizationMemberInsurancesRecord value11(java.lang.Byte value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhOrganizationMemberInsurancesRecord values(java.lang.Long value1, java.lang.Long value2, java.lang.Integer value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.sql.Date value7, java.sql.Date value8, java.lang.Long value9, java.sql.Timestamp value10, java.lang.Byte value11) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EhOrganizationMemberInsurancesRecord
	 */
	public EhOrganizationMemberInsurancesRecord() {
		super(com.everhomes.server.schema.tables.EhOrganizationMemberInsurances.EH_ORGANIZATION_MEMBER_INSURANCES);
	}

	/**
	 * Create a detached, initialised EhOrganizationMemberInsurancesRecord
	 */
	public EhOrganizationMemberInsurancesRecord(java.lang.Long id, java.lang.Long detailId, java.lang.Integer namespaceId, java.lang.String name, java.lang.String enterprise, java.lang.String number, java.sql.Date startTime, java.sql.Date endTime, java.lang.Long creatorUid, java.sql.Timestamp createTime, java.lang.Byte status) {
		super(com.everhomes.server.schema.tables.EhOrganizationMemberInsurances.EH_ORGANIZATION_MEMBER_INSURANCES);

		setValue(0, id);
		setValue(1, detailId);
		setValue(2, namespaceId);
		setValue(3, name);
		setValue(4, enterprise);
		setValue(5, number);
		setValue(6, startTime);
		setValue(7, endTime);
		setValue(8, creatorUid);
		setValue(9, createTime);
		setValue(10, status);
	}
}
