/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhOrganizationDetailsRecord extends org.jooq.impl.UpdatableRecordImpl<com.everhomes.server.schema.tables.records.EhOrganizationDetailsRecord> {

	private static final long serialVersionUID = 495248283;

	/**
	 * Setter for <code>ehcore.eh_organization_details.id</code>. id of the record
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_details.id</code>. id of the record
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_details.organization_id</code>. group id
	 */
	public void setOrganizationId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_details.organization_id</code>. group id
	 */
	public java.lang.Long getOrganizationId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_details.description</code>. description
	 */
	public void setDescription(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_details.description</code>. description
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_details.contact</code>. the phone number
	 */
	public void setContact(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_details.contact</code>. the phone number
	 */
	public java.lang.String getContact() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_details.address</code>. address str
	 */
	public void setAddress(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_details.address</code>. address str
	 */
	public java.lang.String getAddress() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_details.create_time</code>.
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_details.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_details.longitude</code>.
	 */
	public void setLongitude(java.lang.Double value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_details.longitude</code>.
	 */
	public java.lang.Double getLongitude() {
		return (java.lang.Double) getValue(6);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_details.latitude</code>.
	 */
	public void setLatitude(java.lang.Double value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_details.latitude</code>.
	 */
	public java.lang.Double getLatitude() {
		return (java.lang.Double) getValue(7);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_details.geohash</code>.
	 */
	public void setGeohash(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_details.geohash</code>.
	 */
	public java.lang.String getGeohash() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_details.display_name</code>.
	 */
	public void setDisplayName(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_details.display_name</code>.
	 */
	public java.lang.String getDisplayName() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_details.contactor</code>.
	 */
	public void setContactor(java.lang.String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_details.contactor</code>.
	 */
	public java.lang.String getContactor() {
		return (java.lang.String) getValue(10);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_details.member_count</code>.
	 */
	public void setMemberCount(java.lang.Long value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_details.member_count</code>.
	 */
	public java.lang.Long getMemberCount() {
		return (java.lang.Long) getValue(11);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_details.checkin_date</code>. checkin date
	 */
	public void setCheckinDate(java.sql.Timestamp value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_details.checkin_date</code>. checkin date
	 */
	public java.sql.Timestamp getCheckinDate() {
		return (java.sql.Timestamp) getValue(12);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_details.avatar</code>.
	 */
	public void setAvatar(java.lang.String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_details.avatar</code>.
	 */
	public java.lang.String getAvatar() {
		return (java.lang.String) getValue(13);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_details.post_uri</code>.
	 */
	public void setPostUri(java.lang.String value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_details.post_uri</code>.
	 */
	public java.lang.String getPostUri() {
		return (java.lang.String) getValue(14);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_details.integral_tag1</code>.
	 */
	public void setIntegralTag1(java.lang.Long value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_details.integral_tag1</code>.
	 */
	public java.lang.Long getIntegralTag1() {
		return (java.lang.Long) getValue(15);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_details.integral_tag2</code>.
	 */
	public void setIntegralTag2(java.lang.Long value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_details.integral_tag2</code>.
	 */
	public java.lang.Long getIntegralTag2() {
		return (java.lang.Long) getValue(16);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_details.integral_tag3</code>.
	 */
	public void setIntegralTag3(java.lang.Long value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_details.integral_tag3</code>.
	 */
	public java.lang.Long getIntegralTag3() {
		return (java.lang.Long) getValue(17);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_details.integral_tag4</code>.
	 */
	public void setIntegralTag4(java.lang.Long value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_details.integral_tag4</code>.
	 */
	public java.lang.Long getIntegralTag4() {
		return (java.lang.Long) getValue(18);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_details.integral_tag5</code>.
	 */
	public void setIntegralTag5(java.lang.Long value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_details.integral_tag5</code>.
	 */
	public java.lang.Long getIntegralTag5() {
		return (java.lang.Long) getValue(19);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_details.string_tag1</code>.
	 */
	public void setStringTag1(java.lang.String value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_details.string_tag1</code>.
	 */
	public java.lang.String getStringTag1() {
		return (java.lang.String) getValue(20);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_details.string_tag2</code>.
	 */
	public void setStringTag2(java.lang.String value) {
		setValue(21, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_details.string_tag2</code>.
	 */
	public java.lang.String getStringTag2() {
		return (java.lang.String) getValue(21);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_details.string_tag3</code>.
	 */
	public void setStringTag3(java.lang.String value) {
		setValue(22, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_details.string_tag3</code>.
	 */
	public java.lang.String getStringTag3() {
		return (java.lang.String) getValue(22);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_details.string_tag4</code>.
	 */
	public void setStringTag4(java.lang.String value) {
		setValue(23, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_details.string_tag4</code>.
	 */
	public java.lang.String getStringTag4() {
		return (java.lang.String) getValue(23);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_details.string_tag5</code>.
	 */
	public void setStringTag5(java.lang.String value) {
		setValue(24, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_details.string_tag5</code>.
	 */
	public java.lang.String getStringTag5() {
		return (java.lang.String) getValue(24);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_details.service_user_id</code>. customer service staff
	 */
	public void setServiceUserId(java.lang.Long value) {
		setValue(25, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_details.service_user_id</code>. customer service staff
	 */
	public java.lang.Long getServiceUserId() {
		return (java.lang.Long) getValue(25);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_details.namespace_organization_type</code>.
	 */
	public void setNamespaceOrganizationType(java.lang.String value) {
		setValue(26, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_details.namespace_organization_type</code>.
	 */
	public java.lang.String getNamespaceOrganizationType() {
		return (java.lang.String) getValue(26);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_details.namespace_organization_token</code>.
	 */
	public void setNamespaceOrganizationToken(java.lang.String value) {
		setValue(27, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_details.namespace_organization_token</code>.
	 */
	public java.lang.String getNamespaceOrganizationToken() {
		return (java.lang.String) getValue(27);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EhOrganizationDetailsRecord
	 */
	public EhOrganizationDetailsRecord() {
		super(com.everhomes.server.schema.tables.EhOrganizationDetails.EH_ORGANIZATION_DETAILS);
	}

	/**
	 * Create a detached, initialised EhOrganizationDetailsRecord
	 */
	public EhOrganizationDetailsRecord(java.lang.Long id, java.lang.Long organizationId, java.lang.String description, java.lang.String contact, java.lang.String address, java.sql.Timestamp createTime, java.lang.Double longitude, java.lang.Double latitude, java.lang.String geohash, java.lang.String displayName, java.lang.String contactor, java.lang.Long memberCount, java.sql.Timestamp checkinDate, java.lang.String avatar, java.lang.String postUri, java.lang.Long integralTag1, java.lang.Long integralTag2, java.lang.Long integralTag3, java.lang.Long integralTag4, java.lang.Long integralTag5, java.lang.String stringTag1, java.lang.String stringTag2, java.lang.String stringTag3, java.lang.String stringTag4, java.lang.String stringTag5, java.lang.Long serviceUserId, java.lang.String namespaceOrganizationType, java.lang.String namespaceOrganizationToken) {
		super(com.everhomes.server.schema.tables.EhOrganizationDetails.EH_ORGANIZATION_DETAILS);

		setValue(0, id);
		setValue(1, organizationId);
		setValue(2, description);
		setValue(3, contact);
		setValue(4, address);
		setValue(5, createTime);
		setValue(6, longitude);
		setValue(7, latitude);
		setValue(8, geohash);
		setValue(9, displayName);
		setValue(10, contactor);
		setValue(11, memberCount);
		setValue(12, checkinDate);
		setValue(13, avatar);
		setValue(14, postUri);
		setValue(15, integralTag1);
		setValue(16, integralTag2);
		setValue(17, integralTag3);
		setValue(18, integralTag4);
		setValue(19, integralTag5);
		setValue(20, stringTag1);
		setValue(21, stringTag2);
		setValue(22, stringTag3);
		setValue(23, stringTag4);
		setValue(24, stringTag5);
		setValue(25, serviceUserId);
		setValue(26, namespaceOrganizationType);
		setValue(27, namespaceOrganizationToken);
	}
}
