/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhOrganizationOwnerAddressRecord extends org.jooq.impl.UpdatableRecordImpl<com.everhomes.server.schema.tables.records.EhOrganizationOwnerAddressRecord> implements org.jooq.Record6<java.lang.Long, java.lang.Integer, java.lang.Long, java.lang.Long, java.lang.Byte, java.lang.Byte> {

	private static final long serialVersionUID = -1441931270;

	/**
	 * Setter for <code>ehcore.eh_organization_owner_address.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_owner_address.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_owner_address.namespace_id</code>.
	 */
	public void setNamespaceId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_owner_address.namespace_id</code>.
	 */
	public java.lang.Integer getNamespaceId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_owner_address.organization_owner_id</code>.
	 */
	public void setOrganizationOwnerId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_owner_address.organization_owner_id</code>.
	 */
	public java.lang.Long getOrganizationOwnerId() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_owner_address.address_id</code>.
	 */
	public void setAddressId(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_owner_address.address_id</code>.
	 */
	public java.lang.Long getAddressId() {
		return (java.lang.Long) getValue(3);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_owner_address.living_status</code>.
	 */
	public void setLivingStatus(java.lang.Byte value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_owner_address.living_status</code>.
	 */
	public java.lang.Byte getLivingStatus() {
		return (java.lang.Byte) getValue(4);
	}

	/**
	 * Setter for <code>ehcore.eh_organization_owner_address.auth_type</code>. Auth type
	 */
	public void setAuthType(java.lang.Byte value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ehcore.eh_organization_owner_address.auth_type</code>. Auth type
	 */
	public java.lang.Byte getAuthType() {
		return (java.lang.Byte) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Long, java.lang.Integer, java.lang.Long, java.lang.Long, java.lang.Byte, java.lang.Byte> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Long, java.lang.Integer, java.lang.Long, java.lang.Long, java.lang.Byte, java.lang.Byte> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.everhomes.server.schema.tables.EhOrganizationOwnerAddress.EH_ORGANIZATION_OWNER_ADDRESS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.everhomes.server.schema.tables.EhOrganizationOwnerAddress.EH_ORGANIZATION_OWNER_ADDRESS.NAMESPACE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return com.everhomes.server.schema.tables.EhOrganizationOwnerAddress.EH_ORGANIZATION_OWNER_ADDRESS.ORGANIZATION_OWNER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return com.everhomes.server.schema.tables.EhOrganizationOwnerAddress.EH_ORGANIZATION_OWNER_ADDRESS.ADDRESS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field5() {
		return com.everhomes.server.schema.tables.EhOrganizationOwnerAddress.EH_ORGANIZATION_OWNER_ADDRESS.LIVING_STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field6() {
		return com.everhomes.server.schema.tables.EhOrganizationOwnerAddress.EH_ORGANIZATION_OWNER_ADDRESS.AUTH_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getNamespaceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getOrganizationOwnerId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getAddressId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value5() {
		return getLivingStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value6() {
		return getAuthType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhOrganizationOwnerAddressRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhOrganizationOwnerAddressRecord value2(java.lang.Integer value) {
		setNamespaceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhOrganizationOwnerAddressRecord value3(java.lang.Long value) {
		setOrganizationOwnerId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhOrganizationOwnerAddressRecord value4(java.lang.Long value) {
		setAddressId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhOrganizationOwnerAddressRecord value5(java.lang.Byte value) {
		setLivingStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhOrganizationOwnerAddressRecord value6(java.lang.Byte value) {
		setAuthType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhOrganizationOwnerAddressRecord values(java.lang.Long value1, java.lang.Integer value2, java.lang.Long value3, java.lang.Long value4, java.lang.Byte value5, java.lang.Byte value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EhOrganizationOwnerAddressRecord
	 */
	public EhOrganizationOwnerAddressRecord() {
		super(com.everhomes.server.schema.tables.EhOrganizationOwnerAddress.EH_ORGANIZATION_OWNER_ADDRESS);
	}

	/**
	 * Create a detached, initialised EhOrganizationOwnerAddressRecord
	 */
	public EhOrganizationOwnerAddressRecord(java.lang.Long id, java.lang.Integer namespaceId, java.lang.Long organizationOwnerId, java.lang.Long addressId, java.lang.Byte livingStatus, java.lang.Byte authType) {
		super(com.everhomes.server.schema.tables.EhOrganizationOwnerAddress.EH_ORGANIZATION_OWNER_ADDRESS);

		setValue(0, id);
		setValue(1, namespaceId);
		setValue(2, organizationOwnerId);
		setValue(3, addressId);
		setValue(4, livingStatus);
		setValue(5, authType);
	}
}
