/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhPunchLogsRecord extends org.jooq.impl.UpdatableRecordImpl<com.everhomes.server.schema.tables.records.EhPunchLogsRecord> implements org.jooq.Record9<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Double, java.lang.Double, java.sql.Date, java.sql.Timestamp, java.lang.Byte, java.lang.String> {

	private static final long serialVersionUID = -1640795367;

	/**
	 * Setter for <code>ehcore.eh_punch_logs.id</code>. id
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehcore.eh_punch_logs.id</code>. id
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>ehcore.eh_punch_logs.user_id</code>. user's id
	 */
	public void setUserId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehcore.eh_punch_logs.user_id</code>. user's id
	 */
	public java.lang.Long getUserId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>ehcore.eh_punch_logs.enterprise_id</code>. compay id
	 */
	public void setEnterpriseId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ehcore.eh_punch_logs.enterprise_id</code>. compay id
	 */
	public java.lang.Long getEnterpriseId() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>ehcore.eh_punch_logs.longitude</code>.
	 */
	public void setLongitude(java.lang.Double value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ehcore.eh_punch_logs.longitude</code>.
	 */
	public java.lang.Double getLongitude() {
		return (java.lang.Double) getValue(3);
	}

	/**
	 * Setter for <code>ehcore.eh_punch_logs.latitude</code>.
	 */
	public void setLatitude(java.lang.Double value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ehcore.eh_punch_logs.latitude</code>.
	 */
	public java.lang.Double getLatitude() {
		return (java.lang.Double) getValue(4);
	}

	/**
	 * Setter for <code>ehcore.eh_punch_logs.punch_date</code>. user punch date
	 */
	public void setPunchDate(java.sql.Date value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ehcore.eh_punch_logs.punch_date</code>. user punch date
	 */
	public java.sql.Date getPunchDate() {
		return (java.sql.Date) getValue(5);
	}

	/**
	 * Setter for <code>ehcore.eh_punch_logs.punch_time</code>. user check time
	 */
	public void setPunchTime(java.sql.Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ehcore.eh_punch_logs.punch_time</code>. user check time
	 */
	public java.sql.Timestamp getPunchTime() {
		return (java.sql.Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>ehcore.eh_punch_logs.punch_status</code>. 1:Normal, 0:Not in punch area
	 */
	public void setPunchStatus(java.lang.Byte value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ehcore.eh_punch_logs.punch_status</code>. 1:Normal, 0:Not in punch area
	 */
	public java.lang.Byte getPunchStatus() {
		return (java.lang.Byte) getValue(7);
	}

	/**
	 * Setter for <code>ehcore.eh_punch_logs.identification</code>. unique identification for a phone
	 */
	public void setIdentification(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ehcore.eh_punch_logs.identification</code>. unique identification for a phone
	 */
	public java.lang.String getIdentification() {
		return (java.lang.String) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Double, java.lang.Double, java.sql.Date, java.sql.Timestamp, java.lang.Byte, java.lang.String> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Double, java.lang.Double, java.sql.Date, java.sql.Timestamp, java.lang.Byte, java.lang.String> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.everhomes.server.schema.tables.EhPunchLogs.EH_PUNCH_LOGS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.everhomes.server.schema.tables.EhPunchLogs.EH_PUNCH_LOGS.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return com.everhomes.server.schema.tables.EhPunchLogs.EH_PUNCH_LOGS.ENTERPRISE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field4() {
		return com.everhomes.server.schema.tables.EhPunchLogs.EH_PUNCH_LOGS.LONGITUDE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field5() {
		return com.everhomes.server.schema.tables.EhPunchLogs.EH_PUNCH_LOGS.LATITUDE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field6() {
		return com.everhomes.server.schema.tables.EhPunchLogs.EH_PUNCH_LOGS.PUNCH_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return com.everhomes.server.schema.tables.EhPunchLogs.EH_PUNCH_LOGS.PUNCH_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field8() {
		return com.everhomes.server.schema.tables.EhPunchLogs.EH_PUNCH_LOGS.PUNCH_STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return com.everhomes.server.schema.tables.EhPunchLogs.EH_PUNCH_LOGS.IDENTIFICATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getEnterpriseId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value4() {
		return getLongitude();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value5() {
		return getLatitude();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value6() {
		return getPunchDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getPunchTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value8() {
		return getPunchStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getIdentification();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchLogsRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchLogsRecord value2(java.lang.Long value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchLogsRecord value3(java.lang.Long value) {
		setEnterpriseId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchLogsRecord value4(java.lang.Double value) {
		setLongitude(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchLogsRecord value5(java.lang.Double value) {
		setLatitude(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchLogsRecord value6(java.sql.Date value) {
		setPunchDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchLogsRecord value7(java.sql.Timestamp value) {
		setPunchTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchLogsRecord value8(java.lang.Byte value) {
		setPunchStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchLogsRecord value9(java.lang.String value) {
		setIdentification(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchLogsRecord values(java.lang.Long value1, java.lang.Long value2, java.lang.Long value3, java.lang.Double value4, java.lang.Double value5, java.sql.Date value6, java.sql.Timestamp value7, java.lang.Byte value8, java.lang.String value9) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EhPunchLogsRecord
	 */
	public EhPunchLogsRecord() {
		super(com.everhomes.server.schema.tables.EhPunchLogs.EH_PUNCH_LOGS);
	}

	/**
	 * Create a detached, initialised EhPunchLogsRecord
	 */
	public EhPunchLogsRecord(java.lang.Long id, java.lang.Long userId, java.lang.Long enterpriseId, java.lang.Double longitude, java.lang.Double latitude, java.sql.Date punchDate, java.sql.Timestamp punchTime, java.lang.Byte punchStatus, java.lang.String identification) {
		super(com.everhomes.server.schema.tables.EhPunchLogs.EH_PUNCH_LOGS);

		setValue(0, id);
		setValue(1, userId);
		setValue(2, enterpriseId);
		setValue(3, longitude);
		setValue(4, latitude);
		setValue(5, punchDate);
		setValue(6, punchTime);
		setValue(7, punchStatus);
		setValue(8, identification);
	}
}
