/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhPunchWifisRecord extends org.jooq.impl.UpdatableRecordImpl<com.everhomes.server.schema.tables.records.EhPunchWifisRecord> implements org.jooq.Record8<java.lang.Long, java.lang.String, java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.lang.Long, java.sql.Timestamp> {

	private static final long serialVersionUID = 1637540696;

	/**
	 * Setter for <code>ehcore.eh_punch_wifis.id</code>. id of the record
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehcore.eh_punch_wifis.id</code>. id of the record
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>ehcore.eh_punch_wifis.owner_type</code>. owner resource(user/organization) type
	 */
	public void setOwnerType(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehcore.eh_punch_wifis.owner_type</code>. owner resource(user/organization) type
	 */
	public java.lang.String getOwnerType() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>ehcore.eh_punch_wifis.owner_id</code>. owner resource(user/organization) id
	 */
	public void setOwnerId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ehcore.eh_punch_wifis.owner_id</code>. owner resource(user/organization) id
	 */
	public java.lang.Long getOwnerId() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>ehcore.eh_punch_wifis.wifi_rule_id</code>. fk:eh_punch_wifi_rules id
	 */
	public void setWifiRuleId(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ehcore.eh_punch_wifis.wifi_rule_id</code>. fk:eh_punch_wifi_rules id
	 */
	public java.lang.Long getWifiRuleId() {
		return (java.lang.Long) getValue(3);
	}

	/**
	 * Setter for <code>ehcore.eh_punch_wifis.ssid</code>. wifi ssid
	 */
	public void setSsid(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ehcore.eh_punch_wifis.ssid</code>. wifi ssid
	 */
	public java.lang.String getSsid() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>ehcore.eh_punch_wifis.mac_address</code>. wifi mac address
	 */
	public void setMacAddress(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ehcore.eh_punch_wifis.mac_address</code>. wifi mac address
	 */
	public java.lang.String getMacAddress() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>ehcore.eh_punch_wifis.creator_uid</code>.
	 */
	public void setCreatorUid(java.lang.Long value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ehcore.eh_punch_wifis.creator_uid</code>.
	 */
	public java.lang.Long getCreatorUid() {
		return (java.lang.Long) getValue(6);
	}

	/**
	 * Setter for <code>ehcore.eh_punch_wifis.create_time</code>.
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ehcore.eh_punch_wifis.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Long, java.lang.String, java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.lang.Long, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Long, java.lang.String, java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.lang.Long, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.everhomes.server.schema.tables.EhPunchWifis.EH_PUNCH_WIFIS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.everhomes.server.schema.tables.EhPunchWifis.EH_PUNCH_WIFIS.OWNER_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return com.everhomes.server.schema.tables.EhPunchWifis.EH_PUNCH_WIFIS.OWNER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return com.everhomes.server.schema.tables.EhPunchWifis.EH_PUNCH_WIFIS.WIFI_RULE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.everhomes.server.schema.tables.EhPunchWifis.EH_PUNCH_WIFIS.SSID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.everhomes.server.schema.tables.EhPunchWifis.EH_PUNCH_WIFIS.MAC_ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field7() {
		return com.everhomes.server.schema.tables.EhPunchWifis.EH_PUNCH_WIFIS.CREATOR_UID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field8() {
		return com.everhomes.server.schema.tables.EhPunchWifis.EH_PUNCH_WIFIS.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getOwnerType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getOwnerId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getWifiRuleId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getSsid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getMacAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value7() {
		return getCreatorUid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value8() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchWifisRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchWifisRecord value2(java.lang.String value) {
		setOwnerType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchWifisRecord value3(java.lang.Long value) {
		setOwnerId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchWifisRecord value4(java.lang.Long value) {
		setWifiRuleId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchWifisRecord value5(java.lang.String value) {
		setSsid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchWifisRecord value6(java.lang.String value) {
		setMacAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchWifisRecord value7(java.lang.Long value) {
		setCreatorUid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchWifisRecord value8(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchWifisRecord values(java.lang.Long value1, java.lang.String value2, java.lang.Long value3, java.lang.Long value4, java.lang.String value5, java.lang.String value6, java.lang.Long value7, java.sql.Timestamp value8) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EhPunchWifisRecord
	 */
	public EhPunchWifisRecord() {
		super(com.everhomes.server.schema.tables.EhPunchWifis.EH_PUNCH_WIFIS);
	}

	/**
	 * Create a detached, initialised EhPunchWifisRecord
	 */
	public EhPunchWifisRecord(java.lang.Long id, java.lang.String ownerType, java.lang.Long ownerId, java.lang.Long wifiRuleId, java.lang.String ssid, java.lang.String macAddress, java.lang.Long creatorUid, java.sql.Timestamp createTime) {
		super(com.everhomes.server.schema.tables.EhPunchWifis.EH_PUNCH_WIFIS);

		setValue(0, id);
		setValue(1, ownerType);
		setValue(2, ownerId);
		setValue(3, wifiRuleId);
		setValue(4, ssid);
		setValue(5, macAddress);
		setValue(6, creatorUid);
		setValue(7, createTime);
	}
}
