/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhPunchRulesRecord extends org.jooq.impl.UpdatableRecordImpl<com.everhomes.server.schema.tables.records.EhPunchRulesRecord> implements org.jooq.Record15<java.lang.Long, java.lang.Long, java.lang.Byte, java.lang.Integer, java.sql.Time, java.sql.Time, java.sql.Time, java.sql.Time, java.sql.Time, java.sql.Time, java.sql.Time, java.lang.Long, java.sql.Timestamp, java.lang.Long, java.sql.Timestamp> {

	private static final long serialVersionUID = 2051703761;

	/**
	 * Setter for <code>ehcore.eh_punch_rules.id</code>. id
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehcore.eh_punch_rules.id</code>. id
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>ehcore.eh_punch_rules.company_id</code>. rule company id
	 */
	public void setCompanyId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehcore.eh_punch_rules.company_id</code>. rule company id
	 */
	public java.lang.Long getCompanyId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>ehcore.eh_punch_rules.check_type</code>. 0:standard ;  1:flextime
	 */
	public void setCheckType(java.lang.Byte value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ehcore.eh_punch_rules.check_type</code>. 0:standard ;  1:flextime
	 */
	public java.lang.Byte getCheckType() {
		return (java.lang.Byte) getValue(2);
	}

	/**
	 * Setter for <code>ehcore.eh_punch_rules.punch_times</code>. how many times everyday emloyee need punched. 2 times or 4 times
	 */
	public void setPunchTimes(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ehcore.eh_punch_rules.punch_times</code>. how many times everyday emloyee need punched. 2 times or 4 times
	 */
	public java.lang.Integer getPunchTimes() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>ehcore.eh_punch_rules.start_time</code>. type=0:work start time ;1:work start earlist time
	 */
	public void setStartTime(java.sql.Time value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ehcore.eh_punch_rules.start_time</code>. type=0:work start time ;1:work start earlist time
	 */
	public java.sql.Time getStartTime() {
		return (java.sql.Time) getValue(4);
	}

	/**
	 * Setter for <code>ehcore.eh_punch_rules.end_time</code>. type=0:work end time ;1:work start latest time
	 */
	public void setEndTime(java.sql.Time value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ehcore.eh_punch_rules.end_time</code>. type=0:work end time ;1:work start latest time
	 */
	public java.sql.Time getEndTime() {
		return (java.sql.Time) getValue(5);
	}

	/**
	 * Setter for <code>ehcore.eh_punch_rules.noon_end_time</code>.
	 */
	public void setNoonEndTime(java.sql.Time value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ehcore.eh_punch_rules.noon_end_time</code>.
	 */
	public java.sql.Time getNoonEndTime() {
		return (java.sql.Time) getValue(6);
	}

	/**
	 * Setter for <code>ehcore.eh_punch_rules.afternoon_start_time</code>.
	 */
	public void setAfternoonStartTime(java.sql.Time value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ehcore.eh_punch_rules.afternoon_start_time</code>.
	 */
	public java.sql.Time getAfternoonStartTime() {
		return (java.sql.Time) getValue(7);
	}

	/**
	 * Setter for <code>ehcore.eh_punch_rules.work_time</code>. how long must I work
	 */
	public void setWorkTime(java.sql.Time value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ehcore.eh_punch_rules.work_time</code>. how long must I work
	 */
	public java.sql.Time getWorkTime() {
		return (java.sql.Time) getValue(8);
	}

	/**
	 * Setter for <code>ehcore.eh_punch_rules.late_arrive_time</code>. how long can I be late
	 */
	public void setLateArriveTime(java.sql.Time value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>ehcore.eh_punch_rules.late_arrive_time</code>. how long can I be late
	 */
	public java.sql.Time getLateArriveTime() {
		return (java.sql.Time) getValue(9);
	}

	/**
	 * Setter for <code>ehcore.eh_punch_rules.early_leave_time</code>. how long can I be early leave from work
	 */
	public void setEarlyLeaveTime(java.sql.Time value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>ehcore.eh_punch_rules.early_leave_time</code>. how long can I be early leave from work
	 */
	public java.sql.Time getEarlyLeaveTime() {
		return (java.sql.Time) getValue(10);
	}

	/**
	 * Setter for <code>ehcore.eh_punch_rules.create_uid</code>.
	 */
	public void setCreateUid(java.lang.Long value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>ehcore.eh_punch_rules.create_uid</code>.
	 */
	public java.lang.Long getCreateUid() {
		return (java.lang.Long) getValue(11);
	}

	/**
	 * Setter for <code>ehcore.eh_punch_rules.create_time</code>.
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>ehcore.eh_punch_rules.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(12);
	}

	/**
	 * Setter for <code>ehcore.eh_punch_rules.update_uid</code>.
	 */
	public void setUpdateUid(java.lang.Long value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>ehcore.eh_punch_rules.update_uid</code>.
	 */
	public java.lang.Long getUpdateUid() {
		return (java.lang.Long) getValue(13);
	}

	/**
	 * Setter for <code>ehcore.eh_punch_rules.update_time</code>.
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>ehcore.eh_punch_rules.update_time</code>.
	 */
	public java.sql.Timestamp getUpdateTime() {
		return (java.sql.Timestamp) getValue(14);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record15 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row15<java.lang.Long, java.lang.Long, java.lang.Byte, java.lang.Integer, java.sql.Time, java.sql.Time, java.sql.Time, java.sql.Time, java.sql.Time, java.sql.Time, java.sql.Time, java.lang.Long, java.sql.Timestamp, java.lang.Long, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row15) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row15<java.lang.Long, java.lang.Long, java.lang.Byte, java.lang.Integer, java.sql.Time, java.sql.Time, java.sql.Time, java.sql.Time, java.sql.Time, java.sql.Time, java.sql.Time, java.lang.Long, java.sql.Timestamp, java.lang.Long, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row15) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.everhomes.server.schema.tables.EhPunchRules.EH_PUNCH_RULES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.everhomes.server.schema.tables.EhPunchRules.EH_PUNCH_RULES.COMPANY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field3() {
		return com.everhomes.server.schema.tables.EhPunchRules.EH_PUNCH_RULES.CHECK_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return com.everhomes.server.schema.tables.EhPunchRules.EH_PUNCH_RULES.PUNCH_TIMES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Time> field5() {
		return com.everhomes.server.schema.tables.EhPunchRules.EH_PUNCH_RULES.START_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Time> field6() {
		return com.everhomes.server.schema.tables.EhPunchRules.EH_PUNCH_RULES.END_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Time> field7() {
		return com.everhomes.server.schema.tables.EhPunchRules.EH_PUNCH_RULES.NOON_END_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Time> field8() {
		return com.everhomes.server.schema.tables.EhPunchRules.EH_PUNCH_RULES.AFTERNOON_START_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Time> field9() {
		return com.everhomes.server.schema.tables.EhPunchRules.EH_PUNCH_RULES.WORK_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Time> field10() {
		return com.everhomes.server.schema.tables.EhPunchRules.EH_PUNCH_RULES.LATE_ARRIVE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Time> field11() {
		return com.everhomes.server.schema.tables.EhPunchRules.EH_PUNCH_RULES.EARLY_LEAVE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field12() {
		return com.everhomes.server.schema.tables.EhPunchRules.EH_PUNCH_RULES.CREATE_UID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field13() {
		return com.everhomes.server.schema.tables.EhPunchRules.EH_PUNCH_RULES.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field14() {
		return com.everhomes.server.schema.tables.EhPunchRules.EH_PUNCH_RULES.UPDATE_UID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field15() {
		return com.everhomes.server.schema.tables.EhPunchRules.EH_PUNCH_RULES.UPDATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getCompanyId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value3() {
		return getCheckType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getPunchTimes();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Time value5() {
		return getStartTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Time value6() {
		return getEndTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Time value7() {
		return getNoonEndTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Time value8() {
		return getAfternoonStartTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Time value9() {
		return getWorkTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Time value10() {
		return getLateArriveTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Time value11() {
		return getEarlyLeaveTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value12() {
		return getCreateUid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value13() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value14() {
		return getUpdateUid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value15() {
		return getUpdateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchRulesRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchRulesRecord value2(java.lang.Long value) {
		setCompanyId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchRulesRecord value3(java.lang.Byte value) {
		setCheckType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchRulesRecord value4(java.lang.Integer value) {
		setPunchTimes(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchRulesRecord value5(java.sql.Time value) {
		setStartTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchRulesRecord value6(java.sql.Time value) {
		setEndTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchRulesRecord value7(java.sql.Time value) {
		setNoonEndTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchRulesRecord value8(java.sql.Time value) {
		setAfternoonStartTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchRulesRecord value9(java.sql.Time value) {
		setWorkTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchRulesRecord value10(java.sql.Time value) {
		setLateArriveTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchRulesRecord value11(java.sql.Time value) {
		setEarlyLeaveTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchRulesRecord value12(java.lang.Long value) {
		setCreateUid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchRulesRecord value13(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchRulesRecord value14(java.lang.Long value) {
		setUpdateUid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchRulesRecord value15(java.sql.Timestamp value) {
		setUpdateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhPunchRulesRecord values(java.lang.Long value1, java.lang.Long value2, java.lang.Byte value3, java.lang.Integer value4, java.sql.Time value5, java.sql.Time value6, java.sql.Time value7, java.sql.Time value8, java.sql.Time value9, java.sql.Time value10, java.sql.Time value11, java.lang.Long value12, java.sql.Timestamp value13, java.lang.Long value14, java.sql.Timestamp value15) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EhPunchRulesRecord
	 */
	public EhPunchRulesRecord() {
		super(com.everhomes.server.schema.tables.EhPunchRules.EH_PUNCH_RULES);
	}

	/**
	 * Create a detached, initialised EhPunchRulesRecord
	 */
	public EhPunchRulesRecord(java.lang.Long id, java.lang.Long companyId, java.lang.Byte checkType, java.lang.Integer punchTimes, java.sql.Time startTime, java.sql.Time endTime, java.sql.Time noonEndTime, java.sql.Time afternoonStartTime, java.sql.Time workTime, java.sql.Time lateArriveTime, java.sql.Time earlyLeaveTime, java.lang.Long createUid, java.sql.Timestamp createTime, java.lang.Long updateUid, java.sql.Timestamp updateTime) {
		super(com.everhomes.server.schema.tables.EhPunchRules.EH_PUNCH_RULES);

		setValue(0, id);
		setValue(1, companyId);
		setValue(2, checkType);
		setValue(3, punchTimes);
		setValue(4, startTime);
		setValue(5, endTime);
		setValue(6, noonEndTime);
		setValue(7, afternoonStartTime);
		setValue(8, workTime);
		setValue(9, lateArriveTime);
		setValue(10, earlyLeaveTime);
		setValue(11, createUid);
		setValue(12, createTime);
		setValue(13, updateUid);
		setValue(14, updateTime);
	}
}
