/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhRentalSiteItemsRecord extends org.jooq.impl.UpdatableRecordImpl<com.everhomes.server.schema.tables.records.EhRentalSiteItemsRecord> implements org.jooq.Record10<java.lang.Long, java.lang.Long, java.lang.String, java.math.BigDecimal, java.lang.Integer, java.lang.Byte, java.lang.Long, java.sql.Timestamp, java.lang.Long, java.sql.Timestamp> {

	private static final long serialVersionUID = -1042987406;

	/**
	 * Setter for <code>ehcore.eh_rental_site_items.id</code>. id
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehcore.eh_rental_site_items.id</code>. id
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>ehcore.eh_rental_site_items.rental_site_id</code>. rental_site id
	 */
	public void setRentalSiteId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehcore.eh_rental_site_items.rental_site_id</code>. rental_site id
	 */
	public java.lang.Long getRentalSiteId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>ehcore.eh_rental_site_items.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ehcore.eh_rental_site_items.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>ehcore.eh_rental_site_items.price</code>.
	 */
	public void setPrice(java.math.BigDecimal value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ehcore.eh_rental_site_items.price</code>.
	 */
	public java.math.BigDecimal getPrice() {
		return (java.math.BigDecimal) getValue(3);
	}

	/**
	 * Setter for <code>ehcore.eh_rental_site_items.counts</code>. item count
	 */
	public void setCounts(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ehcore.eh_rental_site_items.counts</code>. item count
	 */
	public java.lang.Integer getCounts() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>ehcore.eh_rental_site_items.status</code>.
	 */
	public void setStatus(java.lang.Byte value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ehcore.eh_rental_site_items.status</code>.
	 */
	public java.lang.Byte getStatus() {
		return (java.lang.Byte) getValue(5);
	}

	/**
	 * Setter for <code>ehcore.eh_rental_site_items.creator_uid</code>.
	 */
	public void setCreatorUid(java.lang.Long value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ehcore.eh_rental_site_items.creator_uid</code>.
	 */
	public java.lang.Long getCreatorUid() {
		return (java.lang.Long) getValue(6);
	}

	/**
	 * Setter for <code>ehcore.eh_rental_site_items.create_time</code>.
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ehcore.eh_rental_site_items.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(7);
	}

	/**
	 * Setter for <code>ehcore.eh_rental_site_items.operator_uid</code>.
	 */
	public void setOperatorUid(java.lang.Long value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ehcore.eh_rental_site_items.operator_uid</code>.
	 */
	public java.lang.Long getOperatorUid() {
		return (java.lang.Long) getValue(8);
	}

	/**
	 * Setter for <code>ehcore.eh_rental_site_items.operate_time</code>.
	 */
	public void setOperateTime(java.sql.Timestamp value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>ehcore.eh_rental_site_items.operate_time</code>.
	 */
	public java.sql.Timestamp getOperateTime() {
		return (java.sql.Timestamp) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.lang.Long, java.lang.Long, java.lang.String, java.math.BigDecimal, java.lang.Integer, java.lang.Byte, java.lang.Long, java.sql.Timestamp, java.lang.Long, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.lang.Long, java.lang.Long, java.lang.String, java.math.BigDecimal, java.lang.Integer, java.lang.Byte, java.lang.Long, java.sql.Timestamp, java.lang.Long, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.everhomes.server.schema.tables.EhRentalSiteItems.EH_RENTAL_SITE_ITEMS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.everhomes.server.schema.tables.EhRentalSiteItems.EH_RENTAL_SITE_ITEMS.RENTAL_SITE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.everhomes.server.schema.tables.EhRentalSiteItems.EH_RENTAL_SITE_ITEMS.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigDecimal> field4() {
		return com.everhomes.server.schema.tables.EhRentalSiteItems.EH_RENTAL_SITE_ITEMS.PRICE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return com.everhomes.server.schema.tables.EhRentalSiteItems.EH_RENTAL_SITE_ITEMS.COUNTS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field6() {
		return com.everhomes.server.schema.tables.EhRentalSiteItems.EH_RENTAL_SITE_ITEMS.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field7() {
		return com.everhomes.server.schema.tables.EhRentalSiteItems.EH_RENTAL_SITE_ITEMS.CREATOR_UID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field8() {
		return com.everhomes.server.schema.tables.EhRentalSiteItems.EH_RENTAL_SITE_ITEMS.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field9() {
		return com.everhomes.server.schema.tables.EhRentalSiteItems.EH_RENTAL_SITE_ITEMS.OPERATOR_UID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field10() {
		return com.everhomes.server.schema.tables.EhRentalSiteItems.EH_RENTAL_SITE_ITEMS.OPERATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getRentalSiteId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigDecimal value4() {
		return getPrice();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getCounts();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value6() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value7() {
		return getCreatorUid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value8() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value9() {
		return getOperatorUid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value10() {
		return getOperateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhRentalSiteItemsRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhRentalSiteItemsRecord value2(java.lang.Long value) {
		setRentalSiteId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhRentalSiteItemsRecord value3(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhRentalSiteItemsRecord value4(java.math.BigDecimal value) {
		setPrice(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhRentalSiteItemsRecord value5(java.lang.Integer value) {
		setCounts(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhRentalSiteItemsRecord value6(java.lang.Byte value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhRentalSiteItemsRecord value7(java.lang.Long value) {
		setCreatorUid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhRentalSiteItemsRecord value8(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhRentalSiteItemsRecord value9(java.lang.Long value) {
		setOperatorUid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhRentalSiteItemsRecord value10(java.sql.Timestamp value) {
		setOperateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhRentalSiteItemsRecord values(java.lang.Long value1, java.lang.Long value2, java.lang.String value3, java.math.BigDecimal value4, java.lang.Integer value5, java.lang.Byte value6, java.lang.Long value7, java.sql.Timestamp value8, java.lang.Long value9, java.sql.Timestamp value10) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EhRentalSiteItemsRecord
	 */
	public EhRentalSiteItemsRecord() {
		super(com.everhomes.server.schema.tables.EhRentalSiteItems.EH_RENTAL_SITE_ITEMS);
	}

	/**
	 * Create a detached, initialised EhRentalSiteItemsRecord
	 */
	public EhRentalSiteItemsRecord(java.lang.Long id, java.lang.Long rentalSiteId, java.lang.String name, java.math.BigDecimal price, java.lang.Integer counts, java.lang.Byte status, java.lang.Long creatorUid, java.sql.Timestamp createTime, java.lang.Long operatorUid, java.sql.Timestamp operateTime) {
		super(com.everhomes.server.schema.tables.EhRentalSiteItems.EH_RENTAL_SITE_ITEMS);

		setValue(0, id);
		setValue(1, rentalSiteId);
		setValue(2, name);
		setValue(3, price);
		setValue(4, counts);
		setValue(5, status);
		setValue(6, creatorUid);
		setValue(7, createTime);
		setValue(8, operatorUid);
		setValue(9, operateTime);
	}
}
