/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhRentalBillPaybillMapRecord extends org.jooq.impl.UpdatableRecordImpl<com.everhomes.server.schema.tables.records.EhRentalBillPaybillMapRecord> implements org.jooq.Record8<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.sql.Timestamp, java.lang.Long, java.sql.Timestamp, java.lang.String> {

	private static final long serialVersionUID = 1575919576;

	/**
	 * Setter for <code>ehcore.eh_rental_bill_paybill_map.id</code>. id
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehcore.eh_rental_bill_paybill_map.id</code>. id
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>ehcore.eh_rental_bill_paybill_map.rental_bill_id</code>.
	 */
	public void setRentalBillId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehcore.eh_rental_bill_paybill_map.rental_bill_id</code>.
	 */
	public java.lang.Long getRentalBillId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>ehcore.eh_rental_bill_paybill_map.online_pay_bill_id</code>.
	 */
	public void setOnlinePayBillId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ehcore.eh_rental_bill_paybill_map.online_pay_bill_id</code>.
	 */
	public java.lang.Long getOnlinePayBillId() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>ehcore.eh_rental_bill_paybill_map.creator_uid</code>.
	 */
	public void setCreatorUid(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ehcore.eh_rental_bill_paybill_map.creator_uid</code>.
	 */
	public java.lang.Long getCreatorUid() {
		return (java.lang.Long) getValue(3);
	}

	/**
	 * Setter for <code>ehcore.eh_rental_bill_paybill_map.create_time</code>.
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ehcore.eh_rental_bill_paybill_map.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>ehcore.eh_rental_bill_paybill_map.operator_uid</code>.
	 */
	public void setOperatorUid(java.lang.Long value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ehcore.eh_rental_bill_paybill_map.operator_uid</code>.
	 */
	public java.lang.Long getOperatorUid() {
		return (java.lang.Long) getValue(5);
	}

	/**
	 * Setter for <code>ehcore.eh_rental_bill_paybill_map.operate_time</code>.
	 */
	public void setOperateTime(java.sql.Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ehcore.eh_rental_bill_paybill_map.operate_time</code>.
	 */
	public java.sql.Timestamp getOperateTime() {
		return (java.sql.Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>ehcore.eh_rental_bill_paybill_map.vendor_type</code>. 支付方式,10001-支付宝，10002-微信
	 */
	public void setVendorType(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ehcore.eh_rental_bill_paybill_map.vendor_type</code>. 支付方式,10001-支付宝，10002-微信
	 */
	public java.lang.String getVendorType() {
		return (java.lang.String) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.sql.Timestamp, java.lang.Long, java.sql.Timestamp, java.lang.String> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long, java.sql.Timestamp, java.lang.Long, java.sql.Timestamp, java.lang.String> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.everhomes.server.schema.tables.EhRentalBillPaybillMap.EH_RENTAL_BILL_PAYBILL_MAP.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.everhomes.server.schema.tables.EhRentalBillPaybillMap.EH_RENTAL_BILL_PAYBILL_MAP.RENTAL_BILL_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return com.everhomes.server.schema.tables.EhRentalBillPaybillMap.EH_RENTAL_BILL_PAYBILL_MAP.ONLINE_PAY_BILL_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return com.everhomes.server.schema.tables.EhRentalBillPaybillMap.EH_RENTAL_BILL_PAYBILL_MAP.CREATOR_UID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return com.everhomes.server.schema.tables.EhRentalBillPaybillMap.EH_RENTAL_BILL_PAYBILL_MAP.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field6() {
		return com.everhomes.server.schema.tables.EhRentalBillPaybillMap.EH_RENTAL_BILL_PAYBILL_MAP.OPERATOR_UID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return com.everhomes.server.schema.tables.EhRentalBillPaybillMap.EH_RENTAL_BILL_PAYBILL_MAP.OPERATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.everhomes.server.schema.tables.EhRentalBillPaybillMap.EH_RENTAL_BILL_PAYBILL_MAP.VENDOR_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getRentalBillId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getOnlinePayBillId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getCreatorUid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value6() {
		return getOperatorUid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getOperateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getVendorType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhRentalBillPaybillMapRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhRentalBillPaybillMapRecord value2(java.lang.Long value) {
		setRentalBillId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhRentalBillPaybillMapRecord value3(java.lang.Long value) {
		setOnlinePayBillId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhRentalBillPaybillMapRecord value4(java.lang.Long value) {
		setCreatorUid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhRentalBillPaybillMapRecord value5(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhRentalBillPaybillMapRecord value6(java.lang.Long value) {
		setOperatorUid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhRentalBillPaybillMapRecord value7(java.sql.Timestamp value) {
		setOperateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhRentalBillPaybillMapRecord value8(java.lang.String value) {
		setVendorType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhRentalBillPaybillMapRecord values(java.lang.Long value1, java.lang.Long value2, java.lang.Long value3, java.lang.Long value4, java.sql.Timestamp value5, java.lang.Long value6, java.sql.Timestamp value7, java.lang.String value8) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EhRentalBillPaybillMapRecord
	 */
	public EhRentalBillPaybillMapRecord() {
		super(com.everhomes.server.schema.tables.EhRentalBillPaybillMap.EH_RENTAL_BILL_PAYBILL_MAP);
	}

	/**
	 * Create a detached, initialised EhRentalBillPaybillMapRecord
	 */
	public EhRentalBillPaybillMapRecord(java.lang.Long id, java.lang.Long rentalBillId, java.lang.Long onlinePayBillId, java.lang.Long creatorUid, java.sql.Timestamp createTime, java.lang.Long operatorUid, java.sql.Timestamp operateTime, java.lang.String vendorType) {
		super(com.everhomes.server.schema.tables.EhRentalBillPaybillMap.EH_RENTAL_BILL_PAYBILL_MAP);

		setValue(0, id);
		setValue(1, rentalBillId);
		setValue(2, onlinePayBillId);
		setValue(3, creatorUid);
		setValue(4, createTime);
		setValue(5, operatorUid);
		setValue(6, operateTime);
		setValue(7, vendorType);
	}
}
