/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhServiceModuleScopesRecord extends org.jooq.impl.UpdatableRecordImpl<com.everhomes.server.schema.tables.records.EhServiceModuleScopesRecord> implements org.jooq.Record8<java.lang.Long, java.lang.Integer, java.lang.Long, java.lang.String, java.lang.String, java.lang.Long, java.lang.Integer, java.lang.Byte> {

	private static final long serialVersionUID = -141961353;

	/**
	 * Setter for <code>ehcore.eh_service_module_scopes.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehcore.eh_service_module_scopes.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>ehcore.eh_service_module_scopes.namespace_id</code>.
	 */
	public void setNamespaceId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehcore.eh_service_module_scopes.namespace_id</code>.
	 */
	public java.lang.Integer getNamespaceId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>ehcore.eh_service_module_scopes.module_id</code>.
	 */
	public void setModuleId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ehcore.eh_service_module_scopes.module_id</code>.
	 */
	public java.lang.Long getModuleId() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>ehcore.eh_service_module_scopes.module_name</code>.
	 */
	public void setModuleName(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ehcore.eh_service_module_scopes.module_name</code>.
	 */
	public java.lang.String getModuleName() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>ehcore.eh_service_module_scopes.owner_type</code>.
	 */
	public void setOwnerType(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ehcore.eh_service_module_scopes.owner_type</code>.
	 */
	public java.lang.String getOwnerType() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>ehcore.eh_service_module_scopes.owner_id</code>.
	 */
	public void setOwnerId(java.lang.Long value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ehcore.eh_service_module_scopes.owner_id</code>.
	 */
	public java.lang.Long getOwnerId() {
		return (java.lang.Long) getValue(5);
	}

	/**
	 * Setter for <code>ehcore.eh_service_module_scopes.default_order</code>. order number
	 */
	public void setDefaultOrder(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ehcore.eh_service_module_scopes.default_order</code>. order number
	 */
	public java.lang.Integer getDefaultOrder() {
		return (java.lang.Integer) getValue(6);
	}

	/**
	 * Setter for <code>ehcore.eh_service_module_scopes.apply_policy</code>. 0: delete , 1: override, 2: revert
	 */
	public void setApplyPolicy(java.lang.Byte value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ehcore.eh_service_module_scopes.apply_policy</code>. 0: delete , 1: override, 2: revert
	 */
	public java.lang.Byte getApplyPolicy() {
		return (java.lang.Byte) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Long, java.lang.Integer, java.lang.Long, java.lang.String, java.lang.String, java.lang.Long, java.lang.Integer, java.lang.Byte> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Long, java.lang.Integer, java.lang.Long, java.lang.String, java.lang.String, java.lang.Long, java.lang.Integer, java.lang.Byte> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.everhomes.server.schema.tables.EhServiceModuleScopes.EH_SERVICE_MODULE_SCOPES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.everhomes.server.schema.tables.EhServiceModuleScopes.EH_SERVICE_MODULE_SCOPES.NAMESPACE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return com.everhomes.server.schema.tables.EhServiceModuleScopes.EH_SERVICE_MODULE_SCOPES.MODULE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.everhomes.server.schema.tables.EhServiceModuleScopes.EH_SERVICE_MODULE_SCOPES.MODULE_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.everhomes.server.schema.tables.EhServiceModuleScopes.EH_SERVICE_MODULE_SCOPES.OWNER_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field6() {
		return com.everhomes.server.schema.tables.EhServiceModuleScopes.EH_SERVICE_MODULE_SCOPES.OWNER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return com.everhomes.server.schema.tables.EhServiceModuleScopes.EH_SERVICE_MODULE_SCOPES.DEFAULT_ORDER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field8() {
		return com.everhomes.server.schema.tables.EhServiceModuleScopes.EH_SERVICE_MODULE_SCOPES.APPLY_POLICY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getNamespaceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getModuleId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getModuleName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getOwnerType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value6() {
		return getOwnerId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getDefaultOrder();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value8() {
		return getApplyPolicy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhServiceModuleScopesRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhServiceModuleScopesRecord value2(java.lang.Integer value) {
		setNamespaceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhServiceModuleScopesRecord value3(java.lang.Long value) {
		setModuleId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhServiceModuleScopesRecord value4(java.lang.String value) {
		setModuleName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhServiceModuleScopesRecord value5(java.lang.String value) {
		setOwnerType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhServiceModuleScopesRecord value6(java.lang.Long value) {
		setOwnerId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhServiceModuleScopesRecord value7(java.lang.Integer value) {
		setDefaultOrder(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhServiceModuleScopesRecord value8(java.lang.Byte value) {
		setApplyPolicy(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhServiceModuleScopesRecord values(java.lang.Long value1, java.lang.Integer value2, java.lang.Long value3, java.lang.String value4, java.lang.String value5, java.lang.Long value6, java.lang.Integer value7, java.lang.Byte value8) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EhServiceModuleScopesRecord
	 */
	public EhServiceModuleScopesRecord() {
		super(com.everhomes.server.schema.tables.EhServiceModuleScopes.EH_SERVICE_MODULE_SCOPES);
	}

	/**
	 * Create a detached, initialised EhServiceModuleScopesRecord
	 */
	public EhServiceModuleScopesRecord(java.lang.Long id, java.lang.Integer namespaceId, java.lang.Long moduleId, java.lang.String moduleName, java.lang.String ownerType, java.lang.Long ownerId, java.lang.Integer defaultOrder, java.lang.Byte applyPolicy) {
		super(com.everhomes.server.schema.tables.EhServiceModuleScopes.EH_SERVICE_MODULE_SCOPES);

		setValue(0, id);
		setValue(1, namespaceId);
		setValue(2, moduleId);
		setValue(3, moduleName);
		setValue(4, ownerType);
		setValue(5, ownerId);
		setValue(6, defaultOrder);
		setValue(7, applyPolicy);
	}
}
