/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhTerminalAppVersionActivesRecord extends org.jooq.impl.UpdatableRecordImpl<com.everhomes.server.schema.tables.records.EhTerminalAppVersionActivesRecord> implements org.jooq.Record7<java.lang.Long, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp> {

	private static final long serialVersionUID = -1800280275;

	/**
	 * Setter for <code>ehcore.eh_terminal_app_version_actives.id</code>. id of the record
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehcore.eh_terminal_app_version_actives.id</code>. id of the record
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>ehcore.eh_terminal_app_version_actives.namespace_id</code>.
	 */
	public void setNamespaceId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehcore.eh_terminal_app_version_actives.namespace_id</code>.
	 */
	public java.lang.Integer getNamespaceId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>ehcore.eh_terminal_app_version_actives.app_version_realm</code>.
	 */
	public void setAppVersionRealm(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ehcore.eh_terminal_app_version_actives.app_version_realm</code>.
	 */
	public java.lang.String getAppVersionRealm() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>ehcore.eh_terminal_app_version_actives.app_version</code>.
	 */
	public void setAppVersion(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ehcore.eh_terminal_app_version_actives.app_version</code>.
	 */
	public java.lang.String getAppVersion() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>ehcore.eh_terminal_app_version_actives.imei_number</code>.
	 */
	public void setImeiNumber(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ehcore.eh_terminal_app_version_actives.imei_number</code>.
	 */
	public java.lang.String getImeiNumber() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>ehcore.eh_terminal_app_version_actives.date</code>.
	 */
	public void setDate(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ehcore.eh_terminal_app_version_actives.date</code>.
	 */
	public java.lang.String getDate() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>ehcore.eh_terminal_app_version_actives.create_time</code>.
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ehcore.eh_terminal_app_version_actives.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Long, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Long, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.everhomes.server.schema.tables.EhTerminalAppVersionActives.EH_TERMINAL_APP_VERSION_ACTIVES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.everhomes.server.schema.tables.EhTerminalAppVersionActives.EH_TERMINAL_APP_VERSION_ACTIVES.NAMESPACE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.everhomes.server.schema.tables.EhTerminalAppVersionActives.EH_TERMINAL_APP_VERSION_ACTIVES.APP_VERSION_REALM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.everhomes.server.schema.tables.EhTerminalAppVersionActives.EH_TERMINAL_APP_VERSION_ACTIVES.APP_VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.everhomes.server.schema.tables.EhTerminalAppVersionActives.EH_TERMINAL_APP_VERSION_ACTIVES.IMEI_NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.everhomes.server.schema.tables.EhTerminalAppVersionActives.EH_TERMINAL_APP_VERSION_ACTIVES.DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return com.everhomes.server.schema.tables.EhTerminalAppVersionActives.EH_TERMINAL_APP_VERSION_ACTIVES.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getNamespaceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getAppVersionRealm();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getAppVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getImeiNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhTerminalAppVersionActivesRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhTerminalAppVersionActivesRecord value2(java.lang.Integer value) {
		setNamespaceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhTerminalAppVersionActivesRecord value3(java.lang.String value) {
		setAppVersionRealm(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhTerminalAppVersionActivesRecord value4(java.lang.String value) {
		setAppVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhTerminalAppVersionActivesRecord value5(java.lang.String value) {
		setImeiNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhTerminalAppVersionActivesRecord value6(java.lang.String value) {
		setDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhTerminalAppVersionActivesRecord value7(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhTerminalAppVersionActivesRecord values(java.lang.Long value1, java.lang.Integer value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.sql.Timestamp value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EhTerminalAppVersionActivesRecord
	 */
	public EhTerminalAppVersionActivesRecord() {
		super(com.everhomes.server.schema.tables.EhTerminalAppVersionActives.EH_TERMINAL_APP_VERSION_ACTIVES);
	}

	/**
	 * Create a detached, initialised EhTerminalAppVersionActivesRecord
	 */
	public EhTerminalAppVersionActivesRecord(java.lang.Long id, java.lang.Integer namespaceId, java.lang.String appVersionRealm, java.lang.String appVersion, java.lang.String imeiNumber, java.lang.String date, java.sql.Timestamp createTime) {
		super(com.everhomes.server.schema.tables.EhTerminalAppVersionActives.EH_TERMINAL_APP_VERSION_ACTIVES);

		setValue(0, id);
		setValue(1, namespaceId);
		setValue(2, appVersionRealm);
		setValue(3, appVersion);
		setValue(4, imeiNumber);
		setValue(5, date);
		setValue(6, createTime);
	}
}
