/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhTerminalHourStatisticsRecord extends org.jooq.impl.UpdatableRecordImpl<com.everhomes.server.schema.tables.records.EhTerminalHourStatisticsRecord> implements org.jooq.Record11<java.lang.Long, java.lang.Integer, java.lang.Long, java.lang.Long, java.math.BigDecimal, java.math.BigDecimal, java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.sql.Timestamp> {

	private static final long serialVersionUID = 1959473926;

	/**
	 * Setter for <code>ehcore.eh_terminal_hour_statistics.id</code>. id of the record
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehcore.eh_terminal_hour_statistics.id</code>. id of the record
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>ehcore.eh_terminal_hour_statistics.namespace_id</code>.
	 */
	public void setNamespaceId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehcore.eh_terminal_hour_statistics.namespace_id</code>.
	 */
	public java.lang.Integer getNamespaceId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>ehcore.eh_terminal_hour_statistics.new_user_number</code>. number of new users
	 */
	public void setNewUserNumber(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ehcore.eh_terminal_hour_statistics.new_user_number</code>. number of new users
	 */
	public java.lang.Long getNewUserNumber() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>ehcore.eh_terminal_hour_statistics.active_user_number</code>. number of active users
	 */
	public void setActiveUserNumber(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ehcore.eh_terminal_hour_statistics.active_user_number</code>. number of active users
	 */
	public java.lang.Long getActiveUserNumber() {
		return (java.lang.Long) getValue(3);
	}

	/**
	 * Setter for <code>ehcore.eh_terminal_hour_statistics.change_rate</code>. today compared to yesterdays rate of change.
	 */
	public void setChangeRate(java.math.BigDecimal value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ehcore.eh_terminal_hour_statistics.change_rate</code>. today compared to yesterdays rate of change.
	 */
	public java.math.BigDecimal getChangeRate() {
		return (java.math.BigDecimal) getValue(4);
	}

	/**
	 * Setter for <code>ehcore.eh_terminal_hour_statistics.active_rate</code>. active_user_number/accumulative_user_number
	 */
	public void setActiveRate(java.math.BigDecimal value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ehcore.eh_terminal_hour_statistics.active_rate</code>. active_user_number/accumulative_user_number
	 */
	public java.math.BigDecimal getActiveRate() {
		return (java.math.BigDecimal) getValue(5);
	}

	/**
	 * Setter for <code>ehcore.eh_terminal_hour_statistics.start_number</code>. number of starts
	 */
	public void setStartNumber(java.lang.Long value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ehcore.eh_terminal_hour_statistics.start_number</code>. number of starts
	 */
	public java.lang.Long getStartNumber() {
		return (java.lang.Long) getValue(6);
	}

	/**
	 * Setter for <code>ehcore.eh_terminal_hour_statistics.cumulative_user_number</code>. cumulative number of users
	 */
	public void setCumulativeUserNumber(java.lang.Long value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ehcore.eh_terminal_hour_statistics.cumulative_user_number</code>. cumulative number of users
	 */
	public java.lang.Long getCumulativeUserNumber() {
		return (java.lang.Long) getValue(7);
	}

	/**
	 * Setter for <code>ehcore.eh_terminal_hour_statistics.date</code>.
	 */
	public void setDate(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ehcore.eh_terminal_hour_statistics.date</code>.
	 */
	public java.lang.String getDate() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>ehcore.eh_terminal_hour_statistics.hour</code>.
	 */
	public void setHour(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>ehcore.eh_terminal_hour_statistics.hour</code>.
	 */
	public java.lang.String getHour() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>ehcore.eh_terminal_hour_statistics.create_time</code>.
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>ehcore.eh_terminal_hour_statistics.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.lang.Long, java.lang.Integer, java.lang.Long, java.lang.Long, java.math.BigDecimal, java.math.BigDecimal, java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.lang.Long, java.lang.Integer, java.lang.Long, java.lang.Long, java.math.BigDecimal, java.math.BigDecimal, java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.everhomes.server.schema.tables.EhTerminalHourStatistics.EH_TERMINAL_HOUR_STATISTICS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.everhomes.server.schema.tables.EhTerminalHourStatistics.EH_TERMINAL_HOUR_STATISTICS.NAMESPACE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return com.everhomes.server.schema.tables.EhTerminalHourStatistics.EH_TERMINAL_HOUR_STATISTICS.NEW_USER_NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return com.everhomes.server.schema.tables.EhTerminalHourStatistics.EH_TERMINAL_HOUR_STATISTICS.ACTIVE_USER_NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigDecimal> field5() {
		return com.everhomes.server.schema.tables.EhTerminalHourStatistics.EH_TERMINAL_HOUR_STATISTICS.CHANGE_RATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigDecimal> field6() {
		return com.everhomes.server.schema.tables.EhTerminalHourStatistics.EH_TERMINAL_HOUR_STATISTICS.ACTIVE_RATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field7() {
		return com.everhomes.server.schema.tables.EhTerminalHourStatistics.EH_TERMINAL_HOUR_STATISTICS.START_NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field8() {
		return com.everhomes.server.schema.tables.EhTerminalHourStatistics.EH_TERMINAL_HOUR_STATISTICS.CUMULATIVE_USER_NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return com.everhomes.server.schema.tables.EhTerminalHourStatistics.EH_TERMINAL_HOUR_STATISTICS.DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return com.everhomes.server.schema.tables.EhTerminalHourStatistics.EH_TERMINAL_HOUR_STATISTICS.HOUR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field11() {
		return com.everhomes.server.schema.tables.EhTerminalHourStatistics.EH_TERMINAL_HOUR_STATISTICS.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getNamespaceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getNewUserNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getActiveUserNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigDecimal value5() {
		return getChangeRate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigDecimal value6() {
		return getActiveRate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value7() {
		return getStartNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value8() {
		return getCumulativeUserNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getHour();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value11() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhTerminalHourStatisticsRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhTerminalHourStatisticsRecord value2(java.lang.Integer value) {
		setNamespaceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhTerminalHourStatisticsRecord value3(java.lang.Long value) {
		setNewUserNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhTerminalHourStatisticsRecord value4(java.lang.Long value) {
		setActiveUserNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhTerminalHourStatisticsRecord value5(java.math.BigDecimal value) {
		setChangeRate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhTerminalHourStatisticsRecord value6(java.math.BigDecimal value) {
		setActiveRate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhTerminalHourStatisticsRecord value7(java.lang.Long value) {
		setStartNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhTerminalHourStatisticsRecord value8(java.lang.Long value) {
		setCumulativeUserNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhTerminalHourStatisticsRecord value9(java.lang.String value) {
		setDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhTerminalHourStatisticsRecord value10(java.lang.String value) {
		setHour(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhTerminalHourStatisticsRecord value11(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhTerminalHourStatisticsRecord values(java.lang.Long value1, java.lang.Integer value2, java.lang.Long value3, java.lang.Long value4, java.math.BigDecimal value5, java.math.BigDecimal value6, java.lang.Long value7, java.lang.Long value8, java.lang.String value9, java.lang.String value10, java.sql.Timestamp value11) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EhTerminalHourStatisticsRecord
	 */
	public EhTerminalHourStatisticsRecord() {
		super(com.everhomes.server.schema.tables.EhTerminalHourStatistics.EH_TERMINAL_HOUR_STATISTICS);
	}

	/**
	 * Create a detached, initialised EhTerminalHourStatisticsRecord
	 */
	public EhTerminalHourStatisticsRecord(java.lang.Long id, java.lang.Integer namespaceId, java.lang.Long newUserNumber, java.lang.Long activeUserNumber, java.math.BigDecimal changeRate, java.math.BigDecimal activeRate, java.lang.Long startNumber, java.lang.Long cumulativeUserNumber, java.lang.String date, java.lang.String hour, java.sql.Timestamp createTime) {
		super(com.everhomes.server.schema.tables.EhTerminalHourStatistics.EH_TERMINAL_HOUR_STATISTICS);

		setValue(0, id);
		setValue(1, namespaceId);
		setValue(2, newUserNumber);
		setValue(3, activeUserNumber);
		setValue(4, changeRate);
		setValue(5, activeRate);
		setValue(6, startNumber);
		setValue(7, cumulativeUserNumber);
		setValue(8, date);
		setValue(9, hour);
		setValue(10, createTime);
	}
}
