/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhUserActivitiesRecord extends org.jooq.impl.UpdatableRecordImpl<com.everhomes.server.schema.tables.records.EhUserActivitiesRecord> implements org.jooq.Record20<java.lang.Long, java.lang.Long, java.lang.Byte, java.lang.Long, java.lang.String, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.Byte, java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.Long, java.lang.Long, java.sql.Timestamp, java.lang.Integer, java.lang.String> {

	private static final long serialVersionUID = -1390747688;

	/**
	 * Setter for <code>ehcore.eh_user_activities.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_activities.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>ehcore.eh_user_activities.uid</code>.
	 */
	public void setUid(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_activities.uid</code>.
	 */
	public java.lang.Long getUid() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>ehcore.eh_user_activities.activity_type</code>.
	 */
	public void setActivityType(java.lang.Byte value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_activities.activity_type</code>.
	 */
	public java.lang.Byte getActivityType() {
		return (java.lang.Byte) getValue(2);
	}

	/**
	 * Setter for <code>ehcore.eh_user_activities.app_version_code</code>.
	 */
	public void setAppVersionCode(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_activities.app_version_code</code>.
	 */
	public java.lang.Long getAppVersionCode() {
		return (java.lang.Long) getValue(3);
	}

	/**
	 * Setter for <code>ehcore.eh_user_activities.app_version_name</code>.
	 */
	public void setAppVersionName(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_activities.app_version_name</code>.
	 */
	public java.lang.String getAppVersionName() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>ehcore.eh_user_activities.channel_id</code>.
	 */
	public void setChannelId(java.lang.Long value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_activities.channel_id</code>.
	 */
	public java.lang.Long getChannelId() {
		return (java.lang.Long) getValue(5);
	}

	/**
	 * Setter for <code>ehcore.eh_user_activities.imei_number</code>.
	 */
	public void setImeiNumber(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_activities.imei_number</code>.
	 */
	public java.lang.String getImeiNumber() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>ehcore.eh_user_activities.device_type</code>.
	 */
	public void setDeviceType(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_activities.device_type</code>.
	 */
	public java.lang.String getDeviceType() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>ehcore.eh_user_activities.os_info</code>.
	 */
	public void setOsInfo(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_activities.os_info</code>.
	 */
	public java.lang.String getOsInfo() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>ehcore.eh_user_activities.os_type</code>.
	 */
	public void setOsType(java.lang.Byte value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_activities.os_type</code>.
	 */
	public java.lang.Byte getOsType() {
		return (java.lang.Byte) getValue(9);
	}

	/**
	 * Setter for <code>ehcore.eh_user_activities.mkt_data_version</code>.
	 */
	public void setMktDataVersion(java.lang.Long value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_activities.mkt_data_version</code>.
	 */
	public java.lang.Long getMktDataVersion() {
		return (java.lang.Long) getValue(10);
	}

	/**
	 * Setter for <code>ehcore.eh_user_activities.report_config_version</code>.
	 */
	public void setReportConfigVersion(java.lang.Long value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_activities.report_config_version</code>.
	 */
	public java.lang.Long getReportConfigVersion() {
		return (java.lang.Long) getValue(11);
	}

	/**
	 * Setter for <code>ehcore.eh_user_activities.internal_ip</code>.
	 */
	public void setInternalIp(java.lang.String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_activities.internal_ip</code>.
	 */
	public java.lang.String getInternalIp() {
		return (java.lang.String) getValue(12);
	}

	/**
	 * Setter for <code>ehcore.eh_user_activities.external_ip</code>.
	 */
	public void setExternalIp(java.lang.String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_activities.external_ip</code>.
	 */
	public java.lang.String getExternalIp() {
		return (java.lang.String) getValue(13);
	}

	/**
	 * Setter for <code>ehcore.eh_user_activities.user_agent</code>.
	 */
	public void setUserAgent(java.lang.String value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_activities.user_agent</code>.
	 */
	public java.lang.String getUserAgent() {
		return (java.lang.String) getValue(14);
	}

	/**
	 * Setter for <code>ehcore.eh_user_activities.collect_time_ms</code>.
	 */
	public void setCollectTimeMs(java.lang.Long value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_activities.collect_time_ms</code>.
	 */
	public java.lang.Long getCollectTimeMs() {
		return (java.lang.Long) getValue(15);
	}

	/**
	 * Setter for <code>ehcore.eh_user_activities.report_time_ms</code>.
	 */
	public void setReportTimeMs(java.lang.Long value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_activities.report_time_ms</code>.
	 */
	public java.lang.Long getReportTimeMs() {
		return (java.lang.Long) getValue(16);
	}

	/**
	 * Setter for <code>ehcore.eh_user_activities.create_time</code>.
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_activities.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(17);
	}

	/**
	 * Setter for <code>ehcore.eh_user_activities.namespace_id</code>.
	 */
	public void setNamespaceId(java.lang.Integer value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_activities.namespace_id</code>.
	 */
	public java.lang.Integer getNamespaceId() {
		return (java.lang.Integer) getValue(18);
	}

	/**
	 * Setter for <code>ehcore.eh_user_activities.version_realm</code>.
	 */
	public void setVersionRealm(java.lang.String value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_activities.version_realm</code>.
	 */
	public java.lang.String getVersionRealm() {
		return (java.lang.String) getValue(19);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record20 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row20<java.lang.Long, java.lang.Long, java.lang.Byte, java.lang.Long, java.lang.String, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.Byte, java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.Long, java.lang.Long, java.sql.Timestamp, java.lang.Integer, java.lang.String> fieldsRow() {
		return (org.jooq.Row20) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row20<java.lang.Long, java.lang.Long, java.lang.Byte, java.lang.Long, java.lang.String, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.Byte, java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.Long, java.lang.Long, java.sql.Timestamp, java.lang.Integer, java.lang.String> valuesRow() {
		return (org.jooq.Row20) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.everhomes.server.schema.tables.EhUserActivities.EH_USER_ACTIVITIES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.everhomes.server.schema.tables.EhUserActivities.EH_USER_ACTIVITIES.UID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field3() {
		return com.everhomes.server.schema.tables.EhUserActivities.EH_USER_ACTIVITIES.ACTIVITY_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return com.everhomes.server.schema.tables.EhUserActivities.EH_USER_ACTIVITIES.APP_VERSION_CODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.everhomes.server.schema.tables.EhUserActivities.EH_USER_ACTIVITIES.APP_VERSION_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field6() {
		return com.everhomes.server.schema.tables.EhUserActivities.EH_USER_ACTIVITIES.CHANNEL_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.everhomes.server.schema.tables.EhUserActivities.EH_USER_ACTIVITIES.IMEI_NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.everhomes.server.schema.tables.EhUserActivities.EH_USER_ACTIVITIES.DEVICE_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return com.everhomes.server.schema.tables.EhUserActivities.EH_USER_ACTIVITIES.OS_INFO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field10() {
		return com.everhomes.server.schema.tables.EhUserActivities.EH_USER_ACTIVITIES.OS_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field11() {
		return com.everhomes.server.schema.tables.EhUserActivities.EH_USER_ACTIVITIES.MKT_DATA_VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field12() {
		return com.everhomes.server.schema.tables.EhUserActivities.EH_USER_ACTIVITIES.REPORT_CONFIG_VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field13() {
		return com.everhomes.server.schema.tables.EhUserActivities.EH_USER_ACTIVITIES.INTERNAL_IP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field14() {
		return com.everhomes.server.schema.tables.EhUserActivities.EH_USER_ACTIVITIES.EXTERNAL_IP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field15() {
		return com.everhomes.server.schema.tables.EhUserActivities.EH_USER_ACTIVITIES.USER_AGENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field16() {
		return com.everhomes.server.schema.tables.EhUserActivities.EH_USER_ACTIVITIES.COLLECT_TIME_MS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field17() {
		return com.everhomes.server.schema.tables.EhUserActivities.EH_USER_ACTIVITIES.REPORT_TIME_MS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field18() {
		return com.everhomes.server.schema.tables.EhUserActivities.EH_USER_ACTIVITIES.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field19() {
		return com.everhomes.server.schema.tables.EhUserActivities.EH_USER_ACTIVITIES.NAMESPACE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field20() {
		return com.everhomes.server.schema.tables.EhUserActivities.EH_USER_ACTIVITIES.VERSION_REALM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getUid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value3() {
		return getActivityType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getAppVersionCode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getAppVersionName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value6() {
		return getChannelId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getImeiNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getDeviceType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getOsInfo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value10() {
		return getOsType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value11() {
		return getMktDataVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value12() {
		return getReportConfigVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value13() {
		return getInternalIp();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value14() {
		return getExternalIp();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value15() {
		return getUserAgent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value16() {
		return getCollectTimeMs();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value17() {
		return getReportTimeMs();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value18() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value19() {
		return getNamespaceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value20() {
		return getVersionRealm();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserActivitiesRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserActivitiesRecord value2(java.lang.Long value) {
		setUid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserActivitiesRecord value3(java.lang.Byte value) {
		setActivityType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserActivitiesRecord value4(java.lang.Long value) {
		setAppVersionCode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserActivitiesRecord value5(java.lang.String value) {
		setAppVersionName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserActivitiesRecord value6(java.lang.Long value) {
		setChannelId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserActivitiesRecord value7(java.lang.String value) {
		setImeiNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserActivitiesRecord value8(java.lang.String value) {
		setDeviceType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserActivitiesRecord value9(java.lang.String value) {
		setOsInfo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserActivitiesRecord value10(java.lang.Byte value) {
		setOsType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserActivitiesRecord value11(java.lang.Long value) {
		setMktDataVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserActivitiesRecord value12(java.lang.Long value) {
		setReportConfigVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserActivitiesRecord value13(java.lang.String value) {
		setInternalIp(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserActivitiesRecord value14(java.lang.String value) {
		setExternalIp(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserActivitiesRecord value15(java.lang.String value) {
		setUserAgent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserActivitiesRecord value16(java.lang.Long value) {
		setCollectTimeMs(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserActivitiesRecord value17(java.lang.Long value) {
		setReportTimeMs(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserActivitiesRecord value18(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserActivitiesRecord value19(java.lang.Integer value) {
		setNamespaceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserActivitiesRecord value20(java.lang.String value) {
		setVersionRealm(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserActivitiesRecord values(java.lang.Long value1, java.lang.Long value2, java.lang.Byte value3, java.lang.Long value4, java.lang.String value5, java.lang.Long value6, java.lang.String value7, java.lang.String value8, java.lang.String value9, java.lang.Byte value10, java.lang.Long value11, java.lang.Long value12, java.lang.String value13, java.lang.String value14, java.lang.String value15, java.lang.Long value16, java.lang.Long value17, java.sql.Timestamp value18, java.lang.Integer value19, java.lang.String value20) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EhUserActivitiesRecord
	 */
	public EhUserActivitiesRecord() {
		super(com.everhomes.server.schema.tables.EhUserActivities.EH_USER_ACTIVITIES);
	}

	/**
	 * Create a detached, initialised EhUserActivitiesRecord
	 */
	public EhUserActivitiesRecord(java.lang.Long id, java.lang.Long uid, java.lang.Byte activityType, java.lang.Long appVersionCode, java.lang.String appVersionName, java.lang.Long channelId, java.lang.String imeiNumber, java.lang.String deviceType, java.lang.String osInfo, java.lang.Byte osType, java.lang.Long mktDataVersion, java.lang.Long reportConfigVersion, java.lang.String internalIp, java.lang.String externalIp, java.lang.String userAgent, java.lang.Long collectTimeMs, java.lang.Long reportTimeMs, java.sql.Timestamp createTime, java.lang.Integer namespaceId, java.lang.String versionRealm) {
		super(com.everhomes.server.schema.tables.EhUserActivities.EH_USER_ACTIVITIES);

		setValue(0, id);
		setValue(1, uid);
		setValue(2, activityType);
		setValue(3, appVersionCode);
		setValue(4, appVersionName);
		setValue(5, channelId);
		setValue(6, imeiNumber);
		setValue(7, deviceType);
		setValue(8, osInfo);
		setValue(9, osType);
		setValue(10, mktDataVersion);
		setValue(11, reportConfigVersion);
		setValue(12, internalIp);
		setValue(13, externalIp);
		setValue(14, userAgent);
		setValue(15, collectTimeMs);
		setValue(16, reportTimeMs);
		setValue(17, createTime);
		setValue(18, namespaceId);
		setValue(19, versionRealm);
	}
}
