/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhUserNotificationSettingsRecord extends org.jooq.impl.UpdatableRecordImpl<com.everhomes.server.schema.tables.records.EhUserNotificationSettingsRecord> implements org.jooq.Record12<java.lang.Long, java.lang.Integer, java.lang.Long, java.lang.String, java.lang.Long, java.lang.String, java.lang.Long, java.lang.Byte, java.lang.Long, java.sql.Timestamp, java.lang.Long, java.sql.Timestamp> {

	private static final long serialVersionUID = 1744890863;

	/**
	 * Setter for <code>ehcore.eh_user_notification_settings.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_notification_settings.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>ehcore.eh_user_notification_settings.namespace_id</code>.
	 */
	public void setNamespaceId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_notification_settings.namespace_id</code>.
	 */
	public java.lang.Integer getNamespaceId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>ehcore.eh_user_notification_settings.app_id</code>. default to messaging app itself
	 */
	public void setAppId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_notification_settings.app_id</code>. default to messaging app itself
	 */
	public java.lang.Long getAppId() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>ehcore.eh_user_notification_settings.owner_type</code>. e.g: EhUsers
	 */
	public void setOwnerType(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_notification_settings.owner_type</code>. e.g: EhUsers
	 */
	public java.lang.String getOwnerType() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>ehcore.eh_user_notification_settings.owner_id</code>. owner type identify token
	 */
	public void setOwnerId(java.lang.Long value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_notification_settings.owner_id</code>. owner type identify token
	 */
	public java.lang.Long getOwnerId() {
		return (java.lang.Long) getValue(4);
	}

	/**
	 * Setter for <code>ehcore.eh_user_notification_settings.target_type</code>. e.g: EhUsers
	 */
	public void setTargetType(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_notification_settings.target_type</code>. e.g: EhUsers
	 */
	public java.lang.String getTargetType() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>ehcore.eh_user_notification_settings.target_id</code>. target type identify token
	 */
	public void setTargetId(java.lang.Long value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_notification_settings.target_id</code>. target type identify token
	 */
	public java.lang.Long getTargetId() {
		return (java.lang.Long) getValue(6);
	}

	/**
	 * Setter for <code>ehcore.eh_user_notification_settings.mute_flag</code>. 0: none, 1: mute
	 */
	public void setMuteFlag(java.lang.Byte value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_notification_settings.mute_flag</code>. 0: none, 1: mute
	 */
	public java.lang.Byte getMuteFlag() {
		return (java.lang.Byte) getValue(7);
	}

	/**
	 * Setter for <code>ehcore.eh_user_notification_settings.creator_uid</code>.
	 */
	public void setCreatorUid(java.lang.Long value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_notification_settings.creator_uid</code>.
	 */
	public java.lang.Long getCreatorUid() {
		return (java.lang.Long) getValue(8);
	}

	/**
	 * Setter for <code>ehcore.eh_user_notification_settings.create_time</code>.
	 */
	public void setCreateTime(java.sql.Timestamp value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_notification_settings.create_time</code>.
	 */
	public java.sql.Timestamp getCreateTime() {
		return (java.sql.Timestamp) getValue(9);
	}

	/**
	 * Setter for <code>ehcore.eh_user_notification_settings.update_uid</code>.
	 */
	public void setUpdateUid(java.lang.Long value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_notification_settings.update_uid</code>.
	 */
	public java.lang.Long getUpdateUid() {
		return (java.lang.Long) getValue(10);
	}

	/**
	 * Setter for <code>ehcore.eh_user_notification_settings.update_time</code>.
	 */
	public void setUpdateTime(java.sql.Timestamp value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>ehcore.eh_user_notification_settings.update_time</code>.
	 */
	public java.sql.Timestamp getUpdateTime() {
		return (java.sql.Timestamp) getValue(11);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record12 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row12<java.lang.Long, java.lang.Integer, java.lang.Long, java.lang.String, java.lang.Long, java.lang.String, java.lang.Long, java.lang.Byte, java.lang.Long, java.sql.Timestamp, java.lang.Long, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row12) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row12<java.lang.Long, java.lang.Integer, java.lang.Long, java.lang.String, java.lang.Long, java.lang.String, java.lang.Long, java.lang.Byte, java.lang.Long, java.sql.Timestamp, java.lang.Long, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row12) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.everhomes.server.schema.tables.EhUserNotificationSettings.EH_USER_NOTIFICATION_SETTINGS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.everhomes.server.schema.tables.EhUserNotificationSettings.EH_USER_NOTIFICATION_SETTINGS.NAMESPACE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return com.everhomes.server.schema.tables.EhUserNotificationSettings.EH_USER_NOTIFICATION_SETTINGS.APP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.everhomes.server.schema.tables.EhUserNotificationSettings.EH_USER_NOTIFICATION_SETTINGS.OWNER_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field5() {
		return com.everhomes.server.schema.tables.EhUserNotificationSettings.EH_USER_NOTIFICATION_SETTINGS.OWNER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.everhomes.server.schema.tables.EhUserNotificationSettings.EH_USER_NOTIFICATION_SETTINGS.TARGET_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field7() {
		return com.everhomes.server.schema.tables.EhUserNotificationSettings.EH_USER_NOTIFICATION_SETTINGS.TARGET_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field8() {
		return com.everhomes.server.schema.tables.EhUserNotificationSettings.EH_USER_NOTIFICATION_SETTINGS.MUTE_FLAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field9() {
		return com.everhomes.server.schema.tables.EhUserNotificationSettings.EH_USER_NOTIFICATION_SETTINGS.CREATOR_UID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field10() {
		return com.everhomes.server.schema.tables.EhUserNotificationSettings.EH_USER_NOTIFICATION_SETTINGS.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field11() {
		return com.everhomes.server.schema.tables.EhUserNotificationSettings.EH_USER_NOTIFICATION_SETTINGS.UPDATE_UID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field12() {
		return com.everhomes.server.schema.tables.EhUserNotificationSettings.EH_USER_NOTIFICATION_SETTINGS.UPDATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getNamespaceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getAppId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getOwnerType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value5() {
		return getOwnerId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getTargetType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value7() {
		return getTargetId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value8() {
		return getMuteFlag();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value9() {
		return getCreatorUid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value10() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value11() {
		return getUpdateUid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value12() {
		return getUpdateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserNotificationSettingsRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserNotificationSettingsRecord value2(java.lang.Integer value) {
		setNamespaceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserNotificationSettingsRecord value3(java.lang.Long value) {
		setAppId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserNotificationSettingsRecord value4(java.lang.String value) {
		setOwnerType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserNotificationSettingsRecord value5(java.lang.Long value) {
		setOwnerId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserNotificationSettingsRecord value6(java.lang.String value) {
		setTargetType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserNotificationSettingsRecord value7(java.lang.Long value) {
		setTargetId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserNotificationSettingsRecord value8(java.lang.Byte value) {
		setMuteFlag(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserNotificationSettingsRecord value9(java.lang.Long value) {
		setCreatorUid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserNotificationSettingsRecord value10(java.sql.Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserNotificationSettingsRecord value11(java.lang.Long value) {
		setUpdateUid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserNotificationSettingsRecord value12(java.sql.Timestamp value) {
		setUpdateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EhUserNotificationSettingsRecord values(java.lang.Long value1, java.lang.Integer value2, java.lang.Long value3, java.lang.String value4, java.lang.Long value5, java.lang.String value6, java.lang.Long value7, java.lang.Byte value8, java.lang.Long value9, java.sql.Timestamp value10, java.lang.Long value11, java.sql.Timestamp value12) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EhUserNotificationSettingsRecord
	 */
	public EhUserNotificationSettingsRecord() {
		super(com.everhomes.server.schema.tables.EhUserNotificationSettings.EH_USER_NOTIFICATION_SETTINGS);
	}

	/**
	 * Create a detached, initialised EhUserNotificationSettingsRecord
	 */
	public EhUserNotificationSettingsRecord(java.lang.Long id, java.lang.Integer namespaceId, java.lang.Long appId, java.lang.String ownerType, java.lang.Long ownerId, java.lang.String targetType, java.lang.Long targetId, java.lang.Byte muteFlag, java.lang.Long creatorUid, java.sql.Timestamp createTime, java.lang.Long updateUid, java.sql.Timestamp updateTime) {
		super(com.everhomes.server.schema.tables.EhUserNotificationSettings.EH_USER_NOTIFICATION_SETTINGS);

		setValue(0, id);
		setValue(1, namespaceId);
		setValue(2, appId);
		setValue(3, ownerType);
		setValue(4, ownerId);
		setValue(5, targetType);
		setValue(6, targetId);
		setValue(7, muteFlag);
		setValue(8, creatorUid);
		setValue(9, createTime);
		setValue(10, updateUid);
		setValue(11, updateTime);
	}
}
