INSERT INTO `eh_scene_types`(`id`, `namespace_id`, `name`, `display_name`, `create_time`) VALUES(1, 0, 'default', '默认场景', '2016-03-06 10:50:32');
INSERT INTO `eh_scene_types`(`id`, `namespace_id`, `name`, `display_name`, `create_time`) VALUES(2, 0, 'pm_admin', '物业管理员场景', '2016-03-06 10:50:32');

INSERT INTO `eh_locale_strings`(`scope`, `code`,`locale`, `text`) VALUES( 'forum', '101', 'zh_CN', '小区圈');
INSERT INTO `eh_locale_strings`(`scope`, `code`,`locale`, `text`) VALUES( 'forum', '102', 'zh_CN', '周边小区');
INSERT INTO `eh_locale_strings`(`scope`, `code`,`locale`, `text`) VALUES( 'forum', '103', 'zh_CN', '本小区');
INSERT INTO `eh_locale_strings`(`scope`, `code`,`locale`, `text`) VALUES( 'forum', '104', 'zh_CN', '兴趣圈');
INSERT INTO `eh_locale_strings`(`scope`, `code`,`locale`, `text`) VALUES( 'forum', '105', 'zh_CN', '公司圈');
INSERT INTO `eh_locale_strings`(`scope`, `code`,`locale`, `text`) VALUES( 'forum', '106', 'zh_CN', '全部');

-- INSERT INTO `eh_launch_pad_layouts`(`id`, `namespace_id`, `scene_type`, `name`, `layout_json`, `version_code`, `min_version_code`, `status`, `create_time`) 
-- 	VALUES (28, 0, 'default', 'DiscoveryLayout', '{"versionCode":"2016031201","versionName":"3.3.0","layoutName":"DiscoveryLayout","displayName":"发现","groups":[{"groupName":"","widget":"Navigator","instanceConfig":{"itemGroup":"NeighborLifes"},"style":"Default","defaultOrder":1,"separatorFlag":1,"separatorHeight":21,"columnCount":2},{"groupName":"","widget":"ScenePosts","instanceConfig":{"filterType":"discovery"},"style":"Default","defaultOrder":2,"separatorFlag":1,"separatorHeight":21}]}', '2016031201', '0', 2, '2016-03-12 19:16:25');
-- INSERT INTO `eh_launch_pad_layouts`(`id`, `namespace_id`, `scene_type`, `name`, `layout_json`, `version_code`, `min_version_code`, `status`, `create_time`) 
--	VALUES (29, 0, 'pm_admin', 'DiscoveryLayout', '{"versionCode":"2016031201","versionName":"3.3.0","layoutName":"DiscoveryLayout","displayName":"发现","groups":[{"groupName":"","widget":"Navigator","instanceConfig":{"itemGroup":"NeighborLifes"},"style":"Default","defaultOrder":1,"separatorFlag":1,"separatorHeight":21,"columnCount":2},{"groupName":"","widget":"ScenePosts","instanceConfig":{"filterType":"discovery"},"style":"Default","defaultOrder":2,"separatorFlag":1,"separatorHeight":21}]}', '2016031201', '0', 2, '2016-03-12 19:16:25');
INSERT INTO `eh_launch_pad_layouts`(`id`, `namespace_id`, `scene_type`, `name`, `layout_json`, `version_code`, `min_version_code`, `status`, `create_time`) 
	VALUES (30, 0, 'pm_admin', 'ServiceMarketLayout', '{"versionCode":"2016031201","versionName":"3.3.0","layoutName":"ServiceMarketLayout","displayName":"服务市场","groups":[{"groupName":"","widget":"Banners","instanceConfig":{"itemGroup":"Default"},"style":"Default","defaultOrder":1,"separatorFlag":0,"separatorHeight":0},{"groupName":"","widget":"Navigator","instanceConfig":{"itemGroup":"GovAgencies"},"style":"Default","defaultOrder":2,"separatorFlag":1,"separatorHeight":21,"columnCount":4},{"groupName":"","widget":"Coupons","instanceConfig":{"itemGroup":"Coupons"},"style":"Default","defaultOrder":3,"separatorFlag":1,"separatorHeight":21},{"groupName":"商家服务","widget":"Navigator","instanceConfig":{"itemGroup":"Bizs"},"style":"Default","defaultOrder":5,"separatorFlag":0,"separatorHeight":0}]}', '2016031201', '0', 2, '2016-03-12 19:16:25');
INSERT INTO `eh_launch_pad_layouts`(id, namespace_id, `scene_type`, name, layout_json, version_code, min_version_code, status, create_time) 
	VALUES (31, 0, 'pm_admin', 'SceneNoticeLayout', '{"versionCode":"2015072815","versionName":"3.0.0","displayName":"公告管理","layoutName":"SceneNoticeLayout","groups":[{"groupName":"","widget":"Navigator","instanceConfig":{"itemGroup":"GaActions"},"style":"Default","defaultOrder":2,"separatorFlag":1,"separatorHeight":21,"columnCount":4},{"groupName":"","widget":"ScenePosts","instanceConfig":{"filterType":"ga_notice"},"style":"Default","defaultOrder":3,"separatorFlag":0,"separatorHeight":0}]}', '2015082914', '2015061701', '2', '2015-06-27 14:04:57');
	
-- INSERT INTO `eh_launch_pad_items`(`id`, `scene_type`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) 
--	VALUES (10001, 'default', 0, 0, 0, 0, '/discovery', 'NeighborLifes', 'NeighborActivities', '周边活动', 'cs://1/image/aW1hZ2UvTVRvNFlXSXdaRGRqTnpKaU56UmtZMll3WlRNeU1XUmxOekU0WXpNNU9HWmpZUQ', '1', '1', '41', '', '0', '0', '1', '1', '', '0', null, null, null);
-- INSERT INTO `eh_launch_pad_items`(`id`, `scene_type`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) 
--	VALUES (10002, 'default', 0, 0, 0, 0, '/discovery', 'NeighborLifes', 'NeighborClubs', '周边俱乐部', 'cs://1/image/aW1hZ2UvTVRvNFlXSXdaRGRqTnpKaU56UmtZMll3WlRNeU1XUmxOekU0WXpNNU9HWmpZUQ', '1', '1', '42', '', '0', '0', '1', '1', '', '0', null, null, null);
-- INSERT INTO `eh_launch_pad_items`(`id`, `scene_type`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) 
--	VALUES (10003, 'pm_admin', 0, 0, 0, 0, '/discovery', 'NeighborLifes', 'NeighborActivities', '周边活动', 'cs://1/image/aW1hZ2UvTVRvNFlXSXdaRGRqTnpKaU56UmtZMll3WlRNeU1XUmxOekU0WXpNNU9HWmpZUQ', '1', '1', '41', '', '0', '0', '1', '1', '', '0', null, null, null);
-- INSERT INTO `eh_launch_pad_items`(`id`, `scene_type`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) 
--	VALUES (10004, 'pm_admin', 0, 0, 0, 0, '/discovery', 'NeighborLifes', 'NeighborClubs', '周边俱乐部', 'cs://1/image/aW1hZ2UvTVRvNFlXSXdaRGRqTnpKaU56UmtZMll3WlRNeU1XUmxOekU0WXpNNU9HWmpZUQ', '1', '1', '42', '', '0', '0', '1', '1', '', '0', null, null, null);
INSERT INTO `eh_launch_pad_items`(`id`, `scene_type`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) 
	VALUES (10005, 'pm_admin', 0, 0, 0, 0, '/home', 'GovAgencies', 'OrgTaskManagement', '任务管理', 'cs://1/image/aW1hZ2UvTVRwbE16QXlNekJrTVRZMU16Rm1OakpoTnpVNE9URmtaalU1WXpJMFpUaG1Ndw', 1, 1, '39', '{"module":"ORG_TASK_MANAGEMENT"}', 0, 0, 1, 1, '','0', NULL, NULL, NULL);
INSERT INTO `eh_launch_pad_items`(`id`, `scene_type`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) 
	VALUES (10006, 'pm_admin', 0, 0, 0, 0, '/home','GovAgencies','NoticeManager','公告管理','cs://1/image/aW1hZ2UvTVRvMU1tUmhZbVE0T0RZek5URm1NVEl5WVRWa05HSTJaVEJpWWpVeU1UUm1OZw',1,1,2, '{"itemLocation":"/home/NoticeManager","layoutName":"SceneNoticeLayout","title":"公告管理","entityTag":"PM"}', 0, 0, 1, 1, '', '0', NULL, NULL, NULL);
INSERT INTO `eh_launch_pad_items`(`id`, `scene_type`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) 
	VALUES (10007, 'pm_admin', 0, 0, 0, 0, '/home/NoticeManager', 'GaActions', 'PUBLIC_NOTICE', '发布公告', 'cs://1/image/aW1hZ2UvTVRwall6VTVOV1U0WkdRMk56aGxPRFV3TVRBMk5qVXlNVFkzWVRZek56aGpOdw', 1, 1, 19, '{"contentCategory":1003,"actionCategory":0,"targetEntityTag":"PM","visibleRegionType":0}', 0, 0, 1, 1, '', '0', NULL, NULL, NULL);
INSERT INTO `eh_launch_pad_items`(`id`, `scene_type`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) 
	VALUES (10008, 'pm_admin', 0, 0, 0, 0, '/home', 'Coupons', '优惠券', '优惠券', 'cs://1/image/aW1hZ2UvTVRwbFlXUTBOemd5WkdZd1l6RTVaV1l6WkRRNU1UZ3dOVFl3T1Rjd1pEazFNdw', 3, 1, 14, '{"url":"https://biz.zuolin.com/zl-ec?hideNavigationBar=1&sourceUrl=https%3A%2F%2Fbiz.zuolin.com%2Fweb%2Fapp%2Fuser%2Findex.html%23%2Fallpromotions#sign_suffix"}', 0, 0, 1, 1, '','0', NULL, NULL, NULL);
INSERT INTO `eh_launch_pad_items`(`id`, `scene_type`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) 
	VALUES (10009, 'pm_admin', 0, 0, 0, 0, '/home', 'Coupons', '市场动态', '市场动态', 'cs://1/image/aW1hZ2UvTVRvME5qRmhZVEF4TW1JeVpHWmpZVEU0TW1Kak9HRTNNR0l3TXpCak5UQXpOZw', 5, 1, 14, '{"url":"https://biz.zuolin.com/zl-ec?hideNavigationBar=1&sourceUrl=https%3A%2F%2Fbiz.zuolin.com%2Fweb%2Fapp%2Fuser%2Findex.html%23%2Fstore%2Fdetails%2F14477417463124576784#sign_suffix"}', 2, 0, 1, 1, '', 0, NULL, NULL, NULL);
INSERT INTO `eh_launch_pad_items`(`id`, `scene_type`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) 
	VALUES (10010, 'pm_admin', 0, 0, 0, 0, '/home', 'Bizs', 'PUNCH', '打卡考勤', 'cs://1/image/aW1hZ2UvTVRwa01ESXpZalEwTkdZeE1ETTNPRGMyWkdVMU5UQXlOMlZrT1dKaE9UZzBNZw', '1', '1', '23', '', 0, 0, 1, 1, '', '0', NULL, NULL, NULL);
INSERT INTO `eh_launch_pad_items`(`id`, `scene_type`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) 
	VALUES (10011, 'pm_admin', 0, 0, 0, 0, '/home', 'Bizs', 'DoorManagement', '门禁', 'cs://1/image/aW1hZ2UvTVRwalptSm1PRFE1T1dObVpqTXdZelZqWVRNME56azBNelk1TkdNNU1UUm1Zdw', 1, 1, 40, '', 0, 0, 1, 1, '', 0, NULL, NULL, NULL);
INSERT INTO `eh_launch_pad_items`(`id`, `scene_type`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) 
	VALUES (10012, 'pm_admin', 0, 0, 0, 0, '/home', 'Bizs', 'QualityInspection', '品质核查', 'cs://1/image/aW1hZ2UvTVRvNVpEWTROR0prTnpGak0yVm1NRGhsWVRNMU5EY3lPR0kzT1RSalkySmxZdw', '1', '1', '44', ' {"realm":"quality","entryUrl":"http://aclinktest.zuolin.com/nar/quality/index.html?hideNavigationBar=1#/task_list#sign_suffix"}', 0, 0, 1, 1, '', 0, NULL, NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`,  `scene_type`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`) 
	VALUES (10013, 'pm_admin', 0, 0, 0, 0, '/home', 'Bizs', '视频会议', '视频会议', 'cs://1/image/aW1hZ2UvTVRveE9HRmlOelV6TUdJNE9ERTRaalF6Wm1Nd05EWmxabVkyTkRjMlltVTNaZw', '1', '1', '27', '', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1');

INSERT INTO  `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) 
	VALUES (10014, '0', '0', '0', '0', '/home/pm', 'GaActions', '服务预约', '服务预约', 'cs://1/image/aW1hZ2UvTVRvNFpEVTVOalpqTVdNMk1UQTVPREpqWW1RME5qTTFOalV5WVRKa09UY3laUQ', '1', '1', '37', ' {\"ownerType\":\"organization\"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL);	
INSERT INTO `eh_launch_pad_items`(id,namespace_id,app_id,scope_code,scope_id,item_location,item_group,item_name,item_label,icon_uri,item_width,item_height,action_type,action_data,default_order,apply_policy,min_version,display_flag,display_layout,bgcolor,tag) 
	VALUES (10015, 0, 0, '0', 0, '/home/Gacw', 'GaPosts', 'ADVISE', '投诉建议', NULL, 1, 1, 15, '{"contentCategory":1006,"actionCategory":0,"forumId":1,"embedAppId":27}', 0, 0, 1, 1, '', 0,NULL);
INSERT INTO `eh_launch_pad_items`(id,namespace_id,app_id,scope_code,scope_id,item_location,item_group,item_name,item_label,icon_uri,item_width,item_height,action_type,action_data,default_order,apply_policy,min_version,display_flag,display_layout,bgcolor,tag) 
	VALUES (10016, 0, 0, '0', 0, '/home/Gacw', 'GaPosts', 'HELP', '咨询求助', NULL, 1, 1, 15, '{"contentCategory":1005,"actionCategory":0,"forumId":1,"embedAppId":27}', 0, 0, 1, 1, '', 0,NULL);