INSERT INTO `eh_locale_templates`(`scope`, `code`,`locale`, `description`, `text`, `namespace_id`) 
    VALUES( 'user.notification', 2, 'zh_CN', '注册天数描述', '我已加入左邻“${days}”天', 0);

INSERT INTO `eh_locale_strings`(`scope`, `code`,`locale`, `text`) VALUES( 'hottag', '10001', 'zh_CN', '该标签已是热门标签');



-- by sfyan 20160629
set @layout_id = (select max(id) from `eh_launch_pad_layouts`);
INSERT INTO `eh_launch_pad_layouts`(id, namespace_id, `scene_type`, name, layout_json, version_code, min_version_code, status, create_time,scope_code,scope_id,apply_policy) 
	VALUES ((@layout_id := @layout_id + 1), 0, 'default', 'ServiceMarketLayout', '{"versionCode":"2016031201","versionName":"3.3.0","layoutName":"ServiceMarketLayout","displayName":"服务市场","groups":[{"groupName":"","widget":"Banners","instanceConfig":{"itemGroup":"Default"},"style":"Default","defaultOrder":1,"separatorFlag":0,"separatorHeight":0},{"groupName":"","widget":"Navigator","instanceConfig":{"itemGroup":"GovAgencies"},"style":"Default","defaultOrder":2,"separatorFlag":1,"separatorHeight":21,"columnCount":4},{"groupName":"滚动广告","widget":"Bulletins","instanceConfig":{"itemGroup":""},"style":"Default","defaultOrder":4,"separatorFlag":1,"separatorHeight":21},{"groupName":"商家服务","widget":"Navigator","instanceConfig":{"itemGroup":"Bizs"},"style":"Default","defaultOrder":5,"separatorFlag":0,"separatorHeight":0},{"groupName":"","widget":"Coupons","instanceConfig":{"itemGroup":"Coupons"},"style":"Default","defaultOrder":3,"separatorFlag":1,"separatorHeight":21}]}', '2015082914', '2015061701', '2', '2015-06-27 14:04:57',1,24210090697430842,3);
	
INSERT INTO `eh_launch_pad_layouts`(id, namespace_id, `scene_type`, name, layout_json, version_code, min_version_code, status, create_time,scope_code,scope_id,apply_policy) 
	VALUES ((@layout_id := @layout_id + 1), 0, 'pm_admin', 'ServiceMarketLayout', '{"versionCode":"2016031201","versionName":"3.3.0","layoutName":"ServiceMarketLayout","displayName":"服务市场","groups":[{"groupName":"商家服务","widget":"Navigator","instanceConfig":{"itemGroup":"Bizs"},"style":"Default","defaultOrder":5,"separatorFlag":0,"separatorHeight":0},{"groupName":"","widget":"Banners","instanceConfig":{"itemGroup":"Default"},"style":"Default","defaultOrder":1,"separatorFlag":0,"separatorHeight":0},{"groupName":"","widget":"Navigator","instanceConfig":{"itemGroup":"GovAgencies"},"style":"Default","defaultOrder":2,"separatorFlag":1,"separatorHeight":21,"columnCount":4},{"groupName":"","widget":"Coupons","instanceConfig":{"itemGroup":"Coupons"},"style":"Default","defaultOrder":3,"separatorFlag":1,"separatorHeight":21},{"groupName":"滚动广告","widget":"Bulletins","instanceConfig":{"itemGroup":""},"style":"Default","defaultOrder":4,"separatorFlag":1,"separatorHeight":21}]}', '2015082914', '2015061701', '2', '2015-06-27 14:04:57',4,1000631,3);
	
set @banner_id = (select max(id) from `eh_banners`);
INSERT INTO `eh_banners` (`id`, `namespace_id`, `appId`, `banner_location`, `banner_group`, `scope_code`, `scope_id`, `name`, `vendor_tag`, `poster_path`, `action_type`, `action_data`, `start_time`, `end_time`, `status`, `order`, `creator_uid`, `create_time`, `delete_time`, `scene_type`,apply_policy) VALUES ((@banner_id := @banner_id + 1),0,NULL,'/home','DEFAULT',1,24210090697430842,'wowowowowowowoowowow~',NULL,'cs://1/image/aW1hZ2UvTVRvelpqY3laV0UzTmprMlptWXlZalF3WVRRNU16WTFabU5oTUdWbU1HVmpPQQ',9,'{\"forumId\":100334,\"topicId\":176119}',NULL,NULL,2,10,1,'2016-06-17 15:34:35',NULL,'default',3);
INSERT INTO `eh_banners` (`id`, `namespace_id`, `appId`, `banner_location`, `banner_group`, `scope_code`, `scope_id`, `name`, `vendor_tag`, `poster_path`, `action_type`, `action_data`, `start_time`, `end_time`, `status`, `order`, `creator_uid`, `create_time`, `delete_time`, `scene_type`,apply_policy) VALUES ((@banner_id := @banner_id + 1),0,NULL,'/home','DEFAULT',1,24210090697430842,'办公司啦,办公司啦...',NULL,'cs://1/image/aW1hZ2UvTVRveE5qSTRaREZqWVdFd09URXpabVZtWVRFeE9ERTFZekV6TURJMU9XWTFNUQ',9,'{\"forumId\":100334,\"topicId\":180523}',NULL,NULL,2,10,67663,'2016-06-29 00:09:58',NULL,'default',3);
INSERT INTO `eh_banners` (`id`, `namespace_id`, `appId`, `banner_location`, `banner_group`, `scope_code`, `scope_id`, `name`, `vendor_tag`, `poster_path`, `action_type`, `action_data`, `start_time`, `end_time`, `status`, `order`, `creator_uid`, `create_time`, `delete_time`, `scene_type`,apply_policy) VALUES ((@banner_id := @banner_id + 1),0,NULL,'/home','DEFAULT',4,1000631,'世纪春城物业唯一的banner...',NULL,'cs://1/image/aW1hZ2UvTVRveE5qSTRaREZqWVdFd09URXpabVZtWVRFeE9ERTFZekV6TURJMU9XWTFNUQ',9,'{\"forumId\":100334,\"topicId\":180523}',NULL,NULL,2,10,67663,'2016-06-29 00:09:58',NULL,'pm_admin',0);