-- from club 3.2 start

-- 俱乐部详情页  add by yanjun 20171107
SET @id = (SELECT MAX(id) from eh_configurations);
INSERT INTO `eh_configurations` (`id`, `name`, `value`, `description`, `namespace_id`, `display_name`) VALUES ((@id := @id + 1), 'club.description.url', '/mobile/static/club_detail/index.html', 'club description url', '0', NULL);

INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`, `level`, `condition_type`, `category`) VALUES ('10760', '行业协会', '10000', NULL, 'groups/guild', '0', '2', '/10000/10760', 'park', '180', '10750', '2', NULL, 'module');
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`, `level`, `condition_type`, `category`) VALUES ('10761', '行业协会管理', '10760', NULL, 'groups_management/guild', '0', '2', '/10000/10760/10761', 'park', '181', '10750', '3', NULL, 'module');
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`, `level`, `condition_type`, `category`) VALUES ('10762', '审核行业协会', '10760', NULL, 'react:/club-audit/audit-list', '0', '2', '/10000/10760/10762', 'park', '182', '10750', '3', NULL, 'module');

UPDATE eh_web_menus SET data_type = 'react:/club-audit/audit-list/1' where id = 10752;

INSERT INTO `eh_service_modules` (`id`, `name`, `parent_id`, `path`, `type`, `level`, `status`, `default_order`, `create_time`, `instance_config`, `action_type`, `update_time`, `operator_uid`, `creator_uid`, `description`, `multiple_flag`) VALUES ('10760', '行业协会', '10000', '/10000/10760', '1', '2', '2', '0', NOW(), NULL, '38', NOW(), '0', '0', '0', '0');

SET @menu_scope_id = (SELECT MAX(id) FROM `eh_web_menu_scopes`);
INSERT INTO `eh_web_menu_scopes`(`id`, `menu_id`,`menu_name`, `owner_type`, `owner_id`, `apply_policy`) VALUES((@menu_scope_id := @menu_scope_id + 1),10760,'', 'EhNamespaces', 999971,2);
INSERT INTO `eh_web_menu_scopes`(`id`, `menu_id`,`menu_name`, `owner_type`, `owner_id`, `apply_policy`) VALUES((@menu_scope_id := @menu_scope_id + 1),10761,'', 'EhNamespaces', 999971,2);
INSERT INTO `eh_web_menu_scopes`(`id`, `menu_id`,`menu_name`, `owner_type`, `owner_id`, `apply_policy`) VALUES((@menu_scope_id := @menu_scope_id + 1),10762,'', 'EhNamespaces', 999971,2);

SET @id = (SELECT MAX(id) from eh_locale_templates);
INSERT INTO `eh_locale_templates` (`id`, `scope`, `code`, `locale`, `description`, `text`, `namespace_id`) VALUES ((@id := @id + 1), 'group.notification', '60', 'zh_CN', '行业协会申请加入', '${userName}申请“${organizationName}”加入“${groupName}”，是否同意？', '0');
INSERT INTO `eh_locale_templates` (`id`, `scope`, `code`, `locale`, `description`, `text`, `namespace_id`) VALUES ((@id := @id + 1), 'group.notification', '61', 'zh_CN', '行业协会通过申请', '您提交的申请：“${organizationName}”加入“${groupName}”，已被管理员通过。', '0');
INSERT INTO `eh_locale_templates` (`id`, `scope`, `code`, `locale`, `description`, `text`, `namespace_id`) VALUES ((@id := @id + 1), 'group.notification', '62', 'zh_CN', '行业协会拒绝申请', '您提交的申请：“${organizationName}”加入“${groupName}”，已被管理员拒绝，理由：“${rejectText}”。', '0');
INSERT INTO `eh_locale_templates` (`id`, `scope`, `code`, `locale`, `description`, `text`, `namespace_id`) VALUES ((@id := @id + 1), 'group.notification', '63', 'zh_CN', '行业协会解散', '您加入的行业协会“${groupName}”已解散', '0');
INSERT INTO `eh_locale_templates` (`id`, `scope`, `code`, `locale`, `description`, `text`, `namespace_id`) VALUES ((@id := @id + 1), 'group.notification', '64', 'zh_CN', '俱乐部解散', '您加入的俱乐部“${groupName}”已解散', '0');
INSERT INTO `eh_locale_templates` (`id`, `scope`, `code`, `locale`, `description`, `text`, `namespace_id`) VALUES ((@id := @id + 1), 'group.notification', '65', 'zh_CN', '退出俱乐部', '您已退出俱乐部“${groupName}”', '0');
INSERT INTO `eh_locale_templates` (`id`, `scope`, `code`, `locale`, `description`, `text`, `namespace_id`) VALUES ((@id := @id + 1), 'group.notification', '66', 'zh_CN', '退出行业协会', '您已退出行业协会“${groupName}”', '0');
INSERT INTO `eh_locale_templates` (`id`, `scope`, `code`, `locale`, `description`, `text`, `namespace_id`) VALUES ((@id := @id + 1), 'group.notification', '67', 'zh_CN', '退出俱乐部发给管理员', '${userName}已退出俱乐部“${groupName}”', '0');
INSERT INTO `eh_locale_templates` (`id`, `scope`, `code`, `locale`, `description`, `text`, `namespace_id`) VALUES ((@id := @id + 1), 'group.notification', '68', 'zh_CN', '退出行业协会发给管理员', '${userName}已退出行业协会“${groupName}”', '0');
INSERT INTO `eh_locale_templates` (`id`, `scope`, `code`, `locale`, `description`, `text`, `namespace_id`) VALUES ((@id := @id + 1), 'group.notification', '69', 'zh_CN', '加入免费俱乐部发给管理员', '${userName}已加入俱乐部“${groupName}”', '0');
INSERT INTO `eh_locale_templates` (`id`, `scope`, `code`, `locale`, `description`, `text`, `namespace_id`) VALUES ((@id := @id + 1), 'group.notification', '70', 'zh_CN', '加入免费行业协会发给管理员', '${userName}已加入行业协会“${groupName}”', '0');

SET @id = (SELECT MAX(id) from eh_locale_strings);
INSERT INTO `eh_locale_strings` (`id`, `scope`, `code`, `locale`, `text`) VALUES ((@id := @id + 1), 'group', '10036', 'zh_CN', '俱乐部创建者无法被删除');
INSERT INTO `eh_locale_strings` (`id`, `scope`, `code`, `locale`, `text`) VALUES ((@id := @id + 1), 'group', '10037', 'zh_CN', '行业协会创建者无法被删除');

-- from club 3.2 end

-- added by R for approval-1.6
-- menu
UPDATE `eh_web_menus` SET `id`='52000', `name`='审批管理', `parent_id`='50000', `icon_url`=NULL, `data_type`='react:/approval-management/approval-list/52000/EhOrganizations', `leaf_flag`='0', `status`='2', `path`='/50000/52000', `type`='park', `sort_num`='591', `module_id`='52000', `level`='2', `condition_type`=NULL, `category`='module' WHERE (`id`='52000');
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`, `level`, `condition_type`, `category`) VALUES ('52010', '审批记录', '52000', NULL, 'react:/approval-management/approval-records?approvalModuleId=52000', '0', '2', '/50000/52000/52010', 'park', '591', '52000', '3', NULL, 'module');
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`, `level`, `condition_type`, `category`) VALUES ('52020', '规则设置', '52000', NULL, 'react:/approval-management/approval-list/52000/EhOrganizations', '0', '2', '/50000/52000/52020', 'park', '591', '52000', '3', NULL, 'module');
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`, `level`, `condition_type`, `category`) VALUES ('52030', '表单管理', '52000', NULL, 'react:/form-management/form-list?moduleId=52000&moduleType=approval', '0', '2', '/50000/52000/52030', 'park', '591', '52000', '3', NULL, 'module');

-- template
INSERT INTO `eh_general_form_templates` (`id`, `namespace_id`, `organization_id`, `owner_id`, `owner_type`, `module_id`, `module_type`, `form_name`, `version`, `template_type`, `template_text`, `modify_flag`, `delete_flag`, `update_time`, `create_time`) VALUES ('1', '0', '0', '0', 'EhOrganizations', '52000', 'any-module', '请假申请单', '0', 'DEFAULT_JSON', '[{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"请假事由\",\"fieldExtra\":\"{}\",\"fieldName\":\"请假事由\",\"fieldType\":\"MULTI_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":0},{\"dynamicFlag\":0,\"fieldDisplayName\":\"请假时段\",\"fieldExtra\":\"{}\",\"fieldName\":\"请假时段\",\"fieldType\":\"ASK_FOR_LEAVE\",\"renderType\":\"DEFAULT\",\"requiredFlag\":1,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":0,\"deleteFlag\":0},{\"dynamicFlag\":0,\"fieldDisplayName\":\"说明图片\",\"fieldExtra\":\"{\\\"limitCount\\\":9,\\\"limitPerSize\\\":5242880}\",\"fieldName\":\"说明图片\",\"fieldType\":\"IMAGE\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"IMAGE_COUNT_SIZE_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1}]', '1', '0', '2017-10-17 21:25:37', '2017-10-17 21:25:33');
INSERT INTO `eh_general_form_templates` (`id`, `namespace_id`, `organization_id`, `owner_id`, `owner_type`, `module_id`, `module_type`, `form_name`, `version`, `template_type`, `template_text`, `modify_flag`, `delete_flag`, `update_time`, `create_time`) VALUES ('2', '0', '0', '0', 'EhOrganizations', '52000', 'any-module', '加班申请单', '0', 'DEFAULT_JSON', '[{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"加班事由\",\"fieldExtra\":\"{}\",\"fieldName\":\"加班事由\",\"fieldType\":\"MULTI_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":0},{\"dynamicFlag\":0,\"fieldDisplayName\":\"加班时段\",\"fieldExtra\":\"{}\",\"fieldName\":\"加班时段\",\"fieldType\":\"OVERTIME\",\"renderType\":\"DEFAULT\",\"requiredFlag\":1,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":0,\"deleteFlag\":0},{\"dynamicFlag\":0,\"fieldDisplayName\":\"说明图片\",\"fieldExtra\":\"{\\\"limitCount\\\":9,\\\"limitPerSize\\\":5242880}\",\"fieldName\":\"说明图片\",\"fieldType\":\"IMAGE\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"IMAGE_COUNT_SIZE_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1}]', '1', '0', '2017-10-17 21:25:37', '2017-10-17 21:25:33');
INSERT INTO `eh_general_form_templates` (`id`, `namespace_id`, `organization_id`, `owner_id`, `owner_type`, `module_id`, `module_type`, `form_name`, `version`, `template_type`, `template_text`, `modify_flag`, `delete_flag`, `update_time`, `create_time`) VALUES ('3', '0', '0', '0', 'EhOrganizations', '52000', 'any-module', '出差申请单', '0', 'DEFAULT_JSON', '[{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"出差事由\",\"fieldExtra\":\"{}\",\"fieldName\":\"出差事由\",\"fieldType\":\"MULTI_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":0},{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"出差地点\",\"fieldExtra\":\"{\\\"limitWord\\\":10}\",\"fieldName\":\"出差地点\",\"fieldType\":\"SINGLE_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1},{\"dynamicFlag\":0,\"fieldDisplayName\":\"出差时段\",\"fieldExtra\":\"{}\",\"fieldName\":\"出差时段\",\"fieldType\":\"BUSINESS_TRIP\",\"renderType\":\"DEFAULT\",\"requiredFlag\":1,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":0,\"deleteFlag\":0},{\"dynamicFlag\":0,\"fieldDisplayName\":\"说明图片\",\"fieldExtra\":\"{\\\"limitCount\\\":9,\\\"limitPerSize\\\":5242880}\",\"fieldName\":\"说明图片\",\"fieldType\":\"IMAGE\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"IMAGE_COUNT_SIZE_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1}]', '1', '0', '2017-10-17 21:25:37', '2017-10-17 21:25:33');
INSERT INTO `eh_general_form_templates` (`id`, `namespace_id`, `organization_id`, `owner_id`, `owner_type`, `module_id`, `module_type`, `form_name`, `version`, `template_type`, `template_text`, `modify_flag`, `delete_flag`, `update_time`, `create_time`) VALUES ('4', '0', '0', '0', 'EhOrganizations', '52000', 'any-module', '外出申请单', '0', 'DEFAULT_JSON', '[{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"外出事由\",\"fieldExtra\":\"{}\",\"fieldName\":\"外出事由\",\"fieldType\":\"MULTI_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":0},{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"外出地点\",\"fieldExtra\":\"{\\\"limitWord\\\":10}\",\"fieldName\":\"外出地点\",\"fieldType\":\"SINGLE_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1},{\"dynamicFlag\":0,\"fieldDisplayName\":\"外出时段\",\"fieldExtra\":\"{}\",\"fieldName\":\"外出时段\",\"fieldType\":\"GO_OUT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":1,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":0,\"deleteFlag\":0},{\"dynamicFlag\":0,\"fieldDisplayName\":\"说明图片\",\"fieldExtra\":\"{\\\"limitCount\\\":9,\\\"limitPerSize\\\":5242880}\",\"fieldName\":\"说明图片\",\"fieldType\":\"IMAGE\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"IMAGE_COUNT_SIZE_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1}]', '1', '0', '2017-10-17 21:25:37', '2017-10-17 21:25:33');
INSERT INTO `eh_general_form_templates` (`id`, `namespace_id`, `organization_id`, `owner_id`, `owner_type`, `module_id`, `module_type`, `form_name`, `version`, `template_type`, `template_text`, `modify_flag`, `delete_flag`, `update_time`, `create_time`) VALUES ('5', '0', '0', '0', 'EhOrganizations', '52000', 'any-module', '打卡异常申请单', '0', 'DEFAULT_JSON', '[{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"异常事由\",\"fieldExtra\":\"{}\",\"fieldName\":\"异常事由\",\"fieldType\":\"MULTI_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":0},{\"dynamicFlag\":0,\"fieldDisplayName\":\"异常时间\",\"fieldExtra\":\"{}\",\"fieldName\":\"异常时间\",\"fieldType\":\"ABNORMAL_PUNCH\",\"renderType\":\"DEFAULT\",\"requiredFlag\":1,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":0,\"deleteFlag\":0},{\"dynamicFlag\":0,\"fieldDisplayName\":\"说明图片\",\"fieldExtra\":\"{\\\"limitCount\\\":9,\\\"limitPerSize\\\":5242880}\",\"fieldName\":\"说明图片\",\"fieldType\":\"IMAGE\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"IMAGE_COUNT_SIZE_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1}]', '1', '0', '2017-10-17 21:25:37', '2017-10-17 21:25:33');

INSERT INTO `eh_general_approval_templates`(`id`, `namespace_id`, `owner_id`, `owner_type`, `organization_id`, `module_id`, `module_type`, `project_id`, `project_type`, `form_template_id`, `support_type`, `approval_name`, `modify_flag`, `delete_flag`, `icon_uri`, `update_time`, `create_time`, `approval_attribute`) VALUES (1, 0, 0, 'EhOrganizations', 0, 52000, 'any-module', 0, NULL, 1, 0, '请假', 0, 0, 'cs://1/image/aW1hZ2UvTVRwbU1qTTFZekl3TnpNM05UQTNabU14Wm1Jd04yWmtaakprTldFd01qTTBOQQ', '2017-10-17 21:11:05', '2017-10-17 21:11:03', 'ASK_FOR_LEAVE');
INSERT INTO `eh_general_approval_templates`(`id`, `namespace_id`, `owner_id`, `owner_type`, `organization_id`, `module_id`, `module_type`, `project_id`, `project_type`, `form_template_id`, `support_type`, `approval_name`, `modify_flag`, `delete_flag`, `icon_uri`, `update_time`, `create_time`, `approval_attribute`) VALUES (2, 0, 0, 'EhOrganizations', 0, 52000, 'any-module', 0, NULL, 2, 0, '加班', 0, 0, 'cs://1/image/aW1hZ2UvTVRwbU16RTJNR05oWVdZME1tVXlNR0UzWXpjd01tTmhNamxtWmpobVlURmhaQQ', '2017-10-17 21:11:15', '2017-10-17 21:11:13', 'OVERTIME');
INSERT INTO `eh_general_approval_templates`(`id`, `namespace_id`, `owner_id`, `owner_type`, `organization_id`, `module_id`, `module_type`, `project_id`, `project_type`, `form_template_id`, `support_type`, `approval_name`, `modify_flag`, `delete_flag`, `icon_uri`, `update_time`, `create_time`, `approval_attribute`) VALUES (3, 0, 0, 'EhOrganizations', 0, 52000, 'any-module', 0, NULL, 3, 0, '出差', 0, 0, 'cs://1/image/aW1hZ2UvTVRwaU1tRXhaV1V4WlRRM00yVmlOalV4TmpRNU4yWXdNbVpqWXpBek5XSmhNUQ', '2017-10-17 21:11:25', '2017-10-17 21:11:23', 'BUSINESS_TRIP');
INSERT INTO `eh_general_approval_templates`(`id`, `namespace_id`, `owner_id`, `owner_type`, `organization_id`, `module_id`, `module_type`, `project_id`, `project_type`, `form_template_id`, `support_type`, `approval_name`, `modify_flag`, `delete_flag`, `icon_uri`, `update_time`, `create_time`, `approval_attribute`) VALUES (4, 0, 0, 'EhOrganizations', 0, 52000, 'any-module', 0, NULL, 4, 0, '外出', 0, 0, 'cs://1/image/aW1hZ2UvTVRvME9UUmxaREJrWlRWbVpEZzFOV05tTWpOaVlqaGlNMkl5Tm1RNE1UY3dNZw', '2017-10-17 21:11:35', '2017-10-17 21:11:33', 'GO_OUT');
INSERT INTO `eh_general_approval_templates`(`id`, `namespace_id`, `owner_id`, `owner_type`, `organization_id`, `module_id`, `module_type`, `project_id`, `project_type`, `form_template_id`, `support_type`, `approval_name`, `modify_flag`, `delete_flag`, `icon_uri`, `update_time`, `create_time`, `approval_attribute`) VALUES (5, 0, 0, 'EhOrganizations', 0, 52000, 'any-module', 0, NULL, 5, 0, '打卡异常', 0, 0, 'cs://1/image/aW1hZ2UvTVRwaE5URTFZMlZsT1RZNU0ySTVOamM0TkdNM1lUWTJaVGN4TTJOak1URmlaZw', '2017-10-17 21:11:45', '2017-10-17 21:11:43', 'ABNORMAL_PUNCH');

-- 请假类型
SET @cat_id = (SELECT MAX(id) FROM eh_approval_categories);
INSERT INTO `eh_approval_categories` (`id`, `namespace_id`, `owner_type`, `owner_id`, `approval_type`, `category_name`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES (@cat_id := @cat_id + 1, '0', NULL, '0', '1', '事假', '2', '212500', '2017-09-28 08:59:25', '2017-09-28 08:59:25', '212500');
INSERT INTO `eh_approval_categories` (`id`, `namespace_id`, `owner_type`, `owner_id`, `approval_type`, `category_name`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES (@cat_id := @cat_id + 1, '0', NULL, '0', '1', '病假', '2', '212500', '2017-09-28 08:59:40', '2017-09-28 08:59:40', '212500');
INSERT INTO `eh_approval_categories` (`id`, `namespace_id`, `owner_type`, `owner_id`, `approval_type`, `category_name`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES (@cat_id := @cat_id + 1, '0', NULL, '0', '1', '年假', '2', '212500', '2017-09-28 09:00:05', '2017-09-28 09:00:05', '212500');
INSERT INTO `eh_approval_categories` (`id`, `namespace_id`, `owner_type`, `owner_id`, `approval_type`, `category_name`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES (@cat_id := @cat_id + 1, '0', NULL, '0', '1', '调休', '2', '212500', '2017-11-03 09:00:05', '2017-11-03 09:00:05', '212500');
INSERT INTO `eh_approval_categories` (`id`, `namespace_id`, `owner_type`, `owner_id`, `approval_type`, `category_name`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES (@cat_id := @cat_id + 1, '0', NULL, '0', '1', '婚假', '2', '212500', '2017-11-03 09:00:06', '2017-11-03 09:00:06', '212500');
INSERT INTO `eh_approval_categories` (`id`, `namespace_id`, `owner_type`, `owner_id`, `approval_type`, `category_name`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES (@cat_id := @cat_id + 1, '0', NULL, '0', '1', '产假', '2', '212500', '2017-11-03 09:00:07', '2017-11-03 09:00:07', '212500');
INSERT INTO `eh_approval_categories` (`id`, `namespace_id`, `owner_type`, `owner_id`, `approval_type`, `category_name`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES (@cat_id := @cat_id + 1, '0', NULL, '0', '1', '陪产假', '2', '212500', '2017-11-03 09:00:08', '2017-11-03 09:00:08', '212500');
INSERT INTO `eh_approval_categories` (`id`, `namespace_id`, `owner_type`, `owner_id`, `approval_type`, `category_name`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES (@cat_id := @cat_id + 1, '0', NULL, '0', '1', '丧假', '2', '212500', '2017-11-03 09:00:09', '2017-11-03 09:00:09', '212500');
INSERT INTO `eh_approval_categories` (`id`, `namespace_id`, `owner_type`, `owner_id`, `approval_type`, `category_name`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES (@cat_id := @cat_id + 1, '0', NULL, '0', '1', '工伤假', '2', '212500', '2017-11-03 09:00:10', '2017-11-03 09:00:10', '212500');
INSERT INTO `eh_approval_categories` (`id`, `namespace_id`, `owner_type`, `owner_id`, `approval_type`, `category_name`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES (@cat_id := @cat_id + 1, '0', NULL, '0', '1', '路途假', '2', '212500', '2017-11-03 09:00:11', '2017-11-03 09:00:11', '212500');

-- 增加普通公司的对应的菜单
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`, `level`, `condition_type`, `category`)
VALUES ('520000', '审批管理', '500000', NULL, null, '0', '2', '/500000/520000', 'organization', '591', '52000', '2', NULL, 'module');
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`, `level`, `condition_type`, `category`)
VALUES ('520100', '审批记录', '520000', NULL, 'react:/approval-management/approval-records?approvalModuleId=52000', '0', '2', '/500000/520000/520100', 'organization', '592', '52000', '3', NULL, 'module');
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`, `level`, `condition_type`, `category`)
VALUES ('520200', '审批设置', '520000', NULL, 'react:/approval-management/approval-list/52000/EhOrganizations', '0', '2', '/500000/520000/520200', 'organization', '593', '52000', '3', NULL, 'module');
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`, `level`, `condition_type`, `category`)
VALUES ('520300', '表单管理', '520000', NULL, 'react:/form-management/form-list?moduleId=52000&moduleType=any-module', '0', '2', '/500000/520000/520300', 'organization', '594', '52000', '3', NULL, 'module');

-- ended by R

-- 运营后台菜单配置的菜单  add by yanjun 201711211550
INSERT INTO `eh_service_modules` (`id`, `name`, `parent_id`, `path`, `type`, `level`, `status`, `default_order`, `create_time`, `instance_config`, `action_type`, `update_time`, `operator_uid`, `creator_uid`, `description`, `multiple_flag`) VALUES ('70300', '菜单配置', '70000', '/70000/70300', '1', '2', '2', '0', NOW(), NULL, null, NOW(), '0', '0', '0', '0');
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`, `level`, `condition_type`, `category`) VALUES ('4200000', '菜单配置', '4000000', NULL, 'menu-config', '1', '2', '/4000000/4200000', 'zuolin', '2', '0', '2', 'namespace', 'module');
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`, `level`, `condition_type`, `category`) VALUES ('4210000', '菜单配置', '4200000', NULL, 'menu-config', '0', '2', '/4000000/4200000/4210000', 'zuolin', '1', '70300', '3', 'namespace', 'page');

-- 行业协会-所属行业  add by yanjun 20171121
INSERT INTO `eh_industry_types` (`id`, `uuid`, `namespace_id`, `name`, `create_time`) VALUES ('1', '1', '999971', '集成电路', NOW());
INSERT INTO `eh_industry_types` (`id`, `uuid`, `namespace_id`, `name`, `create_time`) VALUES ('2', '2', '999971', '软件', NOW());
INSERT INTO `eh_industry_types` (`id`, `uuid`, `namespace_id`, `name`, `create_time`) VALUES ('3', '3', '999971', '通信技术', NOW());
INSERT INTO `eh_industry_types` (`id`, `uuid`, `namespace_id`, `name`, `create_time`) VALUES ('4', '4', '999971', '生物医药', NOW());
INSERT INTO `eh_industry_types` (`id`, `uuid`, `namespace_id`, `name`, `create_time`) VALUES ('5', '5', '999971', '医疗器械', NOW());
INSERT INTO `eh_industry_types` (`id`, `uuid`, `namespace_id`, `name`, `create_time`) VALUES ('6', '6', '999971', '光机电', NOW());
INSERT INTO `eh_industry_types` (`id`, `uuid`, `namespace_id`, `name`, `create_time`) VALUES ('7', '7', '999971', '金融服务', NOW());
INSERT INTO `eh_industry_types` (`id`, `uuid`, `namespace_id`, `name`, `create_time`) VALUES ('8', '8', '999971', '新能源与环保', NOW());
INSERT INTO `eh_industry_types` (`id`, `uuid`, `namespace_id`, `name`, `create_time`) VALUES ('9', '9', '999971', '文化创意', NOW());
INSERT INTO `eh_industry_types` (`id`, `uuid`, `namespace_id`, `name`, `create_time`) VALUES ('10', '10', '999971', '其他', NOW());

-- 条件表达式的默认值  add by xq.tian  2017/11/20
UPDATE eh_flow_condition_expressions SET variable1='', variable2='' WHERE variable1='1' OR variable2='1';

-- 行业协会的actiontype改为38  add by yanjun 201711241009
UPDATE eh_launch_pad_items set action_type = 38 where namespace_id = 999971 and item_label = '行业协会';