-- 2018法定节假日added by wh
SET @id =(SELECT MAX(id) FROM eh_punch_holidays);
INSERT INTO `eh_punch_holidays` (`id`, `owner_type`, `owner_id`, `workday_rule_id`, `status`, `rule_date`, `creator_uid`, `create_time`, `exchange_from_date`) VALUES((@id:=@id+1),NULL,NULL,NULL,'1','2018-01-01','1','2017-12-06 14:20:10',NULL);
INSERT INTO `eh_punch_holidays` (`id`, `owner_type`, `owner_id`, `workday_rule_id`, `status`, `rule_date`, `creator_uid`, `create_time`, `exchange_from_date`) VALUES((@id:=@id+1),NULL,NULL,NULL,'1','2018-02-15','1','2017-12-06 14:20:10',NULL);
INSERT INTO `eh_punch_holidays` (`id`, `owner_type`, `owner_id`, `workday_rule_id`, `status`, `rule_date`, `creator_uid`, `create_time`, `exchange_from_date`) VALUES((@id:=@id+1),NULL,NULL,NULL,'1','2018-02-16','1','2017-12-06 14:20:10',NULL);
INSERT INTO `eh_punch_holidays` (`id`, `owner_type`, `owner_id`, `workday_rule_id`, `status`, `rule_date`, `creator_uid`, `create_time`, `exchange_from_date`) VALUES((@id:=@id+1),NULL,NULL,NULL,'1','2018-02-19','1','2017-12-06 14:20:10',NULL);
INSERT INTO `eh_punch_holidays` (`id`, `owner_type`, `owner_id`, `workday_rule_id`, `status`, `rule_date`, `creator_uid`, `create_time`, `exchange_from_date`) VALUES((@id:=@id+1),NULL,NULL,NULL,'1','2018-02-20','1','2017-12-06 14:20:10',NULL);
INSERT INTO `eh_punch_holidays` (`id`, `owner_type`, `owner_id`, `workday_rule_id`, `status`, `rule_date`, `creator_uid`, `create_time`, `exchange_from_date`) VALUES((@id:=@id+1),NULL,NULL,NULL,'1','2018-02-21','1','2017-12-06 14:20:10',NULL);
INSERT INTO `eh_punch_holidays` (`id`, `owner_type`, `owner_id`, `workday_rule_id`, `status`, `rule_date`, `creator_uid`, `create_time`, `exchange_from_date`) VALUES((@id:=@id+1),NULL,NULL,NULL,'0','2018-02-11','1','2017-12-06 14:20:10','2018-02-20');
INSERT INTO `eh_punch_holidays` (`id`, `owner_type`, `owner_id`, `workday_rule_id`, `status`, `rule_date`, `creator_uid`, `create_time`, `exchange_from_date`) VALUES((@id:=@id+1),NULL,NULL,NULL,'0','2018-02-24','1','2017-12-06 14:20:10','2017-12-21');
INSERT INTO `eh_punch_holidays` (`id`, `owner_type`, `owner_id`, `workday_rule_id`, `status`, `rule_date`, `creator_uid`, `create_time`, `exchange_from_date`) VALUES((@id:=@id+1),NULL,NULL,NULL,'1','2018-04-05','1','2017-12-06 14:20:10',NULL);
INSERT INTO `eh_punch_holidays` (`id`, `owner_type`, `owner_id`, `workday_rule_id`, `status`, `rule_date`, `creator_uid`, `create_time`, `exchange_from_date`) VALUES((@id:=@id+1),NULL,NULL,NULL,'1','2018-04-06','1','2017-12-06 14:20:10',NULL);
INSERT INTO `eh_punch_holidays` (`id`, `owner_type`, `owner_id`, `workday_rule_id`, `status`, `rule_date`, `creator_uid`, `create_time`, `exchange_from_date`) VALUES((@id:=@id+1),NULL,NULL,NULL,'0','2018-04-08','1','2017-12-06 14:20:10','2018-04-06');
INSERT INTO `eh_punch_holidays` (`id`, `owner_type`, `owner_id`, `workday_rule_id`, `status`, `rule_date`, `creator_uid`, `create_time`, `exchange_from_date`) VALUES((@id:=@id+1),NULL,NULL,NULL,'1','2018-04-30','1','2017-12-06 14:20:10',NULL);
INSERT INTO `eh_punch_holidays` (`id`, `owner_type`, `owner_id`, `workday_rule_id`, `status`, `rule_date`, `creator_uid`, `create_time`, `exchange_from_date`) VALUES((@id:=@id+1),NULL,NULL,NULL,'1','2018-05-01','1','2017-12-06 14:20:10',NULL);
INSERT INTO `eh_punch_holidays` (`id`, `owner_type`, `owner_id`, `workday_rule_id`, `status`, `rule_date`, `creator_uid`, `create_time`, `exchange_from_date`) VALUES((@id:=@id+1),NULL,NULL,NULL,'0','2018-04-28','1','2017-12-06 14:20:10','2018-04-30');
INSERT INTO `eh_punch_holidays` (`id`, `owner_type`, `owner_id`, `workday_rule_id`, `status`, `rule_date`, `creator_uid`, `create_time`, `exchange_from_date`) VALUES((@id:=@id+1),NULL,NULL,NULL,'1','2018-06-18','1','2017-12-06 14:20:10',NULL);
INSERT INTO `eh_punch_holidays` (`id`, `owner_type`, `owner_id`, `workday_rule_id`, `status`, `rule_date`, `creator_uid`, `create_time`, `exchange_from_date`) VALUES((@id:=@id+1),NULL,NULL,NULL,'1','2018-09-24','1','2017-12-06 14:20:10',NULL);
INSERT INTO `eh_punch_holidays` (`id`, `owner_type`, `owner_id`, `workday_rule_id`, `status`, `rule_date`, `creator_uid`, `create_time`, `exchange_from_date`) VALUES((@id:=@id+1),NULL,NULL,NULL,'1','2018-10-01','1','2017-12-06 14:20:10',NULL);
INSERT INTO `eh_punch_holidays` (`id`, `owner_type`, `owner_id`, `workday_rule_id`, `status`, `rule_date`, `creator_uid`, `create_time`, `exchange_from_date`) VALUES((@id:=@id+1),NULL,NULL,NULL,'1','2018-10-02','1','2017-12-06 14:20:10',NULL);
INSERT INTO `eh_punch_holidays` (`id`, `owner_type`, `owner_id`, `workday_rule_id`, `status`, `rule_date`, `creator_uid`, `create_time`, `exchange_from_date`) VALUES((@id:=@id+1),NULL,NULL,NULL,'1','2018-10-03','1','2017-12-06 14:20:10',NULL);
INSERT INTO `eh_punch_holidays` (`id`, `owner_type`, `owner_id`, `workday_rule_id`, `status`, `rule_date`, `creator_uid`, `create_time`, `exchange_from_date`) VALUES((@id:=@id+1),NULL,NULL,NULL,'1','2018-10-04','1','2017-12-06 14:20:10',NULL);
INSERT INTO `eh_punch_holidays` (`id`, `owner_type`, `owner_id`, `workday_rule_id`, `status`, `rule_date`, `creator_uid`, `create_time`, `exchange_from_date`) VALUES((@id:=@id+1),NULL,NULL,NULL,'1','2018-10-05','1','2017-12-06 14:20:10',NULL);
INSERT INTO `eh_punch_holidays` (`id`, `owner_type`, `owner_id`, `workday_rule_id`, `status`, `rule_date`, `creator_uid`, `create_time`, `exchange_from_date`) VALUES((@id:=@id+1),NULL,NULL,NULL,'0','2018-09-29','1','2017-12-06 14:20:10','2018-10-04');
INSERT INTO `eh_punch_holidays` (`id`, `owner_type`, `owner_id`, `workday_rule_id`, `status`, `rule_date`, `creator_uid`, `create_time`, `exchange_from_date`) VALUES((@id:=@id+1),NULL,NULL,NULL,'0','2018-09-30','1','2017-12-06 14:20:10','2018-10-05');

-- merge from customercd by xiongying20171208
set @field_id = (select max(id) from eh_var_fields);
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'founderIntroduce', '创始人介绍', 'String', '10', '/1/10', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "richText", "length": 1024}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'foundingTime', '企业成立时间', 'Date', '11', '/1/11', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "datetime", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'registrationTypeId', '企业登记注册类型', 'Long', '11', '/1/11', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "customizationSelect", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'technicalFieldId', '企业所属技术领域', 'Long', '11', '/1/11', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "customizationSelect", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'taxpayerTypeId', '企业纳税人类型', 'Long', '11', '/1/11', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "customizationSelect", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'relationWillingId', '是否愿意与创业导师建立辅导关系', 'Long', '11', '/1/11', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "customizationSelect", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'highAndNewTechId', '是否高新技术企业', 'Long', '11', '/1/11', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "customizationSelect", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'entrepreneurialCharacteristicsId', '企业主要负责人创业特征', 'Long', '11', '/1/11', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "customizationSelect", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'serialEntrepreneurId', '企业主要负责人是否为连续创业者', 'Long', '11', '/1/11', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "customizationSelect", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'riskInvestmentAmount', '获天使或风险投资总金额（万元）', 'BigDecimal', '11', '/1/11', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "text", "length": 32}');

INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'totalEmployees', '从业人员总人数', 'Integer', '4', '/4', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "text", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'juniorColleges', '大专', 'Integer', '4', '/4', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "text", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'undergraduates', '本科', 'Integer', '4', '/4', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "text", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'masters', '硕士', 'Integer', '4', '/4', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "text", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'doctors', '博士', 'Integer', '4', '/4', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "text", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'overseas', '留学人员', 'Integer', '4', '/4', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "text", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'thousandTalentsProgram', '千人计划人数', 'Integer', '4', '/4', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "text", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'freshGraduates', '吸纳应届大学毕业生', 'Integer', '4', '/4', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "text", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'age', '年龄', 'Integer', '4', '/4', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "text", "length": 32}');

INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'applications', '知识产权申请总数', 'Integer', '5', '/17/5', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "text", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'patentApplications', '申请发明专利数', 'Integer', '5', '/17/5', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "text", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'authorizations', '知识产权授权总数', 'Integer', '5', '/17/5', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "text", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'patentAuthorizations', '授权发明专利数', 'Integer', '5', '/17/5', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "text", "length": 32}');

INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'effectiveIntellectualProperties', '拥有有效知识产权总数', 'Integer', '16', '/17/16', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "text", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'patents', '发明专利', 'Integer', '16', '/17/16', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "text", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'softwareCopyrights', '软件著作权', 'Integer', '16', '/17/16', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "text", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'icLayout', '集成电路布图', 'Integer', '16', '/17/16', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "text", "length": 32}');

INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'buyPatents', '购买国外专利', 'Integer', '18', '/17/18', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "text", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'technologyContracts', '技术合同交易数量', 'Integer', '18', '/17/18', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "text", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'technologyContractAmount', '技术合同交易总金额（万元）', 'Integer', '18', '/17/18', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "text", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'nationalProjects', '当年承担国家级科技计划项目数', 'Integer', '18', '/17/18', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "text", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'provincialAwards', '当年获得省级以上奖励', 'Integer', '18', '/17/18', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "text", "length": 32}');

INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'investmentTime', '时间', 'Date', '8', '/8', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "datetime", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'investmentRound', 'XX轮', 'String', '8', '/8', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "text", "length": 32}');

INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'description', '主要项目介绍', 'String', '6', '/6', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "richText", "length": 1024}');




INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`)
VALUES (28, 'enterprise_customer', '0', '/28', '入驻信息', 'com.everhomes.customer.CustomerEntryInfo', '0', NULL, '2', '1', UTC_TIMESTAMP());

INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'area', '区域', 'String', 28, '/28', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "text", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'address', '地址', 'String', 28, '/28', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "text", "length": 256}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'addressId', '楼栋门牌', 'Long', 28, '/28', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "text", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'areaSize', '面积', 'BigDecimal', 28, '/28', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "text", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'contractStartDate', '入驻开始日期', 'Date', 28, '/28', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "datetime", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'contractEndDate', '入驻结束日期', 'Date', 28, '/28', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "datetime", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'contractEndMonth', '入驻到期月份', 'Integer', 28, '/28', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "text", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'remark', '备注', 'String', 28, '/28', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "multiText", "length": 128}');


INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`)
VALUES (29, 'enterprise_customer', '0', '/29', '离场信息', 'com.everhomes.customer.CustomerDepartureInfo', '0', NULL, '2', '1', UTC_TIMESTAMP());

INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'reviewTime', '离场申请时间', 'Date', 29, '/29', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "datetime", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'hatchMonths', '离场时间', 'Integer', 29, '/29', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "text", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'departureNatureId', '离场性质', 'Long', 29, '/29', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "customizationSelect", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'departureDirectionId', '离场去向', 'Long', 29, '/29', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "customizationSelect", "length": 32}');
INSERT INTO `eh_var_fields` (`id`, `module_name`, `name`, `display_name`, `field_type`, `group_id`, `group_path`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `field_param`) VALUES ((@field_id:=@field_id+1), 'enterprise_customer', 'remark', '备注', 'String', 29, '/29', '0', NULL, '2', '1', UTC_TIMESTAMP(),'{"fieldParamType": "multiText", "length": 128}');


-- 成都孵化器菜单 add by xiongying20171208
SET @menu_scope_id = IFNULL((SELECT MAX(id) FROM `eh_web_menu_scopes`), 1);
INSERT INTO `eh_web_menu_scopes` (`id`, `menu_id`, `menu_name`, `owner_type`, `owner_id`, `apply_policy`) VALUES ((@menu_scope_id := @menu_scope_id + 1), '21100', '', 'EhNamespaces', '999964', '2');
INSERT INTO `eh_web_menu_scopes` (`id`, `menu_id`, `menu_name`, `owner_type`, `owner_id`, `apply_policy`) VALUES ((@menu_scope_id := @menu_scope_id + 1), '21110', '', 'EhNamespaces', '999964', '2');
INSERT INTO `eh_web_menu_scopes` (`id`, `menu_id`, `menu_name`, `owner_type`, `owner_id`, `apply_policy`) VALUES ((@menu_scope_id := @menu_scope_id + 1), '21120', '', 'EhNamespaces', '999964', '2');
