-- add more variables by janson
INSERT INTO `eh_flow_variables`
(`id`, `namespace_id`, `owner_id`, `owner_type`, `module_id`, `module_type`, `name`, `label`, `var_type`, `script_type`, `script_cls`, `status`)
VALUES ('1004', '0', '0', '', '0', '', 'currAllProcessorsName', '本节点处理人姓名', 'text', 'bean_id', 'flow-variable-curr-all-processors-name', '1');

INSERT INTO `eh_flow_variables`
(`id`, `namespace_id`, `owner_id`, `owner_type`, `module_id`, `module_type`, `name`, `label`, `var_type`, `script_type`, `script_cls`, `status`)
VALUES ('1005', '0', '0', '', '0', '', 'currAllProcessorsPhone', '本节点处理人手机号码', 'text', 'bean_id', 'flow-variable-curr-all-processors-phone', '1');

INSERT INTO `eh_flow_variables`
(`id`, `namespace_id`, `owner_id`, `owner_type`, `module_id`, `module_type`, `name`, `label`, `var_type`, `script_type`, `script_cls`, `status`)
VALUES ('1006', '0', '0', '', '0', '', 'prefixAllProcessorsName', '上一步处理人姓名', 'text', 'bean_id', 'flow-variable-prefix-all-processors-name', '1');

INSERT INTO `eh_flow_variables`
(`id`, `namespace_id`, `owner_id`, `owner_type`, `module_id`, `module_type`, `name`, `label`, `var_type`, `script_type`, `script_cls`, `status`)
VALUES ('1007', '0', '0', '', '0', '', 'prefixAllProcessorsPhone', '上一步处理人手机号码', 'text', 'bean_id', 'flow-variable-prefix-all-processors-phone', '1');

INSERT INTO `eh_flow_variables`
(`id`, `namespace_id`, `owner_id`, `owner_type`, `module_id`, `module_type`, `name`, `label`, `var_type`, `script_type`, `script_cls`, `status`)
VALUES ('1008', '0', '0', '', '0', '', 'transferTargetName', '被转交人姓名', 'text', 'bean_id', 'flow-variable-transfer-target-name', '1');

INSERT INTO `eh_flow_variables`
(`id`, `namespace_id`, `owner_id`, `owner_type`, `module_id`, `module_type`, `name`, `label`, `var_type`, `script_type`, `script_cls`, `status`)
VALUES ('1009', '0', '0', '', '0', '', 'transferTargetPhone', '被转交人手机号', 'text', 'bean_id', 'flow-variable-transfer-target-phone', '1');

UPDATE `eh_flow_variables` SET `label`='本节点操作执行人姓名' WHERE `id`='1002';
UPDATE `eh_flow_variables` SET `label`='本节点操作执行人手机号' WHERE `id`='1003';

UPDATE `eh_flow_variables` SET `label`='上一个节点执行人' WHERE `id`='2001';
UPDATE `eh_flow_variables` SET `label`='本节点执行人' WHERE `id`='2002';

INSERT INTO `eh_flow_variables`
(`id`, `namespace_id`, `owner_id`, `owner_type`, `module_id`, `module_type`, `name`, `label`, `var_type`, `script_type`, `script_cls`, `status`)
VALUES ('2007', '0', '0', '', '0', '', 'prefixProcessors', '上个节点处理人', 'node_user', 'bean_id', 'flow-variable-prefix-node-processors', '1');

INSERT INTO `eh_flow_variables`
(`id`, `namespace_id`, `owner_id`, `owner_type`, `module_id`, `module_type`, `name`, `label`, `var_type`, `script_type`, `script_cls`, `status`)
VALUES ('2008', '0', '0', '', '0', '', 'currProcessors', '本节点处理人', 'node_user', 'bean_id', 'flow-variable-curr-node-processors', '1');

INSERT INTO `eh_flow_variables`
(`id`, `namespace_id`, `owner_id`, `owner_type`, `module_id`, `module_type`, `name`, `label`, `var_type`, `script_type`, `script_cls`, `status`)
VALUES ('2009', '0', '0', '', '0', '', 'targetTransfer', '被转交人', 'node_user', 'bean_id', 'flow-variable-target-node-transfer', '1');

-- 对接工作流短信模版 add by sw 20170324
INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'sms.default.yzx', 23, 'zh_CN', '新建月卡申请', '34956');
INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'sms.default.yzx', 24, 'zh_CN', '月卡申请驳回', '34957');
INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'sms.default.yzx', 25, 'zh_CN', '月卡申请审核通过', '34958');
INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'sms.default.yzx', 26, 'zh_CN', '月卡申请办理成功', '34959');

INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'sms.default.yzx', 35, 'zh_CN', '新建园区入驻', '39496');
INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'sms.default.yzx', 36, 'zh_CN', '园区入驻已受理', '39497');
INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'sms.default.yzx', 37, 'zh_CN', '园区入驻审核未通过', '39498');
INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'sms.default.yzx', 38, 'zh_CN', '园区入驻催办', '39499');
INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'sms.default.yzx', 39, 'zh_CN', '园区入驻办理成功', '39500');

INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'sms.default.yzx', 40, 'zh_CN', '新建资源预约', '39615');
INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'sms.default.yzx', 41, 'zh_CN', '资源预约督办', '39616');
INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'sms.default.yzx', 42, 'zh_CN', '资源预约已受理', '39617');
INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'sms.default.yzx', 43, 'zh_CN', '资源预约驳回', '39618');
INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'sms.default.yzx', 44, 'zh_CN', '资源预约催办', '39619');
INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'sms.default.yzx', 45, 'zh_CN', '资源预约办理成功', '39620');

INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'sms.default.yzx', 46, 'zh_CN', '物业报修督办受理', '39721');
INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'sms.default.yzx', 47, 'zh_CN', '物业报修待分配', '39722');
INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'sms.default.yzx', 48, 'zh_CN', '物业报修督办分配', '39723');
INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'sms.default.yzx', 49, 'zh_CN', '物业报修已完成', '39724');

INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'flow:40800', 23, 'zh_CN', '新建月卡申请', '34956');
INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'flow:40800', 24, 'zh_CN', '月卡申请驳回', '34957');
INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'flow:40800', 25, 'zh_CN', '月卡申请审核通过', '34958');
INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'flow:40800', 26, 'zh_CN', '月卡申请办理成功', '34959');

INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'flow:40100', 35, 'zh_CN', '新建园区入驻', '39496');
INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'flow:40100', 36, 'zh_CN', '园区入驻已受理', '39497');
INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'flow:40100', 37, 'zh_CN', '园区入驻审核未通过', '39498');
INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'flow:40100', 38, 'zh_CN', '园区入驻催办', '39499');
INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'flow:40100', 39, 'zh_CN', '园区入驻办理成功', '39500');

INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'flow:40400', 40, 'zh_CN', '新建资源预约', '39615');
INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'flow:40400', 41, 'zh_CN', '资源预约督办', '39616');
INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'flow:40400', 42, 'zh_CN', '资源预约已受理', '39617');
INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'flow:40400', 43, 'zh_CN', '资源预约驳回', '39618');
INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'flow:40400', 44, 'zh_CN', '资源预约催办', '39619');
INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'flow:40400', 45, 'zh_CN', '资源预约办理成功', '39620');

INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'flow:20100', 46, 'zh_CN', '物业报修督办受理', '39721');
INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'flow:20100', 47, 'zh_CN', '物业报修待分配', '39722');
INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'flow:20100', 48, 'zh_CN', '物业报修督办分配', '39723');
INSERT INTO `eh_locale_templates`(`namespace_id`, `scope`, `code`,`locale`, `description`, `text`)
	VALUES (1000000, 'flow:20100', 49, 'zh_CN', '物业报修已完成', '39724');


-- oauth2client 1.0   add by xq.tian 2017/03/09
--
-- 门禁icon
--
SET @max_id = (SELECT max(id) FROM `eh_launch_pad_items`);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`)
VALUES ((@max_id := @max_id + 1), 999986, 0, 0, 0, '/home', 'Bizs', 'ACLINK', '门禁', 'cs://1/image/aW1hZ2UvTVRwaVl6ZGtPVFE0TURZd1pUZzRZekppTTJNMVl6QmlPVFprTWpWbFpHRXlNUQ', 1, 1, 13, '{"url":"https://core.zuolin.com/evh/oauth2cli/redirect/huanteng?serviceUrl=%2fzlapp%2fdist%2f%3fhideNavigationBar%3d1%23%2faccess-control%2flock-list-cy&hideNavigationBar=1#sign_suffix"}', 0, 0, 1, 1, NULL, 0, NULL, NULL, NULL, 0, 'default', 0, NULL, NULL);
SET @max_id = (SELECT max(id) FROM `eh_launch_pad_items`);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`)
VALUES ((@max_id := @max_id + 1), 999986, 0, 0, 0, '/home', 'Bizs', 'ACLINK', '门禁', 'cs://1/image/aW1hZ2UvTVRwaVl6ZGtPVFE0TURZd1pUZzRZekppTTJNMVl6QmlPVFprTWpWbFpHRXlNUQ', 1, 1, 13, '{"url":"https://core.zuolin.com/evh/oauth2cli/redirect/huanteng?serviceUrl=%2fzlapp%2fdist%2f%3fhideNavigationBar%3d1%23%2faccess-control%2flock-list-cy&hideNavigationBar=1#sign_suffix"}', 0, 0, 1, 1, NULL, 0, NULL, NULL, NULL, 0, 'pm_admin', 0, NULL, NULL);


-- 帖子评论时给创建者或父评论者发送消息模板，add by tt, 20170316
select max(id) into @id from `eh_locale_templates`;
INSERT INTO `eh_locale_templates` (`id`, `scope`, `code`, `locale`, `description`, `text`, `namespace_id`) VALUES (@id:=@id+1, 'forum.notification', 2, 'zh_CN', '帖子评论给创建者发消息', '有人评论了你的帖子\t${userName} 评论了你的帖子 ${postName}。', 0);
INSERT INTO `eh_locale_templates` (`id`, `scope`, `code`, `locale`, `description`, `text`, `namespace_id`) VALUES (@id:=@id+1, 'forum.notification', 3, 'zh_CN', '帖子评论给父评论者发消息', '有人回复了你的评论\t${userName} 回复了你在帖子 ${postName} 的评论。', 0);

-- 更改帖子删除提示，add by tt, 20170316
UPDATE `eh_locale_strings` SET `text`='该帖子已被主人删除' WHERE  `id`=44;


-- 删除0域空间服务市场数据，add by tt, 20170324
-- create table eh_banners_bak select * from eh_banners where namespace_id = 0;
-- create table eh_item_service_categries_bak select * from eh_item_service_categries where namespace_id = 0;
-- create table eh_launch_pad_items_bak select * from eh_launch_pad_items where namespace_id = 0;
-- create table eh_launch_pad_layouts_bak select * from eh_launch_pad_layouts where namespace_id = 0;

delete from eh_banners where namespace_id = 0;
delete from eh_item_service_categries where namespace_id = 0;
delete from eh_launch_pad_items where namespace_id = 0;
delete from eh_launch_pad_layouts where namespace_id = 0;

-- 增加0域空间数据，add by tt, 20170316
select max(id) into @id from `eh_banners`;
INSERT INTO `eh_banners` (`id`, `namespace_id`, `appId`, `banner_location`, `banner_group`, `scope_code`, `scope_id`, `name`, `vendor_tag`, `poster_path`, `action_type`, `action_data`, `start_time`, `end_time`, `status`, `order`, `creator_uid`, `create_time`, `delete_time`, `scene_type`, `apply_policy`, `update_time`) VALUES (@id:=@id+1,0,0,'/home','Default',0,0,'','','cs://1/image/aW1hZ2UvTVRwa1pUa3haR1F3TTJVNVpqRmlPVFl5TVRFeU5XVTJZV1JpT1RBMk4yWmhZZw',0,'{}',NULL,NULL,2,10,0,'2017-03-24 16:39:26',NULL,'pm_admin',0,NULL);
INSERT INTO `eh_banners` (`id`, `namespace_id`, `appId`, `banner_location`, `banner_group`, `scope_code`, `scope_id`, `name`, `vendor_tag`, `poster_path`, `action_type`, `action_data`, `start_time`, `end_time`, `status`, `order`, `creator_uid`, `create_time`, `delete_time`, `scene_type`, `apply_policy`, `update_time`) VALUES (@id:=@id+1,0,0,'/home','Default',0,0,'','','cs://1/image/aW1hZ2UvTVRvM1lXTXhNVEV4TVRSa01HTm1PV016WmpObE9UYzNZalpqTW1Gak1tVTJZdw',0,'{}',NULL,NULL,2,10,0,'2017-03-24 16:39:26',NULL,'pm_admin',0,NULL);
INSERT INTO `eh_banners` (`id`, `namespace_id`, `appId`, `banner_location`, `banner_group`, `scope_code`, `scope_id`, `name`, `vendor_tag`, `poster_path`, `action_type`, `action_data`, `start_time`, `end_time`, `status`, `order`, `creator_uid`, `create_time`, `delete_time`, `scene_type`, `apply_policy`, `update_time`) VALUES (@id:=@id+1,0,0,'/home','ZJt44e',0,0,NULL,'','cs://1/image/aW1hZ2UvTVRwa1pUa3haR1F3TTJVNVpqRmlPVFl5TVRFeU5XVTJZV1JpT1RBMk4yWmhZZw',0,'{}',NULL,NULL,2,10,0,'2017-03-24 16:45:14',NULL,'park_tourist',0,NULL);
INSERT INTO `eh_banners` (`id`, `namespace_id`, `appId`, `banner_location`, `banner_group`, `scope_code`, `scope_id`, `name`, `vendor_tag`, `poster_path`, `action_type`, `action_data`, `start_time`, `end_time`, `status`, `order`, `creator_uid`, `create_time`, `delete_time`, `scene_type`, `apply_policy`, `update_time`) VALUES (@id:=@id+1,0,0,'/home','ZJt44e',0,0,NULL,'','cs://1/image/aW1hZ2UvTVRvM1lXTXhNVEV4TVRSa01HTm1PV016WmpObE9UYzNZalpqTW1Gak1tVTJZdw',0,'{}',NULL,NULL,2,10,0,'2017-03-24 16:45:14',NULL,'park_tourist',0,NULL);
INSERT INTO `eh_banners` (`id`, `namespace_id`, `appId`, `banner_location`, `banner_group`, `scope_code`, `scope_id`, `name`, `vendor_tag`, `poster_path`, `action_type`, `action_data`, `start_time`, `end_time`, `status`, `order`, `creator_uid`, `create_time`, `delete_time`, `scene_type`, `apply_policy`, `update_time`) VALUES (@id:=@id+1,0,0,'/home','Default',0,0,NULL,'','cs://1/image/aW1hZ2UvTVRwa1pUa3haR1F3TTJVNVpqRmlPVFl5TVRFeU5XVTJZV1JpT1RBMk4yWmhZZw',13,'{\"url\": \"\"}',NULL,NULL,2,10,0,'2017-03-24 16:45:21',NULL,'default',0,NULL);
INSERT INTO `eh_banners` (`id`, `namespace_id`, `appId`, `banner_location`, `banner_group`, `scope_code`, `scope_id`, `name`, `vendor_tag`, `poster_path`, `action_type`, `action_data`, `start_time`, `end_time`, `status`, `order`, `creator_uid`, `create_time`, `delete_time`, `scene_type`, `apply_policy`, `update_time`) VALUES (@id:=@id+1,0,0,'/home','Default',0,0,NULL,'','cs://1/image/aW1hZ2UvTVRvM1lXTXhNVEV4TVRSa01HTm1PV016WmpObE9UYzNZalpqTW1Gak1tVTJZdw',0,'{}',NULL,NULL,2,10,0,'2017-03-24 16:45:21',NULL,'default',0,NULL);
select ifnull(max(id),0) into @id from `eh_item_service_categries`;
INSERT INTO `eh_item_service_categries` (`id`, `name`, `icon_uri`, `order`, `align`, `status`, `namespace_id`, `scene_type`) VALUES (@id:=@id+1,'园区运营服务','cs://1/image/aW1hZ2UvTVRvME9ESmxPR1pqT0dFM1pHSmpaRFkwTWpRNE16TmtaVEUwTWpRMFl6UTNaUQ',1,0,1,0,'pm_admin');
INSERT INTO `eh_item_service_categries` (`id`, `name`, `icon_uri`, `order`, `align`, `status`, `namespace_id`, `scene_type`) VALUES (@id:=@id+1,'企业行政服务','cs://1/image/aW1hZ2UvTVRvME9ESmxPR1pqT0dFM1pHSmpaRFkwTWpRNE16TmtaVEUwTWpRMFl6UTNaUQ',2,0,1,0,'pm_admin');
INSERT INTO `eh_item_service_categries` (`id`, `name`, `icon_uri`, `order`, `align`, `status`, `namespace_id`, `scene_type`) VALUES (@id:=@id+1,'物业内部管控','cs://1/image/aW1hZ2UvTVRvME9ESmxPR1pqT0dFM1pHSmpaRFkwTWpRNE16TmtaVEUwTWpRMFl6UTNaUQ',3,0,1,0,'pm_admin');
INSERT INTO `eh_item_service_categries` (`id`, `name`, `icon_uri`, `order`, `align`, `status`, `namespace_id`, `scene_type`) VALUES (@id:=@id+1,'园区运营服务','cs://1/image/aW1hZ2UvTVRvME9ESmxPR1pqT0dFM1pHSmpaRFkwTWpRNE16TmtaVEUwTWpRMFl6UTNaUQ',1,0,1,0,'park_tourist');
INSERT INTO `eh_item_service_categries` (`id`, `name`, `icon_uri`, `order`, `align`, `status`, `namespace_id`, `scene_type`) VALUES (@id:=@id+1,'企业行政服务','cs://1/image/aW1hZ2UvTVRvME9ESmxPR1pqT0dFM1pHSmpaRFkwTWpRNE16TmtaVEUwTWpRMFl6UTNaUQ',2,0,1,0,'park_tourist');
INSERT INTO `eh_item_service_categries` (`id`, `name`, `icon_uri`, `order`, `align`, `status`, `namespace_id`, `scene_type`) VALUES (@id:=@id+1,'小区运营服务','cs://1/image/aW1hZ2UvTVRvME9ESmxPR1pqT0dFM1pHSmpaRFkwTWpRNE16TmtaVEUwTWpRMFl6UTNaUQ',1,0,1,0,'default');
select max(id) into @id from `eh_launch_pad_layouts`;
INSERT INTO `eh_launch_pad_layouts` (`id`, `namespace_id`, `name`, `layout_json`, `version_code`, `min_version_code`, `status`, `create_time`, `scene_type`, `scope_code`, `scope_id`, `apply_policy`) VALUES (@id:=@id+1,0,'ServiceMarketLayout','{\"versionCode\": \"2017032425\", \"displayName\": \"服务市场\", \"layoutName\": \"ServiceMarketLayout\", \"groups\": [{\"defaultOrder\": 1, \"groupName\": \"\", \"instanceConfig\": {\"itemGroup\": \"Default\", \"item_group\": \"Default\"}, \"separatorFlag\": 1, \"style\": \"Default\", \"widget\": \"Banners\", \"separatorHeight\": 16}, {\"defaultOrder\": 2, \"groupName\": \"\", \"instanceConfig\": {\"itemGroup\": \"Default\"}, \"separatorFlag\": 1, \"style\": \"Default\", \"widget\": \"Bulletins\", \"separatorHeight\": 1}, {\"defaultOrder\": 3, \"groupName\": \"\", \"instanceConfig\": {\"itemGroup\": \"Default\", \"item_group\": \"Default\"}, \"separatorFlag\": 1, \"style\": \"Default\", \"widget\": \"Navigator\", \"separatorHeight\": 16}, {\"defaultOrder\": 4, \"columnCount\": 1, \"instanceConfig\": {\"itemGroup\": \"Bizs\", \"item_group\": \"Bizs\"}, \"separatorFlag\": 1, \"style\": \"Gallery\", \"groupName\": \"\", \"widget\": \"Navigator\", \"separatorHeight\": 16}, {\"defaultOrder\": 5, \"groupName\": \"\", \"instanceConfig\": {\"entityCount\": 6, \"newsSize\": 6, \"item_group\": \"OPPushBiz\", \"itemGroup\": \"OPPushBiz\", \"subjectHeight\": 1, \"descriptionHeight\": 0}, \"separatorFlag\": 1, \"style\": \"HorizontalScrollView\", \"widget\": \"OPPush\", \"separatorHeight\": 16}, {\"defaultOrder\": 6, \"groupName\": \"\", \"instanceConfig\": {\"entityCount\": 3, \"newsSize\": 3, \"item_group\": \"OPPushActivity\", \"itemGroup\": \"OPPushActivity\", \"subjectHeight\": 1, \"descriptionHeight\": 0}, \"separatorFlag\": 1, \"style\": \"ListView\", \"widget\": \"OPPush\", \"separatorHeight\": 16}], \"versionName\": \"3.3.0\"}',2017032425,0,2,'2017-03-24 16:39:26','pm_admin',0,0,0);
INSERT INTO `eh_launch_pad_layouts` (`id`, `namespace_id`, `name`, `layout_json`, `version_code`, `min_version_code`, `status`, `create_time`, `scene_type`, `scope_code`, `scope_id`, `apply_policy`) VALUES (@id:=@id+1,0,'ServiceMarketLayout','{\"versionCode\": \"2017032414\", \"displayName\": \"服务市场\", \"layoutName\": \"ServiceMarketLayout\", \"groups\": [{\"defaultOrder\": 1, \"groupName\": \"\", \"instanceConfig\": {\"itemGroup\": \"ZJt44e\"}, \"separatorFlag\": 0, \"style\": \"Default\", \"widget\": \"Banners\", \"separatorHeight\": 0}, {\"defaultOrder\": 2, \"groupName\": \"\", \"instanceConfig\": {\"itemGroup\": \"Default\", \"rowCount\": 1}, \"separatorFlag\": 1, \"style\": \"Default\", \"widget\": \"Bulletins\", \"separatorHeight\": 1}, {\"defaultOrder\": 3, \"groupName\": \"\", \"instanceConfig\": {\"itemGroup\": \"Default\"}, \"separatorFlag\": 1, \"style\": \"Default\", \"widget\": \"Navigator\", \"separatorHeight\": 16}, {\"defaultOrder\": 4, \"columnCount\": 1, \"instanceConfig\": {\"itemGroup\": \"Bizs\"}, \"separatorFlag\": 1, \"style\": \"Gallery\", \"groupName\": \"\", \"widget\": \"Navigator\", \"separatorHeight\": 16}, {\"defaultOrder\": 5, \"groupName\": \"\", \"instanceConfig\": {\"entityCount\": 6, \"newsSize\": 6, \"subjectHeight\": 1, \"descriptionHeight\": 0, \"itemGroup\": \"OPPushBiz\"}, \"separatorFlag\": 1, \"style\": \"HorizontalScrollView\", \"widget\": \"OPPush\", \"separatorHeight\": 16}, {\"defaultOrder\": 6, \"groupName\": \"\", \"instanceConfig\": {\"entityCount\": 6, \"newsSize\": 6, \"subjectHeight\": 1, \"descriptionHeight\": 0, \"itemGroup\": \"OPPushActivity\"}, \"separatorFlag\": 1, \"style\": \"ListView\", \"widget\": \"OPPush\", \"separatorHeight\": 16}], \"versionName\": \"3.3.0\"}',2017032414,0,2,'2017-03-24 16:45:14','park_tourist',0,0,0);
INSERT INTO `eh_launch_pad_layouts` (`id`, `namespace_id`, `name`, `layout_json`, `version_code`, `min_version_code`, `status`, `create_time`, `scene_type`, `scope_code`, `scope_id`, `apply_policy`) VALUES (@id:=@id+1,0,'ServiceMarketLayout','{\"versionCode\": \"2017032420\", \"displayName\": \"服务市场\", \"layoutName\": \"ServiceMarketLayout\", \"groups\": [{\"defaultOrder\": 1, \"columnCount\": 4, \"instanceConfig\": {\"itemGroup\": \"Default\"}, \"separatorFlag\": 1, \"style\": \"Default\", \"groupName\": \"\", \"widget\": \"Banners\", \"separatorHeight\": 16}, {\"defaultOrder\": 2, \"groupName\": \"\", \"instanceConfig\": {\"itemGroup\": \"Default\"}, \"separatorFlag\": 1, \"style\": \"Default\", \"widget\": \"Bulletins\", \"separatorHeight\": 1}, {\"defaultOrder\": 3, \"groupName\": \"\", \"instanceConfig\": {\"itemGroup\": \"Default\"}, \"separatorFlag\": 1, \"style\": \"Default\", \"widget\": \"Navigator\", \"separatorHeight\": 16}, {\"defaultOrder\": 4, \"columnCount\": 1, \"instanceConfig\": {\"itemGroup\": \"Bizs\"}, \"separatorFlag\": 1, \"style\": \"Gallery\", \"groupName\": \"\", \"widget\": \"Navigator\", \"separatorHeight\": 16}, {\"defaultOrder\": 5, \"groupName\": \"\", \"instanceConfig\": {\"entityCount\": 6, \"newsSize\": 6, \"subjectHeight\": 1, \"descriptionHeight\": 0, \"itemGroup\": \"OPPushBiz\"}, \"separatorFlag\": 1, \"style\": \"HorizontalScrollView\", \"widget\": \"OPPush\", \"separatorHeight\": 16}, {\"defaultOrder\": 6, \"groupName\": \"\", \"instanceConfig\": {\"entityCount\": 6, \"newsSize\": 6, \"subjectHeight\": 1, \"descriptionHeight\": 0, \"itemGroup\": \"OPPushActivity\"}, \"separatorFlag\": 1, \"style\": \"ListView\", \"widget\": \"OPPush\", \"separatorHeight\": 16}], \"versionName\": \"3.3.0\"}',2017032420,0,2,'2017-03-24 16:45:21','default',0,0,0);
select ifnull(max(id),0) into @id from `eh_launch_pad_items`;
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','园区公告','园区公告','cs://1/image/aW1hZ2UvTVRwaE1UWTFaamszWmpVek1EaGtORFE0TkRObFpqRTJZakpoWVdFeU1HWTNZZw',1,1,15,'{\"actionCategory\": 0, \"contentCategory\": \"1003\", \"forumId\": 1, \"entityTag\": \"PM\", \"embedAppId\": \"0\"}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'pm_admin',0,8,0);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','园区活动','园区活动','cs://1/image/aW1hZ2UvTVRwa01EbGhPV0kyT0dGa05UZ3lNakl6WVRZMFkyWmlZakk0T1RSbE56RXdNUQ',1,1,50,'{}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'pm_admin',0,8,1);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','园区论坛','园区论坛','cs://1/image/aW1hZ2UvTVRwbE5Ea3hOMkppWkdRNE1USmxZelppT1dFeE5HTXlaR0psTlRneVltSTJNZw',1,1,62,'{}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'pm_admin',0,8,2);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','服务热线','服务热线','cs://1/image/aW1hZ2UvTVRvelpXRm1NV0UzWXpZNFpqRmpZekExWlRBNVl6QTBOalZqWVdJeFkyVmhNUQ',1,1,45,'{}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'pm_admin',0,8,3);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','门禁','门禁','cs://1/image/aW1hZ2UvTVRvMVpHRXpNV0UyTmprek5EVTRZMk00TTJJME56Rm1Oak16TUdVNE5qVTRaUQ',1,1,40,'{\"hardwareId\": \"\", \"isSupportSmart\": \"0\", \"isSupportQR\": \"1\", \"doorId\": \"\"}',4,0,1,1,'1',0,NULL,NULL,NULL,0,'pm_admin',0,8,4);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','打印服务','打印服务','cs://1/image/aW1hZ2UvTVRwbE1ERTVaREZoWTJaa1kyTmlNVFUxWW1aallXRTFaak14WW1FM05HWmpNdw',1,1,14,'{\"url\": \"http://zuolin.com/mobile/static/coming_soon/index.html\"}',7,0,1,1,'1',0,NULL,NULL,NULL,0,'pm_admin',0,8,5);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','物业服务','物业服务','cs://1/image/aW1hZ2UvTVRwbE1tUTFZVFZsWlRRNU1ETTVORGc1WTJJell6QmlOR1pqTkRRNFkyTTVOUQ',1,1,60,'{\"url\": \"zl://propertyrepair/create?type=user&taskCategoryId=0&displayName=物业服务\"}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'pm_admin',0,8,6);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','物业缴费','物业缴费','cs://1/image/aW1hZ2UvTVRvNE5tSmlZalkxTlRSaE5tWmxNemM0WVdReE1qQXlNbUU0T0RGbU16VTBNQQ',1,1,14,'{\"url\": \"https://core.zuolin.com/property_fee/index.html?hideNavigationBar=1#/bill_query?sign_suffix\"}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'pm_admin',0,8,7);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','电子屏预订','电子屏预订','cs://1/image/aW1hZ2UvTVRwa01HVm1PR0ppT1RGaU1UVm1ORFExTUdaa1pEQmhPRFZtTnpObE9UZ3laZw',1,1,49,'{\"resourceTypeId\": \"80003\", \"pageType\": \"0\"}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'pm_admin',0,8,8);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','公共会议室','公共会议室','cs://1/image/aW1hZ2UvTVRvd1lXVmxaV1kzWVRjeE1HTmxZVE15Wkdaak0yTXpZV1ZqWVRoaU9UVTRPQQ',1,1,49,'{\"resourceTypeId\": \"80002\", \"pageType\": \"0\"}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'pm_admin',0,8,9);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','停车充值','停车充值','cs://1/image/aW1hZ2UvTVRvek4yVmpPREEzTkRsalpXTTFOMk5qWldKak5tSm1OMlpqT1dGaE9XVXpOUQ',1,1,30,'{}',6,0,1,1,'1',0,NULL,NULL,NULL,0,'pm_admin',0,8,10);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','VIP车位','VIP车位','cs://1/image/aW1hZ2UvTVRvMVlqVTNNVFJrTkdWaE1ETTJaV1ExWldFM1pEQXhZVEV4TURJMk16SXlOUQ',1,1,49,'{\"resourceTypeId\": \"8\", \"pageType\": \"0\"}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'pm_admin',0,8,11);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','通讯录','通讯录','cs://1/image/aW1hZ2UvTVRwak1ERTVaREEwWTJObVlqRm1PREkwTkRSaE9HTTRNREkyT1Roa01tSXdNZw',1,1,46,'{}',2,0,1,1,'1',0,NULL,NULL,NULL,0,'pm_admin',0,9,12);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','打卡考勤','打卡考勤','cs://1/image/aW1hZ2UvTVRvNVpUQXpaRFpqWW1RNFlXSmxOVGRrWXprNVl6azFORFEzT0RjeFpUUmpZUQ',1,1,23,'{}',3,0,1,1,'1',0,NULL,NULL,NULL,0,'pm_admin',0,9,13);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','会议室预订','会议室预订','cs://1/image/aW1hZ2UvTVRwa1pEVTNPREF5TldVME1qWmxOVEJqTkRJME1HTmxaR1JrTnpSaU56SmxaZw',1,1,49,'{\"resourceTypeId\": \"80001\", \"pageType\": \"0\"}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'pm_admin',0,9,14);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','视频会议','视频会议','cs://1/image/aW1hZ2UvTVRveE5UazBabU5qWVRrMU56QmxaVEJqWkdReVpqSTNPV1V6WWpGaU5UUTBNQQ',1,1,27,'{}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'pm_admin',0,9,15);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','审批','审批','cs://1/image/aW1hZ2UvTVRvNFkyUmpNV0V4TmpVMU0yWXdOVFU1T1RNMk9XWTFOV016WmpSak5HTmxOUQ',1,1,54,'{}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'pm_admin',0,9,16);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','任务管理','任务管理','cs://1/image/aW1hZ2UvTVRwbVlUVmxPRGhrWldaaU5Ua3pNamcwWm1JMU1UVmpPV0UzWXpjMU0ySXhPQQ',1,1,56,'{}',1,0,1,1,'1',0,NULL,NULL,NULL,0,'pm_admin',0,10,17);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','公告管理','公告管理','cs://1/image/aW1hZ2UvTVRvNU1UQTFORFk1T0Roall6RTBNRGd5TWpReVptSTVNekJrWldReU1UTTNOdw',1,1,43,'{}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'pm_admin',0,10,18);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','能耗管理','能耗管理','cs://1/image/aW1hZ2UvTVRwaU16ZGtZVE0xTlRJM01tUm1NV0ZpTXpReU16RTRaV0l5T1RsaE1Ua3hZZw',1,1,13,'{\"url\": \"http://core.zuolin.com/energy-management/index.html?hideNavigationBar=1#/address_choose#sign_suffix\"}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'pm_admin',0,10,19);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','设备巡检','设备巡检','cs://1/image/aW1hZ2UvTVRwalpUWm1ObUV3WVRnMVpXSmhPREF5WWpFMlpqSmtZalJsWVRjMk5ESTFNQQ',1,1,14,'{\"url\": \"https://core.zuolin.com/equipment-inspection/dist/index.html?hideNavigationBar=1#sign_suffix\"}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'pm_admin',0,10,20);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','品质核查','品质核查','cs://1/image/aW1hZ2UvTVRvd1pqWmxZekkxTVRRelpURmhPRFprTWpkalpUWmpOelk0WWpGa09USTFZUQ',1,1,44,'{\"entryUrl\": \"https://core.zuolin.com/nar/quality/index.html?hideNavigationBar=1#/select_community#sign_suffix\", \"realm\": \"quality\"}',5,0,1,1,'1',0,NULL,NULL,NULL,0,'pm_admin',0,10,21);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','全部','全部','cs://1/image/aW1hZ2UvTVRvellqSXhNemd5T1RZNU5tWTNZV016TkRreE9HTTRaR1JqWmpneE5EWTBNdw',1,1,53,'{\"itemLocation\": \"/home\", \"itemGroup\": \"Default\"}',8,0,1,1,'1',0,NULL,NULL,NULL,0,'pm_admin',0,NULL,22);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Bizs','valgo coffee','valgo coffee','cs://1/image/aW1hZ2UvTVRvMVl6bGlNekZrTlRkbE9ETmtNMlptTjJFeU1ERTBNbUV4TlRReE5XWm1OUQ',1,1,14,'{\"url\": \"https://biz.zuolin.com/zl-ec/rest/service/front/logon?hideNavigationBar=1&sourceUrl=https%3a%2f%2fbiz.zuolin.com%2fnar%2fbiz%2fweb%2fapp%2fuser%2findex.html%23%2fmicroshop%2fhome%3fisfromindex%3d0%26_k%3dzlbiz#sign_suffix\"}',0,0,1,1,'1',0,NULL,NULL,NULL,0,'pm_admin',0,NULL,0);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','OPPushBiz','新品推荐','新品推荐',NULL,1,1,13,'{\"url\": \"https://biz.zuolin.com/zl-ec/rest/service/front/logon?hideNavigationBar=1&sourceUrl=https%3a%2f%2fbiz.zuolin.com%2fnar%2fbiz%2fweb%2fapp%2fuser%2findex.html%23%2fmicroshop%2fhome%3fisfromindex%3d0%26_k%3dzlbiz#sign_suffix\"}',0,0,1,1,'1',0,NULL,NULL,NULL,0,'pm_admin',0,NULL,0);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','OPPushActivity','最新活动','最新活动',NULL,1,1,61,'{\"title\": \"白领活动\", \"scope\": \"0\", \"publishPrivilege\": \"1\", \"style\": \"4\", \"livePrivilege\": \"0\", \"categoryId\": 1, \"listStyle\": \"1\"}',0,0,1,1,'1',0,NULL,NULL,NULL,0,'pm_admin',0,NULL,0);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','园区公告','园区公告','cs://1/image/aW1hZ2UvTVRwaE1UWTFaamszWmpVek1EaGtORFE0TkRObFpqRTJZakpoWVdFeU1HWTNZZw',1,1,15,'{\"actionCategory\": 0, \"contentCategory\": \"1003\", \"forumId\": 1, \"entityTag\": \"PM\", \"embedAppId\": \"0\"}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'park_tourist',0,11,0);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','园区活动','园区活动','cs://1/image/aW1hZ2UvTVRwa01EbGhPV0kyT0dGa05UZ3lNakl6WVRZMFkyWmlZakk0T1RSbE56RXdNUQ',1,1,50,'{}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'park_tourist',0,11,1);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','园区论坛','园区论坛','cs://1/image/aW1hZ2UvTVRwbE5Ea3hOMkppWkdRNE1USmxZelppT1dFeE5HTXlaR0psTlRneVltSTJNZw',1,1,62,'{}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'park_tourist',0,11,2);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','服务热线','服务热线','cs://1/image/aW1hZ2UvTVRvelpXRm1NV0UzWXpZNFpqRmpZekExWlRBNVl6QTBOalZqWVdJeFkyVmhNUQ',1,1,45,'{}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'park_tourist',0,11,3);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','门禁','门禁','cs://1/image/aW1hZ2UvTVRvMVpHRXpNV0UyTmprek5EVTRZMk00TTJJME56Rm1Oak16TUdVNE5qVTRaUQ',1,1,40,'{\"isSupportQR\": 1, \"isSupportSmart\": 0}',1,0,1,1,'1',0,NULL,NULL,NULL,0,'park_tourist',0,11,4);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','打印服务','打印服务','cs://1/image/aW1hZ2UvTVRwbE1ERTVaREZoWTJaa1kyTmlNVFUxWW1aallXRTFaak14WW1FM05HWmpNdw',1,1,14,'{\"url\": \"http://zuolin.com/mobile/static/coming_soon/index.html\"}',2,0,1,1,'1',0,NULL,NULL,NULL,0,'park_tourist',0,11,5);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','物业服务','物业服务','cs://1/image/aW1hZ2UvTVRwbE1tUTFZVFZsWlRRNU1ETTVORGc1WTJJell6QmlOR1pqTkRRNFkyTTVOUQ',1,1,60,'{\"url\": \"zl://propertyrepair/create?type=user&taskCategoryId=0&displayName=物业服务\"}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'park_tourist',0,11,6);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','物业缴费','物业缴费','cs://1/image/aW1hZ2UvTVRvNE5tSmlZalkxTlRSaE5tWmxNemM0WVdReE1qQXlNbUU0T0RGbU16VTBNQQ',1,1,14,'{\"url\": \"https://core.zuolin.com/property_fee/index.html?hideNavigationBar=1#/bill_query?sign_suffix\"}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'park_tourist',0,11,7);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','电子屏预订','电子屏预订','cs://1/image/aW1hZ2UvTVRwa01HVm1PR0ppT1RGaU1UVm1ORFExTUdaa1pEQmhPRFZtTnpObE9UZ3laZw',1,1,49,'{\"resourceTypeId\": \"80003\", \"pageType\": 0}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'park_tourist',0,11,8);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','公共会议室','公共会议室','cs://1/image/aW1hZ2UvTVRvd1lXVmxaV1kzWVRjeE1HTmxZVE15Wkdaak0yTXpZV1ZqWVRoaU9UVTRPQQ',1,1,49,'{\"resourceTypeId\": \"80002\", \"pageType\": 0}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'park_tourist',0,11,9);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','停车充值','停车充值','cs://1/image/aW1hZ2UvTVRvek4yVmpPREEzTkRsalpXTTFOMk5qWldKak5tSm1OMlpqT1dGaE9XVXpOUQ',1,1,30,'{}',3,0,1,1,'1',0,NULL,NULL,NULL,0,'park_tourist',0,11,10);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','VIP车位','VIP车位','cs://1/image/aW1hZ2UvTVRvMVlqVTNNVFJrTkdWaE1ETTJaV1ExWldFM1pEQXhZVEV4TURJMk16SXlOUQ',1,1,49,'{\"resourceTypeId\": 8, \"pageType\": 0}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'park_tourist',0,11,11);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','通讯录','通讯录','cs://1/image/aW1hZ2UvTVRwak1ERTVaREEwWTJObVlqRm1PREkwTkRSaE9HTTRNREkyT1Roa01tSXdNZw',1,1,46,'{}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'park_tourist',0,12,12);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','打卡考勤','打卡考勤','cs://1/image/aW1hZ2UvTVRvNVpUQXpaRFpqWW1RNFlXSmxOVGRrWXprNVl6azFORFEzT0RjeFpUUmpZUQ',1,1,23,'{}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'park_tourist',0,12,13);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','会议室预订','会议室预订','cs://1/image/aW1hZ2UvTVRwa1pEVTNPREF5TldVME1qWmxOVEJqTkRJME1HTmxaR1JrTnpSaU56SmxaZw',1,1,49,'{\"resourceTypeId\": \"80001\", \"pageType\": 0}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'park_tourist',0,12,14);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','视频会议','视频会议','cs://1/image/aW1hZ2UvTVRveE5UazBabU5qWVRrMU56QmxaVEJqWkdReVpqSTNPV1V6WWpGaU5UUTBNQQ',1,1,14,'{\"url\": \"http://172.17.1.1:8080/\"}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'park_tourist',0,12,15);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','审批','审批','cs://1/image/aW1hZ2UvTVRvNFkyUmpNV0V4TmpVMU0yWXdOVFU1T1RNMk9XWTFOV016WmpSak5HTmxOUQ',1,1,54,'{}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'park_tourist',0,12,16);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','全部','全部','cs://1/image/aW1hZ2UvTVRvellqSXhNemd5T1RZNU5tWTNZV016TkRreE9HTTRaR1JqWmpneE5EWTBNdw',1,1,53,'{\"itemLocation\": \"/home\", \"itemGroup\": \"Default\"}',4,0,1,1,'1',0,NULL,NULL,NULL,0,'park_tourist',0,NULL,17);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Bizs','Volgo caffe','Volgo caffe','cs://1/image/aW1hZ2UvTVRvMVl6bGlNekZrTlRkbE9ETmtNMlptTjJFeU1ERTBNbUV4TlRReE5XWm1OUQ',1,1,13,'{\"url\": \"https://biz.zuolin.com/zl-ec/rest/service/front/logon?hideNavigationBar=1&sourceUrl=https%3a%2f%2fbiz.zuolin.com%2fnar%2fbiz%2fweb%2fapp%2fuser%2findex.html%23%2fmicroshop%2fhome%3fisfromindex%3d0%26_k%3dzlbiz#sign_suffix\"}',0,0,1,1,'1',0,NULL,NULL,NULL,0,'park_tourist',0,NULL,0);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','OPPushBiz','新品推荐','新品推荐',NULL,1,1,13,'{\"url\": \"https://biz.zuolin.com/zl-ec/rest/service/front/logon?hideNavigationBar=1&sourceUrl=https%3a%2f%2fbiz.zuolin.com%2fnar%2fbiz%2fweb%2fapp%2fuser%2findex.html%23%2fmicroshop%2fhome%3fisfromindex%3d0%26_k%3dzlbiz#sign_suffix\"}',0,0,1,1,'1',0,NULL,NULL,NULL,0,'park_tourist',0,NULL,0);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','OPPushActivity','最新活动','最新活动',NULL,1,1,61,'{\"title\": \"最新活动\", \"scope\": \"2\", \"publishPrivilege\": \"1\", \"style\": \"4\", \"livePrivilege\": \"1\", \"categoryId\": 1, \"listStyle\": \"2\"}',0,0,1,1,'1',0,NULL,NULL,NULL,0,'park_tourist',0,NULL,0);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','服务热线','服务热线','cs://1/image/aW1hZ2UvTVRvelpXRm1NV0UzWXpZNFpqRmpZekExWlRBNVl6QTBOalZqWVdJeFkyVmhNUQ',1,1,45,'{}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'default',0,13,0);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','小区公告','小区公告','cs://1/image/aW1hZ2UvTVRvMk9XWmtOVEV4TnpWallXWm1OVE0yTldNd1pXRXlaRFV4TW1WbE9HTTBOUQ',1,1,15,'{\"actionCategory\": 0, \"contentCategory\": \"1003\", \"forumId\": 1, \"entityTag\": \"PM\", \"embedAppId\": \"0\"}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'default',0,13,1);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','小区活动','小区活动','cs://1/image/aW1hZ2UvTVRvNVptSmlOelJrWWpRME5UazNOV1pqTURnME1qSTRNMlV5TnpjM1pHWTFNZw',1,1,50,'{}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'default',0,13,2);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','小区论坛','小区论坛','cs://1/image/aW1hZ2UvTVRvM1kyTXdPRGhqT0RjNU5UWmtOREEwWm1FeVlqSTJOMkk0WW1SaE5tRTBZZw',1,1,62,'{}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'default',0,13,3);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','门禁','门禁','cs://1/image/aW1hZ2UvTVRvMVpHRXpNV0UyTmprek5EVTRZMk00TTJJME56Rm1Oak16TUdVNE5qVTRaUQ',1,1,40,'{\"isSupportQR\": 1, \"isSupportSmart\": 0}',1,0,1,1,'1',0,NULL,NULL,NULL,0,'default',0,13,4);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','物业服务','物业服务','cs://1/image/aW1hZ2UvTVRwbE1tUTFZVFZsWlRRNU1ETTVORGc1WTJJell6QmlOR1pqTkRRNFkyTTVOUQ',1,1,60,'{\"url\": \"zl://propertyrepair/create?type=user&taskCategoryId=0&displayName=物业服务\"}',2,0,1,1,'1',0,NULL,NULL,NULL,0,'default',0,13,5);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','物业缴费','物业缴费','cs://1/image/aW1hZ2UvTVRvNE5tSmlZalkxTlRSaE5tWmxNemM0WVdReE1qQXlNbUU0T0RGbU16VTBNQQ',1,1,14,'{\"url\": \"https://core.zuolin.com/property_fee/index.html?hideNavigationBar=1#/bill_query?sign_suffix\"}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'default',0,13,6);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','管道疏通','管道疏通','cs://1/image/aW1hZ2UvTVRveVpXWXhORE5pT1dFME56VTVaR0psTmpBM1ltUmlOall5WWpSbE56UTVZUQ',1,1,14,'{\"url\": \"http://www.jsb.so/shopex/\"}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'default',0,13,7);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','家政服务','家政服务','cs://1/image/aW1hZ2UvTVRvNFpqbGpZbUk1TnpWaE9HWmxNV0kyT1RBMk1qWXlZMkkyWldSbFltTmpOZw',1,1,14,'{\"url\": \"http://koala.yunjiazheng.com/\"}',3,0,1,1,'1',0,NULL,NULL,NULL,0,'default',0,13,8);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','快递查询','快递查询','cs://1/image/aW1hZ2UvTVRwbU5tRTBOVGRpWVRJMU9UYzNZVGszTkdJM09HWTFabVkyWWpVeFl6UXlaZw',1,1,14,'{\"url\": \"http://m.kuaidi100.com/\"}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'default',0,13,9);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','停车充值','停车充值','cs://1/image/aW1hZ2UvTVRvek4yVmpPREEzTkRsalpXTTFOMk5qWldKak5tSm1OMlpqT1dGaE9XVXpOUQ',1,1,30,'{}',0,0,1,0,'1',0,NULL,NULL,NULL,0,'default',0,13,10);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Default','全部','全部','cs://1/image/aW1hZ2UvTVRvellqSXhNemd5T1RZNU5tWTNZV016TkRreE9HTTRaR1JqWmpneE5EWTBNdw',1,1,53,'{\"itemLocation\": \"/home\", \"itemGroup\": \"Default\"}',4,0,1,1,'1',0,NULL,NULL,NULL,0,'default',0,NULL,11);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','Bizs','Volgo caffe','Volgo caffe','cs://1/image/aW1hZ2UvTVRvMVl6bGlNekZrTlRkbE9ETmtNMlptTjJFeU1ERTBNbUV4TlRReE5XWm1OUQ',1,1,13,'{\"url\": \"https://biz.zuolin.com/zl-ec/rest/service/front/logon?hideNavigationBar=1&sourceUrl=https%3a%2f%2fbiz.zuolin.com%2fnar%2fbiz%2fweb%2fapp%2fuser%2findex.html%23%2fmicroshop%2fhome%3fisfromindex%3d0%26_k%3dzlbiz#sign_suffix\"}',0,0,1,1,'1',0,NULL,NULL,NULL,0,'default',0,NULL,0);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','OPPushBiz','新品推荐','新品推荐',NULL,1,1,13,'{\"url\": \"https://biz.zuolin.com/zl-ec/rest/service/front/logon?hideNavigationBar=1&sourceUrl=https%3a%2f%2fbiz.zuolin.com%2fnar%2fbiz%2fweb%2fapp%2fuser%2findex.html%23%2fmicroshop%2fhome%3fisfromindex%3d0%26_k%3dzlbiz#sign_suffix\"}',0,0,1,1,'1',0,NULL,NULL,NULL,0,'default',0,NULL,0);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `more_order`) VALUES (@id:=@id+1,0,0,0,0,'/home','OPPushActivity','最新活动','最新活动',NULL,1,1,61,'{\"title\": \"小区活动\", \"scope\": \"2\", \"publishPrivilege\": \"1\", \"style\": \"4\", \"livePrivilege\": \"1\", \"categoryId\": 1, \"listStyle\": \"2\"}',0,0,1,1,'1',0,NULL,NULL,NULL,0,'default',0,NULL,0);


