-- by dengs,2017.08.28 快递2.0
set @namespaceId = 999968; -- 国贸namespaceId
set @community_id = 240111044331050363;
-- 国贸EMS快递公司 -- 图标待定 --url等，待定 -- TODO
set @guo_mao_ems_logo = 'cs://1/image/aW1hZ2UvTVRwak9XSTJOVFJqWXpjMVkyTmtNVGt4WW1NNU1qaGlNR0k1WlRNelpXRTJNdw';
set @guo_mao_ems_order_url = 'http://60.205.8.187:18001/api/gateway';
set @guo_mao_ems_logistics_url = 'http://60.205.8.187:18001/api/gateway';
set @guo_mao_ems_app_key = '461bdd5e2655492434936e96fd3eab7d';
set @guo_mao_ems_app_secret = '9134a30fdfba770d1b64438d9d0aafed';
set @guo_mao_ems_authorization = '7cacaabcbb996fdcbe4b42096e09724c';
INSERT INTO `eh_express_companies` (`id`, `namespace_id`, `owner_type`, `owner_id`, `parent_id`, `name`, `logo`, `description`, `order_url`, `logistics_url`, `app_key`, `app_secret`, `authorization`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES ('2', @namespaceId, 'EhNamespaces', @namespaceId, '0', 'EMS', @guo_mao_ems_logo, '国贸项目，EMS快递公司', @guo_mao_ems_order_url,@guo_mao_ems_logistics_url, @guo_mao_ems_app_key, @guo_mao_ems_app_secret, @guo_mao_ems_authorization, '2', '0', NOW(), NOW(), '0');
INSERT INTO `eh_express_companies` (`id`, `namespace_id`, `owner_type`, `owner_id`, `parent_id`, `name`, `logo`, `description`, `order_url`, `logistics_url`, `app_key`, `app_secret`, `authorization`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES ('10003', @namespaceId, 'community', @community_id, '2', 'EMS', '', '国贸项目，EMS快递公司', NULL,NULL, NULL, NULL, NULL, '2', '0', NOW(), NOW(), '0');
-- 国贸中国邮政快递公司
set @guo_mao_chinapost_logo = 'cs://1/image/aW1hZ2UvTVRvM1pEWTBOamxrWW1SbE1EQXlZamcwTlRsbE1qVTFPR1UyWkRVd04yTXdaUQ';
set @guo_mao_chinapost_order_url = 'http://222.222.2.155:8001';
set @guo_mao_chinapost_logistics_url = 'http://211.156.198.97/zdxtJkServer/zhddws/MailTtService_Gn?wsdl';
set @guo_mao_chinapost_app_key = '123';
set @guo_mao_chinapost_app_secret = 'FC480127D90D26DE382506EE5D409F46';
INSERT INTO `eh_express_companies` (`id`, `namespace_id`, `owner_type`, `owner_id`, `parent_id`, `name`, `logo`, `description`, `order_url`, `logistics_url`, `app_key`, `app_secret`, `authorization`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES ('3', @namespaceId, 'EhNamespaces', @namespaceId, '0', '中国邮政', @guo_mao_chinapost_logo, '国贸项目，中国邮政快递公司', @guo_mao_chinapost_order_url,@guo_mao_chinapost_logistics_url, @guo_mao_chinapost_app_key, @guo_mao_chinapost_app_secret, NULL, '2', '0', NOW(), NOW(), '0');
INSERT INTO `eh_express_companies` (`id`, `namespace_id`, `owner_type`, `owner_id`, `parent_id`, `name`, `logo`, `description`, `order_url`, `logistics_url`, `app_key`, `app_secret`, `authorization`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES ('10004', @namespaceId, 'community', @community_id, '3', '中国邮政', '', '国贸项目，中国邮政快递公司', NULL,NULL, NULL, NULL, NULL, '2', '0', NOW(), NOW(), '0');
-- 华润的EMS的namespace改成 华润namespaceid 999985
UPDATE `eh_express_companies` SET `namespace_id`=999985, `owner_type`='EhNamespaces',`owner_id`=999985 WHERE `id`= 1;

-- 标签的基本设置
INSERT INTO `eh_express_param_settings` (`id`, `namespace_id`, `owner_type`, `owner_id`, `express_user_setting_show_flag`, `business_note_setting_show_flag`, `hotline_setting_show_flag`, `hotline_flag`, `business_note`, `business_note_flag`, `send_mode`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES (1, 999985, 'EhNamespaces', 999985, 1, 1, 1, NULL, NULL, NULL,1, 2, 0, NOW(), NOW(), 0);
INSERT INTO `eh_express_param_settings` (`id`, `namespace_id`, `owner_type`, `owner_id`, `express_user_setting_show_flag`, `business_note_setting_show_flag`, `hotline_setting_show_flag`, `hotline_flag`, `business_note`, `business_note_flag`, `send_mode`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES (2, @namespaceId, 'EhNamespaces', @namespaceId, 0, 1, 1, NULL, NULL, NULL,2, 2, 0, NOW(), NOW(), 0);

-- 国贸 热线与业务说明的初始化数据
INSERT INTO `eh_express_param_settings` (`id`, `namespace_id`, `owner_type`, `owner_id`, `express_user_setting_show_flag`, `business_note_setting_show_flag`, `hotline_setting_show_flag`, `hotline_flag`, `business_note`, `business_note_flag`, `send_mode`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES (3, 999985, 'community',240111044331055035, 0, 1, 1, 0, '', 0, NULL, 2, 0, NOW(), NOW(), 0);
INSERT INTO `eh_express_param_settings` (`id`, `namespace_id`, `owner_type`, `owner_id`, `express_user_setting_show_flag`, `business_note_setting_show_flag`, `hotline_setting_show_flag`, `hotline_flag`, `business_note`, `business_note_flag`, `send_mode`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES (4, 999985, 'community', 240111044331055036, 0, 1, 1, 0, '', 0, NULL, 2, 0, NOW(), NOW(), 0);
INSERT INTO `eh_express_param_settings` (`id`, `namespace_id`, `owner_type`, `owner_id`, `express_user_setting_show_flag`, `business_note_setting_show_flag`, `hotline_setting_show_flag`, `hotline_flag`, `business_note`, `business_note_flag`, `send_mode`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES (5, @namespaceId, 'community', @community_id, 0, 1, 1, 0, '', 0, NULL, 2, 0, NOW(), NOW(), 0);
-- 业务包装类型文案等
INSERT INTO `eh_express_company_businesses` (`id`, `namespace_id`, `owner_type`, `owner_id`, `express_company_id`, `send_type`, `send_type_name`, `package_types`, `insured_documents`, `order_status_collections`, `pay_type`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES ('1', 999985, 'EhNamespaces', 999985, '1', '1', '标准快递', '[]', NULL, '[{"status": 1},{"status": 2},{"status": 3},{"status": 4}]', '1', '2', '0', NOW(), NOW(), '0');
-- EMS业务暂时 去掉包装类型 {"packageType": 3},{"packageType": 1}
INSERT INTO `eh_express_company_businesses` (`id`, `namespace_id`, `owner_type`, `owner_id`, `express_company_id`, `send_type`, `send_type_name`, `package_types`, `insured_documents`, `order_status_collections`, `pay_type`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES ('2', @namespaceId, 'EhNamespaces', @namespaceId, '2', '3', 'EMS标准快递', '[]', '请确认寄件物品价值不超过5万元，贵重物品务必保价，保价费=保价金额*0.5%，最低1元','[{"status": 1},{"status": 2},{"status": 5},{"status": 4}]', '2', '2', '0', NOW(), NOW(), '0');
INSERT INTO `eh_express_company_businesses` (`id`, `namespace_id`, `owner_type`, `owner_id`, `express_company_id`, `send_type`, `send_type_name`, `package_types`, `insured_documents`, `order_status_collections`, `pay_type`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES ('3', @namespaceId, 'EhNamespaces', @namespaceId, '3', '9', '邮政快递包裹', '[{"packageType": 3},{"packageType": 2},{"packageType": 1}]', '请确认寄件物品价值不超过2万元，贵重物品务必保价，保价费=保价金额*1%，最低2元', '[{"status": 1},{"status": 2},{"status": 5},{"status": 4}]','1',  '2', '0', NOW(), NOW(), '0');
INSERT INTO `eh_express_company_businesses` (`id`, `namespace_id`, `owner_type`, `owner_id`, `express_company_id`, `send_type`, `send_type_name`, `package_types`, `insured_documents`, `order_status_collections`, `pay_type`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES ('4', @namespaceId, 'EhNamespaces', @namespaceId, '3', '2', '同城信筒快件', '[{"packageType": 4},{"packageType": 5}]', NULL, '[{"status": 1},{"status": 2},{"status": 5},{"status": 4}]', '1', '2', '0', NOW(), NOW(), '0');

-- 国贸单点登录的appkey，和seckey
set @appKey = 'de875e40-1c5f-4a0c-94a6-0b37421b8554';
set @secretKey = 'k9+3iUUSlUah1Uggv5ZKbTEktcIuvs7834ZThJS/CmA4eVBR2msOBak9uvut1Io0gZ9tdFJ0LpJ9ELfes8XXZw==';

set @eh_apps_id = (select MAX(id) FROM eh_apps);
INSERT INTO `eh_apps` (`id`, `creator_uid`, `app_key`, `secret_key`, `name`, `description`, `status`, `create_time`, `update_uid`, `update_time`) VALUES ((@eh_apps_id:=@eh_apps_id+1), '1', @appKey, @secretKey, 'guomao', 'guomao app key', '1', NOW(), NULL, NULL);
-- appkey mapping namespace
set @eh_app_namespace_mappings_id = (select MAX(id) FROM eh_app_namespace_mappings);
INSERT INTO `eh_app_namespace_mappings` (`id`, `namespace_id`, `app_key`, `community_id`) VALUES ((@eh_app_namespace_mappings_id:=@eh_app_namespace_mappings_id+1), @namespace_id, @appKey, @community_id);

-- 菜单修改 by dengs 2017.07.31
UPDATE eh_web_menus SET  `name` = '参数设置' where id = 40710;
UPDATE eh_web_menus SET  `name` = '订单管理' where id = 40720;

-- payserverapp支付接口地址
SET @configuration_id = (SELECT MAX(id) FROM `eh_configurations`);
INSERT INTO `eh_configurations` (`id`, `name`, `value`, `description`, `namespace_id`, `display_name`)
    VALUES (@configuration_id:=@configuration_id+1, 'guomao.payserver.url', 'http://pay.zuolin.com/EDS_PAY/rest/pay_common/payInfo_record/save_payInfo_record', '左邻支付平台地址', 0, NULL);
-- 修改快递连接地址
UPDATE eh_launch_pad_items SET action_data = '{"url":"https://core.zuolin.com/deliver/dist/index.html#/home_page#sign_suffix"}' WHERE namespace_id = 999985 AND item_label = '快递';

-- by dengs,2017.08.28 快递2.0 end

-- add by sw 20170828
DELETE from eh_parking_lots where id = 10002;
UPDATE `eh_parking_lots` SET `config_json`='{\"tempfeeFlag\": 1, \"rateFlag\": 1, \"lockCarFlag\": 1, \"searchCarFlag\": 0, \"currentInfoType\": 1, \"contact\": \"13632650699\"}' WHERE `id`='10001';
UPDATE `eh_parking_lots` SET `config_json`='{\"tempfeeFlag\": 0, \"rateFlag\": 0, \"lockCarFlag\": 0, \"searchCarFlag\": 0, \"currentInfoType\": 0, \"contact\": \"13510551322\"}' WHERE `id`='10003';
UPDATE `eh_parking_lots` SET `config_json`='{\"tempfeeFlag\": 1, \"rateFlag\": 0, \"lockCarFlag\": 0, \"searchCarFlag\": 0, \"currentInfoType\": 0, \"contact\": \"18927485550\"}' WHERE `id`='10004';
UPDATE `eh_parking_lots` SET `config_json`='{\"tempfeeFlag\": 1, \"rateFlag\": 0, \"lockCarFlag\": 0, \"searchCarFlag\": 1, \"currentInfoType\": 2, \"contact\": \"18718523489\"}', expired_recharge_json='{"expiredRechargeFlag":1, "maxExpiredDay":365, "expiredRechargeMonthCount":1, "expiredRechargeType":1}' WHERE `id`='10006';
UPDATE `eh_parking_lots` SET `config_json`='{\"tempfeeFlag\": 1, \"rateFlag\": 1, \"lockCarFlag\": 0, \"searchCarFlag\": 0, \"currentInfoType\": 0, \"contact\": \"13918348877\"}' WHERE `id`='10021';
UPDATE `eh_parking_lots` SET `config_json`='{\"tempfeeFlag\": 1, \"rateFlag\": 0, \"lockCarFlag\": 0, \"searchCarFlag\": 0, \"currentInfoType\": 0, \"contact\": \"18051307125\"}' WHERE `id`='10023';
INSERT INTO `eh_parking_lots` (`id`, `owner_type`, `owner_id`, `name`, `vendor_name`, `vendor_lot_token`, `status`, `creator_uid`, `create_time`, `namespace_id`, `expired_recharge_json`, `config_json`)
  VALUES ('10011', 'community', '240111044331050370', '软件产业基地停车场', 'XIAOMAO', NULL, '2', '1025', '2016-12-16 17:07:20', '0', NULL, '{\"tempfeeFlag\": 1, \"rateFlag\": 1, \"lockCarFlag\": 1, \"searchCarFlag\": 0, \"currentInfoType\": 1, \"contact\": \"18665331243\"}');
INSERT INTO `eh_parking_lots` (`id`, `owner_type`, `owner_id`, `name`, `vendor_name`, `vendor_lot_token`, `status`, `creator_uid`, `create_time`, `namespace_id`, `expired_recharge_json`, `config_json`)
  VALUES ('10012', 'community', '240111044331050371', '创投大厦停车场', 'XIAOMAO', NULL, '2', '1025', '2016-12-16 17:07:20', '0', NULL, '{\"tempfeeFlag\": 1, \"rateFlag\": 1, \"lockCarFlag\": 1, \"searchCarFlag\": 0, \"currentInfoType\": 1, \"contact\": \"18665331243\"}');
INSERT INTO `eh_parking_lots` (`id`, `owner_type`, `owner_id`, `name`, `vendor_name`, `vendor_lot_token`, `status`, `creator_uid`, `create_time`, `namespace_id`, `expired_recharge_json`, `config_json`)
  VALUES ('10013', 'community', '240111044331050369', '生态园停车场', 'Mybay', NULL, '2', '1025', '2016-12-16 17:07:20', '0', NULL, '{\"tempfeeFlag\": 1, \"rateFlag\": 0, \"lockCarFlag\": 0, \"searchCarFlag\": 0, \"currentInfoType\": 2, \"contact\": \"18665331243\"}');

INSERT INTO `eh_configurations` ( `name`, `value`, `description`, `namespace_id`, `display_name`) VALUES ( 'parking.mybay.url', 'http://220.160.111.114:9099', '深圳湾停车充值key', '0', NULL);
INSERT INTO `eh_configurations` ( `name`, `value`, `description`, `namespace_id`, `display_name`) VALUES ( 'parking.mybay.key', 'F7A0B971B199FD2A1017CEC5', '深圳湾停车充值key', '0', NULL);
INSERT INTO `eh_configurations` ( `name`, `value`, `description`, `namespace_id`, `display_name`) VALUES ( 'parking.mybay.user', 'ktapi', '深圳湾停车充值用户名', '0', NULL);
INSERT INTO `eh_configurations` ( `name`, `value`, `description`, `namespace_id`, `display_name`) VALUES ( 'parking.mybay.pwd', '0306A9', '深圳湾停车充值密码', '0', NULL);


-- By lei.lv
-- layout数据
delete from eh_launch_pad_layouts where namespace_id = 999971;
INSERT INTO `eh_launch_pad_layouts` (`id`, `namespace_id`, `name`, `layout_json`, `version_code`, `min_version_code`, `status`, `create_time`, `scene_type`, `scope_code`, `scope_id`, `apply_policy`) VALUES ('600', '999971', 'ServiceMarketLayout', '{\"versionCode\":\"2017082007\",\"versionName\":\"4.4.0\",\"layoutName\":\"ServiceMarketLayout\",\"displayName\":\"服务市场\",\"groups\":[{\"groupName\":\"\",\"widget\":\"Banners\",\"instanceConfig\":{\"itemGroup\":\"Default\"},\"style\":\"Default\",\"defaultOrder\":1,\"separatorFlag\":0,\"separatoeparatorHeight\":0},{\"groupName\":\"商家服务\",\"widget\":\"Navigator\",\"instanceConfig\":{\"itemGroup\":\"Bizs\"},\"style\":\"Default\",\"separatorFlag\":1,\"separatorHeight\":1,\"defaultOrder\":5,\"columnCount\":4},{\"groupName\":\"\",\"widget\":\"Bulletins\",\"instanceConfig\":{\"itemGroup\":\"Default\",\"paddingTop\":1},\"style\":\"Default\",\"defaultOrder\":3},{\"groupName\":\"\",\"widget\":\"Navigator\",\"instanceConfig\":{\"itemGroup\":\"EnterpriseServices\",\"cssStyleFlag\":1,\"paddingTop\":20,\"paddingLeft\":20,\"paddingBottom\":40,\"paddingRight\":20,\"lineSpacing\":16,\"columnSpacing\":16,\"backgroundColor\":\"#FFFFFF\"},\"style\":\"Gallery\",\"defaultOrder\":2,\"separatorFlag\":1,\"columnCount\":2},{\"groupName\":\"\",\"widget\":\"NewsFlash\",\"instanceConfig\":{\"timeWidgetStyle\":\"datetime\",\"categoryId\":0,\"itemGroup\":\"Default\",\"newsSize\":3},\"style\":\"Default\",\"defaultOrder\":1}]}', '2017082007', '0', '2', '2017-08-22 10:53:21', 'pm_admin', '0', '0', '0');
INSERT INTO `eh_launch_pad_layouts` (`id`, `namespace_id`, `name`, `layout_json`, `version_code`, `min_version_code`, `status`, `create_time`, `scene_type`, `scope_code`, `scope_id`, `apply_policy`) VALUES ('601', '999971', 'ServiceMarketLayout', '{\"versionCode\":\"2017082007\",\"versionName\":\"4.4.0\",\"layoutName\":\"ServiceMarketLayout\",\"displayName\":\"服务市场\",\"groups\":[{\"groupName\":\"\",\"widget\":\"Banners\",\"instanceConfig\":{\"itemGroup\":\"Default\"},\"style\":\"Default\",\"defaultOrder\":1,\"separatorFlag\":0,\"separatoeparatorHeight\":0},{\"groupName\":\"商家服务\",\"widget\":\"Navigator\",\"instanceConfig\":{\"itemGroup\":\"Bizs\"},\"style\":\"Default\",\"separatorFlag\":1,\"separatorHeight\":1,\"defaultOrder\":5,\"columnCount\":4},{\"groupName\":\"\",\"widget\":\"Bulletins\",\"instanceConfig\":{\"itemGroup\":\"Default\",\"paddingTop\":1},\"style\":\"Default\",\"defaultOrder\":3},{\"groupName\":\"\",\"widget\":\"Navigator\",\"instanceConfig\":{\"itemGroup\":\"EnterpriseServices\",\"cssStyleFlag\":1,\"paddingTop\":20,\"paddingLeft\":20,\"paddingBottom\":40,\"paddingRight\":20,\"lineSpacing\":16,\"columnSpacing\":16,\"backgroundColor\":\"#FFFFFF\"},\"style\":\"Gallery\",\"defaultOrder\":2,\"separatorFlag\":1,\"columnCount\":2},{\"groupName\":\"\",\"widget\":\"NewsFlash\",\"instanceConfig\":{\"timeWidgetStyle\":\"datetime\",\"categoryId\":0,\"itemGroup\":\"Default\",\"newsSize\":3},\"style\":\"Default\",\"defaultOrder\":1}]}', '2017082007', '0', '2', '2017-08-22 10:53:22', 'park_tourist', '0', '0', '0');
INSERT INTO `eh_launch_pad_layouts` (`id`, `namespace_id`, `name`, `layout_json`, `version_code`, `min_version_code`, `status`, `create_time`, `scene_type`, `scope_code`, `scope_id`, `apply_policy`) VALUES ('602', '999971', 'ServiceMarketLayout', '{\"versionCode\":\"2017082007\",\"versionName\":\"4.4.0\",\"layoutName\":\"ServiceMarketLayout\",\"displayName\":\"服务市场\",\"groups\":[{\"groupName\":\"\",\"widget\":\"Banners\",\"instanceConfig\":{\"itemGroup\":\"Default\"},\"style\":\"Default\",\"defaultOrder\":1,\"separatorFlag\":0,\"separatoeparatorHeight\":0},{\"groupName\":\"商家服务\",\"widget\":\"Navigator\",\"instanceConfig\":{\"itemGroup\":\"Bizs\"},\"style\":\"Default\",\"separatorFlag\":1,\"separatorHeight\":1,\"defaultOrder\":5,\"columnCount\":3},{\"groupName\":\"\",\"widget\":\"Bulletins\",\"instanceConfig\":{\"itemGroup\":\"Default\",\"paddingTop\":1},\"style\":\"Default\",\"defaultOrder\":3},{\"groupName\":\"\",\"widget\":\"Navigator\",\"instanceConfig\":{\"itemGroup\":\"EnterpriseServices\",\"cssStyleFlag\":1,\"paddingTop\":20,\"paddingLeft\":20,\"paddingBottom\":60,\"paddingRight\":20,\"lineSpacing\":16,\"columnSpacing\":16,\"backgroundColor\":\"#FFFFFF\"},\"style\":\"Gallery\",\"defaultOrder\":2,\"separatorFlag\":1,\"columnCount\":2},{\"groupName\":\"\",\"widget\":\"NewsFlash\",\"instanceConfig\":{\"timeWidgetStyle\":\"datetime\",\"categoryId\":0,\"itemGroup\":\"Default\",\"newsSize\":3},\"style\":\"Default\",\"defaultOrder\":1}]}', '2017082007', '0', '2', '2017-08-22 10:53:22', 'default', '0', '0', '0');


-- eh_communities表数据
DELETE FROM eh_communities where namespace_id = 999971;
SET @eh_communities_id = (SELECT MAX(id) from eh_communities);
INSERT INTO `eh_communities` (`id`, `uuid`, `city_id`, `city_name`, `area_id`, `area_name`, `name`, `alias_name`, `address`, `zipcode`, `description`, `detail_description`, `apt_segment1`, `apt_segment2`, `apt_segment3`, `apt_seg1_sample`, `apt_seg2_sample`, `apt_seg3_sample`, `apt_count`, `creator_uid`, `operator_uid`, `status`, `create_time`, `delete_time`, `integral_tag1`, `integral_tag2`, `integral_tag3`, `integral_tag4`, `integral_tag5`, `string_tag1`, `string_tag2`, `string_tag3`, `string_tag4`, `string_tag5`, `community_type`, `default_forum_id`, `feedback_forum_id`, `update_time`, `namespace_id`, `area_size`) VALUES ('240111044331050388', '9c63e9e7-6d48-11e7-a008-0242ac110006', '14809', '上海市', '14810', '浦东新区', '张江大厦', '张江大厦', '松涛路560号', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '214', '1', NULL, '2', '2017-07-20 12:40:28', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', '190570', '190571', '2017-07-20 12:40:28', '999971', NULL);
INSERT INTO `eh_communities` (`id`, `uuid`, `city_id`, `city_name`, `area_id`, `area_name`, `name`, `alias_name`, `address`, `zipcode`, `description`, `detail_description`, `apt_segment1`, `apt_segment2`, `apt_segment3`, `apt_seg1_sample`, `apt_seg2_sample`, `apt_seg3_sample`, `apt_count`, `creator_uid`, `operator_uid`, `status`, `create_time`, `delete_time`, `integral_tag1`, `integral_tag2`, `integral_tag3`, `integral_tag4`, `integral_tag5`, `string_tag1`, `string_tag2`, `string_tag3`, `string_tag4`, `string_tag5`, `community_type`, `default_forum_id`, `feedback_forum_id`, `update_time`, `namespace_id`, `area_size`) VALUES ('240111044331050389', '9c63e9e7-6d48-11e7-a008-0242ac110007', '14809', '上海市', '14810', '浦东新区', '天之骄子专家楼', '天之骄子专家楼', '上海市浦东新区盛夏路58弄', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '214', '1', NULL, '2', '2017-07-20 12:40:28', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '190570', '190571', '2017-07-20 12:40:28', '999971', NULL);
INSERT INTO `eh_communities` (`id`, `uuid`, `city_id`, `city_name`, `area_id`, `area_name`, `name`, `alias_name`, `address`, `zipcode`, `description`, `detail_description`, `apt_segment1`, `apt_segment2`, `apt_segment3`, `apt_seg1_sample`, `apt_seg2_sample`, `apt_seg3_sample`, `apt_count`, `creator_uid`, `operator_uid`, `status`, `create_time`, `delete_time`, `integral_tag1`, `integral_tag2`, `integral_tag3`, `integral_tag4`, `integral_tag5`, `string_tag1`, `string_tag2`, `string_tag3`, `string_tag4`, `string_tag5`, `community_type`, `default_forum_id`, `feedback_forum_id`, `update_time`, `namespace_id`, `area_size`) VALUES (@eh_communities_id+1, '9c63e9e7-6d48-11e7-a008-0242ac110018', '14809', '上海市', '14810', '浦东新区', '领袖之都(东块、股份)', '领袖之都(东块、股份)', '张东路1387号', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '214', '1', NULL, '2', '2017-07-20 12:40:28', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', '190570', '190571', '2017-07-20 12:40:28', '999971', NULL);
INSERT INTO `eh_communities` (`id`, `uuid`, `city_id`, `city_name`, `area_id`, `area_name`, `name`, `alias_name`, `address`, `zipcode`, `description`, `detail_description`, `apt_segment1`, `apt_segment2`, `apt_segment3`, `apt_seg1_sample`, `apt_seg2_sample`, `apt_seg3_sample`, `apt_count`, `creator_uid`, `operator_uid`, `status`, `create_time`, `delete_time`, `integral_tag1`, `integral_tag2`, `integral_tag3`, `integral_tag4`, `integral_tag5`, `string_tag1`, `string_tag2`, `string_tag3`, `string_tag4`, `string_tag5`, `community_type`, `default_forum_id`, `feedback_forum_id`, `update_time`, `namespace_id`, `area_size`) VALUES (@eh_communities_id+2, '9c63e9e7-6d48-11e7-a008-0242ac110019', '14809', '上海市', '14810', '浦东新区', '领袖之都(东块、集电)', '领袖之都(东块、集电)', '张东路1387号', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '214', '1', NULL, '2', '2017-07-20 12:40:28', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', '190570', '190571', '2017-07-20 12:40:28', '999971', NULL);
INSERT INTO `eh_communities` (`id`, `uuid`, `city_id`, `city_name`, `area_id`, `area_name`, `name`, `alias_name`, `address`, `zipcode`, `description`, `detail_description`, `apt_segment1`, `apt_segment2`, `apt_segment3`, `apt_seg1_sample`, `apt_seg2_sample`, `apt_seg3_sample`, `apt_count`, `creator_uid`, `operator_uid`, `status`, `create_time`, `delete_time`, `integral_tag1`, `integral_tag2`, `integral_tag3`, `integral_tag4`, `integral_tag5`, `string_tag1`, `string_tag2`, `string_tag3`, `string_tag4`, `string_tag5`, `community_type`, `default_forum_id`, `feedback_forum_id`, `update_time`, `namespace_id`, `area_size`) VALUES (@eh_communities_id+3, '9c63e9e7-6d48-11e7-a008-0242ac110020', '14809', '上海市', '14810', '浦东新区', '领袖之都(西块、集电)', '领袖之都(西块、集电)', '张东路1388号', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '214', '1', NULL, '2', '2017-07-20 12:40:28', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', '190570', '190571', '2017-07-20 12:40:28', '999971', NULL);
-- 测试数据
INSERT INTO `eh_communities` (`id`, `uuid`, `city_id`, `city_name`, `area_id`, `area_name`, `name`, `alias_name`, `address`, `zipcode`, `description`, `detail_description`, `apt_segment1`, `apt_segment2`, `apt_segment3`, `apt_seg1_sample`, `apt_seg2_sample`, `apt_seg3_sample`, `apt_count`, `creator_uid`, `operator_uid`, `status`, `create_time`, `delete_time`, `integral_tag1`, `integral_tag2`, `integral_tag3`, `integral_tag4`, `integral_tag5`, `string_tag1`, `string_tag2`, `string_tag3`, `string_tag4`, `string_tag5`, `community_type`, `default_forum_id`, `feedback_forum_id`, `update_time`, `namespace_id`, `area_size`) VALUES (@eh_communities_id+4, '9c63e9e7-6d48-11e7-a008-0242ac110017', '14809', '上海市', '14810', '浦东新区', '天之骄子人才公寓测试地址1号', '人才公寓1号', '上海市浦东新区盛夏路58弄', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '214', '1', NULL, '2', '2017-07-20 12:40:28', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '190570', '190571', '2017-07-20 12:40:28', '999971', NULL);
INSERT INTO `eh_communities` (`id`, `uuid`, `city_id`, `city_name`, `area_id`, `area_name`, `name`, `alias_name`, `address`, `zipcode`, `description`, `detail_description`, `apt_segment1`, `apt_segment2`, `apt_segment3`, `apt_seg1_sample`, `apt_seg2_sample`, `apt_seg3_sample`, `apt_count`, `creator_uid`, `operator_uid`, `status`, `create_time`, `delete_time`, `integral_tag1`, `integral_tag2`, `integral_tag3`, `integral_tag4`, `integral_tag5`, `string_tag1`, `string_tag2`, `string_tag3`, `string_tag4`, `string_tag5`, `community_type`, `default_forum_id`, `feedback_forum_id`, `update_time`, `namespace_id`, `area_size`) VALUES (@eh_communities_id+5, '9c63e9e7-6d48-11e7-a008-0242ac1100120', '14809', '上海市', '14810', '浦东新区', '天之骄子人才公寓测试地址2号', '人才公寓2号', '上海市浦东新区盛夏路58弄', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '214', '1', NULL, '2', '2017-07-20 12:40:28', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', '190570', '190571', '2017-07-20 12:40:28', '999971', NULL);
-- 测试数据结束


-- eh_organization_communities数据
DELETE from eh_organization_communities where organization_id = 1012516;
SET @oc_id = (SELECT MAX(id) from eh_organization_communities);
INSERT INTO `eh_organization_communities` (`id`, `organization_id`, `community_id`) VALUES (@oc_id+1, '1012516', @eh_communities_id+3);
INSERT INTO `eh_organization_communities` (`id`, `organization_id`, `community_id`) VALUES (@oc_id+2, '1012516', @eh_communities_id+2);
INSERT INTO `eh_organization_communities` (`id`, `organization_id`, `community_id`) VALUES (@oc_id+3, '1012516', @eh_communities_id+1);
INSERT INTO `eh_organization_communities` (`id`, `organization_id`, `community_id`) VALUES (@oc_id+4, '1012516', '240111044331050389');
INSERT INTO `eh_organization_communities` (`id`, `organization_id`, `community_id`) VALUES (@oc_id+5, '1012516', '240111044331050388');

-- 测试数据
INSERT INTO `eh_organization_communities` (`id`, `organization_id`, `community_id`) VALUES (@oc_id+6, '1012516', @eh_communities_id+5);
INSERT INTO `eh_organization_communities` (`id`, `organization_id`, `community_id`) VALUES (@oc_id+7, '1012516', @eh_communities_id+4);
-- 测试数据结束

-- eh_community_geopoints表数据
DELETE FROM eh_community_geopoints WHERE community_id in (240111044331050388,240111044331050389,@eh_communities_id+1,@eh_communities_id+2,@eh_communities_id+3,@eh_communities_id+4,@eh_communities_id+5);
SET @coge_id = (SELECT MAX(id) from eh_community_geopoints);
INSERT INTO `eh_community_geopoints` (`id`, `community_id`, `description`, `longitude`, `latitude`, `geohash`) VALUES (@coge_id+1, @eh_communities_id+3, '', '121.642243', '31.224285', 'uxypyxbzfxfr');
INSERT INTO `eh_community_geopoints` (`id`, `community_id`, `description`, `longitude`, `latitude`, `geohash`) VALUES (@coge_id+2, @eh_communities_id+2, '', '121.643166', '31.223298', 'uxypyxbpgxfr');
INSERT INTO `eh_community_geopoints` (`id`, `community_id`, `description`, `longitude`, `latitude`, `geohash`) VALUES (@coge_id+3, @eh_communities_id+1, '', '121.643166', '31.223298', 'uxypyxbpgxfr');
INSERT INTO `eh_community_geopoints` (`id`, `community_id`, `description`, `longitude`, `latitude`, `geohash`) VALUES (@coge_id+4, '240111044331050389', '', '0', '0', '7zzzzzzzzzzz');
INSERT INTO `eh_community_geopoints` (`id`, `community_id`, `description`, `longitude`, `latitude`, `geohash`) VALUES (@coge_id+5, '240111044331050388', '', '0', '0', '7zzzzzzzzzzz');

-- 测试数据
INSERT INTO `eh_community_geopoints` (`id`, `community_id`, `description`, `longitude`, `latitude`, `geohash`) VALUES (@coge_id+6, @eh_communities_id+5, '', '121.642243', '31.224285', 's00000000000');
INSERT INTO `eh_community_geopoints` (`id`, `community_id`, `description`, `longitude`, `latitude`, `geohash`) VALUES (@coge_id+7, @eh_communities_id+4, '', '121.642243', '31.224285', 's00000000000');
-- 测试数据结束

-- eh_organization_community_requests 数据
DELETE FROM eh_organization_community_requests WHERE id = 1143623;
INSERT INTO `eh_organization_community_requests` (`id`, `community_id`, `member_type`, `member_id`, `member_status`, `creator_uid`, `create_time`, `operator_uid`, `process_code`, `process_details`, `proof_resource_uri`, `approve_time`, `requestor_comment`, `operation_type`, `inviter_uid`, `invite_time`, `update_time`, `integral_tag1`, `integral_tag2`, `integral_tag3`, `integral_tag4`, `integral_tag5`, `string_tag1`, `string_tag2`, `string_tag3`, `string_tag4`, `string_tag5`) VALUES ('1143623', '240111044331050388', 'organization', '1012516', '3', '0', '2017-08-15 13:30:44', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);


-- eh_launch_pad_items数据
delete from eh_launch_pad_items WHERE namespace_id = 999971;
SET @item_id = (SELECT MAX(id) from eh_launch_pad_items);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`, `alias_icon_uri`, `categry_name`) VALUES ((@item_id := @item_id + 1), '999971', '0', '0', '0', '/home', 'EnterpriseServices', '人才公寓', '人才公寓', 'cs://1/image/aW1hZ2UvTVRwalpHVmhaVGt3WldZM1pHSXhZemczWW1FME5UVmtaR05sTVdObU9HVXlZUQ', '1', '1', '66', '{\"viewTitle\": \"选择人才公寓\"}', '1', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'park_tourist', '1', NULL, NULL, '0', NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`, `alias_icon_uri`, `categry_name`) VALUES ((@item_id := @item_id + 1), '999971', '0', '0', '0', '/home', 'EnterpriseServices', '人才公寓', '人才公寓', 'cs://1/image/aW1hZ2UvTVRwalpHVmhaVGt3WldZM1pHSXhZemczWW1FME5UVmtaR05sTVdObU9HVXlZUQ', '1', '1', '66', '{\"viewTitle\": \"选择人才公寓\"}', '1', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'pm_admin', '0', NULL, NULL, '0', NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`, `alias_icon_uri`, `categry_name`) VALUES ((@item_id := @item_id + 1), '999971', '0', '0', '0', '/home', 'EnterpriseServices', '企业账单', '企业账单', 'cs://1/image/aW1hZ2UvTVRveU5tRmlORGt6WW1JM00yTmtZVEZoTVRabE9EbGhZbU5pT0dRek1EQm1Ndw', '1', '1', '13', '{\"url\":\"http://zuolin.com/mobile/static/coming_soon/index.html\"}', '3', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'park_tourist', '1', NULL, NULL, '0', NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`, `alias_icon_uri`, `categry_name`) VALUES ((@item_id := @item_id + 1), '999971', '0', '0', '0', '/home', 'EnterpriseServices', '企业账单', '企业账单', 'cs://1/image/aW1hZ2UvTVRveU5tRmlORGt6WW1JM00yTmtZVEZoTVRabE9EbGhZbU5pT0dRek1EQm1Ndw', '1', '1', '13', '{\"url\":\"http://zuolin.com/mobile/static/coming_soon/index.html\"}', '3', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'pm_admin', '0', NULL, NULL, '0', NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`, `alias_icon_uri`, `categry_name`) VALUES ((@item_id := @item_id + 1), '999971', '0', '0', '0', '/home', 'EnterpriseServices', '企业通讯录', '企业通讯录', 'cs://1/image/aW1hZ2UvTVRvelpHRmtOak00TkRrM09XVmlZamRrWWpKa1l6bGpOV1l3T1RZeFlUVXpaZw', '1', '1', '46', '', '2', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'park_tourist', '1', NULL, NULL, '0', NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`, `alias_icon_uri`, `categry_name`) VALUES ((@item_id := @item_id + 1), '999971', '0', '0', '0', '/home', 'EnterpriseServices', '企业通讯录', '企业通讯录', 'cs://1/image/aW1hZ2UvTVRvelpHRmtOak00TkRrM09XVmlZamRrWWpKa1l6bGpOV1l3T1RZeFlUVXpaZw', '1', '1', '46', '', '2', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'pm_admin', '0', NULL, NULL, '0', NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`, `alias_icon_uri`, `categry_name`) VALUES ((@item_id := @item_id + 1), '999971', '0', '0', '0', '/home', 'Bizs', '公寓介绍', '公寓介绍', 'cs://1/image/aW1hZ2UvTVRwak9EUmlZelV5Tm1SbVpEQmpOelV4WkdRME9ESmxaVE14WVRjM1pXWTFZUQ', '1', '1', '33', '{\"type\":201191,\"parentId\":201191,\"displayType\": \"grid\"}', '0', '0', '1', '1', '1', '0', NULL, NULL, NULL, '0', 'default', '0', NULL, NULL, '0', NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`, `alias_icon_uri`, `categry_name`) VALUES ((@item_id := @item_id + 1), '999971', '0', '0', '0', '/home', 'EnterpriseServices', '合同查询', '合同查询', 'cs://1/image/aW1hZ2UvTVRvNU1ETm1ZV1kyTnpOaVkySTNaamxtTWpVME56WXdZakF4TjJaaE1tWmpOdw', '1', '1', '13', '{\"url\":\"http://zuolin.com/mobile/static/coming_soon/index.html\"}', '4', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'default', '1', NULL, NULL, '0', NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`, `alias_icon_uri`, `categry_name`) VALUES ((@item_id := @item_id + 1), '999971', '0', '0', '0', '/home', 'Bizs', '园区商业', '园区商业', 'cs://1/image/aW1hZ2UvTVRvMFpHWmpNbUUwTldaak9EWmxNREUxWldKbU0yWTNNR1EzTURZMU1tWTRaUQ', '1', '1', '33', '{\"type\":201187,\"parentId\":201187,\"displayType\": \"tab\"}', '2', '0', '1', '1', '1', '0', NULL, NULL, NULL, '1', 'pm_admin', '0', NULL, NULL, '0', NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`, `alias_icon_uri`, `categry_name`) VALUES ((@item_id := @item_id + 1), '999971', '0', '0', '0', '/home', 'Bizs', '园区商业', '园区商业', 'cs://1/image/aW1hZ2UvTVRvMFpHWmpNbUUwTldaak9EWmxNREUxWldKbU0yWTNNR1EzTURZMU1tWTRaUQ', '1', '1', '33', '{\"type\":201187,\"parentId\":201187,\"displayType\": \"tab\"}', '2', '0', '1', '1', '1', '0', NULL, NULL, NULL, '1', 'park_tourist', '0', NULL, NULL, '0', NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`, `alias_icon_uri`, `categry_name`) VALUES ((@item_id := @item_id + 1), '999971', '0', '0', '0', '/home', 'EnterpriseServices', '园区商业', '园区服务', 'cs://1/image/aW1hZ2UvTVRvNVpHUmxNalExWkdSaU16Y3hNelV3T1RjME5ERmhORGRtWm1aak16TTBNdw', '1', '1', '66', '{\"viewTitle\": \"选择园区服务\"}', '1', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'default', '1', NULL, NULL, '0', NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`, `alias_icon_uri`, `categry_name`) VALUES ((@item_id := @item_id + 1), '999971', '0', '0', '0', '/home', 'Bizs', '园区食堂', '园区食堂', 'cs://1/image/aW1hZ2UvTVRvNVpEVTJNemsyTURJelptSXdaR00wTVRSaU4yUTBPV1ptTUROa1lUa3hNZw', '1', '1', '33', '{\"type\":201186,\"parentId\":201186,\"displayType\": \"list\"}', '3', '0', '1', '0', '', '0', NULL, NULL, NULL, '1', 'pm_admin', '1', NULL, NULL, '0', NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`, `alias_icon_uri`, `categry_name`) VALUES ((@item_id := @item_id + 1), '999971', '0', '0', '0', '/home', 'Bizs', '园区食堂', '园区食堂', 'cs://1/image/aW1hZ2UvTVRvNVpEVTJNemsyTURJelptSXdaR00wTVRSaU4yUTBPV1ptTUROa1lUa3hNZw', '1', '1', '33', '{\"type\":201186,\"parentId\":201186,\"displayType\": \"list\"}', '3', '0', '1', '0', '', '0', NULL, NULL, NULL, '1', 'park_tourist', '1', NULL, NULL, '0', NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`, `alias_icon_uri`, `categry_name`) VALUES ((@item_id := @item_id + 1), '999971', '0', '0', '0', '/home', 'EnterpriseServices', '家园卡', '家园卡', 'cs://1/image/aW1hZ2UvTVRwa01qUTVaVEl5TmpFNU9UbGtNakUxTVRGaFpEY3pZemN6TVRGaU1tUXhOQQ', '1', '1', '33', '{\"type\":201188,\"parentId\":201188,\"displayType\": \"list\"}', '6', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'park_tourist', '1', NULL, NULL, '0', NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`, `alias_icon_uri`, `categry_name`) VALUES ((@item_id := @item_id + 1), '999971', '0', '0', '0', '/home', 'EnterpriseServices', '家园卡', '家园卡', 'cs://1/image/aW1hZ2UvTVRwa01qUTVaVEl5TmpFNU9UbGtNakUxTVRGaFpEY3pZemN6TVRGaU1tUXhOQQ', '1', '1', '33', '{\"type\":201188,\"parentId\":201188,\"displayType\": \"list\"}', '6', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'pm_admin', '0', NULL, NULL, '0', NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`, `alias_icon_uri`, `categry_name`) VALUES ((@item_id := @item_id + 1), '999971', '0', '0', '0', '/home', 'Bizs', '我的任务', '我的任务', 'cs://1/image/aW1hZ2UvTVRvME9UVXlORFU1WW1KbU9UWXhNVGM0TTJJM09XRXdNVEV4TlRKaE9HWXlOZw', '1', '1', '56', '', '3', '0', '1', '0', '1', '0', NULL, NULL, NULL, '1', 'pm_admin', '0', NULL, NULL, '0', NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`, `alias_icon_uri`, `categry_name`) VALUES ((@item_id := @item_id + 1), '999971', '0', '0', '0', '/home', 'Bizs', '我的任务', '我的任务', 'cs://1/image/aW1hZ2UvTVRvME9UVXlORFU1WW1KbU9UWXhNVGM0TTJJM09XRXdNVEV4TlRKaE9HWXlOZw', '1', '1', '56', '', '3', '0', '1', '0', '1', '0', NULL, NULL, NULL, '1', 'park_tourist', '0', NULL, NULL, '0', NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`, `alias_icon_uri`, `categry_name`) VALUES ((@item_id := @item_id + 1), '999971', '0', '0', '0', '/home', 'Bizs', '招商信息', '招商信息', 'cs://1/image/aW1hZ2UvTVRvNU1qWm1OakE0WWpoaVltWTJZVGxpTm1Ka05qYzNPREV5WlRGbFlUSTNOZw', '1', '1', '33', '{\"displayType\": \"grid\"}', '0', '0', '1', '1', '1', '0', NULL, NULL, NULL, '1', 'pm_admin', '0', NULL, NULL, '0', NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`, `alias_icon_uri`, `categry_name`) VALUES ((@item_id := @item_id + 1), '999971', '0', '0', '0', '/home', 'Bizs', '招商信息', '招商信息', 'cs://1/image/aW1hZ2UvTVRvNU1qWm1OakE0WWpoaVltWTJZVGxpTm1Ka05qYzNPREV5WlRGbFlUSTNOZw', '1', '1', '33', '{\"displayType\": \"grid\"}', '0', '0', '1', '1', '1', '0', NULL, NULL, NULL, '1', 'park_tourist', '0', NULL, NULL, '0', NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`, `alias_icon_uri`, `categry_name`) VALUES ((@item_id := @item_id + 1), '999971', '0', '0', '0', '/home', 'Bizs', '更多', '更多', 'cs://1/image/aW1hZ2UvTVRwbFpUZzVORGM1TVdKalpqRmhOMkUzTW1ZME5UWmtOVGxrTlRNME1XRTFNZw', '1', '1', '1', '{\"itemLocation\":\"/home\", \"itemGroup\":\"Bizs\"}', '3', '0', '1', '1', '1', '0', NULL, NULL, NULL, '0', 'pm_admin', '0', NULL, NULL, '0', NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`, `alias_icon_uri`, `categry_name`) VALUES ((@item_id := @item_id + 1), '999971', '0', '0', '0', '/home', 'Bizs', '更多', '更多', 'cs://1/image/aW1hZ2UvTVRwbFpUZzVORGM1TVdKalpqRmhOMkUzTW1ZME5UWmtOVGxrTlRNME1XRTFNZw', '1', '1', '1', '{\"itemLocation\":\"/home\", \"itemGroup\":\"Bizs\"}', '3', '0', '1', '1', '1', '0', NULL, NULL, NULL, '0', 'park_tourist', '0', NULL, NULL, '0', NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`, `alias_icon_uri`, `categry_name`) VALUES ((@item_id := @item_id + 1), '999971', '0', '0', '0', '/home', 'Bizs', '服务热线', '服务热线', 'cs://1/image/aW1hZ2UvTVRvMU5XRmtPV1F3TVdWa05XSTRaVGhtTlRsallqSXpZamt6TUdZeE1qQXdaQQ', '1', '1', '45', '', '0', '0', '1', '1', '1', '0', NULL, NULL, NULL, '0', 'default', '0', NULL, NULL, '0', NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`, `alias_icon_uri`, `categry_name`) VALUES ((@item_id := @item_id + 1), '999971', '0', '0', '0', '/home', 'EnterpriseServices', '物业报修', '物业报修', 'cs://1/image/aW1hZ2UvTVRwak9XVTFOMlJsTkdRME4yVmxPVGxpWmpOak1EaGpNak0yT1RrMk1HRmlZZw', '1', '1', '60', '{\"url\":\"zl://propertyrepair/create?type=user&taskCategoryId=0&displayName=物业报修\"}', '5', '0', '1', '1', '1', '0', NULL, NULL, NULL, '0', 'park_tourist', '0', NULL, NULL, '0', NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`, `alias_icon_uri`, `categry_name`) VALUES ((@item_id := @item_id + 1), '999971', '0', '0', '0', '/home', 'EnterpriseServices', '物业报修', '物业报修', 'cs://1/image/aW1hZ2UvTVRvMlpUTXdNelkyWTJNd1ptTmlaR0kxTUdOaFpERXlZVGs0WlRrM1kyTXdPUQ', '1', '1', '60', '{\"url\":\"zl://propertyrepair/create?type=user&taskCategoryId=0&displayName=物业报修\"}', '2', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'default', '1', NULL, NULL, '0', NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`, `alias_icon_uri`, `categry_name`) VALUES ((@item_id := @item_id + 1), '999971', '0', '0', '0', '/home', 'EnterpriseServices', '物业报修', '物业报修', 'cs://1/image/aW1hZ2UvTVRwak9XVTFOMlJsTkdRME4yVmxPVGxpWmpOak1EaGpNak0yT1RrMk1HRmlZZw', '1', '1', '60', '{\"url\":\"zl://propertyrepair/create?type=user&taskCategoryId=0&displayName=物业报修\"}', '5', '0', '1', '1', '1', '0', NULL, NULL, NULL, '0', 'pm_admin', '0', NULL, NULL, '0', NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`, `alias_icon_uri`, `categry_name`) VALUES ((@item_id := @item_id + 1), '999971', '0', '0', '0', '/home', 'Bizs', '租赁指南', '租赁指南', 'cs://1/image/aW1hZ2UvTVRvMU5XRmtPV1F3TVdWa05XSTRaVGhtTlRsallqSXpZamt6TUdZeE1qQXdaQQ', '1', '1', '33', '{\"type\":201192,\"parentId\":201192,\"displayType\": \"grid\"}', '1', '0', '1', '1', '1', '0', NULL, NULL, NULL, '0', 'default', '0', NULL, NULL, '0', NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`, `alias_icon_uri`, `categry_name`) VALUES ((@item_id := @item_id + 1), '999971', '0', '0', '0', '/home', 'EnterpriseServices', '移动考勤', '移动考勤', 'cs://1/image/aW1hZ2UvTVRvME56QmlZMkUwT0dNM056QmpOV1JsTWpkaVlXVmpOelZoTTJNeU1UTmlOdw', '1', '1', '23', '', '4', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'park_tourist', '1', NULL, NULL, '0', NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`, `alias_icon_uri`, `categry_name`) VALUES ((@item_id := @item_id + 1), '999971', '0', '0', '0', '/home', 'EnterpriseServices', '移动考勤', '移动考勤', 'cs://1/image/aW1hZ2UvTVRvME56QmlZMkUwT0dNM056QmpOV1JsTWpkaVlXVmpOelZoTTJNeU1UTmlOdw', '1', '1', '23', '', '4', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'pm_admin', '0', NULL, NULL, '0', NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`, `alias_icon_uri`, `categry_name`) VALUES ((@item_id := @item_id + 1), '999971', '0', '0', '0', '/home', 'EnterpriseServices', '费用查缴', '费用查缴', 'cs://1/image/aW1hZ2UvTVRvek1qZGtaV1ZsTlRJek1UWTFNVGhsTVRJNVlqQXdNVE00WTJGbE1qUmxOQQ', '1', '1', '13', '{\"url\":\"http://zuolin.com/mobile/static/coming_soon/index.html\"}', '3', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'default', '1', NULL, NULL, '0', NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`, `alias_icon_uri`, `categry_name`) VALUES ((@item_id := @item_id + 1), '999971', '0', '0', '0', '/home', 'Bizs', '集中登记地', '集中登记地', 'cs://1/image/aW1hZ2UvTVRvNE16RXpaVEl5TkRZeU1HTTNOamN5Wm1aa09XTTNObVE0WTJWbE16aGxZUQ', '1', '1', '33', '{\"type\":201190,\"parentId\":201190,\"displayType\": \"list\"}', '1', '0', '1', '1', '1', '0', NULL, NULL, NULL, '1', 'pm_admin', '0', NULL, NULL, '0', NULL, NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`, `scale_type`, `service_categry_id`, `selected_icon_uri`, `more_order`, `alias_icon_uri`, `categry_name`) VALUES ((@item_id := @item_id + 1), '999971', '0', '0', '0', '/home', 'Bizs', '集中登记地', '集中登记地', 'cs://1/image/aW1hZ2UvTVRvNE16RXpaVEl5TkRZeU1HTTNOamN5Wm1aa09XTTNObVE0WTJWbE16aGxZUQ', '1', '1', '33', '{\"type\":201190,\"parentId\":201190,\"displayType\": \"list\"}', '1', '0', '1', '1', '1', '0', NULL, NULL, NULL, '1', 'park_tourist', '0', NULL, NULL, '0', NULL, NULL);

-- eh_namespace_resources数据
DELETE FROM eh_namespace_resources WHERE namespace_id = 999971;
INSERT INTO `eh_namespace_resources` (`id`, `namespace_id`, `resource_type`, `resource_id`, `create_time`) VALUES ('19935', '999971', 'COMMUNITY', '240111044331050388', '2017-08-29 09:55:59');
INSERT INTO `eh_namespace_resources` (`id`, `namespace_id`, `resource_type`, `resource_id`, `create_time`) VALUES ('19929', '999971', 'COMMUNITY', '240111044331050389', '2017-08-29 09:52:46');
INSERT INTO `eh_namespace_resources` (`id`, `namespace_id`, `resource_type`, `resource_id`, `create_time`) VALUES ('19930', '999971', 'COMMUNITY', @eh_communities_id+1, '2017-08-29 09:52:46');
INSERT INTO `eh_namespace_resources` (`id`, `namespace_id`, `resource_type`, `resource_id`, `create_time`) VALUES ('19931', '999971', 'COMMUNITY', @eh_communities_id+2, '2017-08-29 09:52:46');
INSERT INTO `eh_namespace_resources` (`id`, `namespace_id`, `resource_type`, `resource_id`, `create_time`) VALUES ('19932', '999971', 'COMMUNITY', @eh_communities_id+3, '2017-08-29 09:52:47');
-- 测试数据
INSERT INTO `eh_namespace_resources` (`id`, `namespace_id`, `resource_type`, `resource_id`, `create_time`) VALUES ('19933', '999971', 'COMMUNITY', @eh_communities_id+4, '2017-08-29 09:52:47');
INSERT INTO `eh_namespace_resources` (`id`, `namespace_id`, `resource_type`, `resource_id`, `create_time`) VALUES ('19934', '999971', 'COMMUNITY', @eh_communities_id+5, '2017-08-29 09:52:48');
-- 测试数据结束

-- 增加蒙版配置项
SET @con_id = (SELECT MAX(id) from eh_configurations);
delete from eh_configurations where 'value' in ('mask.key','scenes.switchKey');
INSERT INTO `eh_configurations` VALUES (@con_id + 1, 'mask.key', 0, '默认启用蒙版', 999971, '');
INSERT INTO `eh_configurations` VALUES (@con_id + 2, 'scenes.switchKey', 0, '默认启用蒙版', 999971, '');
-- 增加蒙版表数据
delete from eh_namespace_masks;
INSERT INTO `eh_namespace_masks` VALUES ('1', '999971', '人才公寓', '3', '快速切换至人才市场', 'park_tourist');
INSERT INTO `eh_namespace_masks` VALUES ('2', '999971', '园区服务', '3', '快速切换至园区主页', 'default');
-- By janson
-- 更改默认错误提示
update eh_locale_strings set `text`='应用开小差了' where `text` = '呃，好像哪里出错了';


