-- add by nan.rong for workReport
INSERT INTO `eh_work_report_templates` (`id`, `namespace_id`, `owner_id`, `owner_type`, `organization_id`, `module_id`, `module_type`, `report_name`, `report_type`, `report_attribute`, `form_template_id`, `modify_flag`, `delete_flag`, `icon_uri`, `update_time`, `create_time`) VALUES ('1', '0', '0', 'EhOrganizations', '0', '54000', 'any-module', '日报', '0', 'DEFAULT', '6', '0', '0', NULL, '2017-12-06 18:55:10', '2017-12-06 18:55:10');
INSERT INTO `eh_work_report_templates` (`id`, `namespace_id`, `owner_id`, `owner_type`, `organization_id`, `module_id`, `module_type`, `report_name`, `report_type`, `report_attribute`, `form_template_id`, `modify_flag`, `delete_flag`, `icon_uri`, `update_time`, `create_time`) VALUES ('2', '0', '0', 'EhOrganizations', '0', '54000', 'any-module', '周报', '1', 'DEFAULT', '7', '0', '0', NULL, '2017-12-06 18:55:10', '2017-12-06 18:55:10');
INSERT INTO `eh_work_report_templates` (`id`, `namespace_id`, `owner_id`, `owner_type`, `organization_id`, `module_id`, `module_type`, `report_name`, `report_type`, `report_attribute`, `form_template_id`, `modify_flag`, `delete_flag`, `icon_uri`, `update_time`, `create_time`) VALUES ('3', '0', '0', 'EhOrganizations', '0', '54000', 'any-module', '月报', '2', 'DEFAULT', '8', '0', '0', NULL, '2017-12-06 18:55:10', '2017-12-06 18:55:10');

INSERT INTO `eh_general_form_templates` (`id`, `namespace_id`, `organization_id`, `owner_id`, `owner_type`, `module_id`, `module_type`, `form_name`, `version`, `template_type`, `template_text`, `modify_flag`, `delete_flag`, `update_time`, `create_time`) VALUES ('6', '0', '0', '0', 'EhOrganizations', '54000', 'any-module', '日报', '0', 'DEFAULT_JSON', '[{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"今日完成工作\",\"fieldExtra\":\"{}\",\"fieldName\":\"今日完成工作\",\"fieldType\":\"MULTI_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1},{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"未完成工作\",\"fieldExtra\":\"{}\",\"fieldName\":\"未完成工作\",\"fieldType\":\"MULTI_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1},{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"需协助工作\",\"fieldExtra\":\"{}\",\"fieldName\":\"需协助工作\",\"fieldType\":\"MULTI_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1},{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"明日计划工作\",\"fieldExtra\":\"{}\",\"fieldName\":\"明日计划工作\",\"fieldType\":\"MULTI_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1}]', '1', '0', '2017-12-06 18:57:08', '2017-12-06 18:57:08');
INSERT INTO `eh_general_form_templates` (`id`, `namespace_id`, `organization_id`, `owner_id`, `owner_type`, `module_id`, `module_type`, `form_name`, `version`, `template_type`, `template_text`, `modify_flag`, `delete_flag`, `update_time`, `create_time`) VALUES ('7', '0', '0', '0', 'EhOrganizations', '54000', 'any-module', '周报', '0', 'DEFAULT_JSON', '[{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"本周完成工作\",\"fieldExtra\":\"{}\",\"fieldName\":\"本周完成工作\",\"fieldType\":\"MULTI_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1},{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"未完成工作\",\"fieldExtra\":\"{}\",\"fieldName\":\"未完成工作\",\"fieldType\":\"MULTI_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1},{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"需协助工作\",\"fieldExtra\":\"{}\",\"fieldName\":\"需协助工作\",\"fieldType\":\"MULTI_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1},{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"下周计划工作\",\"fieldExtra\":\"{}\",\"fieldName\":\"下周计划工作\",\"fieldType\":\"MULTI_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1}]', '1', '0', '2017-12-06 18:57:08', '2017-12-06 18:57:08');
INSERT INTO `eh_general_form_templates` (`id`, `namespace_id`, `organization_id`, `owner_id`, `owner_type`, `module_id`, `module_type`, `form_name`, `version`, `template_type`, `template_text`, `modify_flag`, `delete_flag`, `update_time`, `create_time`) VALUES ('8', '0', '0', '0', 'EhOrganizations', '54000', 'any-module', '月报', '0', 'DEFAULT_JSON', '[{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"本月完成工作\",\"fieldExtra\":\"{}\",\"fieldName\":\"本月完成工作\",\"fieldType\":\"MULTI_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1},{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"未完成工作\",\"fieldExtra\":\"{}\",\"fieldName\":\"未完成工作\",\"fieldType\":\"MULTI_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1},{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"需协助工作\",\"fieldExtra\":\"{}\",\"fieldName\":\"需协助工作\",\"fieldType\":\"MULTI_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1},{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"下月计划工作\",\"fieldExtra\":\"{}\",\"fieldName\":\"下月计划工作\",\"fieldType\":\"MULTI_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1}]', '1', '0', '2017-12-06 18:57:08', '2017-12-06 18:57:08');

-- menu change
update eh_web_menus set sort_num = 610 where id = 51000;
update eh_web_menus set sort_num = 620 where id = 70000;
update eh_web_menus set sort_num = 620 where id = 700000;
update eh_web_menus set sort_num = 622 where id = 70100;
update eh_web_menus set sort_num = 622 where id = 701000;
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`, `level`, `condition_type`, `category`) VALUES ('54000', '工作汇报', '50000', NULL, '', '0', '2', '/50000/54000', 'park', '600', '54000', '2', NULL, 'module');
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`, `level`, `condition_type`, `category`) VALUES ('54010', '汇报设置', '54000', NULL, 'react:/work-report/report-setting', '0', '2', '/50000/54000/54010', 'park', '601', '54000', '3', NULL, 'module');
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`, `level`, `condition_type`, `category`) VALUES ('54020', '表单管理', '54000', NULL, 'react:/form-management/form-list?moduleId=54000&moduleType=any-module', '0', '2', '/50000/54000/54020', 'park', '602', '54000', '3', NULL, 'module');
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`, `level`, `condition_type`, `category`) VALUES ('540000', '工作汇报', '500000', NULL, '', '0', '2', '/500000/540000', 'organization', '600', '54000', '2', NULL, 'module');
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`, `level`, `condition_type`, `category`) VALUES ('540100', '汇报设置', '540100', NULL, 'react:/work-report/report-setting', '0', '2', '/500000/540000/540100', 'organization', '601', '54000', '3', NULL, 'module');
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`, `level`, `condition_type`, `category`) VALUES ('540200', '表单管理', '540200', NULL, 'react:/work-report/report-setting', '0', '2', '/500000/540000/540200', 'organization', '602', '54000', '3', NULL, 'module');

-- locale Template
SET @tem_ip = (SELECT MAX(id) FROM eh_locale_templates);
INSERT INTO `eh_locale_templates`(`id`, `scope`, `code`, `locale`, `description`, `text`, `namespace_id`) VALUES (@tem_ip := @tem_ip + 1, 'work.report.notification', 1, 'zh_CN', '作者提交汇报', '${applierName}给你提交了${reportName}', 0);
INSERT INTO `eh_locale_templates`(`id`, `scope`, `code`, `locale`, `description`, `text`, `namespace_id`) VALUES (@tem_ip := @tem_ip + 1, 'work.report.notification', 2, 'zh_CN', '作者修改汇报', '${applierName}更新了Ta的${reportName}', 0);
INSERT INTO `eh_locale_templates`(`id`, `scope`, `code`, `locale`, `description`, `text`, `namespace_id`) VALUES (@tem_ip := @tem_ip + 1, 'work.report.notification', 3, 'zh_CN', '读者被作者评论', '${applierName}在Ta的${reportName}中回复了你', 0);
INSERT INTO `eh_locale_templates`(`id`, `scope`, `code`, `locale`, `description`, `text`, `namespace_id`) VALUES (@tem_ip := @tem_ip + 1, 'work.report.notification', 4, 'zh_CN', '作者评论汇报', '${applierName}在Ta的${reportName}中发表了评论', 0);
INSERT INTO `eh_locale_templates`(`id`, `scope`, `code`, `locale`, `description`, `text`, `namespace_id`) VALUES (@tem_ip := @tem_ip + 1, 'work.report.notification', 5, 'zh_CN', '作者被读者评论', '${creatorName}在你的${reportName}中回复了你', 0);
INSERT INTO `eh_locale_templates`(`id`, `scope`, `code`, `locale`, `description`, `text`, `namespace_id`) VALUES (@tem_ip := @tem_ip + 1, 'work.report.notification', 6, 'zh_CN', '读者被读者评论', '${creatorName}在${applierName}的${reportName}中回复了你', 0);
INSERT INTO `eh_locale_templates`(`id`, `scope`, `code`, `locale`, `description`, `text`, `namespace_id`) VALUES (@tem_ip := @tem_ip + 1, 'work.report.notification', 7, 'zh_CN', '作者的汇报被评论', '${creatorName}在你的${reportName}中发表了评论', 0);


-- end by nan.rong

-- 积分使用消息  add by xq.tian 2018/01/03
SET @locale_templates_id = IFNULL((SELECT MAX(id) FROM `eh_locale_templates`), 0);
INSERT INTO `eh_locale_templates` (`id`, `scope`, `code`, `locale`, `description`, `text`, `namespace_id`)
VALUES ((@locale_templates_id := @locale_templates_id + 1), 'point', 10000, 'zh_CN', '您的积分将于12月31日过期，请及时使用。', '您的积分将于12月31日过期，请及时使用。', 0);
INSERT INTO `eh_locale_templates` (`id`, `scope`, `code`, `locale`, `description`, `text`, `namespace_id`)
VALUES ((@locale_templates_id := @locale_templates_id + 1), 'point', 10001, 'zh_CN', '积分通用的模板', '{"messageTitle":"积分消息","resetPointDesc":"积分重置","resetPointCate":"系统","exportLogTitle":"昵称,手机,功能模块,行为,积分变化,日期","exportLogFileName":"用户积分历史"}', 0);

DELETE FROM `eh_point_rules`;
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (1, 0, 1, 0, '注册成功', '注册成功', 1, 10, '{"type":2}', '{"times":1}', 0, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (2, 0, 1, 0, '认证成功', '首次通过认证', 1, 10, '{"type":2}', '{"times":1}', 0, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (3, 0, 1, 0, '完善个人信息', '完善个人信息', 1, 10, '{"type":2}', '{"times":1}', 0, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (4, 0, 2, 0, '发布帖子', '发布帖子', 1, 5, '{"type":1}', '{"times":3}', 0, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (5, 0, 2, 0, '评论帖子', '发布评论', 1, 2, '{"type":1}', '{"times":5}', 0, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (6, 0, 2, 0, '点赞帖子', '点赞帖子', 1, 1, '{"type":1}', '{"times":5}', 0, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (7, 0, 2, 0, '分享帖子', '分享帖子', 1, 1, '{"type":1}', '{"times":2}', 0, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (8, 0, 2, 0, '参与投票', '参与投票', 1, 2, '{"type":1}', '{"times":5}', 0, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (9, 0, 3, 0, '成功发起活动', '发起活动', 1, 10, '{"type":1}', '{"times":1}', 0, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (10, 0, 3, 0, '报名活动', '报名活动', 1, 3, '{"type":1}', '{"times":2}', 0, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (11, 0, 3, 0, '分享活动', '分享活动', 1, 2, '{"type":1}', '{"times":2}', 0, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (12, 0, 3, 0, '评论活动', '评论活动', 1, 2, '{"type":1}', '{"times":5}', 0, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (13, 0, 3, 0, '点赞活动', '点赞活动', 1, 1, '{"type":1}', '{"times":5}', 0, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (14, 0, 4, 0, '成功发起俱乐部', '发起俱乐部', 1, 10, '{"type":1}', '{"times":5}', 0, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (15, 0, 4, 0, '成功加入俱乐部', '加入俱乐部', 1, 3, '{"type":1}', '{"times":5}', 0, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (16, 0, 5, 0, '成功发起行业协会', '发起行业协会', 1, 10, '{"type":1}', '{"times":5}', 0, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (17, 0, 5, 0, '成功加入行业协会', '加入行业协会', 1, 3, '{"type":1}', '{"times":5}', 0, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (18, 0, 6, 0, '在意见反馈中发布帖子', '发布意见反馈', 1, 2, '{"type":1}', '{"times":2}', 0, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (19, 0, 7, 0, '电商消费', '电商每天首次购物', 1, 2, '{"type":1}', '{"times":1}', 0, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (20, 0, 7, 0, '连续三天电商消费', '电商连续购物3天', 1, 8, '{"type":1}', '{"times":1, "continuous":3}', 0, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (21, 0, 8, 0, '园区资源预约成功', '园区资源预约成功', 1, 2, '{"type":1}', '{"times":5}', 0, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (22, 0, 2, 0, '论坛帖子/评论被举报且管理员核实', '论坛帖子/评论被举报', 2, 10, '{"type":1}', '{"times":2}', 0, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (23, 0, 2, 0, '论坛评论被举报且管理员核实', '论坛评论被举报', 2, 5, '{"type":1}', '{"times":2}', 0, 2, 0, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (24, 0, 2, 0, '删除帖子', '删除论坛帖子', 2, 3, '{"type":1}', '{"times":5}', 4, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (25, 0, 2, 0, '删除评论', '删除论坛评论', 2, 2, '{"type":1}', '{"times":5}', 5, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (26, 0, 2, 0, '取消论坛点赞', '取消论坛点赞', 2, 1, '{"type":1}', '{"times":5}', 6, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (27, 0, 3, 0, '活动/评论被举报且管理员核实', '活动/评论被举报', 2, 10, '{"type":1}', '{"times":2}', 0, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (28, 0, 3, 0, '删除活动', '删除活动', 2, 10, '{"type":1}', '{"times":2}', 9, 0, 0, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (29, 0, 3, 0, '取消活动报名', '取消活动报名', 2, 2, '{"type":1}', '{"times":2}', 10, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (30, 0, 3, 0, '删除活动评论', '删除活动评论', 2, 2, '{"type":1}', '{"times":2}', 12, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (31, 0, 3, 0, '取消活动点赞', '取消活动点赞', 2, 1, '{"type":1}', '{"times":2}', 13, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (32, 0, 4, 0, '解散俱乐部', '解散俱乐部', 2, 10, '{"type":1}', '{"times":2}', 14, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (33, 0, 4, 0, '退出俱乐部', '退出俱乐部', 2, 2, '{"type":1}', '{"times":5}', 15, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (34, 0, 5, 0, '解散行业协会', '解散行业协会', 2, 10, '{"type":1}', '{"times":2}', 16, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (35, 0, 5, 0, '退出行业协会', '退出行业协会', 2, 2, '{"type":1}', '{"times":2}', 17, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (36, 0, 6, 0, '删除意见反馈帖子', '删除意见反馈', 2, 2, '{"type":1}', '{"times":2}', 18, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (37, 0, 7, 0, '消费抵现', '电商购物抵现', 2, 0, '{"type":3}', ' ', 0, 2, 0, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (38, 0, 8, 0, '取消资源预约', '取消资源预约', 2, 2, '{"type":1}', '{"times":5}', 21, 2, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (39, 0, 1, 0, '每日首次登录', '每日首次登录', 1, 2, '{"type":1,"disabled":1}', '{"times":1,"disabled":1}', 0, 2, 1, NULL, NULL, NULL, NULL, '');
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `binding_rule_id`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`, `extra`) VALUES (40, 0, 7, 0, '取消订单', '取消订单', 1, 0, '{"type":3}', NULL, 37, 2, 0, NULL, NULL, NULL, NULL, NULL);

DELETE FROM `eh_point_rule_to_event_mappings`;
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (1, 0, 1, 1, 'account.register_success.default');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (2, 0, 1, 2, 'account.auth_success.default');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (3, 0, 1, 3, 'account.complete_info.default');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (4, 0, 2, 4, 'forum.post_create');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (6, 0, 2, 5, 'forum.comment_create');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (8, 0, 2, 6, 'forum.post_like');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (10, 0, 2, 7, 'forum.post_share');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (13, 0, 2, 8, 'forum.post_vote');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (14, 0, 3, 9, 'activity.activity_create.default');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (15, 0, 3, 10, 'activity.activity_enter.default');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (16, 0, 3, 11, 'activity.activity_share.default');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (17, 0, 3, 12, 'activity.comment_create.default');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (18, 0, 3, 13, 'activity.activity_like.default');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (19, 0, 4, 14, 'club.club_create.0');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (20, 0, 4, 15, 'club.club_join.0');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (21, 0, 5, 16, 'club.club_create.1');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (22, 0, 5, 17, 'club.club_join.1');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (23, 0, 6, 18, 'feedback.feedback_create.default');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (24, 0, 7, 19, 'biz.order_pay_complete.default');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (25, 0, 7, 20, 'biz.order_pay_complete.default');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (26, 0, 8, 21, 'rental.resource_apply.default');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (27, 0, 2, 22, 'forum.post_report');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (29, 0, 2, 23, 'forum.comment_report');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (31, 0, 2, 24, 'forum.post_delete');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (33, 0, 2, 25, 'forum.comment_delete');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (35, 0, 2, 26, 'forum.post_like_cancel');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (37, 0, 3, 27, 'activity.activity_report.default');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (38, 0, 3, 28, 'activity.comment_report.default');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (39, 0, 3, 29, 'activity.activity_enter_cancel.default');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (40, 0, 3, 30, 'activity.comment_delete.default');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (41, 0, 3, 31, 'activity.activity_like_cancel.default');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (42, 0, 4, 32, 'club.club_release.0');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (43, 0, 4, 33, 'club.club_leave.0');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (44, 0, 5, 34, 'club.club_release.1');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (45, 0, 5, 35, 'club.club_leave.1');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (46, 0, 6, 36, 'feedback.feedback_delete.default');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (47, 0, 7, 37, 'biz.order_create.default');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (48, 0, 8, 38, 'rental.resource_apply_cancel.default');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (49, 0, 1, 39, 'account.open_app.default');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (59, 0, 3, 28, 'activity.activity_delete.default');
INSERT INTO `eh_point_rule_to_event_mappings` (`id`, `namespace_id`, `category_id`, `rule_id`, `event_name`) VALUES (60, 0, 7, 40, 'biz.order_cancel.default');

--
-- 积分管理菜单   add by xq.tian  2017/12/22
--
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`, `level`, `condition_type`, `category`)
VALUES (47000, '积分管理', 40000, NULL, '', 0, 2, '/40000/47000', 'park', 500, 47000, 2, NULL, 'module');

SET @web_menu_scopes_id = IFNULL((SELECT MAX(id) FROM `eh_web_menu_scopes`), 0);
INSERT INTO `eh_web_menu_scopes` (`id`, `menu_id`, `menu_name`, `owner_type`, `owner_id`, `apply_policy`)
VALUES ((@web_menu_scopes_id := @web_menu_scopes_id + 1), 47000, '', 'EhNamespaces', 1000000, 2);

SET @acl_privileges_id = IFNULL((SELECT MAX(id) FROM `eh_acl_privileges`), 0);
INSERT INTO `eh_acl_privileges` (`id`, `app_id`, `name`, `description`, `tag`)
VALUES ((@acl_privileges_id := @acl_privileges_id + 1), 0, '积分管理', '积分管理 全部权限', NULL);

SET @web_menu_privilege_id = (SELECT MAX(id) FROM `eh_web_menu_privileges`);
INSERT INTO `eh_web_menu_privileges` (`id`, `privilege_id`, `menu_id`, `name`, `show_flag`, `status`, `discription`, `sort_num`)
VALUES ((@web_menu_privilege_id := @web_menu_privilege_id + 1), @acl_privileges_id, 47000, '积分管理', 1, 1, '积分管理  全部权限', 202);

SET @acl_id = (SELECT MAX(id) FROM `eh_acls`);
INSERT INTO `eh_acls` (`id`, `namespace_id`, `owner_type`, `owner_id`, `grant_type`, `privilege_id`, `role_id`, `role_type`, `order_seq`, `creator_uid`, `create_time`)
VALUES ((@acl_id := @acl_id + 1), 0, 'EhOrganizations', NULL, 1, @acl_privileges_id, 1001, 'EhAclRoles', 0, 1, NOW());

INSERT INTO `eh_service_modules` (`id`, `name`, `parent_id`, `path`, `type`, `level`, `status`, `default_order`, `create_time`, `operator_uid`, `creator_uid`)
VALUES (47000, '积分管理', '40000', '/40000/47000', '0', '2', '2', '0', UTC_TIMESTAMP(), 0, 0);

SET @eh_service_module_privileges_id = (SELECT MAX(id) FROM `eh_service_module_privileges`);
INSERT INTO `eh_service_module_privileges` (`id`, `module_id`, `privilege_type`, `privilege_id`, `remark`, `default_order`, `create_time`)
VALUES ((@eh_service_module_privileges_id := @eh_service_module_privileges_id + 1), 47000, '1', @acl_privileges_id, NULL, '0', UTC_TIMESTAMP());


INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`, `level`, `condition_type`, `category`)
VALUES (5500000, '积分系统', 5000000, NULL, 'integral-management', 0, 2, '/5000000/5500000', 'zuolin', 10, 47000, 2, 'namespace', 'module');
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`, `level`, `condition_type`, `category`)
VALUES (5510000, '积分系统', 5500000, NULL, 'integral-management', 0, 2, '/5000000/5500000/5510000', 'zuolin', 10, 47000, 2, 'namespace', 'page');

# INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`, `level`, `condition_type`, `category`)
# VALUES (1200000, '短信管理', 1000000, NULL, 'sms-management', 0, 2, '/1100000/1100000', 'zuolin', 10, 12200, 2, 'namespace', 'module');
# INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`, `level`, `condition_type`, `category`)
# VALUES (1210000, '短信管理', 1200000, NULL, 'sms-management', 0, 2, '/1100000/1100000/1110000', 'zuolin', 10, 12200, 2, 'namespace', 'page');

SET @locale_strings_id = IFNULL((SELECT MAX(id) FROM `eh_locale_strings`), 0);
INSERT INTO `eh_locale_strings` (`id`, `scope`, `code`, `locale`, `text`)
VALUES ((@locale_strings_id := @locale_strings_id + 1), 'point', '10000', 'zh_CN', '积分系统不存在');
INSERT INTO `eh_locale_strings` (`id`, `scope`, `code`, `locale`, `text`)
VALUES ((@locale_strings_id := @locale_strings_id + 1), 'point', '10002', 'zh_CN', '积分指南不存在');
INSERT INTO `eh_locale_strings` (`id`, `scope`, `code`, `locale`, `text`)
VALUES ((@locale_strings_id := @locale_strings_id + 1), 'point', '10004', 'zh_CN', 'Banner不存在');
INSERT INTO `eh_locale_strings` (`id`, `scope`, `code`, `locale`, `text`)
VALUES ((@locale_strings_id := @locale_strings_id + 1), 'point', '10005', 'zh_CN', '商品获取失败');
INSERT INTO `eh_locale_strings` (`id`, `scope`, `code`, `locale`, `text`)
VALUES ((@locale_strings_id := @locale_strings_id + 1), 'point', '10006', 'zh_CN', '验证码错误');
INSERT INTO `eh_locale_strings` (`id`, `scope`, `code`, `locale`, `text`)
VALUES ((@locale_strings_id := @locale_strings_id + 1), 'point', '10007', 'zh_CN', '积分系统名称已存在');
INSERT INTO `eh_locale_strings` (`id`, `scope`, `code`, `locale`, `text`)
VALUES ((@locale_strings_id := @locale_strings_id + 1), 'point', '10008', 'zh_CN', '积分名称已存在');
