CREATE TABLE `eh_office_cubicle_default_rules` (
  `id` BIGINT NOT NULL DEFAULT 0 COMMENT 'id',
  `owner_type` VARCHAR(255) COMMENT 'owner type: community, organization',
  `owner_id` BIGINT COMMENT 'community id or organization id',
  `resource_type_id` BIGINT COMMENT 'resource type id',
  `rental_start_time` BIGINT COMMENT '最多提前多少时间预定',
  `rental_end_time` BIGINT COMMENT '最少提前多少时间预定',
  `refund_flag` TINYINT COMMENT '是否支持退款: 1-是, 0-否',
  `refund_ratio` INTEGER COMMENT '退款比例',
  `creator_uid` BIGINT,
  `create_time` DATETIME,
  `operator_uid` BIGINT,
  `operate_time` DATETIME,
  `multi_time_interval` TINYINT COMMENT '是否允许预约多个时段: 1-是, 0-否',
  `need_pay` TINYINT COMMENT '是否需要支付: 1-是, 0-否',
  `begin_date` DATE COMMENT '开始日期',
  `end_date` DATE COMMENT '结束日期',
  `day_open_time` DOUBLE,
  `day_close_time` DOUBLE,
  `open_weekday` VARCHAR(7) COMMENT '7位二进制，0000000每一位表示星期7123456',
  `cubicle_start_time_flag` TINYINT DEFAULT 0 COMMENT '至少提前预约时间标志: 1-限制, 0-不限制',
  `cubicle_end_time_flag` TINYINT DEFAULT 0 COMMENT '最多提前预约时间标志: 1-限制, 0-不限制',
  `source_type` VARCHAR(255) COMMENT 'default_rule, resource_rule',
  `source_id` BIGINT,
  `resource_type` VARCHAR(64) COMMENT '资源类型',
  `holiday_open_flag` TINYINT COMMENT '节假日是否开放预约: 1-是, 0-否',
  `holiday_type` TINYINT COMMENT '1-普通双休, 2-同步中国节假日',
  `refund_strategy` TINYINT COMMENT '1-custom, 2-full',
  `overtime_strategy` TINYINT COMMENT '1-custom, 2-full',
  `remark_flag` TINYINT COMMENT '备注是否必填 0否 1是',
  `remark` VARCHAR(255) COMMENT '备注显示文案',
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;