-- 审批分类初始数据
INSERT INTO `eh_enterprise_approval_groups` (`id`, `namespace_id`, `owner_type`, `owner_id`, `name`, `status`, `group_attribute`, `operator_uid`, `operator_time`) VALUES ('1', '0', NULL, '0', '出勤休假', '1', 'DEFAULT', '1', '2018-04-28 09:00:00');
INSERT INTO `eh_enterprise_approval_groups` (`id`, `namespace_id`, `owner_type`, `owner_id`, `name`, `status`, `group_attribute`, `operator_uid`, `operator_time`) VALUES ('2', '0', NULL, '0', '组织人事', '1', 'DEFAULT', '1', '2018-04-28 09:00:00');
INSERT INTO `eh_enterprise_approval_groups` (`id`, `namespace_id`, `owner_type`, `owner_id`, `name`, `status`, `group_attribute`, `operator_uid`, `operator_time`) VALUES ('3', '0', NULL, '0', '行政办公', '1', 'CUSTOMIZE', '1', '2018-04-28 09:00:00');
INSERT INTO `eh_enterprise_approval_groups` (`id`, `namespace_id`, `owner_type`, `owner_id`, `name`, `status`, `group_attribute`, `operator_uid`, `operator_time`) VALUES ('4', '0', NULL, '0', '市场商务', '1', 'CUSTOMIZE', '1', '2018-04-28 09:00:00');
INSERT INTO `eh_enterprise_approval_groups` (`id`, `namespace_id`, `owner_type`, `owner_id`, `name`, `status`, `group_attribute`, `operator_uid`, `operator_time`) VALUES ('5', '0', NULL, '0', '其他', '1', 'CUSTOMIZE', '1', '2018-04-28 09:00:00');


INSERT INTO `eh_enterprise_approval_templates` (`id`, `namespace_id`, `owner_id`, `owner_type`, `organization_id`, `module_id`, `module_type`, `project_id`, `project_type`, `form_template_id`, `support_type`, `approval_name`, `modify_flag`, `delete_flag`, `icon_uri`, `update_time`, `create_time`, `approval_attribute`) VALUES ('6', '0', '0', 'EhOrganizations', '0', '52000', 'any-module', '0', NULL, '0', '0', '物品领用申请', '1', '1', '', '2018-04-17 21:11:45', '2018-04-17 21:11:43', 'CUSTOMIZE');
INSERT INTO `eh_enterprise_approval_templates` (`id`, `namespace_id`, `owner_id`, `owner_type`, `organization_id`, `module_id`, `module_type`, `project_id`, `project_type`, `form_template_id`, `support_type`, `approval_name`, `modify_flag`, `delete_flag`, `icon_uri`, `update_time`, `create_time`, `approval_attribute`) VALUES ('7', '0', '0', 'EhOrganizations', '0', '52000', 'any-module', '0', NULL, '0', '0', '费用报销申请', '1', '1', '', '2018-04-17 21:11:45', '2018-04-17 21:11:43', 'CUSTOMIZE');
INSERT INTO `eh_enterprise_approval_templates` (`id`, `namespace_id`, `owner_id`, `owner_type`, `organization_id`, `module_id`, `module_type`, `project_id`, `project_type`, `form_template_id`, `support_type`, `approval_name`, `modify_flag`, `delete_flag`, `icon_uri`, `update_time`, `create_time`, `approval_attribute`) VALUES ('8', '0', '0', 'EhOrganizations', '0', '52000', 'any-module', '0', NULL, '0', '0', '用章申请', '1', '1', '', '2018-04-17 21:11:45', '2018-04-17 21:11:43', 'CUSTOMIZE');
INSERT INTO `eh_enterprise_approval_templates` (`id`, `namespace_id`, `owner_id`, `owner_type`, `organization_id`, `module_id`, `module_type`, `project_id`, `project_type`, `form_template_id`, `support_type`, `approval_name`, `modify_flag`, `delete_flag`, `icon_uri`, `update_time`, `create_time`, `approval_attribute`) VALUES ('9', '0', '0', 'EhOrganizations', '0', '52000', 'any-module', '0', NULL, '0', '0', '用车申请', '1', '1', '', '2018-04-17 21:11:45', '2018-04-17 21:11:43', 'CUSTOMIZE');
INSERT INTO `eh_enterprise_approval_templates` (`id`, `namespace_id`, `owner_id`, `owner_type`, `organization_id`, `module_id`, `module_type`, `project_id`, `project_type`, `form_template_id`, `support_type`, `approval_name`, `modify_flag`, `delete_flag`, `icon_uri`, `update_time`, `create_time`, `approval_attribute`) VALUES ('10', '0', '0', 'EhOrganizations', '0', '52000', 'any-module', '0', NULL, '0', '0', '合同申请', '1', '1', '', '2018-04-17 21:11:45', '2018-04-17 21:11:43', 'CUSTOMIZE');
INSERT INTO `eh_enterprise_approval_templates` (`id`, `namespace_id`, `owner_id`, `owner_type`, `organization_id`, `module_id`, `module_type`, `project_id`, `project_type`, `form_template_id`, `support_type`, `approval_name`, `modify_flag`, `delete_flag`, `icon_uri`, `update_time`, `create_time`, `approval_attribute`) VALUES ('11', '0', '0', 'EhOrganizations', '0', '52000', 'any-module', '0', NULL, '0', '0', '付款申请', '1', '1', '', '2018-04-17 21:11:45', '2018-04-17 21:11:43', 'CUSTOMIZE');
INSERT INTO `eh_enterprise_approval_templates` (`id`, `namespace_id`, `owner_id`, `owner_type`, `organization_id`, `module_id`, `module_type`, `project_id`, `project_type`, `form_template_id`, `support_type`, `approval_name`, `modify_flag`, `delete_flag`, `icon_uri`, `update_time`, `create_time`, `approval_attribute`) VALUES ('12', '0', '0', 'EhOrganizations', '0', '52000', 'any-module', '0', NULL, '0', '0', '备用金申请', '1', '1', '', '2018-04-17 21:11:45', '2018-04-17 21:11:43', 'CUSTOMIZE');
