-- added by R for approval-1.6
-- menu
UPDATE `eh_web_menus` SET `id`='52000', `name`='审批管理', `parent_id`='50000', `icon_url`=NULL, `data_type`='react:/approval-management/approval-list/52000/EhOrganizations', `leaf_flag`='0', `status`='2', `path`='/50000/52000', `type`='park', `sort_num`='591', `module_id`='52000', `level`='2', `condition_type`=NULL, `category`='module' WHERE (`id`='52000');
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`, `level`, `condition_type`, `category`) VALUES ('52010', '审批记录', '52000', NULL, 'react:/approval-management/approval-records?approvalModuleId=52000', '0', '2', '/50000/52000/52010', 'park', '591', '52000', '3', NULL, 'module');
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`, `level`, `condition_type`, `category`) VALUES ('52020', '规则设置', '52000', NULL, 'react:/approval-management/approval-list/52000/EhOrganizations', '0', '2', '/50000/52000/52020', 'park', '591', '52000', '3', NULL, 'module');
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`, `level`, `condition_type`, `category`) VALUES ('52030', '表单管理', '52000', NULL, 'react:/form-management/form-list?moduleId=52000&moduleType=approval', '0', '2', '/50000/52000/52030', 'park', '591', '52000', '3', NULL, 'module');

-- template
INSERT INTO `eh_general_form_templates`(`id`, `namespace_id`, `organization_id`, `owner_id`, `owner_type`, `module_id`, `module_type`, `form_name`, `version`, `template_type`, `template_text`, `modify_flag`, `delete_flag`, `update_time`, `create_time`) VALUES (1, 0, 0, 0, 'EhOrganizations', 52000, 'any-module', '请假申请单', 0, 'DEFAULT_JSON', '[{\"dynamicFlag\":0,\"fieldDesc\":\"请输入请假事由\",\"fieldDisplayName\":\"请假事由\",\"fieldExtra\":\"{}\",\"fieldName\":\"请假事由\",\"fieldType\":\"MULTI_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":0},{\"dynamicFlag\":0,\"fieldDisplayName\":\"请假时段\",\"fieldExtra\":\"{}\",\"fieldName\":\"请假时段\",\"fieldType\":\"ASK_FOR_LEAVE\",\"renderType\":\"DEFAULT\",\"requiredFlag\":1,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":0,\"deleteFlag\":0},{\"dynamicFlag\":0,\"fieldDisplayName\":\"说明图片\",\"fieldExtra\":\"{\\\"limitCount\\\":9,\\\"limitPerSize\\\":5242880}\",\"fieldName\":\"说明图片\",\"fieldType\":\"IMAGE\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"IMAGE_COUNT_SIZE_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1}]', 1, 0, '2017-10-17 21:25:37', '2017-10-17 21:25:33');
INSERT INTO `eh_general_form_templates`(`id`, `namespace_id`, `organization_id`, `owner_id`, `owner_type`, `module_id`, `module_type`, `form_name`, `version`, `template_type`, `template_text`, `modify_flag`, `delete_flag`, `update_time`, `create_time`) VALUES (2, 0, 0, 0, 'EhOrganizations', 52000, 'any-module', '加班申请单', 0, 'DEFAULT_JSON', '[{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"加班事由\",\"fieldExtra\":\"{}\",\"fieldName\":\"加班事由\",\"fieldType\":\"MULTI_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":0},{\"dynamicFlag\":0,\"fieldDisplayName\":\"加班时段\",\"fieldExtra\":\"{}\",\"fieldName\":\"加班时段\",\"fieldType\":\"OVERTIME\",\"renderType\":\"DEFAULT\",\"requiredFlag\":1,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":0,\"deleteFlag\":0},{\"dynamicFlag\":0,\"fieldDisplayName\":\"说明图片\",\"fieldExtra\":\"{\\\"limitCount\\\":9,\\\"limitPerSize\\\":5242880}\",\"fieldName\":\"说明图片\",\"fieldType\":\"IMAGE\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"IMAGE_COUNT_SIZE_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1}]', 1, 0, '2017-10-17 21:25:37', '2017-10-17 21:25:33');
INSERT INTO `eh_general_form_templates`(`id`, `namespace_id`, `organization_id`, `owner_id`, `owner_type`, `module_id`, `module_type`, `form_name`, `version`, `template_type`, `template_text`, `modify_flag`, `delete_flag`, `update_time`, `create_time`) VALUES (3, 0, 0, 0, 'EhOrganizations', 52000, 'any-module', '出差申请单', 0, 'DEFAULT_JSON', '[{\"dynamicFlag\":0,\"fieldDesc\":\"请输入出差事由\",\"fieldDisplayName\":\"出差事由\",\"fieldExtra\":\"{}\",\"fieldName\":\"出差事由\",\"fieldType\":\"MULTI_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":0},{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"出差地点\",\"fieldExtra\":\"{\\\"limitWord\\\":10}\",\"fieldName\":\"出差地点\",\"fieldType\":\"SINGLE_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1},{\"dynamicFlag\":0,\"fieldDisplayName\":\"出差时段\",\"fieldExtra\":\"{}\",\"fieldName\":\"出差时段\",\"fieldType\":\"BUSINESS_TRIP\",\"renderType\":\"DEFAULT\",\"requiredFlag\":1,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":0,\"deleteFlag\":0},{\"dynamicFlag\":0,\"fieldDisplayName\":\"说明图片\",\"fieldExtra\":\"{\\\"limitCount\\\":9,\\\"limitPerSize\\\":5242880}\",\"fieldName\":\"说明图片\",\"fieldType\":\"IMAGE\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"IMAGE_COUNT_SIZE_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1}]', 1, 0, '2017-10-17 21:25:37', '2017-10-17 21:25:33');
INSERT INTO `eh_general_form_templates`(`id`, `namespace_id`, `organization_id`, `owner_id`, `owner_type`, `module_id`, `module_type`, `form_name`, `version`, `template_type`, `template_text`, `modify_flag`, `delete_flag`, `update_time`, `create_time`) VALUES (4, 0, 0, 0, 'EhOrganizations', 52000, 'any-module', '外出申请单', 0, 'DEFAULT_JSON', '[{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"外出事由\",\"fieldExtra\":\"{}\",\"fieldName\":\"外出事由\",\"fieldType\":\"MULTI_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":0},{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"外出地点\",\"fieldExtra\":\"{\\\"limitWord\\\":10}\",\"fieldName\":\"外出地点\",\"fieldType\":\"SINGLE_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1},{\"dynamicFlag\":0,\"fieldDisplayName\":\"外出时段\",\"fieldExtra\":\"{}\",\"fieldName\":\"外出时段\",\"fieldType\":\"GO_OUT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":1,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":0,\"deleteFlag\":0},{\"dynamicFlag\":0,\"fieldDisplayName\":\"说明图片\",\"fieldExtra\":\"{\\\"limitCount\\\":9,\\\"limitPerSize\\\":5242880}\",\"fieldName\":\"说明图片\",\"fieldType\":\"IMAGE\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"IMAGE_COUNT_SIZE_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1}]', 1, 0, '2017-10-17 21:25:37', '2017-10-17 21:25:33');
INSERT INTO `eh_general_form_templates`(`id`, `namespace_id`, `organization_id`, `owner_id`, `owner_type`, `module_id`, `module_type`, `form_name`, `version`, `template_type`, `template_text`, `modify_flag`, `delete_flag`, `update_time`, `create_time`) VALUES (5, 0, 0, 0, 'EhOrganizations', 52000, 'any-module', '打卡异常申请单', 0, 'DEFAULT_JSON', '[{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"异常事由\",\"fieldExtra\":\"{}\",\"fieldName\":\"异常事由\",\"fieldType\":\"MULTI_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":0},{\"dynamicFlag\":0,\"fieldDisplayName\":\"异常时间\",\"fieldExtra\":\"{}\",\"fieldName\":\"异常时间\",\"fieldType\":\"ABNORMAL_PUNCH\",\"renderType\":\"DEFAULT\",\"requiredFlag\":1,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":0,\"deleteFlag\":0},{\"dynamicFlag\":0,\"fieldDisplayName\":\"说明图片\",\"fieldExtra\":\"{\\\"limitCount\\\":9,\\\"limitPerSize\\\":5242880}\",\"fieldName\":\"说明图片\",\"fieldType\":\"IMAGE\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"IMAGE_COUNT_SIZE_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1}]', 1, 0, '2017-10-17 21:25:37', '2017-10-17 21:25:33');

INSERT INTO `eh_general_approval_templates`(`id`, `namespace_id`, `owner_id`, `owner_type`, `organization_id`, `module_id`, `module_type`, `project_id`, `project_type`, `form_template_id`, `support_type`, `approval_name`, `modify_flag`, `delete_flag`, `icon_uri`, `update_time`, `create_time`, `approval_attribute`) VALUES (1, 0, 0, 'EhOrganizations', 0, 52000, 'any-module', 0, NULL, 1, 0, '请假', 0, 0, 'cs://1/image/aW1hZ2UvTVRwbU1qTTFZekl3TnpNM05UQTNabU14Wm1Jd04yWmtaakprTldFd01qTTBOQQ', '2017-10-17 21:11:05', '2017-10-17 21:11:03', 'ASK_FOR_LEAVE');
INSERT INTO `eh_general_approval_templates`(`id`, `namespace_id`, `owner_id`, `owner_type`, `organization_id`, `module_id`, `module_type`, `project_id`, `project_type`, `form_template_id`, `support_type`, `approval_name`, `modify_flag`, `delete_flag`, `icon_uri`, `update_time`, `create_time`, `approval_attribute`) VALUES (2, 0, 0, 'EhOrganizations', 0, 52000, 'any-module', 0, NULL, 2, 0, '加班', 0, 0, 'cs://1/image/aW1hZ2UvTVRwbU16RTJNR05oWVdZME1tVXlNR0UzWXpjd01tTmhNamxtWmpobVlURmhaQQ', '2017-10-17 21:11:15', '2017-10-17 21:11:13', 'OVERTIME');
INSERT INTO `eh_general_approval_templates`(`id`, `namespace_id`, `owner_id`, `owner_type`, `organization_id`, `module_id`, `module_type`, `project_id`, `project_type`, `form_template_id`, `support_type`, `approval_name`, `modify_flag`, `delete_flag`, `icon_uri`, `update_time`, `create_time`, `approval_attribute`) VALUES (3, 0, 0, 'EhOrganizations', 0, 52000, 'any-module', 0, NULL, 3, 0, '出差', 0, 0, 'cs://1/image/aW1hZ2UvTVRwaU1tRXhaV1V4WlRRM00yVmlOalV4TmpRNU4yWXdNbVpqWXpBek5XSmhNUQ', '2017-10-17 21:11:25', '2017-10-17 21:11:23', 'BUSINESS_TRIP');
INSERT INTO `eh_general_approval_templates`(`id`, `namespace_id`, `owner_id`, `owner_type`, `organization_id`, `module_id`, `module_type`, `project_id`, `project_type`, `form_template_id`, `support_type`, `approval_name`, `modify_flag`, `delete_flag`, `icon_uri`, `update_time`, `create_time`, `approval_attribute`) VALUES (4, 0, 0, 'EhOrganizations', 0, 52000, 'any-module', 0, NULL, 4, 0, '外出', 0, 0, 'cs://1/image/aW1hZ2UvTVRvME9UUmxaREJrWlRWbVpEZzFOV05tTWpOaVlqaGlNMkl5Tm1RNE1UY3dNZw', '2017-10-17 21:11:35', '2017-10-17 21:11:33', 'GO_OUT');
INSERT INTO `eh_general_approval_templates`(`id`, `namespace_id`, `owner_id`, `owner_type`, `organization_id`, `module_id`, `module_type`, `project_id`, `project_type`, `form_template_id`, `support_type`, `approval_name`, `modify_flag`, `delete_flag`, `icon_uri`, `update_time`, `create_time`, `approval_attribute`) VALUES (5, 0, 0, 'EhOrganizations', 0, 52000, 'any-module', 0, NULL, 5, 0, '打卡异常', 0, 0, 'cs://1/image/aW1hZ2UvTVRwaE5URTFZMlZsT1RZNU0ySTVOamM0TkdNM1lUWTJaVGN4TTJOak1URmlaZw', '2017-10-17 21:11:45', '2017-10-17 21:11:43', 'ABNORMAL_PUNCH');
-- ended by R

-- added for 10.1.10.85
SET @scope_id = (SELECT MAX(id) from `eh_web_menu_scopes`)
INSERT INTO `eh_web_menu_scopes`(`id`, `menu_id`, `menu_name`, `owner_type`, `owner_id`, `apply_policy`) VALUES (@scope_id := @scope_id +1, 52000, '', 'EhNamespaces', 999975, 2);
INSERT INTO `eh_web_menu_scopes`(`id`, `menu_id`, `menu_name`, `owner_type`, `owner_id`, `apply_policy`) VALUES (@scope_id := @scope_id +1, 52010, '审批记录', 'EhNamespaces', 999975, 2);
INSERT INTO `eh_web_menu_scopes`(`id`, `menu_id`, `menu_name`, `owner_type`, `owner_id`, `apply_policy`) VALUES (@scope_id := @scope_id +1, 52020, '规则设置', 'EhNamespaces', 999975, 2);
INSERT INTO `eh_web_menu_scopes`(`id`, `menu_id`, `menu_name`, `owner_type`, `owner_id`, `apply_policy`) VALUES (@scope_id := @scope_id +1, 52030, '表单管理', 'EhNamespaces', 999975, 2);

SET @category_id = (SELECT MAX(id) FROM `eh_configurations`);
INSERT INTO `eh_approval_categories` (`id`, `namespace_id`, `owner_type`, `owner_id`, `approval_type`, `category_name`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES (@category_id := @category_id + 1, '0', NULL, '0', '1', '调休', '2', '212500', '2017-11-03 09:00:05', '2017-11-03 09:00:05', '212500');
INSERT INTO `eh_approval_categories` (`id`, `namespace_id`, `owner_type`, `owner_id`, `approval_type`, `category_name`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES (@category_id := @category_id + 1, '0', NULL, '0', '1', '婚假', '2', '212500', '2017-11-03 09:00:06', '2017-11-03 09:00:06', '212500');
INSERT INTO `eh_approval_categories` (`id`, `namespace_id`, `owner_type`, `owner_id`, `approval_type`, `category_name`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES (@category_id := @category_id + 1, '0', NULL, '0', '1', '产假', '2', '212500', '2017-11-03 09:00:07', '2017-11-03 09:00:07', '212500');
INSERT INTO `eh_approval_categories` (`id`, `namespace_id`, `owner_type`, `owner_id`, `approval_type`, `category_name`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES (@category_id := @category_id + 1, '0', NULL, '0', '1', '陪产假', '2', '212500', '2017-11-03 09:00:08', '2017-11-03 09:00:08', '212500');
INSERT INTO `eh_approval_categories` (`id`, `namespace_id`, `owner_type`, `owner_id`, `approval_type`, `category_name`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES (@category_id := @category_id + 1, '0', NULL, '0', '1', '丧假', '2', '212500', '2017-11-03 09:00:09', '2017-11-03 09:00:09', '212500');
INSERT INTO `eh_approval_categories` (`id`, `namespace_id`, `owner_type`, `owner_id`, `approval_type`, `category_name`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES (@category_id := @category_id + 1, '0', NULL, '0', '1', '工伤假', '2', '212500', '2017-11-03 09:00:10', '2017-11-03 09:00:10', '212500');
INSERT INTO `eh_approval_categories` (`id`, `namespace_id`, `owner_type`, `owner_id`, `approval_type`, `category_name`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES (@category_id := @category_id + 1, '0', NULL, '0', '1', '路途假', '2', '212500', '2017-11-03 09:00:11', '2017-11-03 09:00:11', '212500');
