-- --------------------- SECTION BEGIN -------------------------------------------------------
-- ENV: ALL
-- DESCRIPTION: 此SECTION放所有域空间都需要执行的脚本，包含基线、独立部署、研发数据等环境
-- AUTHOR: tangcen
-- REMARK: 楼宇资产管理模块添加自定义tab卡
SET @var_field_groups_id = (SELECT MAX(id) FROM `eh_var_field_groups`);
INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`) VALUES ((@var_field_groups_id:=@var_field_groups_id+1), 'asset_management', '0', CONCAT('/',@var_field_groups_id), '客户管理', '', '0', NULL, '2', '1', NOW(), NULL, NULL);
INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`) VALUES ((@var_field_groups_id:=@var_field_groups_id+1), 'asset_management', '0', CONCAT('/',@var_field_groups_id), '住户管理', '', '0', NULL, '2', '1', NOW(), NULL, NULL);
INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`) VALUES ((@var_field_groups_id:=@var_field_groups_id+1), 'asset_management', '0', CONCAT('/',@var_field_groups_id), '合同管理', '', '0', NULL, '2', '1', NOW(), NULL, NULL);
INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`) VALUES ((@var_field_groups_id:=@var_field_groups_id+1), 'asset_management', '0', CONCAT('/',@var_field_groups_id), '账单管理', '', '0', NULL, '2', '1', NOW(), NULL, NULL);
INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`) VALUES ((@var_field_groups_id:=@var_field_groups_id+1), 'asset_management', '0', CONCAT('/',@var_field_groups_id), '活动记录', '', '0', NULL, '2', '1', NOW(), NULL, NULL);
INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`) VALUES ((@var_field_groups_id:=@var_field_groups_id+1), 'asset_management', '0', CONCAT('/',@var_field_groups_id), '车辆管理', '', '0', NULL, '2', '1', NOW(), NULL, NULL);
INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`) VALUES ((@var_field_groups_id:=@var_field_groups_id+1), 'asset_management', '0', CONCAT('/',@var_field_groups_id), '服务信息', '', '0', NULL, '2', '1', NOW(), NULL, NULL);
INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`) VALUES ((@var_field_groups_id:=@var_field_groups_id+1), 'asset_management', '0', CONCAT('/',@var_field_groups_id), '历史房源', '', '0', NULL, '2', '1', NOW(), NULL, NULL);
INSERT INTO `eh_var_field_groups` (`id`, `module_name`, `parent_id`, `path`, `title`, `name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`) VALUES ((@var_field_groups_id:=@var_field_groups_id+1), 'asset_management', '0', CONCAT('/',@var_field_groups_id), '附件', '', '0', NULL, '2', '1', NOW(), NULL, NULL);
-- --------------------- SECTION END ---------------------------------------------------------
