-- 表单 by dengs,20170711
set @eh_general_forms_id = (select max(id) from eh_general_forms);
set @namespace_id = 999971; -- 此处应该修改为张江的namespace
set @appKey = '7757a75f-b79a-42fd-896e-107f4b59';
set @secretKey = 'nM9PpqGaV2Qe5QqmNSHfW';
-- appkey
set @eh_apps_id = (select MAX(id) FROM eh_apps);
INSERT INTO `ehcore`.`eh_apps` (`id`, `creator_uid`, `app_key`, `secret_key`, `name`, `description`, `status`, `create_time`, `update_uid`, `update_time`) VALUES ((@eh_apps_id:=@eh_apps_id+1), '1', @appKey, @secretKey, 'zjgk', 'zjgk app key', '1', NOW(), NULL, NULL);
-- appkey mapping namespace
set @eh_app_namespace_mappings_id = (select MAX(id) FROM eh_app_namespace_mappings);
INSERT INTO `ehcore`.`eh_app_namespace_mappings` (`id`, `namespace_id`, `app_key`, `community_id`) VALUES ((@eh_app_namespace_mappings_id:=@eh_app_namespace_mappings_id+1), @namespace_id, @appKey, '1');

-- json 需要重新写
INSERT INTO `eh_general_forms` (`id`, `namespace_id`, `organization_id`, `owner_id`, `owner_type`, `module_id`, `module_type`, `form_name`, `form_origin_id`, `form_version`, `template_type`, `template_text`, `status`, `update_time`, `create_time`, `string_tag1`, `string_tag2`, `string_tag3`, `string_tag4`, `string_tag5`, `integral_tag1`, `integral_tag2`, `integral_tag3`, `integral_tag4`, `integral_tag5`) VALUES ((@eh_general_forms_id := @eh_general_forms_id+1), @namespace_id, 0, 0, 'personal_auth', NULL, NULL, '张江个人认证', 448, 0, 'DEFAULT_JSON', '[{"dataSourceType": "USER_PHONE","fieldDesc": "请输入手机号码","fieldDisplayName": "手机号","fieldExtra": "{\\"limitWord\\":50}","fieldName": "phone","fieldType": "MULTI_LINE_TEXT","renderType": "DEFAULT","requiredFlag": 1,"validatorType": "TEXT_LIMIT","visibleType": "READONLY"},{"fieldDesc": "请输入真实姓名","fieldDisplayName": "姓名","fieldExtra": "{\\"limitWord\\":50}","fieldName": "name","fieldType": "MULTI_LINE_TEXT","renderType": "DEFAULT","requiredFlag": 1,"validatorType": "TEXT_LIMIT","visibleType": "EDITABLE"},{"fieldDesc": "身份证","fieldDisplayName": "证件类型","fieldExtra": "{\\"limitWord\\":30}","fieldName": "certificateType","fieldType": "MULTI_LINE_TEXT","renderType": "DEFAULT","requiredFlag": 1,"validatorType": "TEXT_LIMIT","visibleType": "EDITABLE"},{"fieldDesc": "请输入证件号码","fieldDisplayName": "证件号码","fieldExtra": "{\\"limitWord\\":50}","fieldName": "certificateNo","fieldType": "MULTI_LINE_TEXT","renderType": "DEFAULT","requiredFlag": 1,"validatorType": "TEXT_LIMIT","visibleType": "EDITABLE"}]', 1, NOW(), NOW(), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_general_forms` (`id`, `namespace_id`, `organization_id`, `owner_id`, `owner_type`, `module_id`, `module_type`, `form_name`, `form_origin_id`, `form_version`, `template_type`, `template_text`, `status`, `update_time`, `create_time`, `string_tag1`, `string_tag2`, `string_tag3`, `string_tag4`, `string_tag5`, `integral_tag1`, `integral_tag2`, `integral_tag3`, `integral_tag4`, `integral_tag5`) VALUES ((@eh_general_forms_id := @eh_general_forms_id+1), @namespace_id, 0, 0, 'organization_auth', NULL, NULL, '张江企业认证', 449, 0, 'DEFAULT_JSON', '[{"fieldDesc": "请输入准确的组织机构代码","fieldDisplayName": "组织机构代码","fieldExtra": "{\\"limitWord\\":50}","fieldName": "organizationCode","fieldType": "MULTI_LINE_TEXT","renderType": "DEFAULT","requiredFlag": 1,"validatorType": "TEXT_LIMIT","visibleType": "EDITABLE"},{"fieldDesc": "请输入承租时填写的企业联系人","fieldDisplayName": "企业联系人","fieldExtra": "{\\"limitWord\\":50}","fieldName": "organizationContact","fieldType": "MULTI_LINE_TEXT","renderType": "DEFAULT","requiredFlag": 1,"validatorType": "TEXT_LIMIT","visibleType": "EDITABLE"},{"fieldDesc": "请输入承租时填写的企业联系电话","fieldDisplayName": "企业联系电话","fieldExtra": "{\\"limitWord\\":50}","fieldName": "organizationPhone","fieldType": "MULTI_LINE_TEXT","renderType": "DEFAULT","requiredFlag": 1,"validatorType": "TEXT_LIMIT","visibleType": "EDITABLE"}]', 1, NOW(), NOW(), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

-- 张江表单和张江namespace关联
INSERT INTO `eh_authorization_third_party_forms` (`id`, `namespace_id`, `owner_type`, `owner_id`, `source_type`, `source_id`, `authorization_url`, `app_key`, `secret_key`, `title`, `detail`, `creator_uid`, `create_time`, `operator_uid`, `update_time`) VALUES (1, @namespace_id, 'EhNamespaces', @namespace_id, 'personal_auth', 0, 'http://139.129.220.146:3578/openapi/Authenticate', 'ee4c8905-9aa4-4d45-973c-ede4cbb3cf21', '2CQ7dgiGCIfdKyHfHzO772IltqC50e9w7fswbn6JezdEAZU+x4+VHsBE/RKQ5BCkz/irj0Kzg6te6Y9JLgAvbQ==', '个人认证', '认证我的居住地址', 0, NOW(), NULL, NOW());
INSERT INTO `eh_authorization_third_party_forms` (`id`, `namespace_id`, `owner_type`, `owner_id`, `source_type`, `source_id`, `authorization_url`, `app_key`, `secret_key`, `title`, `detail`, `creator_uid`, `create_time`, `operator_uid`, `update_time`) VALUES (2, @namespace_id, 'EhNamespaces', @namespace_id, 'organization_auth', 0, 'http://139.129.220.146:3578/openapi/Authenticate', 'ee4c8905-9aa4-4d45-973c-ede4cbb3cf21', '2CQ7dgiGCIfdKyHfHzO772IltqC50e9w7fswbn6JezdEAZU+x4+VHsBE/RKQ5BCkz/irj0Kzg6te6Y9JLgAvbQ==', '企业认证', '认证企业承租地址', 0, NOW(), NULL, NOW());

-- buttons状态
INSERT INTO `eh_authorization_third_party_buttons` (`id`, `namespace_id`, `owner_type`, `owner_id`, `title`, `modify_flag`, `families_flag`, `qrcode_flag`, `delete_flag`, `blank_detail`,`button_detail`, `creator_uid`, `create_time`, `operator_uid`, `update_time`) VALUES (1, @namespace_id, 'EhNamespaces', @namespace_id, '公寓信息', 0, 1, 0, 0,'您还未加入任何公寓，快来加入吧！','申请认证', NULL, NOW(), NULL, NOW());

-- 文本
set @eh_locale_strings_id = (select MAX(id) FROM eh_locale_strings);
INSERT INTO `eh_locale_strings` (`id`, `scope`, `code`, `locale`, `text`) VALUES 
	((@eh_locale_strings_id := @eh_locale_strings_id + 1), 'third.party.authorization', 'work_flow_title', 'zh_CN', '姓名 : |证件号码 : |个人认证申请|组织机构代码 : |企业联系人 : |企业认证申请');
INSERT INTO `eh_locale_strings` (`id`, `scope`, `code`, `locale`, `text`) VALUES 
	((@eh_locale_strings_id := @eh_locale_strings_id + 1), 'third.party.authorization', 'personal_back_code_detail', 'zh_CN', '很遗憾，您的认证未成功|1、请检测信息填写是否正确，如填写有误，请重新提交|2、如填写无误，请到携带相关证件管理处核对信息|您已退租，如有疑问请联系客服|恭喜您，成为我们的一员，您承租的地址信息如下|未定义的返回码|园区[|]不存在|园区[|]名称存在多个|地址|请求认证失败！|系统认证异常，已退出家庭');
INSERT INTO `eh_locale_strings` (`id`, `scope`, `code`, `locale`, `text`) VALUES 
	((@eh_locale_strings_id := @eh_locale_strings_id + 1), 'third.party.authorization', 'organization_back_code_detail', 'zh_CN', '提交信息匹配不成功|1、请检测信息填写是否正确，如填写有误，请重新提交|2、如填写无误，请到携带相关证件管理处核对信息|您已退租，如有疑问请联系客服|认证成功！您承租地址信息如下|未定义的返回码|园区[|]不存在|园区[|]名称存在多个|地址|请求认证失败！|系统认证异常，已退出公司');
INSERT INTO `eh_locale_strings` (`id`, `scope`, `code`, `locale`, `text`) VALUES 
	((@eh_locale_strings_id := @eh_locale_strings_id + 1), 'third.party.authorization', 'work_flow_content', 'zh_CN', '组织机构代码|企业联系人|企业联系电话|认证反馈结果|手机号|姓名|证件类型|证件号码|认证反馈结果|身份证|未知证件类型');
INSERT INTO `eh_locale_strings` (`id`, `scope`, `code`, `locale`, `text`) VALUES 
	((@eh_locale_strings_id := @eh_locale_strings_id + 1), 'third.party.authorization', 'family_detail', 'zh_CN', '家庭信息|您还未加入任何家庭，快去加入吧!|添加住址');
