-- 表单 by dengs,20170711
set @eh_general_forms_id = (select max(id) from eh_general_forms);
set @namespace_id = -1; -- 此处应该修改为张江的namespace
-- json 需要重新写
INSERT INTO `eh_general_forms` (`id`, `namespace_id`, `organization_id`, `owner_id`, `owner_type`, `module_id`, `module_type`, `form_name`, `form_origin_id`, `form_version`, `template_type`, `template_text`, `status`, `update_time`, `create_time`, `string_tag1`, `string_tag2`, `string_tag3`, `string_tag4`, `string_tag5`, `integral_tag1`, `integral_tag2`, `integral_tag3`, `integral_tag4`, `integral_tag5`) VALUES ((@eh_general_forms_id := @eh_general_forms_id+1), @namespace_id, 0, 1, 'zj_personal_auth', NULL, NULL, '张江个人认证', 448, 0, 'DEFAULT_JSON', '[{"dataSourceType":"USER_NAME","dynamicFlag":1,"fieldDisplayName":"姓名","fieldExtra":"{\\"limitWord\\":10}","fieldName":"USER_NAME","fieldType":"SINGLE_LINE_TEXT","renderType":"DEFAULT","validatorType":"TEXT_LIMIT","visibleType":"HIDDEN"},{"dataSourceType":"USER_PHONE","dynamicFlag":1,"fieldDisplayName":"联系电话","fieldExtra":"{\\"limitLength\\":11}","fieldName":"USER_PHONE","fieldType":"NUMBER_TEXT","renderType":"DEFAULT","validatorType":"TEXT_LIMIT","visibleType":"HIDDEN"},{"dataSourceType":"USER_COMPANY","dynamicFlag":1,"fieldDisplayName":"企业","fieldExtra":"{}","fieldName":"USER_COMPANY","fieldType":"MULTI_LINE_TEXT","renderType":"DEFAULT","validatorType":"TEXT_LIMIT","visibleType":"HIDDEN"},{"dataSourceType":"USER_ADDRESS","dynamicFlag":1,"fieldDisplayName":"楼栋门牌","fieldExtra":"{}","fieldName":"USER_ADDRESS","fieldType":"MULTI_LINE_TEXT","renderType":"DEFAULT","validatorType":"TEXT_LIMIT","visibleType":"HIDDEN"},{"fieldDesc":"请输入手机号码","fieldDisplayName":"手机号","fieldExtra":"{\\"limitWord\\":50}","fieldName":"手机号","fieldType":"MULTI_LINE_TEXT","renderType":"DEFAULT","requiredFlag":1,"validatorType":"TEXT_LIMIT","visibleType":"EDITABLE"},{"fieldDesc":"请输入真实姓名","fieldDisplayName":"姓        名","fieldExtra":"{\\"limitWord\\":50}","fieldName":"姓        名","fieldType":"MULTI_LINE_TEXT","renderType":"DEFAULT","requiredFlag":1,"validatorType":"TEXT_LIMIT","visibleType":"EDITABLE"},{"fieldDesc":"身份证","fieldDisplayName":"证件类型","fieldExtra":"{\\"limitWord\\":30}","fieldName":"证件类型","fieldType":"MULTI_LINE_TEXT","renderType":"DEFAULT","requiredFlag":1,"validatorType":"TEXT_LIMIT","visibleType":"EDITABLE"},{"fieldDesc":"请输入证件号码","fieldDisplayName":"证件号码","fieldExtra":"{\\"limitWord\\":50}","fieldName":"证件号码","fieldType":"MULTI_LINE_TEXT","renderType":"DEFAULT","requiredFlag":1,"validatorType":"TEXT_LIMIT","visibleType":"EDITABLE"}]', 1, NOW(), NOW(), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_general_forms` (`id`, `namespace_id`, `organization_id`, `owner_id`, `owner_type`, `module_id`, `module_type`, `form_name`, `form_origin_id`, `form_version`, `template_type`, `template_text`, `status`, `update_time`, `create_time`, `string_tag1`, `string_tag2`, `string_tag3`, `string_tag4`, `string_tag5`, `integral_tag1`, `integral_tag2`, `integral_tag3`, `integral_tag4`, `integral_tag5`) VALUES ((@eh_general_forms_id := @eh_general_forms_id+1), @namespace_id, 0, 2, 'zj_organization_auth', NULL, NULL, '张江企业认证', 449, 0, 'DEFAULT_JSON', '[{"dataSourceType":"USER_NAME","dynamicFlag":1,"fieldDisplayName":"姓名","fieldExtra":"{\\"limitWord\\":10}","fieldName":"USER_NAME","fieldType":"SINGLE_LINE_TEXT","renderType":"DEFAULT","validatorType":"TEXT_LIMIT","visibleType":"HIDDEN"},{"dataSourceType":"USER_PHONE","dynamicFlag":1,"fieldDisplayName":"联系电话","fieldExtra":"{\\"limitLength\\":11}","fieldName":"USER_PHONE","fieldType":"NUMBER_TEXT","renderType":"DEFAULT","validatorType":"TEXT_LIMIT","visibleType":"HIDDEN"},{"dataSourceType":"USER_COMPANY","dynamicFlag":1,"fieldDisplayName":"企业","fieldExtra":"{}","fieldName":"USER_COMPANY","fieldType":"MULTI_LINE_TEXT","renderType":"DEFAULT","validatorType":"TEXT_LIMIT","visibleType":"HIDDEN"},{"dataSourceType":"USER_ADDRESS","dynamicFlag":1,"fieldDisplayName":"楼栋门牌","fieldExtra":"{}","fieldName":"USER_ADDRESS","fieldType":"MULTI_LINE_TEXT","renderType":"DEFAULT","validatorType":"TEXT_LIMIT","visibleType":"HIDDEN"},{"fieldDesc":"请输入准确的组织机构代码","fieldDisplayName":"组织机构代码","fieldExtra":"{\\"limitWord\\":50}","fieldName":"组织机构代码","fieldType":"MULTI_LINE_TEXT","renderType":"DEFAULT","requiredFlag":1,"validatorType":"TEXT_LIMIT","visibleType":"EDITABLE"},{"fieldDesc":"请输入承租时填写的企业联系人","fieldDisplayName":"企业联系人","fieldExtra":"{\\"limitWord\\":50}","fieldName":"企业联系人","fieldType":"MULTI_LINE_TEXT","renderType":"DEFAULT","requiredFlag":1,"validatorType":"TEXT_LIMIT","visibleType":"EDITABLE"},{"fieldDesc":"请输入承租时填写的企业联系电话","fieldDisplayName":"企业联系电话","fieldExtra":"{\\"limitWord\\":50}","fieldName":"企业联系电话","fieldType":"MULTI_LINE_TEXT","renderType":"DEFAULT","requiredFlag":1,"validatorType":"TEXT_LIMIT","visibleType":"EDITABLE"}]', 1, NOW(), NOW(), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

-- 张江表单和张江namespace关联
set @eh_lease_form_requests_id = (select max(id) from eh_lease_form_requests);
INSERT INTO `eh_lease_form_requests` (`id`, `namespace_id`, `owner_id`, `owner_type`, `source_id`, `source_type`, `create_time`) VALUES ((@eh_lease_form_requests_id := @eh_lease_form_requests_id+1), @namespace_id, @namespace_id, 'EhNamespaces', 1, 'zj_personal_auth', NOW());
INSERT INTO `eh_lease_form_requests` (`id`, `namespace_id`, `owner_id`, `owner_type`, `source_id`, `source_type`, `create_time`) VALUES ((@eh_lease_form_requests_id := @eh_lease_form_requests_id+1), @namespace_id, @namespace_id, 'EhNamespaces', 2, 'zj_organization_auth', NOW());
