-- 表单 by dengs,20170711
set @eh_general_forms_id = (select max(id) from eh_general_forms);
set @namespace_id = 0; -- 此处应该修改为张江的namespace
-- json 需要重新写
INSERT INTO `eh_general_forms` (`id`, `namespace_id`, `organization_id`, `owner_id`, `owner_type`, `module_id`, `module_type`, `form_name`, `form_origin_id`, `form_version`, `template_type`, `template_text`, `status`, `update_time`, `create_time`, `string_tag1`, `string_tag2`, `string_tag3`, `string_tag4`, `string_tag5`, `integral_tag1`, `integral_tag2`, `integral_tag3`, `integral_tag4`, `integral_tag5`) VALUES ((@eh_general_forms_id := @eh_general_forms_id+1), @namespace_id, 0, 0, 'personal_auth', NULL, NULL, '张江个人认证', 448, 0, 'DEFAULT_JSON', '[{"dataSourceType": "USER_PHONE","fieldDesc": "请输入手机号码","fieldDisplayName": "手机号","fieldExtra": "{\\"limitWord\\":50}","fieldName": "phone","fieldType": "MULTI_LINE_TEXT","renderType": "DEFAULT","requiredFlag": 1,"validatorType": "TEXT_LIMIT","visibleType": "EDITABLE"},{"fieldDesc": "请输入真实姓名","fieldDisplayName": "姓名","fieldExtra": "{\\"limitWord\\":50}","fieldName": "name","fieldType": "MULTI_LINE_TEXT","renderType": "DEFAULT","requiredFlag": 1,"validatorType": "TEXT_LIMIT","visibleType": "EDITABLE"},{"fieldDesc": "身份证","fieldDisplayName": "证件类型","fieldExtra": "{\\"limitWord\\":30}","fieldName": "certificateType","fieldType": "MULTI_LINE_TEXT","renderType": "DEFAULT","requiredFlag": 1,"validatorType": "TEXT_LIMIT","visibleType": "EDITABLE"},{"fieldDesc": "请输入证件号码","fieldDisplayName": "证件号码","fieldExtra": "{\\"limitWord\\":50}","fieldName": "certificateNo","fieldType": "MULTI_LINE_TEXT","renderType": "DEFAULT","requiredFlag": 1,"validatorType": "TEXT_LIMIT","visibleType": "EDITABLE"}]', 1, NOW(), NOW(), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `eh_general_forms` (`id`, `namespace_id`, `organization_id`, `owner_id`, `owner_type`, `module_id`, `module_type`, `form_name`, `form_origin_id`, `form_version`, `template_type`, `template_text`, `status`, `update_time`, `create_time`, `string_tag1`, `string_tag2`, `string_tag3`, `string_tag4`, `string_tag5`, `integral_tag1`, `integral_tag2`, `integral_tag3`, `integral_tag4`, `integral_tag5`) VALUES ((@eh_general_forms_id := @eh_general_forms_id+1), @namespace_id, 0, 0, 'organization_auth', NULL, NULL, '张江企业认证', 449, 0, 'DEFAULT_JSON', '[{"fieldDesc": "请输入准确的组织机构代码","fieldDisplayName": "组织机构代码","fieldExtra": "{\\"limitWord\\":50}","fieldName": "organizationCode","fieldType": "MULTI_LINE_TEXT","renderType": "DEFAULT","requiredFlag": 1,"validatorType": "TEXT_LIMIT","visibleType": "EDITABLE"},{"fieldDesc": "请输入承租时填写的企业联系人","fieldDisplayName": "企业联系人","fieldExtra": "{\\"limitWord\\":50}","fieldName": "organizationContact","fieldType": "MULTI_LINE_TEXT","renderType": "DEFAULT","requiredFlag": 1,"validatorType": "TEXT_LIMIT","visibleType": "EDITABLE"},{"fieldDesc": "请输入承租时填写的企业联系电话","fieldDisplayName": "企业联系电话","fieldExtra": "{\\"limitWord\\":50}","fieldName": "organizationPhone","fieldType": "MULTI_LINE_TEXT","renderType": "DEFAULT","requiredFlag": 1,"validatorType": "TEXT_LIMIT","visibleType": "EDITABLE"}]', 1, NOW(), NOW(), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

-- 张江表单和张江namespace关联
INSERT INTO `eh_authorization_third_party_forms` (`id`, `namespace_id`, `owner_type`, `owner_id`, `source_type`, `source_id`, `authorization_url`, `app_key`, `secret_key`, `title`, `detail`, `creator_uid`, `create_time`, `operator_uid`, `update_time`) VALUES (1, @namespace_id, 'EhNamespaces', @namespace_id, 'personal_auth', 0, 'http://139.129.220.146:3578/openapi/Authenticate', 'ee4c8905-9aa4-4d45-973c-ede4cbb3cf21', '2CQ7dgiGCIfdKyHfHzO772IltqC50e9w7fswbn6JezdEAZU+x4+VHsBE/RKQ5BCkz/irj0Kzg6te6Y9JLgAvbQ==', '个人认证', '认证我的居住地址', 0, NOW(), NULL, NOW());
INSERT INTO `eh_authorization_third_party_forms` (`id`, `namespace_id`, `owner_type`, `owner_id`, `source_type`, `source_id`, `authorization_url`, `app_key`, `secret_key`, `title`, `detail`, `creator_uid`, `create_time`, `operator_uid`, `update_time`) VALUES (2, @namespace_id, 'EhNamespaces', @namespace_id, 'organization_auth', 0, 'http://139.129.220.146:3578/openapi/Authenticate', 'ee4c8905-9aa4-4d45-973c-ede4cbb3cf21', '2CQ7dgiGCIfdKyHfHzO772IltqC50e9w7fswbn6JezdEAZU+x4+VHsBE/RKQ5BCkz/irj0Kzg6te6Y9JLgAvbQ==', '企业认证', '认证企业承租地址', 0, NOW(), NULL, NOW());

-- buttons状态
INSERT INTO `eh_authorization_third_party_buttons` (`id`, `namespace_id`, `owner_type`, `owner_id`, `title`, `modify_flag`, `families_flag`, `qrcode_flag`, `delete_flag`, `blank_detail`,`button_detail`, `creator_uid`, `create_time`, `operator_uid`, `update_time`) VALUES (1, @namespace_id, 'EhNamespaces', @namespace_id, '公寓信息', 0, 1, 0, 0,'您还未加入任何公寓，快来加入吧！','申请认证', NULL, NOW(), NULL, NOW());
