
-- 合同动态表单修改  by jiarui
UPDATE  eh_var_field_groups set title = '收款合同' WHERE  module_name ='contract' and title ='合同信息' AND  parent_id =0;

-- 表单default  by jiarui

SET  @id = (SELECT MAX(id) FROM  eh_var_field_group_scopes);
INSERT INTO `eh_var_field_group_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `group_display_name`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_parent_id`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '1', '客户信息', '1', '2', '1', NOW(), NULL, NULL, NULL, NULL);
INSERT INTO `eh_var_field_group_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `group_display_name`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_parent_id`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '10', '基本信息', '1', '2', '1', NOW(), NULL, NULL, NULL, NULL);
INSERT INTO `eh_var_field_group_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `group_display_name`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_parent_id`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '11', '企业情况', '3', '2', '1',NOW(), NULL, NULL, NULL, NULL);
INSERT INTO `eh_var_field_group_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `group_display_name`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_parent_id`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '12', '员工情况', '4', '2', '1', NOW(), NULL, NULL, NULL, NULL);

SET  @id = (SELECT MAX(id) FROM  eh_var_field_scopes);
INSERT INTO `eh_var_field_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `field_id`, `field_param`, `field_display_name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_path`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '10', '2', '{\"fieldParamType\": \"text\", \"length\": 32}', '客户名称', '1', '1', '2', '1', now(), '1', NULL , NULL, '/1/10/');
INSERT INTO `eh_var_field_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `field_id`, `field_param`, `field_display_name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_path`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '10', '3', '{\"fieldParamType\": \"text\", \"length\": 32}', '简称', '0', '3', '2', '1', now(), NULL, NULL, NULL, '/1/10/');
INSERT INTO `eh_var_field_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `field_id`, `field_param`, `field_display_name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_path`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '10', '4', '{\"fieldParamType\": \"select\", \"length\": 32}', '客户类型', '0', '3', '2', '1', now(), NULL, NULL, NULL, '/1/10/');
INSERT INTO `eh_var_field_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `field_id`, `field_param`, `field_display_name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_path`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '10', '5', '{\"fieldParamType\": \"select\", \"length\": 32}', '客户级别', '1', '4', '2', '1', now(), '1', NULL , NULL, '/1/10/');
INSERT INTO `eh_var_field_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `field_id`, `field_param`, `field_display_name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_path`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '10', '7', '{\"fieldParamType\": \"text\", \"length\": 32}', '联系人', '1', '5', '2', '1', now(), '1', NULL , NULL, '/1/10/');
INSERT INTO `eh_var_field_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `field_id`, `field_param`, `field_display_name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_path`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '10', '10', '{\"fieldParamType\": \"text\", \"length\": 32}', '联系电话', '1', '6', '2', '1',now(), '1', NULL , NULL , '/1/10/');
INSERT INTO `eh_var_field_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `field_id`, `field_param`, `field_display_name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_path`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '10', '211', '{\"fieldParamType\": \"text\", \"length\": 32}', '跟进人', '1', '8', '2', '1', now(), '1', NULL , NULL, '/1/10/');

INSERT INTO `eh_var_field_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `field_id`, `field_param`, `field_display_name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_path`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '11', '15', '{\"fieldParamType\": \"text\", \"length\": 32}', '地址', '1', '8', '2', '1', now(), NULL, NULL, NULL, '/1/11/');
INSERT INTO `eh_var_field_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `field_id`, `field_param`, `field_display_name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_path`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '11', '17', '{\"fieldParamType\": \"text\", \"length\": 32}', '企业网址', '0', '11', '2', '1', now(), NULL, NULL, NULL, '/1/11/');
INSERT INTO `eh_var_field_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `field_id`, `field_param`, `field_display_name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_path`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '11', '24', '{\"fieldParamType\": \"select\", \"length\": 32}', '行业类型', '1', '13', '2', '1',now(), NULL, NULL, NULL, '/1/11/');
INSERT INTO `eh_var_field_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `field_id`, `field_param`, `field_display_name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_path`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '11', '36', '{\"fieldParamType\": \"image\", \"length\": 1}', '企业LOGO', '0', '46', '0', '1', now(), '1', NULL , NULL , '/1/11//');
INSERT INTO `eh_var_field_scopes` (`id`, `namespace_id`, `module_name`, `group_id`, `field_id`, `field_param`, `field_display_name`, `mandatory_flag`, `default_order`, `status`, `creator_uid`, `create_time`, `operator_uid`, `update_time`, `community_id`, `group_path`) VALUES ((@id:=@id+1), '0', 'enterprise_customer', '11', '37', '{\"fieldParamType\": \"multiText\", \"length\": 2048}', '企业简介', '0', '26', '2', '1', now(), '1', NULL , NULL , '/1/11/');
