-- 新增装修办理模块 by st.zheng
INSERT INTO `eh_service_modules` (`id`, `name`, `parent_id`, `path`, `type`, `level`, `status`, `default_order`, `create_time`, `instance_config`, `action_type`, `update_time`, `operator_uid`, `creator_uid`, `description`, `multiple_flag`, `module_control_type`, `access_control_type`, `menu_auth_flag`, `category`) VALUES ('43000', '装修办理', '40000', '/200/40000/43000', '1', '3', '2', '10', now(), '{}', '13', now(), '0', '0', '0', NULL, 'community_control', '1', '1', 'module');

INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`, `level`, `condition_type`, `category`, `config_type`) VALUES ('16032200', '装修办理', '16030000', NULL, 'decoration-management', '1', '2', '/16000000/16030000/16032200', 'zuolin', '8', '43000', '3', 'system', 'module', NULL);
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`, `level`, `condition_type`, `category`, `config_type`) VALUES ('45150000', '装修办理', '45000000', NULL, 'decoration-management', '1', '2', '/40000040/45000000/45150000', 'park', '2', '43000', '3', 'system', 'module', NULL);

set @privilege_id = (select max(id) from eh_service_module_privileges);
INSERT INTO `eh_acl_privileges` (`id`, `app_id`, `name`, `description`, `tag`) VALUES (4300043000, '0', '装修办理 全部权限', '装修办理 全部权限', NULL);
INSERT INTO `eh_service_module_privileges` (`id`, `module_id`, `privilege_type`, `privilege_id`, `remark`, `default_order`, `create_time`) VALUES (@privilege_id:=@privilege_id+1, '43000', '0', 4300043000, '全部权限', '0', now());

INSERT INTO `eh_acl_privileges` (`id`, `app_id`, `name`, `description`, `tag`) VALUES (4300043010, '0', '装修办理 装修办理权限', '装修办理 装修办理权限', NULL);
INSERT INTO `eh_service_module_privileges` (`id`, `module_id`, `privilege_type`, `privilege_id`, `remark`, `default_order`, `create_time`) VALUES (@privilege_id:=@privilege_id+1, '43010', '0', 4300043010, '全部权限', '0', now());

set @eh_locale_templates_id = (select max(id) from eh_locale_templates);
INSERT INTO `eh_locale_templates` (`id`, `scope`, `code`, `locale`, `description`, `text`, `namespace_id`) VALUES (@eh_locale_templates_id := @eh_locale_templates_id+1, 'sms.default', '70', 'zh_CN', '装修申请通过', '尊敬的${decoratorName}，用户（${applyName}：${applyPhone}）提交的装修申请（${applyCompamy}）已审核通过，需尽快提交相关装修资料，请前往APP查看详情，您可以点击以下链接下载APP，并使用本机号码进行注册：${url} 。', '0');
INSERT INTO `eh_locale_templates` (`id`, `scope`, `code`, `locale`, `description`, `text`, `namespace_id`) VALUES (@eh_locale_templates_id := @eh_locale_templates_id+1, 'sms.default', '71', 'zh_CN', '资料审核成功', '尊敬的${decoratorName}，关于${applyCompamy}的装修资料已审核通过，请等待管理公司上传费用清单，您可前往APP查看详情。', '0');
INSERT INTO `eh_locale_templates` (`id`, `scope`, `code`, `locale`, `description`, `text`, `namespace_id`) VALUES (@eh_locale_templates_id := @eh_locale_templates_id+1, 'sms.default', '72', 'zh_CN', '资料审核失败', '尊敬的${decoratorName}，关于${applyCompamy}的装修资料审核不通过，装修办理流程已中止，您可前往APP查看详情。', '0');
INSERT INTO `eh_locale_templates` (`id`, `scope`, `code`, `locale`, `description`, `text`, `namespace_id`) VALUES (@eh_locale_templates_id := @eh_locale_templates_id+1, 'sms.default', '73', 'zh_CN', '装修费用清单生成', '尊敬的${name}，关于${applyCompamy}的装修费用清单已上传，需尽快缴费，您可前往APP查看详情。', '0');
INSERT INTO `eh_locale_templates` (`id`, `scope`, `code`, `locale`, `description`, `text`, `namespace_id`) VALUES (@eh_locale_templates_id := @eh_locale_templates_id+1, 'sms.default', '74', 'zh_CN', '缴费完成', '尊敬的${name}，关于${applyCompamy}的装修费用已缴纳，施工人员可凭证进场，请遵守施工相关规定，感谢您的配合。', '0');
INSERT INTO `eh_locale_templates` (`id`, `scope`, `code`, `locale`, `description`, `text`, `namespace_id`) VALUES (@eh_locale_templates_id := @eh_locale_templates_id+1, 'sms.default', '75', 'zh_CN', '竣工验收工作流正常结束', '尊敬的${decoratorName}，关于${applyCompamy}的装修已通过竣工验收，请等待管理公司确认押金退费信息，您可前往APP查看详情。', '0');
INSERT INTO `eh_locale_templates` (`id`, `scope`, `code`, `locale`, `description`, `text`, `namespace_id`) VALUES (@eh_locale_templates_id := @eh_locale_templates_id+1, 'sms.default', '76', 'zh_CN', '竣工验收工作流异常结束', '尊敬的${decoratorName}，关于${applyCompamy}的装修竣工验收未通过，装修办理流程已中止，您可前往APP查看详情。', '0');
INSERT INTO `eh_locale_templates` (`id`, `scope`, `code`, `locale`, `description`, `text`, `namespace_id`) VALUES (@eh_locale_templates_id := @eh_locale_templates_id+1, 'sms.default', '77', 'zh_CN', '押金退回信息生成', '尊敬的${name}，关于${applyCompamy}的装修押金退费信息已上传，您可前往APP查看详情。', '0');
INSERT INTO `eh_locale_templates` (`id`, `scope`, `code`, `locale`, `description`, `text`, `namespace_id`) VALUES (@eh_locale_templates_id := @eh_locale_templates_id+1, 'sms.default', '78', 'zh_CN', '押金退回成功', '尊敬的${name}，关于${applyCompamy}的装修押金已退回，装修办理完成，感谢您的使用。', '0');
INSERT INTO `eh_locale_templates` (`id`, `scope`, `code`, `locale`, `description`, `text`, `namespace_id`) VALUES (@eh_locale_templates_id := @eh_locale_templates_id+1, 'sms.default', '79', 'zh_CN', '装修公司负责人登记施工人员成功', '尊敬的“${workerName}，用户（${decoratorName}：${decoratorPhone}）已登记您为此次装修工程（${applyCompamy}）的施工人员，请前往APP查看详情，您可以点击以下链接下载APP，并使用本机号码进行注册：${url} 。', '0');
INSERT INTO `eh_locale_templates` (`id`, `scope`, `code`, `locale`, `description`, `text`, `namespace_id`) VALUES (@eh_locale_templates_id := @eh_locale_templates_id+1, 'sms.default', '80', 'zh_CN', '装修流程被管理员在后台手动中止', '尊敬的${name}，关于${applyCompamy}的装修流程已被管理公司（${operatorName}；${operatorPhone}）中止，您可前往APP查看详情。', '0');
