-- by zheng 初始化communityId
update `eh_lease_promotions`  right join `eh_lease_buildings` on `eh_lease_promotions`.building_id = `eh_lease_buildings`.id
set `eh_lease_promotions`.community_id = `eh_lease_buildings`.community_id
where `eh_lease_promotions`.building_id>0;

update `eh_service_modules` set module_control_type = 'community_control' where id = 40100;

update `eh_general_forms` set template_text = '[{"dataSourceType":"USER_NAME","dynamicFlag":1,"fieldDisplayName":"用户姓名","fieldExtra":"{\"limitWord\":10}","fieldName":"USER_NAME","fieldType":"SINGLE_LINE_TEXT","renderType":"DEFAULT","requiredFlag":1,"validatorType":"TEXT_LIMIT","visibleType":"EDITABLE"},{"dataSourceType":"USER_PHONE","dynamicFlag":1,"fieldDisplayName":"手机号码","fieldExtra":"{\"limitWord\":11}","fieldName":"USER_PHONE","fieldType":"INTEGER_TEXT","renderType":"DEFAULT","requiredFlag":1,"validatorType":"TEXT_LIMIT","visibleType":"EDITABLE"},{"dataSourceType":"LEASE_PROJECT_NAME","dynamicFlag":1,"fieldDisplayName":"项目名称","fieldExtra":"{\"limitWord\":20}","fieldName":"LEASE_PROJECT_NAME","fieldType":"SINGLE_LINE_TEXT","renderType":"DEFAULT","requiredFlag":1,"validatorType":"TEXT_LIMIT","visibleType":"EDITABLE"},{"dataSourceType":"LEASE_PROMOTION_BUILDING","dynamicFlag":1,"fieldDisplayName":"楼栋名称","fieldExtra":"{\"limitWord\":20}","fieldName":"LEASE_PROMOTION_BUILDING","fieldType":"SINGLE_LINE_TEXT","renderType":"DEFAULT","requiredFlag":1,"validatorType":"TEXT_LIMIT","visibleType":"EDITABLE"},{"dataSourceType":"LEASE_PROMOTION_APARTMENT","dynamicFlag":1,"fieldDisplayName":"门牌号码","fieldExtra":"{\"limitWord\":20}","fieldName":"LEASE_PROMOTION_APARTMENT","fieldType":"SINGLE_LINE_TEXT","renderType":"DEFAULT","requiredFlag":0,"validatorType":"TEXT_LIMIT","visibleType":"EDITABLE"},{"dataSourceType":"LEASE_PROMOTION_DESCRIPTION","dynamicFlag":0,"fieldDisplayName":"备注说明","fieldName":"LEASE_PROMOTION_DESCRIPTION","fieldType":"MULTI_LINE_TEXT","renderType":"DEFAULT","requiredFlag":0,"validatorType":"TEXT_LIMIT","visibleType":"EDITABLE"},{"dataSourceType":"CUSTOM_DATA","dynamicFlag":0,"fieldName":"CUSTOM_DATA","fieldType":"SINGLE_LINE_TEXT","renderType":"DEFAULT","requiredFlag":1,"visibleType":"HIDDEN"}]'
where owner_type = 'EhLeasePromotions';

update `eh_general_forms` set template_text = '[{"dataSourceType":"USER_NAME","dynamicFlag":1,"fieldDisplayName":"用户姓名","fieldExtra":"{\"limitWord\":10}","fieldName":"USER_NAME","fieldType":"SINGLE_LINE_TEXT","renderType":"DEFAULT","requiredFlag":1,"validatorType":"TEXT_LIMIT","visibleType":"EDITABLE"},{"dataSourceType":"USER_PHONE","dynamicFlag":1,"fieldDisplayName":"手机号码","fieldExtra":"{\"limitWord\":11}","fieldName":"USER_PHONE","fieldType":"INTEGER_TEXT","renderType":"DEFAULT","requiredFlag":1,"validatorType":"TEXT_LIMIT","visibleType":"EDITABLE"},{"dataSourceType":"LEASE_PROJECT_NAME","dynamicFlag":1,"fieldDisplayName":"项目名称","fieldExtra":"{\"limitWord\":20}","fieldName":"LEASE_PROJECT_NAME","fieldType":"SINGLE_LINE_TEXT","renderType":"DEFAULT","requiredFlag":1,"validatorType":"TEXT_LIMIT","visibleType":"EDITABLE"},{"dataSourceType":"LEASE_PROMOTION_BUILDING","dynamicFlag":1,"fieldDisplayName":"楼栋名称","fieldExtra":"{\"limitWord\":20}","fieldName":"LEASE_PROMOTION_BUILDING","fieldType":"SINGLE_LINE_TEXT","renderType":"DEFAULT","requiredFlag":1,"validatorType":"TEXT_LIMIT","visibleType":"EDITABLE"},{"dataSourceType":"LEASE_PROMOTION_DESCRIPTION","dynamicFlag":0,"fieldDisplayName":"备注说明","fieldName":"LEASE_PROMOTION_DESCRIPTION","fieldType":"MULTI_LINE_TEXT","renderType":"DEFAULT","requiredFlag":0,"validatorType":"TEXT_LIMIT","visibleType":"EDITABLE"},{"dataSourceType":"CUSTOM_DATA","dynamicFlag":0,"fieldName":"CUSTOM_DATA","fieldType":"SINGLE_LINE_TEXT","renderType":"DEFAULT","requiredFlag":1,"visibleType":"HIDDEN"}]'
where owner_type = 'EhBuildings';

update `eh_general_forms` set template_text = '[{"dataSourceType":"USER_NAME","dynamicFlag":1,"fieldDisplayName":"用户姓名","fieldExtra":"{\"limitWord\":10}","fieldName":"USER_NAME","fieldType":"SINGLE_LINE_TEXT","renderType":"DEFAULT","requiredFlag":1,"validatorType":"TEXT_LIMIT","visibleType":"EDITABLE"},{"dataSourceType":"USER_PHONE","dynamicFlag":1,"fieldDisplayName":"手机号码","fieldExtra":"{\"limitWord\":11}","fieldName":"USER_PHONE","fieldType":"INTEGER_TEXT","renderType":"DEFAULT","requiredFlag":1,"validatorType":"TEXT_LIMIT","visibleType":"EDITABLE"},{"dataSourceType":"LEASE_PROJECT_NAME","dynamicFlag":1,"fieldDisplayName":"项目名称","fieldExtra":"{\"limitWord\":20}","fieldName":"LEASE_PROJECT_NAME","fieldType":"SINGLE_LINE_TEXT","renderType":"DEFAULT","requiredFlag":1,"validatorType":"TEXT_LIMIT","visibleType":"EDITABLE"},{"dataSourceType":"LEASE_PROMOTION_DESCRIPTION","dynamicFlag":0,"fieldDisplayName":"备注说明","fieldName":"LEASE_PROMOTION_DESCRIPTION","fieldType":"MULTI_LINE_TEXT","renderType":"DEFAULT","requiredFlag":0,"validatorType":"TEXT_LIMIT","visibleType":"EDITABLE"},{"dataSourceType":"CUSTOM_DATA","dynamicFlag":0,"fieldName":"CUSTOM_DATA","fieldType":"SINGLE_LINE_TEXT","renderType":"DEFAULT","requiredFlag":1,"visibleType":"HIDDEN"}]'
where owner_type = 'EhLeaseProjects';