update `eh_communities` set `name` = '海岸大厦西座' where id = 240111044331050812;
update `eh_communities` set `alias_name` = '海岸大厦西座' where id = 240111044331050812;

delete from `eh_launch_pad_items` where namespace_id = 999993;
delete from `eh_banners` where namespace_id = 999993;

INSERT INTO `eh_launch_pad_layouts` (`id`, `namespace_id`, `name`, `layout_json`, `version_code`, `min_version_code`, `status`, `create_time`, `scene_type`) 
    VALUES ('210', '999993', 'jzLayout', '{\"versionCode\":\"2015111401\",\"versionName\":\"3.0.0\",\"displayName\":\"家政服务\",\"layoutName\":\"jzLayout\",\"groups\":[{\"groupName\":\"\",\"widget\":\"Navigator\",\"instanceConfig\":{\"itemGroup\":\"GaActions\"},\"style\":\"Default\",\"defaultOrder\":2,\"separatorFlag\":1,\"separatorHeight\":21,\"columnCount\":4},{\"groupName\":\"\",\"widget\":\"Posts\",\"instanceConfig\":{\"itemGroup\":\"GaPosts\"},\"style\":\"Default\",\"defaultOrder\":3,\"separatorFlag\":0,\"separatorHeight\":0},{\"groupName\":\"CallPhone\",\"widget\":\"CallPhones\",\"instanceConfig\":{\"itemGroup\":\"CallPhones\",\"position\":\"bottom\"},\"style\":\"Default\",\"defaultOrder\":3,\"separatorFlag\":0,\"separatorHeight\":0}]}', '2015111401', '2015061701', '2', '2015-06-27 14:04:57', 'park_tourist');
INSERT INTO `eh_launch_pad_layouts` (`id`, `namespace_id`, `name`, `layout_json`, `version_code`, `min_version_code`, `status`, `create_time`, `scene_type`) 
    VALUES ('211', '999993', 'jzLayout', '{\"versionCode\":\"2015111401\",\"versionName\":\"3.0.0\",\"displayName\":\"家政服务\",\"layoutName\":\"jzLayout\",\"groups\":[{\"groupName\":\"\",\"widget\":\"Navigator\",\"instanceConfig\":{\"itemGroup\":\"GaActions\"},\"style\":\"Default\",\"defaultOrder\":2,\"separatorFlag\":1,\"separatorHeight\":21,\"columnCount\":4},{\"groupName\":\"\",\"widget\":\"Posts\",\"instanceConfig\":{\"itemGroup\":\"GaPosts\"},\"style\":\"Default\",\"defaultOrder\":3,\"separatorFlag\":0,\"separatorHeight\":0},{\"groupName\":\"CallPhone\",\"widget\":\"CallPhones\",\"instanceConfig\":{\"itemGroup\":\"CallPhones\",\"position\":\"bottom\"},\"style\":\"Default\",\"defaultOrder\":3,\"separatorFlag\":0,\"separatorHeight\":0}]}', '2015111401', '2015061701', '2', '2015-06-27 14:04:57', 'pm_admin');
INSERT INTO `eh_launch_pad_layouts` (`id`, `namespace_id`, `name`, `layout_json`, `version_code`, `min_version_code`, `status`, `create_time`, `scene_type`) 
    VALUES ('212', '999993', 'wxLayout', '{\"versionCode\":\"2015111401\",\"versionName\":\"3.0.0\",\"displayName\":\"综合维修\",\"layoutName\":\"wxLayout\",\"groups\":[{\"groupName\":\"\",\"widget\":\"Navigator\",\"instanceConfig\":{\"itemGroup\":\"GaActions\"},\"style\":\"Default\",\"defaultOrder\":2,\"separatorFlag\":1,\"separatorHeight\":21,\"columnCount\":4},{\"groupName\":\"\",\"widget\":\"Posts\",\"instanceConfig\":{\"itemGroup\":\"GaPosts\"},\"style\":\"Default\",\"defaultOrder\":3,\"separatorFlag\":0,\"separatorHeight\":0},{\"groupName\":\"CallPhone\",\"widget\":\"CallPhones\",\"instanceConfig\":{\"itemGroup\":\"CallPhones\",\"position\":\"bottom\"},\"style\":\"Default\",\"defaultOrder\":3,\"separatorFlag\":0,\"separatorHeight\":0}]}', '2015111401', '2015061701', '2', '2015-06-27 14:04:57', 'park_tourist');
INSERT INTO `eh_launch_pad_layouts` (`id`, `namespace_id`, `name`, `layout_json`, `version_code`, `min_version_code`, `status`, `create_time`, `scene_type`) 
    VALUES ('213', '999993', 'wxLayout', '{\"versionCode\":\"2015111401\",\"versionName\":\"3.0.0\",\"displayName\":\"综合维修\",\"layoutName\":\"wxLayout\",\"groups\":[{\"groupName\":\"\",\"widget\":\"Navigator\",\"instanceConfig\":{\"itemGroup\":\"GaActions\"},\"style\":\"Default\",\"defaultOrder\":2,\"separatorFlag\":1,\"separatorHeight\":21,\"columnCount\":4},{\"groupName\":\"\",\"widget\":\"Posts\",\"instanceConfig\":{\"itemGroup\":\"GaPosts\"},\"style\":\"Default\",\"defaultOrder\":3,\"separatorFlag\":0,\"separatorHeight\":0},{\"groupName\":\"CallPhone\",\"widget\":\"CallPhones\",\"instanceConfig\":{\"itemGroup\":\"CallPhones\",\"position\":\"bottom\"},\"style\":\"Default\",\"defaultOrder\":3,\"separatorFlag\":0,\"separatorHeight\":0}]}', '2015111401', '2015061701', '2', '2015-06-27 14:04:57', 'pm_admin');

INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('1760', '999993', '0', '0', '0', '/home', 'GovAgencies', 'NOTICE', '物业通知', 'cs://1/image/aW1hZ2UvTVRvMFpEazRNREkzTmpnMk5UVmhPR1F6TXpjMFptUTNOalJqWm1ObVpHUTBZUQ', '1', '1', '15', '{\"contentCategory\":1003,\"actionCategory\":0,\"forumId\":179511,\"embedAppId\":27} ', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'park_tourist');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('1761', '999993', '0', '0', '0', '/home', 'GovAgencies', 'NOTICE', '物业通知', 'cs://1/image/aW1hZ2UvTVRvMFpEazRNREkzTmpnMk5UVmhPR1F6TXpjMFptUTNOalJqWm1ObVpHUTBZUQ', '1', '1', '15', '{\"contentCategory\":1003,\"actionCategory\":0,\"forumId\":179511,\"embedAppId\":27} ', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'pm_admin');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('1762', '999993', '0', '0', '0', '/home', 'GovAgencies', 'PUNCH', '停车缴费', 'cs://1/image/aW1hZ2UvTVRvNE9EaG1ZVEl6WW1JNVptSTBZV013T0Rkak5qUm1ZVEkxTVRJNVlXTmxNdw', '1', '1', '14', '{\"url\":\"https://zuolin.com/mobile/static/coming_soon/index.html"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'park_tourist');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('1763', '999993', '0', '0', '0', '/home', 'GovAgencies', 'PUNCH', '停车缴费', 'cs://1/image/aW1hZ2UvTVRvNE9EaG1ZVEl6WW1JNVptSTBZV013T0Rkak5qUm1ZVEkxTVRJNVlXTmxNdw', '1', '1', '14', '{\"url\":\"https://zuolin.com/mobile/static/coming_soon/index.html"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'pm_admin');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('1764', '999993', '0', '0', '0', '/home', 'GovAgencies', 'PAY', '物业缴费', 'cs://1/image/aW1hZ2UvTVRwaE5EQmtaakEyTldJeE9UVXpNelZpWXpZMlpXRmpaVEl5T0dFNE9XRTNNUQ', '1', '1', '14', '{\"url\":\"https://core.zuolin.com/property_fee/index.html?hideNavigationBar=1#/bill_query?sign_suffix"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'park_tourist');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('1765', '999993', '0', '0', '0', '/home', 'GovAgencies', 'PAY', '物业缴费', 'cs://1/image/aW1hZ2UvTVRwaE5EQmtaakEyTldJeE9UVXpNelZpWXpZMlpXRmpaVEl5T0dFNE9XRTNNUQ', '1', '1', '14', '{\"url\":\"https://core.zuolin.com/property_fee/index.html?hideNavigationBar=1#/bill_query?sign_suffix"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'pm_admin');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('1766', '999993', '0', '0', '0', '/home', 'GovAgencies', 'SERVICE_HOT_LINE', '便民服务', 'cs://1/image/aW1hZ2UvTVRwaU1ESXlNVFExWmpBM05UTXlNamRsTkRka05HWXdPVFF3T1RWa016a3pPUQ', '1', '1', '45', '', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'park_tourist');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('1767', '999993', '0', '0', '0', '/home', 'GovAgencies', 'SERVICE_HOT_LINE', '便民服务', 'cs://1/image/aW1hZ2UvTVRwaU1ESXlNVFExWmpBM05UTXlNamRsTkRka05HWXdPVFF3T1RWa016a3pPUQ', '1', '1', '45', '', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'pm_admin');

INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('1768', '999993', '0', '0', '0', '/home', 'Bizs', 'MEETINGROOM', '会议室预定', 'cs://1/image/aW1hZ2UvTVRwall6bGpZbU0xWmpBd05ESTNaakE0WWpjM1pqRmpZVGxqWkRJeU1USmxZZw', '1', '1', '24', '', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'park_tourist');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('1769', '999993', '0', '0', '0', '/home', 'Bizs', 'MEETINGROOM', '会议室预定', 'cs://1/image/aW1hZ2UvTVRwall6bGpZbU0xWmpBd05ESTNaakE0WWpjM1pqRmpZVGxqWkRJeU1USmxZZw', '1', '1', '24', '', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'pm_admin');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('1770', '999993', '0', '0', '0', '/home', 'Bizs', '饮用水服务', '饮用水服务', 'cs://1/image/aW1hZ2UvTVRwbE1XWTFNMlUzTnpFNE1UY3pOVFJtT0RaaFpHUXhNMlExTjJJM016QmhZZw', '1', '1', '14', NULL, '0', '0', '1', '1', NULL, '0', NULL, 'biz', '117', '1', 'park_tourist');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('1771', '999993', '0', '0', '0', '/home', 'Bizs', '饮用水服务', '饮用水服务', 'cs://1/image/aW1hZ2UvTVRwbE1XWTFNMlUzTnpFNE1UY3pOVFJtT0RaaFpHUXhNMlExTjJJM016QmhZZw', '1', '1', '14', NULL, '0', '0', '1', '1', NULL, '0', NULL, 'biz', '117', '1', 'pm_admin');

INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('1773', '999993', '0', '0', '0', '/home', 'Bizs', 'ELECSCREEN', '广告租赁', 'cs://1/image/aW1hZ2UvTVRwa1lqWXpOemxtWW1Zd05tSTBNRFptTXpoa01EQTRNVEU0TXpjMU56TTBaQQ', '1', '1', '26', '', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'park_tourist');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('1774', '999993', '0', '0', '0', '/home', 'Bizs', 'ELECSCREEN', '广告租赁', 'cs://1/image/aW1hZ2UvTVRwa1lqWXpOemxtWW1Zd05tSTBNRFptTXpoa01EQTRNVEU0TXpjMU56TTBaQQ', '1', '1', '26', '', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'pm_admin');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('1785', '999993', '0', '0', '0', '/home', 'Bizs', '租售中心', '租售中心', 'cs://1/image/aW1hZ2UvTVRvMk1ETTBZV0kwTVdKak5XTTBaREZtTURCa05HTTNZakV5TTJWbU9XVXhZdw', '1', '1', '28', '', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'park_tourist');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('1905', '999993', '0', '0', '0', '/home', 'Bizs', '租售中心', '租售中心', 'cs://1/image/aW1hZ2UvTVRvMk1ETTBZV0kwTVdKak5XTTBaREZtTURCa05HTTNZakV5TTJWbU9XVXhZdw', '1', '1', '28', '', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'pm_admin');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('10370', '999993', '0', '0', '0', '/home', 'Bizs', 'PM', '家政服务', 'cs://1/image/aW1hZ2UvTVRvMk1Ua3dZV1V5WkdJeFlXUTNOakV3TlRZek9UUTBOREF5WlRVMVlUZzVOdw', '1', '1', '2', '{\"itemLocation\":\"/home/housekeeping\",\"layoutName\":\"jzLayout\",\"title\":\"家政服务\",\"entityTag\":\"PM\"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'park_tourist');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('10700', '999993', '0', '0', '0', '/home/housekeeping', 'GaActions', '家政服务', '家政服务', 'cs://1/image/aW1hZ2UvTVRvMk1Ua3dZV1V5WkdJeFlXUTNOakV3TlRZek9UUTBOREF5WlRVMVlUZzVOdw', '1', '1', '19', '{\"contentCategory\":102022,\"actionCategory\":0,\"forumId\":179511,\"targetEntityTag\":\"PM\",\"embedAppId\":27} ', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'park_tourist');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('10701', '999993', '0', '0', '0', '/home/housekeeping', 'GaPosts', '家政服务', '家政服务', 'cs://1/image/aW1hZ2UvTVRvMk1Ua3dZV1V5WkdJeFlXUTNOakV3TlRZek9UUTBOREF5WlRVMVlUZzVOdw', '1', '1', '19', '{\"contentCategory\":102022,\"actionCategory\":0,\"forumId\":179511,\"targetEntityTag\":\"PM\",\"embedAppId\":27} ', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'park_tourist');

--INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
--VALUES ('1768', '999993', '0', '0', '0', '/home/Pm', 'GaPosts', '家政', '家政', NULL, '1', '1', '15', '{\"contentCategory\":102022,\"actionCategory\":0,\"forumId\":179511,\"embedAppId\":27,\"entityTag\":\"PM\"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'park_tourist');

INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('10371', '999993', '0', '0', '0', '/home', 'Bizs', 'PM', '家政服务', 'cs://1/image/aW1hZ2UvTVRvMk1Ua3dZV1V5WkdJeFlXUTNOakV3TlRZek9UUTBOREF5WlRVMVlUZzVOdw', '1', '1', '2', '{\"itemLocation\":\"/home/housekeeping\",\"layoutName\":\"jzLayout\",\"title\":\"家政服务\",\"entityTag\":\"PM\"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'pm_admin');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('10702', '999993', '0', '0', '0', '/home/housekeeping', 'GaActions', '家政服务', '家政服务', 'cs://1/image/aW1hZ2UvTVRvMk1Ua3dZV1V5WkdJeFlXUTNOakV3TlRZek9UUTBOREF5WlRVMVlUZzVOdw', '1', '1', '19', '{\"contentCategory\":102022,\"actionCategory\":0,\"forumId\":179511,\"targetEntityTag\":\"PM\",\"embedAppId\":27} ', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'pm_admin');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('10703', '999993', '0', '0', '0', '/home/housekeeping', 'GaPosts', '家政服务', '家政服务', 'cs://1/image/aW1hZ2UvTVRvMk1Ua3dZV1V5WkdJeFlXUTNOakV3TlRZek9UUTBOREF5WlRVMVlUZzVOdw', '1', '1', '19', '{\"contentCategory\":102022,\"actionCategory\":0,\"forumId\":179511,\"targetEntityTag\":\"PM\",\"embedAppId\":27} ', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'pm_admin');

--INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
--VALUES ('10378', '999993', '0', '0', '0', '/home/Pm', 'GaPosts', '家政', '家政', NULL, '1', '1', '15', '{\"contentCategory\":102022,\"actionCategory\":0,\"forumId\":179511,\"embedAppId\":27,\"entityTag\":\"PM\"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'pm_admin');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('10704', '999993', '0', '0', '0', '/home', 'Bizs', 'PM', '综合维修', 'cs://1/image/aW1hZ2UvTVRvMU1URmlNV1poWVRFeFpEWTROVFE1TWpFNVl6Y3dNakZpTjJZNFlqVmpNdw', '1', '1', '2', '{\"itemLocation\":\"/home/maintenance\",\"layoutName\":\"wxLayout\",\"title\":\"综合维修\",\"entityTag\":\"PM\"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'park_tourist');

INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('10372', '999993', '0', '0', '0', '/home/maintenance', 'GaActions', '综合维修', '综合维修', 'cs://1/image/aW1hZ2UvTVRvMU1URmlNV1poWVRFeFpEWTROVFE1TWpFNVl6Y3dNakZpTjJZNFlqVmpNdw', '1', '1', '19', '{\"contentCategory\":102023,\"actionCategory\":0,\"forumId\":179511,\"targetEntityTag\":\"PM\",\"embedAppId\":27}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'park_tourist');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('10705', '999993', '0', '0', '0', '/home/maintenance', 'GaPosts', '综合维修', '综合维修', 'cs://1/image/aW1hZ2UvTVRvMU1URmlNV1poWVRFeFpEWTROVFE1TWpFNVl6Y3dNakZpTjJZNFlqVmpNdw', '1', '1', '19', '{\"contentCategory\":102023,\"actionCategory\":0,\"forumId\":179511,\"targetEntityTag\":\"PM\",\"embedAppId\":27}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'park_tourist');
--INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
--VALUES ('1769', '999993', '0', '0', '0', '/home/Pm', 'GaPosts', '综合维修', '综合维修', NULL, '1', '1', '15', '{\"contentCategory\":102023,\"actionCategory\":0,\"forumId\":179511,\"embedAppId\":27,\"entityTag\":\"PM\"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'park_tourist');

INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('10706', '999993', '0', '0', '0', '/home', 'Bizs', 'PM', '综合维修', 'cs://1/image/aW1hZ2UvTVRvMU1URmlNV1poWVRFeFpEWTROVFE1TWpFNVl6Y3dNakZpTjJZNFlqVmpNdw', '1', '1', '2', '{\"itemLocation\":\"/home/maintenance\",\"layoutName\":\"wxLayout\",\"title\":\"综合维修\",\"entityTag\":\"PM\"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'pm_admin');

INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('10373', '999993', '0', '0', '0', '/home/maintenance', 'GaActions', '综合维修', '综合维修', 'cs://1/image/aW1hZ2UvTVRvMU1URmlNV1poWVRFeFpEWTROVFE1TWpFNVl6Y3dNakZpTjJZNFlqVmpNdw', '1', '1', '19', '{\"contentCategory\":102023,\"actionCategory\":0,\"forumId\":179511,\"targetEntityTag\":\"PM\",\"embedAppId\":27}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'pm_admin');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('10707', '999993', '0', '0', '0', '/home/maintenance', 'GaPosts', '综合维修', '综合维修', 'cs://1/image/aW1hZ2UvTVRvMU1URmlNV1poWVRFeFpEWTROVFE1TWpFNVl6Y3dNakZpTjJZNFlqVmpNdw', '1', '1', '19', '{\"contentCategory\":102023,\"actionCategory\":0,\"forumId\":179511,\"targetEntityTag\":\"PM\",\"embedAppId\":27}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '0', 'pm_admin');
--INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
--VALUES ('10379', '999993', '0', '0', '0', '/home/Pm', 'GaPosts', '综合维修', '综合维修', NULL, '1', '1', '15', '{\"contentCategory\":102023,\"actionCategory\":0,\"forumId\":179511,\"embedAppId\":27,\"entityTag\":\"PM\"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'pm_admin');


INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('10374', '999993', '0', '0', '0', '/home', 'Bizs', 'VIDEO_MEETING', '视频会议', 'cs://1/image/aW1hZ2UvTVRvMk1tTXlPR1ZqTURSaU56a3dOemRpWkRneFpUVmhNMlU1WkdGak5ETTVaQQ', '1', '1', '27', '', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'park_tourist');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('10375', '999993', '0', '0', '0', '/home', 'Bizs', 'VIDEO_MEETING', '视频会议', 'cs://1/image/aW1hZ2UvTVRvMk1tTXlPR1ZqTURSaU56a3dOemRpWkRneFpUVmhNMlU1WkdGak5ETTVaQQ', '1', '1', '27', '', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'pm_admin');

INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('10376', '999993', '0', '0', '0', '/home', 'Bizs', 'CONTACTS', '通讯录', 'cs://1/image/aW1hZ2UvTVRvMFpEUTNNbVF5WW1abU5XVXhNak16WTJOa1pHVTVZekl4TmpGalpERmlOdw', '1', '1', '46', '', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'park_tourist');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('10377', '999993', '0', '0', '0', '/home', 'Bizs', 'CONTACTS', '通讯录', 'cs://1/image/aW1hZ2UvTVRvMFpEUTNNbVF5WW1abU5XVXhNak16WTJOa1pHVTVZekl4TmpGalpERmlOdw', '1', '1', '46', '', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'pm_admin');



--INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
--VALUES ('1760', '999993', '0', '0', '0', '/home', 'GovAgencies', 'PM', '物业服务', 'cs://1/image/aW1hZ2UvTVRwaE5qWmlZMkV3TW1Gall6aGxOVFJrWkRjNU1qQXlPV1kwTnpVek5XSXpZZw', '1', '1', '2', '{\"itemLocation\":\"/home/Pm\",\"layoutName\":\"PmLayout\",\"title\":\"物业服务\",\"entityTag\":\"PM\"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'park_tourist');
--INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
--VALUES ('10370', '999993', '0', '0', '0', '/home', 'GovAgencies', 'PM', '物业服务', 'cs://1/image/aW1hZ2UvTVRwaE5qWmlZMkV3TW1Gall6aGxOVFJrWkRjNU1qQXlPV1kwTnpVek5XSXpZZw', '1', '1', '2', '{\"itemLocation\":\"/home/Pm\",\"layoutName\":\"PmLayout\",\"title\":\"物业服务\",\"entityTag\":\"PM\"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'pm_admin');


INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('10380', '999993', '0', '0', '0', '/home', 'Coupons', '优惠券', '优惠券', 'cs://1/image/aW1hZ2UvTVRwaE1UWXhPVEUwTkRrek1UQXdZalUyWXpOalltVTNNekJsTWpBeE9Ua3lNQQ', '3', '1', '14', '{\"url\":\"https://biz.zuolin.com/zl-ec/rest/service/front/logon?hideNavigationBar=1&sourceUrl=https://biz.zuolin.com%2Fweb%2Fapp%2Fuser%2Findex.html%23%2Fpromotion%2Fall%3F_k%3Dzlbiz#sign_suffix"}', '1', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'park_tourist');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('10381', '999993', '0', '0', '0', '/home', 'Coupons', '优惠券', '优惠券', 'cs://1/image/aW1hZ2UvTVRwaE1UWXhPVEUwTkRrek1UQXdZalUyWXpOalltVTNNekJsTWpBeE9Ua3lNQQ', '3', '1', '14', '{\"url\":\"https://biz.zuolin.com/zl-ec/rest/service/front/logon?hideNavigationBar=1&sourceUrl=https://biz.zuolin.com%2Fweb%2Fapp%2Fuser%2Findex.html%23%2Fpromotion%2Fall%3F_k%3Dzlbiz#sign_suffix"}', '1', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'pm_admin');

--INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
--VALUES ('1764', '999993', '0', '0', '0', '/home/Pm', 'GaActions', '保洁', '保洁', 'cs://1/image/aW1hZ2UvTVRwa09EVXlPR0prTUdNeVlqSXpZbUV6WkRnMVlqZ3dObVV5WVRZek56VmpZZw', '1', '1', '19', '{\"contentCategory\":102021,\"actionCategory\":0,\"forumId\":179511,\"targetEntityTag\":\"PM\",\"embedAppId\":27} ', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'park_tourist');
--INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
--VALUES ('1767', '999993', '0', '0', '0', '/home/Pm', 'GaPosts', '保洁', '保洁', NULL, '1', '1', '15', '{\"contentCategory\":102021,\"actionCategory\":0,\"forumId\":179511,\"embedAppId\":27,\"entityTag\":\"PM\"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'park_tourist');

--INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
--VALUES ('10374', '999993', '0', '0', '0', '/home/Pm', 'GaActions', '保洁', '保洁', 'cs://1/image/aW1hZ2UvTVRwa09EVXlPR0prTUdNeVlqSXpZbUV6WkRnMVlqZ3dObVV5WVRZek56VmpZZw', '1', '1', '19', '{\"contentCategory\":102021,\"actionCategory\":0,\"forumId\":179511,\"targetEntityTag\":\"PM\",\"embedAppId\":27} ', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'pm_admin');
--INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
--VALUES ('10377', '999993', '0', '0', '0', '/home/Pm', 'GaPosts', '保洁', '保洁', NULL, '1', '1', '15', '{\"contentCategory\":102021,\"actionCategory\":0,\"forumId\":179511,\"embedAppId\":27,\"entityTag\":\"PM\"}', '0', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'pm_admin');


INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('10382', '999993', '0', '0', '0', '/home', 'Coupons', '左邻小站', '左邻小站', 'cs://1/image/aW1hZ2UvTVRwak5qRmpPVGd3WkdVeE5EZGlOalV4TXpKa05EaG1NVE00T1dJNU9HTTJPQQ', '5', '1', '14', '{\"url\":\"http://m.ubive.com/index.php"}', '2', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'park_tourist');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('10383', '999993', '0', '0', '0', '/home', 'Coupons', '左邻小站', '左邻小站', 'cs://1/image/aW1hZ2UvTVRwak5qRmpPVGd3WkdVeE5EZGlOalV4TXpKa05EaG1NVE00T1dJNU9HTTJPQQ', '5', '1', '14', '{\"url\":\"http://m.ubive.com/index.php"}', '2', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'pm_admin');

INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('10394', '999993', '0', '0', '0', '/home', 'Bizs', '更多', '更多', 'cs://1/image/aW1hZ2UvTVRvNE1XRTNZVEUxT0RGaE1EQmpZakF6TmprNE1EZ3paR1k0TVRVMFptUTJZdw', '1', '1', '1', '{\"itemLocation\":\"/home\", \"itemGroup\":\"Bizs\"}', '30', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'park_tourist');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, `delete_flag`, `scene_type`) 
VALUES ('10395', '999993', '0', '0', '0', '/home', 'Bizs', '更多', '更多', 'cs://1/image/aW1hZ2UvTVRvNE1XRTNZVEUxT0RGaE1EQmpZakF6TmprNE1EZ3paR1k0TVRVMFptUTJZdw', '1', '1', '1', '{\"itemLocation\":\"/home\", \"itemGroup\":\"Bizs\"}', '30', '0', '1', '1', '', '0', NULL, NULL, NULL, '1', 'pm_admin');





INSERT INTO `eh_banners` (`id`, `namespace_id`, `appId`, `banner_location`, `banner_group`, `scope_code`, `scope_id`, `name`, `vendor_tag`, `poster_path`, `action_type`, `action_data`, `start_time`, `end_time`, `status`, `order`, `creator_uid`, `create_time`, `delete_time`, `scene_type`) 
VALUES ('52', '999993', '0', '/home', 'Default', '0', '0', 'haiancheng', 'haiancheng', 'cs://1/image/aW1hZ2UvTVRveE1XUmhObVExT1RKa01qVXpaRE5rWmpSak9XTTVaV1UwWlRKbU1qZzVNQQ', '13', '{\"url\":\"http://m.szhaian.com\"}', NULL, NULL, '2', '10', '0', '2015-06-30 16:01:45', NULL, 'park_tourist');
INSERT INTO `eh_banners` (`id`, `namespace_id`, `appId`, `banner_location`, `banner_group`, `scope_code`, `scope_id`, `name`, `vendor_tag`, `poster_path`, `action_type`, `action_data`, `start_time`, `end_time`, `status`, `order`, `creator_uid`, `create_time`, `delete_time`, `scene_type`) 
VALUES ('82', '999993', '0', '/home', 'Default', '0', '0', 'haiancheng', 'haiancheng', 'cs://1/image/aW1hZ2UvTVRvMFl6UTRNbVZpTnpobE4yUmxOemcyWmpsaE56WmpOemMyWlRrME1EQTVNdw', '13', '{\"url\":\"http://a.eqxiu.com/s/dMtqkDDH"}', NULL, NULL, '2', '10', '0', '2015-06-30 16:01:45', NULL, 'park_tourist');
INSERT INTO `eh_banners` (`id`, `namespace_id`, `appId`, `banner_location`, `banner_group`, `scope_code`, `scope_id`, `name`, `vendor_tag`, `poster_path`, `action_type`, `action_data`, `start_time`, `end_time`, `status`, `order`, `creator_uid`, `create_time`, `delete_time`, `scene_type`) 
VALUES ('83', '999993', '0', '/home', 'Default', '0', '0', 'haiancheng', 'haiancheng', 'cs://1/image/aW1hZ2UvTVRwa05XSmxabUl5T0daa01qa3hZemsyT1RVNU5EZGxZakE0WkRKbU1EbGlaZw', '13', '{\"url\":\"http://x.eqxiu.com/s/iDJ3lh63"}', NULL, NULL, '2', '10', '0', '2015-06-30 16:01:45', NULL, 'park_tourist');
INSERT INTO `eh_banners` (`id`, `namespace_id`, `appId`, `banner_location`, `banner_group`, `scope_code`, `scope_id`, `name`, `vendor_tag`, `poster_path`, `action_type`, `action_data`, `start_time`, `end_time`, `status`, `order`, `creator_uid`, `create_time`, `delete_time`, `scene_type`) 
VALUES ('84', '999993', '0', '/home', 'Default', '0', '0', 'haiancheng', 'haiancheng', 'cs://1/image/aW1hZ2UvTVRvMllqbG1OVE01WVdSbE16YzRaR1k0TmpFMlptVTVPV1F6TnpVd09EQTBPUQ', '13', '{\"url\":\"http://q.eqxiu.com/s/64Zt0Q9X"}', NULL, NULL, '2', '10', '0', '2015-06-30 16:01:45', NULL, 'park_tourist');
INSERT INTO `eh_banners` (`id`, `namespace_id`, `appId`, `banner_location`, `banner_group`, `scope_code`, `scope_id`, `name`, `vendor_tag`, `poster_path`, `action_type`, `action_data`, `start_time`, `end_time`, `status`, `order`, `creator_uid`, `create_time`, `delete_time`, `scene_type`) 
VALUES ('85', '999993', '0', '/home', 'Default', '0', '0', 'haiancheng', 'haiancheng', 'cs://1/image/aW1hZ2UvTVRveE1XUmhObVExT1RKa01qVXpaRE5rWmpSak9XTTVaV1UwWlRKbU1qZzVNQQ', '13', '{\"url\":\"http://m.szhaian.com\"}', NULL, NULL, '2', '10', '0', '2015-06-30 16:01:45', NULL, 'pm_admin');
INSERT INTO `eh_banners` (`id`, `namespace_id`, `appId`, `banner_location`, `banner_group`, `scope_code`, `scope_id`, `name`, `vendor_tag`, `poster_path`, `action_type`, `action_data`, `start_time`, `end_time`, `status`, `order`, `creator_uid`, `create_time`, `delete_time`, `scene_type`) 
VALUES ('86', '999993', '0', '/home', 'Default', '0', '0', 'haiancheng', 'haiancheng', 'cs://1/image/aW1hZ2UvTVRvMFl6UTRNbVZpTnpobE4yUmxOemcyWmpsaE56WmpOemMyWlRrME1EQTVNdw', '13', '{\"url\":\"http://a.eqxiu.com/s/dMtqkDDH"}', NULL, NULL, '2', '10', '0', '2015-06-30 16:01:45', NULL, 'pm_admin');
INSERT INTO `eh_banners` (`id`, `namespace_id`, `appId`, `banner_location`, `banner_group`, `scope_code`, `scope_id`, `name`, `vendor_tag`, `poster_path`, `action_type`, `action_data`, `start_time`, `end_time`, `status`, `order`, `creator_uid`, `create_time`, `delete_time`, `scene_type`) 
VALUES ('87', '999993', '0', '/home', 'Default', '0', '0', 'haiancheng', 'haiancheng', 'cs://1/image/aW1hZ2UvTVRwa05XSmxabUl5T0daa01qa3hZemsyT1RVNU5EZGxZakE0WkRKbU1EbGlaZw', '13', '{\"url\":\"http://x.eqxiu.com/s/iDJ3lh63"}', NULL, NULL, '2', '10', '0', '2015-06-30 16:01:45', NULL, 'pm_admin');
INSERT INTO `eh_banners` (`id`, `namespace_id`, `appId`, `banner_location`, `banner_group`, `scope_code`, `scope_id`, `name`, `vendor_tag`, `poster_path`, `action_type`, `action_data`, `start_time`, `end_time`, `status`, `order`, `creator_uid`, `create_time`, `delete_time`, `scene_type`) 
VALUES ('1012', '999993', '0', '/home', 'Default', '0', '0', 'haiancheng', 'haiancheng', 'cs://1/image/aW1hZ2UvTVRvMllqbG1OVE01WVdSbE16YzRaR1k0TmpFMlptVTVPV1F6TnpVd09EQTBPUQ', '13', '{\"url\":\"http://q.eqxiu.com/s/64Zt0Q9X"}', NULL, NULL, '2', '10', '0', '2015-06-30 16:01:45', NULL, 'pm_admin');



INSERT INTO `eh_web_menu_scopes`(`id`, `menu_id`,`menu_name`, `owner_type`, `owner_id`, `apply_policy`) VALUES( 31, 47000,'', 'EhNamespaces', 999993 , 0);
INSERT INTO `eh_web_menu_scopes`(`id`, `menu_id`,`menu_name`, `owner_type`, `owner_id`, `apply_policy`) VALUES( 32, 48000,'', 'EhNamespaces', 999993 , 0);
INSERT INTO `eh_web_menu_scopes`(`id`, `menu_id`,`menu_name`, `owner_type`, `owner_id`, `apply_policy`) VALUES( 33, 46100,'', 'EhNamespaces', 999993 , 0);
INSERT INTO `eh_web_menu_scopes`(`id`, `menu_id`,`menu_name`, `owner_type`, `owner_id`, `apply_policy`) VALUES( 34, 47150,'', 'EhNamespaces', 999993 , 0);
INSERT INTO `eh_web_menu_scopes`(`id`, `menu_id`,`menu_name`, `owner_type`, `owner_id`, `apply_policy`) VALUES( 35, 47100,'', 'EhNamespaces', 999993 , 0);
INSERT INTO `eh_web_menu_scopes`(`id`, `menu_id`,`menu_name`, `owner_type`, `owner_id`, `apply_policy`) VALUES( 36, 47160,'', 'EhNamespaces', 999993 , 0);
INSERT INTO `eh_web_menu_scopes`(`id`, `menu_id`,`menu_name`, `owner_type`, `owner_id`, `apply_policy`) VALUES( 37, 47200,'', 'EhNamespaces', 999993 , 0);
INSERT INTO `eh_web_menu_scopes`(`id`, `menu_id`,`menu_name`, `owner_type`, `owner_id`, `apply_policy`) VALUES( 38, 47300,'', 'EhNamespaces', 999993 , 0);

INSERT INTO `eh_web_menu_scopes`(`id`, `menu_id`,`menu_name`, `owner_type`, `owner_id`, `apply_policy`) VALUES( 39, 48100,'', 'EhNamespaces', 999993 , 0);
INSERT INTO `eh_web_menu_scopes`(`id`, `menu_id`,`menu_name`, `owner_type`, `owner_id`, `apply_policy`) VALUES( 40, 48200,'', 'EhNamespaces', 999993 , 0);
INSERT INTO `eh_web_menu_scopes`(`id`, `menu_id`,`menu_name`, `owner_type`, `owner_id`, `apply_policy`) VALUES( 41, 48300,'', 'EhNamespaces', 999993 , 0);


