-- 合同报表数据表
CREATE TABLE `eh_contract_reportform_statistic_community` (
	`id` BIGINT (20) NOT NULL,
	`namespace_id` INT (11) DEFAULT NULL,
	`community_id` BIGINT (20) DEFAULT NULL,
	`community_name` VARCHAR (64) DEFAULT NULL,
	`month_str` VARCHAR (10) DEFAULT NULL COMMENT '统计月份（格式为xxxx-xx）',
	`year_str` VARCHAR (10) DEFAULT NULL COMMENT '统计年份（格式为xxxx）',
	`community_count` INT (11) DEFAULT '0' COMMENT '园区总数',
	`customer_count` INT (11) DEFAULT '0' COMMENT '新签客户总数',
	`newcontract_count` INT (11) DEFAULT '0' COMMENT '新签合同总数',
	`denunciationcontract_count` INT (11) DEFAULT '0' COMMENT '退约合同总数',
	`changecontract_count` INT (11) DEFAULT '0' COMMENT '变更合同总数',
	`renewcontract_count` INT (11) DEFAULT '0' COMMENT '续约合同总数',
	`signedupcontract_count` INT (11) DEFAULT '0' COMMENT '待签约合同总数',
	`waitingroomcontract_count` INT (11) DEFAULT '0' COMMENT '待接房合同总数',
	`newcontract_amount` DECIMAL (10, 2) DEFAULT '0.00' COMMENT '新签合同总额',
	`denunciationcontract_amount` DECIMAL (10, 2) DEFAULT '0.00' COMMENT '退约合同总额',
	`changecontract_amount` DECIMAL (10, 2) DEFAULT '0.00' COMMENT '变更合同总额',
	`renewcontract_amount` DECIMAL (10, 2) DEFAULT '0.00' COMMENT '续约合同总额',
	`deposit_amount` DECIMAL (10, 2) DEFAULT '0.00' COMMENT '新增押金总额',
	`rent_amount` DECIMAL (10, 2) DEFAULT '0.00' COMMENT '合同租金总额',
	`propertyfee_amount` DECIMAL (10, 2) DEFAULT '0.00' COMMENT '合同物业费总额',
	`newcontractarea_size` DECIMAL (10, 2) DEFAULT '0.00' COMMENT '新签合同总面积',
	`organizationcontract_count` INT (11) DEFAULT '0' COMMENT '企业合同总数',
	`organizationcontract_amount` DECIMAL (10, 2) DEFAULT '0.00' COMMENT '企业合同总额',
	`individualcontract_count` INT (11) DEFAULT '0' COMMENT '个人合同总数',
	`individualcontract_amount` DECIMAL (10, 2) DEFAULT '0.00' COMMENT '个人合同总额',
	`status` TINYINT (4) DEFAULT '2' COMMENT '该条的记录状态：0-inactive, 1-confirming, 2-active',
	`create_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
	`update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (`id`)
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 COMMENT = '项目合同报表结果集（项目-月份）'