CREATE TABLE `eh_organization_member_details` (
  `id` bigint(20) NOT NULL COMMENT 'id for records',
  `namespace_id` int(11) NOT NULL DEFAULT '0',
  `organization_id` bigint(20) NOT NULL COMMENT 'reference for eh_organization_member organization_id',
  `contact_name` varchar(64) DEFAULT NULL,
  `contact_type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0: mobile, 1: email',
  `contact_token` varchar(128) DEFAULT NULL COMMENT 'phone number, reference for eh_organization_member contact_token',
  `contact_description` text,
  `employee_no` varchar(128) DEFAULT NULL,
  `avatar` varchar(128) DEFAULT NULL,
  `gender` tinyint(4) DEFAULT '0' COMMENT '0: undisclosured, 1: male, 2: female',
  `status` tinyint(4) NOT NULL DEFAULT '0',
  `birthday` date DEFAULT NULL COMMENT 'the birthday of the member',
  `marital_flag` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0: undisclosured, 1: married, 2: unmarried',
  `political_status` varchar(128) DEFAULT NULL COMMENT '政治面貌',
  `native_place` varchar(128) DEFAULT NULL COMMENT '籍贯',
  `en_name` varchar(128) DEFAULT NULL COMMENT 'english name',
  `reg_residence` varchar(128) DEFAULT NULL COMMENT '户口',
  `id_number` varchar(64) DEFAULT NULL COMMENT 'ID Card number',
  `email` varchar(128) DEFAULT NULL COMMENT 'email for members',
  `wechat` varchar(128) DEFAULT NULL,
  `qq` varchar(128) DEFAULT NULL,
  `emergency_name` varchar(128) DEFAULT NULL COMMENT 'emergency contact name',
  `emergency_contact` varchar(128) DEFAULT NULL COMMENT 'emergency contact tel-number',
  `address` varchar(255) DEFAULT NULL COMMENT 'address for the member',
  `employee_type` tinyint(4) DEFAULT NULL COMMENT '0: full-time, 1: part-time, 2: internship, 3: labor dispatch',
  `employee_status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0: probation, 1: on the job, 2: leave the job',
  `employment_time` date DEFAULT NULL COMMENT '转正日期',
  `dimission_time` date DEFAULT NULL COMMENT '离职日期',
  `salary_card_number` varchar(128) DEFAULT NULL COMMENT '工资卡号',
  `social_security_number` varchar(128) DEFAULT NULL COMMENT '社保号',
  `provident_fund_number` varchar(128) DEFAULT NULL COMMENT '公积金号',
  `profile_integrity` int(11) DEFAULT '0' COMMENT '档案完整度，0-100%',
  `check_in_time` date NOT NULL COMMENT '入职日期',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


ALTER TABLE `eh_organization_members` ADD COLUMN `detail_id` BIGINT COMMENT 'id for detail records'