-- 积分规则分类
INSERT INTO `eh_point_rule_categories` (`id`, `namespace_id`, `display_name`, `status`, `server_id`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (1, 0, '账户', 2, 'default', NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rule_categories` (`id`, `namespace_id`, `display_name`, `status`, `server_id`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (2, 0, '论坛', 2, 'default', NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rule_categories` (`id`, `namespace_id`, `display_name`, `status`, `server_id`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (3, 0, '活动', 2, 'default', NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rule_categories` (`id`, `namespace_id`, `display_name`, `status`, `server_id`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (4, 0, '俱乐部', 2, 'default', NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rule_categories` (`id`, `namespace_id`, `display_name`, `status`, `server_id`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (5, 0, '行业协会', 2, 'default', NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rule_categories` (`id`, `namespace_id`, `display_name`, `status`, `server_id`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (6, 0, '意见反馈', 2, 'default', NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rule_categories` (`id`, `namespace_id`, `display_name`, `status`, `server_id`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (7, 0, '电商', 2, 'default', NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rule_categories` (`id`, `namespace_id`, `display_name`, `status`, `server_id`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (8, 0, '园区服务', 2, 'default', NULL, NULL, NULL, NULL);


-- 积分规则
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (1, 0, 0, 1, 0, '注册成功', '注册成功', 1, 10, 2, '{"times":1}', 'account.register_success.default', '', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (2, 0, 0, 1, 0, '认证成功', '首次通过认证', 1, 10, 2, '{"times":1}', 'account.auth_success.default', '', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (3, 0, 0, 1, 0, '完善个人信息', '完善个人信息', 1, 10, 2, '{"times":1}', 'account.complete_info.default', '', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (4, 0, 0, 2, 0, '发布帖子', '发布帖子', 1, 5, 1, '{"times":3}', 'form.post_create.default', '', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (5, 0, 0, 2, 0, '评论帖子', '发布评论', 1, 2, 1, '{"times":5}', 'form.comment_create.default', '', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (6, 0, 0, 2, 0, '点赞帖子', '点赞帖子', 1, 1, 1, '{"times":5}', 'form.post_like.default', '', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (7, 0, 0, 2, 0, '分享帖子', '分享帖子', 1, 1, 1, '{"times":2}', 'form.post_share.default', '', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (8, 0, 0, 2, 0, '参与投票', '参与投票', 1, 2, 1, '{"times":5}', 'form.post_vote.default', '', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (9, 0, 0, 3, 0, '成功发起活动', '发起活动', 1, 10, 1, '{"times":1}', 'activity.activity_create.default', '', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (10, 0, 0, 3, 0, '报名活动', '报名活动', 1, 3, 1, '{"times":2}', 'activity.activity_enter.default', '', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (11, 0, 0, 3, 0, '分享活动', '分享活动', 1, 2, 1, '{"times":5}', 'activity.activity_share.default', '', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (12, 0, 0, 3, 0, '评论活动', '评论活动', 1, 2, 1, '{"times":5}', 'activity.comment_create.default', '', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (13, 0, 0, 3, 0, '点赞活动', '点赞活动', 1, 1, 1, '{"times":5}', 'activity.activity_like.default', '', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (14, 0, 0, 4, 0, '成功发起俱乐部', '发起俱乐部', 1, 10, 1, '{"times":5}', 'club.club_create.default', '', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (15, 0, 0, 4, 0, '成功加入俱乐部', '加入俱乐部', 1, 3, 1, '{"times":5}', 'club.club_join.default', '', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (16, 0, 0, 5, 0, '成功发起行业协会', '发起行业协会', 1, 10, 1, '{"times":5}', 'club.club_create.default', '', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (17, 0, 0, 5, 0, '成功加入行业协会', '加入行业协会', 1, 3, 1, '{"times":5}', 'club.club_join.default', '', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (18, 0, 0, 6, 0, '在意见反馈中发布帖子', '发布意见反馈', 1, 2, 1, '{"times":2}', 'form.post_create.default', '', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (19, 0, 0, 7, 0, '电商消费', '电商每天首次购物', 1, 2, 1, '{"times":1}', 'biz.order_pay_complete.default', '', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (20, 0, 0, 7, 0, '连续三天电商消费', '电商连续购物3天', 1, 8, 1, '{"times":1}', 'biz.order_pay_complete.default', '', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (21, 0, 0, 8, 0, '园区资源预约成功', '园区资源预约成功', 1, 2, 1, '{"times":5}', 'rental.resource_apply.default', '', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (22, 0, 0, 2, 0, '论坛帖子被举报且管理员核实', '论坛帖子被举报', 2, 10, 1, '{"times":2}', 'form.post_report.default', '', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (23, 0, 0, 2, 0, '论坛评论被举报且管理员核实', '论坛评论被举报', 2, 5, 1, '{"times":2}', 'form.comment_report.default', '', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (24, 0, 0, 2, 0, '删除帖子', '删除论坛帖子', 2, 3, 1, '{"times":5}', 'form.post_delete.default', 'form.post_create.default', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (25, 0, 0, 2, 0, '删除评论', '删除论坛评论', 2, 2, 1, '{"times":5}', 'form.comment_delete.default', 'form.comment_create.default', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (26, 0, 0, 2, 0, '取消论坛点赞', '取消论坛点赞', 2, 1, 1, '{"times":5}', 'form.post_like_cancel.default', 'form.post_like.default', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (27, 0, 0, 3, 0, '活动被举报且管理员核实', '活动被举报', 2, 10, 1, '{"times":2}', 'activity.activity_report.default', '', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (28, 0, 0, 3, 0, '活动评论被举报且管理员核实', '活动评论被举报', 2, 5, 1, '{"times":2}', 'activity.comment_report.default', '', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (29, 0, 0, 3, 0, '取消活动报名', '取消活动报名', 2, 2, 1, '{"times":2}', 'activity.activity_enter_cancel.default', 'activity.activity_enter.default', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (30, 0, 0, 3, 0, '删除活动评论', '删除活动评论', 2, 2, 1, '{"times":2}', 'activity.comment_delete.default', 'activity.comment_create.default', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (31, 0, 0, 3, 0, '取消活动点赞', '取消活动点赞', 2, 1, 1, '{"times":2}', 'activity.activity_like_cancel.default', 'activity.activity_like.default', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (32, 0, 0, 4, 0, '解散俱乐部', '解散俱乐部', 2, 10, 1, '{"times":2}', 'club.club_release.default', 'club.club_create.default', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (33, 0, 0, 4, 0, '退出俱乐部', '退出俱乐部', 2, 2, 1, '{"times":5}', 'club.club_leave.default', 'club.club_join.default', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (34, 0, 0, 5, 0, '解散行业协会', '解散行业协会', 2, 10, 1, '{"times":2}', 'club.club_release.default', 'club.club_create.default', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (35, 0, 0, 5, 0, '退出行业协会', '退出行业协会', 2, 2, 1, '{"times":2}', 'club.club_leave.default', 'club.club_join.default', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (36, 0, 0, 6, 0, '删除意见反馈帖子', '删除意见反馈', 2, 2, 1, '{"times":2}', 'form.post_delete.default', 'form.post_create.default', 1, 1, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (37, 0, 0, 7, 0, '消费抵现', '电商购物抵现', 2, 0, 3, ' ', 'biz.order_create.default', '', 1, 0, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_rules` (`id`, `namespace_id`, `system_id`, `category_id`, `module_id`, `display_name`, `description`, `arithmetic_type`, `points`, `limit_type`, `limit_data`, `event_name`, `binding_event_name`, `status`, `display_flag`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (38, 0, 0, 8, 0, '取消资源预约', '取消资源预约', 2, 2, 1, '{"times":5}', 'rental.resource_apply_cancel.default', 'rental.resource_apply.default', 1, 1, NULL, NULL, NULL, NULL);

-- 积分系统
INSERT INTO `eh_point_systems` (`id`, `namespace_id`, `display_name`, `point_name`, `point_exchange_flag`, `exchange_point`, `exchange_cash`, `user_agreement`, `status`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (1, 1000000, '积分系统', '积分', 1, 100, 1, NULL, 2, '2017-12-08 15:10:23.000', NULL, NULL, NULL);

INSERT INTO `eh_point_tutorials` (`id`, `namespace_id`, `system_id`, `display_name`, `description`, `poster_uri`, `status`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (1, 1000000, 1, '社区讨论', '话题/活动/投票', 'cs://1/image/aW1hZ2UvTVRwaU5EWmxOamMwTlRVek5UbGhNemxsTXpWa05tUmpZMkkwTldNMFpUWTRZUQ', 2, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_tutorials` (`id`, `namespace_id`, `system_id`, `display_name`, `description`, `poster_uri`, `status`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (2, 1000000, 1, '购物消费', '园区消费攒积分', 'cs://1/image/aW1hZ2UvTVRvNU5HTXdaREJoTTJZNVpHUXhZVGMwTTJRNE5XSTBZVEZsTkdWa1ptVXlOQQ', 2, NULL, NULL, NULL, NULL);
INSERT INTO `eh_point_tutorials` (`id`, `namespace_id`, `system_id`, `display_name`, `description`, `poster_uri`, `status`, `create_time`, `creator_uid`, `update_time`, `update_uid`) VALUES (3, 1000000, 1, '园区服务', '使用公共服务送积分', 'cs://1/image/aW1hZ2UvTVRvM09HRTJZbU5sWXpFek9UUmtaREF5TkRNek1tVTRORFUzT1dJeE5ESXpNdw', 2, NULL, NULL, NULL, NULL);


SET @eh_configurations_id = IFNULL((SELECT MAX(id) FROM `eh_configurations`), 1);
INSERT INTO `eh_configurations` (`id`, `name`, `value`, `description`, `namespace_id`, `display_name`)
VALUES ((@eh_configurations_id := @eh_configurations_id + 1), 'point.detail.path', '/integral-management/build/index.html?systemId=%s&ehnavigatorstyle=2#/home#sign_suffix', 'point detail path', 1000000, '');
