
-- 重建服务广场模板
DELETE from eh_portal_layout_templates;
INSERT INTO `eh_portal_layout_templates` (`id`, `namespace_id`, `label`, `template_json`, `show_uri`, `status`, `create_time`, `update_time`, `operator_uid`, `creator_uid`, `description`, `type`) VALUES ('1', '0', '首页', '{\"layoutName\":\"ServiceMarketLayout\",\"location\":\"/home\",\"groups\":[{\"label\":\"海报\", \"separatorFlag\":\"0\", \"separatorHeight\":\"0\",\"widget\":\"Banners\",\"style\":\"Default\",\"defaultOrder\":1},{\"label\":\"公告\", \"separatorFlag\":\"0\", \"separatorHeight\":\"0\",\"widget\":\"Bulletins\",\"style\":\"Default\",\"defaultOrder\":2,\"description\":\"\"},{\"label\":\"容器\", \"separatorFlag\":\"0\", \"separatorHeight\":\"0\",\"widget\":\"Navigator\",\"style\":\"Gallery\",\"instanceConfig\":{\"margin\":20,\"padding\":16,\"backgroundColor\":\"#ffffff\",\"titleFlag\":0,\"title\":\"标题\",\"titleUri\":\"\"},\"defaultOrder\":3,\"description\":\"\"}]}', NULL, '2', '2017-09-15 18:53:16', '2017-09-15 18:53:16', '1', '1', NULL, '1');
INSERT INTO `eh_portal_layout_templates` (`id`, `namespace_id`, `label`, `template_json`, `show_uri`, `status`, `create_time`, `update_time`, `operator_uid`, `creator_uid`, `description`, `type`) VALUES ('2', '0', '自定义门户', '{\"groups\":[{\"label\":\"容器\", \"separatorFlag\":\"0\",\"separatorHeight\":\"0\",\"widget\":\"Navigator\",\"style\":\"Gallery\",\"instanceConfig\":{\"margin\":20,\"padding\":16,\"backgroundColor\":\"#ffffff\",\"titleFlag\":0,\"title\":\"标题\",\"titleUri\":\"\"},\"defaultOrder\":1,\"description\":\"\"}]}', NULL, '2', '2017-09-15 18:53:16', '2017-09-15 18:53:16', '1', '1', NULL, '2');
INSERT INTO `eh_portal_layout_templates` (`id`, `namespace_id`, `label`, `template_json`, `show_uri`, `status`, `create_time`, `update_time`, `operator_uid`, `creator_uid`, `description`, `type`) VALUES ('3', '0', '分页签门户', '{\"groups\":[{\"label\":\"分页签\", \"separatorFlag\":\"0\", \"separatorHeight\":\"0\",\"widget\":\"Tab\",\"style\":\"1\",\"defaultOrder\":1}]}', NULL, '2', '2017-09-15 18:53:16', '2017-09-15 18:53:16', '1', '1', NULL, '3');

-- 首页（激活）
UPDATE eh_portal_layouts SET type = 1, index_flag = 1 WHERE location = '/home' AND `name` = 'ServiceMarketLayout';
-- 自定义门户（激活）
UPDATE eh_portal_layouts SET type = 2, index_flag = 1 WHERE location = '/secondhome' AND `name` = 'SecondServiceMarketLayout';
-- 分页签门户（激活）
UPDATE eh_portal_layouts SET type = 3, index_flag = 1 WHERE location = '/association' AND `name` = 'AssociationLayout';

-- 分页签门户（未激活）
UPDATE eh_portal_layouts a SET type = 3, index_flag = 0 WHERE type IS NULL AND EXISTS ( SELECT * from  eh_portal_item_groups b WHERE a.id = b.layout_id and b.widget = 'Tab');

-- 自定义门户（未激活）
UPDATE eh_portal_layouts SET type = 2, index_flag = 0 WHERE type IS NULL;


--
DELETE FROM eh_service_modules  WHERE  id in (400, 90000, 90100, 92000, 92100, 92200)
INSERT INTO `eh_service_modules` (`id`, `name`, `parent_id`, `path`, `type`, `level`, `status`, `default_order`, `create_time`, `instance_config`, `action_type`, `update_time`, `operator_uid`, `creator_uid`, `description`, `multiple_flag`, `module_control_type`, `access_control_type`, `menu_auth_flag`, `category`) VALUES ('400', '其他', '0', '/400', '1', '1', '2', '40', '2018-07-31 11:44:40', NULL, NULL, '2018-07-31 11:44:44', '0', '0', '0', '0', '', '1', '1', 'classify');
INSERT INTO `eh_service_modules` (`id`, `name`, `parent_id`, `path`, `type`, `level`, `status`, `default_order`, `create_time`, `instance_config`, `action_type`, `update_time`, `operator_uid`, `creator_uid`, `description`, `multiple_flag`, `module_control_type`, `access_control_type`, `menu_auth_flag`, `category`) VALUES ('90000', '第三方服务模块', '400', '/400/90000', '1', '2', '2', '20', '2017-07-04 15:55:50', NULL, NULL, '2017-09-08 18:59:10', '0', '0', '0', '0', '', '1', '1', 'classify');
INSERT INTO `eh_service_modules` (`id`, `name`, `parent_id`, `path`, `type`, `level`, `status`, `default_order`, `create_time`, `instance_config`, `action_type`, `update_time`, `operator_uid`, `creator_uid`, `description`, `multiple_flag`, `module_control_type`, `access_control_type`, `menu_auth_flag`, `category`) VALUES ('90100', '第三方服务模块', '90000', '/400/90000/90100', '1', '3', '2', '10', '2018-07-31 12:10:57', NULL, NULL, NULL, '0', '0', '0', '1', '', '1', '1', 'module');
INSERT INTO `eh_service_modules` (`id`, `name`, `parent_id`, `path`, `type`, `level`, `status`, `default_order`, `create_time`, `instance_config`, `action_type`, `update_time`, `operator_uid`, `creator_uid`, `description`, `multiple_flag`, `module_control_type`, `access_control_type`, `menu_auth_flag`, `category`) VALUES ('92000', '电商', '400', '/400/92000', '1', '2', '2', '10', '2018-07-04 17:22:11', NULL, NULL, '2018-07-04 17:22:20', '0', '0', '0', '0', NULL, '1', '1', 'classify');
INSERT INTO `eh_service_modules` (`id`, `name`, `parent_id`, `path`, `type`, `level`, `status`, `default_order`, `create_time`, `instance_config`, `action_type`, `update_time`, `operator_uid`, `creator_uid`, `description`, `multiple_flag`, `module_control_type`, `access_control_type`, `menu_auth_flag`, `category`) VALUES ('92100', '微商城', '92000', '/400/92000/92100', '1', '3', '2', '10', '2018-07-04 17:23:28', '{\"url\":\"${stat.biz.server.url}zl-ec/rest/service/front/logon?hideNavigationBar=1&sourceUrl=${stat.biz.server.url}nar/biz/web/app/user/index.html?clientrecommend=1#/recommend?_k=zlbiz#sign_suffix\"}', NULL, '2018-07-04 17:23:33', '0', '0', '0', '1', NULL, '1', '1', 'module');
INSERT INTO `eh_service_modules` (`id`, `name`, `parent_id`, `path`, `type`, `level`, `status`, `default_order`, `create_time`, `instance_config`, `action_type`, `update_time`, `operator_uid`, `creator_uid`, `description`, `multiple_flag`, `module_control_type`, `access_control_type`, `menu_auth_flag`, `category`) VALUES ('92200', '食堂', '92000', '/400/92000/92200', '1', '3', '2', '20', '2018-07-31 12:09:15', NULL, NULL, '2018-07-31 12:09:25', '0', '0', '0', '1', '', '1', '1', 'module');
