-- 薪酬管理基础数据 added by wh
INSERT INTO `eh_salary_entity_categories` (`id`, `namespace_id`, `category_name`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES('1','0','基础信息\r\n','2','1','2017-06-22 18:23:54',NULL,NULL);
INSERT INTO `eh_salary_entity_categories` (`id`, `namespace_id`, `category_name`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES('2','0','应发项\r\n','2','1','2017-06-22 18:23:54',NULL,NULL);
INSERT INTO `eh_salary_entity_categories` (`id`, `namespace_id`, `category_name`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES('3','0','补发项\r\n','2','1','2017-06-22 18:23:54',NULL,NULL);
INSERT INTO `eh_salary_entity_categories` (`id`, `namespace_id`, `category_name`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES('4','0','应扣项\r\n','2','1','2017-06-22 18:23:54',NULL,NULL);
INSERT INTO `eh_salary_entity_categories` (`id`, `namespace_id`, `category_name`, `status`, `creator_uid`, `create_time`, `update_time`, `operator_uid`) VALUES('5','0','合计项\r\n','2','1','2017-06-22 18:23:54',NULL,NULL);



INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('1',NULL,NULL,'0','1','0','1','基础信息','工号','0','信息模板1','1',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('2',NULL,NULL,'0','0','0','1','基础信息','工资月份','1','信息模板2','2',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('3',NULL,NULL,'0','0','0','1','基础信息','发放日期','1','信息模板2','3',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('4',NULL,NULL,'0','1','0','1','基础信息','姓名','0','信息模板1','4',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('5',NULL,NULL,'0','1','0','1','基础信息','部门','0','信息模板1','5',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('6',NULL,NULL,'0','0','0','1','基础信息','费用归属','1','信息模板2','6',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('7',NULL,NULL,'0','1','0','1','基础信息','身份证号','0','信息模板1','7',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('8',NULL,NULL,'0','1','0','1','基础信息','银行账号','0','信息模板1','8',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('9',NULL,NULL,'0','0','0','1','基础信息','备注','1','信息模板2','9',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('10',NULL,NULL,'0','0','1','1','基础信息','原工资级别','1','数值模板1','10',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('11',NULL,NULL,'0','0','1','1','基础信息','工资级别','1','数值模板1','11',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('12',NULL,NULL,'0','0','1','1','基础信息','应出勤天数','1','数值模板1','12',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('13',NULL,NULL,'0','0','1','1','基础信息','实出勤天数','1','数值模板1','13',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('14',NULL,NULL,'0','0','1','1','基础信息','绩效系数','1','数值模板1','14',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('15',NULL,NULL,'0','0','1','1','基础信息','平常延时加班小时','1','数值模板1','15',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('16',NULL,NULL,'0','0','1','1','基础信息','休息日加班小时','1','数值模板1','16',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('17',NULL,NULL,'0','0','1','1','基础信息','国假加班小时','1','数值模板1','17',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('18',NULL,NULL,'0','0','1','1','基础信息','平常延时加班工资系数','1','数值模板1','18',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('19',NULL,NULL,'0','0','1','1','基础信息','休息日加班工资系数','1','数值模板1','19',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('20',NULL,NULL,'0','0','1','1','基础信息','国假加班工资系数','1','数值模板1','20',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('21',NULL,NULL,'0','0','1','1','基础信息','病假小时数','1','数值模板1','21',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('22',NULL,NULL,'0','0','1','1','基础信息','事假小时数','1','数值模板1','22',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('23',NULL,NULL,'0','0','1','1','基础信息','病假扣款系数','1','数值模板1','23',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('24',NULL,NULL,'0','0','1','1','基础信息','事假扣款系数','1','数值模板1','24',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('25',NULL,NULL,'0','0','1','1','基础信息','旷工天数','1','数值模板1','25',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('26',NULL,NULL,'0','0','1','1','基础信息','迟到次数','1','数值模板1','26',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('27',NULL,NULL,'0','0','1','1','基础信息','早退次数','1','数值模板1','27',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('28',NULL,NULL,'0','0','1','1','基础信息','迟到扣款基数','1','数值模板1','28',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('29',NULL,NULL,'0','0','1','1','基础信息','早退扣款基数','1','数值模板1','29',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('30',NULL,NULL,'0','0','1','1','基础信息','请假扣款基数','1','数值模板1','30',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('31',NULL,NULL,'0','0','1','1','基础信息','旷工扣款基数','1','数值模板1','31',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('32',NULL,NULL,'0','0','1','1','基础信息','个税基数','1','数值模板1','32',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('33',NULL,NULL,'0','0','1','1','基础信息','试用期不发放比例','1','数值模板1','33',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('34',NULL,NULL,'0','0','1','1','基础信息','打卡异常次数','1','数值模板1','34',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('35',NULL,NULL,'0','0','1','1','基础信息','社保扣款（公司）','1','数值模板1','35',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('36',NULL,NULL,'0','0','1','1','基础信息','公积金扣款（公司）','1','数值模板1','36',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('37',NULL,NULL,'0','0','1','2','应发项','基本工资','1','数值模板1','37',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('38',NULL,NULL,'0','0','1','2','应发项','职级工资','1','数值模板1','38',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('39',NULL,NULL,'0','0','1','2','应发项','岗位工资','1','数值模板1','39',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('40',NULL,NULL,'0','0','1','2','应发项','绩效工资','1','数值模板1','40',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('41',NULL,NULL,'0','0','1','2','应发项','提成工资','1','数值模板1','41',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('42',NULL,NULL,'0','0','1','2','应发项','工龄工资','1','数值模板1','42',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('43',NULL,NULL,'0','0','1','2','应发项','浮动工资','1','数值模板1','43',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('44',NULL,NULL,'0','0','1','2','应发项','固定工资','1','数值模板1','44',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('45',NULL,NULL,'0','0','1','2','应发项','休息日加班工资','1','数值模板1','45',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('46',NULL,NULL,'0','0','1','2','应发项','平常延时加班工资','1','数值模板1','46',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('47',NULL,NULL,'0','0','1','2','应发项','法定节日加班工资','1','数值模板1','47',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('48',NULL,NULL,'0','0','1','2','应发项','加班工资','1','数值模板1','48',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('49',NULL,NULL,'0','0','1','2','应发项','年终奖','1','数值模板1','49',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('50',NULL,NULL,'0','0','1','3','补发项','月度奖金','1','数值模板1','50',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('51',NULL,NULL,'0','0','1','3','补发项','全勤奖','1','数值模板1','51',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('52',NULL,NULL,'0','0','1','3','补发项','其他奖金','1','数值模板1','52',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('53',NULL,NULL,'0','0','1','3','补发项','驻外补贴','1','数值模板1','53',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('54',NULL,NULL,'0','0','1','3','补发项','旅游补贴','1','数值模板1','54',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('55',NULL,NULL,'0','0','1','3','补发项','中夜班补贴','1','数值模板1','55',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('56',NULL,NULL,'0','0','1','3','补发项','饮食补贴','1','数值模板1','56',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('57',NULL,NULL,'0','0','1','3','补发项','手机补贴','1','数值模板1','57',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('58',NULL,NULL,'0','0','1','3','补发项','住住房补贴','1','数值模板1','58',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('59',NULL,NULL,'0','0','1','3','补发项','医疗补贴','1','数值模板1','59',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('60',NULL,NULL,'0','0','1','3','补发项','交通补贴','1','数值模板1','60',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('61',NULL,NULL,'0','0','1','3','补发项','电脑补贴','1','数值模板1','61',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('62',NULL,NULL,'0','0','1','3','补发项','技术补贴','1','数值模板1','62',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('63',NULL,NULL,'0','0','1','3','补发项','通讯补贴','1','数值模板1','63',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('64',NULL,NULL,'0','0','1','3','补发项','出差津贴','1','数值模板1','64',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('65',NULL,NULL,'0','0','1','3','补发项','岗位津贴','1','数值模板1','65',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('66',NULL,NULL,'0','0','1','3','补发项','外派津贴','1','数值模板1','66',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('67',NULL,NULL,'0','0','1','3','补发项','高温津贴','1','数值模板1','67',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('68',NULL,NULL,'0','0','1','3','补发项','计划生育奖','1','数值模板1','68',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('69',NULL,NULL,'0','0','1','3','补发项','独生子女津贴','1','数值模板1','69',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('70',NULL,NULL,'0','0','1','3','补发项','税前补发','1','数值模板1','70',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('71',NULL,NULL,'0','0','1','3','补发项','税后补发','1','数值模板1','71',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('72',NULL,NULL,'0','0','1','3','补发项','其他补发','1','数值模板1','72',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('73',NULL,NULL,'0','0','1','4','应扣项','出勤扣款','1','数值模板1','73',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('74',NULL,NULL,'0','0','1','4','应扣项','迟到扣款','1','数值模板1','74',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('75',NULL,NULL,'0','0','1','4','应扣项','早退扣款','1','数值模板1','75',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('76',NULL,NULL,'0','0','1','4','应扣项','请假扣款','1','数值模板1','76',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('77',NULL,NULL,'0','0','1','4','应扣项','旷工扣款','1','数值模板1','77',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('78',NULL,NULL,'0','0','1','4','应扣项','扣绩效','1','数值模板1','78',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('79',NULL,NULL,'0','0','1','4','应扣项','扣社保（个人）','1','数值模板1','79',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('80',NULL,NULL,'0','0','1','4','应扣项','扣住房（个人）','1','数值模板1','80',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('81',NULL,NULL,'0','0','1','4','应扣项','借支','1','数值模板1','81',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('82',NULL,NULL,'0','0','1','4','应扣项','凉茶费','1','数值模板1','82',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('83',NULL,NULL,'0','0','1','4','应扣项','扣电费','1','数值模板1','83',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('84',NULL,NULL,'0','0','1','4','应扣项','餐费扣款','1','数值模板1','84',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('85',NULL,NULL,'0','0','1','4','应扣项','扣房租','1','数值模板1','85',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('86',NULL,NULL,'0','0','1','4','应扣项','税前扣款','1','数值模板1','86',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('87',NULL,NULL,'0','0','1','4','应扣项','税后扣款','1','数值模板1','87',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('88',NULL,NULL,'0','0','1','4','应扣项','其他扣款','1','数值模板1','88',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('89',NULL,NULL,'0','0','1','5','合计项','本月合计','0','数值模板2','89',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('90',NULL,NULL,'0','0','1','5','合计项','正常工作时间工资','0','数值模板2','90',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('91',NULL,NULL,'0','0','1','5','合计项','扣前合计','0','数值模板2','91',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('92',NULL,NULL,'0','0','1','5','合计项','社保公积金代扣合计','0','数值模板2','92',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('93',NULL,NULL,'0','0','1','5','合计项','扣款合计','0','数值模板2','93',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('94',NULL,NULL,'0','0','1','5','合计项','补贴合计','0','数值模板2','94',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('95',NULL,NULL,'0','0','1','5','合计项','津贴合计','0','数值模板2','95',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('96',NULL,NULL,'0','0','1','5','合计项','补发合计','0','数值模板2','96',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('97',NULL,NULL,'0','1','1','5','合计项','应发工资','0','数值模板2','97',NULL,NULL,'2');
INSERT INTO `eh_salary_default_entities` (`id`, `owner_type`, `owner_id`, `namespace_id`, `default_flag`, `type`, `category_id`, `category_name`, `name`, `editable_flag`, `template_name`, `default_order`, `creator_uid`, `create_time`, `status`) VALUES('98',NULL,NULL,'0','1','1','5','合计项','实发工资','0','数值模板2','98',NULL,NULL,'2');

-- 邮件模板
SET @id = (SELECT MAX(id)FROM eh_locale_templates);
INSERT INTO `eh_locale_templates` (`id`,`scope`,`code`,`locale`,`description`,`text`,`namespace_id`)VALUES ((@id:=@id+1),'salary.mail','1','zh_CN','邮件模板','<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"><html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><title>工资发放</title></head><body>${emailContent}<br><br>${entityTable}</body></html>',0); 



-- 增加薪酬管理菜单
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`) 
VALUES('51200','薪酬管理','50000',NULL,NULL,'0','2','/50000/51200','park','592','51200');
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`) 
VALUES('51210','批次设置','51200',NULL,'react:/salary-management/batch-setting','0','2','/50000/51200/51210','park','592','51200');
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`) 
VALUES('51220','员工工资','51200',NULL,'react:/salary-management/batch-salary','0','2','/50000/51200/51220','park','593','51200');
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`) 
VALUES('51230','工资发放','51200',NULL,'access_group/inside','0','2','/50000/51200/51230','park','594','51203');
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`) 
VALUES('51231','核算阶段','51230',NULL,'react:/salary-management/salary-check','0','2','/50000/51200/51230/51231','park','595','51200');
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`) 
VALUES('51232','发放阶段','51230',NULL,'react:/salary-management/salary-pay','0','2','/50000/51200/51230/51232','park','596','51200');
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`) 
VALUES('51240','发放历史','51200',NULL,'react:/salary-management/pay-history','0','2','/50000/51200/51240','park','597','51200');

-- 给域空间加菜单 
-- volgo
SET @id = (SELECT MAX(id) FROM eh_web_menu_scopes);
INSERT INTO `eh_web_menu_scopes` (`id`, `menu_id`, `menu_name`, `owner_type`, `owner_id`, `apply_policy`) VALUES((@id:=@id+1),'51200','','EhNamespaces','1','2');
INSERT INTO `eh_web_menu_scopes` (`id`, `menu_id`, `menu_name`, `owner_type`, `owner_id`, `apply_policy`) VALUES((@id:=@id+1),'51210','','EhNamespaces','1','2');
INSERT INTO `eh_web_menu_scopes` (`id`, `menu_id`, `menu_name`, `owner_type`, `owner_id`, `apply_policy`) VALUES((@id:=@id+1),'51220','','EhNamespaces','1','2');
INSERT INTO `eh_web_menu_scopes` (`id`, `menu_id`, `menu_name`, `owner_type`, `owner_id`, `apply_policy`) VALUES((@id:=@id+1),'51230','','EhNamespaces','1','2');
INSERT INTO `eh_web_menu_scopes` (`id`, `menu_id`, `menu_name`, `owner_type`, `owner_id`, `apply_policy`) VALUES((@id:=@id+1),'51231','','EhNamespaces','1','2');
INSERT INTO `eh_web_menu_scopes` (`id`, `menu_id`, `menu_name`, `owner_type`, `owner_id`, `apply_policy`) VALUES((@id:=@id+1),'51232','','EhNamespaces','1','2');
INSERT INTO `eh_web_menu_scopes` (`id`, `menu_id`, `menu_name`, `owner_type`, `owner_id`, `apply_policy`) VALUES((@id:=@id+1),'51240','','EhNamespaces','1','2');


-- 加菜单权限
INSERT INTO `eh_service_modules` (`id`, `name`, `parent_id`, `path`, `type`, `level`, `status`, `default_order`, `create_time`) 
VALUES('51200','薪酬管理','50000','/50000/51200','0','2','2','0','2017-07-10 11:50:20');

SET @privileges_id = (SELECT MAX(id) FROM eh_acl_privileges)+1;
INSERT INTO `eh_acl_privileges` (`id`, `app_id`, `name`, `description`, `tag`) 
VALUES (@privileges_id, 0, '薪酬管理', '薪酬管理 全部权限', NULL);

SET @web_menu_privilege_id = (SELECT MAX(id) FROM `eh_web_menu_privileges`);
INSERT INTO `eh_web_menu_privileges` (`id`, `privilege_id`, `menu_id`, `name`, `show_flag`, `status`, `discription`, `sort_num`) 
VALUES ((@web_menu_privilege_id := @web_menu_privilege_id + 1), @privileges_id, 51200, '薪酬管理', 1, 1, '薪酬管理  全部权限', 202); 
INSERT INTO `eh_web_menu_privileges` (`id`, `privilege_id`, `menu_id`, `name`, `show_flag`, `status`, `discription`, `sort_num`) 
VALUES ((@web_menu_privilege_id := @web_menu_privilege_id + 1), @privileges_id, 51210, '薪酬管理', 1, 1, '薪酬管理  批次设置', 202); 
INSERT INTO `eh_web_menu_privileges` (`id`, `privilege_id`, `menu_id`, `name`, `show_flag`, `status`, `discription`, `sort_num`) 
VALUES ((@web_menu_privilege_id := @web_menu_privilege_id + 1), @privileges_id, 51220, '薪酬管理', 1, 1, '薪酬管理  员工工资', 202); 
INSERT INTO `eh_web_menu_privileges` (`id`, `privilege_id`, `menu_id`, `name`, `show_flag`, `status`, `discription`, `sort_num`) 
VALUES ((@web_menu_privilege_id := @web_menu_privilege_id + 1), @privileges_id, 51230, '薪酬管理', 1, 1, '薪酬管理  工资发放', 202); 
INSERT INTO `eh_web_menu_privileges` (`id`, `privilege_id`, `menu_id`, `name`, `show_flag`, `status`, `discription`, `sort_num`) 
VALUES ((@web_menu_privilege_id := @web_menu_privilege_id + 1), @privileges_id, 51231, '薪酬管理', 1, 1, '薪酬管理  核算阶段', 202); 
INSERT INTO `eh_web_menu_privileges` (`id`, `privilege_id`, `menu_id`, `name`, `show_flag`, `status`, `discription`, `sort_num`) 
VALUES ((@web_menu_privilege_id := @web_menu_privilege_id + 1), @privileges_id, 51232, '薪酬管理', 1, 1, '薪酬管理  发放阶段', 202); 
INSERT INTO `eh_web_menu_privileges` (`id`, `privilege_id`, `menu_id`, `name`, `show_flag`, `status`, `discription`, `sort_num`) 
VALUES ((@web_menu_privilege_id := @web_menu_privilege_id + 1), @privileges_id, 51240, '薪酬管理', 1, 1, '薪酬管理  发放历史', 202); 


SET @acl_id = (SELECT MAX(id) FROM `eh_acls`);
INSERT INTO `eh_acls` (`id`, `namespace_id`, `owner_type`, `owner_id`, `grant_type`, `privilege_id`, `role_id`, `role_type`, `order_seq`, `creator_uid`, `create_time`)
VALUES ((@acl_id := @acl_id + 1), 0, 'EhOrganizations', NULL, 1, @privileges_id, 1005, 'EhAclRoles', 0, 1, NOW()); 
INSERT INTO `eh_acls` (`id`, `namespace_id`, `owner_type`, `owner_id`, `grant_type`, `privilege_id`, `role_id`, `role_type`, `order_seq`, `creator_uid`, `create_time`)
VALUES ((@acl_id := @acl_id + 1), 0, 'EhOrganizations', NULL, 1, @privileges_id, 1001, 'EhAclRoles', 0, 1, NOW()); 

SET @locale_id = (SELECT MAX(id) FROM eh_locale_strings);
INSERT INTO `eh_locale_strings` (`id`,`scope`,`code`,`locale`,`text`) VALUES ((@locale_id := @locale_id + 1),'salarygroup','100001','zh_CN','没有文件');
INSERT INTO `eh_locale_strings` (`id`,`scope`,`code`,`locale`,`text`) VALUES ((@locale_id := @locale_id + 1),'salarygroup','100002','zh_CN','姓名为空');
INSERT INTO `eh_locale_strings` (`id`,`scope`,`code`,`locale`,`text`) VALUES ((@locale_id := @locale_id + 1),'salarygroup','100003','zh_CN','手机号码有误');