-- 社保建表social_security
-- 社保基准表
CREATE TABLE `eh_social_security_bases` (
  `id` BIGINT,
  `city_id` BIGINT DEFAULT '0',
  `household_type` VARCHAR (32) COMMENT '户籍类型',
  `pay_item` VARCHAR (32) COMMENT '缴费项:医疗/养老/失业/工伤/生育/大病/残障金/补充医疗',
  `company_radix_min` DECIMAL (10, 2) COMMENT '企业基数最小值',
  `company_radix_max` DECIMAL (10, 2) COMMENT '企业基数最大值',
  `company_ratio_min` INT COMMENT '企业比例最小值 万分之 eq:100=1%;1=0.01%',
  `company_ratio_max` INT COMMENT '企业比例最大值 万分之 eq:100=1%;1=0.01%',
  `employee_radix_min` DECIMAL (10, 2) COMMENT '个人基数最小值',
  `employee_radix_max` DECIMAL (10, 2) COMMENT ' 个人基数最大值',
  `employee_ratio_min` INT COMMENT '个人比例最小值 万分之 eq:100=1%;1=0.01%',
  `employee_ratio_max` INT COMMENT '个人比例最大值 万分之 eq:100=1%;1=0.01%',
  `editable_flag` TINYINT COMMENT '是否可编辑',
  `is_default` TINYINT COMMENT '是否是默认选项(1-是:普通社保;0-否:补充保险)',
  `effect_time_begin` DATETIME COMMENT '生效起始日期',
  `effect_time_end` DATETIME COMMENT '生效结束日期',
  `ratio_options` TEXT COMMENT '比例可选项,如果为null就是手动填写:eq:[120,230,380,480,520]',
  PRIMARY KEY (`id`),
  KEY `i_eh_city_id` (`city_id`)
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 ;

-- 公积金基准表
CREATE TABLE `eh_accumulation_fund_bases` (
  `id` BIGINT,
  `city_id` BIGINT DEFAULT '0',
  `household_type` VARCHAR (32) COMMENT '户籍类型',
  `company_radix_min` DECIMAL (10, 2) COMMENT '企业基数最小值',
  `company_radix_max` DECIMAL (10, 2) COMMENT '企业基数最大值',
  `company_ratio_min` INT COMMENT '企业比例最小值 万分之 eq:100=1%;1=0.01%',
  `company_ratio_max` INT COMMENT '企业比例最大值 万分之 eq:100=1%;1=0.01%',
  `employee_radix_min` DECIMAL (10, 2) COMMENT '个人基数最小值',
  `employee_radix_max` DECIMAL (10, 2) COMMENT ' 个人基数最大值',
  `employee_ratio_min` INT COMMENT '个人比例最小值 万分之 eq:100=1%;1=0.01%',
  `employee_ratio_max` INT COMMENT '个人比例最大值 万分之 eq:100=1%;1=0.01%',
  `effect_time_begin` DATETIME COMMENT '生效起始日期',
  `effect_time_end` DATETIME COMMENT '生效结束日期',
  `ratio_options` TEXT COMMENT '比例可选项,如果为null就是手动填写:eq:[120,230,380,480,520]',
  PRIMARY KEY (`id`),
  KEY `i_eh_city_id` (`city_id`)
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 ;

-- 社保设置表
CREATE TABLE `eh_social_security_settings` (
  `id` BIGINT,
  `city_id` BIGINT DEFAULT '0',
  `namespace_id` INT (11) DEFAULT '0',
  `organization_id` BIGINT,
  `user_id` BIGINT,
  `detail_id` BIGINT,
  `household_type` VARCHAR (32) COMMENT '户籍类型',
  `pay_item` VARCHAR (32) COMMENT '缴费项:医疗/养老/失业/工伤/生育/大病/残障金/补充医疗',
  `company_radix` DECIMAL (10, 2) COMMENT '企业基数',
  `company_ratio` INT COMMENT '企业比例万分之 eq:100=1%;1=0.01%',
  `employee_radix` DECIMAL (10, 2) COMMENT '个人基数',
  `employee_ratio` INT COMMENT '个人比例 万分之 eq:100=1%;1=0.01%',
  `editable_flag` TINYINT COMMENT '是否可编辑',
  `is_default` TINYINT COMMENT '是否是默认选项(1-是:普通社保;0-否:补充保险)',
  PRIMARY KEY (`id`),
  KEY `i_eh_user_detail_id` (`detail_id`),
  KEY `i_eh_organization_id` (`organization_id`)
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 ;

-- 公积金设置表
CREATE TABLE `eh_accumulation_fund_settings` (
  `id` BIGINT,
  `city_id` BIGINT DEFAULT '0',
  `namespace_id` INT (11) DEFAULT '0',
  `organization_id` BIGINT,
  `user_id` BIGINT,
  `detail_id` BIGINT,
  `household_type` VARCHAR (32) COMMENT '户籍类型',
  `company_radix` DECIMAL (10, 2) COMMENT '企业基数',
  `company_ratio` INT COMMENT '企业比例万分之 eq:100=1%;1=0.01%',
  `employee_radix` DECIMAL (10, 2) COMMENT '个人基数',
  `employee_ratio` INT COMMENT '个人比例 万分之 eq:100=1%;1=0.01%',
  PRIMARY KEY (`id`),
  KEY `i_eh_user_detail_id` (`detail_id`),
  KEY `i_eh_organization_id` (`organization_id`)
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 ;

-- 社保缴费表
CREATE TABLE `eh_social_security_payments` (
  `id` BIGINT,
  `city_id` BIGINT DEFAULT '0',
  `namespace_id` INT (11) DEFAULT '0',
  `organization_id` BIGINT,
  `user_id` BIGINT,
  `detail_id` BIGINT,
  `pay_month` VARCHAR (8) DEFAULT NULL COMMENT 'yyyymm',
  `after_pay_flag` TINYINT COMMENT '补缴标记',
  `household_type` VARCHAR (32) COMMENT '户籍类型',
  `pay_item` VARCHAR (32) COMMENT '缴费项:医疗/养老/失业/工伤/生育/大病/残障金/补充医疗',
  `company_radix` DECIMAL (10, 2) COMMENT '企业基数',
  `company_ratio` INT COMMENT '企业比例万分之 eq:100=1%;1=0.01%',
  `employee_radix` DECIMAL (10, 2) COMMENT '个人基数',
  `employee_ratio` INT COMMENT '个人比例 万分之 eq:100=1%;1=0.01%',
  `editable_flag` TINYINT COMMENT '是否可编辑',
  `is_default` TINYINT COMMENT '是否是默认选项(1-是:普通社保;0-否:补充保险)',
  `is_new` TINYINT COMMENT '增减员:0正常,1增员,-1减员',
  `is_work` TINYINT COMMENT '入职离职:0正常,1入职,-1离职',
  PRIMARY KEY (`id`),
  KEY `i_eh_user_detail_id` (`detail_id`),
  KEY `i_eh_organization_id` (`organization_id`)
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 ;

-- 公积金缴费表
CREATE TABLE `eh_accumulation_fund_payments` (
  `id` BIGINT,
  `city_id` BIGINT DEFAULT '0',
  `namespace_id` INT (11) DEFAULT '0',
  `organization_id` BIGINT,
  `user_id` BIGINT,
  `detail_id` BIGINT,
  `pay_month` VARCHAR (8) DEFAULT NULL COMMENT 'yyyymm',
  `after_pay_flag` TINYINT COMMENT '补缴标记',
  `household_type` VARCHAR (32) COMMENT '户籍类型',
  `company_radix` DECIMAL (10, 2) COMMENT '企业基数',
  `company_ratio` INT COMMENT '企业比例万分之 eq:100=1%;1=0.01%',
  `employee_radix` DECIMAL (10, 2) COMMENT '个人基数',
  `employee_ratio` INT COMMENT '个人比例 万分之 eq:100=1%;1=0.01%',
  `is_new` TINYINT COMMENT '增减员:0正常,1增员,-1减员',
  `is_work` TINYINT COMMENT '入职离职:0正常,1入职,-1离职',
  PRIMARY KEY (`id`),
  KEY `i_eh_user_detail_id` (`detail_id`),
  KEY `i_eh_organization_id` (`organization_id`)
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 ;

-- 社保缴费表
CREATE TABLE `eh_social_security_payment_logs` (
  `id` BIGINT,
  `city_id` BIGINT DEFAULT '0',
  `namespace_id` INT (11) DEFAULT '0',
  `organization_id` BIGINT,
  `user_id` BIGINT,
  `detail_id` BIGINT,
  `pay_month` VARCHAR (8) DEFAULT NULL COMMENT 'yyyymm',
  `after_pay_flag` TINYINT COMMENT '补缴标记',
  `household_type` VARCHAR (32) COMMENT '户籍类型',
  `pay_item` VARCHAR (32) COMMENT '缴费项:医疗/养老/失业/工伤/生育/大病/残障金/补充医疗',
  `company_radix` DECIMAL (10, 2) COMMENT '企业基数',
  `company_ratio` INT COMMENT '企业比例万分之 eq:100=1%;1=0.01%',
  `employee_radix` DECIMAL (10, 2) COMMENT '个人基数',
  `employee_ratio` INT COMMENT '个人比例 万分之 eq:100=1%;1=0.01%',
  `editable_flag` TINYINT COMMENT '是否可编辑',
  `is_default` TINYINT COMMENT '是否是默认选项(1-是:普通社保;0-否:补充保险)',
  `is_new` TINYINT COMMENT '增减员:0正常,1增员,-1减员',
  `is_work` TINYINT COMMENT '入职离职:0正常,1入职,-1离职',
  PRIMARY KEY (`id`),
  KEY `i_eh_user_detail_id` (`detail_id`),
  KEY `i_eh_organization_id` (`organization_id`)
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 ;

-- 汇总表
CREATE TABLE `eh_social_security_summary` (
  `id` BIGINT,
  `namespace_id` INT (11) DEFAULT '0',
  `organization_id` BIGINT,
  `pay_month` VARCHAR (8) DEFAULT NULL COMMENT 'yyyymm',
  `company_payment` DECIMAL (10, 2) COMMENT '企业缴纳',
  `employee_payment` DECIMAL (10, 2) COMMENT '个人缴纳',
  `creator_uid` BIGINT (20),
  `create_time` DATETIME,
  `file_uid` BIGINT (20) COMMENT '归档人',
  `file_time` DATETIME COMMENT '归档时间',
  PRIMARY KEY (`id`),
  KEY `i_eh_user_detail_id` (`detail_id`),
  KEY `i_eh_organization_id` (`organization_id`)
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 ;

-- 部门汇总表
CREATE TABLE `eh_social_security_department_summary` (
  `id` BIGINT,
  `namespace_id` INT (11) DEFAULT '0',
  `owner_id` BIGINT COMMENT '所属企业',
  `dept_id` BIGINT (20) DEFAULT NULL COMMENT 'user department id',
  `dept_name` VARCHAR (128) DEFAULT NULL COMMENT 'user department name',
  `pay_month` VARCHAR (8) DEFAULT NULL COMMENT 'yyyymm',
  `employee_count` INT COMMENT '人数', 
  `social_security_sum` DECIMAL (10, 2) COMMENT '社保合计',
  `social_security_company_sum` DECIMAL (10, 2) COMMENT '社保企业合计',
  `social_security_employee_sum` DECIMAL (10, 2) COMMENT '社保个人合计',
  `pension_company_sum` DECIMAL (10, 2) COMMENT '养老企业合计',
  `pension_employee_sum` DECIMAL (10, 2) COMMENT '养老个人合计',
  `medical_company_sum` DECIMAL (10, 2) COMMENT '医疗企业合计',
  `medical_employee_sum` DECIMAL (10, 2) COMMENT '医疗个人合计',
  `injury_company_sum` DECIMAL (10, 2) COMMENT '工伤企业合计',
  `injury_employee_sum` DECIMAL (10, 2) COMMENT '工伤个人合计',
  `unemployment_company_sum` DECIMAL (10, 2) COMMENT '失业企业合计',
  `unemployment_employee_sum` DECIMAL (10, 2) COMMENT '失业个人合计',
  `birth_company_sum` DECIMAL (10, 2) COMMENT '生育企业合计',
  `birth_employee_sum` DECIMAL (10, 2) COMMENT '生育个人合计',
  `critical_illness_company_sum` DECIMAL (10, 2) COMMENT '大病企业合计',
  `critical_illness_employee_sum` DECIMAL (10, 2) COMMENT '大病个人合计',
  `after_social_security_company_sum` DECIMAL (10, 2) COMMENT '补缴社保企业合计',
  `after_social_security_employee_sum` DECIMAL (10, 2) COMMENT '补缴社保个人合计',
  `after_pension_company_sum` DECIMAL (10, 2) COMMENT '补缴养老企业合计',
  `after_pension_employee_sum` DECIMAL (10, 2) COMMENT '补缴养老个人合计',
  `after_medical_company_sum` DECIMAL (10, 2) COMMENT '补缴医疗企业合计',
  `after_medical_employee_sum` DECIMAL (10, 2) COMMENT '补缴医疗个人合计',
  `after_injury_company_sum` DECIMAL (10, 2) COMMENT '补缴工伤企业合计',
  `after_injury_employee_sum` DECIMAL (10, 2) COMMENT '补缴工伤个人合计',
  `after_unemployment_company_sum` DECIMAL (10, 2) COMMENT '补缴失业企业合计',
  `after_unemployment_employee_sum` DECIMAL (10, 2) COMMENT '补缴失业个人合计',
  `after_birth_company_sum` DECIMAL (10, 2) COMMENT '补缴生育企业合计',
  `after_birth_employee_sum` DECIMAL (10, 2) COMMENT '补缴生育个人合计',
  `after_critical_illness_company_sum` DECIMAL (10, 2) COMMENT '补缴大病企业合计',
  `after_critical_illness_employee_sum` DECIMAL (10, 2) COMMENT '补缴大病个人合计',
  `disability_sum` DECIMAL (10, 2) COMMENT '残障金',
  `commercial_insurance` DECIMAL (10, 2) COMMENT '商业保险', 
  `accumulation_fund_sum` DECIMAL (10, 2) COMMENT '公积金合计',
  `accumulation_fund_company_sum` DECIMAL (10, 2) COMMENT '公积金企业合计',
  `accumulation_fund_employee_sum` DECIMAL (10, 2) COMMENT '公积金个人合计',
  `after_accumulation_fund_company_sum` DECIMAL (10, 2) COMMENT '补缴公积金企业合计',
  `after_accumulation_fund_employee_sum` DECIMAL (10, 2) COMMENT '补缴公积金个人合计',
  `creator_uid` BIGINT (20),
  `create_time` DATETIME,
  `file_uid` BIGINT (20) COMMENT '归档人',
  `file_time` DATETIME COMMENT '归档时间',
  PRIMARY KEY (`id`),
  KEY `i_eh_owner_id` (`owner_id`)
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 ;

-- 社保报表
CREATE TABLE `eh_social_security_report` (
  `id` BIGINT,
  `namespace_id` INT (11) DEFAULT '0',
  `organization_id` BIGINT,
  `user_id` BIGINT,
  `detail_id` BIGINT,
  `user_name` VARCHAR (128) COMMENT '姓名',
  `entry_date` DATE COMMENT '入职日期',
  `contact_token` VARCHAR (128) DEFAULT NULL COMMENT '手机号',
  `id_number` VARCHAR (128) DEFAULT NULL COMMENT '身份证号',
  `degree` VARCHAR (64) DEFAULT NULL COMMENT '学历',
  `salary_card_bank` VARCHAR (64) DEFAULT NULL COMMENT '开户行',
  `salary_card_number` VARCHAR (128) DEFAULT NULL COMMENT '工资卡号',
  `dept_name` VARCHAR (128) DEFAULT NULL COMMENT '部门',
  `social_security_number` VARCHAR (128) DEFAULT NULL COMMENT '社保号',
  `provident_fund_number` VARCHAR (128) DEFAULT NULL COMMENT '公积金号',
  `out_work_date` DATE COMMENT '离职日期',
  `household_type` VARCHAR (32) COMMENT '户籍类型',
  `social_security_city_id` BIGINT COMMENT '参保城市id',
  `social_security_city_name` VARCHAR (32) COMMENT '参保城市',
  `pay_month` VARCHAR (8) DEFAULT NULL COMMENT '社保月份',
  `social_security_radix` DECIMAL (10, 2) COMMENT '社保基数',
  `social_security_sum` DECIMAL (10, 2) COMMENT '社保合计',
  `social_security_company_sum` DECIMAL (10, 2) COMMENT '社保企业合计',
  `social_security_employee_sum` DECIMAL (10, 2) COMMENT '社保个人合计',
  `accumulation_fund_city_id` BIGINT COMMENT '公积金城市id',
  `accumulation_fund_city_name` VARCHAR (32) COMMENT '公积金城市',
  `accumulation_fund_radix` DECIMAL (10, 2) COMMENT '公积金基数',
  `accumulation_fund_company_radix` DECIMAL (10, 2) COMMENT '公积金企业基数',
  `accumulation_fund_company_ratio` INT COMMENT '公积金企业比例万分之 eq:100=1%;1=0.01%',
  `accumulation_fund_employee_radix` DECIMAL (10, 2) COMMENT '公积金个人基数',
  `accumulation_fund_employee_ratio` INT COMMENT '公积金个人比例 万分之 eq:100=1%;1=0.01%',
  `accumulation_fund_sum` DECIMAL (10, 2) COMMENT '公积金合计',
  `accumulation_fund_company_sum` DECIMAL (10, 2) COMMENT '公积金企业合计',
  `accumulation_fund_employee_sum` DECIMAL (10, 2) COMMENT '公积金个人合计',
  `pension_company_radix` DECIMAL (10, 2) COMMENT '养老保险企业基数',
  `pension_company_ratio` INT COMMENT '养老保险企业比例万分之 eq:100=1%;1=0.01%',
  `pension_employee_radix` DECIMAL (10, 2) COMMENT '养老保险个人基数',
  `pension_employee_ratio` INT COMMENT '养老保险个人比例 万分之 eq:100=1%;1=0.01%',
  `pension_company_sum` DECIMAL (10, 2) COMMENT '养老保险企业合计',
  `pension_employee_sum` DECIMAL (10, 2) COMMENT '养老保险个人合计',
  `medical_company_radix` DECIMAL (10, 2) COMMENT '医疗保险企业基数',
  `medical_company_ratio` INT COMMENT '医疗保险企业比例万分之 eq:100=1%;1=0.01%',
  `medical_employee_radix` DECIMAL (10, 2) COMMENT '医疗保险个人基数',
  `medical_employee_ratio` INT COMMENT '医疗保险个人比例 万分之 eq:100=1%;1=0.01%',
  `medical_company_sum` DECIMAL (10, 2) COMMENT '医疗保险企业合计',
  `medical_employee_sum` DECIMAL (10, 2) COMMENT '医疗保险个人合计',
  `injury_company_radix` DECIMAL (10, 2) COMMENT '工伤保险企业基数',
  `injury_company_ratio` INT COMMENT '工伤保险企业比例万分之 eq:100=1%;1=0.01%',
  `injury_employee_radix` DECIMAL (10, 2) COMMENT '工伤保险个人基数',
  `injury_employee_ratio` INT COMMENT '工伤保险个人比例 万分之 eq:100=1%;1=0.01%',
  `injury_company_sum` DECIMAL (10, 2) COMMENT '工伤保险企业合计',
  `injury_employee_sum` DECIMAL (10, 2) COMMENT '工伤保险个人合计',
  `unemployment_company_radix` DECIMAL (10, 2) COMMENT '失业保险企业基数',
  `unemployment_company_ratio` INT COMMENT '失业保险企业比例万分之 eq:100=1%;1=0.01%',
  `unemployment_employee_radix` DECIMAL (10, 2) COMMENT '失业保险个人基数',
  `unemployment_employee_ratio` INT COMMENT '失业保险个人比例 万分之 eq:100=1%;1=0.01%',
  `unemployment_company_sum` DECIMAL (10, 2) COMMENT '失业保险企业合计',
  `unemployment_employee_sum` DECIMAL (10, 2) COMMENT '失业保险个人合计',
  `birth_company_radix` DECIMAL (10, 2) COMMENT '生育保险企业基数',
  `birth_company_ratio` INT COMMENT '生育保险企业比例万分之 eq:100=1%;1=0.01%',
  `birth_employee_radix` DECIMAL (10, 2) COMMENT '生育保险个人基数',
  `birth_employee_ratio` INT COMMENT '生育保险个人比例 万分之 eq:100=1%;1=0.01%',
  `birth_company_sum` DECIMAL (10, 2) COMMENT '生育保险企业合计',
  `birth_employee_sum` DECIMAL (10, 2) COMMENT '生育保险个人合计',
  `critical_illness_company_radix` DECIMAL (10, 2) COMMENT '大病保险企业基数',
  `critical_illness_company_ratio` INT COMMENT '大病保险企业比例万分之 eq:100=1%;1=0.01%',
  `critical_illness_employee_radix` DECIMAL (10, 2) COMMENT '大病保险个人基数',
  `critical_illness_employee_ratio` INT COMMENT '大病保险个人比例 万分之 eq:100=1%;1=0.01%',
  `critical_illness_company_sum` DECIMAL (10, 2) COMMENT '大病保险企业合计',
  `critical_illness_employee_sum` DECIMAL (10, 2) COMMENT '大病保险个人合计',
  `after_social_security_company_sum` DECIMAL (10, 2) COMMENT '补缴社保企业合计',
  `after_social_security_employee_sum` DECIMAL (10, 2) COMMENT '补缴社保个人合计',
  `after_pension_company_sum` DECIMAL (10, 2) COMMENT '补缴养老企业合计',
  `after_pension_employee_sum` DECIMAL (10, 2) COMMENT '补缴养老个人合计',
  `after_medical_company_sum` DECIMAL (10, 2) COMMENT '补缴医疗企业合计',
  `after_medical_employee_sum` DECIMAL (10, 2) COMMENT '补缴医疗个人合计',
  `after_injury_company_sum` DECIMAL (10, 2) COMMENT '补缴工伤企业合计',
  `after_injury_employee_sum` DECIMAL (10, 2) COMMENT '补缴工伤个人合计',
  `after_unemployment_company_sum` DECIMAL (10, 2) COMMENT '补缴失业企业合计',
  `after_unemployment_employee_sum` DECIMAL (10, 2) COMMENT '补缴失业个人合计',
  `after_birth_company_sum` DECIMAL (10, 2) COMMENT '补缴生育企业合计',
  `after_birth_employee_sum` DECIMAL (10, 2) COMMENT '补缴生育个人合计',
  `after_critical_illness_company_sum` DECIMAL (10, 2) COMMENT '补缴大病企业合计',
  `after_critical_illness_employee_sum` DECIMAL (10, 2) COMMENT '补缴大病个人合计',
  `disability_sum` DECIMAL (10, 2) COMMENT '残障金',
  `commercial_insurance` DECIMAL (10, 2) COMMENT '商业保险',
  `file_uid` BIGINT (20) COMMENT '归档人',
  `file_time` DATETIME COMMENT '归档时间',
  PRIMARY KEY (`id`),
  KEY `i_eh_user_detail_id` (`detail_id`),
  KEY `i_eh_owner_id` (`owner_id`)
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 ;

-- 社保报表
CREATE TABLE `eh_social_security_inout_report` (
  `id` BIGINT,
  `namespace_id` INT (11) DEFAULT '0',
  `organization_id` BIGINT,
  `user_id` BIGINT,
  `detail_id` BIGINT,
  `user_name` VARCHAR (128) COMMENT '姓名',
  `entry_date` DATE COMMENT '入职日期',
  `out_work_date` DATE COMMENT '离职日期',
  `contact_token` VARCHAR (128) DEFAULT NULL COMMENT '手机号',
  `id_number` VARCHAR (128) DEFAULT NULL COMMENT '身份证号',
  `degree` VARCHAR (64) DEFAULT NULL COMMENT '学历',
  `salary_card_bank` VARCHAR (64) DEFAULT NULL COMMENT '开户行',
  `salary_card_number` VARCHAR (128) DEFAULT NULL COMMENT '工资卡号',
  `dept_name` VARCHAR (128) DEFAULT NULL COMMENT '部门',
  `social_security_number` VARCHAR (128) DEFAULT NULL COMMENT '社保号',
  `provident_fund_number` VARCHAR (128) DEFAULT NULL COMMENT '公积金号',
  `household_type` VARCHAR (32) COMMENT '户籍类型',
  `social_security_city_id` BIGINT COMMENT '参保城市id',
  `social_security_city_name` VARCHAR (32) COMMENT '参保城市',
  `pay_month` VARCHAR (8) DEFAULT NULL COMMENT '社保月份',
  `social_security_radix` DECIMAL (10, 2) COMMENT '社保基数',
  `social_security_increase` DECIMAL (10, 2) COMMENT '社保增',
  `social_security_decrease` DECIMAL (10, 2) COMMENT '社保减',
  `social_security_after` DECIMAL (10, 2) COMMENT '社保补缴',
  `accumulation_fund_city_id` BIGINT COMMENT '公积金城市id',
  `accumulation_fund_city_name` VARCHAR (32) COMMENT '公积金城市',
  `accumulation_fund_radix` DECIMAL (10, 2) COMMENT '公积金基数',
  `accumulation_fund_increase` DECIMAL (10, 2) COMMENT '公积金增',
  `accumulation_fund_decrease` DECIMAL (10, 2) COMMENT '公积金减',
  `accumulation_fund_after` DECIMAL (10, 2) COMMENT '公积金补缴',
  `file_uid` BIGINT (20) COMMENT '归档人',
  `file_time` DATETIME COMMENT '归档时间',
  PRIMARY KEY (`id`),
  KEY `i_eh_user_detail_id` (`detail_id`),
  KEY `i_eh_owner_id` (`owner_id`)
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 ;

