use ehcore;


INSERT INTO `eh_punch_workday` (`id`, `date_status`, `date_tag`, `creator_uid`, `create_time`, `operator_uid`, `operate_time`) VALUES('1','0','2015-09-10',NULL,NULL,NULL,NULL);
INSERT INTO `eh_punch_workday` (`id`, `date_status`, `date_tag`, `creator_uid`, `create_time`, `operator_uid`, `operate_time`) VALUES('2','0','2015-10-10',NULL,NULL,NULL,NULL);
INSERT INTO `eh_punch_workday` (`id`, `date_status`, `date_tag`, `creator_uid`, `create_time`, `operator_uid`, `operate_time`) VALUES('3','1','2015-10-01',NULL,NULL,NULL,NULL);
INSERT INTO `eh_punch_workday` (`id`, `date_status`, `date_tag`, `creator_uid`, `create_time`, `operator_uid`, `operate_time`) VALUES('4','1','2015-10-02',NULL,NULL,NULL,NULL);
INSERT INTO `eh_punch_workday` (`id`, `date_status`, `date_tag`, `creator_uid`, `create_time`, `operator_uid`, `operate_time`) VALUES('5','1','2015-10-05',NULL,NULL,NULL,NULL);
INSERT INTO `eh_punch_workday` (`id`, `date_status`, `date_tag`, `creator_uid`, `create_time`, `operator_uid`, `operate_time`) VALUES('6','1','2015-10-06',NULL,NULL,NULL,NULL);
INSERT INTO `eh_punch_workday` (`id`, `date_status`, `date_tag`, `creator_uid`, `create_time`, `operator_uid`, `operate_time`) VALUES('7','1','2015-10-07',NULL,NULL,NULL,NULL);
INSERT INTO `eh_rental_rules` (`id`, `community_id`, `site_type`, `rental_start_time`, `rental_end_time`, `pay_start_time`, `pay_end_time`, `payment_ratio`, `refund_flag`, `contact_num`, `time_tag1`, `time_tag2`, `time_tag3`, `date_tag1`, `date_tag2`, `date_tag3`, `datetime_tag1`, `datetime_tag2`, `datetime_tag3`, `integral_tag1`, `integral_tag2`, `integral_tag3`, `integral_tag4`, `string_tag1`, `string_tag2`, `string_tag3`, `creator_uid`, `create_time`, `operator_uid`, `operate_time`) 
	VALUES('1','240111044331048623','MEETINGROOM','2592000000','172800000','1728000000','691200000','10','1','13530178444',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'100011','2015-10-30 11:29:32');
INSERT INTO `eh_rental_rules` (`id`, `community_id`, `site_type`, `rental_start_time`, `rental_end_time`, `pay_start_time`, `pay_end_time`, `payment_ratio`, `refund_flag`, `contact_num`, `time_tag1`, `time_tag2`, `time_tag3`, `date_tag1`, `date_tag2`, `date_tag3`, `datetime_tag1`, `datetime_tag2`, `datetime_tag3`, `integral_tag1`, `integral_tag2`, `integral_tag3`, `integral_tag4`, `string_tag1`, `string_tag2`, `string_tag3`, `creator_uid`, `create_time`, `operator_uid`, `operate_time`) 
	VALUES('2','240111044331048623','VIPPARKING','2592000000','172800000','1728000000','691200000','10','1','13530178444',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'100011','2015-10-30 11:29:32');
INSERT INTO `eh_rental_rules` (`id`, `community_id`, `site_type`, `rental_start_time`, `rental_end_time`, `pay_start_time`, `pay_end_time`, `payment_ratio`, `refund_flag`, `contact_num`, `time_tag1`, `time_tag2`, `time_tag3`, `date_tag1`, `date_tag2`, `date_tag3`, `datetime_tag1`, `datetime_tag2`, `datetime_tag3`, `integral_tag1`, `integral_tag2`, `integral_tag3`, `integral_tag4`, `string_tag1`, `string_tag2`, `string_tag3`, `creator_uid`, `create_time`, `operator_uid`, `operate_time`) 
	VALUES('3','240111044331048623','ELECSCREEN','2592000000','172800000','1728000000','691200000','10','1','13530178444',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'100011','2015-10-30 11:29:32');
INSERT INTO `eh_locale_strings`(`scope`, `code`,`locale`, `text`) VALUES( 'rental', '10001', 'zh_CN', '还没有到预定时间');
INSERT INTO `eh_locale_strings`(`scope`, `code`,`locale`, `text`) VALUES( 'rental', '10002', 'zh_CN', '已经过了预定时间');
INSERT INTO `eh_locale_strings`(`scope`, `code`,`locale`, `text`) VALUES( 'rental', '10003', 'zh_CN', '已经被预定了');
INSERT INTO `eh_locale_strings`(`scope`, `code`,`locale`, `text`) VALUES( 'rental', '10004', 'zh_CN', '场所数量不够');
INSERT INTO `eh_locale_strings`(`scope`, `code`,`locale`, `text`) VALUES( 'rental', '10005', 'zh_CN', '订单超时失效了');


INSERT INTO `eh_categories`(`id`, `parent_id`, `link_id`, `name`, `path`, `default_order`, `status`, `create_time`, `namespace_id`)
    VALUES(4201, 4, 0, '亲子与教育', '活动/亲子与教育', 0, 2, UTC_TIMESTAMP(), 1000000);
INSERT INTO `eh_categories`(`id`, `parent_id`, `link_id`, `name`, `path`, `default_order`, `status`, `create_time`, `namespace_id`)
    VALUES(4202, 4, 0, '运动与音乐', '活动/运动与音乐', 0, 2, UTC_TIMESTAMP(), 1000000);
INSERT INTO `eh_categories`(`id`, `parent_id`, `link_id`, `name`, `path`, `default_order`, `status`, `create_time`, `namespace_id`)
    VALUES(4203, 4, 0, '宠物会', '活动/宠物会', 0, 2, UTC_TIMESTAMP(), 1000000);
INSERT INTO `eh_categories`(`id`, `parent_id`, `link_id`, `name`, `path`, `default_order`, `status`, `create_time`, `namespace_id`)
    VALUES(4204, 4, 0, '美食与厨艺', '活动/美食与厨艺', 0, 2, UTC_TIMESTAMP(), 1000000);
INSERT INTO `eh_categories`(`id`, `parent_id`, `link_id`, `name`, `path`, `default_order`, `status`, `create_time`, `namespace_id`)
    VALUES(4205, 4, 0, '美容化妆', '活动/美容化妆', 0, 2, UTC_TIMESTAMP(), 1000000);
INSERT INTO `eh_categories`(`id`, `parent_id`, `link_id`, `name`, `path`, `default_order`, `status`, `create_time`, `namespace_id`)
    VALUES(4206, 4, 0, '家庭装饰', '活动/家庭装饰', 0, 2, UTC_TIMESTAMP(), 1000000);
INSERT INTO `eh_categories`(`id`, `parent_id`, `link_id`, `name`, `path`, `default_order`, `status`, `create_time`, `namespace_id`)
    VALUES(4207, 4, 0, '其他', '活动/其他', 1, 2, UTC_TIMESTAMP(), 1000000);
INSERT INTO `eh_categories`(`id`, `parent_id`, `link_id`, `name`, `path`, `default_order`, `status`, `create_time`, `namespace_id`)
    VALUES(4208, 4001, 0, '亲子', '活动/亲子与教育/亲子', 0, 2, UTC_TIMESTAMP(), 1000000);
INSERT INTO `eh_categories`(`id`, `parent_id`, `link_id`, `name`, `path`, `default_order`, `status`, `create_time`, `namespace_id`)
    VALUES(4209, 4001, 0, '教育', '活动/亲子与教育/教育', 0, 2, UTC_TIMESTAMP(), 1000000);	
INSERT INTO `eh_categories`(`id`, `parent_id`, `link_id`, `name`, `path`, `default_order`, `status`, `create_time`, `namespace_id`)
    VALUES(4210, 4002, 0, '运动', '活动/运动与音乐/运动', 0, 2, UTC_TIMESTAMP(), 1000000);
INSERT INTO `eh_categories`(`id`, `parent_id`, `link_id`, `name`, `path`, `default_order`, `status`, `create_time`, `namespace_id`)
    VALUES(4211, 4002, 0, '音乐', '活动/运动与音乐/音乐', 0, 2, UTC_TIMESTAMP(), 1000000);
INSERT INTO `eh_categories`(`id`, `parent_id`, `link_id`, `name`, `path`, `default_order`, `status`, `create_time`, `namespace_id`)
    VALUES(4213, 4, 0, '科技', '活动/科技', 0, 2, UTC_TIMESTAMP(), 1000000);
INSERT INTO `eh_categories`(`id`, `parent_id`, `link_id`, `name`, `path`, `default_order`, `status`, `create_time`, `namespace_id`)
    VALUES(4214, 4, 0, '论坛', '活动/论坛', 0, 2, UTC_TIMESTAMP(), 1000000);
INSERT INTO `eh_categories`(`id`, `parent_id`, `link_id`, `name`, `path`, `default_order`, `status`, `create_time`, `namespace_id`)
    VALUES(4215, 4, 0, '创客', '活动/创客', 0, 2, UTC_TIMESTAMP(), 1000000);
INSERT INTO `eh_categories`(`id`, `parent_id`, `link_id`, `name`, `path`, `default_order`, `status`, `create_time`, `namespace_id`)
    VALUES(4216, 4, 0, '项目', '活动/项目', 0, 2, UTC_TIMESTAMP(), 1000000);
INSERT INTO `eh_categories`(`id`, `parent_id`, `link_id`, `name`, `path`, `default_order`, `status`, `create_time`, `namespace_id`)
    VALUES(4217, 4, 0, '联谊', '活动/联谊', 0, 2, UTC_TIMESTAMP(), 1000000);
INSERT INTO `eh_categories`(`id`, `parent_id`, `link_id`, `name`, `path`, `default_order`, `status`, `create_time`, `namespace_id`)
    VALUES(4218, 4, 0, '沙龙', '活动/沙龙', 0, 2, UTC_TIMESTAMP(), 1000000);

INSERT INTO `eh_launch_pad_layouts`(id, namespace_id, name, layout_json, version_code, min_version_code, status, create_time) 
	VALUES (11, 1000000, 'ServiceMarketLayout', '{"versionCode":"2015111401","versionName":"3.0.0","layoutName":"ServiceMarketLayout","displayName":"服务市场","groups":[{"groupName":"","widget":"Banners","instanceConfig":{"itemGroup":"Default"},"style":"Default","defaultOrder":1,"separatorFlag":0,"separatorHeight":0},{"groupName":"","widget":"Navigator","instanceConfig":{"itemGroup":"GovAgencies"},"style":"Default","defaultOrder":2,"separatorFlag":1,"separatorHeight":21,"columnCount":4},{"groupName":"","widget":"Coupons","instanceConfig":{"itemGroup":"Coupons"},"style":"Default","defaultOrder":3,"separatorFlag":1,"separatorHeight":21},{"groupName":"商家服务","widget":"Navigator","instanceConfig":{"itemGroup":"Bizs"},"style":"Default","defaultOrder":5,"separatorFlag":0,"separatorHeight":0}]}', '2015111401', '2015061701', '2', '2015-06-24 16:09:30');
INSERT INTO `eh_launch_pad_layouts`(id, namespace_id, name, layout_json, version_code, min_version_code, status, create_time) 
	VALUES (12, 1000000, 'PmLayout', '{"versionCode":"2015111401","versionName":"3.0.0","displayName":"物业","layoutName":"PmLayout","groups":[{"groupName":"","widget":"Navigator","instanceConfig":{"itemGroup":"GaActions"},"style":"Default","defaultOrder":2,"separatorFlag":1,"separatorHeight":21,"columnCount":4},{"groupName":"","widget":"Posts","instanceConfig":{"itemGroup":"GaPosts"},"style":"Default","defaultOrder":3,"separatorFlag":0,"separatorHeight":0},{"groupName":"CallPhone","widget":"CallPhones","instanceConfig":{"itemGroup":"CallPhones","position":"bottom"},"style":"Default","defaultOrder":3,"separatorFlag":0,"separatorHeight":0}]}', '2015111401', '2015061701', '2', '2015-06-27 14:04:57');

INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) 
	VALUES(801, 1000000, 0, 0, 0, '/home','GovAgencies','园区入驻','园区入驻','cs://1/image/aW1hZ2UvTVRvNFlXSXdaRGRqTnpKaU56UmtZMll3WlRNeU1XUmxOekU0WXpNNU9HWmpZUQ','1','1','28',NULL,'0','0','1','1','','0',NULL,NULL,NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) 
	VALUES(802, 1000000, 0, 0, 0, '/home','GovAgencies','交流大厅','交流大厅','cs://1/image/aW1hZ2UvTVRwaE5HRTBNR1ZtTmpSa1lqVm1NbVJrWVRNNFlURXdZMlppTnpVNE1ESTRaQQ','1','1','15', '{"contentCategory":1010,"actionCategory":0,"entityTag":"USER","forumId":176520}','0','0','1','1','','0',NULL,NULL,NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) 
	VALUES(803, 1000000, 0, 0, 0, '/home','GovAgencies','服务联盟','服务联盟','cs://1/image/aW1hZ2UvTVRvM016RmpNelJtTURGbU9ETTJZVEJrTWprNE1qbGpZbU0xTTJZMFlqWTFNZw','1','1','33','{"type":2}','0','0','1','1','','0',NULL,NULL,NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) 
	VALUES(804, 1000000, 0, 0, 0, '/home','GovAgencies','创客空间','创客空间','cs://1/image/aW1hZ2UvTVRvd1kyUmxZakZsWW1Sa1lUVXpZakUwT1RJMU9XUm1PRFU0T1dRNVptSmxPQQ','1','1','32','{"type":1,"forumId":177000,"categoryId":4}','0','0','1','1','','0',NULL,NULL,NULL);

-- INSERT INTO `eh_launch_pad_items`(id,namespace_id,app_id,scope_code,scope_id,item_location,item_group,item_name,item_label,icon_uri,item_width,item_height,action_type,action_data,default_order,apply_policy,min_version,display_flag,display_layout,bgcolor,tag) 
--	VALUES (809, 1000000, 0, 0, 0, '/home', 'Coupons', '优惠券', '优惠券', 'cs://1/image/aW1hZ2UvTVRwaFl6RTRZMlppT1dOak1HRTVZVFpqWlRKaFltWmtNMk0xTmpoak1XUmpaQQ', 3, 1, 14, '{"url":"http://biz.zuolin.com/zl-ec?hideNavigationBar=1&sourceUrl=http%3A%2F%2Fbiz.zuolin.com%2Fweb%2Fapp%2Fuser%2Findex.html%23%2Fstore%2Fdetails%2Fpromotions%2F"}', 1, 0, 1, 1, '', 0,NULL);
-- INSERT INTO `eh_launch_pad_items`(id,namespace_id,app_id,scope_code,scope_id,item_location,item_group,item_name,item_label,icon_uri,item_width,item_height,action_type,action_data,default_order,apply_policy,min_version,display_flag,display_layout,bgcolor,tag) 
--	VALUES (810, 1000000, 0, 0, 0, '/home', 'Coupons', '市场动态', '市场动态', 'cs://1/image/aW1hZ2UvTVRwaU5HUTJNMkptTldVMk5qUTVZakk0TVdRNFl6WXlaak0zT1dNNU16TTRNdw', 5, 1, 14, '{"url":"http://biz.zuolin.com/zl-ec?hideNavigationBar=1&sourceUrl=http://biz.zuolin.com/web/app/user/index.html#/store/details/14454796321398120148#sign_suffix"}', 2, 0, 1, 1, '', 0,NULL);

-- for testserver30
DELETE FROM `eh_launch_pad_items` WHERE ID=809 OR ID=810;
INSERT INTO `eh_launch_pad_items`(id,namespace_id,app_id,scope_code,scope_id,item_location,item_group,item_name,item_label,icon_uri,item_width,item_height,action_type,action_data,default_order,apply_policy,min_version,display_flag,display_layout,bgcolor,tag) 
	VALUES (809, 1000000, 0, 0, 0, '/home', 'Coupons', '优惠券', '优惠券', 'cs://1/image/aW1hZ2UvTVRwaFl6RTRZMlppT1dOak1HRTVZVFpqWlRKaFltWmtNMk0xTmpoak1XUmpaQQ', 3, 1, 14, '{"url":"http://121.199.69.107:8080/zl-ec?hideNavigationBar=1&sourceUrl=http%3A%2F%2F121.199.69.107:8080%2Fweb%2Fapp%2Fuser%2Findex.html%23%2Fstore%2Fdetails%2Fpromotions%2F#sign_suffix"}', 1, 0, 1, 1, '', 0,NULL);
INSERT INTO `eh_launch_pad_items`(id,namespace_id,app_id,scope_code,scope_id,item_location,item_group,item_name,item_label,icon_uri,item_width,item_height,action_type,action_data,default_order,apply_policy,min_version,display_flag,display_layout,bgcolor,tag) 
	VALUES (810, 1000000, 0, 0, 0, '/home', 'Coupons', '市场动态', '市场动态', 'cs://1/image/aW1hZ2UvTVRwaU5HUTJNMkptTldVMk5qUTVZakk0TVdRNFl6WXlaak0zT1dNNU16TTRNdw', 5, 1, 14, '{"url":"http://121.199.69.107:8080/zl-ec?hideNavigationBar=1&sourceUrl=http%3A%2F%2F121.199.69.107:8080%2Fweb%2Fapp%2Fuser%2Findex.html%23%2Fstore%2Fdetails%2F14477439920233207899#sign_suffix"}', 2, 0, 1, 1, '', 0,NULL);
update eh_configurations set `value`='http://121.199.69.107:8080/zl-ec?hideNavigationBar=1&sourceUrl=http://121.199.69.107:8080' where name='prefix.url';
update eh_configurations set `value`='http://121.199.69.107:8081/imageService/' where name='business.image.url';
update eh_configurations set `value`='/web/app/shop/index.html%23/store/add#sign_suffix' where name='apply.shop.url';
update eh_configurations set `value`='%2fweb%2fapp%2fshop%2findex.html#sign_suffix' where name='manage.shop.url';
update eh_configurations set `value`='%2Fweb%2Fapp%2Fuser%2Findex.html%23%2Forder#sign_suffix' where name='user.order.url';
update eh_configurations set `value`='/web/app/user/index.html#/store/details/#sign_suffix' where name='business.detail.url';
update eh_configurations set `value`='%2Fweb%2Fapp%2Fuser%2Findex.html%23%2Froll#sign_suffix' where name='user.coupon.url';

	
-- INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) 
--	VALUES('811', 1000000, 0, 0, 0, '/home','Bizs','CAR_USE','用车','cs://1/image/aW1hZ2UvTVRwbE9UUmpOMkpsTVdaaU9UTTFNREUwTVdVek1qUXpaV0ppWlRobFpqbGtOZw','1','1','0',NULL,'0','0','1','1','','0',NULL,NULL,NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) 
	VALUES('812', 1000000, 0, 0, 0, '/home','Bizs','PUNCH','打卡','cs://1/image/aW1hZ2UvTVRwa01ESXpZalEwTkdZeE1ETTNPRGMyWkdVMU5UQXlOMlZrT1dKaE9UZzBNZw','1','1','23',NULL,'0','0','1','1','','0',NULL,NULL,NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) 
	VALUES('813', 1000000, 0, 0, 0, '/home','Bizs','CLUB','俱乐部','cs://1/image/aW1hZ2UvTVRwbE9XVTRNelUzT1dReU4ySXdNREJpT0RBeFpqQTNZakZqTUdZMk1EZzJNZw','1','1','31','{"forumId": 546}','0','0','1','1','','0',NULL,NULL,NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) 
	VALUES('814', 1000000, 0, 0, 0, '/home','Bizs','PM','物业报修','cs://1/image/aW1hZ2UvTVRveU5tSXhOMlV6TmpSak5qQmpOMlk1T1RVMFpqSTNPR0U1TXpNMll6QmlNdw',1,1,2, '{"itemLocation":"/home/Pm","layoutName":"PmLayout","title":"物业报修","entityTag":"PM"}', '0','0','1','1','','0',NULL,NULL,NULL);
-- INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) 
-- 	VALUES('815', 1000000, 0, 0, 0, '/home','Bizs','BUS','班车','cs://1/image/aW1hZ2UvTVRveFpHTmxNVEJsTldFeE5XVTFaV0l5TkdOaU4yRTFZVGhoT1dSbE1EUmxaUQ','1','1','0',NULL,'0','0','1','1','','0',NULL,NULL,NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) 
	VALUES('816', 1000000, 0, 0, 0, '/home','Bizs','ENTERPRISE','园区企业','cs://1/image/aW1hZ2UvTVRveVptTmpNMkU0WkdGbE1HUmhObUZrT0RZM1ltVmtZbUptTUdKbU4yUmtOdw','1','1','34','{"type":3}','0','0','1','1','','0',NULL,NULL,NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) 
	VALUES('817', 1000000, 0, 0, 0, '/home','Bizs','PUNCH','停车','cs://1/image/aW1hZ2UvTVRwbVkyRTVNR1pqTURJNE1qY3pOVEZqTlRFMVpUZzFZVEU1T0RSak16RTFZUQ','1','1','30',NULL,'0','0','1','1','','0',NULL,NULL,NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) 
	VALUES('818', 1000000, 0, 0, 0, '/home','Bizs','ELECSCREEN','电子屏','cs://1/image/aW1hZ2UvTVRwbU1tWTJZbUk1T0dNNFlXUmpNalEyTnpBMFlXSXhNakU0WVRVM016QTFPQQ','1','1','26',NULL,'0','0','1','1','','0',NULL,NULL,NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) 
	VALUES('819', 1000000, 0, 0, 0, '/home','Bizs','MEETINGROOM','会议室','cs://1/image/aW1hZ2UvTVRvME1Ua3hOVFEwTUdFME56Y3hNalkzWldZMk1HUmtNRFJoTXpRNU1EVm1aQQ','1','1','24',NULL,'0','0','1','1','','0',NULL,NULL,NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) 
	VALUES('820', 1000000, 0, 0, 0, '/home','Bizs','VIPPARKING','VIP车位','cs://1/image/aW1hZ2UvTVRwbFpESTJNbVl3WWpNMU9XTXdOVEZpTkdSaFkyRXlZMlk0WTJSbE1UZzVNUQ','1','1','25',NULL,'0','0','1','1','','0',NULL,NULL,NULL);
-- INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) 
--	VALUES('821', 1000000, 0, 0, 0, '/home','Bizs','VIDEO_MEETING','视频会议','cs://1/image/aW1hZ2UvTVRveE9HRmlOelV6TUdJNE9ERTRaalF6Wm1Nd05EWmxabVkyTkRjMlltVTNaZw','1','1','27',NULL,'0','0','1','1','','0',NULL,NULL,NULL);
-- INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) 
--	VALUES('822', 1000000, 0, 0, 0, '/home','Bizs','CARPOOL','拼车','cs://1/image/aW1hZ2UvTVRvME16a3lPVEJrTjJOaE5qTXhPV1prWVdKbE5EZzNOakEzWm1VM05tWTFPUQ','1','1','0',NULL,'0','0','1','1','','0',NULL,NULL,NULL);
	
INSERT INTO `eh_launch_pad_items`(id,namespace_id,app_id,scope_code,scope_id,item_location,item_group,item_name,item_label,icon_uri,item_width,item_height,action_type,action_data,default_order,apply_policy,min_version,display_flag,display_layout,bgcolor,tag) 
	VALUES (823, 1000000, 0, 0, 0, '/home/Pm', 'GaActions', 'ADVISE', '投诉建议', 'cs://1/image/aW1hZ2UvTVRwall6VTVOV1U0WkdRMk56aGxPRFV3TVRBMk5qVXlNVFkzWVRZek56aGpOdw', 1, 1, 19, '{"contentCategory":1006,"actionCategory":0,"forumId":1,"targetEntityTag":"PM","embedAppId":27,"visibleRegionType":0}', 0, 0, 1, 1, '', 0,NULL);
INSERT INTO `eh_launch_pad_items`(id,namespace_id,app_id,scope_code,scope_id,item_location,item_group,item_name,item_label,icon_uri,item_width,item_height,action_type,action_data,default_order,apply_policy,min_version,display_flag,display_layout,bgcolor,tag) 
	VALUES (824, 1000000, 0, 0, 0, '/home/Pm', 'GaActions', 'HELP', '咨询求助', 'cs://1/image/aW1hZ2UvTVRvM016VXdabVE0WW1SaVpqazJaVFJpWWpVeVpHTTBNMlEwT0RsaVpqQTRZZw', 1, 1, 19, '{"contentCategory":1005,"actionCategory":0,"forumId":1,"targetEntityTag":"PM","embedAppId":27,"visibleRegionType":0}', 0, 0, 1, 1, '', 0,NULL);
INSERT INTO `eh_launch_pad_items`(id,namespace_id,app_id,scope_code,scope_id,item_location,item_group,item_name,item_label,icon_uri,item_width,item_height,action_type,action_data,default_order,apply_policy,min_version,display_flag,display_layout,bgcolor,tag) 
	VALUES (825, 1000000, 0, 0, 0, '/home/Pm', 'GaActions', 'REPAIR', '报修', 'cs://1/image/aW1hZ2UvTVRveE1tWmtOMkprWXpaak5EWmpOV1JrTURkbU1EUTNNbUptTXpJek4yUmpaQQ', 1, 1, 19, '{"contentCategory":1004,"actionCategory":0,"forumId":1,"targetEntityTag":"PM","embedAppId":27,"visibleRegionType":0}', 0, 0, 1, 1, '', 0,NULL);
INSERT INTO `eh_launch_pad_items`(id,namespace_id,app_id,scope_code,scope_id,item_location,item_group,item_name,item_label,icon_uri,item_width,item_height,action_type,action_data,default_order,apply_policy,min_version,display_flag,display_layout,bgcolor,tag) 
	VALUES (826, 1000000, 0, 0, 0, '/home/Pm', 'GaActions', 'PAYMENT', '缴费', 'cs://1/image/aW1hZ2UvTVRvMk5qRmhPV1EyWlRRNFl6TTJPVFF5WmpNMllqSmtPVFJrT1RSbE1EQm1PUQ', 1, 1, 2, '{"itemLocation":"/home/Pm/Payment","layoutName":"PaymentLayout","title":"缴费"}', 0, 0, 1, 1, '', 0,NULL);
	
INSERT INTO `eh_banners` (`id`, `namespace_id`, `appId`, `banner_location`, `banner_group`, `scope_code`, `scope_id`, `name`, `vendor_tag`, `poster_path`, `action_type`, `action_data`, `start_time`, `end_time`, `status`, `order`, `creator_uid`, `create_time`, `delete_time`) 
	VALUES(11, 1000000, 0, '/home', 'Default', 0, 0, 'techpark', 'techpark','cs://1/image/aW1hZ2UvTVRveU0yTTFOR0k0WXpnNFpqWmlOekF5TnpFeU0ySTBOMkZtT0RZek9UWXhNQQ','13','{"url":"http://www.ssipc.com.cn/web/index.aspx"}',NULL,NULL,'2','1','0','2015-06-30 16:01:45',NULL);


insert into `eh_yellow_pages` (`id`, `parent_id`, `owner_type`, `owner_id`, `name`, `nick_name`, `type`, `address`, `contact`, `description`, `poster_uri`, `status`, `default_order`, `longitude`, `latitude`, `geohash`, `integral_tag1`, `integral_tag2`, `integral_tag3`, `integral_tag4`, `integral_tag5`, `string_tag1`, `string_tag2`, `string_tag3`, `string_tag4`, `string_tag5`, `creator_uid`, `create_time`) values('1','0','community','240111044331048623','创客空间','科技园创业孵化器','1','深圳市南山区科苑路金融科技大厦A座5楼','0755-86620293','科技园创业孵化器是由深圳科技工业园（集团）有限公司倾力打造的创新型专业孵化器，致力于打造一个创投对接平台和创业黄埔军校。政府为科技园集团授牌深圳市南山区股权投资基金集聚园、深圳市南山区互联网金融集聚园及深圳市南山区互联网金融产业园，这三大平台联合并共享优质资源，为入驻的有潜力的创业企业在平台、品牌、渠道、资源、资金上面给予帮助，助力其加速发展。 科技园创业孵化器精心选择优质的具备较强自主创新能力的初创型企业进入孵化器，不仅能为其提供经济高效的创意办公空间，更为入驻的创业企业提供捆绑式的成长服务，提供包括创业辅导、管理咨询、交流培训、项目推介、市场推广、人才引进等服务内容，促进企业的发展壮大。','cs://1/image/aW1hZ2UvTVRvNE9EazJNRGRpWm1OaFlqVTVaV1JtT1Rrd05tVm1OVE0xT1dOaE9ETXpPUQ','2',NULL,'113.95097','22.552217','',NULL,NULL,NULL,NULL,NULL,'苟丹','13686467512',NULL,NULL,NULL,NULL,NULL);
insert into `eh_yellow_pages` (`id`, `parent_id`, `owner_type`, `owner_id`, `name`, `nick_name`, `type`, `address`, `contact`, `description`, `poster_uri`, `status`, `default_order`, `longitude`, `latitude`, `geohash`, `integral_tag1`, `integral_tag2`, `integral_tag3`, `integral_tag4`, `integral_tag5`, `string_tag1`, `string_tag2`, `string_tag3`, `string_tag4`, `string_tag5`, `creator_uid`, `create_time`) values('2','0','community','240111044331048623','服务联盟','服务联盟首页','2','','0755-86620293','公共服务联盟旨在集聚社会优质服务资源，为园区广大企业提供专业、高效、有保障的服务，以帮助广大企业畅通信息渠道，提升企业管理，降低经营成本，增强市场竞争能力。服务类型包括项目融资对接、人才招聘和培训、信息化建设、管理咨询、知识产权管理、质量管理、外贸事务、法律事务、 物流服务、场地装修等。','cs://1/image/aW1hZ2UvTVRvMU56TXpOV0l3T1RKaFlqQTRNVFJpWmpSaVlUazFNall5WldRNVlUZ3dZUQ','2',NULL,NULL,NULL,'',NULL,NULL,NULL,NULL,NULL,'','','',NULL,NULL,NULL,NULL);
insert into `eh_yellow_pages` (`id`, `parent_id`, `owner_type`, `owner_id`, `name`, `nick_name`, `type`, `address`, `contact`, `description`, `poster_uri`, `status`, `default_order`, `longitude`, `latitude`, `geohash`, `integral_tag1`, `integral_tag2`, `integral_tag3`, `integral_tag4`, `integral_tag5`, `string_tag1`, `string_tag2`, `string_tag3`, `string_tag4`, `string_tag5`, `creator_uid`, `create_time`) values('3','0','community','240111044331048623','园区企业','园区企业','3','谁知道在哪','0755-86620293','园区企业没说明，直接用list','cs://1/image/aW1hZ2UvTVRvd01qUmpNV00wTkdaaVltWTNNemt3TXpOak9EZGlOMk15TldZd01qWTNNUQ','2',NULL,NULL,NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2015-11-20 15:00:45');
insert into `eh_yellow_pages` (`id`, `parent_id`, `owner_type`, `owner_id`, `name`, `nick_name`, `type`, `address`, `contact`, `description`, `poster_uri`, `status`, `default_order`, `longitude`, `latitude`, `geohash`, `integral_tag1`, `integral_tag2`, `integral_tag3`, `integral_tag4`, `integral_tag5`, `string_tag1`, `string_tag2`, `string_tag3`, `string_tag4`, `string_tag5`, `creator_uid`, `create_time`) values('5','2','community','240111044331048623','深圳市创卓企业管理顾问有限公司','','2','广东省深圳市南山区科技园科智西路25栋5层东','13509667165',' 深圳市卓越质量品牌研究院是中国首家以《卓越绩效评价准则》为研究对象的专业研究院，通过研究世界最先进企业的管理模式，寻求适合于中国企业的最优管理模式。','cs://1/image/aW1hZ2UvTVRvM01qRmtaalk0Wm1WaE9UVmxNR00wT0RNek5tVXpObVkyT0RZek56VXdZUQ','2',NULL,NULL,NULL,'',NULL,NULL,NULL,NULL,NULL,'','','管理顾问、企业管理培训、管理软件开发等',NULL,NULL,NULL,NULL);
insert into `eh_yellow_pages` (`id`, `parent_id`, `owner_type`, `owner_id`, `name`, `nick_name`, `type`, `address`, `contact`, `description`, `poster_uri`, `status`, `default_order`, `longitude`, `latitude`, `geohash`, `integral_tag1`, `integral_tag2`, `integral_tag3`, `integral_tag4`, `integral_tag5`, `string_tag1`, `string_tag2`, `string_tag3`, `string_tag4`, `string_tag5`, `creator_uid`, `create_time`) values('6','2','community','240111044331048623','上海联广认证有限公司深圳分公司','','2','深圳市南山区金融基地2栋10楼CD单元','82210420','最初于1998年在深圳建立代表处, 我们可以提供本地化的安全, EMC电磁兼容; 能效及RoHS的检测、发证和全球准入服务。我们可以服务的产品包括: 信息技术和视听设备、家电、灯饰、电动工具、开关、插头、插座等零部件;致力于为广大中国电器制造商提供进入全球市场的更高效、快捷的测试、认证和咨询服务。','cs://1/image/aW1hZ2UvTVRwaVptVmlOakkwT0dRd056UmlaalZoTURBM00yRmlaVEU1Tm1JeE5tVXpZZw','2',NULL,NULL,NULL,'',NULL,NULL,NULL,NULL,NULL,'','','产品国际认证、测试、认证服务',NULL,NULL,NULL,NULL);
insert into `eh_yellow_pages` (`id`, `parent_id`, `owner_type`, `owner_id`, `name`, `nick_name`, `type`, `address`, `contact`, `description`, `poster_uri`, `status`, `default_order`, `longitude`, `latitude`, `geohash`, `integral_tag1`, `integral_tag2`, `integral_tag3`, `integral_tag4`, `integral_tag5`, `string_tag1`, `string_tag2`, `string_tag3`, `string_tag4`, `string_tag5`, `creator_uid`, `create_time`) values('7','2','community','240111044331048623','众华会计师事务所（特殊普通合伙）深圳分所','','2','深圳市南山区科苑北路11号金融科技大厦A座9楼CD单元','13823321722','总部成立于1985年9月，众华会计师事务所为客提供全面优质的服务，包括审计、咨询、会计、税务、企业融资、企业重组等。','cs://1/image/aW1hZ2UvTVRwa056ZzBZV0ZsTTJVNFkyVTJabVV6WmpFMlkyRTNZakk0Wm1NeFpUUXpZZw','2',NULL,NULL,NULL,'',NULL,NULL,NULL,NULL,NULL,'','','证券期货、验证资本、资产评估、审计、会计、税务、咨询等',NULL,NULL,NULL,NULL);
insert into `eh_yellow_pages` (`id`, `parent_id`, `owner_type`, `owner_id`, `name`, `nick_name`, `type`, `address`, `contact`, `description`, `poster_uri`, `status`, `default_order`, `longitude`, `latitude`, `geohash`, `integral_tag1`, `integral_tag2`, `integral_tag3`, `integral_tag4`, `integral_tag5`, `string_tag1`, `string_tag2`, `string_tag3`, `string_tag4`, `string_tag5`, `creator_uid`, `create_time`) values('8','2','community','240111044331048623','网宿科技股份有限公司深圳分公司','','2','深圳市南山区科苑路6号科技园工业大厦4楼','13510086416','网宿科技股份有限公司深圳分公司，主要经营CDN加速、服务器托管服务器租用、专线接入、服务器，注册资本万元，公司是广东深圳其他网络设备、配件的知名企业，公司坚持诚信、互利，为客户提供最好的服务和最实惠的价格。','cs://1/image/aW1hZ2UvTVRvNU9EWTBPRGhsTkRnME1Ua3dOakk1TWprMk0yRmlZbVJpTldaaU1qRTBNQQ','2',NULL,NULL,NULL,'',NULL,NULL,NULL,NULL,NULL,'','','计算机软硬件的技术开发与咨询、信息系统集成、办公设备的销售',NULL,NULL,NULL,NULL);
insert into `eh_yellow_pages` (`id`, `parent_id`, `owner_type`, `owner_id`, `name`, `nick_name`, `type`, `address`, `contact`, `description`, `poster_uri`, `status`, `default_order`, `longitude`, `latitude`, `geohash`, `integral_tag1`, `integral_tag2`, `integral_tag3`, `integral_tag4`, `integral_tag5`, `string_tag1`, `string_tag2`, `string_tag3`, `string_tag4`, `string_tag5`, `creator_uid`, `create_time`) values('9','3','community','240111044331048623','深圳市江波龙电子有限公司','','3','深圳市高新技术产业园区科发路8号金融基地1栋8层','0755-86168848','深圳市江波龙电子有限公司成立于1999年，于2014年正式启用新的企业标志：longsys以应对全球化发展，总部位于深圳，在北京、上海、香港、台北、成都、英国、泰国等地设有分公司或办事处。主要从事消费类、嵌入式、无线、系统及金融安全等存储应用方案设计、创新型技术产品的研发和全球销售。   江波龙结合市场反馈信息，致力于为客户提供创新设计的存储应用产品服务。公司研发设计团队人数超过总人数50%，在产品研发上勇于创新，具备IC固件设计，晶圆封装的基板设计和开发移动客户端APP的能力，我们一直专注于存储周边产品的专业技术创新。   江波龙致力于为个人用户、行业用户、移动互联网、无线家庭提供存储应用产品及服务。','cs://1/image/aW1hZ2UvTVRwaU5qQTBNRE5oWldOak1EZGlaREF5WldZelpqVmlaVEZrTnpRME1tTXhNZw','2',NULL,'113.95353','22.54918','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2015-11-20 15:55:41');
insert into `eh_yellow_pages` (`id`, `parent_id`, `owner_type`, `owner_id`, `name`, `nick_name`, `type`, `address`, `contact`, `description`, `poster_uri`, `status`, `default_order`, `longitude`, `latitude`, `geohash`, `integral_tag1`, `integral_tag2`, `integral_tag3`, `integral_tag4`, `integral_tag5`, `string_tag1`, `string_tag2`, `string_tag3`, `string_tag4`, `string_tag5`, `creator_uid`, `create_time`) values('10','3','community','240111044331048623','深圳科技工业园（集团）有限公司','','3','深圳市南山区科技园科苑路6号','0755-86620123','深圳科技工业园是我国大陆第一个高新科技产业园，于1985年由深圳市政府和中国科学院共同创办。1991年，经国务院批准，深圳科技工业园成为首批国家级高新技术产业园区。  园区占地面积1.15平方公里，经过不断的开发建设，深圳科技工业园已成为投资环境优越、高新技术企业云集、科技开发实力雄厚、人才济济的科技园区。  公司成立以来转化了一批以中国科学院为主的高新技术成果，引进了大量国内外高新技术企业，在园区业形成了电子信息、新材料和生物工程制药等高新技术产业集群，是深圳市发展高新技术产业的重要基地。目前，园区拥有长城计算机、长城国际、珀金埃尔默、艾默生、康泰、科兴、长园新材等一批高新技术企业。公司现有全资，参股企业七家，主要集中在科技园区开发服务和高科技领域。其中，西甫、天鼎、意杰、金科等企业为高新技术企业，涉及新材料和新型电子元器件产业领域，主要产品包括改性工程塑料、有机硅材料及织物整理剂、铝合金辅助材料，有机和陶瓷PTC热敏材料、强磁材料、各类高精密金属膜电阻和晶体振荡器等。  近几年来，公司紧紧抓住深圳市产业结构调整的机遇，重点推进深圳市金融服务技术创新基地、深港动漫及网游产业孵化基地、深港生产力基地的建设工作。走出了一条金融产业、文化产业与科技产业相互融合、共同发展的新型道路，力将科技园打造成为具有高科技含量的金融创新区与文化创意园。科技园金融基地作为深圳市率先启用的金融基地于2009年3月投入使用，目前已吸引大批知名的金融企业、金融服务类企业入驻，品牌效应初步树立。  深圳科技工业园（集团）有限公司作为负责园区开发、管理、服务和高科技产业投资的集团公司，经营范围包括开发、经营及管理科技园区内的土地、物业；租赁自有物业；开发、经营高新技术产品、专利技术和非专利技术；管理园区内的工商企业；进出口贸易。目前股东为深业（集团）有限公司、北京中关村科学城建设股份有限公司、中科实业集团（控股）公司。','cs://1/image/aW1hZ2UvTVRwa09UTTRPVE13TWpjeVlqRTNNalE1TXpRell6TTBOVGN3TWpGbVl6a3lZZw','2',NULL,'113.950709','22.558767','',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2015-11-20 15:55:03');

insert into `eh_yellow_page_attachments` (`id`, `owner_id`, `content_type`, `content_uri`, `creator_uid`, `create_time`) values('1','1','image','cs://1/image/aW1hZ2UvTVRvNE9EazJNRGRpWm1OaFlqVTVaV1JtT1Rrd05tVm1OVE0xT1dOaE9ETXpPUQ','0','2015-11-20 16:59:19');
insert into `eh_yellow_page_attachments` (`id`, `owner_id`, `content_type`, `content_uri`, `creator_uid`, `create_time`) values('2','1','image','cs://1/image/aW1hZ2UvTVRvd1l6RmhZV0U1WmpnMU9XUmxNMkl6WlRFeE1UQTVZalUwTWprM1kyRTBaQQ','0','2015-11-20 16:59:19');
insert into `eh_yellow_page_attachments` (`id`, `owner_id`, `content_type`, `content_uri`, `creator_uid`, `create_time`) values('3','1','image','cs://1/image/aW1hZ2UvTVRwa1lqTXdORGhrWlRBNE1UZGxOVEEzTkdNME5tTXdOR1UxWldKa1pEa3dNdw','0','2015-11-20 16:59:19');
insert into `eh_yellow_page_attachments` (`id`, `owner_id`, `content_type`, `content_uri`, `creator_uid`, `create_time`) values('4','2','image','cs://1/image/aW1hZ2UvTVRvMU56TXpOV0l3T1RKaFlqQTRNVFJpWmpSaVlUazFNall5WldRNVlUZ3dZUQ','0','2015-11-20 17:01:41');
insert into `eh_yellow_page_attachments` (`id`, `owner_id`, `content_type`, `content_uri`, `creator_uid`, `create_time`) values('5','5','image','cs://1/image/aW1hZ2UvTVRvNU1UUTJObVF3TXpVMk9ESXdaVGN6WkROaU5UZGhNR1l6TXpnNFptVTFOUQ','0','2015-11-20 09:40:16');
insert into `eh_yellow_page_attachments` (`id`, `owner_id`, `content_type`, `content_uri`, `creator_uid`, `create_time`) values('6','6','image','cs://1/image/aW1hZ2UvTVRvNE5UVTBNakUzTXpSbVpUSTJOemcyTUdaa1pUVTRZalZsTW1Sak9UQTNZdw','0','2015-11-20 09:43:32');
insert into `eh_yellow_page_attachments` (`id`, `owner_id`, `content_type`, `content_uri`, `creator_uid`, `create_time`) values('7','7','image','cs://1/image/aW1hZ2UvTVRvd05UZzNNV1prTVRNelpqWmxZekE1TldRNU9Ea3dZVFU0TURoaFl6YzNOdw','0','2015-11-20 09:44:46');
insert into `eh_yellow_page_attachments` (`id`, `owner_id`, `content_type`, `content_uri`, `creator_uid`, `create_time`) values('8','8','image','cs://1/image/aW1hZ2UvTVRveU9XVmtZVGcyTW1Ga04yWTRZVGd6WkRBMVpqUmxZbUZoWlRaa01EaG1ZZw','0','2015-11-20 09:48:02');
insert into `eh_yellow_page_attachments` (`id`, `owner_id`, `content_type`, `content_uri`, `creator_uid`, `create_time`) values('9','9','image','cs://1/image/aW1hZ2UvTVRveU9UWTFOVFZpTXpSbE1ETTROV1E0TVdFeE9XWXpZall3TldSbU5tTTNOUQ','0','2015-11-20 09:40:16');
insert into `eh_yellow_page_attachments` (`id`, `owner_id`, `content_type`, `content_uri`, `creator_uid`, `create_time`) values('10','10','image','cs://1/image/aW1hZ2UvTVRwbFpHSmlabUV3TVdGa1lqWmhNMkkzT0dZeE5UVXhNR0kyTkRnd04yUXhZZw','0','2015-11-20 09:40:16');

