use ehcore;

insert into `eh_punch_workday` (`id`, `date_status`, `date_tag`, `creator_uid`, `create_time`, `operator_uid`, `operate_time`) values('1','0','2015-09-10',NULL,NULL,NULL,NULL);
insert into `eh_punch_workday` (`id`, `date_status`, `date_tag`, `creator_uid`, `create_time`, `operator_uid`, `operate_time`) values('2','0','2015-10-10',NULL,NULL,NULL,NULL);
insert into `eh_punch_workday` (`id`, `date_status`, `date_tag`, `creator_uid`, `create_time`, `operator_uid`, `operate_time`) values('3','1','2015-10-01',NULL,NULL,NULL,NULL);
insert into `eh_punch_workday` (`id`, `date_status`, `date_tag`, `creator_uid`, `create_time`, `operator_uid`, `operate_time`) values('4','1','2015-10-02',NULL,NULL,NULL,NULL);
insert into `eh_punch_workday` (`id`, `date_status`, `date_tag`, `creator_uid`, `create_time`, `operator_uid`, `operate_time`) values('5','1','2015-10-05',NULL,NULL,NULL,NULL);
insert into `eh_punch_workday` (`id`, `date_status`, `date_tag`, `creator_uid`, `create_time`, `operator_uid`, `operate_time`) values('6','1','2015-10-06',NULL,NULL,NULL,NULL);
insert into `eh_punch_workday` (`id`, `date_status`, `date_tag`, `creator_uid`, `create_time`, `operator_uid`, `operate_time`) values('7','1','2015-10-07',NULL,NULL,NULL,NULL);
INSERT INTO `eh_rental_rules` (`id`, `community_id`, `site_type`, `rental_start_time`, `rental_end_time`, `pay_start_time`, `pay_end_time`, `payment_ratio`, `refund_flag`, `contact_num`, `time_tag1`, `time_tag2`, `time_tag3`, `date_tag1`, `date_tag2`, `date_tag3`, `datetime_tag1`, `datetime_tag2`, `datetime_tag3`, `integral_tag1`, `integral_tag2`, `integral_tag3`, `integral_tag4`, `string_tag1`, `string_tag2`, `string_tag3`, `creator_uid`, `create_time`, `operator_uid`, `operate_time`) VALUES('1','240111044331046562','MEETINGROOM','2592000000','172800000','1728000000','691200000','10','1','13530178444',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'100011','2015-10-30 11:29:32');
INSERT INTO `eh_rental_rules` (`id`, `community_id`, `site_type`, `rental_start_time`, `rental_end_time`, `pay_start_time`, `pay_end_time`, `payment_ratio`, `refund_flag`, `contact_num`, `time_tag1`, `time_tag2`, `time_tag3`, `date_tag1`, `date_tag2`, `date_tag3`, `datetime_tag1`, `datetime_tag2`, `datetime_tag3`, `integral_tag1`, `integral_tag2`, `integral_tag3`, `integral_tag4`, `string_tag1`, `string_tag2`, `string_tag3`, `creator_uid`, `create_time`, `operator_uid`, `operate_time`) VALUES('2','240111044331046562','VIPPARKING','2592000000','172800000','1728000000','691200000','10','1','13530178444',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'100011','2015-10-30 11:29:32');
INSERT INTO `eh_rental_rules` (`id`, `community_id`, `site_type`, `rental_start_time`, `rental_end_time`, `pay_start_time`, `pay_end_time`, `payment_ratio`, `refund_flag`, `contact_num`, `time_tag1`, `time_tag2`, `time_tag3`, `date_tag1`, `date_tag2`, `date_tag3`, `datetime_tag1`, `datetime_tag2`, `datetime_tag3`, `integral_tag1`, `integral_tag2`, `integral_tag3`, `integral_tag4`, `string_tag1`, `string_tag2`, `string_tag3`, `creator_uid`, `create_time`, `operator_uid`, `operate_time`) VALUES('3','240111044331046562','ELECSCREEN','2592000000','172800000','1728000000','691200000','10','1','13530178444',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'100011','2015-10-30 11:29:32');
INSERT INTO `eh_locale_strings`(`scope`, `code`,`locale`, `text`) VALUES( 'rental', '10001', 'zh_CN', '还没有到预定时间');
INSERT INTO `eh_locale_strings`(`scope`, `code`,`locale`, `text`) VALUES( 'rental', '10002', 'zh_CN', '已经过了预定时间');
INSERT INTO `eh_locale_strings`(`scope`, `code`,`locale`, `text`) VALUES( 'rental', '10003', 'zh_CN', '已经被预定了');
INSERT INTO `eh_locale_strings`(`scope`, `code`,`locale`, `text`) VALUES( 'rental', '10004', 'zh_CN', '场所数量不够');
INSERT INTO `eh_locale_strings`(`scope`, `code`,`locale`, `text`) VALUES( 'rental', '10005', 'zh_CN', '订单超时失效了');

INSERT INTO `eh_launch_pad_layouts`(id, namespace_id, name, layout_json, version_code, min_version_code, status, create_time, site_uri) 
	VALUES ('11', '0', 'ServiceMarketLayout', '{"versionCode":"2015111401","versionName":"3.0.0","layoutName":"ServiceMarketLayout","displayName":"服务市场","groups":[{"groupName":"","widget":"Banners","instanceConfig":{"itemGroup":"Default"},"style":"Default","defaultOrder":1,"separatorFlag":0,"separatorHeight":0},{"groupName":"","widget":"Navigator","instanceConfig":{"itemGroup":"GovAgencies"},"style":"Default","defaultOrder":2,"separatorFlag":1,"separatorHeight":21,"columnCount":4},{"groupName":"","widget":"Coupons","instanceConfig":{"itemGroup":"Coupons"},"style":"Default","defaultOrder":3,"separatorFlag":1,"separatorHeight":21},{"groupName":"商家服务","widget":"Navigator","instanceConfig":{"itemGroup":"Bizs"},"style":"Default","defaultOrder":5,"separatorFlag":0,"separatorHeight":0}]}', '2015111401', '2015061701', '2', '2015-06-24 16:09:30', 'http://zuolin.com?partnerId=1000000');
INSERT INTO `eh_launch_pad_layouts`(id, namespace_id, name, layout_json, version_code, min_version_code, status, create_time, site_uri) 
	VALUES ('12', '0', 'PmLayout', '{"versionCode":"2015111401","versionName":"3.0.0","displayName":"物业","layoutName":"PmLayout","groups":[{"groupName":"","widget":"Navigator","instanceConfig":{"itemGroup":"GaActions"},"style":"Default","defaultOrder":2,"separatorFlag":1,"separatorHeight":21,"columnCount":4},{"groupName":"","widget":"Posts","instanceConfig":{"itemGroup":"GaPosts"},"style":"Default","defaultOrder":3,"separatorFlag":0,"separatorHeight":0},{"groupName":"CallPhone","widget":"CallPhones","instanceConfig":{"itemGroup":"CallPhones","position":"bottom"},"style":"Default","defaultOrder":3,"separatorFlag":0,"separatorHeight":0}]}', '2015111401', '2015061701', '2', '2015-06-27 14:04:57', 'http://zuolin.com?partnerId=1000000');

INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, site_uri) 
	VALUES('701','0','0','1','240111044331046562','/home','GovAgencies','园区入驻','园区入驻','cs://1/image/aW1hZ2UvTVRvNFlXSXdaRGRqTnpKaU56UmtZMll3WlRNeU1XUmxOekU0WXpNNU9HWmpZUQ','1','1','28',NULL,'0','0','1','1','','0',NULL,NULL,NULL, 'http://zuolin.com?partnerId=1000000');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, site_uri) 
	VALUES('702','0','0','1','240111044331046562','/home','GovAgencies','交流大厅','交流大厅','cs://1/image/aW1hZ2UvTVRwaE5HRTBNR1ZtTmpSa1lqVm1NbVJrWVRNNFlURXdZMlppTnpVNE1ESTRaQQ','1','1','29',NULL,'0','0','1','1','','0',NULL,NULL,NULL, 'http://zuolin.com?partnerId=1000000');
insert into `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) values('703','0','0','1','240111044331046562','/home','GovAgencies','服务联盟','服务联盟','cs://1/image/aW1hZ2UvTVRvM016RmpNelJtTURGbU9ETTJZVEJrTWprNE1qbGpZbU0xTTJZMFlqWTFNZw','1','1','33','{\"id\":\"2\",\"ownerType\":\"community\",\"ownerId\":\"240111044331046562\",\"type\":\"2\"}','0','0','1','1','','0',NULL,NULL,NULL);
insert into `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) values('704','0','0','1','240111044331046562','/home','GovAgencies','创客空间','创客空间','cs://1/image/aW1hZ2UvTVRvd1kyUmxZakZsWW1Sa1lUVXpZakUwT1RJMU9XUm1PRFU0T1dRNVptSmxPQQ','1','1','32','{\"id\":\"1\",\"ownerType\":\"community\",\"ownerId\":\"240111044331046562\",\"type\":\"1\"}','0','0','1','1','','0',NULL,NULL,NULL);

-- INSERT INTO `eh_launch_pad_items`(id,namespace_id,app_id,scope_code,scope_id,item_location,item_group,item_name,item_label,icon_uri,item_width,item_height,action_type,action_data,default_order,apply_policy,min_version,display_flag,display_layout,bgcolor,tag, site_uri) 
--	VALUES (709, 0, 0, 0, 0, '/home', 'Coupons', '优惠券', '优惠券', 'cs://1/image/aW1hZ2UvTVRwaFl6RTRZMlppT1dOak1HRTVZVFpqWlRKaFltWmtNMk0xTmpoak1XUmpaQQ', 3, 1, 14, '{"url":"http://biz.zuolin.com/zl-ec?hideNavigationBar=1&sourceUrl=http%3A%2F%2Fbiz.zuolin.com%2Fweb%2Fapp%2Fuser%2Findex.html%23%2Fstore%2Fdetails%2Fpromotions%2F"}', 1, 0, 1, 1, '', 0,NULL, 'http://zuolin.com?partnerId=1000000');
-- INSERT INTO `eh_launch_pad_items`(id,namespace_id,app_id,scope_code,scope_id,item_location,item_group,item_name,item_label,icon_uri,item_width,item_height,action_type,action_data,default_order,apply_policy,min_version,display_flag,display_layout,bgcolor,tag, site_uri) 
--	VALUES (710, 0, 0, 0, 0, '/home', 'Coupons', '市场动态', '市场动态', 'cs://1/image/aW1hZ2UvTVRwaU5HUTJNMkptTldVMk5qUTVZakk0TVdRNFl6WXlaak0zT1dNNU16TTRNdw', 5, 1, 14, '{"url":"http://biz.zuolin.com/zl-ec?hideNavigationBar=1&sourceUrl=http://biz.zuolin.com/web/app/user/index.html#/store/details/14454796321398120148#sign_suffix"}', 2, 0, 1, 1, '', 0,NULL, 'http://zuolin.com?partnerId=1000000');

-- for testserver30
DELETE FROM `eh_launch_pad_items` WHERE ID=709 OR ID=710;
INSERT INTO `eh_launch_pad_items`(id,namespace_id,app_id,scope_code,scope_id,item_location,item_group,item_name,item_label,icon_uri,item_width,item_height,action_type,action_data,default_order,apply_policy,min_version,display_flag,display_layout,bgcolor,tag, site_uri) 
	VALUES (709, 0, 0, 0, 0, '/home', 'Coupons', '优惠券', '优惠券', 'cs://1/image/aW1hZ2UvTVRwaFl6RTRZMlppT1dOak1HRTVZVFpqWlRKaFltWmtNMk0xTmpoak1XUmpaQQ', 3, 1, 14, '{"url":"http://121.199.69.107:8080/zl-ec?hideNavigationBar=1&sourceUrl=http%3A%2F%2F121.199.69.107:8080%2Fweb%2Fapp%2Fuser%2Findex.html%23%2Fstore%2Fdetails%2Fpromotions%2F#sign_suffix"}', 1, 0, 1, 1, '', 0,NULL, 'http://zuolin.com?partnerId=1000000');
INSERT INTO `eh_launch_pad_items`(id,namespace_id,app_id,scope_code,scope_id,item_location,item_group,item_name,item_label,icon_uri,item_width,item_height,action_type,action_data,default_order,apply_policy,min_version,display_flag,display_layout,bgcolor,tag, site_uri) 
	VALUES (710, 0, 0, 0, 0, '/home', 'Coupons', '市场动态', '市场动态', 'cs://1/image/aW1hZ2UvTVRwaU5HUTJNMkptTldVMk5qUTVZakk0TVdRNFl6WXlaak0zT1dNNU16TTRNdw', 5, 1, 14, '{"url":"http://121.199.69.107:8080/zl-ec?hideNavigationBar=1&sourceUrl=http%3A%2F%2F121.199.69.107:8080%2Fweb%2Fapp%2Fuser%2Findex.html%23%2Fstore%2Fdetails%2F14477439920233207899#sign_suffix"}', 2, 0, 1, 1, '', 0,NULL, 'http://zuolin.com?partnerId=1000000');
update eh_configurations set `value`='http://121.199.69.107:8080/zl-ec?hideNavigationBar=1&sourceUrl=http://121.199.69.107:8080' where name='prefix.url';
update eh_configurations set `value`='http://121.199.69.107:8081/imageService/' where name='business.image.url';
update eh_configurations set `value`='/web/app/shop/index.html%23/store/add#sign_suffix' where name='apply.shop.url';
update eh_configurations set `value`='%2fweb%2fapp%2fshop%2findex.html#sign_suffix' where name='manage.shop.url';
update eh_configurations set `value`='%2Fweb%2Fapp%2Fuser%2Findex.html%23%2Forder#sign_suffix' where name='user.order.url';
update eh_configurations set `value`='/web/app/user/index.html#/store/details/#sign_suffix' where name='business.detail.url';
update eh_configurations set `value`='%2Fweb%2Fapp%2Fuser%2Findex.html%23%2Froll#sign_suffix' where name='user.coupon.url';

	
-- INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, site_uri) 
--	VALUES('711','0','0','1','240111044331046562','/home','Bizs','CAR_USE','用车','cs://1/image/aW1hZ2UvTVRwbE9UUmpOMkpsTVdaaU9UTTFNREUwTVdVek1qUXpaV0ppWlRobFpqbGtOZw','1','1','0',NULL,'0','0','1','1','','0',NULL,NULL,NULL, 'http://zuolin.com?partnerId=1000000');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, site_uri) 
	VALUES('712','0','0','1','240111044331046562','/home','Bizs','PUNCH','打卡','cs://1/image/aW1hZ2UvTVRwa01ESXpZalEwTkdZeE1ETTNPRGMyWkdVMU5UQXlOMlZrT1dKaE9UZzBNZw','1','1','23',NULL,'0','0','1','1','','0',NULL,NULL,NULL, 'http://zuolin.com?partnerId=1000000');
-- INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, site_uri) 
--	VALUES('713','0','0','1','240111044331046562','/home','Bizs','CLUB','俱乐部','cs://1/image/aW1hZ2UvTVRwbE9XVTRNelUzT1dReU4ySXdNREJpT0RBeFpqQTNZakZqTUdZMk1EZzJNZw','1','1','31','{"forumId": 546}','0','0','1','1','','0',NULL,NULL,NULL, 'http://zuolin.com?partnerId=1000000');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, site_uri) 
	VALUES('714','0','0','1','240111044331046562','/home','Bizs','PM','物业报修','cs://1/image/aW1hZ2UvTVRveU5tSXhOMlV6TmpSak5qQmpOMlk1T1RVMFpqSTNPR0U1TXpNMll6QmlNdw',1,1,2, '{"itemLocation":"/home/Pm","layoutName":"PmLayout","title":"物业报修","entityTag":"PM"}', '0','0','1','1','','0',NULL,NULL,NULL, 'http://zuolin.com?partnerId=1000000');
-- INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, site_uri) 
-- 	VALUES('715','0','0','1','240111044331046562','/home','Bizs','BUS','班车','cs://1/image/aW1hZ2UvTVRveFpHTmxNVEJsTldFeE5XVTFaV0l5TkdOaU4yRTFZVGhoT1dSbE1EUmxaUQ','1','1','0',NULL,'0','0','1','1','','0',NULL,NULL,NULL, 'http://zuolin.com?partnerId=1000000');
insert into `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`) values('716','0','0','1','240111044331046562','/home','Bizs','ENTERPRISE','园区企业','cs://1/image/aW1hZ2UvTVRwaE1ETXhaREEyTXpRd05XSTFabVU1WmpFMk1qSXpZakZpWVRWa09EVm1PUQ','1','1','34','{\"ownerType\":\"community\",\"ownerId\":\"240111044331046562\",\"type\":\"3\"}','0','0','1','1','','0',NULL,NULL,NULL);
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, site_uri) 
	VALUES('717','0','0','1','240111044331046562','/home','Bizs','PUNCH','停车','cs://1/image/aW1hZ2UvTVRwbVkyRTVNR1pqTURJNE1qY3pOVEZqTlRFMVpUZzFZVEU1T0RSak16RTFZUQ','1','1','30',NULL,'0','0','1','1','','0',NULL,NULL,NULL, 'http://zuolin.com?partnerId=1000000');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, site_uri) 
	VALUES('718','0','0','1','240111044331046562','/home','Bizs','ELECSCREEN','电子屏','cs://1/image/aW1hZ2UvTVRwbU1tWTJZbUk1T0dNNFlXUmpNalEyTnpBMFlXSXhNakU0WVRVM016QTFPQQ','1','1','26',NULL,'0','0','1','1','','0',NULL,NULL,NULL, 'http://zuolin.com?partnerId=1000000');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, site_uri) 
	VALUES('719','0','0','1','240111044331046562','/home','Bizs','MEETINGROOM','会议室','cs://1/image/aW1hZ2UvTVRvME1Ua3hOVFEwTUdFME56Y3hNalkzWldZMk1HUmtNRFJoTXpRNU1EVm1aQQ','1','1','24',NULL,'0','0','1','1','','0',NULL,NULL,NULL, 'http://zuolin.com?partnerId=1000000');
INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, site_uri) 
	VALUES('720','0','0','1','240111044331046562','/home','Bizs','VIPPARKING','VIP车位','cs://1/image/aW1hZ2UvTVRwbFpESTJNbVl3WWpNMU9XTXdOVEZpTkdSaFkyRXlZMlk0WTJSbE1UZzVNUQ','1','1','25',NULL,'0','0','1','1','','0',NULL,NULL,NULL, 'http://zuolin.com?partnerId=1000000');
-- INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, site_uri) 
--	VALUES('721','0','0','1','240111044331046562','/home','Bizs','VIDEO_MEETING','视频会议','cs://1/image/aW1hZ2UvTVRveE9HRmlOelV6TUdJNE9ERTRaalF6Wm1Nd05EWmxabVkyTkRjMlltVTNaZw','1','1','27',NULL,'0','0','1','1','','0',NULL,NULL,NULL, 'http://zuolin.com?partnerId=1000000');
-- INSERT INTO `eh_launch_pad_items` (`id`, `namespace_id`, `app_id`, `scope_code`, `scope_id`, `item_location`, `item_group`, `item_name`, `item_label`, `icon_uri`, `item_width`, `item_height`, `action_type`, `action_data`, `default_order`, `apply_policy`, `min_version`, `display_flag`, `display_layout`, `bgcolor`, `tag`, `target_type`, `target_id`, site_uri) 
--	VALUES('722','0','0','1','240111044331046562','/home','Bizs','CARPOOL','拼车','cs://1/image/aW1hZ2UvTVRvME16a3lPVEJrTjJOaE5qTXhPV1prWVdKbE5EZzNOakEzWm1VM05tWTFPUQ','1','1','0',NULL,'0','0','1','1','','0',NULL,NULL,NULL, 'http://zuolin.com?partnerId=1000000');
	
INSERT INTO `eh_launch_pad_items`(id,namespace_id,app_id,scope_code,scope_id,item_location,item_group,item_name,item_label,icon_uri,item_width,item_height,action_type,action_data,default_order,apply_policy,min_version,display_flag,display_layout,bgcolor,tag, site_uri) 
	VALUES (723, 0, 0, 1, 240111044331046562, '/home/Pm', 'GaActions', 'ADVISE', '投诉建议', 'cs://1/image/aW1hZ2UvTVRwall6VTVOV1U0WkdRMk56aGxPRFV3TVRBMk5qVXlNVFkzWVRZek56aGpOdw', 1, 1, 19, '{"contentCategory":1006,"actionCategory":0,"forumId":1,"targetEntityTag":"PM","embedAppId":27,"visibleRegionType":0}', 0, 0, 1, 1, '', 0,NULL, 'http://zuolin.com?partnerId=1000000');
INSERT INTO `eh_launch_pad_items`(id,namespace_id,app_id,scope_code,scope_id,item_location,item_group,item_name,item_label,icon_uri,item_width,item_height,action_type,action_data,default_order,apply_policy,min_version,display_flag,display_layout,bgcolor,tag, site_uri) 
	VALUES (724, 0, 0, 1, 240111044331046562, '/home/Pm', 'GaActions', 'HELP', '咨询求助', 'cs://1/image/aW1hZ2UvTVRvM016VXdabVE0WW1SaVpqazJaVFJpWWpVeVpHTTBNMlEwT0RsaVpqQTRZZw', 1, 1, 19, '{"contentCategory":1005,"actionCategory":0,"forumId":1,"targetEntityTag":"PM","embedAppId":27,"visibleRegionType":0}', 0, 0, 1, 1, '', 0,NULL, 'http://zuolin.com?partnerId=1000000');
INSERT INTO `eh_launch_pad_items`(id,namespace_id,app_id,scope_code,scope_id,item_location,item_group,item_name,item_label,icon_uri,item_width,item_height,action_type,action_data,default_order,apply_policy,min_version,display_flag,display_layout,bgcolor,tag, site_uri) 
	VALUES (725, 0, 0, 1, 240111044331046562, '/home/Pm', 'GaActions', 'REPAIR', '报修', 'cs://1/image/aW1hZ2UvTVRveE1tWmtOMkprWXpaak5EWmpOV1JrTURkbU1EUTNNbUptTXpJek4yUmpaQQ', 1, 1, 19, '{"contentCategory":1004,"actionCategory":0,"forumId":1,"targetEntityTag":"PM","embedAppId":27,"visibleRegionType":0}', 0, 0, 1, 1, '', 0,NULL, 'http://zuolin.com?partnerId=1000000');
INSERT INTO `eh_launch_pad_items`(id,namespace_id,app_id,scope_code,scope_id,item_location,item_group,item_name,item_label,icon_uri,item_width,item_height,action_type,action_data,default_order,apply_policy,min_version,display_flag,display_layout,bgcolor,tag, site_uri) 
	VALUES (726, 0, 0, 1, 240111044331046562, '/home/Pm', 'GaActions', 'PAYMENT', '缴费', 'cs://1/image/aW1hZ2UvTVRvMk5qRmhPV1EyWlRRNFl6TTJPVFF5WmpNMllqSmtPVFJrT1RSbE1EQm1PUQ', 1, 1, 2, '{"itemLocation":"/home/Pm/Payment","layoutName":"PaymentLayout","title":"缴费"}', 0, 0, 1, 1, '', 0,NULL, 'http://zuolin.com?partnerId=1000000');
	
INSERT INTO `eh_banners` (`id`, `namespace_id`, `appId`, `banner_location`, `banner_group`, `scope_code`, `scope_id`, `name`, `vendor_tag`, `poster_path`, `action_type`, `action_data`, `start_time`, `end_time`, `status`, `order`, `creator_uid`, `create_time`, `delete_time`, `site_uri`) 
	VALUES('11','0','0','/home','GovAgencies','1','240111044331046562','techpark','techpark','cs://1/image/aW1hZ2UvTVRveU0yTTFOR0k0WXpnNFpqWmlOekF5TnpFeU0ySTBOMkZtT0RZek9UWXhNQQ','13','{"url":"http://www.ssipc.com.cn/web/index.aspx"}',NULL,NULL,'2','1','0','2015-06-30 16:01:45',NULL, 'http://zuolin.com?partnerId=1000000');


insert into `eh_yellow_pages` (`id`, `parent_id`, `owner_type`, `owner_id`, `name`, `nick_name`, `type`, `address`, `contact`, `description`, `poster_uri`, `status`, `default_order`, `longitude`, `latitude`, `geohash`, `integral_tag1`, `integral_tag2`, `integral_tag3`, `integral_tag4`, `integral_tag5`, `string_tag1`, `string_tag2`, `string_tag3`, `string_tag4`, `string_tag5`, `creator_uid`, `create_time`) values('1','0','community','240111044331046562','创客空间','科技园创业孵化器','1','深圳市南山区科苑路金融科技大厦A座5楼','0755-86620293','科技园创业孵化器是由深圳科技工业园（集团）有限公司倾力打造的创新型专业孵化器，致力于打造一个创投对接平台和创业黄埔军校。政府为科技园集团授牌深圳市南山区股权投资基金集聚园、深圳市南山区互联网金融集聚园及深圳市南山区互联网金融产业园，这三大平台联合并共享优质资源，为入驻的有潜力的创业企业在平台、品牌、渠道、资源、资金上面给予帮助，助力其加速发展。 科技园创业孵化器精心选择优质的具备较强自主创新能力的初创型企业进入孵化器，不仅能为其提供经济高效的创意办公空间，更为入驻的创业企业提供捆绑式的成长服务，提供包括创业辅导、管理咨询、交流培训、项目推介、市场推广、人才引进等服务内容，促进企业的发展壮大。','','2',NULL,NULL,NULL,'',NULL,NULL,NULL,NULL,NULL,'苟丹','13686467512',NULL,NULL,NULL,NULL,'2015-11-20 14:57:37');
insert into `eh_yellow_pages` (`id`, `parent_id`, `owner_type`, `owner_id`, `name`, `nick_name`, `type`, `address`, `contact`, `description`, `poster_uri`, `status`, `default_order`, `longitude`, `latitude`, `geohash`, `integral_tag1`, `integral_tag2`, `integral_tag3`, `integral_tag4`, `integral_tag5`, `string_tag1`, `string_tag2`, `string_tag3`, `string_tag4`, `string_tag5`, `creator_uid`, `create_time`) values('2','0','community','240111044331046562','服务联盟','服务联盟首页','2','谁知道在哪','0755-86620293','公共服务联盟旨在集聚社会优质服务资源，为园区广大企业提供专业、高效、有保障的服务，以帮助广大企业畅通信息渠道，提升企业管理，降低经营成本，增强市场竞争能力。服务类型包括项目融资对接、人才招聘和培训、信息化建设、管理咨询、知识产权管理、质量管理、外贸事务、法律事务、 物流服务、场地装修等。','cs://1/image/aW1hZ2UvTVRvd01qUmpNV00wTkdaaVltWTNNemt3TXpOak9EZGlOMk15TldZd01qWTNNUQ','2',NULL,NULL,NULL,'',NULL,NULL,NULL,NULL,NULL,'苟丹','13686467512','',NULL,NULL,NULL,'2015-11-20 14:59:28');
insert into `eh_yellow_pages` (`id`, `parent_id`, `owner_type`, `owner_id`, `name`, `nick_name`, `type`, `address`, `contact`, `description`, `poster_uri`, `status`, `default_order`, `longitude`, `latitude`, `geohash`, `integral_tag1`, `integral_tag2`, `integral_tag3`, `integral_tag4`, `integral_tag5`, `string_tag1`, `string_tag2`, `string_tag3`, `string_tag4`, `string_tag5`, `creator_uid`, `create_time`) values('3','0','community','240111044331046562','园区企业','园区企业','3','谁知道在哪','0755-86620293','园区企业没说明，直接用list','cs://1/image/aW1hZ2UvTVRvd01qUmpNV00wTkdaaVltWTNNemt3TXpOak9EZGlOMk15TldZd01qWTNNUQ','2',NULL,NULL,NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2015-11-20 15:00:45');
