-- 访客管理1.0事由列表 by dengs,20180507
INSERT INTO `eh_visitor_sys_visit_reason` (`id`, `namespace_id`, `owner_type`, `owner_id`, `visitor_reason`, `status`, `creator_uid`, `create_time`, `operator_uid`, `operate_time`) VALUES ('1', '0', 'community', '0', '临时来访', '2', '0', now(), '0', now());
INSERT INTO `eh_visitor_sys_visit_reason` (`id`, `namespace_id`, `owner_type`, `owner_id`, `visitor_reason`, `status`, `creator_uid`, `create_time`, `operator_uid`, `operate_time`) VALUES ('2', '0', 'community', '0', '入职', '2', '0', now(), '0', now());
INSERT INTO `eh_visitor_sys_visit_reason` (`id`, `namespace_id`, `owner_type`, `owner_id`, `visitor_reason`, `status`, `creator_uid`, `create_time`, `operator_uid`, `operate_time`) VALUES ('3', '0', 'community', '0', '面试', '2', '0', now(), '0', now());
INSERT INTO `eh_visitor_sys_visit_reason` (`id`, `namespace_id`, `owner_type`, `owner_id`, `visitor_reason`, `status`, `creator_uid`, `create_time`, `operator_uid`, `operate_time`) VALUES ('4', '0', 'community', '0', '送货', '2', '0', now(), '0', now());
INSERT INTO `eh_visitor_sys_visit_reason` (`id`, `namespace_id`, `owner_type`, `owner_id`, `visitor_reason`, `status`, `creator_uid`, `create_time`, `operator_uid`, `operate_time`) VALUES ('5', '0', 'community', '0', '出差	', '2', '0', now(), '0', now());
INSERT INTO `eh_visitor_sys_visit_reason` (`id`, `namespace_id`, `owner_type`, `owner_id`, `visitor_reason`, `status`, `creator_uid`, `create_time`, `operator_uid`, `operate_time`) VALUES ('6', '0', 'community', '0', '开会', '2', '0', now(), '0', now());
INSERT INTO `eh_visitor_sys_visit_reason` (`id`, `namespace_id`, `owner_type`, `owner_id`, `visitor_reason`, `status`, `creator_uid`, `create_time`, `operator_uid`, `operate_time`) VALUES ('7', '0', 'community', '0', '施工', '2', '0', now(), '0', now());
INSERT INTO `eh_visitor_sys_visit_reason` (`id`, `namespace_id`, `owner_type`, `owner_id`, `visitor_reason`, `status`, `creator_uid`, `create_time`, `operator_uid`, `operate_time`) VALUES ('8', '0', 'community', '0', '其它原因', '2', '0', now(), '0', now());
