-- add by nan.rong for workReport
INSERT INTO `eh_work_report_templates` (`id`, `namespace_id`, `owner_id`, `owner_type`, `organization_id`, `module_id`, `module_type`, `report_name`, `report_type`, `report_attribute`, `form_template_id`, `modify_flag`, `delete_flag`, `icon_uri`, `update_time`, `create_time`) VALUES ('1', '0', '0', 'EhOrganizations', '0', '54000', 'any-module', '日报', '0', 'DEFAULT', '6', '0', '0', NULL, '2017-12-06 18:55:10', '2017-12-06 18:55:10');
INSERT INTO `eh_work_report_templates` (`id`, `namespace_id`, `owner_id`, `owner_type`, `organization_id`, `module_id`, `module_type`, `report_name`, `report_type`, `report_attribute`, `form_template_id`, `modify_flag`, `delete_flag`, `icon_uri`, `update_time`, `create_time`) VALUES ('2', '0', '0', 'EhOrganizations', '0', '54000', 'any-module', '周报', '1', 'DEFAULT', '7', '0', '0', NULL, '2017-12-06 18:55:10', '2017-12-06 18:55:10');
INSERT INTO `eh_work_report_templates` (`id`, `namespace_id`, `owner_id`, `owner_type`, `organization_id`, `module_id`, `module_type`, `report_name`, `report_type`, `report_attribute`, `form_template_id`, `modify_flag`, `delete_flag`, `icon_uri`, `update_time`, `create_time`) VALUES ('3', '0', '0', 'EhOrganizations', '0', '54000', 'any-module', '月报', '2', 'DEFAULT', '8', '0', '0', NULL, '2017-12-06 18:55:10', '2017-12-06 18:55:10');

INSERT INTO `eh_general_form_templates` (`id`, `namespace_id`, `organization_id`, `owner_id`, `owner_type`, `module_id`, `module_type`, `form_name`, `version`, `template_type`, `template_text`, `modify_flag`, `delete_flag`, `update_time`, `create_time`) VALUES ('6', '0', '0', '0', 'EhOrganizations', '54000', 'any-module', '日报', '0', 'DEFAULT_JSON', '[{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"今日完成工作\",\"fieldExtra\":\"{}\",\"fieldName\":\"今日完成工作\",\"fieldType\":\"MULTI_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1},{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"未完成工作\",\"fieldExtra\":\"{}\",\"fieldName\":\"未完成工作\",\"fieldType\":\"MULTI_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1},{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"需协助工作\",\"fieldExtra\":\"{}\",\"fieldName\":\"需协助工作\",\"fieldType\":\"MULTI_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1},{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"明日计划工作\",\"fieldExtra\":\"{}\",\"fieldName\":\"明日计划工作\",\"fieldType\":\"MULTI_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1}]', '1', '0', '2017-12-06 18:57:08', '2017-12-06 18:57:08');
INSERT INTO `eh_general_form_templates` (`id`, `namespace_id`, `organization_id`, `owner_id`, `owner_type`, `module_id`, `module_type`, `form_name`, `version`, `template_type`, `template_text`, `modify_flag`, `delete_flag`, `update_time`, `create_time`) VALUES ('7', '0', '0', '0', 'EhOrganizations', '54000', 'any-module', '周报', '0', 'DEFAULT_JSON', '[{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"本周完成工作\",\"fieldExtra\":\"{}\",\"fieldName\":\"本周完成工作\",\"fieldType\":\"MULTI_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1},{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"未完成工作\",\"fieldExtra\":\"{}\",\"fieldName\":\"未完成工作\",\"fieldType\":\"MULTI_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1},{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"需协助工作\",\"fieldExtra\":\"{}\",\"fieldName\":\"需协助工作\",\"fieldType\":\"MULTI_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1},{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"下周计划工作\",\"fieldExtra\":\"{}\",\"fieldName\":\"下周计划工作\",\"fieldType\":\"MULTI_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1}]', '1', '0', '2017-12-06 18:57:08', '2017-12-06 18:57:08');
INSERT INTO `eh_general_form_templates` (`id`, `namespace_id`, `organization_id`, `owner_id`, `owner_type`, `module_id`, `module_type`, `form_name`, `version`, `template_type`, `template_text`, `modify_flag`, `delete_flag`, `update_time`, `create_time`) VALUES ('8', '0', '0', '0', 'EhOrganizations', '54000', 'any-module', '月报', '0', 'DEFAULT_JSON', '[{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"本月完成工作\",\"fieldExtra\":\"{}\",\"fieldName\":\"本月完成工作\",\"fieldType\":\"MULTI_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1},{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"未完成工作\",\"fieldExtra\":\"{}\",\"fieldName\":\"未完成工作\",\"fieldType\":\"MULTI_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1},{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"需协助工作\",\"fieldExtra\":\"{}\",\"fieldName\":\"需协助工作\",\"fieldType\":\"MULTI_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1},{\"dynamicFlag\":0,\"fieldDesc\":\"请输入\",\"fieldDisplayName\":\"下月计划工作\",\"fieldExtra\":\"{}\",\"fieldName\":\"下月计划工作\",\"fieldType\":\"MULTI_LINE_TEXT\",\"renderType\":\"DEFAULT\",\"requiredFlag\":0,\"validatorType\":\"TEXT_LIMIT\",\"visibleType\":\"EDITABLE\",\"modifyFlag\":1,\"deleteFlag\":1}]', '1', '0', '2017-12-06 18:57:08', '2017-12-06 18:57:08');

-- menu change
update eh_web_menus set sort_num = 610 where id = 51000;
update eh_web_menus set sort_num = 620 where id = 70000;
update eh_web_menus set sort_num = 620 where id = 700000;
update eh_web_menus set sort_num = 622 where id = 70100;
update eh_web_menus set sort_num = 622 where id = 701000;
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`, `level`, `condition_type`, `category`) VALUES ('54000', '工作汇报', '50000', NULL, '', '0', '2', '/50000/54000', 'park', '600', '54000', '2', NULL, 'module');
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`, `level`, `condition_type`, `category`) VALUES ('54010', '汇报设置', '54000', NULL, 'react:/work-report/report-setting', '0', '2', '/50000/54000/54010', 'park', '601', '54000', '3', NULL, 'module');
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`, `level`, `condition_type`, `category`) VALUES ('54020', '表单管理', '54000', NULL, 'react:/form-management/form-list?moduleId=54000&moduleType=any-module', '0', '2', '/50000/54000/54020', 'park', '602', '54000', '3', NULL, 'module');
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`, `level`, `condition_type`, `category`) VALUES ('540000', '工作汇报', '500000', NULL, '', '0', '2', '/500000/540000', 'organization', '600', '54000', '2', NULL, 'module');
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`, `level`, `condition_type`, `category`) VALUES ('540100', '汇报设置', '540100', NULL, 'react:/work-report/report-setting', '0', '2', '/500000/540000/540100', 'organization', '601', '54000', '3', NULL, 'module');
INSERT INTO `eh_web_menus` (`id`, `name`, `parent_id`, `icon_url`, `data_type`, `leaf_flag`, `status`, `path`, `type`, `sort_num`, `module_id`, `level`, `condition_type`, `category`) VALUES ('540200', '表单管理', '540200', NULL, 'react:/work-report/report-setting', '0', '2', '/500000/540000/540200', 'organization', '602', '54000', '3', NULL, 'module');

