/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhAccountVedioconfDao extends org.jooq.impl.DAOImpl<com.everhomes.server.schema.tables.records.EhAccountVedioconfRecord, com.everhomes.server.schema.tables.pojos.EhAccountVedioconf, java.lang.Long> {

	/**
	 * Create a new EhAccountVedioconfDao without any configuration
	 */
	public EhAccountVedioconfDao() {
		super(com.everhomes.server.schema.tables.EhAccountVedioconf.EH_ACCOUNT_VEDIOCONF, com.everhomes.server.schema.tables.pojos.EhAccountVedioconf.class);
	}

	/**
	 * Create a new EhAccountVedioconfDao with an attached configuration
	 */
	public EhAccountVedioconfDao(org.jooq.Configuration configuration) {
		super(com.everhomes.server.schema.tables.EhAccountVedioconf.EH_ACCOUNT_VEDIOCONF, com.everhomes.server.schema.tables.pojos.EhAccountVedioconf.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Long getId(com.everhomes.server.schema.tables.pojos.EhAccountVedioconf object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhAccountVedioconf> fetchById(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhAccountVedioconf.EH_ACCOUNT_VEDIOCONF.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.everhomes.server.schema.tables.pojos.EhAccountVedioconf fetchOneById(java.lang.Long value) {
		return fetchOne(com.everhomes.server.schema.tables.EhAccountVedioconf.EH_ACCOUNT_VEDIOCONF.ID, value);
	}

	/**
	 * Fetch records that have <code>account_id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhAccountVedioconf> fetchByAccountId(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhAccountVedioconf.EH_ACCOUNT_VEDIOCONF.ACCOUNT_ID, values);
	}

	/**
	 * Fetch records that have <code>source _account_id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhAccountVedioconf> fetchBySource_AccountId(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhAccountVedioconf.EH_ACCOUNT_VEDIOCONF.SOURCE__ACCOUNT_ID, values);
	}

	/**
	 * Fetch records that have <code>conf_id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhAccountVedioconf> fetchByConfId(java.lang.Integer... values) {
		return fetch(com.everhomes.server.schema.tables.EhAccountVedioconf.EH_ACCOUNT_VEDIOCONF.CONF_ID, values);
	}

	/**
	 * Fetch records that have <code>create_time IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhAccountVedioconf> fetchByCreateTime(java.sql.Timestamp... values) {
		return fetch(com.everhomes.server.schema.tables.EhAccountVedioconf.EH_ACCOUNT_VEDIOCONF.CREATE_TIME, values);
	}
}
