/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhCommunityPmBillsDao extends org.jooq.impl.DAOImpl<com.everhomes.server.schema.tables.records.EhCommunityPmBillsRecord, com.everhomes.server.schema.tables.pojos.EhCommunityPmBills, java.lang.Long> {

	/**
	 * Create a new EhCommunityPmBillsDao without any configuration
	 */
	public EhCommunityPmBillsDao() {
		super(com.everhomes.server.schema.tables.EhCommunityPmBills.EH_COMMUNITY_PM_BILLS, com.everhomes.server.schema.tables.pojos.EhCommunityPmBills.class);
	}

	/**
	 * Create a new EhCommunityPmBillsDao with an attached configuration
	 */
	public EhCommunityPmBillsDao(org.jooq.Configuration configuration) {
		super(com.everhomes.server.schema.tables.EhCommunityPmBills.EH_COMMUNITY_PM_BILLS, com.everhomes.server.schema.tables.pojos.EhCommunityPmBills.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Long getId(com.everhomes.server.schema.tables.pojos.EhCommunityPmBills object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhCommunityPmBills> fetchById(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhCommunityPmBills.EH_COMMUNITY_PM_BILLS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.everhomes.server.schema.tables.pojos.EhCommunityPmBills fetchOneById(java.lang.Long value) {
		return fetchOne(com.everhomes.server.schema.tables.EhCommunityPmBills.EH_COMMUNITY_PM_BILLS.ID, value);
	}

	/**
	 * Fetch records that have <code>community_id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhCommunityPmBills> fetchByCommunityId(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhCommunityPmBills.EH_COMMUNITY_PM_BILLS.COMMUNITY_ID, values);
	}

	/**
	 * Fetch records that have <code>entity_type IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhCommunityPmBills> fetchByEntityType(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhCommunityPmBills.EH_COMMUNITY_PM_BILLS.ENTITY_TYPE, values);
	}

	/**
	 * Fetch records that have <code>entity_id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhCommunityPmBills> fetchByEntityId(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhCommunityPmBills.EH_COMMUNITY_PM_BILLS.ENTITY_ID, values);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhCommunityPmBills> fetchByName(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhCommunityPmBills.EH_COMMUNITY_PM_BILLS.NAME, values);
	}

	/**
	 * Fetch records that have <code>date_str IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhCommunityPmBills> fetchByDateStr(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhCommunityPmBills.EH_COMMUNITY_PM_BILLS.DATE_STR, values);
	}

	/**
	 * Fetch records that have <code>total_amount IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhCommunityPmBills> fetchByTotalAmount(java.math.BigDecimal... values) {
		return fetch(com.everhomes.server.schema.tables.EhCommunityPmBills.EH_COMMUNITY_PM_BILLS.TOTAL_AMOUNT, values);
	}

	/**
	 * Fetch records that have <code>description IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhCommunityPmBills> fetchByDescription(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhCommunityPmBills.EH_COMMUNITY_PM_BILLS.DESCRIPTION, values);
	}

	/**
	 * Fetch records that have <code>creator_uid IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhCommunityPmBills> fetchByCreatorUid(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhCommunityPmBills.EH_COMMUNITY_PM_BILLS.CREATOR_UID, values);
	}

	/**
	 * Fetch records that have <code>create_time IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhCommunityPmBills> fetchByCreateTime(java.sql.Timestamp... values) {
		return fetch(com.everhomes.server.schema.tables.EhCommunityPmBills.EH_COMMUNITY_PM_BILLS.CREATE_TIME, values);
	}

	/**
	 * Fetch records that have <code>notify_count IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhCommunityPmBills> fetchByNotifyCount(java.lang.Integer... values) {
		return fetch(com.everhomes.server.schema.tables.EhCommunityPmBills.EH_COMMUNITY_PM_BILLS.NOTIFY_COUNT, values);
	}

	/**
	 * Fetch records that have <code>notify_time IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhCommunityPmBills> fetchByNotifyTime(java.sql.Timestamp... values) {
		return fetch(com.everhomes.server.schema.tables.EhCommunityPmBills.EH_COMMUNITY_PM_BILLS.NOTIFY_TIME, values);
	}
}
