/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhDoorAccessDao extends org.jooq.impl.DAOImpl<com.everhomes.server.schema.tables.records.EhDoorAccessRecord, com.everhomes.server.schema.tables.pojos.EhDoorAccess, java.lang.Long> {

	/**
	 * Create a new EhDoorAccessDao without any configuration
	 */
	public EhDoorAccessDao() {
		super(com.everhomes.server.schema.tables.EhDoorAccess.EH_DOOR_ACCESS, com.everhomes.server.schema.tables.pojos.EhDoorAccess.class);
	}

	/**
	 * Create a new EhDoorAccessDao with an attached configuration
	 */
	public EhDoorAccessDao(org.jooq.Configuration configuration) {
		super(com.everhomes.server.schema.tables.EhDoorAccess.EH_DOOR_ACCESS, com.everhomes.server.schema.tables.pojos.EhDoorAccess.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Long getId(com.everhomes.server.schema.tables.pojos.EhDoorAccess object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhDoorAccess> fetchById(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhDoorAccess.EH_DOOR_ACCESS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.everhomes.server.schema.tables.pojos.EhDoorAccess fetchOneById(java.lang.Long value) {
		return fetchOne(com.everhomes.server.schema.tables.EhDoorAccess.EH_DOOR_ACCESS.ID, value);
	}

	/**
	 * Fetch records that have <code>uuid IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhDoorAccess> fetchByUuid(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhDoorAccess.EH_DOOR_ACCESS.UUID, values);
	}

	/**
	 * Fetch a unique record that has <code>uuid = value</code>
	 */
	public com.everhomes.server.schema.tables.pojos.EhDoorAccess fetchOneByUuid(java.lang.String value) {
		return fetchOne(com.everhomes.server.schema.tables.EhDoorAccess.EH_DOOR_ACCESS.UUID, value);
	}

	/**
	 * Fetch records that have <code>door_type IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhDoorAccess> fetchByDoorType(java.lang.Byte... values) {
		return fetch(com.everhomes.server.schema.tables.EhDoorAccess.EH_DOOR_ACCESS.DOOR_TYPE, values);
	}

	/**
	 * Fetch records that have <code>hardware_id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhDoorAccess> fetchByHardwareId(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhDoorAccess.EH_DOOR_ACCESS.HARDWARE_ID, values);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhDoorAccess> fetchByName(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhDoorAccess.EH_DOOR_ACCESS.NAME, values);
	}

	/**
	 * Fetch records that have <code>description IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhDoorAccess> fetchByDescription(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhDoorAccess.EH_DOOR_ACCESS.DESCRIPTION, values);
	}

	/**
	 * Fetch records that have <code>avatar IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhDoorAccess> fetchByAvatar(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhDoorAccess.EH_DOOR_ACCESS.AVATAR, values);
	}

	/**
	 * Fetch records that have <code>address IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhDoorAccess> fetchByAddress(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhDoorAccess.EH_DOOR_ACCESS.ADDRESS, values);
	}

	/**
	 * Fetch records that have <code>active_user_id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhDoorAccess> fetchByActiveUserId(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhDoorAccess.EH_DOOR_ACCESS.ACTIVE_USER_ID, values);
	}

	/**
	 * Fetch records that have <code>creator_user_id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhDoorAccess> fetchByCreatorUserId(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhDoorAccess.EH_DOOR_ACCESS.CREATOR_USER_ID, values);
	}

	/**
	 * Fetch records that have <code>longitude IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhDoorAccess> fetchByLongitude(java.lang.Double... values) {
		return fetch(com.everhomes.server.schema.tables.EhDoorAccess.EH_DOOR_ACCESS.LONGITUDE, values);
	}

	/**
	 * Fetch records that have <code>latitude IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhDoorAccess> fetchByLatitude(java.lang.Double... values) {
		return fetch(com.everhomes.server.schema.tables.EhDoorAccess.EH_DOOR_ACCESS.LATITUDE, values);
	}

	/**
	 * Fetch records that have <code>geohash IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhDoorAccess> fetchByGeohash(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhDoorAccess.EH_DOOR_ACCESS.GEOHASH, values);
	}

	/**
	 * Fetch records that have <code>aes_iv IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhDoorAccess> fetchByAesIv(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhDoorAccess.EH_DOOR_ACCESS.AES_IV, values);
	}

	/**
	 * Fetch records that have <code>link_status IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhDoorAccess> fetchByLinkStatus(java.lang.Byte... values) {
		return fetch(com.everhomes.server.schema.tables.EhDoorAccess.EH_DOOR_ACCESS.LINK_STATUS, values);
	}

	/**
	 * Fetch records that have <code>owner_type IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhDoorAccess> fetchByOwnerType(java.lang.Byte... values) {
		return fetch(com.everhomes.server.schema.tables.EhDoorAccess.EH_DOOR_ACCESS.OWNER_TYPE, values);
	}

	/**
	 * Fetch records that have <code>owner_id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhDoorAccess> fetchByOwnerId(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhDoorAccess.EH_DOOR_ACCESS.OWNER_ID, values);
	}

	/**
	 * Fetch records that have <code>role IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhDoorAccess> fetchByRole(java.lang.Byte... values) {
		return fetch(com.everhomes.server.schema.tables.EhDoorAccess.EH_DOOR_ACCESS.ROLE, values);
	}

	/**
	 * Fetch records that have <code>create_time IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhDoorAccess> fetchByCreateTime(java.sql.Timestamp... values) {
		return fetch(com.everhomes.server.schema.tables.EhDoorAccess.EH_DOOR_ACCESS.CREATE_TIME, values);
	}

	/**
	 * Fetch records that have <code>status IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhDoorAccess> fetchByStatus(java.lang.Byte... values) {
		return fetch(com.everhomes.server.schema.tables.EhDoorAccess.EH_DOOR_ACCESS.STATUS, values);
	}

	/**
	 * Fetch records that have <code>acking_secret_version IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhDoorAccess> fetchByAckingSecretVersion(java.lang.Integer... values) {
		return fetch(com.everhomes.server.schema.tables.EhDoorAccess.EH_DOOR_ACCESS.ACKING_SECRET_VERSION, values);
	}

	/**
	 * Fetch records that have <code>expect_secret_key IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhDoorAccess> fetchByExpectSecretKey(java.lang.Integer... values) {
		return fetch(com.everhomes.server.schema.tables.EhDoorAccess.EH_DOOR_ACCESS.EXPECT_SECRET_KEY, values);
	}

	/**
	 * Fetch records that have <code>groupId IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhDoorAccess> fetchByGroupid(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhDoorAccess.EH_DOOR_ACCESS.GROUPID, values);
	}
}
