/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhEquipmentInspectionItemsDao extends org.jooq.impl.DAOImpl<com.everhomes.server.schema.tables.records.EhEquipmentInspectionItemsRecord, com.everhomes.server.schema.tables.pojos.EhEquipmentInspectionItems, java.lang.Long> {

	/**
	 * Create a new EhEquipmentInspectionItemsDao without any configuration
	 */
	public EhEquipmentInspectionItemsDao() {
		super(com.everhomes.server.schema.tables.EhEquipmentInspectionItems.EH_EQUIPMENT_INSPECTION_ITEMS, com.everhomes.server.schema.tables.pojos.EhEquipmentInspectionItems.class);
	}

	/**
	 * Create a new EhEquipmentInspectionItemsDao with an attached configuration
	 */
	public EhEquipmentInspectionItemsDao(org.jooq.Configuration configuration) {
		super(com.everhomes.server.schema.tables.EhEquipmentInspectionItems.EH_EQUIPMENT_INSPECTION_ITEMS, com.everhomes.server.schema.tables.pojos.EhEquipmentInspectionItems.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Long getId(com.everhomes.server.schema.tables.pojos.EhEquipmentInspectionItems object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhEquipmentInspectionItems> fetchById(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhEquipmentInspectionItems.EH_EQUIPMENT_INSPECTION_ITEMS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.everhomes.server.schema.tables.pojos.EhEquipmentInspectionItems fetchOneById(java.lang.Long value) {
		return fetchOne(com.everhomes.server.schema.tables.EhEquipmentInspectionItems.EH_EQUIPMENT_INSPECTION_ITEMS.ID, value);
	}

	/**
	 * Fetch records that have <code>owner_type IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhEquipmentInspectionItems> fetchByOwnerType(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhEquipmentInspectionItems.EH_EQUIPMENT_INSPECTION_ITEMS.OWNER_TYPE, values);
	}

	/**
	 * Fetch records that have <code>owner_id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhEquipmentInspectionItems> fetchByOwnerId(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhEquipmentInspectionItems.EH_EQUIPMENT_INSPECTION_ITEMS.OWNER_ID, values);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhEquipmentInspectionItems> fetchByName(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhEquipmentInspectionItems.EH_EQUIPMENT_INSPECTION_ITEMS.NAME, values);
	}

	/**
	 * Fetch records that have <code>value_type IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhEquipmentInspectionItems> fetchByValueType(java.lang.Byte... values) {
		return fetch(com.everhomes.server.schema.tables.EhEquipmentInspectionItems.EH_EQUIPMENT_INSPECTION_ITEMS.VALUE_TYPE, values);
	}

	/**
	 * Fetch records that have <code>unit IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhEquipmentInspectionItems> fetchByUnit(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhEquipmentInspectionItems.EH_EQUIPMENT_INSPECTION_ITEMS.UNIT, values);
	}

	/**
	 * Fetch records that have <code>value_jason IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhEquipmentInspectionItems> fetchByValueJason(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhEquipmentInspectionItems.EH_EQUIPMENT_INSPECTION_ITEMS.VALUE_JASON, values);
	}

	/**
	 * Fetch records that have <code>namespace_id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhEquipmentInspectionItems> fetchByNamespaceId(java.lang.Integer... values) {
		return fetch(com.everhomes.server.schema.tables.EhEquipmentInspectionItems.EH_EQUIPMENT_INSPECTION_ITEMS.NAMESPACE_ID, values);
	}
}
