/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhFlowNodesDao extends org.jooq.impl.DAOImpl<com.everhomes.server.schema.tables.records.EhFlowNodesRecord, com.everhomes.server.schema.tables.pojos.EhFlowNodes, java.lang.Long> {

	/**
	 * Create a new EhFlowNodesDao without any configuration
	 */
	public EhFlowNodesDao() {
		super(com.everhomes.server.schema.tables.EhFlowNodes.EH_FLOW_NODES, com.everhomes.server.schema.tables.pojos.EhFlowNodes.class);
	}

	/**
	 * Create a new EhFlowNodesDao with an attached configuration
	 */
	public EhFlowNodesDao(org.jooq.Configuration configuration) {
		super(com.everhomes.server.schema.tables.EhFlowNodes.EH_FLOW_NODES, com.everhomes.server.schema.tables.pojos.EhFlowNodes.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Long getId(com.everhomes.server.schema.tables.pojos.EhFlowNodes object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhFlowNodes> fetchById(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhFlowNodes.EH_FLOW_NODES.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.everhomes.server.schema.tables.pojos.EhFlowNodes fetchOneById(java.lang.Long value) {
		return fetchOne(com.everhomes.server.schema.tables.EhFlowNodes.EH_FLOW_NODES.ID, value);
	}

	/**
	 * Fetch records that have <code>namespace_id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhFlowNodes> fetchByNamespaceId(java.lang.Integer... values) {
		return fetch(com.everhomes.server.schema.tables.EhFlowNodes.EH_FLOW_NODES.NAMESPACE_ID, values);
	}

	/**
	 * Fetch records that have <code>flow_main_id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhFlowNodes> fetchByFlowMainId(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhFlowNodes.EH_FLOW_NODES.FLOW_MAIN_ID, values);
	}

	/**
	 * Fetch records that have <code>flow_version IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhFlowNodes> fetchByFlowVersion(java.lang.Integer... values) {
		return fetch(com.everhomes.server.schema.tables.EhFlowNodes.EH_FLOW_NODES.FLOW_VERSION, values);
	}

	/**
	 * Fetch records that have <code>node_name IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhFlowNodes> fetchByNodeName(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhFlowNodes.EH_FLOW_NODES.NODE_NAME, values);
	}

	/**
	 * Fetch records that have <code>description IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhFlowNodes> fetchByDescription(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhFlowNodes.EH_FLOW_NODES.DESCRIPTION, values);
	}

	/**
	 * Fetch records that have <code>node_level IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhFlowNodes> fetchByNodeLevel(java.lang.Integer... values) {
		return fetch(com.everhomes.server.schema.tables.EhFlowNodes.EH_FLOW_NODES.NODE_LEVEL, values);
	}

	/**
	 * Fetch records that have <code>auto_step_minute IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhFlowNodes> fetchByAutoStepMinute(java.lang.Integer... values) {
		return fetch(com.everhomes.server.schema.tables.EhFlowNodes.EH_FLOW_NODES.AUTO_STEP_MINUTE, values);
	}

	/**
	 * Fetch records that have <code>auto_step_type IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhFlowNodes> fetchByAutoStepType(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhFlowNodes.EH_FLOW_NODES.AUTO_STEP_TYPE, values);
	}

	/**
	 * Fetch records that have <code>allow_applier_update IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhFlowNodes> fetchByAllowApplierUpdate(java.lang.Byte... values) {
		return fetch(com.everhomes.server.schema.tables.EhFlowNodes.EH_FLOW_NODES.ALLOW_APPLIER_UPDATE, values);
	}

	/**
	 * Fetch records that have <code>allow_timeout_action IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhFlowNodes> fetchByAllowTimeoutAction(java.lang.Byte... values) {
		return fetch(com.everhomes.server.schema.tables.EhFlowNodes.EH_FLOW_NODES.ALLOW_TIMEOUT_ACTION, values);
	}

	/**
	 * Fetch records that have <code>create_time IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhFlowNodes> fetchByCreateTime(java.sql.Timestamp... values) {
		return fetch(com.everhomes.server.schema.tables.EhFlowNodes.EH_FLOW_NODES.CREATE_TIME, values);
	}

	/**
	 * Fetch records that have <code>params IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhFlowNodes> fetchByParams(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhFlowNodes.EH_FLOW_NODES.PARAMS, values);
	}

	/**
	 * Fetch records that have <code>status IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhFlowNodes> fetchByStatus(java.lang.Byte... values) {
		return fetch(com.everhomes.server.schema.tables.EhFlowNodes.EH_FLOW_NODES.STATUS, values);
	}
}
