/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhNamespaceDetailsDao extends org.jooq.impl.DAOImpl<com.everhomes.server.schema.tables.records.EhNamespaceDetailsRecord, com.everhomes.server.schema.tables.pojos.EhNamespaceDetails, java.lang.Long> {

	/**
	 * Create a new EhNamespaceDetailsDao without any configuration
	 */
	public EhNamespaceDetailsDao() {
		super(com.everhomes.server.schema.tables.EhNamespaceDetails.EH_NAMESPACE_DETAILS, com.everhomes.server.schema.tables.pojos.EhNamespaceDetails.class);
	}

	/**
	 * Create a new EhNamespaceDetailsDao with an attached configuration
	 */
	public EhNamespaceDetailsDao(org.jooq.Configuration configuration) {
		super(com.everhomes.server.schema.tables.EhNamespaceDetails.EH_NAMESPACE_DETAILS, com.everhomes.server.schema.tables.pojos.EhNamespaceDetails.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Long getId(com.everhomes.server.schema.tables.pojos.EhNamespaceDetails object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhNamespaceDetails> fetchById(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhNamespaceDetails.EH_NAMESPACE_DETAILS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.everhomes.server.schema.tables.pojos.EhNamespaceDetails fetchOneById(java.lang.Long value) {
		return fetchOne(com.everhomes.server.schema.tables.EhNamespaceDetails.EH_NAMESPACE_DETAILS.ID, value);
	}

	/**
	 * Fetch records that have <code>namespace_id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhNamespaceDetails> fetchByNamespaceId(java.lang.Integer... values) {
		return fetch(com.everhomes.server.schema.tables.EhNamespaceDetails.EH_NAMESPACE_DETAILS.NAMESPACE_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>namespace_id = value</code>
	 */
	public com.everhomes.server.schema.tables.pojos.EhNamespaceDetails fetchOneByNamespaceId(java.lang.Integer value) {
		return fetchOne(com.everhomes.server.schema.tables.EhNamespaceDetails.EH_NAMESPACE_DETAILS.NAMESPACE_ID, value);
	}

	/**
	 * Fetch records that have <code>resource_type IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhNamespaceDetails> fetchByResourceType(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhNamespaceDetails.EH_NAMESPACE_DETAILS.RESOURCE_TYPE, values);
	}

	/**
	 * Fetch records that have <code>create_time IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhNamespaceDetails> fetchByCreateTime(java.sql.Timestamp... values) {
		return fetch(com.everhomes.server.schema.tables.EhNamespaceDetails.EH_NAMESPACE_DETAILS.CREATE_TIME, values);
	}
}
