/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhOrganizationMemberLogsDao extends org.jooq.impl.DAOImpl<com.everhomes.server.schema.tables.records.EhOrganizationMemberLogsRecord, com.everhomes.server.schema.tables.pojos.EhOrganizationMemberLogs, java.lang.Long> {

	/**
	 * Create a new EhOrganizationMemberLogsDao without any configuration
	 */
	public EhOrganizationMemberLogsDao() {
		super(com.everhomes.server.schema.tables.EhOrganizationMemberLogs.EH_ORGANIZATION_MEMBER_LOGS, com.everhomes.server.schema.tables.pojos.EhOrganizationMemberLogs.class);
	}

	/**
	 * Create a new EhOrganizationMemberLogsDao with an attached configuration
	 */
	public EhOrganizationMemberLogsDao(org.jooq.Configuration configuration) {
		super(com.everhomes.server.schema.tables.EhOrganizationMemberLogs.EH_ORGANIZATION_MEMBER_LOGS, com.everhomes.server.schema.tables.pojos.EhOrganizationMemberLogs.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Long getId(com.everhomes.server.schema.tables.pojos.EhOrganizationMemberLogs object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhOrganizationMemberLogs> fetchById(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhOrganizationMemberLogs.EH_ORGANIZATION_MEMBER_LOGS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.everhomes.server.schema.tables.pojos.EhOrganizationMemberLogs fetchOneById(java.lang.Long value) {
		return fetchOne(com.everhomes.server.schema.tables.EhOrganizationMemberLogs.EH_ORGANIZATION_MEMBER_LOGS.ID, value);
	}

	/**
	 * Fetch records that have <code>namespace_id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhOrganizationMemberLogs> fetchByNamespaceId(java.lang.Integer... values) {
		return fetch(com.everhomes.server.schema.tables.EhOrganizationMemberLogs.EH_ORGANIZATION_MEMBER_LOGS.NAMESPACE_ID, values);
	}

	/**
	 * Fetch records that have <code>organization_id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhOrganizationMemberLogs> fetchByOrganizationId(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhOrganizationMemberLogs.EH_ORGANIZATION_MEMBER_LOGS.ORGANIZATION_ID, values);
	}

	/**
	 * Fetch records that have <code>user_id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhOrganizationMemberLogs> fetchByUserId(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhOrganizationMemberLogs.EH_ORGANIZATION_MEMBER_LOGS.USER_ID, values);
	}

	/**
	 * Fetch records that have <code>contact_name IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhOrganizationMemberLogs> fetchByContactName(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhOrganizationMemberLogs.EH_ORGANIZATION_MEMBER_LOGS.CONTACT_NAME, values);
	}

	/**
	 * Fetch records that have <code>contact_type IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhOrganizationMemberLogs> fetchByContactType(java.lang.Byte... values) {
		return fetch(com.everhomes.server.schema.tables.EhOrganizationMemberLogs.EH_ORGANIZATION_MEMBER_LOGS.CONTACT_TYPE, values);
	}

	/**
	 * Fetch records that have <code>contact_token IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhOrganizationMemberLogs> fetchByContactToken(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhOrganizationMemberLogs.EH_ORGANIZATION_MEMBER_LOGS.CONTACT_TOKEN, values);
	}

	/**
	 * Fetch records that have <code>operation_type IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhOrganizationMemberLogs> fetchByOperationType(java.lang.Byte... values) {
		return fetch(com.everhomes.server.schema.tables.EhOrganizationMemberLogs.EH_ORGANIZATION_MEMBER_LOGS.OPERATION_TYPE, values);
	}

	/**
	 * Fetch records that have <code>request_type IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhOrganizationMemberLogs> fetchByRequestType(java.lang.Byte... values) {
		return fetch(com.everhomes.server.schema.tables.EhOrganizationMemberLogs.EH_ORGANIZATION_MEMBER_LOGS.REQUEST_TYPE, values);
	}

	/**
	 * Fetch records that have <code>operate_time IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhOrganizationMemberLogs> fetchByOperateTime(java.sql.Timestamp... values) {
		return fetch(com.everhomes.server.schema.tables.EhOrganizationMemberLogs.EH_ORGANIZATION_MEMBER_LOGS.OPERATE_TIME, values);
	}

	/**
	 * Fetch records that have <code>operator_uid IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhOrganizationMemberLogs> fetchByOperatorUid(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhOrganizationMemberLogs.EH_ORGANIZATION_MEMBER_LOGS.OPERATOR_UID, values);
	}

	/**
	 * Fetch records that have <code>contact_description IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhOrganizationMemberLogs> fetchByContactDescription(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhOrganizationMemberLogs.EH_ORGANIZATION_MEMBER_LOGS.CONTACT_DESCRIPTION, values);
	}
}
