/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhRecommendationsDao extends org.jooq.impl.DAOImpl<com.everhomes.server.schema.tables.records.EhRecommendationsRecord, com.everhomes.server.schema.tables.pojos.EhRecommendations, java.lang.Long> {

	/**
	 * Create a new EhRecommendationsDao without any configuration
	 */
	public EhRecommendationsDao() {
		super(com.everhomes.server.schema.tables.EhRecommendations.EH_RECOMMENDATIONS, com.everhomes.server.schema.tables.pojos.EhRecommendations.class);
	}

	/**
	 * Create a new EhRecommendationsDao with an attached configuration
	 */
	public EhRecommendationsDao(org.jooq.Configuration configuration) {
		super(com.everhomes.server.schema.tables.EhRecommendations.EH_RECOMMENDATIONS, com.everhomes.server.schema.tables.pojos.EhRecommendations.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Long getId(com.everhomes.server.schema.tables.pojos.EhRecommendations object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhRecommendations> fetchById(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhRecommendations.EH_RECOMMENDATIONS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.everhomes.server.schema.tables.pojos.EhRecommendations fetchOneById(java.lang.Long value) {
		return fetchOne(com.everhomes.server.schema.tables.EhRecommendations.EH_RECOMMENDATIONS.ID, value);
	}

	/**
	 * Fetch records that have <code>appId IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhRecommendations> fetchByAppid(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhRecommendations.EH_RECOMMENDATIONS.APPID, values);
	}

	/**
	 * Fetch records that have <code>suggest_type IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhRecommendations> fetchBySuggestType(java.lang.Integer... values) {
		return fetch(com.everhomes.server.schema.tables.EhRecommendations.EH_RECOMMENDATIONS.SUGGEST_TYPE, values);
	}

	/**
	 * Fetch records that have <code>user_id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhRecommendations> fetchByUserId(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhRecommendations.EH_RECOMMENDATIONS.USER_ID, values);
	}

	/**
	 * Fetch records that have <code>target_type IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhRecommendations> fetchByTargetType(java.lang.Integer... values) {
		return fetch(com.everhomes.server.schema.tables.EhRecommendations.EH_RECOMMENDATIONS.TARGET_TYPE, values);
	}

	/**
	 * Fetch records that have <code>target_id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhRecommendations> fetchByTargetId(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhRecommendations.EH_RECOMMENDATIONS.TARGET_ID, values);
	}

	/**
	 * Fetch records that have <code>embedded_json IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhRecommendations> fetchByEmbeddedJson(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhRecommendations.EH_RECOMMENDATIONS.EMBEDDED_JSON, values);
	}

	/**
	 * Fetch records that have <code>max_count IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhRecommendations> fetchByMaxCount(java.lang.Integer... values) {
		return fetch(com.everhomes.server.schema.tables.EhRecommendations.EH_RECOMMENDATIONS.MAX_COUNT, values);
	}

	/**
	 * Fetch records that have <code>score IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhRecommendations> fetchByScore(java.lang.Double... values) {
		return fetch(com.everhomes.server.schema.tables.EhRecommendations.EH_RECOMMENDATIONS.SCORE, values);
	}

	/**
	 * Fetch records that have <code>status IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhRecommendations> fetchByStatus(java.lang.Integer... values) {
		return fetch(com.everhomes.server.schema.tables.EhRecommendations.EH_RECOMMENDATIONS.STATUS, values);
	}

	/**
	 * Fetch records that have <code>create_time IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhRecommendations> fetchByCreateTime(java.sql.Timestamp... values) {
		return fetch(com.everhomes.server.schema.tables.EhRecommendations.EH_RECOMMENDATIONS.CREATE_TIME, values);
	}

	/**
	 * Fetch records that have <code>expire_time IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhRecommendations> fetchByExpireTime(java.sql.Timestamp... values) {
		return fetch(com.everhomes.server.schema.tables.EhRecommendations.EH_RECOMMENDATIONS.EXPIRE_TIME, values);
	}
}
