/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhUserImpersonationsDao extends org.jooq.impl.DAOImpl<com.everhomes.server.schema.tables.records.EhUserImpersonationsRecord, com.everhomes.server.schema.tables.pojos.EhUserImpersonations, java.lang.Long> {

	/**
	 * Create a new EhUserImpersonationsDao without any configuration
	 */
	public EhUserImpersonationsDao() {
		super(com.everhomes.server.schema.tables.EhUserImpersonations.EH_USER_IMPERSONATIONS, com.everhomes.server.schema.tables.pojos.EhUserImpersonations.class);
	}

	/**
	 * Create a new EhUserImpersonationsDao with an attached configuration
	 */
	public EhUserImpersonationsDao(org.jooq.Configuration configuration) {
		super(com.everhomes.server.schema.tables.EhUserImpersonations.EH_USER_IMPERSONATIONS, com.everhomes.server.schema.tables.pojos.EhUserImpersonations.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Long getId(com.everhomes.server.schema.tables.pojos.EhUserImpersonations object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhUserImpersonations> fetchById(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhUserImpersonations.EH_USER_IMPERSONATIONS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.everhomes.server.schema.tables.pojos.EhUserImpersonations fetchOneById(java.lang.Long value) {
		return fetchOne(com.everhomes.server.schema.tables.EhUserImpersonations.EH_USER_IMPERSONATIONS.ID, value);
	}

	/**
	 * Fetch records that have <code>namespace_id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhUserImpersonations> fetchByNamespaceId(java.lang.Integer... values) {
		return fetch(com.everhomes.server.schema.tables.EhUserImpersonations.EH_USER_IMPERSONATIONS.NAMESPACE_ID, values);
	}

	/**
	 * Fetch records that have <code>owner_type IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhUserImpersonations> fetchByOwnerType(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhUserImpersonations.EH_USER_IMPERSONATIONS.OWNER_TYPE, values);
	}

	/**
	 * Fetch records that have <code>owner_id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhUserImpersonations> fetchByOwnerId(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhUserImpersonations.EH_USER_IMPERSONATIONS.OWNER_ID, values);
	}

	/**
	 * Fetch records that have <code>target_type IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhUserImpersonations> fetchByTargetType(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhUserImpersonations.EH_USER_IMPERSONATIONS.TARGET_TYPE, values);
	}

	/**
	 * Fetch records that have <code>target_id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhUserImpersonations> fetchByTargetId(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhUserImpersonations.EH_USER_IMPERSONATIONS.TARGET_ID, values);
	}

	/**
	 * Fetch records that have <code>description IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhUserImpersonations> fetchByDescription(java.lang.String... values) {
		return fetch(com.everhomes.server.schema.tables.EhUserImpersonations.EH_USER_IMPERSONATIONS.DESCRIPTION, values);
	}

	/**
	 * Fetch records that have <code>status IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhUserImpersonations> fetchByStatus(java.lang.Byte... values) {
		return fetch(com.everhomes.server.schema.tables.EhUserImpersonations.EH_USER_IMPERSONATIONS.STATUS, values);
	}

	/**
	 * Fetch records that have <code>create_time IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhUserImpersonations> fetchByCreateTime(java.sql.Timestamp... values) {
		return fetch(com.everhomes.server.schema.tables.EhUserImpersonations.EH_USER_IMPERSONATIONS.CREATE_TIME, values);
	}
}
