/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhUserCommunitiesDao extends org.jooq.impl.DAOImpl<com.everhomes.server.schema.tables.records.EhUserCommunitiesRecord, com.everhomes.server.schema.tables.pojos.EhUserCommunities, java.lang.Long> {

	/**
	 * Create a new EhUserCommunitiesDao without any configuration
	 */
	public EhUserCommunitiesDao() {
		super(com.everhomes.server.schema.tables.EhUserCommunities.EH_USER_COMMUNITIES, com.everhomes.server.schema.tables.pojos.EhUserCommunities.class);
	}

	/**
	 * Create a new EhUserCommunitiesDao with an attached configuration
	 */
	public EhUserCommunitiesDao(org.jooq.Configuration configuration) {
		super(com.everhomes.server.schema.tables.EhUserCommunities.EH_USER_COMMUNITIES, com.everhomes.server.schema.tables.pojos.EhUserCommunities.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Long getId(com.everhomes.server.schema.tables.pojos.EhUserCommunities object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhUserCommunities> fetchById(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhUserCommunities.EH_USER_COMMUNITIES.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.everhomes.server.schema.tables.pojos.EhUserCommunities fetchOneById(java.lang.Long value) {
		return fetchOne(com.everhomes.server.schema.tables.EhUserCommunities.EH_USER_COMMUNITIES.ID, value);
	}

	/**
	 * Fetch records that have <code>owner_uid IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhUserCommunities> fetchByOwnerUid(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhUserCommunities.EH_USER_COMMUNITIES.OWNER_UID, values);
	}

	/**
	 * Fetch records that have <code>community_type IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhUserCommunities> fetchByCommunityType(java.lang.Byte... values) {
		return fetch(com.everhomes.server.schema.tables.EhUserCommunities.EH_USER_COMMUNITIES.COMMUNITY_TYPE, values);
	}

	/**
	 * Fetch records that have <code>community_id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhUserCommunities> fetchByCommunityId(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhUserCommunities.EH_USER_COMMUNITIES.COMMUNITY_ID, values);
	}

	/**
	 * Fetch records that have <code>join_policy IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhUserCommunities> fetchByJoinPolicy(java.lang.Byte... values) {
		return fetch(com.everhomes.server.schema.tables.EhUserCommunities.EH_USER_COMMUNITIES.JOIN_POLICY, values);
	}

	/**
	 * Fetch records that have <code>create_time IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhUserCommunities> fetchByCreateTime(java.sql.Timestamp... values) {
		return fetch(com.everhomes.server.schema.tables.EhUserCommunities.EH_USER_COMMUNITIES.CREATE_TIME, values);
	}
}
