/**
 * This class is generated by jOOQ
 */
package com.everhomes.server.schema.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EhVideoconfOrderDao extends org.jooq.impl.DAOImpl<com.everhomes.server.schema.tables.records.EhVideoconfOrderRecord, com.everhomes.server.schema.tables.pojos.EhVideoconfOrder, java.lang.Long> {

	/**
	 * Create a new EhVideoconfOrderDao without any configuration
	 */
	public EhVideoconfOrderDao() {
		super(com.everhomes.server.schema.tables.EhVideoconfOrder.EH_VIDEOCONF_ORDER, com.everhomes.server.schema.tables.pojos.EhVideoconfOrder.class);
	}

	/**
	 * Create a new EhVideoconfOrderDao with an attached configuration
	 */
	public EhVideoconfOrderDao(org.jooq.Configuration configuration) {
		super(com.everhomes.server.schema.tables.EhVideoconfOrder.EH_VIDEOCONF_ORDER, com.everhomes.server.schema.tables.pojos.EhVideoconfOrder.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Long getId(com.everhomes.server.schema.tables.pojos.EhVideoconfOrder object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhVideoconfOrder> fetchById(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhVideoconfOrder.EH_VIDEOCONF_ORDER.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.everhomes.server.schema.tables.pojos.EhVideoconfOrder fetchOneById(java.lang.Long value) {
		return fetchOne(com.everhomes.server.schema.tables.EhVideoconfOrder.EH_VIDEOCONF_ORDER.ID, value);
	}

	/**
	 * Fetch records that have <code>order_id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhVideoconfOrder> fetchByOrderId(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhVideoconfOrder.EH_VIDEOCONF_ORDER.ORDER_ID, values);
	}

	/**
	 * Fetch records that have <code>enterprise_id IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhVideoconfOrder> fetchByEnterpriseId(java.lang.Long... values) {
		return fetch(com.everhomes.server.schema.tables.EhVideoconfOrder.EH_VIDEOCONF_ORDER.ENTERPRISE_ID, values);
	}

	/**
	 * Fetch records that have <code>quantity IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhVideoconfOrder> fetchByQuantity(java.lang.Integer... values) {
		return fetch(com.everhomes.server.schema.tables.EhVideoconfOrder.EH_VIDEOCONF_ORDER.QUANTITY, values);
	}

	/**
	 * Fetch records that have <code>package_months IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhVideoconfOrder> fetchByPackageMonths(java.lang.Integer... values) {
		return fetch(com.everhomes.server.schema.tables.EhVideoconfOrder.EH_VIDEOCONF_ORDER.PACKAGE_MONTHS, values);
	}

	/**
	 * Fetch records that have <code>amount IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhVideoconfOrder> fetchByAmount(java.math.BigDecimal... values) {
		return fetch(com.everhomes.server.schema.tables.EhVideoconfOrder.EH_VIDEOCONF_ORDER.AMOUNT, values);
	}

	/**
	 * Fetch records that have <code>invoice_flag IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhVideoconfOrder> fetchByInvoiceFlag(java.lang.Byte... values) {
		return fetch(com.everhomes.server.schema.tables.EhVideoconfOrder.EH_VIDEOCONF_ORDER.INVOICE_FLAG, values);
	}

	/**
	 * Fetch records that have <code>make_out_flag IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhVideoconfOrder> fetchByMakeOutFlag(java.lang.Byte... values) {
		return fetch(com.everhomes.server.schema.tables.EhVideoconfOrder.EH_VIDEOCONF_ORDER.MAKE_OUT_FLAG, values);
	}

	/**
	 * Fetch records that have <code>account_type IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhVideoconfOrder> fetchByAccountType(java.lang.Byte... values) {
		return fetch(com.everhomes.server.schema.tables.EhVideoconfOrder.EH_VIDEOCONF_ORDER.ACCOUNT_TYPE, values);
	}

	/**
	 * Fetch records that have <code>conf_tpye IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhVideoconfOrder> fetchByConfTpye(java.lang.Byte... values) {
		return fetch(com.everhomes.server.schema.tables.EhVideoconfOrder.EH_VIDEOCONF_ORDER.CONF_TPYE, values);
	}

	/**
	 * Fetch records that have <code>buy_channel IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhVideoconfOrder> fetchByBuyChannel(java.lang.Byte... values) {
		return fetch(com.everhomes.server.schema.tables.EhVideoconfOrder.EH_VIDEOCONF_ORDER.BUY_CHANNEL, values);
	}

	/**
	 * Fetch records that have <code>create_time IN (values)</code>
	 */
	public java.util.List<com.everhomes.server.schema.tables.pojos.EhVideoconfOrder> fetchByCreateTime(java.sql.Timestamp... values) {
		return fetch(com.everhomes.server.schema.tables.EhVideoconfOrder.EH_VIDEOCONF_ORDER.CREATE_TIME, values);
	}
}
