package com.everhomes.rest.customer;

/**
 * Created by ying.xiong on 2017/8/15.
 */
public interface CustomerErrorCode {
    String SCOPE = "customer";

    int ERROR_CUSTOMER_NOT_EXIST = 10001;  //客户不存在
    int ERROR_CUSTOMER_TALENT_NOT_EXIST = 10002;  //客户人才不存在
    int ERROR_CUSTOMER_PROJECT_NOT_EXIST = 10003;  //客户申报项目不存在
    int ERROR_CUSTOMER_COMMERCIAL_NOT_EXIST = 10004;  //客户工商信息不存在
    int ERROR_CUSTOMER_PATENT_NOT_EXIST = 10005;  //客户专利不存在
    int ERROR_CUSTOMER_TRADEMARK_NOT_EXIST = 10006;  //客户商标不存在
    int ERROR_CUSTOMER_ECONOMIC_INDICATOR_NOT_EXIST = 10007;  //客户经济指标不存在
    int ERROR_CUSTOMER_INVESTMENT_NOT_EXIST = 10008;  //客户经济指标不存在
    int ERROR_CUSTOMER_CERTIFICATE_NOT_EXIST = 10009;  //客户证书不存在
    int ERROR_CUSTOMER_NAME_IS_NULL = 10010;  //客户名称为空
    int ERROR_CUSTOMER_CONTACT_IS_NULL = 10011;  //客户联系人为空
    int ERROR_CUSTOMER_CONTACT_MOBILE_IS_NULL = 10012;  //客户联系人手机号为空
    int ERROR_CUSTOMER_NAME_IS_EXIST = 10013;  //客户名称已存在
    int ERROR_CUSTOMER_CATEGORY_IS_NULL = 10014;  //客户类型不存在
    int ERROR_CUSTOMER_LEVEL_IS_NULL = 10015;  //客户级别不存在
    int ERROR_CUSTOMER_NUMBER_IS_EXIST = 10016;  //客户编号已存在
    int ERROR_CUSTOMER_TRACKING_NOT_EXIST = 10017;  //更近信息不存在
    int ERROR_CUSTOMER_HAS_CONTRACT = 10018;  //客户存在合同
    int ERROR_CUSTOMER_ACCOUNT_NOT_EXIST = 10019;  //客户银行账号不存在
    int ERROR_CUSTOMER_TAX_NOT_EXIST = 10020;  //客户税务信息不存在
    int ERROR_CUSTOMER_IMPORT_ERROR = 10021;  //客户税务信息不存在
    int ERROR_CUSTOMER_MANDATORY_ERROR = 10022;  //必填写未填写
    int ERROR_CUSTOMER_ITEM_ERROR = 10023;  //枚举类型找不到
    int ERROR_CUSTOMER_TRACKING_ERROR = 10024;  //跟进人格式错误
    int ERROR_CUSTOMER_UNKNOW_ERROR = 10025;  //未知格式错误
    int ERROR_CUSTOMER_ADMIN_FORMAT_ERROR = 10026;  //管理员格式错误
    int ERROR_CUSTOMER_ADDRESS_FORMAT_ERROR = 10027;  //楼栋门牌格式错误
    int ERROR_CUSTOMER_ADDRESS_NOT_EXIST_ERROR = 10028;  //楼栋门牌不存在
    int ERROR_CUSTOMER_NUM_FORMAT_ERROR = 10029;  //数字格式不对
    int ERROR_CUSTOMER_DATE_FORMAT_ERROR = 10030;  //日期格式不对
    int ERROR_CUSTOMER_TRACKING_USER_ERROR = 10031;  //跟进人找不到
    int ERROR_CUSTOMER_ADDRESS_ISNULL = 10032;  //地址参数未填写
    int ERROR_CUSTOMER_PRIVILGE_ERROR = 10033;  //线索客户操作权限不足
    int ERROR_CUSTOMER_ADDRESS_NOT_EXIST = 10034;  //openApi address 不存在
    int ERROR_CUSTOMER_HAS_REQUISITION = 10035; //客户存在请示单
    int ERROR_CUSTOMER_STATISTIC_DELETE_DATE = 10036;  //删除客户统计的时候日期不能为空
}
