#!/bin/bash
# chkconfig: 345 80 20

#set -x

EH_HOME=.
WAR=ehcore-0.0.1-SNAPSHOT.war

getpid() {
    local i
    for i in $(ps -ef | grep "ehcore$" | grep -v grep | awk '{print $2}')
    do
        echo $i
    done	
}

start() {
    local pid=$(getpid)
    if [ "$pid" != "" ]; then
        echo "Core server is already running with pid=$pid"
        return 0
    fi
    
    if [ ! -e $EH_HOME/$WAR ]; then
        echo "Core server is not properly installed"
        return 1
    fi
    
    echo -n "Starting Core server"
    
    rm -rf $EH_HOME/atomikos
    nohup java -jar $EH_HOME/$WAR --spring.config.name=ehcore > /dev/null &
    sleep 2
    pid=$(getpid)
    if [ "$pid" != "" ]; then
        echo " succeeded"
    else
        echo " failed"
    fi       
}

stop() {
    local pid=$(getpid)
    if [ "$pid" != "" ]; then
        echo -n "Stopping Core server"

        kill $pid >/dev/null 2>&1
        sleep 1
        
        pid=$(getpid)
        if [ "$pid" == "" ]; then
            echo " succeeded"
        else
            echo " failed"
        fi       
    else
        echo "Core server is already stopped"
    fi
}

status() {
    local pid=$(getpid)
    if [ "$pid" != "" ]; then
        echo "Core server is currently running with pid: $pid"
    else
        echo "Core server is not running"
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart}"
        exit 1
        ;;
esac

exit $?

